### ISSUE TITLE
Treesitter highlight not load

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1001]
### **Describe the bug**
suddenly after I updated the Nvchad, Treesitter highlights stopped working. I thought maybe it because my previous custom config _(before breaking change)_, so I decided to _remove all_ my nvim configuration directories (https://nvchad.github.io/getting-started/setup#uninstall) and reinstall Nvchad _but it's still the same_.

**_Keep in mind I don't have any additional plugins/configuration except as video below ⬇️_** 

### **To Reproduce**
none.

### **Expected behavior**
as we expected.

### **Video**

https://user-images.githubusercontent.com/73665622/166120791-2d013109-cbad-4748-963a-e35faee8f791.mp4

> Treesitter config file took from [`siduck/dotfiles/configs.lua`](https://github.com/siduck/dotfiles/blob/master/nvchad/custom/plugins/configs.lua)

### **Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Wezterm & Kitty
 - NVIM v0.7.0 Release

**Comment by GreatestOfAllTimee** [comment]
after a while, I managed to figure out what the cause was. Actually I don't know what `did_load_filetypes` &` do_filetype_lua` do but after remove that, it's back to normal.

https://github.com/NvChad/NvChad/blob/985217b93f9274d40c408ca26c6152cc5bcf8f0b/lua/core/options.lua#L4-L6

![highlight_workaround](https://user-images.githubusercontent.com/73665622/166127348-4956dd9f-5b2d-4da2-9023-586c49f8cdae.gif)

**Comment by siduck** [comment]
that file type lua should work if you're using v0.7

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/166127442-60987f5a-76fe-4ef3-903a-673f781bd4dc.mp4

deleted all nvim dirs and vanilla nvchad still works. Im unable to reproduce your error

**Comment by GreatestOfAllTimee** [comment]
> that file type lua should work if you're using v0.7

![Neovim_Version](https://user-images.githubusercontent.com/73665622/166128046-4a4dfdfc-883b-49b2-9d5a-20a3bb9b8875.gif)

#### Here are global statusline (only on Neovim v0.7+)

![Global_Statusline](https://user-images.githubusercontent.com/73665622/166128072-24e755bc-ba53-4e24-903b-8c3c0f5573a7.gif)

**Comment by GreatestOfAllTimee** [comment]
_maybe_ this is Neovim issue, I'm gonna find out.

**Comment by siduck** [comment]
> _maybe_ this is Neovim issue, I'm gonna find out.

looks like an issue from your side ._.

**Comment by GreatestOfAllTimee** [comment]
> > _maybe_ this is Neovim issue, I'm gonna find out.
> 
> looks like an issue from your side ._.

weird, how can that happen

**Comment by siduck** [comment]
> > > _maybe_ this is Neovim issue, I'm gonna find out.
> > 
> > 
> > looks like an issue from your side ._.
> 
> weird, how can that happen
> 
> Opps

i showed you a clean vanilla nvchad install as a proof! 

Things you can do is : 

```bash
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
```

Then clone nvchad repo

**Comment by GreatestOfAllTimee** [comment]
> i showed you a clean vanilla nvchad install as a proof!
> 
> Things you can do is :
> 
> ```shell
> rm -rf ~/.config/nvim
> rm -rf ~/.local/share/nvim
> rm -rf ~/.cache/nvim
> ```
> 
> Then clone nvchad repo

I dont want to be annoy or what, but I hope you get what I try to say https://github.com/NvChad/NvChad/issues/1001#issue-1221910383

**Comment by siduck** [comment]
hmm, Ive got no clue regarding this ;(

**Comment by GreatestOfAllTimee** [comment]
I think this issue is related to Neovim, I managed to fix it by building from source [`Neovim v0.7.1`](https://github.com/neovim/neovim/tree/release-0.7) _(maybe v0.7 might work as well )_. I believe in v0.7.1 they fixed major bugs from previous v0.7.0 releases and I guess this issue may be related to https://github.com/neovim/neovim/issues/18258

**Comment by GreatestOfAllTimee** [comment]
out of topic:
how do I spawn a new terminal on a new tab (like before using `<leader>w`?

**Comment by siduck** [comment]
> out of topic: how do I spawn a new terminal on a new tab (like before using `<leader>w`?

this feature is yet to be added, check nvterm's opened issue

**Comment by GreatestOfAllTimee** [comment]
how do I remap current terminal mapping?

**Comment by siduck** [comment]
> how do I remap current terminal mapping?
> 
> I didn't found any nvterm mapping on https://github.com/NvChad/NvChad/blob/main/lua/core/mappings.lua.

![image](https://user-images.githubusercontent.com/59060246/166153994-4ceb7607-5239-4be2-986a-11272f474004.png)

nvterm config, so now u need to override nvterm config in chadrc

**Comment by GreatestOfAllTimee** [comment]
under `plugins.options` or `options` table? both seems not working

![image](https://user-images.githubusercontent.com/73665622/166154348-14e47024-1dc1-4ca7-992f-0b1256d3a887.png)

**Comment by siduck** [comment]
override table in plugins 
![image](https://user-images.githubusercontent.com/59060246/166154458-71ee42c4-538d-4cd8-9397-557c77e3e876.png)

read our docs regarding how to override a plugin config. 

Also include the tables only in which u want the change, no need to include whole table , for example if i wanted to just change these highlights then : 

![image](https://user-images.githubusercontent.com/59060246/166154491-7331326c-be47-486d-9453-d917785c580c.png)

**Comment by GreatestOfAllTimee** [comment]
my mistake I'm confused. to much is going on nvchad.

Also, this seems like throw an error
https://github.com/NvChad/NvChad/blob/7123edf0efd6adb35b507c0f67c7cbc2891543c4/lua/core/mappings.lua#L57-L60

![image](https://user-images.githubusercontent.com/73665622/166155259-193fe57f-588c-4048-a243-c86f5aa4bd6e.png)

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-default-config-of-a-plugin

**Comment by siduck** [comment]
yes i saw that JK error today, please make an issue of it on nvterm repo so @zbirenbaum could have a track of it

**Comment by siduck** [comment]
I just realized that the mapping isnt NEEDED, lemme remove it!

**Comment by GreatestOfAllTimee** [comment]
That what I thought at first. JK already perform same as `<leader>x` so without make this complicated just remove it.
