### ISSUE TITLE
Error while exit file

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1002]
### **Describe the bug**
Error if exit file without save. I don't know how Nvchad handle exit file without save before.

### **To Reproduce**
1. edit any file
2. and close the file without save `<leader>x`
3. See error

### **Error output**
https://user-images.githubusercontent.com/73665622/166122447-5d3544ab-910e-483b-9e0a-a47c178bae4d.mp4

### **Expected behavior**
![nvchad_exit_error](https://user-images.githubusercontent.com/73665622/166121966-20f3e1be-7a3e-41ee-8630-c9a8ea44c2dc.gif) 

### **Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Wezterm & Kitty
 - NVIM v0.7.0 Release

**Comment by siduck** [comment]
in the expected behaviour what command do you get that save file prompt?

**Comment by siduck** [comment]
@GreatestOfAllTimee  know any way to find if current buffer's unsaved?
