### ISSUE TITLE
Remapping lsp-config hotkeys

### ISSUE THREAD

**Issue by primeapple** [NvChad/NvChad#1004]
**Is your feature request related to a problem? Please describe.**
In #994 we discuss a solution on how to override the default hotkeys for settings.
This is not so trivial for lsp-config. You would have to override the `config` function, which requires a deeper lua understanding.

**Describe the solution you'd like**
Maybe we could find a better alternative for changing the inbuilt mappings, alltogether? I honestly liked the previous approach where we could just override the default values in the `mappings` or `mappings.plugin` key in the chadrc itself.  
Atleast give an option to easily change the lsp mappings is a must have.

**Comment by siduck** [comment]
you dont need to have a deeper lua understanding for this  ._.

**Comment by siduck** [comment]
i will however think of an easier way

**Comment by primeapple** [comment]
> you dont need to have a deeper lua understanding for this ._.

What I meant is that you have to copy the `on_attach` function [here](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/lspconfig.lua#L5=) into your own config. So if there are ever changes on this function you will have to implement them on your own what is probably not what we want, right?

**Comment by siduck** [comment]
@ahhshm Ig this PR adds a lil complexity for many users https://github.com/NvChad/NvChad/pull/992

**Comment by siduck** [comment]
So i'll revert it

**Comment by primeapple** [comment]
It's easier now, still a better way would probably be to do it like before the "custom config removal discussion".
Lets hope this stands true:

> i will however think of an easier way

**Comment by roganartu** [comment]
Is this meant to work on current master? I have read the docs many times and still find myself unable to successfully override the `<leader>q` mapping that lspconfig sets. Are you able to provide a snippet that works for this?

eg adding this from the docs to `custom/init.lua` as instructed doesn't work for me:
```
local map = require("core.utils").map
map("n", "<leader>q", ":q <CR>")
```
Source: https://nvchad.github.io/config/Custom%20config#add-new-mappings.

I have also tried to do an `nvim-lspconfig` version of https://nvchad.github.io/config/Custom%20config#change-plugin-mappings which didn't work either.

If I delete the `<leader>q` mapping from `core.mappings` then both of the above options work fine.

**Comment by siduck** [comment]
@roganartu https://nvchad.github.io/config/Custom%20config#change-plugin-mappings

you need to put it lspconfig plugin, custom/init.lua can be used only for new mappings. To change default non plugin mappings put them in mappings,misc table and for plugin mappings , u need to modify their setup function as linked doc above. 

example : 

```lua 
map("n", "<leader>q", ":q <CR>")
map("n", "<leader>q", ":w <CR>")
```

So what will the leader q? it'll load :w  as that mapping overrides the above one, we do the same with our mappings to make them overridable by the user. Also i think leader q cant be mapped, I tried doing it and it does nothing but other key combinations do work

**Comment by roganartu** [comment]
@siduck I tried that, but unless I'm misunderstanding you it also didn't work.

> Also i think leader q cant be mapped, I tried doing it and it does nothing but other key combinations do work

I suspect we hit the same thing. In fact, I don't think anything defined in `core.mappings.lspconfig()` can be remapped, which is what I thought this issue was opened to address? The `lspconfig` attach calls `require("core.mappings").lspconfig()` which seems to override whatever you set in the plugin setup https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/lspconfig.lua#L15

I've tried overriding several of the `core.mappings.lspconfig()` mappings, and none of the overrides I set work, while others mapping set inside the same function do.

Here's a worked example:
```
❯ cat ~/.config/nvim/lua/custom/plugins/init.lua 
return {
  ["neovim/nvim-lspconfig"] = {
    setup = function()
      require("core.mappings").lspconfig()

      local map = require("core.utils").map

      -- These work
      map("n", "<leader>a", function()
       require("core.utils").close_buffer()
      end)
      map("n", "<leader>d", function()
       require("core.utils").close_buffer()
      end)

      -- These don't
      map("n", "<leader>q", function()
       require("core.utils").close_buffer()
      end)
      map("n", "<leader>D", function()
       require("core.utils").close_buffer()
      end)
    end,
  },
}
```
Both `<leader>a` and `<leader>d` close the buffer as expected, while `<leader>q` and `<leader>D` (both of which are mapped in `core.mappings.lspconfig()` don't. If I delete the `<leader>q` mapping from `core.mappings.lspconfig()` then the close buffer override starts working.

So, how do you remap things inside `core.mappings.lspconfig()`?

**Comment by siduck** [comment]
@roganartu im thinking about adding whichkey and define plugins in tables which could be easily overridable by the users so gimmie some time!

**Comment by roganartu** [comment]
Sure! Sorry if I came across as rude or impatient, I was just trying to make sure I wasn't misunderstanding anything. I think nvchad is awesome and I'm very keen on swapping out my current nvim config for it so thanks a lot for working on it :)
