### ISSUE TITLE
Local nvchad theme

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1008]
Allow user to add themes in custom/themes dir so they wouldnt bother to PR new themes every now and then.

**Comment by siduck** [comment]
fixed https://github.com/NvChad/nvim-base16.lua/commit/1db5a6eda8494edf724ec6e16f3286d7d26643b9

https://nvchad.github.io/config/Custom%20config#local-themes

**Comment by marko911** [comment]
Hey, why is there no option to add a custom theme locally ?

**Comment by siduck** [comment]
@marko91 https://nvchad.com/config/theming#local-themes
