### ISSUE TITLE
HELP NEEDED | Reloading themes on fly with telescope no longer works :(

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1009]
https://user-images.githubusercontent.com/59060246/166405471-74bbce8c-f809-406d-9237-6464c785f8e4.mp4

- as I re-wrote the base16 plugin and made it cleaner https://github.com/NvChad/nvim-base16.lua/commit/1db5a6eda8494edf724ec6e16f3286d7d26643b9 , Im not sure why the theme reloading on fly with out theme switcher doesnt work 

- reload_theme function in extensions repo that handles theme reloading 
https://github.com/NvChad/extensions/blob/main/lua/nvchad/reload_theme.lua#L19

- telescope theme  module
https://github.com/NvChad/extensions/blob/main/lua/telescope/_extensions/themes.lua

I've got no clue why's this happening, need someone to fix this issue ;(

**Comment by LeonHeidelbach** [comment]
@siduck from the little testing I did I found out that the function `reload_theme` is never called when scrolling through the list of themes. I won't have time to look at this today but maybe this helps.

**Comment by siduck** [comment]
> @siduck from the little testing I did I found out that the function `reload_theme` is never called when scrolling through the list of themes. I won't have time to look at this today but maybe this helps.

it was the same before

**Comment by siduck** [comment]
@LeonHeidelbach https://github.com/NvChad/extensions/blob/03b39322f1144570b1b6c21af5aaaec639568807/lua/telescope/_extensions/themes.lua#L55

**Comment by LeonHeidelbach** [comment]
@siduck I will have a look at this tomorrow if no-one fixes it in the meantime.

**Comment by siduck** [comment]
thanks :v

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach https://github.com/NvChad/extensions/blob/03b39322f1144570b1b6c21af5aaaec639568807/lua/telescope/_extensions/themes.lua#L55
> 
> https://github.com/NvChad/extensions/blob/03b39322f1144570b1b6c21af5aaaec639568807/lua/nvchad/reload_theme.lua

@siduck if you put some `vim.api.nvim_err_writeln("This should print an error")` calls anywhere in `reload_theme` nothing happenes. This leads me to believe that the trigger somehow got borked. I don't know why though.

**Comment by siduck** [comment]
@LeonHeidelbach 
![image](https://user-images.githubusercontent.com/59060246/166419999-c9083bab-e877-4626-8ff8-d997fb16640b.png)

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach
> ![image](https://user-images.githubusercontent.com/59060246/166419999-c9083bab-e877-4626-8ff8-d997fb16640b.png)

That's weird. Apparently the message did not print for me or was cut off while my terminal window was vertically longer than wide 👀. Now it worked for me as well. However, when clicking on any theme in the picker I got this, even though the "penokai" theme is not even in the list but it's set as my default theme:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/55194243/166420850-a9db351c-3938-4c0f-97ff-0263f900bd1e.png">

**Comment by LeonHeidelbach** [comment]
@siduck maybe this error "No such theme" gets cut off or is just not printed properly for some reason. Is it possible that you just have not adjusted the theme directory path anywhere?

**Comment by siduck** [comment]
did u do packersync?  if penokai is set in your chadrc then it'll show the no theme error

**Comment by siduck** [comment]
> Custom themes are not shown in picker 

cuz i didnt add its dir yet, first we need to fix the live theme reload issue.  however you can add custom/themes dir here 

https://github.com/NvChad/extensions/blob/main/lua/nvchad/init.lua#L74

**Comment by LeonHeidelbach** [comment]
> did u do packersync? if penokai is set in your chadrc then it'll show the no theme error

Yeah I did. And I still have it set as default in my chardrc's `M.ui` field.

> > Custom themes are not shown in picker
> 
> cuz i didnt add its dir yet, first we need to fix the live theme reload issue. however you can add custom/themes dir here
> 
> https://github.com/NvChad/extensions/blob/main/lua/nvchad/init.lua#L74

I also added the theme inside of the custom/themes dir. It's also properly loaded and works fine from there, no issues. Also very weird is that the bufferline plugin changes the theme when I scroll through the list, only the rest of the buffer stays the same.

**Comment by siduck** [comment]
ya bufferline and statusline plugin load on fly but not other highlights ;(

**Comment by LeonHeidelbach** [comment]
As I said I will have a closer look at it tomorrow 😁👍🏻

**Comment by siduck** [comment]
yea i'll wait :)

**Comment by LeonHeidelbach** [comment]
@siduck I found out that the entire theme switching logic is working properly. The problem is that it only ever switches to the same colors e.g. the new colors are not set properly before running [chadlights.lua](https://github.com/NvChad/base46/blob/master/lua/chadlights.lua). Still don't know why though.

**Comment by siduck** [comment]
@LeonHeidelbach I think if chadlights is loaded once then it if I require it once again, nothing changes. 

For example current theme's onedark 

so vim.g.nvchad_theme is onedark 

try 

let g:nvchad_theme = nord 

then the global variable will change.

Then require chadlights in cmdline, nothing happens :( 

- Chadlights loop through each file i.e files in integration folder. And each file in that folder, has a line on the top   loads the get_colors function 

- https://github.com/NvChad/base46/blob/master/lua/base16.lua#L6

**Comment by LeonHeidelbach** [comment]
@siduck to check that I have implemented some debug code that randomly replaces parts of the hex color string as you can see here when applying the new hightlights:

https://user-images.githubusercontent.com/55194243/166700447-00832646-62cf-4b17-9d23-568287f8480f.mp4

**Comment by siduck** [comment]
@LeonHeidelbach we will get new colors once the vim.g.nvchad_theme gets updated, then the get_color function takes the colors from "hl_themes." .. vim.g.nvchad_theme value :thinking:
