### ISSUE TITLE
Suggestion for cmp ui

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1010]
![image](https://user-images.githubusercontent.com/59060246/166452497-15a71cce-c2f5-44ca-a056-a63b3394764e.png)

or

![image](https://user-images.githubusercontent.com/59060246/166452327-3a5dfb5d-2499-488d-b363-4359e59e3277.png)

**Comment by siduck** [comment]
alright!

**Comment by LeonHeidelbach** [comment]
I always though cmp looked kinda dull without any color. But this looks really nice now.
