### ISSUE TITLE
lua autocommands

### ISSUE THREAD

**Issue by ahhshm** [NvChad/NvChad#1012]
auto-commands are still written in vimscript. @siduck Do you intend to rewrite them in Lua in the future? I wanted to do it myself but I thought maybe there is a reason you haven't done it yet.

**Comment by siduck** [comment]
we just have the autocmds but we dont use any autocmds, we just have them commented. I didnt write them in lua cuz idk about autocommands in lua

**Comment by ahhshm** [comment]
So do you want me to rewrite them?

**Comment by siduck** [comment]
ofcourse, idk why but i dont like vimscript :( , its good to have a pure 100% lua config lul

**Comment by ahhshm** [comment]
Who likes vimscript?

**Comment by siduck** [comment]
> Who likes vimscript?

u :rofl:

**Comment by siduck** [comment]
@ahhshm how can I write this in lua?
```
autocmd FileType alpha set laststatus=0 | autocmd BufUnload <buffer> set laststatus=3
```
This is for disabling statusline in dashboard

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/167620495-3a189645-81ad-4957-a611-15fe74be6d9b.png)

it works, is it correct?

**Comment by ahhshm** [comment]
The second one is a buffer local auto command:
```lua
autocmd("BufUnload", {
  buffer = 0,
  callback = function()
    vim.opt.laststatus = 3
  end, 
})
```

**Comment by siduck** [comment]
thx!
