### ISSUE TITLE
Installing nvchad using a different nvchad repository location on the file system.

### ISSUE THREAD

**Issue by jamesla** [NvChad/NvChad#1014]
I'm trying to install nvchad using the guide except I would like to clone the nvchad repository to a different location.

IE
```bash
git clone https://github.com/NvChad/NvChad ~/my-custom-location --depth 1
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
```

How can I provide a custom location for the nvchad repository so that when I run `nvim +'hi NormalFloat guibg=#1e222a' +PackerSync` it knows where to look?

**Comment by siduck** [comment]
i dont think that'll work, we just support  ~/.config/nvim for now. You could however add a PR to change the stdpath of config

**Comment by ahhshm** [comment]
I believe neovim only supports `~/.config/nvim` as its config path and we can't change it. However, you could clone NvChad in a different directory and symlink it to `~/.config/nvim`:
```sh
git clone https://github.com/NvChad/NvChad ~/my-custom-location --depth 1
ln -s ~/my-custom-location ~/.config/nvim
```

**Comment by siduck** [comment]
@ahhshm idk how lunarvim did it but they have their own dirs like ~/.config/lvim and ~/.local/share/lvim :thinking:

**Comment by ahhshm** [comment]
@siduck They do the same thing. they link `~/.config/lvim` to `~/.config/nvim` as you can see in the [lunarvim installer](https://github.com/LunarVim/LunarVim/blob/e1d32ca42ee6fdef8c724e3f391e548895f0bdcf/utils/installer/install.sh#L384):
```lua
function link_local_lvim() {
  echo "Linking local LunarVim repo"

  # Detect whether it's a symlink or a folder
  if [ -d "$LUNARVIM_BASE_DIR" ]; then
    echo "Removing old installation files"
    rm -rf "$LUNARVIM_BASE_DIR"
  fi

  echo "   - $BASEDIR -> $LUNARVIM_BASE_DIR"
  ln -s -f "$BASEDIR" "$LUNARVIM_BASE_DIR"
}
```

**Comment by siduck** [comment]
@ahhshm I doubt it, I was able to use nvchad and lunarvim at the same time, if lunarvim was linked to config/nvim then that wouldnt be possible. 

check

**Comment by ahhshm** [comment]
Yes, you are right. Their installer is complex and beyond my knowledge of bash scripting. I'm not sure how they do this but I can figure it out. just give me some time. looks like an interesting side project.

**Comment by siduck** [comment]
> Yes, you are right. Their installer is complex and beyond my knowledge of bash scripting. I'm not sure how they do this but I can figure it out. just give me some time. looks like an interesting side project.

ya its not needed, we had a bloated installer before too but I removed it xD. It added 1% shell info. Im glad its just 100% lua here now

![image](https://user-images.githubusercontent.com/59060246/166637115-db1b3050-36cc-445a-b0c4-220952947eab.png)

**Comment by ahhshm** [comment]
> Im glad its just 100% lua here now
It's beautiful

**Comment by jamesla** [comment]
> @jamesla I believe neovim only supports `~/.config/nvim` as its config path and we can't change it. However, you could clone NvChad in a different directory and symlink it to `~/.config/nvim`:
> 
> ```shell
> git clone https://github.com/NvChad/NvChad ~/my-custom-location --depth 1
> ln -s ~/my-custom-location ~/.config/nvim
> ```

unfortunately i'm trying to write a nixos package so this won't work

**Comment by jamesla** [comment]
nvim supports `XDG_CONFIG_HOME` and `XDG_DATA_HOME` so possibly this will work using the XDG mechanism? Or are we talking actually hardcoded values in the lua installer for nvchad?

**Comment by ahhshm** [comment]
> nvim supports XDG_CONFIG_HOME and XDG_DATA_HOME so possibly this will work using the XDG mechanism?

Unfortunately, I don't know much about XDG or nixos so I can't help you.

> Or are we talking actually hardcoded values in the lua installer for nvchad?

NvChad is just some neovim configuration files. You can put them anywhere neovim can read it. 

This issue is more related to neovim than nvchad. You probably can get more help in the [neovim forum](https://neovim.discourse.group/)

**Comment by siduck** [comment]
> @siduck @ahhshm nvim supports `XDG_CONFIG_HOME` and `XDG_DATA_HOME` so possibly this will work using the XDG mechanism? Or are we talking actually hardcoded values in the lua installer for nvchad?

I'm not sure about xdg but nvchad works only with ~/.config/nvim for now, you can however implement a PR to make it use ~/.config/nvchad and so on.idk how to do it tho

**Comment by tomasky** [comment]
Just like this, my config is working:

nvim nvi

```bash
rootdir=/root/nvchad
export XDG_CONFIG_HOME=$rootdir
export XDG_DATA_HOME=$rootdir/share
nvim $*
```
chmod +x nvi

**Comment by siduck** [comment]
cool, Idk XDG stuff so wasnt able to help. @jamesla check the above comment

**Comment by jamesla** [comment]
cheers @siduck @tomasky @ahhshm

**Comment by vricop** [comment]
> 

Is the `nvim` part, at the end needed in order for it work?
`root/nvchad/nvim`

**Comment by vricop** [comment]
> cheers @siduck @tomasky @ahhshm

Did you make it work?

**Comment by vricop** [comment]
@jamesla Did you make it work?
