### ISSUE TITLE
Custom snippets paths broken

### ISSUE THREAD

**Issue by fullstopslash** [NvChad/NvChad#1015]
**Describe the bug**

**To Reproduce**
Updated Nvchad while using this setting in chadrc.lua
```
options = {
      luasnip = {
         snippet_path = { "$HOME/.config/snippets" },
      },
```

**Expected behavior**
For it to load custom snippets.

**Comment by siduck** [comment]
check the pinned issue, a lot has changed. i have removed that option. Now you can just override luasnip config

**Comment by danjenson** [comment]
damn, came here for this
