### ISSUE TITLE
Completion menu overwrites text being entered

### ISSUE THREAD

**Issue by mcctuxic** [NvChad/NvChad#1016]
**Describe the bug**
Entering text starts the completion menu, which overwrites the text being entered

**To Reproduce**
Start nvim, enter text.

**Expected behavior**
The completion menu should stay out of my way - that is: above or below the text being entered.

**Screenshots**
![MenuClash](https://user-images.githubusercontent.com/30279786/166622204-e9337bd1-9524-43f8-902b-fc73cb145e2f.png)
I wrote "Hallo NVChad" starting at column 0.

**Desktop (please complete the following information):**
 - Operating System: GENTOO Linux - updated this morning (04-05-2022)
 - Terminal: Wezterm (wezterm 20220427-144728-efcc4b48)
 - Version of Neovim: NVIM v0.8.0-dev+124-g815b65d77

**Additional context**
Nvim/NVChad has worked with wezterm yesterday. The update of NVChad and/or the plugins (done this morning) broke
the whole thing. Currently I am not able to edit anything...

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/166623024-f45bf208-8d38-417f-983e-66bb11818e84.png)

unable to reproduce this. Also please use 0.7

**Comment by siduck** [comment]
tried using wezterm, I dont face this issue 
![image](https://user-images.githubusercontent.com/59060246/166623169-ecc442e2-ee32-411e-bc33-6eb421fdfcad.png)

**Comment by mcctuxic** [comment]
Ok, thanks for testing - I will search for another solution.

**Comment by siduck** [comment]
This might be related https://github.com/NvChad/NvChad/issues/882#issuecomment-1080569162

**Comment by siduck** [comment]
Do you still face this issue?  can you try it without tmux

**Comment by RaulSanchezzt** [comment]
Hi, I have the same problem, I reinstalled NvChad and I have the latest Nvim version. I'm currently using the default NvChad configuration in Gnome-Terminal - Kali Linux. I don't know what can cause this error.
![Screenshot_20220505_195313](https://user-images.githubusercontent.com/96440745/166983534-e865450f-9b7a-4c91-a689-3b23ca226e59.png)

**Comment by siduck** [comment]
also please use v0.7 and from the release page

**Comment by RaulSanchezzt** [comment]
Hi, to solve the problem I am going to use kitty from now on. Thanks for your time

**Comment by siduck** [comment]
@RaulSanchezzt you may check my st build  https://github.com/siduck/st
