### ISSUE TITLE
Update lspconfig client.resolved_capabilities

### ISSUE THREAD

**Issue by kmiasko** [NvChad/NvChad#1018]
**Describe the bug**

There is a warning in messages suggesting to update lspconfig config (resolved_capabilities will be removed in nvim 0.8).

`[LSP] Accessing client.resolved_capabilities is deprecated, update your plugins or configuration to access client.server_capabilities instead.The new key/value pairs in server_capabilities directly match those defined in the language server protocol`

**Comment by bryant-the-coder** [comment]
Use nvim 0.7 for now

**Comment by siduck** [comment]
Nvchad supports latest stable version which is 0.7 so use it for now! When 0.8 gets released, I'll make it compatible
