### ISSUE TITLE
LSP not working with LSP server installed from LSPInstall

### ISSUE THREAD

**Issue by sherlock1453** [NvChad/NvChad#1020]
I have added the williamboman/nvim-lsp-installer in the chadrc.lua (attached below).
Installed LSP server for java (jdtls) and javascript(eslint) using :LspInstall. No errors, servers were installed successfully.
Followed the docs from [here](https://nvchad.github.io/config/Lsp%20stuff) and the bit about setting up LspInstall (lspconfig.lua attached below).
When I open a java or javascript file the expected behavior is LSP client should attach to the buffer, but the actual behavior is that when I do :LspInfo I get 0 clients attached to this buffer and LSP does not work as expected.

There is a 90% chance that I'm doing something wrong in the setup and that this is not an issue with the NvChad itself, but I can't find anything in the Lsp logs or the lsp installer logs to suggest that.

Nvim version: 0.7

chadrc.lua
`-- Just an example, supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.plugins = {
  options = {
    lspconfig = {
      setup_lspconf = "custom.plugins.lspconfig"
    }
  },
  user = {
    ["williamboman/nvim-lsp-installer"] = {
      config = function()
        require("nvim-lsp-installer").setup{
          autostart = true
        }
--        local lspconfig = require("lspconfig")
--        lspconfig.sumneko_lua.setup{
--          autostart = true
--        }
      end,
    }
  }
}

M.ui = {
   theme = "chadracula",
}

return M`

`local M = {}

M.setup_lsp = function(attach, capabilities)
  local lsp_installer = require "nvim-lsp-installer"

  lsp_installer.on_server_ready(function(server)
    local opts = {
      on_attach = attach,
      capabilities = capabilities,
      settings = {},
    }

    server:setup(opts)
    vim.cmd [[ do User LspAttachBuffers ]]
  end)
end

return M`

**Comment by siduck** [comment]
Sorry that's the outdated lsp config, you need to configure lsp with lspconfig only
