### ISSUE TITLE
Highlighting for conceal is broken

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1023]
Before, my syntax was replaced with unicode characters, but now it is just highlight blobs:
![image](https://user-images.githubusercontent.com/4793438/166809642-2ccb6103-d86f-4e96-a797-12f9353950d8.png)
![image](https://user-images.githubusercontent.com/4793438/166809673-eb73f0eb-ff19-4fc1-bf51-4386de5161bd.png)
Every theme I've tried does the same thing.

**Comment by danjenson** [comment]
This seems to be fixed by `hi Conceal guibg=None`

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-default-highlights
