### ISSUE TITLE
Theme switcher doesnt reload bufferline & web-devicons colors 

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1025]
https://user-images.githubusercontent.com/59060246/166912224-44a7b81c-2dcb-4854-bda5-54c038019ae2.mp4

 @Akianonymus 
 
 shouldnt this work?
 
 
![image](https://user-images.githubusercontent.com/59060246/166912332-cec3480f-9013-4418-88bb-b66cd13aca5f.png)

**Comment by bryant-the-coder** [comment]
mayb try closing nvim-tree and reopening it?

**Comment by siduck** [comment]
did, doesnt work

**Comment by Akianonymus** [comment]
> simplescreenrecorder-2022-05-05_16.42.37.mp4
> 
> @Akianonymus
> 
> shouldnt this work?
> 
> ![image](https://user-images.githubusercontent.com/59060246/166912332-cec3480f-9013-4418-88bb-b66cd13aca5f.png)

ooh when did this happen, have to see old code on how to tackle this.

**Comment by siduck** [comment]
> > simplescreenrecorder-2022-05-05_16.42.37.mp4
> > @Akianonymus
> > shouldnt this work?
> > ![image](https://user-images.githubusercontent.com/59060246/166912332-cec3480f-9013-4418-88bb-b66cd13aca5f.png)
> 
> ooh when did this happen, have to see old code on how to tackle this.

https://github.com/NvChad/base46/commit/1db5a6eda8494edf724ec6e16f3286d7d26643b9

**Comment by siduck** [comment]
both bufferline & web-devicons highlight colors are defined in their setup which seems sus :thinking: 

![image](https://user-images.githubusercontent.com/59060246/166918747-ab4edc71-44ec-4b25-8927-ef5186f3d7d5.png)

**Comment by siduck** [comment]
even feline has colors for its highlights defined in its config 
![image](https://user-images.githubusercontent.com/59060246/166919126-1d8b316a-1954-4eb6-b7b4-a6adeb3da2dc.png)
 
 but it reloads properly

**Comment by siduck** [comment]
ig this is related https://github.com/NvChad/extensions/blob/main/lua/nvchad/reload_theme.lua#L22

**Comment by Akianonymus** [comment]
I looked around, bufferline reloads when :colorscheme some_theme is applied.

So, when making our themes appear in :colorscheme

**Comment by siduck** [comment]
> I looked around, bufferline reloads when :colorscheme some_theme is applied.
> 
> So, when making our themes appear in :colorscheme

i didnt see bufferline reloading when thats applied, weird

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/166938961-9b150636-815a-49f5-9f0a-1da002752e00.mp4

**Comment by Akianonymus** [comment]
> 

First change the theme with theme switcher, then use the colorscheme command.

**Comment by siduck** [comment]
doesnt work here ._.

**Comment by Akianonymus** [comment]
> tried, doesnt work here ._.


https://user-images.githubusercontent.com/32216346/166950076-73e4e806-b986-4b0a-bd73-5f0c0e0b8412.mp4

**Comment by siduck** [comment]
or bufferline does  it, probably this https://github.com/akinsho/bufferline.nvim/commit/b9b91a879e0d5d5d42aecd58bc0e25dc8a214bb3

**Comment by Akianonymus** [comment]
> oh, btw how did you get pmenu look like that? I hope thats not cmp cmdline plugin

It is cmp cmdline plugin. What do you mean by i hope that not .....

**Comment by Akianonymus** [comment]
> or bufferline does it, probably this [akinsho/bufferline.nvim@b9b91a8](https://github.com/akinsho/bufferline.nvim/commit/b9b91a879e0d5d5d42aecd58bc0e25dc8a214bb3)

Maybe we should just create a issue, author can probably guide us clearly as i have no clue on how to flawlessly do it.
