### ISSUE TITLE
module 'cmp' not found, while install

### ISSUE THREAD

**Issue by carrotfarmer** [NvChad/NvChad#1029]
**Describe the bug**
While following https://nvchad.github.io/getting-started/setup, I ran into an error
```
Error detected while processing /Users/dhruvasrinivas/.local/share/nvim/site/pack/packer/start/cmp-cmdline/after/plugin/cmp_
cmdline.lua:
E5113: Error while calling lua chunk: ...ck/packer/start/cmp-cmdline/after/plugin/cmp_cmdline.lua:1: module 'cmp' not found:

        no field package.preload['cmp']
        no file './cmp.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp/init.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/cmp.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/cmp/init.lua'
        no file './cmp.so'
        no file '/usr/local/lib/lua/5.1/cmp.so'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/cmp.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...ck/packer/start/cmp-cmdline/after/plugin/cmp_cmdline.lua:1: in main chunk
```

**To Reproduce**
```
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
```

**Expected behavior**
Install runs successfully

**Screenshots**
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/66675022/167074147-67e35a27-63ad-431d-9046-e761765f9448.png">
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/66675022/167074176-95fb210f-3b8b-4b0c-891a-744959b8cfce.png">

**Desktop (please complete the following information):**
 - macOS Monterey 12.1
 - Kitty 0.25.0
 - Nvim 0.7.0

**Additional context**
N/A

**Comment by siduck** [comment]
are you trying to install cmdline plugin or install nvchad?

**Comment by carrotfarmer** [comment]
nvchad @siduck

**Comment by siduck** [comment]
then why will you have the cmdline error?

**Comment by carrotfarmer** [comment]
Idk, I just ran the Setup commands and ran into this error

**Comment by carrotfarmer** [comment]
These commands
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/66675022/167076992-21f596fc-d1a5-4e3d-958c-00713a0571f7.png">

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/167077197-d9ba9373-ed55-457d-ad14-c2bab9e46db0.mp4

works fine here

**Comment by siduck** [comment]
show nvim -v

**Comment by carrotfarmer** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/66675022/167077299-f8d58cc0-145e-48d4-8dcb-0336b2684dcf.png">

**Comment by carrotfarmer** [comment]
Ok weird lmao, after I removed the nvim cache, the install worked. Thanks!
