### ISSUE TITLE
luasnip-expand-or-jump error

### ISSUE THREAD

**Issue by ericwq** [NvChad/NvChad#1030]
**Describe the bug**
in neovim command mode, type ":Ls", then type tab key, you should get a hint list while i got a luasnip-expand-or-jump error. see bellow.

**To Reproduce**
1. Go to command mode
2. type ":Ls"
3. type tab key
<img width="434" alt="Screen Shot 2022-05-06 at 13 29 53" src="https://user-images.githubusercontent.com/1501146/167076865-fe30abd2-e410-4d1b-858d-1a3b64d09cf3.png">

**Expected behavior**
<img width="229" alt="Screen Shot 2022-05-06 at 13 29 41" src="https://user-images.githubusercontent.com/1501146/167076703-fa3759dc-5fb5-42ae-8fcd-6e867e49338f.png">

**Desktop (please complete the following information):**
 - macOS Monterey 12.3.1 
 - Alacritty 0.10.1
 - Version of Neovim 0.7.0

**Additional context**

**Comment by siduck** [comment]
this is weird 
![image](https://user-images.githubusercontent.com/59060246/167077486-d9b4d0fd-9f2c-48b6-8cb1-6f6f18201df5.png)


Show nvim -v

**Comment by siduck** [comment]
macos users surely get weird issues! https://github.com/NvChad/NvChad/issues/1029

**Comment by ericwq** [comment]
2 days ago, it's works as usual.

nvim -v shows
```
$ nvim -v
NVIM v0.7.0
Build type: MinSizeRel
LuaJIT 2.1.0-beta3
Compiled by buildozer@build-edge-x86_64

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck** [comment]
weird, i cant reproduce this issue

**Comment by siduck** [comment]
did u try this release https://github.com/neovim/neovim/releases/tag/v0.7.0

**Comment by ericwq** [comment]
I solved this issue. It's my configuration problem.

- I already have a `lua server` in custom directory. So I remove it from custom directory since `NvChad` already provide one.
- I disabled the automatic LSP installer.

```lua
M.lspinstaller = {
       automatic_installation = false,
}
```
Now the issue disappear.
