### ISSUE TITLE
After calling telescope, tab autocompletion does not work in the tabline anymore

### ISSUE THREAD

**Issue by mihneaCR** [NvChad/NvChad#1031]
**Describe the bug**
After calling telescope (for example oldfiles), the autocompletion of paths using tab does not work anymore (.con should expand to .config when pressing tab), instead tab is replaced by ^I.

**To Reproduce**
1. Open NvChad
2. Try completing a path, for example .con, then press tab to expand it to .config/ correctly.
3. Now call telescope oldfiles via SPC f o, and exit the window using escape
4. Now when trying to expand .con to .config, you get .con^I
![nvchad_tab_after](https://user-images.githubusercontent.com/47532611/167100196-8e364a5c-a816-454a-ac4d-2cdca70b5c69.png)

**Expected behavior**
It should expand to .config/, as before calling telescope oldfiles

**Screenshots**

**Desktop (please complete the following information):**
 - Arch 5.17.5-arch1-1
 - Alacritty, or Neovide (GUI client)
 - NVIM 0.7.0

**Additional context**
![nvchad_cmap_before](https://user-images.githubusercontent.com/47532611/167099991-0640622b-fb2f-4f28-940d-b97975821a4d.png)
Before calling telescope, :cmap <tab> shows:
![nvchad_cmap_result](https://user-images.githubusercontent.com/47532611/167100090-2847bfd5-2c04-478d-a58e-1c65d7e9c1bc.png)
After calling telescope oldfiles, :cmap shows:
![nvchad_cmap_after](https://user-images.githubusercontent.com/47532611/167100047-14014d60-352d-482c-b8cc-56e5e2d8bf5d.png)

Note: This happens for me without any modification of the default config, and with the newest plugin updates obtained via PackerSync. I assume this behavior stems from a recent plugin update, i can not verify this however.

**Comment by siduck** [comment]
oh i tried lunarvim and it works, idk whats causing this!

**Comment by mihneaCR** [comment]
Update: Using following config:
return require('packer').startup(function()
        use 'wbthomason/packer.nvim'
        use 'nvim-lua/plenary.nvim'
        use 'nvim-telescope/telescope.nvim'
end)
in init.lua, this issue does not occur. Maybe this has something to do with another plugin. I am not very good with lua however, maybe someone else has another idea for how to debug this.

**Comment by mihneaCR** [comment]
> yes I can reproduce this issue. I meant to try a bare neovim config with only telescope installed

Update: Using following config:
return require('packer').startup(function()
use 'wbthomason/packer.nvim'
use 'nvim-lua/plenary.nvim'
use 'nvim-telescope/telescope.nvim'
end)
in init.lua, this issue does not occur. Maybe this has something to do with another plugin. I am not very good with lua however, maybe someone else has another idea for how to debug this.

**Comment by mihneaCR** [comment]
> @mihneaCR send a PR reverting it :v

done!
