### ISSUE TITLE
When i press Tab in VIM Command become character

### ISSUE THREAD

**Issue by ayatmaulana** [NvChad/NvChad#1032]
**Describe the bug**
Hey look, when I want to use the vim command there is a problem that the Tab becomes character like this

**To Reproduce**
1. Open some file
2. Please type any and use lsp recommendation
3. Try any vim command eg: `:Ls *then press Tab`

**Expected behavior**

**Screenshots**
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/20509355/167115591-c2f39a72-ec8f-41d5-9055-f15bf3f95c80.png">

**Desktop (please complete the following information):**
 - Macos Montery (M1)
 - Alacritty Terminal
 - 0.7.0
 
```shell
❯ nvim -version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

**Additional context**
I also try in my ArchLinux and got same error

**Comment by siduck** [comment]
duplicate! #1031
