### ISSUE TITLE
Prompt users to :PackerSync immediately after update if necessary

### ISSUE THREAD

**Issue by LeonHeidelbach** [NvChad/NvChad#1033]
Since a lot of changes to NvChad require a subsequent `:PackerSync` I would suggest to implement a feature into the updater that scans for a new keyword in commit messages (same as with breaking changes - e.g. "PS REQUIRED" or similar, @siduck would have to decide on the exact terminology) that would prompt the user to `PackerSync` right after the update without having to manually type in the command (users would still be able to decide not to `PackerSync` though). I see @siduck commenting `PackerSync` on a lot of commits and some users having issues just because they did not do it and this would help to mitigate those issues. I would implement the feature myself and wanted to get some feedback + input on whether or not this is something you would like me to add.

If you think this is a good idea and want me to add this just react with 👍, if not 👎.

**Comment by siduck** [comment]
@LeonHeidelbach no need to ask for suggestions, this is a must thing. Whenever I make any theme /extensions related change in nvchad config, a packersync is needed to update those plugins. Add a pr for this!

**Comment by LeonHeidelbach** [comment]
@siduck Done https://github.com/NvChad/extensions/pull/20
