### ISSUE TITLE
Custom themes not available through theme switcher & toggle button

### ISSUE THREAD

**Issue by LeonHeidelbach** [NvChad/NvChad#1036]
**Describe the bug**
Themes from the custom theme dir are not listed in the theme switcher. When closing out of the theme switcher without selecting a new theme, while having a custom theme set as default in `chadrc` it fails to reset to the custom theme. This also affects the theme toggle button. I know we have talked about this before @siduck in https://github.com/NvChad/NvChad/issues/1009#issuecomment-1115836618. I could implement this, but since this is your domain I'll let you have the pleasure :smile:. This issue is only supposed to be a quick reminder.

**To Reproduce**
1. Set a custom theme as default in `chadrc`
2. Reopen nvim, the custom theme loads as expected and works properly
3. Open the theme selector `<leader>th`, and immediately exit out of it using `<ESC>`
4. You will be prompted with `No such theme (  <YOUR_CUSTOM_THEME_NAME> )`
5. The same happens when using the theme toggle button

**Expected behavior**
Custom themes sould be merged into the themes table so that they can be reapplied on the fly through the theme selector as well as the toggle button.

**Comment by siduck** [comment]
lemme try!

**Comment by siduck** [comment]
@LeonHeidelbach to set toggle button themes you need to set them in chadrc and make sure your current theme is listed in toggle theme table soo if current theme is nord then 

toggle_theme = {"nord", "onedark"}

**Comment by siduck** [comment]
@LeonHeidelbach it'll list custom themes too now BUT! i face another bug. 

Whenever i select themes, i dont get the prompt ( Y / N ) and the theme doesnt change at all

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/167252334-0fcde23e-d3bc-49a6-a305-b2f604942956.mp4

This is the last theme bug we have XD!  for real!

**Comment by siduck** [comment]
nvm its fixed :lessssssssssssssssssssssssgooooooooooooooooooooooooooo:

**Comment by siduck** [comment]
and this was the fix https://github.com/NvChad/extensions/commit/0b9de25f5522e0d810bf93ade618335c96b97011 :laughing: :rofl:

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach to set toggle button themes you need to set them in chadrc and make sure your current theme is listed in toggle theme table soo if current theme is nord then
> 
> toggle_theme = {"nord", "onedark"}

I was gonna say - I done that :laughing:

https://user-images.githubusercontent.com/55194243/167252713-7027763e-dad1-439b-9d9a-714e79df6c58.mp4

> and this was the fix [NvChad/extensions@0b9de25](https://github.com/NvChad/extensions/commit/0b9de25f5522e0d810bf93ade618335c96b97011) laughing rofl

Nice one :laughing: :+1:

**Comment by LeonHeidelbach** [comment]
@siduck Just tried it myself, everything works like a charm now :+1:

**Comment by siduck** [comment]
this thing looks ugly, why do you use it :thinking: 
![image](https://user-images.githubusercontent.com/59060246/167253016-5b5b78c2-1799-4d3e-95ea-40a8bdb48ee3.png)

**Comment by LeonHeidelbach** [comment]
> this thing looks ugly, why do you use it thinking ![image](https://user-images.githubusercontent.com/59060246/167253016-5b5b78c2-1799-4d3e-95ea-40a8bdb48ee3.png)

Oi, u hatin on my setup :rofl: this is my column indicator. It marks the 100th char in the line. We have projects that have specific guidelines and "no more than 100 chars per line" is one of them :wink:. Makes the code more easily readable for people with smaller screens or in tiny terminal windows.
