### ISSUE TITLE
Install for the first time nvchad

### ISSUE THREAD

**Issue by ConanEdogawa1** [NvChad/NvChad#1043]
✗ Failed to update feline-nvim/feline.nvim                                         
           │  Errors:                                                                           
           │    fatal: refusing to merge unrelated histories                                    
           │    e54e0cc                                                                         
           │ ✗ Failed to update akinsho/bufferline.nvim                                        
           │  Errors:                                                                           
           │    fatal: unable to access 'https://github.com/akinsho/bufferline.nvim.git/': Libre│
           │    17efb4c

**Comment by siduck** [comment]
can you make sure that your internet is well?

**Comment by ConanEdogawa1** [comment]
> can you make sure that your internet is well?

Yes, the network is fine. Other plugins are installed correctly

**Comment by siduck** [comment]
> > can you make sure that your internet is well?
> 
> Yes, the network is fine. Other plugins are installed correctly

is this your first time installing nvchad?

**Comment by ConanEdogawa1** [comment]
> is this your first time installing nvchad?

yes

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/167303031-bb5f7b40-46bd-4087-b253-589fff1f4c6b.mp4

cant reproduce it

**Comment by ConanEdogawa1** [comment]
> simplescreenrecorder-2022-05-08_20.47.06.mp4 
> cant reproduce it, btw your pfp looks inappropriate. I'd suggest you to change it. Doesnt fit as appropriate for a github profile

Thank you ! Let me try

**Comment by boonkerz** [comment]
![image](https://user-images.githubusercontent.com/277321/167311531-8e60a8dd-c7dd-4f13-93c2-ca9711a523a7.png)

**Comment by siduck** [comment]
this is very weird

**Comment by tomasky** [comment]
Do you use a github url proxy  in china ? I suggest you change it and try again or  
```bash
:PackerSync feline.nvim
:PackerSync bufferline.nvim
```

**Comment by nzlov** [comment]
> ![image](https://user-images.githubusercontent.com/277321/167311531-8e60a8dd-c7dd-4f13-93c2-ca9711a523a7.png)

Change 'custom/plugins/init.lua' like:
```
return { 
  {
     'hrsh7th/nvim-cmp',
     config = function()
        require "custom.plugins.cmp"
     end,
  },
}
```
To:
```
return { 
    ["hrsh7th/nvim-cmp"] = {
     config = function()
        require "custom.plugins.cmp"
     end,
  }, 
}
```

**Comment by boonkerz** [comment]
My init.lua currently
```
return {
  { "/home/thomas/projekte/himalaya/vim" },
  { "ray-x/lsp_signature.nvim" },
  [ "weilbith/nvim-code-action-menu"] = {
    cmd = {
      'CodeActionMenu'
    }
  } 
}
```

**Comment by ConanEdogawa1** [comment]
> > simplescreenrecorder-2022-05-08_20.47.06.mp4
> > 无法重现，顺便说一句，您的 pfp 看起来不合适。我建议你改变它。不适合 github 个人资料
> 
> 谢谢 ！让我尝试

what is pfp

**Comment by ConanEdogawa1** [comment]
> 你在中国使用 github url 代理吗？我建议你改变它，然后再试一次，或者
> 
> ```shell
> :PackerSync feline.nvim
> :PackerSync bufferline.nvim
> ```

A proxy is used, and other checks have been installed successfully. There are two exceptions

**Comment by ConanEdogawa1** [comment]
> 我的 init.lua 目前
> 
> ```
> return {
>   { "/home/thomas/projekte/himalaya/vim" },
>   { "ray-x/lsp_signature.nvim" },
>   [ "weilbith/nvim-code-action-menu"] = {
>     cmd = {
>       'CodeActionMenu'
>     }
>   } 
> }
> ```
> 
> 好的，我已经修复了我的 lua :)
> 
> ```
> return {
>   [ "ray-x/lsp_signature.nvim" ] = {
>       config = function ()
>         require "lsp_signature" 
>       end
>   },
>   [ "weilbith/nvim-code-action-menu"] = {
>     cmd = {
>       'CodeActionMenu'
>     }
>   } 
> }
> ```

OK！Thank You

**Comment by ConanEdogawa1** [comment]
![image](https://user-images.githubusercontent.com/49578735/167398463-55581627-a562-4e69-9f71-c3b43a39088d.png)

**Comment by siduck** [comment]
> ![image](https://user-images.githubusercontent.com/49578735/167398463-55581627-a562-4e69-9f71-c3b43a39088d.png)


rm -rf .local/share/nvim and open nvim, do a packersync

**Comment by ConanEdogawa1** [comment]
> > ![image](https://user-images.githubusercontent.com/49578735/167398463-55581627-a562-4e69-9f71-c3b43a39088d.png)
> 
> rm -rf .local/share/nvim and open nvim, do a packersync

Thank you, it has been installed successfully

**Comment by ConanEdogawa1** [comment]
Thanks for your help guys
