### ISSUE TITLE
Basic NvChad Lsp setup after breaking changes --- `0 client(s) attached to this buffer`

### ISSUE THREAD

**Issue by erwin** [NvChad/NvChad#1044]
**Describe the bug**
Using the latest NvChad, Unable to get `Lsp` to activate for any language servers. Lsp worked fine for me with earlier versions of NvChad...
When running `:LspInfo`

I'm trying to run EXACTLY what Siduck has currently published in [his dotfiles](https://github.com/siduck/dotfiles), but unfortunately even that config verbatim does not work for me.

```
Language client log: /home/erwin/.cache/nvim/lsp.log                                   
Detected filetype:                                                                    
                                                                                                 
0 client(s) attached to this buffer:                                                  
Configured servers list: zk, cssls, html, clangd, solargraph, sumneko_lua, gopls, bashls
```

**To Reproduce**

```
nvim -v
# NVIM v0.7.0
mv ~/.config/nvim ~/.config/nvim.orig
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
git clone https://github.com/siduck/dotfiles ~/.config/siduck
ln -s ~/.config/siduck/nvchad/custom ~/.config/nvim/lua/custom
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
```

<details>
<summary> `tree -l ~/.config/nvim` </summary>

```
❯ tree -l ~/.config/nvim
/home/ryan/.config/nvim
├── examples/
│   ├── chadrc.lua
│   └── init.lua
├── init.lua
├── LICENSE
└── lua/
    ├── core/
    │   ├── autocmds.lua
    │   ├── default_config.lua
    │   ├── mappings.lua
    │   ├── options.lua
    │   └── utils.lua
    ├── custom -> /home/ryan/.config/siduck/nvchad/custom/
    │   ├── chadrc.lua
    │   ├── init.lua
    │   ├── mappings.lua
    │   └── plugins/
    │       ├── configs.lua
    │       ├── init.lua
    │       ├── lspconfig.lua
    │       ├── null-ls.lua
    │       └── truezen.lua
    └── plugins/
        ├── configs/
        │   ├── alpha.lua
        │   ├── bufferline.lua
        │   ├── cmp.lua
        │   ├── icons.lua
        │   ├── lspconfig.lua
        │   ├── lsp_installer.lua
        │   ├── lspkind_icons.lua
        │   ├── nvimtree.lua
        │   ├── nvterm.lua
        │   ├── others.lua
        │   ├── statusline.lua
        │   ├── telescope.lua
        │   └── treesitter.lua
        ├── init.lua
        └── packerInit.lua

7 directories, 32 files
```
</details>

**Expected behavior**
I expect `clangd` and other language servers to attach to the buffer for `.c` files and other language servers for other files...

Unfortunately, I always get `0 client(s) attached to this buffer:` when checking `:LspInfo`

![image](https://user-images.githubusercontent.com/11534217/167334122-0ac9bf96-5e9d-49ea-bfcb-d6814ba1cbfa.png)

**Desktop (please complete the following information):**
- Kubuntu 21.10 x86_64
- Kitty
- Neovim 0.7.0

Would be interesting to survey `NvChad` users and ask how many do not use `Lsp`... If almost everyone is a Lsp user, maybe would be good to include that stuff by default and just make it easy to customize in `lua/custom...`

**Comment by siduck** [comment]
https://nvchad.github.io/config/Lsp%20stuff#setup-lsp-server

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/167346011-1357f63f-1b1d-486c-8b1c-cee88959490a.mp4

Tried setting up vanilla nvchad with lspconfig and it works. Also dont just blindly use my config , you need to read the code within it. This isnt a nvchad issue but your custom config issue. As shown in the video, everything works

**Comment by erwin** [comment]
Just a follow-up for other people having this issue.

On my Ubuntu 21.10 desktop, the exact steps in siducks video do not work. I've tried many permutations over the last few days, including many before posting. The exact set of steps in siducks video still result in exactly what I posted above: `0 client(s) attached to this buffer`

So I installed a clean Ubuntu 22.04 Virtual Machine (on my 21.10 desktop) and inside of the VM, the result does match Siducks's video.

The most puzzling aspect is that the 21.10 desktop previously had Lsp working just perfectly for many months.

Both environments are using neovim-0.7.0 downloaded via `bob`.

I'll update this if I'm able to figure out what is actually preventing LSP from working.

**Comment by siduck** [comment]
@erwin make sure lsp is on path i.e install them with lspinstall

**Comment by erwin** [comment]
Thank you @siduck. Even for the lsp/sumneko_lua example like you show in the video, I did install from inside neovim with `:LspInstall`. Since on a clean install my issue isn't reproducible, please don't trouble yourself with it.

I must admit it's a puzzling issue though.

I went through the video you provided many times, frame by frame doing exactly the same steps... On freshly installed VM, works great... On my workstation, doesn't... This is the kind of moment that I wish I was using Nix.

Hopefully I'll get to the bottom of it without needing to migrate to a new user account or a fresh install...

**Comment by siduck** [comment]
@erwin I suggest you not to use ubuntu if you're an experienced linux user. Try fedora at least or arch/void

**Comment by siduck** [comment]
> I agree that Ubuntu in the last few years has turned to trash... Especially everything connected with `snap`... 100% open to ditching Ubuntu and **never coming back**.
> 
> I used Arch for 2-3 years but got burned a few times... New update came and suddenly a major hardware incompatibility that prevented me from getting any work done...
> 
> I still use RHEL on some servers - maybe you're right about Fedora on the desktop.
> 
> Friend of mine was recommending Gentoo...
> 
> Which distro is currently your favorite and why?

Gentoo is very cool but if you value your time i.e if you can wait for stuff to compile then its fine, It has many advantages such as using multiple versions of a package etc and you can try it if you have a good pc. 

I currently use void, its an independent distro, it supports partial upgrades so I rarely update and update the packages which I need :p . Unlike arch! in arch partial upgrading isnt supported and doing so will break system. Also void feels much minimal, lightweight and faster, I didnt need aur when using it. All packages i required were in its official repo itself. I can still install deb packages via its xdeb tool (its a script)

**Comment by erwin** [comment]
Cool! Very interesting. I'll check out void :-)

**Comment by barungh** [comment]
> simplescreenrecorder-2022-05-09_10.52.27.mp4
> 
> Tried setting up vanilla nvchad with lspconfig and it works. Also dont just blindly use my config , you need to read the code within it. This isnt a nvchad issue but your custom config issue. As shown in the video, everything works

This video helped a lot, Thanks

**Comment by siduck** [comment]
@barungh a lot has changed recently, i suggest you to re-read the custom config docs :)
