### ISSUE TITLE
Is current mappings setup inefficient? 

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1047]
Hi guys Ive seen many issues regarding users not being able change mappings, Do you think the current way of changing mappings isnt good?

**Comment by siduck** [comment]
I have an easier way to do it but that'll be a breaking change, so lemme know!

**Comment by nzlov** [comment]
I like the `which-key`, I had to heavily modify the original mapping

**Comment by ConanEdogawa1** [comment]
As a user of a colemak keyboard I change a lot of keymaps

**Comment by siduck** [comment]
> I like the `which-key`, I had to heavily modify the original mapping

im unable to lazyload it so i cant use it

**Comment by Akianonymus** [comment]
Well, i only have one problem currently, to change plugin mappings, we redefine the packer config and do all that, a bit cumbersome.

**Comment by siduck** [comment]
> Well, i only have one problem currently, to change plugin mappings, we redefine the packer config and do all that, a bit cumbersome.

noted, I will make the change soon then

**Comment by siduck** [comment]
@Akianonymus 

![image](https://user-images.githubusercontent.com/59060246/167472480-042e275f-e53f-478e-bd40-6ee4c6378833.png)

Is it an edge case that the user could use multiple keys for the same command? Never seen anyone doing that 

![image](https://user-images.githubusercontent.com/59060246/167472705-4976361f-34a6-4514-a566-8d4d868dc962.png)

**Comment by Akianonymus** [comment]
Well, doesn't make sense to have multiple keymappings for a single command, but it is definitely possible.

**Comment by nzlov** [comment]
I hope it is easy to disable some bindings in `custom`. Changed `mappings` a lot to use `which-key`, making it hard to sync upstream

**Comment by siduck** [comment]
> Well, doesn't make sense to have multiple keymappings for a single command, but it is definitely possible.

Oh then then the for loop can be removed in the above image but to disable default keys the user has to set them to nil like:
```lua
["<leader>a"] = nil
```

**Comment by primeapple** [comment]
I would like an easier Mapping config. Something like the code example in https://github.com/NvChad/NvChad/issues/1047#issuecomment-1121428993 would be nice. You could even allow the user to have duplicate mappings.

I think this is especially important for LSP and Telescope Mappings.

**Comment by siduck** [comment]
> I would like an easier Mapping config. Something like the code example in [#1047 (comment)](https://github.com/NvChad/NvChad/issues/1047#issuecomment-1121428993) would be nice. You could even allow the user to have duplicate mappings.
> 
> I think this is especially important for LSP and Telescope Mappings.

yes working on it!

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/167822956-39818aff-6b6c-42f9-9698-649b1c7a20c5.png)

![image](https://user-images.githubusercontent.com/59060246/167823913-722cab08-e527-45d2-b226-1310a7136d7e.png)


@primeapple @Akianonymus , which syntax looks better & cleaner?

**Comment by Akianonymus** [comment]
First one, looks better too and no need of second function anyway, the map function takes a single mode or table of modes as input.

**Comment by siduck** [comment]
> I like the `which-key`, I had to heavily modify the original mapping

looks good?

![image](https://user-images.githubusercontent.com/59060246/167984326-2a81472c-bdf2-49e2-b6e6-0860c4e68377.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/167984382-3fc8601c-384e-4f71-85bf-f85f3c348853.png)

:thinking:

**Comment by LeonHeidelbach** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/167993874-5c544fa7-bfcb-46d1-8747-28eed2183902.png)

@siduck looks really good. I like the arrow best.

**Comment by tomasky** [comment]
Maybe arrow better  ,i dont use 'which-key'. If it is actived ,can i disable it?

**Comment by siduck** [comment]
> Maybe arrow better ,i dont use `which-key`. If it is actived ,can i disable it?

i registered the mappings through it u disable whichkey then all mappings will disable too. And then you have to use the map function in core.utils to map mappings. Btw I lazy loaded whichkey so it doesnt take any startuptime

**Comment by tomasky** [comment]
If i disable whichkey,  then all nvchad default mappings will disable too ?   Oh no

**Comment by siduck** [comment]
> If i disable whichkey, then all nvchad's default mappings will disable too ? Oh no

Don't worry I'll try to add a lil function for you

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/169519108-9bb0a264-893b-4a4a-b421-dc061e10e8b2.png)


@LeonHeidelbach I think this syntax will be the easiest to deal with ( default & user tables can merge easily ) also whichkey's mapping description can be automatically generated by the field names :thinking: , but a breaking change would be bad

**Comment by LeonHeidelbach** [comment]
@siduck I don't really see how this would make things easier? The tables can currently merge easily but the loops are needed to make reliable overrides possible. That will not change with this. And how would you even go about enabling users to change mode opts in this? I also think that this looks more convoluted and less straight forward.

**Comment by siduck** [comment]
> @siduck I don't really see how this would make things easier? The tables can currently merge easily but the loops are needed to make reliable overrides possible. That will not change with this. And how would you even go about enabling users to change mode opts and set group names in this? I also think that this looks more convoluted and less straight forward since it adds more layers to the table.

our current way adds 3 layers of tables 

![image](https://user-images.githubusercontent.com/59060246/169530459-9026e1f6-9720-4588-92c2-4b75da071d67.png)


where as that one just adds 2 layers

**Comment by siduck** [comment]
alright lets not go into breaking changes

**Comment by siduck** [comment]
I felt like my startuptime had increased upto 50ms+ so got pretty tensed but if I check it again now, its back to normal 

![image](https://user-images.githubusercontent.com/59060246/169531471-87a5ebe4-ba39-472d-ad78-7005e45daf99.png)


Seems like my system was a lil slow at that time :thinking:

**Comment by LeonHeidelbach** [comment]
@siduck I don't really see an advantage over the current solution, especially because the override issue would persist event with this change (which is the only reason for the loops we currently have - that also have no impact on performance as I showed you). The mode layer (mode_opts,n,v,i,t) that we currently have makes it also very easy to group bindings (including specific mode opts) without having to redefine them per binding. I personally would not make this a breaking change, especially because, when looking at the issues rn, everything seems to work quite well and no-one seems to have any problems with the mapping solution. I find the current way of defining mappings in mappings.lua to be quite clean. However, it's your decision, your choice :).

**Comment by LeonHeidelbach** [comment]
> I felt like my startuptime had increased upto 50ms+ so got pretty tensed but if I check it again now, its back to normal 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/59060246/169531471-87a5ebe4-ba39-472d-ad78-7005e45daf99.png)
> 
> 
> 
> 
> 
> Seems like my system was a lil slow at that time :thinking: 

@siduck yeah, as I explained before, the startup time can be quite volatile depending on what the cpu is doing at the moment. A startup time range between 20 to 70ms is really fast though and faster than any other IDE ;).

**Comment by siduck** [comment]
> @siduck I don't really see an advantage over the current solution, especially because the override issue would persist event with this change (which is the only reason for the loops we currently have - that also have no impact on performance as I showed you). The mode layer (mode_opts,n,v,i,t) that we currently have makes it also very easy to group bindings (including specific mode opts) without having to redefine them per binding. I personally would not make this a breaking change, especially because, when looking at the issues rn, everything seems to work quite well and no-one seems to have any problems with the mapping solution. I find the current way of defining mappings in mappings.lua to be quite clean. However, it's your decision, your choice :).

i prefer the current solution then!

**Comment by siduck** [comment]
@LeonHeidelbach  https://www.reddit.com/r/neovim/comments/utukok/i_cant_change_the_theme_in_neovim_nvchad/i9bruh4/?context=3 Can you look onto this? 

i tried adding a check here 

https://github.com/NvChad/extensions/blob/main/lua/telescope/_extensions/themes.lua#L105

but that didnt work ;(

**Comment by LeonHeidelbach** [comment]
@siduck I will have a look at it

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach https://www.reddit.com/r/neovim/comments/utukok/i_cant_change_the_theme_in_neovim_nvchad/i9bruh4/?context=3 Can you look onto this?
>
>i tried adding a check here
>
>https://github.com/NvChad/extensions/blob/main/lua/telescope/_extensions/themes.lua#L105
>
>but that didnt work ;(

@siduck Done! https://github.com/NvChad/extensions/pull/24
