### ISSUE TITLE
Sweet desktop environment

### ISSUE THREAD

**Issue by webcoderz** [NvChad/NvChad#1050]
What is this amazing desktop env you are using in the screenshots it looks amazing and pairs well with nvchad

**Comment by siduck** [comment]
@webcoderz the current screenshots in nvchad readme are outdated, which one are you talking about ? :thinking:

**Comment by webcoderz** [comment]
This desktop env is so nice ![image](https://user-images.githubusercontent.com/19884161/167464953-64a01550-8bfe-4d4e-b88d-ddb94d498ff0.png)

**Comment by siduck** [comment]
Ohh, that's my bspwm rice. Check my dotfiles repo maim branch

**Comment by webcoderz** [comment]
Sweet thanks
