### ISSUE TITLE
Override defaults mappings of nvterm

### ISSUE THREAD

**Issue by hisamafahri** [NvChad/NvChad#1052]
**Describe the bug**
Hi, I have a question. I want to change [the default](https://github.com/NvChad/NvChad/blob/adecbe719f14e852346dbf672d50776e4789355b/lua/plugins/configs/nvterm.lua#L34-L35) `<leader>h` and `<leader>v` mappings. But so far I couldn't make it work following the docs [here](https://nvchad.github.io/config/Custom%20config#mappings).

**Expected behaviour**
I am able to override the default mappings from my `init.lua` or `chadrc.lua`

**Comment by siduck** [comment]
@hisamafahri 
![image](https://user-images.githubusercontent.com/59060246/167603215-4cd15139-ed1b-4513-842a-b10a413d3bda.png)

**Comment by siduck** [comment]
do you see the mappings table? u just have to override it. Check our docs to know how to override the default options of a plugin

**Comment by hisamafahri** [comment]
Do you mean [this file](https://github.com/NvChad/NvChad/blob/main/lua/core/mappings.lua)? I am sorry but I still don't know how to make it work.

**Comment by hisamafahri** [comment]
I am sure that [this part of docs](https://nvchad.github.io/config/Custom%20config#replace-default-config-of-a-plugin) is related, but still don't know what to put inside the `custom.nvterm`

**Comment by siduck** [comment]
> Do you mean [this file](https://github.com/NvChad/NvChad/blob/main/lua/core/mappings.lua)? I am sorry but I still don't know how to make it work.

no not that, we just didnt define nvterm mappings  inside core.mappings as we can do it in setup table of nvterm itsefl

**Comment by siduck** [comment]
```lua

["NvChad/nvterm"] = {
 mappings = {
  -- whatever you want to change 
 }
}

```

**Comment by hisamafahri** [comment]
I'm sorry, but I hope that I get what you mean but I am feeling so stupid rn. Here's my `plugins/init.lua`:

```lua
return {
    ["NvChad/nvterm"] = {
      mappings = {
        new = {
          horizontal = "", -- I just want to make these 2 go away so I can use it for another mappings
          vertical = "",
        }
      },
   },
}

```

**Comment by hisamafahri** [comment]
All I want is to remap the `<leader>v` to `:vsplit`, and `<leader>h` to `:split`.

**Comment by siduck** [comment]
you cant leave them empty, use different keys for them then add your mappings into custom.init.lua

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#mappings

**Comment by hisamafahri** [comment]
Hi, thank you for your help. Finally able to do that by [overriding the plugin's config](https://nvchad.github.io/config/Custom%20config#override-default-config-of-a-plugin). 

Thank you
