### ISSUE TITLE
Why the utility functions are not in the global scope?

### ISSUE THREAD

**Issue by ahhshm** [NvChad/NvChad#1053]
Why the utility functions are not in the global scope? 90% (if not all) of the files use at least one of the utility functions and having them in the global scope eliminates a lot of `require`s and makes the code base a lot cleaner.

**Comment by siduck** [comment]
@ahhshm how long would you take for this? as we have to do it in base46 and extensions plugin too

**Comment by siduck** [comment]
i couldnt get global functions work!

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/167638083-e6a37870-1013-415a-b6c4-dd391967e133.png)

shouldnt this work?

**Comment by siduck** [comment]
> > how long would you take for this? as we have to do it in base46 and extensions plugin too
> 
> One hour at most

cool then work on it! make sure you dont leave any place where local utils function are requried
