### ISSUE TITLE
Mapping not working

### ISSUE THREAD

**Issue by lvisb** [NvChad/NvChad#1057]
**Describe the bug**
I followed the Telescope example on the website to change the mapping but it's not working.

**To Reproduce**
1. Create a init.lua inside ~/.config/nvim/lua/custom/init.lua
2. Insert the code
```lua
local M = {}

M.plugins = {
  user = {
     ["nvim-telescope/telescope.nvim"] = {
      setup = function()
         -- load default mappings first
         require("core.mappings").telescope()

         -- then load your mappings
         local map = require("core.utils").map
         map("n", "<leader>ts", "<cmd> :Telescope themes <CR>")
      end,
     }
  }
}

return M
```
4. Open a new nvim
5. Press `<leader>ts` and nothing happens
6. Try to open Telescope themes manually: `:Telescope themes` and it works

**Expected behavior**
Keybinding should work.

**Desktop (please complete the following information):**
 - macOS + docker example
 - Allacritty
 - neovim 0.7.0

**Comment by siduck** [comment]
@lvisb i will simplify mappings today so wait a bit

**Comment by danjenson** [comment]
Getting this after an update just now:
![image](https://user-images.githubusercontent.com/4793438/167763707-666f3fb2-d835-436c-80a9-28937a88b62f.png)

**Comment by danjenson** [comment]
curiously changing the utils to this: https://github.com/NvChad/NvChad/issues/1055 worked..

**Comment by siduck** [comment]
> curiously changing the utils to this: #1055 worked..

yep all the utils functions are in global scope now
