### ISSUE TITLE
Gruvbox color scheme (full)

### ISSUE THREAD

**Issue by sudokit** [NvChad/NvChad#1058]
Could someone implement the colorscheme for example from this color palette: [Gruvbox (dark and ligt)](https://github.com/morhetz/gruvbox). (too lazy to do it myself so...)

**Comment by siduck** [comment]
we have the dark one already

**Comment by sudokit** [comment]
Ik but the light one

**Comment by siduck** [comment]
moved to here https://github.com/NvChad/base46/issues/73

**Comment by siduck** [comment]
@sudokit you can send a PR for this ._.

**Comment by sudokit** [comment]
Ik but y'know as i said, im too lazy to make one

**Comment by siduck** [comment]
@sudokit done
