### ISSUE TITLE
moving packer_compiled.lua

### ISSUE THREAD

**Issue by jamesla** [NvChad/NvChad#1059]
Currently in nvchad packer is configured in a way that it compiles the plugins and creates a config file in ~/.config/nvim/plugins/packer_compiled.lua

How can configure nvchad so that it puts this config somewhere else?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/167743094-4a6057bf-594a-496f-92da-f6398188d492.png)

check the compiled path field 

https://github.com/wbthomason/packer.nvim#custom-initialization

**Comment by siduck** [comment]
so u have to modify the default packerinit

![image](https://user-images.githubusercontent.com/59060246/167743137-63f5f395-9cb6-461b-bc8e-6ce3b3315d2d.png)
![image](https://user-images.githubusercontent.com/59060246/167743167-c112249c-e2c7-4ab2-aa81-11419bb5872a.png)

**Comment by jamesla** [comment]
thanks @siduck but is there anyway to override this setting via the custom directory?

**Comment by siduck** [comment]
> thanks @siduck but is there anyway to override this setting via the custom directory?

i will add an option for it today! @jamesla   :))

**Comment by jamesla** [comment]
Legend @siduck

**Comment by siduck** [comment]
@jamesla done! update nvchad ( there's a breaking change regarding mappings btw )

now you can override packer like you override other plugins (chadrc )

**Comment by jamesla** [comment]
Thanks @siduck - really appreciated 

- so implementation something like this right?

```
#chadrc

local M = {}

M.plugins = {
  override = {
    ["wbthomason/packer"] = {
       compile_path = "/tmp/packer_compiled_test.lua"
    },
  }
}

return M
```

**Comment by siduck** [comment]
> Thanks @siduck - really appreciated
> 
> * so implementation something like this right?
> 
> ```lua
> --chadrc
> 
> local M = {}
> 
> M.plugins = {
>   override = {
>     ["wbthomason/packer"] = {
>        compile_path = "/tmp/packer_compiled_test.lua"
>     },
>   }
> }
> 
> return M
> ```

yes

**Comment by jamesla** [comment]
> 

hmm not working - what's best way to debug?

**Comment by siduck** [comment]
> > > Thanks @siduck - really appreciated
> > > 
> > > * so implementation something like this right?
> > > 
> > > ```lua
> > > --chadrc
> > > 
> > > local M = {}
> > > 
> > > M.plugins = {
> > >   override = {
> > >     ["wbthomason/packer"] = {
> > >        compile_path = "/tmp/packer_compiled_test.lua"
> > >     },
> > >   }
> > > }
> > > 
> > > return M
> > > ```
> > 
> > 
> > yes
> 
> hmm not working - what's best way to debug?

did  you run packersync?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/168219400-e1874f66-b70c-4aeb-a36e-d03f026afc75.png)

the best way to debug is write the exact plugin name!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jamesla** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/168219400-e1874f66-b70c-4aeb-a36e-d03f026afc75.png)
> 
> the best way to debug is write the exact plugin name!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

oops working :-) thanks
