### ISSUE TITLE
Error loading custom/init.lua

### ISSUE THREAD

**Issue by mcctuxic** [NvChad/NvChad#1061]
The current git log of my local nvchad installation shows as the newest entries:
commit c0ca91cb92ce99d9e5664ee215e6376b9dc4b6a7 (HEAD -> main, origin/main, origin/HEAD)
Author: siduck <siduck@tutanota.com>
Date:   Tue May 10 20:41:37 2022 +0530

    add nvchad string to sumneko globals

commit 5a1240be82adda3545c5c13e5b795a14b74bf507
Author: Arman.H <ahhdev@gmail.com>
Date:   Tue May 10 18:13:48 2022 +0430

    refactor: add utils to the global scope

....
-----------------------------------------------------------------------------

These last updates via leader uu introduced an error, which breaks nvchad.
Starting nvim results in:

/home/user/.config/nvim/lua/custom/init.lua:4: attempt to index a boolean value
Press ENTER or type command to continue

Then after pressing RETURN:
packer.nvim: Error running setup for gitsigns.nvim: [string "..."]:0: attempt to index a boole
an value
Press ENTER or type command to continue

Then:
packer.nvim: Error running setup for vim-matchup: [string "..."]:0: attempt to index a boolean
 value
Press ENTER or type command to continue

Then:

packer.nvim: Error running config for base46: ...al/share/nvim/site/pack/packer/opt/base46/lua
/base46.lua:9: attempt to index a boolean value
Press ENTER or type command to continue
packer.nvim: Error running config for feline.nvim: ...al/share/nvim/site/pack/packer/opt/base4
6/lua/base46.lua:9: attempt to index a boolean value
Press ENTER or type command to continue

And then I am thrown into a mostly "naked" nvim.

**Comment by siduck** [comment]
Do packersync

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/1055

**Comment by mcctuxic** [comment]
Does not help. Still getting:
Error loading custom/init.lua

/home/user/.config/nvim/lua/custom/init.lua:4: attempt to index a boolean value

...and feline fails to update. Tried several times. Same result

**Comment by siduck** [comment]
dont update like that, open a new nvim window and just do packersync. 

Also its showing custom init.lua cuz you are still using the outdated config. 

all require("core.utils").stuff to nvchad.stuff
