### ISSUE TITLE
Can't use pwsh with nvterm

### ISSUE THREAD

**Issue by bryant-the-coder** [NvChad/NvChad#1063]
**Describe the bug**
When i add this line (i will show below), open nvterm `<A-i>` then error shows for **2 SECONDS**

**To Reproduce**
1. go to settings.lua or the place where u change nvim settings.
2. add this `o.shell = "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"`
3. error show

**Expected behavior**
no errors and show prompt with starship

**Screenshots**
i have no screenshot

**Desktop (please complete the following information):**
 - Windows
 - WindowsTerminal
 - 0.7

**Comment by kamack38** [comment]
I suggest you use the new [`pwsh`](https://github.com/PowerShell/PowerShell) instead of deprecated `powershell` 5.1

I have this in my config

```lua
if vim.fn.has('win32') == 1 then
   opt.shell = 'pwsh.exe -nol'
   opt.shellcmdflag = '-nop -c'
   opt.shellquote = '"'
   opt.shellxquote = ''
   opt.shellpipe = '| Out-File -Encoding UTF8 %s'
   opt.shellredir = '| Out-File -Encoding UTF8 %s'
end
```

The first line just checks if it's a Windows machine, because I use NvChad both on Linux & Windows

**Comment by bryant-the-coder** [comment]
thanks :D

**Comment by siduck** [comment]
> thanks :D

works?

**Comment by xarthurx** [comment]
I don't think so...

> > thanks :D
> 
> works?


![image](https://user-images.githubusercontent.com/1921878/168020681-970014c1-3f65-407c-beca-3de483adb337.png)

**Comment by xarthurx** [comment]
P=

> > thanks :D
> 
> works?

Partially. The color scheme is different and it starts quite slow.

**Comment by siduck** [comment]
> P=
> 
> > > thanks :D
> > 
> > 
> > works?
> 
> Partially. The color scheme is different and it starts quite slow.

i dont think why the colorscheme would start slow cuz of the shell! provide your nvim --startuptime before and after

**Comment by zbirenbaum** [comment]
>  
> 
> 
> 
> > P=
> 
> > 
> 
> > > > thanks :D
> 
> > > 
> 
> > > 
> 
> > > works?
> 
> > 
> 
> > Partially. The color scheme is different and it starts quite slow.
> 
> 
> 
> i dont think why the colorscheme would start slow cuz of the shell! provide your nvim --startuptime before and after

Color scheme and startup are two different issues here I think. He's saying that the shell doesn't match his color scheme and as a separate issue the shell starts slow I believe. Knowing powershell I believe both claims implicitly

**Comment by xarthurx** [comment]
> > P=
> > > > thanks :D
> > > 
> > > 
> > > works?
> > 
> > 
> > Partially. The color scheme is different and it starts quite slow.
> 
> i dont think why the colorscheme would start slow cuz of the shell! provide your nvim --startuptime before and after

Yeah, color scheme might be a non-related issue.
For the time, I mean when pressing `<M-i>` for the first time, the term showup slower than the default term. I think `startuptime` can only measure things loaded with `nvim`? For startup time, I didn't notice too much difference.

**Comment by zbirenbaum** [comment]
> Yeah, color scheme might be a non-related issue.
> For the time, I mean when pressing <M-i> for the first time, the term showup slower than the default term. I think startuptime can only measure things loaded with nvim? For startup time, I didn't notice too much difference

Yeah I was talking about shell startup. The reason it only takes a long time the first one you open is because of the terminal toggling plugin. It keeps the process alive when you toggle.

Even opening powershell on my very very high spec desktop has an unreasonably long launch to prompt time. It's just slow, powershell, and most of windows tbh, is inefficient code.

Add in the extra overhead that might come from it being an integrated terminal rather than inside of a M$FT™️ dedicated™️ terminal emulator and you've got a recipe for slowness.

**Comment by barungh** [comment]
![image](https://user-images.githubusercontent.com/12285528/168655750-3c4096da-8136-40e6-83b7-9b49371cfce9.png)

It works, it launches the powershell instead of windows command prompt,

Powershell takes time to load profile.ps1 file, to parse it, and load the configured modules

I tried replacing 'pwsh.exe' with 'powershell.exe' 
>pwsh.exe if powershell core ( version 6 and above )
>powershell.exe is powershell version 5
powershell version 5 loads little faster

**Comment by siduck** [comment]
@barungh cant you use bash or zsh on windows?

**Comment by barungh** [comment]
> @barungh cant you use bash or zsh on windows? the last time i tried pwsh, it was very heavy. Took more than 100mb of ram o_o

Without a doubt, Poweshell is very heavy, much heavier than bash or zsh,

I work both on Linux and Windows,

working in windows is not a choice, instead "no other choice" sometimes, 
bash and zsh does not work natively on Windows, 

most blog post or YT videos show how to configure using WSL, which would be another bloated  burden.

**Comment by barungh** [comment]
> > > @barungh cant you use bash or zsh on windows? the last time i tried pwsh, it was very heavy. Took more than 100mb of ram o_o
> > 
> > 
> > Without a doubt, Poweshell is very heavy, much heavier than bash or zsh,
> > I work both on Linux and Windows,
> > working in windows is not a choice, instead "no other choice" sometimes,
> > bash and zsh does not work natively on Windows,
> > most blog post or YT videos show how to configure using WSL, which would be another bloated  burden.
> 
> send ur config pwease

https://github.com/barungh/nvim

**Comment by bryant-the-coder** [comment]
> ![image](https://user-images.githubusercontent.com/12285528/168655750-3c4096da-8136-40e6-83b7-9b49371cfce9.png)
> 
> It works, it launches the powershell instead of windows command prompt,
> 
> Powershell takes time to load profile.ps1 file, to parse it, and load the configured modules
> 
> I tried replacing 'pwsh.exe' with 'powershell.exe'
> 
> > pwsh.exe if powershell core ( version 6 and above )
> > powershell.exe is powershell version 5
> > powershell version 5 loads little faster

are u using windows or wsl?

**Comment by siduck** [comment]
@barungh avoid writing anything outside your custom folder, you can add it in chadrc itself

https://nvchad.github.io/config/Custom%20config#change-default-options

**Comment by barungh** [comment]
> > ![image](https://user-images.githubusercontent.com/12285528/168655750-3c4096da-8136-40e6-83b7-9b49371cfce9.png)
> > It works, it launches the powershell instead of windows command prompt,
> > Powershell takes time to load profile.ps1 file, to parse it, and load the configured modules
> > I tried replacing 'pwsh.exe' with 'powershell.exe'
> > > pwsh.exe if powershell core ( version 6 and above )
> > > powershell.exe is powershell version 5
> > > powershell version 5 loads little faster
> 
> are u using windows or wsl?

I am using Windows , Windows 10 to be specific, Windows Terminal and Powershell 7, never used WSL

**Comment by siduck** [comment]
> @bryant-the-coder Is the issue solved ?

he doesnt use nvchad so dont worry about him :stuck_out_tongue_closed_eyes:

**Comment by barungh** [comment]
> > @bryant-the-coder Is the issue solved ?
> 
> he doesnt use nvchad so dont worry about him 😝

How do you know that ? 🤔

**Comment by siduck** [comment]
@zbirenbaum does toggleterm handle the issue of pwsh like nvterm does?

**Comment by siduck** [comment]
current issues are 2 ~, gotta keep it 0 :laughing:

**Comment by siduck** [comment]
@barungh so you no longer face the pwsh issue with nvchad right?

**Comment by barungh** [comment]
> > > ![image](https://user-images.githubusercontent.com/12285528/168655750-3c4096da-8136-40e6-83b7-9b49371cfce9.png)
> > > It works, it launches the powershell instead of windows command prompt,
> > > Powershell takes time to load profile.ps1 file, to parse it, and load the configured modules
> > > I tried replacing 'pwsh.exe' with 'powershell.exe'
> > > > pwsh.exe if powershell core ( version 6 and above )
> > > > powershell.exe is powershell version 5
> > > > powershell version 5 loads little faster
> > 
> > 
> > are u using windows or wsl?
> 
> I am using Windows , Windows 10 to be specific, Windows Terminal and Powershell 7, never used WSL

@siduck 

I think I already did that,

powershell all the versions working fine with NvChad, on Powershell itself ( I mean on native shell of Windows not WSL )

**Comment by bryant-the-coder** [comment]
> @zbirenbaum does toggleterm handle the issue of pwsh like nvterm does?

toggleterm and nvterm are having the same issue btw. 😂

**Comment by bryant-the-coder** [comment]
@siduck please dont stalk me 🙏

**Comment by siduck** [comment]
> > @zbirenbaum does toggleterm handle the issue of pwsh like nvterm does?
> 
> toggleterm and nvterm are having the same issue btw. joy

hmm then this is no longer a nvchad issue, install another OS xD
