### ISSUE TITLE
wrong repo url for lsp_extensions.nvim

### ISSUE THREAD

**Issue by ArshiAAkhavan** [NvChad/NvChad#1069]
**Describe the bug**

i tried to use [lsp_extensions](https://github.com/nvim-lua/lsp_extensions.nvim) for inlay_hint in rust but i couldn't get it to work. and when i started to speculate the installed extension files, i saw the following:
result of `PackerStatus` in `nvim`:

![Screenshot from 2022-05-13 12-56-57](https://user-images.githubusercontent.com/45825003/168243708-da0d7d96-03b1-4e1d-ba5d-8a5472f11d07.png)

and im sure theres a problem here

**Expected behavior**

the source url for `lsp_extensions` and `nvchad_extensions` to differ

**Desktop (please complete the following information):**
 - Operating System: 
```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```
 - Terminal: allactritty 
 - Version of Neovim:
```bash
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck** [comment]
show your chadrc or custom plugins list

**Comment by brutusmcforce** [comment]
Try this:
`["nvim-lua/lsp_extensions.nvim"] = {
    as = 'lsp_extensions',
}`

@siduck Maybe NvChad should prefix its plugin locations with nvchad_ to avoid collisions like these?

**Comment by siduck** [comment]
@brutusmcforce that'd make the string harder to read ( when we require the extensions plugin as modules in our config)

**Comment by ArshiAAkhavan** [comment]
@brutusmcforce `:PackerStatus` still shows the same result, that is, both `lsp_extensions` and `extensions` have the same URL

**Comment by brutusmcforce** [comment]
@ArshiAAkhavan Try removing the installed modules from the packer directory and do a new sync.

**Comment by siduck** [comment]
@ArshiAAkhavan i didnt even use the "as" option and I dont get the same extension folder by default like u 

![image](https://user-images.githubusercontent.com/59060246/168402521-17397b16-59d1-4db9-a872-0982cb92ec4e.png)
