### ISSUE TITLE
transparency not working

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1070]
### **Describe the bug**
Transparency seems like not working with the previous commit c7a4d4e3376b1684c1dd117d53e94480b2d7c9fe. I also uninstall nvchad via https://nvchad.github.io/getting-started/setup#uninstall and reinstall but still act the same.

**Expected behavior**
transparent should work as previous

#### `Nvim-tree`:
![image](https://user-images.githubusercontent.com/73665622/168255705-38e1a47e-e499-4d30-8847-fbec4ae6ec4f.png)

#### `Telescope`:
![image](https://user-images.githubusercontent.com/73665622/168255822-3481c480-aa5c-45ad-b73c-baf06e009b47.png)

### **Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Wezterm & Kitty
 - NVIM v0.7.1-dev

### **Additional context**
I used Nvim v0.7.1-dev **_before_** latest breaking changes (932bd6a74c968df5152ab53ad4ec37ec23339044) and it work fine so neovim version not the issues.

#### **`chadrc.lua`**

<details>

```lua
local M = {}

M.ui = {
   --- File path which contains highlight
   transparency = true,
   theme = "tokyonight",
   theme_toggle = { "tokyonight", "kanagawa" },
}

return M
```
</details>

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/168263344-63d7760c-01e5-4054-87e1-9a2714e00026.mp4

works here

**Comment by GreatestOfAllTimee** [comment]
> simplescreenrecorder-2022-05-13_15.44.06.mp4 
> works here

I know you already said. How can I not? Even I uninstall and install again it still same unless I revert nvchad with a previous commit including revert all nvchad extension/base64 and it work as we expected.

**Comment by LeonHeidelbach** [comment]
@siduck transparencies in normal buffers work, but NvimTree does have a background after the last breaking change which is a little weird.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/55194243/168266239-3bc08b0f-2310-4ebf-8815-b58c0c73258c.png">

**Comment by Pasqat** [comment]
> > simplescreenrecorder-2022-05-13_15.44.06.mp4
> > works here
> 
> I know you already said. How can I not? Even I uninstall and install again it still same unless I revert nvchad with a previous commit including revert all nvchad extension/base64 and it work as we expected.

It could be related to the terminal you are using

**Comment by GreatestOfAllTimee** [comment]
> @siduck transparencies in normal buffers work, but NvimTree does have a background after the last breaking change which is a little weird.
> 
> <img alt="image" width="513" src="https://user-images.githubusercontent.com/55194243/168266239-3bc08b0f-2310-4ebf-8815-b58c0c73258c.png">

Yaah, can you try see telescope if is act the same as nvimtree?

**Comment by Pasqat** [comment]
For me too Nvimtree and Telescope are solid. For the latter I think its better as it is

**Comment by LeonHeidelbach** [comment]
> > @siduck transparencies in normal buffers work, but NvimTree does have a background after the last breaking change which is a little weird.
> > <img alt="image" width="513" src="https://user-images.githubusercontent.com/55194243/168266239-3bc08b0f-2310-4ebf-8815-b58c0c73258c.png">
> 
> Yaah, can you try see telescope if is act the same as nvimtree?

@GreatestOfAllTimee Yes, I can confirm, telescope also has a background now. It's the same.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/55194243/168267075-b4673450-f431-4469-bb14-6be4cf43d0fb.png">

**Comment by siduck** [comment]
I see, ig this is cuz i moved telescope and nvimtree into different files, no worries for this. I'll fix it

**Comment by GreatestOfAllTimee** [comment]
> For me too Nvimtree and Telescope are solid. For the latter I think its better as it is

I increase line spacing and x padding in my terminal, so when in neovim, neovim background doesnt fully apply/override my terminal background, its look ugly

**Comment by siduck** [comment]
ok done ._.

**Comment by gmr458** [comment]
> simplescreenrecorder-2022-05-13_15.44.06.mp4 
> works here

how do you make NvimTree not transparent like the editor?

**Comment by siduck** [comment]
@gmr458 just add bg color for it'd highlight group which is NvimTreeNormal, check how to override highlight groups & their colors from our docs

**Comment by wilberquito** [comment]
I am having the same issue, even if I set transparency to true, buffers stay solid.

```lua
M.ui = {
  theme = "gruvchad",
  theme_toggle = { "gruvchad", "one_light" },

  hl_override = highlights.override,
  hl_add = highlights.add,
  transparency = true,
}
```

**Comment by wilberquito** [comment]
@siduck but setting `transparency = true` should toggle the `base64`  function `toggle_transparency()`?

At least it is what I understand from the documentation: https://nvchad.com/docs/api#toggle_transparency

**Comment by siduck** [comment]
> @siduck but setting `transparency = true` should toggle the `base64` function `toggle_transparency()`?
> 
> At least it is what I understand from the documentation: https://nvchad.com/docs/api#toggle_transparency

it should enable transparency, and setting it false should disable transparency. 

 But your issue isnt related to it, i just didnt add support for making buffer tabs transparent so far. Because not everything transparent looks good! but i can do it if you want
