### ISSUE TITLE
some of mappings override/disable not working

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1071]
### **Describe the bug**
we already discuss this on Discord. I disable whichkey and add `nvchad.no_WhichKey_map()` in `custom/init.lua`.

**The mapping below does not work**. I believe there is more mappings not able to configure:

```lua
local M = {}

...

M.nvterm = {
   n = {
      -- disable both mappings
      ["<A-h>"] = "",
      ["<A-v>"] = "",
   },
}

M.move = {
   v = {
      ["J"] = { "<cmd>m '>+1<CR>gv=gv" },
      ["K"] = { "<cmd>m '<-2<CR>gv=gv" },
   },

   n = {
      -- doesn't work even tho we already disable on M.nvterm
      ["<A-h>"] = { "<cmd> vertical resize +2 <CR>" }, 
      ["<A-l>"] = { "<cmd> vertical resize -2 <CR>" },
   }
}

...

return M
```

### **Expected behavior**
Should work as we expected.

### **Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Wezterm & Kitty
 - NVIM v0.7.1-dev

### **Additional context**
I used Nvim v0.7.1-dev before latest breaking changes (https://github.com/NvChad/NvChad/commit/932bd6a74c968df5152ab53ad4ec37ec23339044) and it work fine.

**Comment by GreatestOfAllTimee** [comment]
> @GreatestOfAllTimee nvterm mappings can be disabled now, do a packersync

I will try later. Did you try apply others mappings? Its work?

**Comment by siduck** [comment]
> > @GreatestOfAllTimee nvterm mappings can be disabled now, do a packersync
> 
> I will try later. Did you try apply others mappings? Its work?

i will test the others later but the nvterm mappings issue not disabling will work now

**Comment by LeonHeidelbach** [comment]
@siduck another thing that just came to mind that I also noticed while rewriting my mappings yesterday is that it now also matters in which order the mapping configurations in `M.<YOUR_KEY_MAP>`s are used in the call  to `wk.register`. If you want to use a mapping for an extension that has already been claimed by another one that previously claimed it, overriding it will only work if the key map is loaded last (Or you would have to specifically add that mapping for a different extension to the one that claims it last, which would be kinda unintuitive if you know what I mean). We could circumvent this issue by looping through all mappings first, checking for a match with any custom override and remove those doubling entries from the table.

**Comment by siduck** [comment]
@LeonHeidelbach this sounds complex for now so lets not touch it xD, the biggest issue we have currently is extracting colors from current theme, as youve seen it doesnt work in chadrc and users need it for overriding their highlight groups in chadrc, its annoying to add hex codes all the time!

**Comment by LeonHeidelbach** [comment]
@siduck it's not really that complex but it is important. People will open issues like this one when they are having trouble overriding mappings 😄 I will look into it later today.

Regarding the color scheme issue, I think the easiest thing to do would be to just hold the color table in a global variable after loading it with `get_colors`. Whenever this function is called you could just set the loaded table to this global variable which would also be available in `chadrc`.

**Comment by siduck** [comment]
> Regarding the color scheme issue, I think the easiest thing to do would be to just hold the color table in a global variable after loading it with `get_colors`. Whenever this function is called you could just set the loaded table to this global variable which would also be available in `chadrc`.

tried the global part and it didnt work

**Comment by siduck** [comment]
@GreatestOfAllTimee so this isnt a nvchad issue! 
```lua
M.move = {
   v = {
      ["J"] = { ":m '>+1<CR>gv=gv" },
      ["K"] = { ":m '<-2<CR>gv=gv" },
   },
}

```
Those arent commands so no need to add <cmd> , tested it locally and this works ._.

**Comment by LeonHeidelbach** [comment]
> > Regarding the color scheme issue, I think the easiest thing to do would be to just hold the color table in a global variable after loading it with `get_colors`. Whenever this function is called you could just set the loaded table to this global variable which would also be available in `chadrc`.
> 
> tried the global part and it didnt work

@siduck did you pay attention to the call stack order? Did you load `chadrc` before or after calling `get_colors`? If you loaded `chadrc` before calling `get_colors` first, the global variable will be empty.

**Comment by siduck** [comment]
@LeonHeidelbach I even removed the chadrc part ( load_config() ) here 

![image](https://user-images.githubusercontent.com/59060246/168278642-efa80656-c88d-4cfa-9fbd-65c93d453519.png)

replaced it with just ```lua local name = vim.g.nvchad_theme``` and put ```lua vim.g.nvchad_theme = nvchad.load_config().ui.theme``` in core/options.lua . Still didnt work!

**Comment by LeonHeidelbach** [comment]
@siduck hard to tell what the problem is, when I don't have the code in front of me. I'll have to look at it myself. The thing is, my schedule is pretty packed so I don't know when I'll get to it.

**Comment by siduck** [comment]
> @siduck hard to tell what the problem is, when I don't have the code in front of me. I'll have to look at it myself. The thing is, my schedule is pretty packed so I don't know when I'll get to it.

no worries, take your time. I dont use the hl_override personally, if I need to make any change I push those highlight changes in the base46 repo :laughing:

**Comment by GreatestOfAllTimee** [comment]
> Those arent commands so no need to add , tested it locally and this works ._.

yes it works, but if I'm not wrong there are some mappings that I tried to add but still don't work. here they are:

```lua
local M = {}

...

M.nvterm = {
   n = {
      ["<A-h>"] = "", -- disable here
      ["<A-v>"] = "",
   },
}

M.screen = {
   n = {
     -- mappings down below does not work
      ["A-v"] = { "<cmd>vs<CR>" },
      ["A-a"] = { "<cmd>sp<CR>" },
      ["A-k"] = { "<cmd>resize +2 <CR>" },
      ["A-j"] = { "<cmd>resize -2 <CR>" },
      ["A-h"] = { "<cmd>vertical resize +2 <CR>" }, -- used here
      ["A-l"] = { "<cmd>vertical resize -2 <CR>" },
      ["<leader>cd"] = { "<cmd>cd %:p:h<CR>:pwd" }, -- this worked!
   },
}

...

return M
```

**Comment by GreatestOfAllTimee** [comment]
#### **but the previous method works as we expected:**

```lua
-- custom/init.lua

nvchad.no_WhichKey_map()

local map = nvchad.map
local opt = { silent = true }

map("n", "<A-v>", ":vs<CR>", opt)
map("n", "<A-a>", ":split<CR>", opt)
map("n", "<A-k>", ":resize +2 <CR>", opt)
map("n", "<A-j>", ":resize -2 <CR>", opt)
map("n", "<A-h>", ":vertical resize +2 <CR>", opt)
map("n", "<A-l>", ":vertical resize -2 <CR>", opt)
```

**Comment by siduck** [comment]
its <A-v> and not A-v, and vice versa

**Comment by siduck** [comment]
@GreatestOfAllTimee its easier to disable default keys now 

https://github.com/NvChad/NvChad/commit/96cd08ef455b8b813f3cc89420339afe70cce895#commitcomment-73629292

**Comment by siduck** [comment]
> > > Regarding the color scheme issue, I think the easiest thing to do would be to just hold the color table in a global variable after loading it with `get_colors`. Whenever this function is called you could just set the loaded table to this global variable which would also be available in `chadrc`.
> > 
> > 
> > tried the global part and it didnt work
> 
> @siduck did you pay attention to the call stack order? Did you load `chadrc` before or after calling `get_colors`? If you loaded `chadrc` before calling `get_colors` first, the global variable will be empty.

seems like i found the issue, Its the override function in every theme file 

![image](https://user-images.githubusercontent.com/59060246/168424770-03a8e2d8-5221-495f-b0a1-dcee4142b934.png)

That function takes a value from the chadrc so the loop error is obvious ig , but I cant remove the function as its used for overriding specific colors of any default theme via chadrc like this 

![image](https://user-images.githubusercontent.com/59060246/168424904-7f1c7a15-b15c-4a9f-a64f-c40c64691209.png)

i tried the global part but it seems to be nil in chadrc :(

**Comment by GreatestOfAllTimee** [comment]
nvchad totally broken after https://github.com/NvChad/base46/commit/0c1a2205fd9a32bacf00229844afca9eea9362a1 or https://github.com/NvChad/base46/commit/ad78b9ffbfd8315d49ca97d8dfd27ad2ce9e382c (which I not sure it was from [base46](https://github.com/NvChad/base46) or nvchad itself). I suggest you to revert that commit.

**Comment by siduck** [comment]
> nvchad totally broken after [NvChad/base46@0c1a220](https://github.com/NvChad/base46/commit/0c1a2205fd9a32bacf00229844afca9eea9362a1) or [NvChad/base46@ad78b9f](https://github.com/NvChad/base46/commit/ad78b9ffbfd8315d49ca97d8dfd27ad2ce9e382c) (which I not sure it was from [base46](https://github.com/NvChad/base46) or nvchad itself). I suggest you to revert that commit.

the recent commit fixed it

**Comment by GreatestOfAllTimee** [comment]
> the recent commit fixed it, do packersync again

haa this I got an error regarding of keymap.

![image](https://user-images.githubusercontent.com/73665622/168425375-a79910d0-eaeb-493f-9164-0586146c45f5.png)

**Comment by siduck** [comment]
> > the recent commit fixed it, do packersync again
> 
> haa this I got an error regarding of keymap.
> 
> ![image](https://user-images.githubusercontent.com/73665622/168425375-a79910d0-eaeb-493f-9164-0586146c45f5.png)

show yoru custom/init.lua

**Comment by GreatestOfAllTimee** [comment]
oh yah this coming from https://github.com/NvChad/NvChad/commit/514c988b3d8f7c2a971554f150feb0bc48995fe2.

#### `custom/init.lua`
<details>

```lua
nvchad.no_WhichKey_map()
local autocmd = vim.api.nvim_create_autocmd

autocmd("TextYankPost", {
   callback = function()
      vim.highlight.on_yank { higroup = "Visual", on_visual = false, timeout = 100 }
   end,
})

require "custom.plugin.clipboard"
require "custom.plugin.highlights"
vim.cmd "source ~/.config/nvim/lua/custom/plugin/Python.vim"
vim.cmd "source ~/.config/nvim/lua/custom/plugin/Copilot.vim"
```

</details>

**Comment by siduck** [comment]
> oh yah this coming from #1074.
> 
> #### `custom/init.lua`

oh I managed to reproduce it by disabling whichkey and using disabled table in mappings, lemme check

**Comment by siduck** [comment]
btw seems like all mappings do work, its just the error

**Comment by GreatestOfAllTimee** [comment]
> btw seems like all mappings do work, its just the error

no, mappings are not working after this error.

**Comment by siduck** [comment]
> > btw seems like all mappings do work, its just the error
> 
> no, mappings are not working after this error.

press space and see leader ff

**Comment by GreatestOfAllTimee** [comment]
> press space and see leader ff
it works. but try to navigate split screen using `<C-h` or `<C-l`

**Comment by siduck** [comment]
@GreatestOfAllTimee I reverted that change, update config. I'll maintain a dev branch from now. Lets get serious :smile:

**Comment by siduck** [comment]
@tomasky @GreatestOfAllTimee   I reverted that change, update config. I'll maintain a dev branch from now. Lets get serious :smile:

**Comment by LeonHeidelbach** [comment]
@GreatestOfAllTimee @siduck This should fix it https://github.com/NvChad/NvChad/pull/1075.

**Comment by LeonHeidelbach** [comment]
> 

@siduck you know what would be nice with the project getting as large as it is. Some unit tests, that check if everything works before we merge. The problem is, that I don't really know how to implement unit tests with neovim. :thinking:

**Comment by siduck** [comment]
> > @tomasky @GreatestOfAllTimee I reverted that change, update config. I'll maintain a dev branch from now. Lets get serious smile
> 
> @siduck you know what would be nice with the project getting as large as it is. Some unit tests, that check if everything works before we merge. The problem is, that I don't really know how to implement unit tests with neovim. thinking

from now all PR's will go to dev branch, i'll test them personally then merge them!

**Comment by GreatestOfAllTimee** [comment]
Me either, but here are the structures of unit test https://github.com/LunarVim/LunarVim/tree/rolling/tests. Nvchad not a framework so it might be easier than this.

**Comment by LeonHeidelbach** [comment]
> > > @tomasky @GreatestOfAllTimee I reverted that change, update config. I'll maintain a dev branch from now. Lets get serious smile
> 
> > 
> 
> > @siduck you know what would be nice with the project getting as large as it is. Some unit tests, that check if everything works before we merge. The problem is, that I don't really know how to implement unit tests with neovim. thinking
> 
> 
> 
> from now all PR's will go to dev branch, i'll test them personally then merge them!

@siduck the thing with manual testing is that you can always miss "something". If we were to establish a test suite that would test for at least most functionality before a commit is merged it would be a lot easier and more reliable.

**Comment by GreatestOfAllTimee** [comment]
> from now all PR's will go to dev branch, i'll test them personally then merge them!

This seems like a lot of work to do (manually test), unit tests a common things that every big project should have.

**Comment by siduck** [comment]
> > > > @tomasky @GreatestOfAllTimee I reverted that change, update config. I'll maintain a dev branch from now. Lets get serious smile
> > 
> > 
> > > 
> > 
> > 
> > > @siduck you know what would be nice with the project getting as large as it is. Some unit tests, that check if everything works before we merge. The problem is, that I don't really know how to implement unit tests with neovim. thinking
> > 
> > 
> > from now all PR's will go to dev branch, i'll test them personally then merge them!
> 
> @siduck the thing with manual testing is that you can always miss "something". If we were to establish a test suite that would test for at least most functionality before a commit is merged it would be a lot easier and more reliable.

the test still  requires manual intervention, we have to provide some custom config to it every now and then when adding new features

**Comment by GreatestOfAllTimee** [comment]
> the test still requires manual intervention as vanilla nvchad without custom config works 100% of the time and then we have to provide some custom config to it every now and then when adding new features

Just a minimal custom config. Nvchad should have a specific api that can handle that

**Comment by GreatestOfAllTimee** [comment]
For unit tests only.

**Comment by LeonHeidelbach** [comment]
@siduck we could have several test configs that check different things. This will be a little work to set up but once this is done it will make things a lot easier and reliable. Is there a way to run neovim in headless mode and let it check for different things? Does anyone know anything about that? How do extension devs implement unit tests or do they just not have any? Do you know more about that @GreatestOfAllTimee?

**Comment by siduck** [comment]
@LeonHeidelbach idk about unit tests so cant say about it but ig we should have sample custom configs after v2.0 release

**Comment by LeonHeidelbach** [comment]
@siduck yes, definitely. Let's have a separate repo for those. different custom folders that we can just plug and play switch out while testing. Btw. pushing new commits to a dev branch first, letting a couple trusted users test their config as well as some of our future test configs on that dev branch would be the way to go from now on to avoid too many unexpected breaking changes for "normal" users.

**Comment by siduck** [comment]
@LeonHeidelbach I hadnt added dev branch before as I didnt know merging dev to branch xD, now I do . So made the dev branch, all PRs will go in it from now

**Comment by GreatestOfAllTimee** [comment]
> @siduck we could have several test configs that check different things. This will be a little work to set up but once this is done it will make things a lot easier and reliable. Is there a way to run neovim in headless mode and let it check for different things? Does anyone know anything about that? How do extension devs implement unit tests or do they just not have any? Do you know more about that @GreatestOfAllTimee?

I'm not quite sure if there is builtin unit tests in lua and I've never used github CI before. Usually large projects will (must) have unit testing so that if there is a issue/conflicts on PR, they can track where it came from. Unit testing can be more handy sometimes for devs.

I believe this might help, take a look [**Olivine-Labs/busted**](https://github.com/Olivine-Labs/busted).

**Comment by GreatestOfAllTimee** [comment]
> How do extension devs implement unit tests or do they just not have any? 

oh yes [**nvim-lspconfig**](https://github.com/neovim/nvim-lspconfig) & [**L3MON4D3/LuaSnip**](https://github.com/L3MON4D3/LuaSnip) and maybe more?

**Comment by tomasky** [comment]
Please dont drop some commits ,just `git revert <commit>` .
