### ISSUE TITLE
Copilot keybind

### ISSUE THREAD

**Issue by iamchokerman** [NvChad/NvChad#1078]
**Describe the bug**
I don't know how to change the default keybind for github copilot. I would like to keep <Tab> for LSP autocompletion, and use <C-e> for copilot completion

**To Reproduce**

**Expected behavior**
I'd like to know the easiest way to do so

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Mac OS
 - Terminal Warp and iTerm2
 - Version of Neovim 0.7.0

**Additional context**
[https://github.com/zbirenbaum/copilot.lua](https://github.com/zbirenbaum/copilot.lua)

**Comment by LeonHeidelbach** [comment]
@iamchokerman you can do it like this:

```lua
-- Github Copilot Bindings
-----------------------------------------------------------
M.copilot = {
  mode_opts = { expr = true },
  i = {
    ["<C-h>"] = { 'copilot#Accept("<Left>")', "   copilot accept" },
  },
}
```

**Comment by iamchokerman** [comment]
gonna test this now

**Comment by LeonHeidelbach** [comment]
I'm using it myself so it should work for you as well ;)

**Comment by iamchokerman** [comment]
yep, it's working rly well tysm, i'm switching full time to nvchad now, i do have a small little issue tho. when i use <C-h> it works as expected, but when i use <C-e> i need to click that keybind twice for the completion to work. i presume this is happening bc <C-e> is a default keybind, and i've tried disabling it by adding it to M.disabled, however that didn't seem to work. any ideas?

**Comment by LeonHeidelbach** [comment]
> yep, it's working rly well tysm, i'm switching full time to nvchad now, i do have a small little issue tho. when i use <C-h> it works as expected, but when i use <C-e> i need to click that keybind twice for the completion to work. i presume this is happening bc <C-e> is a default keybind, and i've tried disabling it by adding it to M.disabled, however that didn't seem to work. any ideas?

@iamchokerman You don't have to add it to M.disabled when overriding a pre-existing map. Try removing it from there and let me know if that fixes it.

**Comment by iamchokerman** [comment]
i already tried that, but no workie 😔 @LeonHeidelbach

**Comment by LeonHeidelbach** [comment]
@iamchokerman you will also have to add the option for it to work properly.

```lua 
-- Disable TAB completion for github copilot
  vim.g.copilot_no_tab_map = true 
```

That works fine for me without having to press the keys twice. Do you use which-key or did you disable ur?

**Comment by iamchokerman** [comment]
i already had this in my chadrc. i do use which-key, but i would like to disable it actually @LeonHeidelbach

**Comment by LeonHeidelbach** [comment]
@iamchokerman If you want to disable which-key you can follow the instructions on in the NVChad documentation.

Can you try setting it to a different key combination like the one I posted in my code example and let me know if you also have it with this map?

**Comment by iamchokerman** [comment]
yep, will do

**Comment by LeonHeidelbach** [comment]
@siduck since the  binding issue with `<C-e>` is probably caused by another plugin registering custom key maps or another user modification I think we can close this issue.  I could not reproduce it myself (setting copilot accept to `<C-e>` works just fine for me). Solved.

**Comment by iamchokerman** [comment]
yep

**Comment by spbui00** [comment]
Hi, I am trying this but it tells me that copilot#Accept is an unknown function, maybe it is under different name...?
