### ISSUE TITLE
Modified Onedark

### ISSUE THREAD

**Issue by SheetaI** [NvChad/NvChad#1079]
Hello. By chance could add this color palette. 
Main bg is #2C3036

**Screenshot**
https://raw.githubusercontent.com/SheetaI/xonedark.nvim/master/theme.png

The screenshot above is a grayish modified version of https://github.com/navarasu/onedark.nvim
I actually just change the theme manually to replicate but it breaks time to time if i do an update.

Here is the link of a fork in which I did change the bg already to 2C3036 https://github.com/SheetaI/xonedark.nvim
Thanks. Appreciate the work on this project!

**Comment by siduck** [comment]
@SheetaI sorry we will use our own version of onedark

**Comment by siduck** [comment]
btw u can just edit the color in your chadrc!

https://nvchad.github.io/config/Custom%20config#override-specific-colors-in-themes

**Comment by HarleyQuinn-Z6** [comment]
I also prefer the normal onedark colorscheme. If someone makes the changes to the custom configuration please copy it here.

**Comment by siduck** [comment]
> I also prefer the normal onedark colorscheme. If someone makes the changes to the custom configuration please copy it here.

you can just change the bg color in chadrc

**Comment by HarleyQuinn-Z6** [comment]
If you tell me where the themes are defined I'll be able to look what's the name of the color that I have to change.

**Comment by siduck** [comment]
> If you tell me where the themes are defined I'll be able to look what's the name of the color that I have to change.

~/.local/share/nvim/site/pack/packer/opt/base46/lua/hl_themes

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/168454267-e420693c-a456-4fd5-8fe8-9e64e0c31b71.png)

**Comment by SheetaI** [comment]
thanks.. just added the theme following the custom config guide.

added my theme in custom/themes/mytheme.lua
added mytheme in chadrc.lua

![1652607371](https://user-images.githubusercontent.com/29585755/168466436-c3ec60d7-9a8d-445a-972a-4a14fac1ccc8.png)
