### ISSUE TITLE
Visual Highlight + Comment not working

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1081]
**Describe the bug**
Highlighting a region of text and running <leader>+/ is not commenting out the right section of text.

```python
def apple():
    pass


def banana():
    pass
```
Put that in a python file and try to comment out the first function by visual highlight.

**To Reproduce**
See desc.

**Expected behavior**
Commenting should work..

**Desktop (please complete the following information):**
 - Void LInux
 - Alacritty
 - NVIM v0.7.0

**Comment by siduck** [comment]
@GreatestOfAllTimee  you were facing the same issue iirc , its fixed now i

**Comment by GreatestOfAllTimee** [comment]
@siduck thanks!
