### ISSUE TITLE
My hl_override not working 

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#1083]
**Describe the bug**
My hl_override not working 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**
the lastest nvchad and latest other plugins, i dont known why

```lua
-- custon/chadrc.lua

local my_highlights = require "custom.highlights"
 
M.ui = {
    hl_override = my_highlights,
}

--- custom/highlights.lua

return {

   Visual = {
      reverse = true,
      bg = "#665c54",
   },
}
```

**Comment by siduck** [comment]
@tomasky it should work with latest commit, is it fixed?

**Comment by tomasky** [comment]
Yes ,thanks
