### ISSUE TITLE
nvim command display

### ISSUE THREAD

**Issue by basluc** [NvChad/NvChad#1084]
**Describe the bug**
In kali linux i have a bug, a message appears in command prompt
**To Reproduce**
1. Install nvim
2. install nvchad and follow instructions in doc
3. start nvim with nvchad and open new buffer
4. press Ctr-n
5. open files in buffer A and B

**Screenshots**

![nvchad_bug](https://user-images.githubusercontent.com/38686246/168471325-842a42c5-55fc-4754-b4b9-63db8add405d.png)
you can see the bug on the bottom and in buffer B

![nvchad_bug2](https://user-images.githubusercontent.com/38686246/168470968-f717d505-d35d-4f8f-b5e7-72aaf7993459.png)
When i enter a command or where status appears the bug persist

**Desktop (please complete the following information):**
 - Kali linux
 - Zsh last version
 - NVIM v0.7.0
 - new neovim installation

**Additional context**
When i run PackerCompile and i select a text the bug disappears and reappears after open new file. But in Ubuntu i haven't problem.

Thanks you for your work in NvChad and sorry for my bad english.

**Comment by zbirenbaum** [comment]
This is an interesting one. Are you using the same term emulator in kali as in Ubuntu? I don't use nvimtree but this really shouldn't happen unless the io pipes are messed up or something.

**Comment by siduck** [comment]
unable to reproduce it

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/926 might be related

**Comment by basluc** [comment]
Yes i use the same and i haven't error, and i use basic parameter in kali

**Comment by siduck** [comment]
which terminal?

**Comment by basluc** [comment]
> #926 pourrait être lié

I will soon try to edit files and see how the lsp reacts

**Comment by basluc** [comment]
> which terminal?

the terminal provided by kali with zsh

**Comment by siduck** [comment]
> > which terminal?
> 
> the terminal provided by kali with zsh

show your neofetch

**Comment by basluc** [comment]
> > > which terminal?
> > 
> > 
> > the terminal provided by kali with zsh
> 
> show your neofetch

![neofetch](https://user-images.githubusercontent.com/38686246/168476032-5a7eb9cb-dbcb-45aa-811e-1772ada2991c.png)

**Comment by zbirenbaum** [comment]
> > > > which terminal?
> 
> > > 
> 
> > > 
> 
> > > the terminal provided by kali with zsh
> 
> > 
> 
> > show your neofetch
> 
> 
> 
> ![neofetch](https://user-images.githubusercontent.com/38686246/168476032-5a7eb9cb-dbcb-45aa-811e-1772ada2991c.png)
> 
> 
> 
> 

Install alacritty or kitty, should be in your package manager and try again using one of those. I've never heard of qterminal and this looks like a io issue so its probably the cause.

If the issue is resolved just change your font in the config of whichever term you install to use your nerd font so the icons appear properly.

**Comment by basluc** [comment]
Hi,
sorry i've been busy this week, but the last updat of nvchad has solve my problem. Thank you for your work ;)
