### ISSUE TITLE
rose-pine theme

### ISSUE THREAD

**Issue by Akavvi** [NvChad/NvChad#1086]
https://github.com/rose-pine/neovim
looks good in the dark version

![image](https://user-images.githubusercontent.com/72504099/168474332-dd450c3e-f208-491c-bcfe-0e713cfda7b1.png)

**Comment by siduck** [comment]
looks ok to me except for the teal color :l

**Comment by Akavvi** [comment]
> looks ok to me except for the teal color :l
![image](https://user-images.githubusercontent.com/72504099/168476128-139818af-9e65-457a-8ff8-df6c31925c5c.png)
in moon version teal color looks better

**Comment by siduck** [comment]
https://github.com/NvChad/base46/issues/74 moved to here. Send the PR for it,check base46 readme first
