### ISSUE TITLE
Error detected while processing C:\Users\username\AppData\Local\nvim\init.lua:

### ISSUE THREAD

**Issue by barungh** [NvChad/NvChad#1093]
**Error loading autocmds**
```[ps]
Error detected while processing C:\Users\livin\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: C:\Users\livin\AppData\Local\nvim\init.lua:18: Error loading autocmds
```

**To Reproduce**
With a fresh installation on Windows

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12285528/168596858-cbc393e1-9545-4268-9ea5-40f8d899fc60.png)
.

**Desktop (please complete the following information):**
 - Windows 10
 - Windows Terminal, Powershell 7
 - Neovim 6.0

**Comment by siduck** [comment]
@barungh use 0.7

**Comment by barungh** [comment]
> @barungh use 0.7

After upgrading to Neovim 0.7 , problem was gone, working fine on Windows 10 

Thank You @siduck
