### ISSUE TITLE
How to disable guibg in custom config? 

### ISSUE THREAD

**Issue by 0xdd7fq** [NvChad/NvChad#1098]
I use kitty terminal with padding and can’t make neovim fill full window,
so I need to enable `:hi Normal guibg=NONE`everytime to disable background.
Too retarded to do it by myself. Can you help me please? Thanks.

![564F2BF9-8E6A-4450-A854-E1BB1A45DD48](https://user-images.githubusercontent.com/88155811/168766503-7706d018-6923-4ddf-ae2c-d06ebcca93f1.jpeg)

**Comment by siduck** [comment]
do packersync first cuz ive made a lil change in the theme plugin

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/168770521-bf4d0c9c-f6d9-44ad-9520-7ef5b2d8a496.png)


override highlights like this

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-default-highlights
