### ISSUE TITLE
Telescope + nvim-tree change current directory

### ISSUE THREAD

**Issue by slade991** [NvChad/NvChad#1099]
Hello,

I'm not quite sure where the problem is, i tried to search on telescope and nvim tree but i cannot seem to solve it.

When i open a file with find_files on Telescope, the current working directory is changing. from the new file.

For example :
if my project has the following structure :

- Root directory
      - folder1 / file1
      - folder2 / file2

I search file1 with telescope. My current working directory is now folder1. Nvim-tree show me only the content of folder1 and telescope will only search into folder1.

this is extremely annoying and make navigating through search impossible as i get stuck in lower directory and i no way of search for files in higher directory.

Is there a way to stay at all time in the root directory ?

Thank you.

**Comment by siduck** [comment]
do a nvchad update i.e leader uu

**Comment by slade991** [comment]
Thank you for you comment, but i just installed it like 3 hours ago.

**Comment by siduck** [comment]
> Thank you for you comment, but i just installed it like 3 hours ago.

show your lua/core/autocmd file

**Comment by slade991** [comment]
`local autocmd = vim.api.nvim_create_autocmd

-- Disable statusline in dashboard
autocmd("FileType", {
   pattern = "alpha",
   callback = function()
      vim.opt.laststatus = 0
   end,
})

autocmd("BufUnload", {
   buffer = 0,
   callback = function()
      vim.opt.laststatus = 3
   end,
})

-- open nvim with a dir while still lazy loading nvimtree
autocmd("BufEnter", {
   callback = function()
      if vim.api.nvim_buf_get_option(0, "buftype") ~= "terminal" then
         vim.cmd "lcd %:p:h"
      end
   end,
})

-- Use relative & absolute line numbers in 'n' & 'i' modes respectively
-- autocmd("InsertEnter", {
--    callback = function()
--       vim.opt.relativenumber = false
--    end,
-- })
-- autocmd("InsertLeave", {
--    callback = function()
--       vim.opt.relativenumber = true
--    end,
-- })

-- Open a file from its last left off position
-- autocmd("BufReadPost", {
--    callback = function()
--       if not vim.fn.expand("%:p"):match ".git" and vim.fn.line "'\"" > 1 and vim.fn.line "'\"" <= vim.fn.line "$" then
--          vim.cmd "normal! g'\""
--          vim.cmd "normal zz"
--       end
--    end,
-- })

-- File extension specific tabbing
-- autocmd("Filetype", {
--    pattern = "python",
--    callback = function()
--       vim.opt_local.expandtab = true
--       vim.opt_local.tabstop = 4
--       vim.opt_local.shiftwidth = 4
--       vim.opt_local.softtabstop = 4
--    end,
-- })

-- Highlight yanked text
-- autocmd("TextYankPost", {
--    callback = function()
--       vim.highlight.on_yank { higroup = "Visual", timeout = 200 }
--    end,
-- })

-- Enable spellchecking in markdown, text and gitcommit files
-- autocmd("FileType", {
--    pattern = { "gitcommit", "markdown", "text" },
--    callback = function()
--       vim.opt_local.spell = true
--    end,
-- })
`

**Comment by siduck** [comment]
yes so do leader uu :p

**Comment by slade991** [comment]
I cannot update due to changes i did to the file, but i commented the "BufEnter" which was the issue.
Thanks!

**Comment by siduck** [comment]
dont change the default config, i reverted and removed that commit and its not there in the commit history as well. So just do a fresh clone or remove your changes  +  leader uu

**Comment by slade991** [comment]
I have too many changes to remove but it's ok. 
Nvchad is just a base config for me.

**Comment by siduck** [comment]
It's better to use the custom config, you can control the whole of nvchad within it. If you edit files put of it then you will no longer get updates!
