### ISSUE TITLE
File opening instead of nvim-tree

### ISSUE THREAD

**Issue by Lalit64** [NvChad/NvChad#1100]
**Describe the bug**
File named `.` opening instead of nvim-tree when typing `nvim .` into terminal

**To Reproduce**
1. Type `nvim .` or `nvim <any directory>` directly into terminal
2. See it open a file named `.` instead of nvim-tree

**Expected behavior**
Open nvim-tree in full-width
<img width="1630" alt="Screenshot 2022-05-17 at 17 20 17" src="https://user-images.githubusercontent.com/79628080/168847557-f6726da7-55f6-4cfe-8f80-531b7560f6de.png">

**Screenshots**
<img width="1630" alt="Screenshot 2022-05-17 at 17 19 54" src="https://user-images.githubusercontent.com/79628080/168847425-51de7731-85c5-4c24-8ad8-b5cecd66a10d.png">

**Desktop (please complete the following information):**
 - macOS Monterey 12.3.1
 - iTerm2 nightly
 - NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local

**Additional context**
Nothing

**Comment by siduck** [comment]
thats cuz nvimtree is lazy loaded

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#modify-plugin-definition-options

**Comment by trungdt880** [comment]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/20278911/230592794-78ea4f0d-600d-4fae-8362-e4837569378b.png">
I did add the event and do `:Lazy check` when run `nvim .`, it still opens only the file with name ".". Can you double check? Thanks!

**Comment by Lalit64** [comment]
I am having the same issue as @bomcon123456  please reopen this.

**Comment by siduck** [comment]
@Lalit64  nvimtree removed the option to load itself on startup

**Comment by siduck** [comment]
To load nvimtree on startup

```lua
vim.schedule(function()
  require("nvim-tree.api").tree.open()
end)
```

**Comment by siduck** [comment]
To cd into a dir when doing `nvim folder` , put this in  your shell config like bashrc etc
```bash
nv() {
  [ -n "$1" ] && [ -d "$1" ] && cd "$1" && shift
  nvim "$@"
}
```
example : `nv folder`
