### ISSUE TITLE
can't just "j" in terminal mode

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1101]
Because "j" signals the start of terminal escape, you can't use the letter at all, really:
![image](https://user-images.githubusercontent.com/4793438/168942391-eb8fe743-d1b5-42f5-89e3-4e452762f7d3.png)

**Comment by danjenson** [comment]
Also doesn't work reading any man pages, etc:

![image](https://user-images.githubusercontent.com/4793438/168958356-46a2fa79-6360-4ab4-9a13-e26f55300276.png)

**Comment by siduck** [comment]
I can confirm the first issue but not    the 2nd one,  j in normal works for anything so why doesnt it work there for you?

**Comment by dfhssilva** [comment]
This also affects me. I changed the "jk" mapping to escape the terminal to "JK" but after doing that the default "jk" mapping remains. I know I might be deviating from the issue but is there any way to erase this default mapping? I have read the documentation and all I found is to override default mappings (but the original ones are kept).

**Comment by danjenson** [comment]
The man pages are still in terminal, so the shortcut is still operating when I try to use the vim paging. To test it, run an R session and then do `?rnorm` and try to page through.

**Comment by siduck** [comment]
disable the default mapping first 

![image](https://user-images.githubusercontent.com/59060246/169425848-ee036e42-a95f-4c4b-8af7-caf40b38035b.png)
