### ISSUE TITLE
Custom plugin not loading

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1104]
![image](https://user-images.githubusercontent.com/4793438/169420667-f6339276-c8de-41ba-be7b-8a5158350f33.png)

Both using the key `L` and the cmd `:IronRepl` fail.

**Comment by siduck** [comment]
does that plugin exist?

https://github.com/hkupty/iron.nvim

**Comment by danjenson** [comment]
Looks like this was an issue with iron.nvim upgrades, apologies.
