### ISSUE TITLE
git icons not showing in nvimtree

### ISSUE THREAD

**Issue by ThatOneOcto** [NvChad/NvChad#1106]
**Describe the bug**
In the nvimtree.nvim tree, it doesn't add the git icons, I made sure that git was enabled in the plugin config and it is

**To Reproduce**
Idk how you reproduce it, it just happens

**Expected behavior**
git icons to show

**Screenshots**

**Desktop (please complete the following information):**
 - Gentoo x86_64
 - Alacritty
 - v0.7.0

**Additional context**

**Comment by siduck** [comment]
enable it in your chadrc, override the default config. You should know how to do that if you read the docs
