### ISSUE TITLE
Configure and load the base map

### ISSUE THREAD

**Issue by ConanEdogawa1** [NvChad/NvChad#1111]
How to map basic keys, I configured in custom folder and loaded in init.lua does not take effect
![image](https://user-images.githubusercontent.com/49578735/169637203-53057d96-2299-4bf6-a52f-52ea3beaca94.png)

**Comment by tomasky** [comment]
```lua
--custom/init.lua
local map = nvchad.map
local opt = { silent = true }
map("n", "<leader>cc", ":Telescope <CR>", opt)


```

**Comment by ConanEdogawa1** [comment]
Thank You!!

**Comment by ConanEdogawa1** [comment]
errors:custom/init.lua:6: attempt to index a boolean value

**Comment by siduck** [comment]
its better to use  the table format for mappings instead, avoid using that function 

https://nvchad.github.io/config/Mappings#mapping-format
