### ISSUE TITLE
I can't install it on Kali Linux

### ISSUE THREAD

**Issue by spoilyzer** [NvChad/NvChad#1114]
I have an issue when I want to install it.
The first command it's ok: git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
But the second one doesn't work: nvim +'hi NormalFloat guibg=#1e222a' +PackerSync

The error is:
Se ha detectado un error al procesar /home/spoilyzer/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/spoilyzer/.config/nvim/init.lua:18: Error loading autocmds

/home/spoilyzer/.config/nvim/lua/core/autocmds.lua:4: attempt to call local 'autocmd' (a nil value)
stack traceback:
        [C]: in function 'error'
        /home/spoilyzer/.config/nvim/init.lua:18: in main chunk
Se ha detectado un error al procesar command line:
E492: No es una orden del editor: PackerSync
Pulse INTRO o escriba una orden para continuar

**Comment by siduck** [comment]
make sure you use 0.7v neovim

**Comment by spoilyzer** [comment]
I just do it and it works! Thank you for helping me!
