### ISSUE TITLE
Problem installing nvchad on linux mint

### ISSUE THREAD

**Issue by Mugworth** [NvChad/NvChad#1118]
Yes i saw that someone reported this bug already, but in opposite to him i have version 0.7.0 of nvim (NVIM v0.7.0-dev+1097-g9fe8d2c9d)

I wanted to upgrade nvchad by uninstalling and installing it again and then i got this error:

Error detected while processing ~/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ~/.config/nvim/init.lua:18: Error loading
 autocmds

~/.config/nvim/lua/core/autocmds.lua:4: attempt to call local 'autocmd' (a nil
value)
stack traceback:
        [C]: in function 'error'
        ~/.config/nvim/init.lua:18: in main chunk
Press ENTER or type command to continue

Edit: worth to mention is that at the same time i installed it on laptop and it worked out smoothly.

**Comment by siduck** [comment]
when was the last time you updated nvchad? also use the neovim version from releases, if it aint on your repo then use this https://github.com/MordechaiHadad/bob

**Comment by Mugworth** [comment]
Well if i don't count today, i installed it few moths ago and didn't update it since.

Thank you for recomending the bob manager it seems really helpful, i installed the nightly version of nvim and then nvchad but now it seems like it can't install treesitter plugin:

Error executing vim.schedule lua callback: ...vim/site/pack/packer/opt/packer.nvim/lua/p
acker/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/
site/pack/packer/opt/packer.nvim/lua/packer/load.lua:139: Vim(lua):E5108: Error executin
g lua vim/_init_packages.lua:0: module 'vim.lsp' not found:
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <..
.vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:780: in function 'lo
ader'
        /home/kuba/.config/nvim/lua/core/utils.lua:139: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

i dunno if i should open new issue.

**Comment by siduck** [comment]
please update it or have a new installation!

**Comment by siduck** [comment]
a lot has changed since last month, let alone few months! So check the pinned issues and update your custom config stuffs accordingly too
