### ISSUE TITLE
Bug: `<ESC>` no longer deselects highlighted search results

### ISSUE THREAD

**Issue by LeonHeidelbach** [NvChad/NvChad#1121]
**Describe the bug**
After searching for a character sequence in a buffer using either `/` or `?` and hitting enter to be able to cycle through the serach results using `N` or `n`, the hightlighted sequences cannot be deselected by hitting "<ESC>". I noticed this a couple of days ago but cannot pin point it down to a specific commit. This can also be reproduced with a clean NvChad install.

**To Reproduce**
1. Open the search prompt using either the `/` or `?` key
2. Typ in the character sequence you would like to search for
3. Hit `Enter` - All occurences should now be highlighted
4. Hit `<ESC>` to remove the highlights

**Expected behavior**
Pressing `ESC` should remove all highlights from the last search.

**Screenshots**

https://user-images.githubusercontent.com/55194243/169887020-83fdb282-15e7-4cd2-8350-053183683e46.mp4

**Desktop (please complete the following information):**
 - Arch Linux
 - Alacritty
 - 0.7

**Comment by nullchilly** [comment]
Map "<esc>" to ":noh<CR>" in the mean time

**Comment by LeonHeidelbach** [comment]
@nullchilly yeah that works, might have been a mapping that @siduck removed in one of the last commits?

**Comment by nullchilly** [comment]
Yeah it was removed when migrating to whichkey. I assume it was a mistake

The old mapping is here: 
https://github.com/NvChad/NvChad/blob/8571787d70aa9852148420e5684eed138a2dd8da/lua/core/mappings.lua#L26

**Comment by LeonHeidelbach** [comment]
@siduck could you push this as a fix pls?

**Comment by nullchilly** [comment]
Haha if I wasnt on phone I would do it
My NvChad pull request last few days was all one line change 😂

**Comment by LeonHeidelbach** [comment]
@nullchilly haha damn, nah small changes like this I think aren't really worth the merge commit in the git history :wink:

**Comment by nullchilly** [comment]
I can definitely see some keymaps disappeared, to name a few

```
-- Don't copy the replaced text after pasting in visual mode
-- https://vim.fandom.com/wiki/Replace_a_word_with_yanked_text#Alternative_mapping_for_paste
map("v", "p", 'p:let @+=@0<CR>:let @"=@0<CR>', { silent = true })

-- Allow moving the cursor through wrapped lines with j, k, <Up> and <Down>
-- http<cmd> ://www.reddit.com/r/vim/comments/2k4cbr/problem_with_gj_and_gk/
-- empty mode is same as using <cmd> :map
-- also don't use g[j|k] when in operator pending mode, so it doesn't alter d, y or c behaviour

map({ "n", "x", "o" }, "j", 'v:count || mode(1)[0:1] == "no" ? "j" : "gj"', { expr = true })
map({ "n", "x", "o" }, "k", 'v:count || mode(1)[0:1] == "no" ? "k" : "gk"', { expr = true })
map("", "<Down>", 'v:count || mode(1)[0:1] == "no" ? "j" : "gj"', { expr = true })
map("", "<Up>", 'v:count || mode(1)[0:1] == "no" ? "k" : "gk"', { expr = true })

-- use ESC to turn off search highlighting
map("n", "<Esc>", "<cmd> :noh <CR>")
map("n", "<C-t>b", "<cmd> :tabnew <CR>") -- new tabs
```

To name a few

Also you removed the autocmds.lua, I kinda like these small tips you know, I wonder if it is available on the website? [Hmm](https://nvchad.github.io/config/walkthrough)
https://github.com/NvChad/NvChad/blob/bdf45a447add58ec07a66f763289f187dfa90a3e/lua/core/autocmds.lua#L39-L47

**Comment by mculp** [comment]
I noticed this also. Let's delete the project and start over

**Comment by siduck** [comment]
@LeonHeidelbach does this work     

```lua
      ["<ESC>"] = { "<cmd> noh <CR>", "  no highlight" },
```

**Comment by siduck** [comment]
@nullchilly i'll add it in tips & tricks section

**Comment by siduck** [comment]
https://nvchad.github.io/config/Tricks

**Comment by siduck** [comment]
> Also we approached 0 issue on github, time for 2.0 @siduck :D
 
 Once the base46 issues get to 0 then nvchad 2.0 will be finished, and @LeonHeidelbach will add a snapshot feature so we can switch to stable 2.0 release & other releases & master version of nvchad on the fly :D
