### ISSUE TITLE
Terminal mode: Typing a j screws everything up

### ISSUE THREAD

**Issue by mculp** [NvChad/NvChad#1122]
**Describe the bug**
If I open a split or pop-up terminal, and I'm typing in Insert Mode, when I hit `j`, no input shows up. Then I press `j` a few more times and `+"jjjjj` or similar shows up. It makes me think it's related to registers, but not sure.

**To Reproduce**
See the above

**Expected behavior**
A j would appear

**Screenshots**
![Screen Shot 2022-05-23 at 6 40 58 PM](https://user-images.githubusercontent.com/129983/169921542-3aac0bd9-2ce2-41a0-ad3d-cd89859ef437.png)

**Desktop (please complete the following information):**
 - MacOS 12.3.1 (m1)
 - iterm2 or 3
 - Neovim Version:
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1650023513425.local

Features: +acl +iconv +tui
See ":help feature-compile"
```

**Comment by siduck** [comment]
update your nvchad, jk was replaced with Ctrl + x to escape from terminal mode
