### ISSUE TITLE
Launch LSP on Library Source File

### ISSUE THREAD

**Issue by BinhaoQin** [NvChad/NvChad#1126]
**Describe the bug**
Cannot attach `clangd` to library source file buffer opened by "Go to Definition" (using `gd`).

**To Reproduce**
1. open a C++ source file with `clangd` attached
2. `gd` to a function or anything defined in a library

**Expected behavior**
Opens the new library source file buffer and attach it to LSP

**Screenshots**
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1017: Invalid buffer id: 2                                             
stack traceback:                                                                                                                                               
        [C]: in function 'nvim_buf_set_option'                                                                                                                 
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1017: in function 'jump_to_location'                                                                      
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:332: in function 'handler'                                                                            
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1025: in function ''                                                                                           
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Desktop (please complete the following information):**
 - Arch Linux
 - Kitty with zsh
 - 0.7.0

**Additional context**
I guess the problem is that as a user, we don't have permission for library files. But I cannot think of a quick and easy way to fix it.

**Comment by siduck** [comment]
ok so which function do i put the cursor on?

i tried here and gd works

![Uploading image.png…]()

**Comment by BinhaoQin** [comment]
I just gd on the header file Eigen/Dense

**Comment by siduck** [comment]
on dense 

![image](https://user-images.githubusercontent.com/59060246/170101580-92cbdda7-1e4a-41d6-8bc6-b86b5c16bd95.png)

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/170104509-115a3fe4-85c4-4f37-b9fa-dd9dbf639754.mp4

is this the expected behaviour from your side?

**Comment by BinhaoQin** [comment]
Yes, but I was unable to attach the newly opened buffer to LSP

**Comment by siduck** [comment]
can you provide a video of your issue?

**Comment by BinhaoQin** [comment]
https://user-images.githubusercontent.com/90790064/170110851-e7fdfc33-a5bb-4446-a835-9937343c4076.mp4
This is what happens on my computer.

**Comment by bryant-the-coder** [comment]
i see the client offset encoding thing. there is one setting u need to have kek

**Comment by BinhaoQin** [comment]
I think that does not matter since null-ls uses utf-16 encoding and clangd supports utf-16. I added that line to suppress warning for that "attaching buffer to lsp clients with different offset encoding is not supported".

**Comment by bryant-the-coder** [comment]
no. clangd uses utf-8 iirc

**Comment by siduck** [comment]
@BinhaoQin i dont get the error you get, can you do a clean nvchad install ?

**Comment by BinhaoQin** [comment]
I have located the issue. One of my plugin requires password whenever connected to a buffer that is in a protected directory. Thank you all for your support!

**Comment by CompeyDev** [comment]
> is this the expected behaviour from your side?

A bit off topic, but what's that WM? Is it hyprland?

**Comment by siduck** [comment]
> > is this the expected behaviour from your side?
> 
> A bit off topic, but what's that WM? Is it hyprland?

my own ( fork of dwm ) https://github.com/siduck/chadwm

**Comment by CompeyDev** [comment]
Cool!
