### ISSUE TITLE
support for dockerfile doesn't work?

### ISSUE THREAD

**Issue by ericwq** [NvChad/NvChad#1129]
**Describe the bug**
open a docker file in NvChad, the TreeSitter highlight stop working. 

**To Reproduce**
just open any docker file.

**Expected behavior**
correct highlight.

**Screenshots**
<img width="575" alt="Screen Shot 2022-05-26 at 23 17 47" src="https://user-images.githubusercontent.com/1501146/170518943-4e175e6e-67b0-4eb4-a059-028cadc89e69.png">

**Desktop (please complete the following information):**
 - Operating System: macOS Monterey
 - Terminal: alacritty
 - Version of Neovim: 0.7

**Additional context**
I install the dockerfile treesitter several times. still figure out what's wrong. several days ago, everything is fine.

**Comment by siduck** [comment]
@ericwq try adding dockerfile filetype in your custom.init.lua , ig thats the issue :thinking:

**Comment by GreatestOfAllTimee** [comment]
I think this is similar https://github.com/NvChad/NvChad/issues/1001. You can try https://github.com/NvChad/NvChad/issues/1001#issuecomment-1114085601 or https://github.com/NvChad/NvChad/issues/1001#issuecomment-1114257827

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/170602109-1941cf5e-e9d0-40d5-9c1a-d1216e7e8c43.mp4

It should work even if its treesitter parser isnt installed, this looks an issue with your setup most likely. When creating a new issue, please try replicate that issue with vanilla nvchad config :c

**Comment by ericwq** [comment]
In case someone need this solution.

- create a `filetype.lua` file, see the content in the following section.
- put `filetype.lua` in `~/.config/nvim/` directory
- restart your neovim

```lua
vim.filetype.add({
        extension = {
                dockerfile = "dockerfile",
        },
})
```
