### ISSUE TITLE
Cannot override lsp mappings

### ISSUE THREAD

**Issue by curtbushko** [NvChad/NvChad#1137]
**Describe the bug**
Hello, 

I am trying to override the mappings for `gr`, `gd`, etc to use telescope instead of the builtin lsp popup. I can override other mappings in my mappings.lua but I cannot these ones to work.

I have this in my custom mappings.lua

```
M.lspconfig = {
  n = {
    ["gd"] = { "<cmd>Telescope lsp_definitions<CR>", "definitions" },    
    ["gr"] = { "<cmd> Telescope lsp_references <CR>", "references" },
  },
}
```

I have also tried overriding in custom.plugins.lspconfig during the lsp on_attach. I do know that the above commands work as I have them in my custom whichkey mappings and they work with <leader>gr

**To Reproduce**
1. Override any non-leader mapping for lspconfig

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Mac
 - Terminal: Alacritty
 - Version of Neovim: NVIM v0.7.0
 - Nvchad: I pulled the repo 5 minutes ago.

Thanks for your help!

**Comment by siduck** [comment]
did u disabled them? https://nvchad.github.io/config/Mappings#mappings-table-structure 
 
i think no! so do it :p

**Comment by curtbushko** [comment]
I have disabled them. I disabled most of the default mappings but these lsp ones won't override.

<snippet from my mappings.lua>

```
M.disabled = {
  n = {
    ["gd"] = "",
    ["gr"] = "",
  },
}

M.lspoveride = {
  n = {
    ["gd"] = { "<cmd>Telescope lsp_definitions<CR>", "definitions" },
    ["gr"] = { "<cmd> Telescope lsp_references <CR>", "references" },
  },
}
```

**Comment by siduck** [comment]
lemme test this locally

**Comment by curtbushko** [comment]
Thanks!  Also, thanks for a fantastic neovim setup!

**Comment by siduck** [comment]
your config works for me

**Comment by curtbushko** [comment]
And it brings up the telescope window?

![Screen Shot 2022-05-27 at 10 28 57 PM](https://user-images.githubusercontent.com/431893/170806187-dc1f0033-048b-494c-8045-1d8ecb225059.png)

**Comment by siduck** [comment]
no i dont get that, this is weird 

empty buffer 



![image](https://user-images.githubusercontent.com/59060246/170806296-1c3c58eb-4829-4205-9954-9dce38b91102.png)

and gd runs its lsp command only

**Comment by siduck** [comment]
i tried running telescopes command manually and that didnt even open up the telescope window

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/170806418-0b68d8a7-3bc3-431b-bf94-4eda83afba9b.mp4

**Comment by siduck** [comment]
this works fine tho ( for testing purposes ) , so we can know that the mappings have been overriden completely

```lua
M.lspoveride = {
   n = {
      ["gd"] = { "<cmd> Telescope <CR>", "definitions" },
      ["gr"] = { "<cmd> Telescope <CR>", "references" },
   },
}
```

**Comment by siduck** [comment]
but those telescope commands you mentioned, were somehow using the default lsp commands? :thinking:

**Comment by curtbushko** [comment]
I stripped away all of my settings and started off with an almost empty chardrc, init.lua, mappings.lua, no plugins. I am able to get 'gr' to work the with telescope the way I want.

This is definitely in my settings somewhere. 

Thanks for taking the time to look at this and feel free to close the issue. When I figure it out, I will report back.

Thanks again!

**Comment by curtbushko** [comment]
It was 100% my fault. I was using the go plugin [ray-x/go.nvim](https://github.com/ray-x/go.nvim) and it was overriding the default lsp commands with its own. 😿

**Comment by dinno7** [comment]
> It was 100% my fault. I was using the go plugin [ray-x/go.nvim](https://github.com/ray-x/go.nvim) and it was overriding the default lsp commands with its own. 😿

How did you fix it?
Can we disable all or some of `go. nvim` keymapping s?
