### ISSUE TITLE
global var causing issues

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#1142]
So I have a script which reloads init.lua and my plugins_table into neovim whenever the file is written, but since core.utils was replaced with the global `nvchad` variable, the script fails, due to the fact that global variables are not accessible by sourcing or running something like `luafile <file>` or `lua require("<file>")`. when running such commands (important for debugging....)  nvchad will be a blank field and thus throw an error, even though it runs fine on startup.

Was there a particular reason core.utils was changed to be a global variable and have no return value? @siduck It's generally bad practice to use globals because of issues like the above, but if there was something it legitimately addresses I'll make sure that any changes don't cause a regression.

**Comment by siduck** [comment]
@zbirenbaum as core.utils functions were used everywhere, it was easier to type them when globals were used but yea ive heard many downsides from @Akianonymus as well. I will remove the globals once 
@LeonHeidelbach tests https://github.com/NvChad/NvChad/tree/dev

**Comment by zbirenbaum** [comment]
@siduck it was literally one line of bash to replace it in all the files so I went ahead and did so and PR'd it so you don't have to wait on that if you were worried about conflicts or something. You can just rebase it or replace all instances in that other branch by running this from the NvChad/lua directory:

`sed -i 's/nvchad\./require("core.utils")\./g' */*.lua *.lua */*/*.lua`

**Comment by LeonHeidelbach** [comment]
I'll have to agree with @zbirenbaum regarding globally scoped variables generally being a bad idea. I would also add that labels and `goto` invocations in any language are bad practice and should absolutely be avoided if possible (it always is). @siduck I'll have a look at your commit in a bit.

**Comment by siduck** [comment]
gotos are fine ._.

**Comment by zbirenbaum** [comment]
> gotos are fine imo ._.

@LeonHeidelbach I'm actually crying

**Comment by siduck** [comment]
> > gotos are fine imo ._.
> 
> @LeonHeidelbach I'm actually crying

how do I restart a loop in lua then? it doesnt have continue statements either

**Comment by zbirenbaum** [comment]
> > > gotos are fine imo ._.
> > 
> > 
> > @LeonHeidelbach I'm actually crying
> 
> how do I restart a loop in lua then? it doesnt have continue statements either

Use a while statement with an if statement? use recursion?

**Comment by siduck** [comment]
oh that'd add more complexity :l

**Comment by siduck** [comment]
goto looks simple to me 

![image](https://user-images.githubusercontent.com/59060246/170860742-c32994e7-9b27-4d78-8a76-c22a07aff651.png)

**Comment by zbirenbaum** [comment]
> oh that'd add more complexity :l

no it doesn't. The recursion in come cases. The while and if is much clearer from a maintainability perspective. This is a very, very, very established coding standard for a reason. goto's may seem innocent in some small scenario, but they quickly get out of hand and are universally avoided.

**Comment by siduck** [comment]
also i used it only once

**Comment by zbirenbaum** [comment]
> also i used it only once, it wont be used ever as the custom config implementation is complete as per the dev branch

It really doesn't matter. Anyone browsing the code base that sees that will be immediately turned off that we use such a bad coding practice in published code.

**Comment by LeonHeidelbach** [comment]
> > gotos are fine imo ._.
> 
> @LeonHeidelbach I'm actually crying
> 
> Technically they aren't avoidable in ASM, but I really doubt you are writing ASM @siduck ...

@zbirenbaum well yeah I agree, in assembly they are necessary of course since this is basically what a loop does :laughing:

**Comment by zbirenbaum** [comment]
@siduck Problem solved, no goto:

```
for section, section_mappings in pairs(mappings) do
  -- skip mapping this as its mapppings are loaded in lspconfig
  if section ~= "lspconfig" then
    for mode, mode_mappings in pairs(section_mappings) do
      for keybind, mapping_info in pairs(mode_mappings) do
        -- merge default + user opts

        local default_opts = merge_tb("force", { mode = mode }, mapping_opt or {})
        local opts = merge_tb("force", default_opts, mapping_info.opts or {})

        if mapping_info.opts then
          mapping_info.opts = nil
        end

        map_func(keybind, mapping_info, opts)
      end
    end
  end
end
```

**Comment by siduck** [comment]
@zbirenbaum i had given that a thought before but that adds more nest levels and looks unreadable kinda :/

**Comment by LeonHeidelbach** [comment]
> @siduck Problem solved, no goto:
> 
> ```
> for section, section_mappings in pairs(mappings) do
>   -- skip mapping this as its mapppings are loaded in lspconfig
>   if section ~= "lspconfig" then
>     for mode, mode_mappings in pairs(section_mappings) do
>       for keybind, mapping_info in pairs(mode_mappings) do
>         -- merge default + user opts
> 
>         local default_opts = merge_tb("force", { mode = mode }, mapping_opt or {})
>         local opts = merge_tb("force", default_opts, mapping_info.opts or {})
> 
>         if mapping_info.opts then
>           mapping_info.opts = nil
>         end
> 
>         map_func(keybind, mapping_info, opts)
>       end
>     end
>   end
> end
> ```

@siduck  @zbirenbaum I actually already wrote that in my comment :laughing: https://github.com/NvChad/NvChad/commit/1bc0b3e1a52a3a4c6a4d12533e6fb69ad36d9953#commitcomment-74817221

**Comment by siduck** [comment]
goto syntax looks smol and cute :smile: , i like it

**Comment by zbirenbaum** [comment]
@siduck I agree, but that's a result of the other code's shortcomings. I'm telling you from an objective professional software engineering perspective, that nested statement is so much more acceptable than the goto it's not even funny.

**Comment by LeonHeidelbach** [comment]
@zbirenbaum what can I say... This is absolutely true.

**Comment by zbirenbaum** [comment]
> goto syntax looks smol and cute smile , i like it

There's a satire book called how to write unmaintainable code with a whole section on how wonderful goto statements are for ensuring no one will ever want to touch it. That is not good practice at all, ever.

**Comment by LeonHeidelbach** [comment]
@zbirenbaum @siduck https://xkcd.com/292/ I know this one... :laughing:

**Comment by siduck** [comment]
@zbirenbaum @LeonHeidelbach  this works https://github.com/NvChad/NvChad/commit/f6b998dca490f96da376e75dcee17ba413735d8d

**Comment by siduck** [comment]
as lspconfig loads mappings separately here https://github.com/NvChad/NvChad/blob/dev/lua/plugins/configs/lspconfig.lua#L25

**Comment by LeonHeidelbach** [comment]
> @zbirenbaum @LeonHeidelbach this works [f6b998d](https://github.com/NvChad/NvChad/commit/f6b998dca490f96da376e75dcee17ba413735d8d)

@siduck sure, that's the same thing I did with the `M.groups` key :wink:

**Comment by siduck** [comment]
@LeonHeidelbach the dev branch works? I tested it and it works here

**Comment by zbirenbaum** [comment]
> as lspconfig loads mappings separately here https://github.com/NvChad/NvChad/blob/dev/lua/plugins/configs/lspconfig.lua#L25

Make sure that the lsp keys still get set when doing this. You may be editing the original copy.

**Comment by siduck** [comment]
> > as lspconfig loads mappings separately here https://github.com/NvChad/NvChad/blob/dev/lua/plugins/configs/lspconfig.lua#L25
> 
> Make sure that the lsp keys still get set when doing this. You may be editing the original copy.

im aware, it works

**Comment by zbirenbaum** [comment]
> > > as lspconfig loads mappings separately here https://github.com/NvChad/NvChad/blob/dev/lua/plugins/configs/lspconfig.lua#L25
> > 
> > 
> > Make sure that the lsp keys still get set when doing this. You may be editing the original copy.
> 
> im aware, it works

Ok sounds good.

**Comment by LeonHeidelbach** [comment]
@siduck unfortunately it does not seem to work for me...

![Screenshot_20220529_112828](https://user-images.githubusercontent.com/55194243/170861359-1e89ee2b-a8d7-4d68-b7cb-e6fd9ad404f0.png)

**Comment by siduck** [comment]
@LeonHeidelbach 
![image](https://user-images.githubusercontent.com/59060246/170861372-7c0aea2b-fb98-48e0-bd71-b2a68b879acb.png)

same syntax as before xd

**Comment by LeonHeidelbach** [comment]
@siduck ah okay :smile:

**Comment by LeonHeidelbach** [comment]
@siduck it seems to work now at first glance :+1:. The lags are gone, they were caused by me having an extensive custom "mappings.lua" and calling the `disabled_keys` function so many times on buffer load.

**Comment by siduck** [comment]
@LeonHeidelbach  that random jumbling of mappings in whichkey popup too fixed?

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach that random jumbling of mappings in whichkey popup too fixed?

@siduck yes, it seems so. At least I haven't seen it with the group names anymore.

**Comment by siduck** [comment]
hmm good to merge then, :lesssgoooooo:

**Comment by LeonHeidelbach** [comment]
> hmm good to merge then, :lesssgoooooo:

I guess so :smile: I'll let you know if I find any issues down the line. Since we don't have any unit tests we'll have to find out if everything works by the amount of new issues we get :rofl:

**Comment by LeonHeidelbach** [comment]
@zbirenbaum what are your thoughts on setting up a suite of unit test for NvChad, since breaking things will get more and more likely the langer the project becomes. I think the extra work would be worth it and spare us a lot of headaches. Is there a best practice on implementing unit tests in lua projects for nvim?

**Comment by siduck** [comment]
@zbirenbaum push the global var removal changes in the repo directly, no need to send PR for such smol fixes

**Comment by siduck** [comment]
and push the changes to the base46 & extensions repo too, i gotta go :shower:

**Comment by LeonHeidelbach** [comment]
> @zbirenbaum push the global var removal changes in the repo directly, no need to send PR for such smol fixes

@zbirenbaum when you do that, don't forget to put `BREAKING CHANGE` into your commit message.

**Comment by siduck** [comment]
> @siduck it was literally one line of bash to replace it in all the files so I went ahead and did so and PR'd it so you don't have to wait on that if you were worried about conflicts or something. You can just rebase it or replace all instances in that other branch by running this from the NvChad/lua directory:
> 
> `sed -i 's/nvchad\./require("core.utils")\./g' */*.lua *.lua */*/*.lua`

![image](https://user-images.githubusercontent.com/59060246/170863273-e21cc470-a807-486f-ab25-dbac846241ee.png)

;((

**Comment by siduck** [comment]
ig i will have to manually change them
