### ISSUE TITLE
module 'packer' not found on fresh install

### ISSUE THREAD

**Issue by creep33** [NvChad/NvChad#1145]
**Describe the bug**

**To Reproduce**
1. I check my nvim version (NVIM v0.7.0)
2. I run the installation command sown in the website. (`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 ; nvim`)

**Expected behavior**
Nvchad installed and working.

**Actual behavior**
Packer not found error

**Screenshots**
![image](https://user-images.githubusercontent.com/30846349/170870531-3a4eb2b9-7678-4cd3-b7b8-cfcc11eac84d.png)

**Desktop (please complete the following information):**
 - Operating System -> Arch Linux
 - Terminal -> Alacritty
 - Version of Neovim (NVIM v0.7.0)

**Comment by siduck** [comment]
@LeonHeidelbach

**Comment by siduck** [comment]
this function causes it 
![image](https://user-images.githubusercontent.com/59060246/170871390-0bf9deb0-3285-4135-98c9-317ed8886cfc.png)


But we had this before too, never had this issue :/

**Comment by siduck** [comment]
@zbirenbaum is your recent commit related to this issue?

**Comment by siduck** [comment]
i reverted it, yes its related to that :/

**Comment by siduck** [comment]
should be fixed by now
