### ISSUE TITLE
Neoscroll doesn't work

### ISSUE THREAD

**Issue by wenanoshe** [NvChad/NvChad#1146]
**Describe the bug**
After update nvchad, neoscroll shows this errors
![image](https://user-images.githubusercontent.com/78445203/170878470-d6dff711-4a59-4afd-8e79-ca2c76310d5f.png)

This is my custom/plugins/init.lua
![image](https://user-images.githubusercontent.com/78445203/170878777-0af46cdb-b4a7-4770-b2b9-6934da121452.png)

**Desktop**
 - Archcraft
 - Alacritty terminal

**PD** Why in the main page https://nvchad.github.io/ has been removed the "extras" page?

**Comment by siduck** [comment]
the extra page was removed as it was not needed

**Comment by siduck** [comment]
globals have been removed soo use require("core.utils") instead of nvchad

**Comment by siduck** [comment]
https://github.com/rockerBOO/awesome-neovim use this instead for checking new plugins
