### ISSUE TITLE
which key menu has some missing glyphs

### ISSUE THREAD

**Issue by asher-gh** [NvChad/NvChad#1148]
**Describe the bug**
The `<leader> f` section in which key menu has some missing icons.
Tested with different nerd fonts (custom patched and direct from the nerd font repo).

**Screenshots**
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/74317567/170880320-59e3b2b2-de21-4c3d-bc8e-a76d16595fd7.png">

**Comment by siduck** [comment]
install nerdfonts and set it in your terminal

**Comment by asher-gh** [comment]
> install nerdfonts and set it in your terminal

I'm using nerdfonts but still these glyphs are missing. The icons are nvimtree are as should be
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/74317567/170889361-5fb2f843-42a6-4111-b6c2-225db060d0a5.png">

**Comment by siduck** [comment]
i hope you are not using iterm2 :/

**Comment by asher-gh** [comment]
> i hope you are not using iterm2 :/

Yes and confirmed that it is in iterm only. Heres a screenshot with kitty
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/74317567/170929977-24aba02d-b967-437e-9262-a5b4a280334b.png">

**Comment by siduck** [comment]
show your iterm2 font name

**Comment by asher-gh** [comment]
patched cascadia code. But I've tried with other nerd fonts.
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/74317567/170935225-d0793413-b105-4e46-b869-8a9b3bfb02c9.png">

**Comment by siduck** [comment]
try JetbrainsMono Nerd font

**Comment by asher-gh** [comment]
No luck. Thanks a lot for helping out though. I was thinking of moving to kitty. This was the final push I needed.
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/74317567/170935632-639d8213-734a-4e06-86b7-e3d5be8bbe24.png">

**Comment by siduck** [comment]
@asher-gh you can try alacritty or wezterm too

**Comment by siduck** [comment]
havent tried this https://www.warp.dev/ but looks fancy

**Comment by asher-gh** [comment]
I've tried alacrity but they don't support ligatures. Haven't tried wezterm though, have heard a lot about it.
Was thinking of trying warp but a its not open source and the features are not that compelling to me. If only they would add a markdown renderer like that in notion or obsidian, I would switch to it.

**Comment by siduck** [comment]
oh you can use glow to render markdown in terminal and glow.nvim for nvim but its limited. I use neorg for notetaking, todo etc stuff

**Comment by asher-gh** [comment]
> oh you can use glow to render markdown in terminal and glow.nvim for nvim but its limited. I use neorg for notetaking, todo etc stuff

I'll surely check these out later. Thanks a lot.
