### ISSUE TITLE
mappings randomly stop working

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1149]
### **Describe the bug**
As a title above. This also happens with default nvchad **_builtin_** & **_custom_** mappings. Introduced after #1144 

### **To Reproduce**
https://user-images.githubusercontent.com/73665622/170886102-c5be3424-9d75-4223-abf3-fdc8ab35a045.mp4

some of the key custom/builtin mappings in the video above don’t work such as `<S-l>`, `<S-h>`, `<C-n>` and so on.

### **Desktop (please complete the following information):**
 - Ubuntu 20
 - Wezterm
 - NVIM v0.7.0/v0.7.1-dev

### **Additional context**
I disable `whichkey`.

**Comment by GreatestOfAllTimee** [comment]
`C-s` save file seems like not working too.

**Comment by ThatOneOcto** [comment]
Bumping this ticket because my mappings don't work either, *(for me I've noticed it's only opening new buffers and tabs)*

**Comment by GreatestOfAllTimee** [comment]
Same, this does not happens to specific mappings (random).

**Comment by siduck** [comment]
show your chadrc

**Comment by siduck** [comment]
I cannot reproduce it

**Comment by siduck** [comment]
C-n is the builtin mapping, idk about S-h or S-l

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/170900843-04a87e9b-0797-48b5-ba94-a02a9c683cc1.mp4

**Comment by tomasky** [comment]
I think people should publish their mappings file, so we can test them,and i think the mappings  should contain two modes(which-key or not),and can switch by setting `true` or `false`

**Comment by tomasky** [comment]
@siduck  `require "custom" ` in  example/chadrc.lua .

**Comment by siduck** [comment]
oh yea @tomasky

**Comment by siduck** [comment]
works now? @GreatestOfAllTimee

**Comment by tomasky** [comment]
@siduck   i think nvchad's mappings  should contain two modes(which-key or not),and can switch by setting `true` or `false`

**Comment by siduck** [comment]
@tomasky everything works here for me after removing that require "custom", can you check at your end?

**Comment by siduck** [comment]
i can reproduce this issue only when requiring custom in chadrc, removed that line in example chadrc. Please try again :/

**Comment by tomasky** [comment]
I've never had that problem

**Comment by tomasky** [comment]
I think every time   release a breaking change,   should release the documentation first

**Comment by siduck** [comment]
only 2-3 days till v0.2 gigachad releases so wait up!

**Comment by GreatestOfAllTimee** [comment]
> C-n is the builtin mapping, idk about S-h or S-l

Like I said above, there does not happens on specific mappings. S-l and S-h is my custom mappings. I will provide my config file later

**Comment by GreatestOfAllTimee** [comment]
#### `custom/chadrc.lua`

<details>

```lua
-- local hl = require "custom.plugin.hightlightt"
local userPlugins = require "custom.install_plugins"
local override_plugin = require "custom.plugin.override"
local M = {}

--- UI configuration
M.ui = {
   --- File path which contains highlight
   -- hl_override = hl,
   transparency = true,
   theme = "tokyonight",
   theme_toggle = { "tokyonight", "kanagawa" },
}

M.options = {
   -- enable_new_mappings = true,
   user = function()
      require "custom.options"
   end,
}

-- NvChad included plugin options & overrides
M.plugins = {
   options = {
      lspconfig = {
         setup_lspconf = "custom.plugin.lspconfig",
      },

      statusline = {
         --- default, round , slant , block , arrow
         seperator_style = "default",
      },
   },

   override = {
      ["nvim-treesitter/nvim-treesitter"] = override_plugin.treesitter,
      ["numToStr/Comment.nvim"] = override_plugin.comment,
      ["NvChad/nvterm"] = override_plugin.nvterm,
   },

   remove = {
      "numToStr/Comment.nvim",
   },

   user = userPlugins,
}

M.mappings = require "custom.mappings"

return M
```

</details

#### `custom/mappings.lua`

<details>

```lua
local M = {}

M.disable = {
   n = {
      -- ["<A-h>"] = "",
      -- ["<A-v>"] = "",
      -- ["<leader>ra"] = "",
      "<C-c>", -- no difference if comment this 
      -- ["<C-c>"] = "", no difference if uncomment this 
      -- ["<C-h>"] = "",
      -- ["<C-l>"] = "",
      -- ["<C-j>"] = "",
      -- ["<C-k>"] = "",
   },
}

M.general = {
   n = {
      ["<leader>ra"] = { "<cmd> set rnu! <CR>" },
      ["<leader>cf"] = { "<cmd> %y+ <CR>" },

      ["<C-h>"] = { "<C-w>h" },
      ["<C-l>"] = { "<C-w>l" },
      ["<C-j>"] = { "<C-w>j" },
      ["<C-k>"] = { "<C-w>k" },
   },

   i = {
      ["<C-a>"] = { "<ESC>^i" },
   },
}

M.lspconfig = {
   n = {
      ["K"] = { "<cmd>Lspsaga hover_doc <CR>" },
      ["<leader>rn"] = { "<cmd> :Lspsaga rename <CR>" },
      ["<leader>ca"] = { "<cmd> :Lspsaga code_action <CR>" },
      ["[d"] = { "<cmd> :Lspsaga diagnostic_jump_next <CR>" },
      ["]d"] = { "<cmd> :Lspsaga diagnostic_jump_prev <CR>" },
      ["gr"] = { "<cmd> :lua vim.lsp.buf.references() <CR>" },
      ["gd"] = { "<cmd> :lua vim.lsp.buf.definition() <CR>" },
      ["gD"] = { "<cmd> :lua vim.lsp.buf.declaration() <CR>" },
      ["ge"] = { "<cmd> :Lspsaga show_line_diagnostics <CR>" },
      ["<A-m>"] = { "<cmd> :lua require('lspsaga.action').smart_scroll_with_saga(-1, '<c-u>') <CR>" },
      ["<A-n>"] = { "<cmd> :lua require('lspsaga.action').smart_scroll_with_saga(1, '<c-d>') <CR>" },
      ["gk"] = {
         function()
            vim.lsp.buf.signature_help()
         end,
      },

      ["gi"] = {
         function()
            vim.lsp.buf.implementation()
         end,
      },

      ["<leader>fm"] = {
         function()
            vim.lsp.buf.formatting()
         end,
      },

      ["<leader>q"] = {
         function()
            vim.diagnostic.setloclist()
         end,
      },

      ["<leader>D"] = {
         function()
            vim.lsp.buf.type_definition()
         end,
      },

      ["<leader>wa"] = {
         function()
            vim.lsp.buf.add_workspace_folder()
         end,
      },

      ["<leader>wr"] = {
         function()
            vim.lsp.buf.remove_workspace_folder()
         end,
      },

      ["<leader>wl"] = {
         function()
            print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
         end,
      },
   },
}

M.telescope = {
   n = {
      ["<leader>cc"] = { "<cmd> Telescope <CR>" },
      ["<leader>W"] = { "<cmd> Telescope terms <CR>" },
      ["<leader>fr"] = { "<cmd> Telescope resume <CR>" },
   },
}

M.move = {
   n = {
      ["H"] = { "^" },
      ["L"] = { "$" },
   },
   v = {
      ["K"] = { ":m '<-2<CR>gv=gv" },
      ["J"] = { ":m '>+1<CR>gv=gv" },
   },
}

M.screen = {
   n = {
      ["<A-v>"] = { "<cmd>vs<CR>" },
      ["<A-a>"] = { "<cmd>sp<CR>" },
      ["<A-k>"] = { "<cmd>resize +2 <CR>" },
      ["<A-j>"] = { "<cmd>resize -2 <CR>" },
      ["<A-h>"] = { "<cmd>vertical resize +2 <CR>" },
      ["<A-l>"] = { "<cmd>vertical resize -2 <CR>" },
      ["<leader>cd"] = { "<cmd>cd %:p:h<CR>:pwd" },
   },
}

M.truezen = {
   n = {
      ["<leader>ta"] = { "<cmd> TZAtaraxis<CR>" },
   },
}

M.bufferline = {
   n = {
      ["<A-=>"] = { "<cmd>BufferLineMoveNext <CR>" },
      ["<A-->"] = { "<cmd>BufferLineMovePrev <CR>" },
   },
}

return M
```

</details

**Comment by siduck** [comment]
@GreatestOfAllTimee  these work fine for me 

![image](https://user-images.githubusercontent.com/59060246/170931815-58dc9b87-5b40-4c04-ae46-50f0cadee474.png)

**Comment by GreatestOfAllTimee** [comment]
> simplescreenrecorder-2022-05-30_06.48.49.mp4

this is fresh install, try add custom mappings and maybe some basic configuration in your config chadrc file.

Regarding to this video I found a **new bug**. If you `require("core.utils").load_mappings()` at the top all the rest configuration below will be ignore. **Example:**

https://user-images.githubusercontent.com/73665622/170932076-da6b67ea-9d15-420a-b6ae-ab2d8b97ba8b.mp4

**Again** in this video some of mappings not working, keep in mind, I believe this does not happens on specific mappings (random).

**Comment by GreatestOfAllTimee** [comment]
> @GreatestOfAllTimee these work fine for me
> 
> ![image](https://user-images.githubusercontent.com/59060246/170931815-58dc9b87-5b40-4c04-ae46-50f0cadee474.png)

try to remove whichkey

**Comment by siduck** [comment]
@GreatestOfAllTimee thx , reproduced it. Btw can u try this?

![image](https://user-images.githubusercontent.com/59060246/170934682-1b577ad5-0b2b-469f-8905-86cc43196282.png)

put it in main init.lua file, If this works then non whichkey users shouldnt even add this function in their init.lua

**Comment by siduck** [comment]
yes it works, making this change right away :zap:

**Comment by GreatestOfAllTimee** [comment]
![image](https://user-images.githubusercontent.com/73665622/170938042-03e59a38-4eab-4e1c-8c96-94eea7400e36.png)

what's are those?

**Comment by siduck** [comment]
did you update the config?

**Comment by siduck** [comment]
and did a packersync?

**Comment by siduck** [comment]
something's issue in your custom mappings. reproduce the error with vanilla nvchad

**Comment by GreatestOfAllTimee** [comment]
> did you update the config?

which config?

> and did a packersync?

`<leader>uu` come with `PackerSync` but after exit vim try to packersync but not found

####  `:PackerSync` not recognize.
![image](https://user-images.githubusercontent.com/73665622/170938377-fe56f25b-eaf7-4e51-bd70-0d62136ba868.png)

**Comment by siduck** [comment]
did you do leader uu?

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/170939399-765e2943-5409-4383-a85b-bc9ac30b6df9.mp4

works here

**Comment by GreatestOfAllTimee** [comment]
> did you do leader uu?

yes I did.

> simplescreenrecorder-2022-05-30_12.52.54.mp4
> 
> works here

no you didn't have custom/mappings file.

I can confirm it works after remove `M.mappings = require "custom.mappings"` in custom/chadrc.lua

**Comment by GreatestOfAllTimee** [comment]
lol how can you close an issue without waiting for feedback 😆

**Comment by siduck** [comment]
> lol how can you close an issue without waiting for feedback laughing

because it works here

https://user-images.githubusercontent.com/59060246/170943547-2dc53663-ff4b-4056-b908-d895566a845d.mp4

**Comment by siduck** [comment]
try my custom mappings 
 ```lua
 local M = {}

M.truzen = {
   n = {
      ["<leader>ta"] = { "<cmd> TZAtaraxis <CR>", "   truzen ataraxis" },
      ["<leader>tm"] = { "<cmd> TZMinimalist <CR>", "   truzen minimal" },
      ["<leader>tf"] = { "<cmd> TZFocus <CR>", "   truzen focus" },
   },
}

M.treesitter = {
   n = {
      ["<leader>cu"] = { "<cmd> TSCaptureUnderCursor <CR>", "  find media" },
   },
}

M.shade = {
   n = {
      ["<leader>s"] = {
         function()
            require("shade").toggle()
         end,

         "   toggle shade.nvim",
      },
   },
}

return M
```

**Comment by siduck** [comment]
lets see if it works, if it does then there's definitely something wrong in your custom mappings

**Comment by tomasky** [comment]
here `<cmd> :`  ,  is  this ok?
```lua
M.lspconfig = {
   n = {
      ["K"] = { "<cmd>Lspsaga hover_doc <CR>" },
      ["<leader>rn"] = { "<cmd> :Lspsaga rename <CR>" },
      ["<leader>ca"] = { "<cmd> :Lspsaga code_action <CR>" },
      ["[d"] = { "<cmd> :Lspsaga diagnostic_jump_next <CR>" },
      ["]d"] = { "<cmd> :Lspsaga diagnostic_jump_prev <CR>" },
      ["gr"] = { "<cmd> :lua vim.lsp.buf.references() <CR>" },
      ["gd"] = { "<cmd> :lua vim.lsp.buf.definition() <CR>" },
      ["gD"] = { "<cmd> :lua vim.lsp.buf.declaration() <CR>" },
      ["ge"] = { "<cmd> :Lspsaga show_line_diagnostics <CR>" },
      ["<A-m>"] = { "<cmd> :lua require('lspsaga.action').smart_scroll_with_saga(-1, '<c-u>') <CR>" },
      ["<A-n>"] = { "<cmd> :lua require('lspsaga.action').smart_scroll_with_saga(1, '<c-d>') <CR>" },
```

**Comment by GreatestOfAllTimee** [comment]
sorry late reply, just returned from work outside.

> because it works here, tested it plenty of times . idk how can you even get such error :l

I had chance to try you custom config:

<details>

```lua
local M = {}

M.truzen = {
  n = {
     ["<leader>ta"] = { "<cmd> TZAtaraxis <CR>"},
     ["<leader>tm"] = { "<cmd> TZMinimalist <CR>"},
     ["<leader>tf"] = { "<cmd> TZFocus <CR>"},
  },
}

M.treesitter = {
  n = {
     ["<leader>cu"] = { "<cmd> TSCaptureUnderCursor <CR>"},
  },
}

return M

```
</details

and it works. I don't how you **_'tested plenty of times'_** but if you try to disable some mappings in won't work. 🤣 

#### Example:

<details>

``` lua
local M = {}

...

M.disable = {
   n = {
      ["<leader>ra"] = "", -- Comment this does not make a difference
      -- "<leader>ra",  -> un-comment this does not make a difference
   },
}

...

return M
```
</details>

**Comment by GreatestOfAllTimee** [comment]
oh yah that was my mistake, not `disable` but `disabled` 🏃

**Comment by siduck** [comment]
:(
