### ISSUE TITLE
Stop characters deleted in normal mode being added to the clip board

### ISSUE THREAD

**Issue by ThatOneOcto** [NvChad/NvChad#1150]
How can I stop characters in normal mode being added to the clipboard, I only want yanked characters to be added, I do have GVIM installed so that's probably the reason why it goes into the clipboard because I remember using GVIM on my config to add yanked stuff to the system clipboard, how can I stop x, d, del, shift-v + del *(etc)* being added to the clipboard and how can I add a specific keybind to delete but add to the clipboard

**Comment by siduck** [comment]
copy them with y?

**Comment by ThatOneOcto** [comment]
I know I can copy them with y but when I delete characters normally they get added to the clipboard even though I don't want them to

**Comment by siduck** [comment]
For now put this in your custom init.lua 

```lua
vim.cmd [[ 
nnoremap d "_d
vnoremap d "_d
]
```

**Comment by siduck** [comment]
https://stackoverflow.com/questions/11993851/how-to-delete-not-cut-in-vim

**Comment by siduck** [comment]
convert them into lua later

**Comment by honeyspoon** [comment]
this is not what we are asking
we want dd to cut
we want to have different registers for vim and for the clipboard
we want them separate

this way we can copy something outside of vim
cut something in vim
paste it with p
and the clipboard stays the same

**Comment by siduck** [comment]
> this is not what we are asking we want dd to cut we want to have different registers for vim and for the clipboard we want them separate
> 
> this way we can copy something outside of vim cut something in vim paste it with p and the clipboard stays the same

revert the action of clipboard+=unamedplus then? we do it in the core/init.lua
