### ISSUE TITLE
Do slant separators on bufferline look better than the current one?

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1152]
![image](https://user-images.githubusercontent.com/59060246/170915725-fe01ce98-2e6d-40ed-87b4-42f9f10f8639.png)
![image](https://user-images.githubusercontent.com/59060246/170915729-8477d447-1808-4615-af64-89427643687b.png)

**Comment by siduck** [comment]
@tomasky

**Comment by tomasky** [comment]
Sorry ,I like the present one,dont like this ,Looks like a lot of space
