### ISSUE TITLE
A way to configure/override `vim.diagnostics.config`

### ISSUE THREAD

**Issue by cusxio** [NvChad/NvChad#1153]
Currently, there isn't a way to disable `virtual_text` as it's hard coded here,

https://github.com/NvChad/NvChad/blob/70390c6e8dc78b939d132326cd8de4e9f5dc3752/lua/plugins/configs/others.lua#L170-L172

I tried to put the following code in `custom/init.lua`, or `custom/chadrc.lua`, but it seems that the code above still takes precedence

```lua
vim.diagnostics.config({ virtual_text = false })
```

The reason why I want to disable `virtual_text` is because I would like to try out [trouble.nvim](https://github.com/folke/trouble.nvim)

**Comment by siduck** [comment]
override it by copying default lsp_handlers function into your custom lspconfig file

**Comment by cusxio** [comment]
That worked, thank you.
