### ISSUE TITLE
cant  override autopairs plugin config

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#1154]
**Describe the bug**
cant  override autopairs plugin config
i want to override fast_wrap key map

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
how are you overriding? please share your config, i cant know anything without it :/

**Comment by tomasky** [comment]
```lua
M.autopairs = {
   fast_wrap = {
      map = "<M-l>",
   },
}
```
