### ISSUE TITLE
How to replicate Webstorm-like tooltips on keypress (peek definition?)

### ISSUE THREAD

**Issue by spacegoldminer** [NvChad/NvChad#1156]
I am missing this tooltip feature of webstorm, that i could hover (in nvim we could press a key maybe) and have all this information appear.

I have enabled lsp servers (tsserver, eslint, css) and i cannot get that.

Is it possible and if so, how?

https://user-images.githubusercontent.com/106533249/170997009-c1754f19-4e07-48b9-934b-f8232c3fd07f.mp4

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/170997584-a4c2fb9b-a550-4395-a17b-d151e79d2bd9.png)

you mean this?

**Comment by siduck** [comment]
https://github.com/neovim/neovim/pull/12178

**Comment by siduck** [comment]
> this would be lsp hover in neovim ig

peek definition shows more info, for example hovering on the display here shows this : 

![image](https://user-images.githubusercontent.com/59060246/171004831-4105b2ba-3210-4ac7-8caa-730147a91d10.png)

**Comment by spacegoldminer** [comment]
> it doesn't really peak definition (show code where definition is) though or does it?

The Webstorm one is not peak definition (show definition), its more like documentation, and when you hover css classes you can see what they contain.

Maybe if i use coc.nvim as language server, i could get something like this?

(I am under the impression that these are stuff the language server provides, but i maybe wrong)
