### ISSUE TITLE
After updating today, my theme colors are not displayed correctly

### ISSUE THREAD

**Issue by dan003400** [NvChad/NvChad#1166]
Updated to latest master today and colors for the nightowl theme are no longer displaying correctly, I will attach a before and after screenshot.

Before:
![IMG_7595](https://user-images.githubusercontent.com/1211542/171511875-bcbd8503-83e6-4efb-8151-896519365a0b.png)

After:
![IMG_0856](https://user-images.githubusercontent.com/1211542/171511897-f48177e3-0842-4ecb-ae2e-0f5cc4755357.png)

Thanks!

**Comment by AlexanderHOtt** [comment]
I noticed this too.

**Comment by dan003400** [comment]
@AlexanderHOtt - does this seem like a treesitter issue?

**Comment by siduck** [comment]
i will fix this, gimmie some  time

**Comment by dan003400** [comment]
Any idea what the issue is? Looks like a lot has changed the last few days on master.

**Comment by siduck** [comment]
> Any idea what the issue is? Looks like a lot has changed the last few days on master.

i changed its color to white and its highlight group is TSField, The children fields in it are of TSFIeldKey highlight group


![image](https://user-images.githubusercontent.com/59060246/171564365-f1cfc935-32e6-4fc0-a8ea-7685ea23a7a9.png)

So M.options here is the TSField and its nested fields  have TSFIeldKey, I set TSField color to white and TSFIeldKey to red, you can check

**Comment by siduck** [comment]
but the screenshot is new, I changed that behaviour

**Comment by dan003400** [comment]
Understood, how would we get back to the functionality we had before?

I'm not sure I understand what you mean by the screenshot is new?

**Comment by siduck** [comment]
for a temporary solution do this : 
 
 ```lua
-- chadrc.lua

M.ui = {
   hl_override =  require "custom.highlights"
}
```

```lua
-- custom.highlights.lua

 return {
   LuaTSFieldr =  {
    fg = "red",
   }
}
 ```
 
 highlights.lua just needs to return a table

**Comment by siduck** [comment]
docs for overriding default or adding new highlight groups & their colors 

https://github.com/NvChad/nvchad.github.io/blob/src/docs/config/Custom%20config.md#override-default-highlights

**Comment by dan003400** [comment]
Gotcha, and will this be specific to lua code? Because I am seeing this similar issue on all languages now?

**Comment by siduck** [comment]
ooh thats weird, I just changed luatsfield. Does replacing it with just TSField work?

**Comment by dan003400** [comment]
Not sure I understand what you mean exactly.

**Comment by siduck** [comment]
> for a temporary solution do this :
> 
> ```lua
> -- chadrc.lua
> 
> M.ui = {
>   hl_override =  require "custom.highlights"
> }
> ```
> 
> ```lua
> -- custom.highlights.lua
> 
>  return {
>    LuaTSField =  {
>     fg = "red",
>    }
> }
> ```
> 
> highlights.lua just needs to return a table

replace luatsfield with TSField here

**Comment by siduck** [comment]
lemme add a quick fix, wait

**Comment by siduck** [comment]
@dan003400 check now

**Comment by dan003400** [comment]
Ran `:PackerSync`, but this only changed the way lua files look, they also do not look the same as they did in the past.

All other files are still not working, I am still confused to what changed and how we can put it back to the way it was a few days ago?

It would appear this change is not properly syntax highlighting all file types when using the nightowl theme.

**Comment by siduck** [comment]
its the same as past now, can you send before and after image?

**Comment by siduck** [comment]
i tweaked nightowl theme recently btw

**Comment by siduck** [comment]
@dan003400 can you share the file? i want to test it here

**Comment by dan003400** [comment]
Here is what that same file looks like after that change:

![image](https://user-images.githubusercontent.com/1211542/171724408-da2b111d-c0b8-4465-bf06-3ab14dc2eb67.png)

**Comment by siduck** [comment]
hmm looks almost the same, just use the old hex color . maybe this #96CEB4

**Comment by dan003400** [comment]
Hmm, not sure that is the correct hex.

After switching back to this, it's looking more like the nightowl theme.

https://github.com/NvChad/base46/commit/1e803fd654acb4ab9b4e6c1a02fd4f205302f7a5#diff-8aa81dd6d81a705f283c085464dccc18e16fa6a48de17ca60f0167adfbc949ceL38
