### ISSUE TITLE
Feline error processing statusline component for .edge file

### ISSUE THREAD

**Issue by baddri** [NvChad/NvChad#1169]
**Describe the bug**
Feline error processing statusline component for .edge file

**To Reproduce**
1. open file with .edge extension
2. boom

**Expected behavior**
does not error.

**Screenshots**
![Screenshot from 2022-06-03 01-49-44](https://user-images.githubusercontent.com/49059318/171713066-66f1748e-5535-49ae-a0b5-1b3472ea2654.png)

**Desktop (please complete the following information):**
 - Operating System : Ubuntu 22.04 LTS x86_64
 - Terminal : Kitty
 - Version of Neovim : NVIM v0.8.0-dev+334-ge9803e1de

**Additional context**
other types of files work just fine

**Comment by siduck** [comment]
update nvchad config again, i fixed the edgecase in latest commit

**Comment by baddri** [comment]
still error. probably someting else

**Comment by siduck** [comment]
Do leader uu and packersync

**Comment by siduck** [comment]
Oh lol the error looks unrelated, your system doesn't have glibc package ._.
