### ISSUE TITLE
Incorrectly mapping ctrl, alt, and shift for custom keymaps.

### ISSUE THREAD

**Issue by AlexanderHOtt** [NvChad/NvChad#1171]
**Describe the bug**
Defining a keymap with `C-b` results in the key combo <kbd>C</kbd> + <kbd>-</kbd>+<kbd>b</kbd> being added, not <kbd>ctrl</kbd>,<kbd>b</kbd>

**To Reproduce**
1. Add a custom mapping in `chardrc.mappings` with <kbd>ctrt</kbd>, <kbd>alt</kbd>, or <kbd>shift</kbd>
2. `:WhichKey` then <kbd>C</kbd>
3. The <kbd>-</kbd> key will be marked as a prefix

**Expected behavior**
The keymap gets mapped to <kbd>ctrl</kbd>,<kbd>b</kbd>

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Windows WSL2 Ubuntu
 - Terminal: Windows Terminal
 - Version of Neovim: 0.7

**Comment by siduck** [comment]
how are you defining them?

**Comment by siduck** [comment]
it works fine here

**Comment by mculp** [comment]
"works on my machine"

**Comment by AlexanderHOtt** [comment]
My current mappings are
```lua
M.general = {
   v = {
      -- Move text
      ["<M-k>"] = { "<ESC>:m .-2<CR>gv", "   Move text up" },
      ["<M-j>"] = { "<ESC>:m .+1<CR>gv", "   Move text down" },

      -- Stay in visual line mode for < and >
      [">"] = { ">gv", "   Indent" },
      ["<"] = { "<gv", "   Dedent" },

      -- Keep yanked text on paste
      ["p"] = { '"_dP', "   Paste" },
   },

   n = {
      ["M-k"] = { ":m .-2<CR>", "   Move text up" },
      ["M-j"] = { ":m .+1<CR>", "   Move text down" },
   },

}
```
and `:WhichKey M` brings up a sub-menu for the `-` character.
![image](https://user-images.githubusercontent.com/66271487/172549407-f3396e68-4aa9-40c5-8803-7053e9e1a4ea.png)

**Comment by AlexanderHOtt** [comment]
Ah, I see my issue, I was using `"M-k"` and not `<"M-k">`

**Comment by siduck** [comment]
> Ah, I see my issue, I was using `"M-k"` and not `<"M-k">`

please check your custom configs well before making an issue D:
