### ISSUE TITLE
How to configure pylsp with NvChad?

### ISSUE THREAD

**Issue by JinraeKim** [NvChad/NvChad#1181]
I've read the docs but I'm struggling with configuring LSP stuff.
I tried to add `pylsp` but I cannot understand how to add "conditional" configurations.

For example, I tried to add some ignores but it seems to not work.

```
   for _, lsp in ipairs(servers) do
      lspconfig[lsp].setup {
         on_attach = function(client, bufnr)
            attach(client, bufnr)
            -- change gopls server capabilities
            if lsp == "pylsp" then
              client.ignore={'E501', 'E231'}
               -- client.resolved_capabilities.document_formatting = true
               -- client.resolved_capabilities.document_range_formatting = true
            end
         end,
         capabilities = capabilities,
      }
```

If there is any place to discuss how to use it instead of reporting issue, please let me know

**Comment by siduck** [comment]
no need to add condition lsp

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/172349067-f04f2088-2331-4ef9-aef1-bb876a397a34.png)

For example this is my custom lspconfig

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/172349254-07e3a34e-644e-4667-837d-51efbc30c9ef.png)

these are our communities , check readme

**Comment by JSilva6** [comment]
https://nvchad.github.io/config/Lsp%20stuff
