### ISSUE TITLE
Can't override telescope defaults mappings

### ISSUE THREAD

**Issue by kiyonlin** [NvChad/NvChad#1182]
**Describe the bug**
I wanted to add [Mapping <Esc> to quit in insert mode](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#mapping-esc-to-quit-in-insert-mode), but I failed cuz I can't `require telescope.actions` at that moment.

**To Reproduce**
1. Go to `chadrc.lua`
2. Override telescope's default config

```
-- failed here
local actions = require('telescope.actions')

M.plugins = {
  override = {
["nvim-telescope/telescope.nvim"] = {
  defaults = {
    mappings = {
      i = {
        ["<ESC>"] = actions.close,
      },
    },
  },
  }
  }
}
```

**Expected behavior**
Override telescope defaults mappings.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System MacOS
 - Terminal iterm2
 - Version of Neovim 0.7

**Comment by siduck** [comment]
did u do packersync

**Comment by kiyonlin** [comment]
> did u do packersync

Yes I did. But `Telescope` lazy loaded by `cmd = 'Telescope'`, maybe that's the reason?

**Comment by siduck** [comment]
I don't think that should  be the issue

**Comment by tomasky** [comment]
default nvchad config and neovim0.7,  this mapping is working .

```lua
--custom/chadrc.lua
local M = {}
 

M.ui = {
   theme = "gruvchad",
}
local actions = require('telescope.actions')

M.plugins = {
  override = {
    ["nvim-telescope/telescope.nvim"] = {
      defaults = {
        mappings = {
          i = {
            ["jkq"] = actions.close,
          },
        },
      },
    }
  }
}
return M
```

**Comment by kiyonlin** [comment]
I tested on my windows PC and it worked. I'll try it again on my mbp tonight to see if it works properly.
Thank you guys!

**Comment by tomasky** [comment]
> I tested on my windows PC and it worked. I'll try it again on my mbp tonight to see if it works properly. Thank you guys!

You dont need to map any key, just press `jkq` ,it is also working .

**Comment by kiyonlin** [comment]
> You dont need to map any key, just press `jkq` ,it is also working .

But I also want to map other keys like <c-j> and <c-k> for next and prev 😄 and more other mappings.
