### ISSUE TITLE
VS Code Neovim Plugin recommend add-in

### ISSUE THREAD

**Issue by AjayShanker-geek** [NvChad/NvChad#1185]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to use [VSCode neovim plugin](https://github.com/vscode-neovim/vscode-neovim) config to my `nvim/lua/custom`. What would the example configs be?

Feel free to share your configs for vscode too.

**Comment by GreatestOfAllTimee** [comment]
I guess he is using vscode with neovim extension and want to use nvchad as neovim plugins. @AjayShanker-geek nvchad are not for vscode, and if im not wrong vscode-neovim are _not suitable with most of the neovim plugins_ (especially ui plugins).
