### ISSUE TITLE
how to set different contrast mode for gruvbox theme

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1192]
**Is your feature request related to a problem? Please describe.**
in my previous vim config i just need to add three line
`colorscheme gruvbox 
set termguicolors
set background=dark
let g:gruvbox_contrast_dark='hard'
`
 and i can change the contrast of gruvbox theme very easily but now i do not know how to do it plz be kind on this noob here :)

**Describe the solution you'd like**
just wanna set high contrast mode for gruvbox theme

**Describe alternatives you've considered**
vim.cmd([[

set background=dark
let g:gruvbox_contrast="hard"
set termguicolors

]])

local g = vim.g
local opt = vim.opt

g.gruvbox_contrast_dark = "soft" -- hard contrast mode for gruvobx
opt.background = "dark"           -- make sure dark mode is used

in chadrc.lua file but it did not work

**Comment by siduck** [comment]
because we dont use the gruvbox.vim colors bruh :l

**Comment by siduck** [comment]
you just get to use gruvbox dark,material, light. Feel free to add a PR for the other contrasts

**Comment by LeonHeidelbach** [comment]
@siduck @Aneeqasif We could make an option available to our user that let’s them change the Hue Saturation and Lightness (HSL) values using my new custom color tools library I implemented a couple of days ago. This would make it very easy to change the entire look of a theme just by adding some fields in `chadrc.lua`. It would also work for all themes. We could introduce new keys that users can set which increase individual HSL values for all theme colors if the input numbers are positive or decrease them if they are negative ones. The values are percentage values. I already built the tools for this in [colors.lua](https://github.com/NvChad/base46/blob/674d6bb3c41ec3c0068e7d94b21596133b15998f/lua/base46/colors.lua#L125), so you would only have to add the function calls if specific fields are set in `chadrc.lua`.

**Comment by siduck** [comment]
@LeonHeidelbach users can already change specific colors of a theme, read the docs! so Im pretty sure then can do it :v

**Comment by LeonHeidelbach** [comment]
@siduck I know that 😉. However, if we introduce new keys for HSL overrides users could just add 3 keys to change all color values of a theme very quickly and have a new color palette without overriding all colors individually. We could offer different variations of all existing themes with very little effort for the user.
