### ISSUE TITLE
Hide statusline in terminal

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1194]
I added this as a bug tag because before this terminal in nvchad there was no statusline display. statusline on terminal is unnecessary, it requires a lot of space. If you add statusline on terminal just because to "look good" you're wrong, unless the terminal is open in a new buffer (not in a horizontal/vertical/floating split), that is acceptable.

#### Question real question: how users can disable statusline in terminal or in certain mode?

If im not wrong, there is no instructions in nvchad docs

**Comment by siduck** [comment]
it takes no space as we use the global statusline. there is a mode such as NT ( normal mode in terminal ) which is important to be seen with the statusline  

![image](https://user-images.githubusercontent.com/59060246/173193599-6922b756-c2bb-46fd-8603-0f7830a141dd.png)


![image](https://user-images.githubusercontent.com/59060246/173193605-28ef0cdd-02b1-427a-afcc-49dddd4512df.png)


normal terminal mode

**Comment by siduck** [comment]
If you still want to disable the statusline then write some autocmds for it like we did before

**Comment by nullchilly** [comment]
https://github.com/NvChad/NvChad/blob/bdf45a447add58ec07a66f763289f187dfa90a3e/lua/core/autocmds.lua#L3-L16

Add them to tips and tricks

**Comment by siduck** [comment]
@nullchilly tips and tricks section is for those useful code snippets that arent in the main repo!

**Comment by siduck** [comment]
```vim.cmd [[ au TermOpen term://* setlocal laststatus=0 ]]
```

this should work but it doesnt 

This happens when i manually disable statusline in terminal

![image](https://user-images.githubusercontent.com/59060246/173277432-de032249-1b81-4a2d-837b-ed3e55ccb0e9.png)


@LeonHeidelbach :raised_hands:

**Comment by siduck** [comment]
```lua
local autocmd = vim.api.nvim_create_autocmd

autocmd("TermOpen", {
   pattern = "*",
   callback = function()
      vim.opt.statusline = "%#normal# "
   end,
})

autocmd("WinEnter", {
   pattern = "*",
   callback = function()
      if vim.bo.buftype ~= "terminal" then
         vim.opt.statusline = "%!v:lua.require'ui.statusline'.run()"
      else
         vim.opt.statusline = "%#normal# "
      end
   end,
})
```
 
 @coffee on discord helped me
