### ISSUE TITLE
packer.nvim: nvim/lua/plugins/configs/statusline.lua:8: loop or previous error loading module 'base46'

### ISSUE THREAD

**Issue by Dalot** [NvChad/NvChad#1195]
**Describe the bug**
When I open `nvim` after a `PackerSync` I have the following error 
```
packer.nvim: Error running config for feline.nvim: ...e/rdalot/.config/nvim/lua/plugins/configs/statusline.lua:8: loop or previous error loading module 'base46'
```

**To Reproduce**
1. `PackerSync`
2. Open nvim
3. See error

**Expected behavior**
No error
**Screenshots**
![image](https://user-images.githubusercontent.com/8915574/173190590-b4b30e46-2945-4ba4-b41d-9139b21d2ad7.png)

**Desktop (please complete the following information):**
 - Ubuntu 18
 - Alacritty
 - 0.7.0

**Comment by Dalot** [comment]
Tried fresh install (did not have snapshot) but ended up with the following error:

```
Error executing vim.schedule lua callback: /home/rdalot/.config/nvim/lua/core/utils.lua:105: attempt to index local 'mapping_info' (a boolean value)
stack traceback:
        /home/rdalot/.config/nvim/lua/core/utils.lua:105: in function 'load_mappings'
        /home/rdalot/.config/nvim/init.lua:12: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by siduck** [comment]
did u do packersync ?

**Comment by Dalot** [comment]
I solved the issue by removing 
```  mode_opts = { noremap = true },``` 
on the `M.nvimtree` overriding custom mappings

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/173193749-89fe63a8-861b-41d0-8809-a36ebb5a0d46.png)

We no longer use feline, I wrote a custom statusline

**Comment by Dalot** [comment]
Yeah, I noticed that in the commits when it was too late. Everything is working now, although I don't know why that error comes up once I add `mode_opts = { noremap = true },` 

The statusline is looking neat :clap: Thank you!

**Comment by siduck** [comment]
@Dalot  mapping structure is changed too so reacd the docs

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/173221582-0158522c-8af0-4bb0-b725-dc2fdac6a658.png)

**Comment by forrestaustin** [comment]
I am getting the same error here also. This is my first time ever running PackerSync and I have not ever updated my version of nvchad since I first downloaded it in early May. Do I need to update nvchad to get past this issue?

This is on macosm nvim v0.7.0

**Comment by siduck** [comment]
yes update nvchad to the latest always
