### ISSUE TITLE
'ctrl+Shift+v' in insert mode not working in gui clients "Neovide"

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1196]
**Describe the bug**
when i was using my config the the clipboard runs perfectly fine both in insert and normal mode while using **Neovide** a rust based nvim client.
but whenever i switch to Nvchad the 'p' in normal mode pasts just fine but Ctrl+V is not working in insert mode.

but in other normal terminals it seems to work ok.

**To Reproduce**
1. run Neovide with default nvchad
2. got to insert mode and try to paste 

**Expected behavior**
in insert mode Ctrl+V should paste if i am using 

**Desktop (please complete the following information):**
 - Operating System = **Linux , Manjaro**
 - Terminal = **Neovide Client**

**Comment by siduck** [comment]
does it work with nvim --clean?

**Comment by Aneeqasif** [comment]
> does it work with nvim --clean?

yes when i do this it open default nvim in my temrinal and it works .
the issue is just with gui client
the terminal worked with both my config and nvchad config
but the issue is with neovide clieant when i use nvchad
neovide works fine with my config which is very simple i can paste it here if you want me to

**Comment by siduck** [comment]
oh, i dont think we have any mapping related to ctrl shift +v  so no clue about this

**Comment by siduck** [comment]
does clipboard=unamedplus work in neovide?

**Comment by Aneeqasif** [comment]
> does clipboard=unamedplus work in neovide?

yes in my previous config it works

**Comment by Aneeqasif** [comment]
# Here is my init.vim 


source $HOME/.config/nvim/vim-plug/plugins.vim

source $HOME/.config/nvim/keys/which-key.vim
source ~/.config/nvim/plug-config/dashboard.vim
"source $Home/.config/nvim/plug-config/gruvbox.vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                    W O R K I N G
""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Working --------- {{{
au! BufWritePost $MYVIMRC source %    
set nocompatible
set splitbelow splitright
set expandtab
set smarttab
set nobackup
set guifont=JetBrainsMono\ Nerd\ Font:h10
"let g:neovide_cursor_vfx_mode = "railgun"
let g:neovide_remember_window_size = v:true
let g:neovide_refresh_rate=140

" Encoding
set encoding=utf-8

set timeoutlen=300
set nocompatible

" Display 5 lines above/below the cursor when scrolling with a mouse.
set scrolloff=5

" Highlight matching pairs of brackets. Use the '%' character to jump between them.
set matchpairs+=<:>

" Fixes common backspace problems
set backspace=indent,eol,start

" Speed up scrolling in Vim
set ttyfast

" Highlight matching pairs of brackets. Use the '%' character to jump between them.
set matchpairs+=<:>

" Automatically wrap text that extends beyond the screen length.
set wrap linebreak nolist

" Enable plugins and load plugin for the detected file type.
filetype plugin indent on

set incsearch

" Include matching uppercase words with lowercase search term
set ignorecase
" Include only uppercase words with uppercase search term
set smartcase

set shiftwidth=4
set tabstop=4
set expandtab
" }}}
 



""""""""""""""""""""""""""""""""""""""""""""""
" L O O K
""""""""""""""""""""""""""""""""""""""""""""""

" Looks --------------- {{{
colorscheme gruvbox
set termguicolors
set background=dark
let g:gruvbox_contrast_dark='hard'
"colorscheme kanagawa
"colorscheme duskfox
"colorscheme molokai 
"colorscheme uwu
let g:UwuNR=1


"colorscheme vim-monokai-tasty
syntax enable
set number relativenumber
set cursorline
set t_Co=256
set mouse=nicr
set mouse=a
set clipboard=unnamedplus
set laststatus=2 
set scrolloff=5
highlight CursorLine       ctermfg=none    ctermbg=236     cterm=none
highlight CursorLineNr    ctermbg=none       cterm=none
highlight LineNr           ctermfg=8    ctermbg=none    cterm=none
" In your init.lua or init.vim
"set termguicolors


"  }}}



" MAPPINGS --------------------------------------------------------------- {{{

map <C-h> <C-w>h
map <C-l> <C-w>l
map <C-j> <C-w>j
map <C-k> <C-w>k
let g:mapleader = "\<Space>"
vmap < <gv
vmap > >gv
nnoremap o o<esc>
nnoremap O O<esc>
map <Leader>tt :vnew term://zsh<CR>
" Resize split windows using arrow keys by pressing:
" CTRL+UP, CTRL+DOWN, CTRL+LEFT, or CTRL+RIGHT.
noremap <c-up> <c-w>+  
noremap <c-down> <c-w>-
noremap <c-left> <c-w>>
noremap <c-right> <c-w><

" Center the cursor vertically when moving to the next word during a search.
nnoremap n nzz
nnoremap N Nzz
inoremap jj <esc>
" }}}








" VIMSCRIPT -------------------------------------------------------------- {{{

" This will enable code folding.
" Use the marker method of folding.
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" More Vimscripts code goes here.

let g:molokai_original = 1
"let g:lightline = {'colorscheme': 'gruvbox'}
if version >= 703
    set undodir=~/.config/nvim/backup
    "set undofile
    "set undoreload=10000
endif

let g:minimap_width = 10
let g:minimap_auto_start = 1
let g:minimap_auto_start_win_enter = 1
let g:minimap_auto_start = 0

" }}}









" Pluggins Config -------------- {{{
"for coc tab-completion
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

"Nerd-tree dont show arrows
"let g:NERDTreeDirArrowExpandable = ''
"let g:NERDTreeDirArrowCollapsible = ''
"let NERDTreeIgnore=['\.jpg$', '\.mp4$', '\.ogg$', '\.iso$', '\.pdf$', '\.pyc$', '\.odt$', '\.png$', '\.gif$', '\.db$']

" Nvim-tree config
lua require'nvim-tree'.setup {}


let g:nvim_tree_respect_buf_cwd = 1
let g:nvim_tree_indent_markers = 1

source $HOME/.config/nvim/plug-config/gruvbox.vim

lua << EOF
require("bufferline").setup{}
EOF












"" }}}


nnoremap <f5> :w <CR>:!clear <CR>:!python3 % <CR>



"Extra ----------------------------------------------- {{{

"let g:NERDTreeGitStatusUntrackedFilesMode = 'all' 
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pa


" => Open terminal inside Vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""







" Use CTRL-S for saving, also in Insert mode
"noremap <C-zz> :update<CR>
"vnoremap zz <C-C>:update<CR>
"inoremap zz <C-O>:update<CR>
" }}}
"




"lua << EOF
"local nightfox = require('nightfox')

"-- This function set the configuration of nightfox. If a value is not passed in the setup function
"-- it will be taken from the default configuration above
"nightfox.setup({
  "fox = "duskfox", -- change the colorscheme to use nordfox
  "-- transparent="true",
  "styles = {
    "comments = "italic", -- change style of comments to be italic
    "keywords = "bold", -- change style of keywords to be bold
    "functions = "italic,bold" -- styles can be a comma separated list
  "},
  "inverse = {
    "match_paren = true, -- inverse the highlighting of match_parens
  "},
  "colors = {
    "red = "#FF000", -- Override the red color for MAX POWER
    "bg_alt = "#000000",
  "},
  "hlgroups = {
    "TSPunctDelimiter = { fg = "${red}" }, -- Override a highlight group with the color red
    "LspCodeLens = { bg = "#000000", style = "italic" },
  "}
"})

"-- Load the configuration set above and apply the colorscheme
"nightfox.load()
"EOF

**Comment by siduck** [comment]
hmm no idea. I suggest you to disable each part of config and check in neovide

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/173278588-9f09e919-6eaa-4db0-a8b3-c97326f86087.mp4

**Comment by siduck** [comment]
This is a neovide issue, i cant get ctrl shift v working with nvim --clean too

**Comment by vlaw** [comment]
neovide/neovide#113
Maybe there are some clues

**Comment by siduck** [comment]
@vlaw yea that was it. 

this worked for me 

```lua

vim.cmd [[
" system clipboard
nmap <c-c> "+y
vmap <c-c> "+y
nmap <c-v> "+p
inoremap <c-v> <c-r>+
cnoremap <c-v> <c-r>+
" use <c-r> to insert original character without triggering things like auto-pairs
inoremap <c-r> <c-v>
]]
```

**Comment by siduck** [comment]
so this is no longer a nvchad issue, closing it
