### ISSUE TITLE
Disable autocompletion feature and snippets

### ISSUE THREAD

**Issue by mcctuxic** [NvChad/NvChad#1198]
**Describe the bug**
Autocompletion and snippets are always on - independet of the current type of file.
When I write mails (for example) I am confronted with a license agreement text which 
suddenly gets inserted into my mail or other nonesense like wordlists, containing words,
which needs lesser characters to type than it needs TAB hits to get to that word finally.

**To Reproduce**
Write a non technical, not programming text.

**Expected behavior**
Autocompletion and snippet feature should be restricted to technical related
types of files.

**Screenshots**
...sorry. My mails are private data. Therefore no screenshot.

**Desktop (please complete the following information):**
 - Gentoo Linux
 - Wezterm 
 - NVIM v0.7.0
   Build type: RelWithDebInfo
   LuaJIT 2.1.0-beta3

**Additional context**
Solution would be sufficient, if it is know, how to disable related plugins in dependence to certain types of files.

**Comment by siduck** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/666

**Comment by siduck** [comment]
or you could write an autocmd for it, idk much about autocmds but this I could come up with this 

```lua
local autocmd = vim.api.nvim_create_autocmd

autocmd("FileType", {
   pattern = "lua",
   callback = function()
      require("cmp").setup.buffer { enabled = false }
   end,
}
```

**Comment by rdaneelu** [comment]
If I want it for .py files It will be 

```lua
pattern = "python"
```

for .md files

```lua
pattern = "markdown"
```

But what about plain text files without a filetype?

**Comment by siduck** [comment]
> If I want it for .py files It will be
> 
> ```lua
> pattern = "python"
> ```
> 
> for .md files
> 
> ```lua
> pattern = "markdown"
> ```
> 
> But what about plain text files without a filetype?

maybe "*"  :thinking:
