### ISSUE TITLE
Error when Neovim starts. Probably Lua 5.1/LuaJIT deprecated

### ISSUE THREAD

**Issue by noisyBrain** [NvChad/NvChad#1199]
**Describe the bug**
It seems to be Lua 5.1/LuaJIT deprecated
Error executing vim.schedule (from load.lua)
Needs quotes (from load.lua)

**To Reproduce**
1. Go to '...' some file and open Nvim, appears the errors like in screenshots below

**Expected behavior**
Everything go okay

**Screenshots**

![neovim issue 1](https://user-images.githubusercontent.com/95882962/173255271-a235d565-4f06-4da9-b106-771cd68a1141.png)
![neovim issue 2](https://user-images.githubusercontent.com/95882962/173255322-55602c83-43ea-47b8-9741-646de750a0f5.png)
![neovim issue 3](https://user-images.githubusercontent.com/95882962/173255352-01c1e2e8-587c-4c4e-a8f3-ece36b568cf1.png)

First screenshot is the error when I open Nvim.
The second one is in load.lua file
The thrid is in utils.lua

**Desktop (please complete the following information):**
 - Operating System -> Windows 10
 - Terminal -> Terminal, oh-my-posh
 - Version of Neovim -> 0.7 v

**Additional context**
I have wingw64 installed

Thanks for help !

**Comment by noisyBrain** [comment]
![image](https://user-images.githubusercontent.com/95882962/173256550-ceab6aeb-58b3-4029-8ae9-c1e127e346c3.png)

That is another error in **"nvim-data\site\pack\packer\start\packer.nvim"**

**Comment by siduck** [comment]
yes neovim uses lua 5.1 so that warning is normal

**Comment by zbirenbaum** [comment]
You should really not have 5.4 running, neovim includes a copy of luajit. Something is pretty messed up here. Can you run `:checkhealth`  and provide the output, as well as the full error message as it appears?

**Comment by noisyBrain** [comment]
Sure! I tried to copy and paste `:checkhealth`'s output here, but I found another error D: 
I took screenshots

![image](https://user-images.githubusercontent.com/95882962/173426606-5a8e63b1-e33d-4ce5-9b2b-bc40ab808291.png)

![image](https://user-images.githubusercontent.com/95882962/173426818-62a43f47-a85a-44b2-af3d-31d132eabb1a.png)

![image](https://user-images.githubusercontent.com/95882962/173426924-2703c713-074f-4baa-8730-3e4668870114.png)

![image](https://user-images.githubusercontent.com/95882962/173426993-01da12e3-6c7f-4ec5-9bfb-581a1849e435.png)

![image](https://user-images.githubusercontent.com/95882962/173427043-e0859655-d097-43aa-9510-c6cf9de76dd4.png)

**Comment by siduck** [comment]
this seems like a windows issue, ughh i always disliked windows!!!!!!!!!!!!!!!!!! :angry:

**Comment by noisyBrain** [comment]
Me too man haha but I'm still scared of linux, idk. Do you recommend me to install Ubuntu? I've already do some stuff on Arco Linux and Manjaro. I'd like to use a wm la bspwm with picom

**Comment by siduck** [comment]
> Me too man haha but I'm still scared of linux, idk. Do you recommend me to install Ubuntu? I've already do some stuff on Arco Linux and Manjaro. I'd like to use a wm la bspwm with picom

ubuntu forces stuff like snap, I'd suggest using linux mint, fedora or endeavouros

**Comment by siduck** [comment]
lemme know when you install them and this error fixes :joy:

**Comment by zbirenbaum** [comment]
Ubuntu was a pain for hardcore development work which often requires version specific libraries which it doesn't officially support. Every time I've used it or a derivative of it, I end up installing something else over it.

Arch Linux has pacman which can do parallel downloads and makes package managers like apt look like windows updates by comparison. I'd recommend using something like Manjaro which is based on it if you are new. I've never used it myself but I've heard it's pretty beginner friendly.

**Comment by siduck** [comment]
@zbirenbaum not manjaro , read https://github.com/arindas/manjarno

**Comment by zbirenbaum** [comment]
> @zbirenbaum not manjaro , read https://github.com/arindas/manjarno

The first sentence I read about the package repos disqualified it from ever being recommended as a system by me again. I'll edit my previous comment.

**Comment by noisyBrain** [comment]
Hahaha thanks guys! I think I'm still too newbie to install Arch by my own. I know there is intallers like Calamares or something like that, but is not the essence of Arch.
I'll research about linux mint, fedora and endeavouros.

It's okay if I close this now?

**Comment by zbirenbaum** [comment]
> Hahaha thanks guys! I think I'm still too newbie to install Arch by my own. I know there is intallers like Calamares or something like that, but is not the essence of Arch. I'll research about linux mint, fedora and endeavouros.
> 
> It's okay if I close this now?

Everyone staying how hard it is to install arch is mostly exaggerating. If you are familiar with linux and can follow step by step instructions its pretty doable. I managed to get it running in a VM as a freshman in HS over half a decade ago when everything was less well documented and stable. 

I don't know what Calamares is, but there are now install scripts in the official community repository to walk you through it:
https://github.com/archlinux/archinstall

Personally, when I tried them out of curiosity around a year ago, those scripts caused me problems due to some complexities in my setup, but for most people its fine, and definitely something worth trying. I haven't used EndeavorOS but apparently its fairly close to normal Arch but with a gui installer.

Of the other ones you listed I would go with Fedora over Mint

**Comment by siduck** [comment]
> Hahaha thanks guys! I think I'm still too newbie to install Arch by my own. I know there is intallers like Calamares or something like that, but is not the essence of Arch. I'll research about linux mint, fedora and endeavouros.
> 
> It's okay if I close this now?

yep close it

**Comment by siduck** [comment]
> Everyone staying how hard it is to install arch is mostly exaggerating. If you are familiar with linux and can follow step by step instructions its pretty doable. I managed to get it running in a VM as a freshman in HS over half a decade ago when everything was less well documented and stable.
 

it depends, I got my own pc at the age of 18 ( im 20 now ) so I didnt had much exposure to computer stuff before, the day i got my own pc, I had a arch usb ready :rofl: and the arch wiki felt way too intimidating. It took me around 10 hours + to install & setup it, I started it at night 7pm and ended up setting up deepin DE till 5 am. I didnt know how docs worked at that time, I use void linux now. It has a tui installer which is much simpler imo. If you want to install the system with just commands only like arch then you can do that too

**Comment by zbirenbaum** [comment]
> > Everyone staying how hard it is to install arch is mostly exaggerating. If you are familiar with linux and can follow step by step instructions its pretty doable. I managed to get it running in a VM as a freshman in HS over half a decade ago when everything was less well documented and stable.
> 
> it depends, I got my own pc at the age of 18 ( im 20 now ) so I didnt had much exposure to computer stuff before, the day i got my own pc, I had a arch usb ready rofl and the arch wiki felt way too intimidating. It took me around 10 hours + to install & setup it, I started it at night 7pm and ended up setting up deepin DE till 5 am. I didnt know how docs worked at that time, I use void linux now. It has a tui installer which is much simpler imo. If you want to install the system with just commands only like arch then you can do that too

Ouch, that's a really rough introduction to linux. It's definitely difficult as a new user, so for someone that hasn't touched linux before I would never recommend it, but since he has experience with an arch derivative I think it would be fine. I've definitely had my fair share of installs go awry and take ages, but it was a good learning experience at least. 

Ironically, the ubuntu graphical installer is the one that caused me the most problems down the line, as it put the bootloader on the wrong drive, and that required a ton of knowledge to fix so I could get its stupid entry out of my EFI after uninstalling it.

**Comment by siduck** [comment]
@zbirenbaum any clue with this? need a fix asap https://www.reddit.com/r/neovim/comments/vbsryc/show_lsp_signature_help_window_above_cursor/

**Comment by noisyBrain** [comment]
I'll take your advices! Probably will be EndeavorOS my option! If you don't mind, I'll be asking some questions about it 😁

@siduck you 20 and you created NvChad? You're a genius man, congrats! I'm 25 yo and I just started on this

**Comment by siduck** [comment]
@noisyBrain yes I created NvChad. I initially created for my personal use to enhance my programming experience ( i had a low end pc so i couldnt use Heavy IDE's ) . 

I got my own pc at 18 years of age and im not a CS student so I wasnt into computers stuff much before, but started getting into linux as soon as I got my own pc and got to know about vim
