### ISSUE TITLE
Question regarding font sizing?

### ISSUE THREAD

**Issue by nico-bellante** [NvChad/NvChad#1203]
So it feels wrong to even consider this a bug because it is so very minor, but I figured I'd post here just in case anyone has seen this and knows how to fix it.

Basically, this little difference in height on the status line:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/35939126/173453673-e24c7881-e7bb-4568-82ec-efc4b3bf27b1.png">
<img width="94" alt="image" src="https://user-images.githubusercontent.com/35939126/173453721-710425c5-351d-4a3f-b9ea-3ab7f7f4db3e.png">

It's very very minor, but maybe someone else has been bothered by it and knows how to fix it. 🤷 

FWIW, I tried with two different nerdfont fonts, and it seems to occur 2/2 times.
Also, this is within iTerm, but I see a lot of comments in here talking about kitty. Maybe that would resolve things?

**Comment by nico-bellante** [comment]
Also, I noticed this happens with the:
```
  docker run -w /root -it --rm alpine:edge sh -uelic '
    apk add git nodejs neovim ripgrep alpine-sdk --update
    git clone https://github.com/NvChad/NvChad ~/.config/nvim
    nvim
    '
   ```
so I figure it's got to be something with my terminal

**Comment by digitallyserviced** [comment]
It is probably your font/terminal. It usually depends on the font used, the line height, icons used, hinting of the font, all sorts of things. 

While my icons seem aligned better, the line height makes it look like more gravity towards the bottom then being centered vertically.

This is Wezterm, ShureTech NF Mono (Nerd Font) font_size: 10, line_height: 0.9

![neovimlines](https://user-images.githubusercontent.com/1828125/173466506-da8f333e-6cea-4eb3-b1a2-693f8349343b.png)
![neovimlines2](https://user-images.githubusercontent.com/1828125/173466508-96027e7f-ea91-460c-912e-c395aa3266b4.png)
![neovimlines3](https://user-images.githubusercontent.com/1828125/173466509-27a788b9-96f4-4da1-8d5f-a94c46b77fdb.png)


Just want you to be able to see the differences...z

**Comment by siduck** [comment]
the font stuff is handled by your terminal, so not our field!

**Comment by siduck** [comment]
u have to set the exact name of a nerd font in your terminal btw, for example this is xresources

![image](https://user-images.githubusercontent.com/59060246/173466992-f87a5420-d4d4-4664-958e-90bf26f87da1.png)
