### ISSUE TITLE
Healthcheck error, Incompatible Architecture on M1 mac book air

### ISSUE THREAD

**Issue by tanshunyuan** [NvChad/NvChad#1205]
**Describe the bug**
After running `:checkhealth`, there is multiple errors citing incompatible architecture for various plugins that are in neovim.
![Screenshot 2022-06-14 at 10 03 57 AM](https://user-images.githubusercontent.com/29978940/173478208-377e468e-470c-4ebc-afd8-9a11dcae187b.png)

**Desktop (please complete the following information):**
 - Operating System: MacOS Monterey (v 12.4) Apple M1 Chip
 - Terminal: Alacritty (v0.9.0 (fed349a))
 - Version of Neovim (v0.7.0)

**Comment by siduck** [comment]
macos issue :l so cant help

**Comment by siduck** [comment]
looks like its just treesitter issues on the m1, on linux I need to have clang or gcc installed for compiling treesitter parsers. U need to have something similar too

**Comment by tanshunyuan** [comment]
oh alright, thanks a lot for the swift reply!

**Comment by tanshunyuan** [comment]
Alright fixed it!
Seems like this was an issue with alacritty, the version I was running is `0.0.9`. So I updated alacritty to it's latest version `0.10.1`. But do note that other than updating alacritty, you do need to regenerate tree-sitter parser in the UPDATED alacritty so that tree-sitter parser will detect the latest version of alacritty.

How do we regnerate tree-sitter parser I have no idea, maybe this [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/791#issuecomment-921980482) in alacritty can help. But what I did was uninstalled nvchad and reinstalled it with the links in the documentation. Launching neovim for the first time, it will install packages and regenerate tree-sitter parser's

**Comment by siduck** [comment]
@tanshunyuan do a clean install, remove .local/share/nvim

**Comment by tanshunyuan** [comment]
Yep, that did it for me!

**Comment by siduck** [comment]
m1 issue :c
