### ISSUE TITLE
jk as escape

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#1206]
jk as escape settings not working anymore.
To be honest I can't remember how and where I had to set it but it worked and with the last update it's gone...

**Comment by siduck** [comment]
yes because i removed better escape

**Comment by se7en-x230** [comment]
Ok I feel like an idiot but I can't figure the right syntax out...

![image](https://user-images.githubusercontent.com/69777713/173735358-74d637a8-1aae-47bd-a0cd-3efe771b0ae4.png)

Someone please assist.

**Comment by siduck** [comment]
the mapping part works perfect here :/

**Comment by se7en-x230** [comment]
so what am I missing?

**Comment by siduck** [comment]
idk, it works here :/

**Comment by se7en-x230** [comment]
adding the mapping to core/mapping.lua works but is obviously inconvenient when updated

**Comment by siduck** [comment]
your custom config is messed up probably

**Comment by se7en-x230** [comment]
the picture is the entire custom.lua.
I have no custom settings.

**Comment by siduck** [comment]
wait some minutes, I will test this for u

**Comment by siduck** [comment]
Uploading simplescreenrecorder-2022-06-15_17.28.21.mp4…

**Comment by siduck** [comment]
bruh wait u have to include that in your mappings table and not misc! First read the docs D:

**Comment by siduck** [comment]
i thought u knew how mappings work
