### ISSUE TITLE
Theme loading does not work properly

### ISSUE THREAD

**Issue by lucario387** [NvChad/NvChad#1209]
**Describe the bug**
Highlight groups aren't shown properly on load, and theme toggling does not reload all highlight groups

**To Reproduce**
1. Clone NvChad from git
2. Create a `lua/custom/chadrc.lua` with the following contents:
```lua
local M = {}
M.ui = {
  theme = "vscode_dark", -- most theme won't load properly, this is one of them
  theme_toggle = {"vscode_dark","onedark"},
  transparency = false,
}
return M
```
3. Leave nvim and reenter
4. Open a file
5. Press `<leader>tt` (default key in NvChad for toggle theme)

**Expected behavior**
On load, the theme is loaded properly, and when `toggle_theme` is called, all highlight groups are changed to its appropriate one

**Actual Behavior**
- The loaded theme on startup is not the theme that has been set in `chadrc.lua`
- Theme toggling only changing color of brackets and some texts, not comments, table entries, etc.

**Screenshots**
1. Currente theme is vscode_dark, but the highlight groups are not correct as can be seen clearly from the image below
![image](https://user-images.githubusercontent.com/29790821/173712016-9e0224f8-a7b6-415f-acbd-d42ce68a4621.png)
2. Theme is now correct after force reloading theme again
![image](https://user-images.githubusercontent.com/29790821/173712094-6ad3875d-0a02-4ee8-a19a-387e374ff44f.png)
3. Toggle theme to gruvbox, but only the brackets are of gruvbox, other parts of syntax stays with vscode_dark highlighting
![image](https://user-images.githubusercontent.com/29790821/173712361-a59a1bea-1166-4792-bb96-d7c5b267557a.png)
5. Preview Video
https://user-images.githubusercontent.com/29790821/173712505-742be805-f77e-4910-8057-36ca5e05321a.mp4

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 2204 LTS
 - Terminal: Kitty
 - $TERM environment: xterm-kitty
 - Version of Neovim: 0.8.0-dev

**Additional context**

**Comment by PoSayDone** [comment]
Facing the same issue now.

https://user-images.githubusercontent.com/29358657/178111140-c7c50564-8391-4e84-bf7f-5d28835009d2.mp4

**Comment by siduck** [comment]
@

**Comment by PoSayDone** [comment]
> @PoSayDone when was the last time u updated nvchad?

Today, about 30 min ago

**Comment by siduck** [comment]
> > @PoSayDone when was the last time u updated nvchad?
> 
> Today, about 30 min ago

can you produce this issue with no custom config?

**Comment by PoSayDone** [comment]
> > > @PoSayDone when was the last time u updated nvchad?
> > 
> > Today, about 30 min ago
> 
> can you produce this issue with no custom config? 

Yep, when I delete M.plugins and all it's contents from my chadrcbeverything works like a charm

**Comment by PoSayDone** [comment]
@siduck, I had an issue in my treesitter config. sry for disturbing.

**Comment by siduck** [comment]
> @siduck, I had an issue in my treesitter config. sry for disturbing.

no worries! next time whenever you get issues, make sure to check if the issue persists with vanilla nvchad config ( no custom conf )

**Comment by bryant-the-coder** [comment]
> **Describe the bug** Highlight groups aren't shown properly on load, and theme toggling does not reload all highlight groups
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Clone NvChad from git
> 2. Create a `lua/custom/chadrc.lua` with the following contents:
> 
> ```lua
> local M = {}
> M.ui = {
>   theme = "vscode_dark", -- most theme won't load properly, this is one of them
>   theme_toggle = {"vscode_dark","onedark"},
>   transparency = false,
> }
> return M
> ```
> 
> 3. Leave nvim and reenter
> 4. Open a file
> 5. Press `<leader>tt` (default key in NvChad for toggle theme)
> 
> **Expected behavior** On load, the theme is loaded properly, and when `toggle_theme` is called, all highlight groups are changed to its appropriate one
> 
> **Actual Behavior**
> 
> * The loaded theme on startup is not the theme that has been set in `chadrc.lua`
> * Theme toggling only changing color of brackets and some texts, not comments, table entries, etc.
> 
> **Screenshots**
> 
> 1. Currente theme is vscode_dark, but the highlight groups are not correct as can be seen clearly from the image below
>    ![image](https://user-images.githubusercontent.com/29790821/173712016-9e0224f8-a7b6-415f-acbd-d42ce68a4621.png)
> 2. Theme is now correct after force reloading theme again
>    ![image](https://user-images.githubusercontent.com/29790821/173712094-6ad3875d-0a02-4ee8-a19a-387e374ff44f.png)
> 3. Toggle theme to gruvbox, but only the brackets are of gruvbox, other parts of syntax stays with vscode_dark highlighting
>    ![image](https://user-images.githubusercontent.com/29790821/173712361-a59a1bea-1166-4792-bb96-d7c5b267557a.png)
> 4. Preview Video
>    https://user-images.githubusercontent.com/29790821/173712505-742be805-f77e-4910-8057-36ca5e05321a.mp4
> 
> **Desktop (please complete the following information):**
> 
> * Operating System: Ubuntu 2204 LTS
> * Terminal: Kitty
> * $TERM environment: xterm-kitty
> * Version of Neovim: 0.8.0-dev
> 
> **Additional context**

what is the wallpaper?
