### ISSUE TITLE
There was something wrong with the upgrade this morning. I don't think it will work to change the cmp nvim-tree configuration.

### ISSUE THREAD

**Issue by j2501987804** [NvChad/NvChad#1210]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - arch-wsl
 - windows-Terminal
 - nvim7.0

**Additional context**
![image](https://user-images.githubusercontent.com/41771911/173724393-0e5d037b-2588-4de4-b299-5a473512c372.png)

This is my warehouse address: https://github.com/j2501987804/dotfiles. 
Custom configuration is stored in custom

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/1201#issuecomment-1155857478

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/173726857-41305fc6-51e9-403e-a0e4-5cb95733bd84.png)

culprit

**Comment by siduck** [comment]
> [#1201 (comment)](https://github.com/NvChad/NvChad/issues/1201#issuecomment-1155857478)

read that comment, in your case its nvimtree+cmp instead of just cmp
