### ISSUE TITLE
Bufferline not show on startup

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1211]
### **Describe the bug**
The bufferline is not displayed at startup if there is only 1 buffer open. I don’t know if this happened on purpose or what, but this is not what we expect.

![Bufferline_NchadBug](https://user-images.githubusercontent.com/73665622/173780630-7935d3f3-3321-449d-a49c-1cf1857c8279.gif)

### **To Reproduce**
1. nvim \<FILENAME\>

### **Expected behavior**
Show bufferline even there is only 1 buffer open.

### **Desktop (please complete the following information):**
 - Ubuntu 20.04 & Debian 10 Server
 - Wezterm & Kitty
 - NVIM v0.7.0 Release & v0.7.1-dev

**Comment by GreatestOfAllTimee** [comment]
NOTE: this happened after a recent update AND I tried with a fresh nvchad installation on a Debian 10 machine apparently this problem still occurs

**Comment by cathaysia** [comment]
set `always_show_bufferline = true` in bufferline's configurations.

**Comment by bryant-the-coder** [comment]
its because of the new lazyload func

**Comment by siduck** [comment]
> This should come by default on nvchad

no, there is no reason to show bufferline on startup when there is just one file opened

**Comment by siduck** [comment]
just override the bufferline's packer definition config

**Comment by GreatestOfAllTimee** [comment]
Huhuhu weird taste. Maybe you are too bored and messing up nvchad 🤣

**Comment by FelixKratz** [comment]
Actually, there is no reason to show the file name in statusline if you leave bufferline enabled by default.

I would like this better, but as long as it can be overridden everything is OK.

**Comment by siduck** [comment]
> Actually, there is no reason to show the file name in statusline if you leave bufferline enabled by default.
> 
> I would like this better, but as long as it can be overridden everything is OK.

most statuslines have the fileinfo. The bufferline's tabs are fixed to a specific size so long names in bufferline buffer tabs are gonna get trunacated , for example : "sdfsdfsdfhsadfhasdfjskdfsdf.lua" would turn into "sdsfsdfsdfdf..." 

So we show it in the statusline

**Comment by FelixKratz** [comment]
Yes I respect that, however, you surely must have implemented a max file name length for the statusline as well?
I am only adding this to the discussion because it fixes the truncation for most files (add to overrides):
```lua
["akinsho/bufferline.nvim"] = {
      options = {
        max_name_length = 20,
      },
},
```

**Comment by siduck** [comment]
> > set `always_show_bufferline = true` in bufferline's configurations.
> 
> This does not work: ![Screen Shot 2022-06-15 at 14 19 49](https://user-images.githubusercontent.com/22680421/173825480-7701b974-aa22-410e-b74e-557705181220.png)

yes cuz the bufferline regardless of the config will initially only show when there are more than 1 buffer

**Comment by mattbailey** [comment]
the other side-effect of this change is that running `nvim somefiles/*` doesn't trigger the lazy loading of bufferline with multiple files...

**Comment by siduck** [comment]
> the other side-effect of this change is that running `nvim somefiles/*` doesn't trigger the lazy loading of bufferline with multiple files...

thats weird, Im not sure how to handle that. PR's are welcome!

**Comment by JSilva6** [comment]
This is because of bufferline's lazy loading. Neither bufferline comes up at the start, but also some weird bugs happens when you open a new tab on unexpected ways for nvchad to detect, such as bringing "tabnew" or "terminal"

![image](https://user-images.githubusercontent.com/43544777/174674559-c11a7d43-80d7-44bc-bdec-fafdb4844d6e.png)

Also, bufferline commands in the prompt wont show anything due to lazy loading, so its required to open multiple files in order to bufferline actually shows up.

This also creates an issue, where while you have only one buffer open, you cant use the proper < leader > space since the plugin hasnt been initialized yet. Opening a new tab or new buffer via command will always show the default vim tab bar as shown in the picture above.

Disabling bufferline lazyloading should fix it.

**Comment by JSilva6** [comment]
Also, its worth to say that, lazyloading bufferline contradicts the "always show bufferline" options, since its mainly set to show bufferline regardless of having more than one buffer.

**Comment by LeonHeidelbach** [comment]
@siduck I agree that we should revert lazy loading bufferline. I myself have removed it from the lazy load list, as it is an essential plugin I always want to have access to.

**Comment by siduck** [comment]
@LeonHeidelbach its just lazy loaded once initially, as soon as nvim has 1+ files opened then bufferline will load . Not like bufferline disables itself when there's just 1 file.

@JSilva6 make issue for this 

![image](https://user-images.githubusercontent.com/59060246/174711017-596cc0f6-740f-489f-8896-9503a737382e.png)

**Comment by Ishigod29** [comment]
solution in your file custom/plugins/init.lua paste:

["NvChad/ui"] = {
  override_options = {
    tabufline = {
      enabled = true,
      lazyload = false,
      overriden_modules = nil,
   },
  },
},

in the lazyload option it must be false

**Comment by Ishigod29** [comment]
![Solution](https://user-images.githubusercontent.com/81834956/206447597-6e59292b-0e28-4b92-99a0-abc2d7c190d7.png)

**Comment by siduck** [comment]
> @GreatestOfAllTimee
> 
> solution in your file custom/plugins/init.lua paste:
> 
> ```
> ["NvChad/ui"] = {
>   override_options = {
>     tabufline = {
>       enabled = true,
>       lazyload = false,
>       overriden_modules = nil,
>    },
>   },
> },
> ```
> 
> in the lazyload option it must be false

["NvChad/ui"] = {
  override_options = {
    tabufline = {
      lazyload = false,
   },
  },
},
