### ISSUE TITLE
Cant use buffer close binding to kill a terminal buffer

### ISSUE THREAD

**Issue by JSilva6** [NvChad/NvChad#1215]
Trying to kill a buffer using the close_buffer function (default is <leader>x) when on a terminal buffer wont work.

**To Reproduce**
1: type :terminal echo "hello world"
2: on the new buffer, try closing using the <leader>x command

**Expected behavior**
Should close normally

**Screenshots**
![image](https://user-images.githubusercontent.com/43544777/173885644-afead6e9-cef1-45c0-a3e0-46affc89f4d7.png)
(translating the portuguesse message: Cant close last window)

**Desktop (please complete the following information):**
 - Operating System macos
 - Terminal alacritty / tmux-256color
 - Version of Neovim 0.7.0

**Comment by JSilva6** [comment]
Just removing these lines from close_buffer completely fixes the issue

`   if vim.bo.buftype == "terminal" then
      api.nvim_win_hide(0)
      return
   end
`

**Comment by siduck** [comment]
> Replacing `api.nvim_win_hide` with `vim.cmd('bd!')` in the lines below completely solves the issue
> 
> ![image](https://user-images.githubusercontent.com/43544777/173886797-0062edc2-d7f9-43ad-b235-f872eec7fbad.png)

we need that snippet to hide terminals ( leader pt )

**Comment by siduck** [comment]
@zbirenbaum

**Comment by zbirenbaum** [comment]
This is intended. Before, there was an issue post about <leader>-x on a term not allowing it to be re-toggled. Here, it's the reverse. @siduck I don't use <leader>-x personally so I don't care either way, but I think most people would want it to be re-togglable

**Comment by zbirenbaum** [comment]
Oh wait I didn't read closely enough. Ok how about it hides unless it's the last window in which case it deletes?

**Comment by zbirenbaum** [comment]
Alright I think I accounted for every possible edge case. Making the code pretty was the hardest part.

So you are aware @siduck i made the behavior that:

- if term is last window and last buffer: it does a forced close like it would for anything else (fixes this issue)

- if last win but there's another buffer available: it swaps to the other buffer and then force deletes the term. I thought about just swapping but we should probably be consistent and that's what non-terminals do. (I already know this would pop up in a week if I didn't do it now lol)

- if not last win: just hides it normally (same as before)
