### ISSUE TITLE
Lsp Format does not work

### ISSUE THREAD

**Issue by baddri** [NvChad/NvChad#1218]
**Describe the bug**
It said **[LSP] Format request failed, no matching language servers.**

**To Reproduce**
1. Open a file
2. \<leader\>fm

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49059318/174048723-8589b92d-1886-44a7-bd5d-d7c00693ebce.png)
:LspInfo
![image](https://user-images.githubusercontent.com/49059318/174048923-beac00a9-9324-46d4-89c1-988a550db04b.png)
~/.local/state/nvim/lsp.log
![image](https://user-images.githubusercontent.com/49059318/174049206-37097cac-163a-4302-a4bf-73ab9cacba0e.png)
null-lsconfig
![image](https://user-images.githubusercontent.com/49059318/174050217-7bcee942-0451-41b2-a5c3-910149df8a63.png)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 22
 - Terminal: Kitty
 - Version of Neovim: v0.8.0-dev+428-g1493efdc1

**Additional context**
after last update

**Comment by siduck** [comment]
did you use any formatter?

**Comment by siduck** [comment]
and which filetype are u trying to format

**Comment by baddri** [comment]
lua, using null-ls

**Comment by siduck** [comment]
where's stylua or luafmt? u need to define such formatters at least

**Comment by siduck** [comment]
sumneko doesnt do formatting ig

**Comment by tomasky** [comment]
No ,sumneko_lua has a formatter,check your lspconfig,

**Comment by siduck** [comment]
oh i didnt see stylua in your nullls conf

**Comment by baddri** [comment]
> 

i just add it. i delete it before to try things

**Comment by siduck** [comment]
it should work, i use stylua everyday, there's some issue with your setup ig

**Comment by baddri** [comment]
![image](https://user-images.githubusercontent.com/49059318/174059949-bb4d02bd-bdd3-4bca-9d72-2705c46eb529.png)
it does

**Comment by tomasky** [comment]
because these lines, sumneko_lua formatter not works, please use null-ls stylelua:
```lua
   -- client.server_capabilities.documentFormattingProvider = false
   -- client.server_capabilities.documentRangeFormattingProvider = false
```

**Comment by tomasky** [comment]
because these lines, sumneko_lua formatter not works, please use null-ls stylelua:
```lua
   -- client.server_capabilities.documentFormattingProvider = false
   -- client.server_capabilities.documentRangeFormattingProvider = false
```

**Comment by tomasky** [comment]
this is my null-ls config:

```lua
M.setup = function()
   null_ls.setup {
      debug = true,
      sources = sources,
      on_attach = function(client, bufnr)
         if client.supports_method "textDocument/formatting" then
            -- vim.api.nvim_clear_autocmds { group = augroup, buffer = bufnr }
            -- vim.api.nvim_create_autocmd("BufWritePre", {
            --    group = augroup,
            --    buffer = bufnr,
            --    callback = function()
            --      vim.lsp.buf.format { async = true }
            --    end,
            -- })
            local map = vim.keymap.set
            map("n", "<Leader>fm", function()
               vim.lsp.buf.format { filter = filter, async = true }
            end, { silent = true })
         end
      end,
   }
end
```
