### ISSUE TITLE
NvChadSnapshots are here (BETA release)

### ISSUE THREAD

**Issue by LeonHeidelbach** [NvChad/NvChad#1221]
As the title says, I have been working on implementing a Snapshot feature for NvChad. The NvChadSnapshot feature will create full backups of your entire NvChad configuration, including all currently installed plugin versions using "PackerSnapshots" as well as your current custom folder setup and also commited changes outside of the custom folder. To use NvChadSnapshots you will find 3 new available commands in your nvim commands:

* NvChadSnapshotCreate
* NvChadSnapshotDelete
* NvChadSnapshotCheckout

Those commands let you create, delete and switch between Snapshots. Snapshots will be managed using Git branches, however do not switch between snapshot branches manually as this will remove your custom folder when switching from a Snapshot back to the main update branch. If you do it anyways, dont't worry, you will not lose your configuration! NvChad always keeps backups of the last 4 versions of your custom directory in the Git Stash so you will not lose any data. Simply use `git stash list` to see all backups of your custom directory, that NvChad created and `git stash apply <stash_index>` to restore your custom directory. All stash entries will have timestamps that let you know, when they were created.

Enough talking though, here is a shot feature preview video! I am looking forward to your feedback, bug reports and feature requests. If you like this feature, feel free to leave a <3 on this post ;).

https://user-images.githubusercontent.com/55194243/174138488-19d5d57c-3b67-4165-8308-5d4d4a76e211.mp4

**Comment by tomasky** [comment]
Nice ,I've thought about these features of `git stash` before

**Comment by siduck** [comment]
Guys in this video I will show you how the snapshot feature is useful when dealing with breaking changes, watch

https://user-images.githubusercontent.com/59060246/174423575-4cfbfbd7-814a-4985-80aa-da26848d09d8.mp4

@LeonHeidelbach works great

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/174424526-8714c48d-ce4c-4930-97e5-2cc61c22f11b.mp4

It works well @LeonHeidelbach :rocket:

**Comment by LeonHeidelbach** [comment]
@siduck Great that everything is working as expected :smile::+1:. There is only one thing that you glanced over in your video, which is very important. When you use `NvChadSnapshoCheckout` you will have to wait for packer to complete the plugin rollback AND should never use `PackerSync` on a snapshot branch as this will pull all NvChad dependencies and will break configs, if there are breaking changes in them. That's why I put a warning message at the end of the checkout process which is not present in my demo video. I might have to update it.

![Screenshot_20220618_115717](https://user-images.githubusercontent.com/55194243/174432766-6a8958e9-fa68-4feb-a8b7-b0cab9779a21.png)

You will have to wait for the following message from packer to pop up at the bottom in order for packer to successfully compelete rolling back all of your plugins. Running `PackerSync` afterwards will revert the rollback and will cause issues if breaking changes occured. If you did accidently ran `PackerSync` on a snapshot branch, you can simply use `PackerSnapshotRollback <NvChadSnapshot_NAME>` and wait for the completion notification or use `NvChadSnapshotCheckout` to switch to the update branch and switch back to the snapshot. This time you should wait for packer to complete it's rollback procedure. In some cases this can even take a couple of minutes, depending on the number of plugins that packer needs to roll back.

![Screenshot_20220618_120207](https://user-images.githubusercontent.com/55194243/174432927-d85661ad-8862-4b81-8a13-91a3746ee36b.png)

**Comment by siduck** [comment]
@LeonHeidelbach it didnt print anything so i did the packersync myself, it'd be great if it'd keep printing "in progress" or something like that until the packersnapshot gets created

**Comment by LeonHeidelbach** [comment]
@siduck yeah, I know. It takes quite some time, you will just have to wait. The problem here is that packer runs the rollback task asynchronously. I tried to await the it with packers await function but it sadly did not work. I might have to dig a little deeper to find out how to do that properly.

**Comment by LeonHeidelbach** [comment]
@siduck that's how long it takes on my machine:

https://user-images.githubusercontent.com/55194243/174433642-fdb4f8b5-5783-4bce-9442-b261ed373ea2.mp4
