### ISSUE TITLE
Caret jumps around erratically when pressing tab in insert mode after using a snippet

### ISSUE THREAD

**Issue by FelixKratz** [NvChad/NvChad#1223]
**Describe the bug**
Caret jumps around erratically when pressing tab in insert mode after using a snippet

**To Reproduce**
use snippet, try to use tab afterwards

**Expected behavior**
The jumping should only happen in the bounds of the snippet and should be cancelled completely when leaving insert mode after a completion

**Screenshots**

https://user-images.githubusercontent.com/22680421/174242371-387d4f9d-df62-4bf2-a547-52416a5b4d34.mp4

**Comment by LeonHeidelbach** [comment]
This also happenes with multi cursor snippets and can mess up the entire document if you continue typing after wanting to exit the multicursor mode of the snippet. Had this happen a couple of times.

**Comment by FelixKratz** [comment]
I did some digging, this seems to be expected behavior from LuaSnip. I find it totally distracting to be honest. Relevant issue at their repo: https://github.com/L3MON4D3/LuaSnip/issues/258

**Comment by siduck** [comment]
Im unable to reproduce this with html/shell snippets

**Comment by FelixKratz** [comment]
This auto command by @L3MON4D3:
```lua
autocmd("InsertLeave", {
  callback = function()
    vim.opt.relativenumber = false
    if require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()]
      and not require("luasnip").session.jump_active then
      require("luasnip").unlink_current()
    end
  end,
})
```
added to `init.lua` fixes the problem. I believe it should be default.
