### ISSUE TITLE
Keep the cursor position while selecting a word (asterisk)

### ISSUE THREAD

**Issue by horta** [NvChad/NvChad#1224]
Enter the following in your neovim:

```
nnoremap * <Cmd>let @/='\<'.expand('<cword>').'\>'<bar>set hlsearch<CR>
```

Typing * now selects the words without moving the cursor. I bet you will find it very useful =)

Source: https://vi.stackexchange.com/a/22889

**Comment by siduck** [comment]
@horta can you provide a video of how this looks? I'll add it in the main repo if I like it :D

**Comment by horta** [comment]
https://user-images.githubusercontent.com/514522/174630722-36eb2ed1-4790-4d1d-8e5f-0d74dba1f38a.mov

I type `*` to search BUFFSIZE (word under the cursor). Then I enable the above proposal and type `*` for  BUFFSIZE and other words. Notice that the cursor select the word under the cursor (and highlight all of them in the screen) without moving the screen.

It is very nice =)

**Comment by LeonHeidelbach** [comment]
@siduck @horta yes, we definitely need this, the default jumping behavior is so annoying!

**Comment by horta** [comment]
That is such a nice feature, right? It basically replaces plugins that highlight words under the cursor and maintain the same functionality that `*` has. I will have a look on how to make it in lua, @siduck Thanks!

**Comment by siduck** [comment]
yep I love it, add a PR for it :)

**Comment by horta** [comment]
Can I ask questions here before I open an PR?

I managed to translate it to lua:

```lua
vim.fn.setreg("/", "\\<" .. vim.fn.expand("<cword>") .. "\\>")
vim.opt.hlsearch = true
```

The first line set the register `"/` to the string `\<word_under_the_cursor\>` and then set the `hlsearch` option to true.

Would it make sense to have a lua function like

```lua
function Shine()
    vim.fn.setreg("/", "\\<" .. vim.fn.expand("<cword>") .. "\\>")
    vim.opt.hlsearch = true
end
```

?


I'm aware that Nvchad use plugins developed by @siduck , does it make sense to have that function in there?

**Comment by siduck** [comment]
@horta add it in the core.options.lua file
