### ISSUE TITLE
Can not remove indent-blankline.

### ISSUE THREAD

**Issue by songww** [NvChad/NvChad#1225]
**Describe the bug**
It always try to load `indent-blankline.nvim` even this plugin was removed.

**To Reproduce**
1. Add `indent-blankline.nvim` to plugins.remove of 'custom/chadrc.lua'
2. Open any file

**Expected behavior**
`indent-blankline.nvim` should be removed with no error.

**Screenshots**

![图片](https://user-images.githubusercontent.com/8115960/174273229-bed6a7b9-6605-426b-814e-ac72a0dff235.png)

**Desktop (please complete the following information):**
 - Debian sid
 - kitty
 - Version of Neovim: 0.7

**Comment by siduck** [comment]
when was the last time you updated nvchad? this issue was fixed before pls update nvchad and packersync
