### ISSUE TITLE
Allow the ability to disable loading snippets from vscode

### ISSUE THREAD

**Issue by uyha** [NvChad/NvChad#1229]
**Is your feature request related to a problem? Please describe.**
Currently, `require("luasnip.loaders.from_vscode").lazy_load()` in `lua/plugins/configs/others.lua` is being run unconditionally which doesn't allow the ability to disable it to stop the snippets inside it from being loaded in.

**Describe the solution you'd like**
Provide the ability to disable it.

**Comment by siduck** [comment]
Hmm ig you have to replace luasnip's configs with yours

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#modify-plugin-definition-options
