### ISSUE TITLE
Provider not working with default config, unable to override

### ISSUE THREAD

**Issue by mihneaCR** [NvChad/NvChad#1230]
When running :checkhealth provider, an error occurs, unless
![nvchadprovider](https://user-images.githubusercontent.com/47532611/174334652-c059e439-871a-49c7-b139-e55b0ed6a2bd.png)

"python3_provider",
"python_provider",
"node_provider",
"ruby_provider",
"perl_provider",
are commented out in lua/core/options.lua.

I have already tried overriding using chadrc like suggested in #1168:

`M.options = {
   user = function()
        vim.opt.relativenumber = true
        vim.opt.shiftwidth = 4
        vim.opt.wrap = false
    end,
    disable_default_plugins = {
       "2html_plugin",  
       "getscript",  
       "getscriptPlugin",  
       "gzip",  
       "logipat",
       "netrw",
       "netrwPlugin",
       "netrwSettings",
       "netrwFileHandlers",
       "matchit",
       "tar",
       "tarPlugin",
       "rrhelper",
       "spellfile_plugin",
       "vimball",
       "vimballPlugin",
       "zip",
       "zipPlugin",
       -- "python3_provider",
       -- "python_provider",
       -- "node_provider",
       -- "ruby_provider",
       -- "perl_provider",
       "tutor",
       "rplugin",
       "syntax",
       "synmenu",
       "optwin",
       "compiler",
       "bugreport",
       "ftplugin",
    },
}
`
This however does not change the behavior in any way, only commenting out the lines in options.lua works. Any suggestions on how to change this?

**Comment by lll9p** [comment]
Maybe you can fix like this.

```lua
M.options = {
  user = function()
    local enable_providers = {
      "python3_provider",
      "node_provider",
      -- and so on
    }
    for _, plugin in pairs(enable_providers) do
      vim.g["loaded_" .. plugin] = nil
      vim.cmd("runtime " .. plugin)
    end
  end,
}


```

**Comment by mihneaCR** [comment]
> Maybe you can fix like this.
> 
> ```lua
> M.options = {
>   user = function()
>     local enable_providers = {
>       "python3_provider",
>       "node_provider",
>       -- and so on
>     }
>     for _, plugin in pairs(enable_providers) do
>       vim.g["loaded_" .. plugin] = nil
>       vim.cmd("runtime " .. plugin)
>     end
>   end,
> }
> ```

Thanks for this, it fixed my issue!

**Comment by GreatestOfAllTimee** [comment]
> Maybe you can fix like this.
> 
> ```lua
> M.options = {
>   user = function()
>     local enable_providers = {
>       "python3_provider",
>       "node_provider",
>       -- and so on
>     }
>     for _, plugin in pairs(enable_providers) do
>       vim.g["loaded_" .. plugin] = nil
>       vim.cmd("runtime " .. plugin)
>     end
>   end,
> }
> ```

Its weird, this is nvchad bug.


```lua
for _, plugin in pairs(enable_providers) do
      vim.g["loaded_" .. plugin] = nil
      vim.cmd("runtime " .. plugin)
    end
```

Nvchad should handle this by default if `enable_providers` in chadrc.lua is define

**Comment by siduck** [comment]
@GreatestOfAllTimee that isnt a bug, one must enable those defaultly disabled plugins in options.lua by that loop only

**Comment by GreatestOfAllTimee** [comment]
@siduck according to https://github.com/NvChad/NvChad/issues/1168#issuecomment-1145270844 users can disable a specific plugins provider by follow that step.

What I understand #1168 he _**don't want to disable**_ `netrwPlugin`, `netrwSettings` & `netrwFileHandlers`.

---

### _This does not work_
<details>

```lua
local M = {}

...

M.options = {
   user = function()
      require "custom.options"
   end,

   disable_default_plugins = {
      "2html_plugin",
      "getscript",
      "getscriptPlugin",
      "gzip",
      "logipat",
      "netrw",
      "netrwPlugin",
      "netrwSettings",
      "netrwFileHandlers",
      "matchit",
      "tar",
      "tarPlugin",
      "rrhelper",
      "spellfile_plugin",
      "vimball",
      "vimballPlugin",
      "zip",
      "zipPlugin",
      --- remove unwanted providers instead
      -- "python3_provider",
      -- "python_provider",
      -- "node_provider",
      -- "ruby_provider",
      -- "perl_provider",
      "tutor",
      "rplugin",
      "syntax",
      "synmenu",
      "optwin",
      "compiler",
      "bugreport",
      "ftplugin",
   },
}

...

return M
```

</details>

**Comment by siduck** [comment]
why would it work if its not even present in the default_config.lua?

![image](https://user-images.githubusercontent.com/59060246/174433974-e2c91461-3f2b-493e-aef3-88d883ab5128.png)

**Comment by siduck** [comment]
that was the old syntax

**Comment by GreatestOfAllTimee** [comment]
ohh didn't realize 16 days ago was that _old_ 😭.

**Comment by GreatestOfAllTimee** [comment]
so that means there is no builtin options user can disable that.

**Comment by siduck** [comment]
> so that means there is no builtin options user can disable that.

its not needed, the method provided by @lll9p is the only method to enable the defaultly disabled builtin vim plugins in nvchad, I did mention it in one of the [commits](https://github.com/NvChad/NvChad/commit/9e3a43302c57d61f78b21e6f565d8026f5bd8d19#commitcomment-75231831), I'll add it in the docs

**Comment by fullstopslash** [comment]
I'm also unable to get the python_provider working, try as i might. even with this snippet involved.
```lua
M.options = {
  user = function()
    local enable_providers = {
      "python3_provider",
      "node_provider",
      -- and so on
    }
    for _, plugin in pairs(enable_providers) do
      vim.g["loaded_" .. plugin] = nil
      vim.cmd("runtime " .. plugin)
    end
  end,
}
```

**Comment by siduck** [comment]
@fullstopslash you should know that M.options.user is no longer there, just put your options in custom init.lua

**Comment by gegnew** [comment]
@siduck 
it should be
```lua
local enable_providers = {
      "python3_provider",
    }
for _, plugin in pairs(enable_providers) do
    vim.g["loaded_" .. plugin] = nil
    vim.cmd("runtime " .. plugin)
end
```

in `custom/init.lua`, yes? 

This does not work for me. Nor does:
```lua
vim.g['loaded_python3_provider'] = nil
vim.cmd("runtime python3_provider")
```

However, running those manually _after_ starting nvim does work. It seems like something is still borked in the order of how options are getting loaded.

For instance:

- If I set `opt.scrolloff = 3` in `custom/init.lua`, then Nvim picks it up fine (`:set scrolloff` returns '3'). Note that `scrolloff` is _not_ set in `core/options.lua`.
- If I set `opt.updatetime = 150` (it is set to 250 in `core/options.lua`), then `:set updatetime` returns 250

**Comment by gegnew** [comment]
of course, changing the line in `core/options.lua` works :shrug: 
```lua
for _, provider in ipairs(default_providers) do
  vim.g["loaded_" .. provider .. "_provider"] = nil -- <-- nil
end
```

**Comment by siduck** [comment]
> of course, changing the line in `core/options.lua` works shrug
> 
> ```lua
> for _, provider in ipairs(default_providers) do
>   vim.g["loaded_" .. provider .. "_provider"] = nil -- <-- nil
> end
> ```

dont, add your options in custom/init.lua

**Comment by gegnew** [comment]
Well, yes, of course, but if it doesn't work, then...

> @siduck it should be
> 
> ```lua
> local enable_providers = {
>       "python3_provider",
>     }
> for _, plugin in pairs(enable_providers) do
>     vim.g["loaded_" .. plugin] = nil
>     vim.cmd("runtime " .. plugin)
> end
> ```
> 
> in `custom/init.lua`, yes?
> 
> This does not work for me. Nor does:
> 
> ```lua
> vim.g['loaded_python3_provider'] = nil
> vim.cmd("runtime python3_provider")
> ```
> 
> However, running those manually _after_ starting nvim does work. It seems like something is still borked in the order of how options are getting loaded.
> 
> For instance:
> 
>     * If I set `opt.scrolloff = 3` in `custom/init.lua`, then Nvim picks it up fine (`:set scrolloff` returns '3'). Note that `scrolloff` is _not_ set in `core/options.lua`.
> 
>     * If I set `opt.updatetime = 150` (it is set to 250 in `core/options.lua`), then `:set updatetime` returns 250

I think this is a bigger issue

**Comment by siduck** [comment]
can you make a new issue for this?
