### ISSUE TITLE
Pyright does not start at all

### ISSUE THREAD

**Issue by zstg** [NvChad/NvChad#1231]
**Describe the bug**
After installing Pyright using `:LspInstall pyright` it does not seem to start , even when the lspconfig line is added to `lua\custom\init.lua`

**Expected behavior**
Pyright starts 

**Desktop (please complete the following information):**
 - Windows 11
 - Windows Terminal
 - Neovim 0.7

**Comment by LeonHeidelbach** [comment]
@zstg Please read the documentation, you need to attach the LSP to the buffer as described here: https://nvchad.github.io/config/Lsp%20stuff.

**Comment by zstg** [comment]
I’ve already tried this , and LspInstall

Both don’t work

**Comment by siduck** [comment]
is it even defined in your lspconfig?

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/174421960-70834441-c5da-4655-8ad0-48fd70987e3c.mp4

**Comment by zstg** [comment]
It doesn’t look like an lspconfig.lua file is generated in the first place

when i tried creating it in my `custom` folder Nvim says there isn’t a file in another location

**Comment by siduck** [comment]
create custom folder in ~/.config/nvim/lua

**Comment by siduck** [comment]
looks like your system issue

**Comment by siduck** [comment]
refer my dotfile repo's nvchad folder as an example

**Comment by zstg** [comment]
> looks like your system issue

This was working for me even 2 days ago
I'm using Windows 11 
Cannot be a system issue for sure

**Comment by siduck** [comment]
i showed you in the video, it works very well here. make sure your lsp server is installed

**Comment by zstg** [comment]
![image](https://user-images.githubusercontent.com/69384921/174424189-d2f24af2-1a20-4245-9f14-30ad9b633df6.png)
![image](https://user-images.githubusercontent.com/69384921/174424195-2aed4905-68a5-4842-b8d8-40f121663551.png)
![image](https://user-images.githubusercontent.com/69384921/174424209-4c877cbc-dda0-4575-a9fb-daeb8fd38061.png)

When i open an untitled file (using `nvim`) the LspInstaller plugin isn't detected

**Comment by siduck** [comment]
can you try a clean install? lspinstall& lspconfig will be loaded when there is a file opened, I'll add an option to load it in cmdline too

**Comment by zstg** [comment]
Tried a clean install
Now it's showing this error:
![image](https://user-images.githubusercontent.com/69384921/174428076-e5a20687-5573-4156-8cdd-a193cbd3c7eb.png)

**Comment by siduck** [comment]
very weird, i cant reproduce this error

**Comment by deformator852** [comment]
I have the same error.

**Comment by siduck** [comment]
> I have the same error.

we dont use packer.nvim in nvchad v2.0 so what error are you having ? please enable pyright in custom lspconfig

**Comment by deformator852** [comment]
### not an editor command LspInstall

**Comment by siduck** [comment]
> ### not an editor command LspInstall

LspInstall was from lspinstaller, please check mason.nvim .

And please read docs from nvchad.com
