### ISSUE TITLE
Themes not loading properly

### ISSUE THREAD

**Issue by JSilva6** [NvChad/NvChad#1232]
After the latest update, my nvchad theme isnt working as intended.
I had set the theme onedark with < leader >th long ago, but I just notice something strange today

![image](https://user-images.githubusercontent.com/43544777/174349957-2a399b73-3934-43c8-b12a-8e9035371b22.png)

They white is waaaay brighter than it should. Funny thing is that bringing up the Telescope theme selector will show a proper onedark coloring

![image](https://user-images.githubusercontent.com/43544777/174350081-7bf11870-b358-4925-b0d0-7ce3bf9e7dc9.png)

Pressing enter and setting as default seems to work just fine for a while, but when trying to enter insert mode, a strange error comes up.

![image](https://user-images.githubusercontent.com/43544777/174350204-6d721fae-f81d-4973-95b6-49b2f3454771.png)

Resetting nvim will just go back to the way bright theme all over again.

Funny thing: If I try to swap to ANOTHER theme and set it as default, after resetting nvim, it goes back to the buggy onedark.

I even tried setting onedark as a theme on my .chadrc, but no effect.

**Desktop (please complete the following information):**
 - Operating System -  macos
 - Terminal - alacritty / tmux
 - Version of Neovim - v0.7.0

**Comment by siduck** [comment]
@JSilva6 this should get fixed after a clean nvchad install
