### ISSUE TITLE
NvimTree cannot be opened if directory is selected

### ISSUE THREAD

**Issue by exsesx** [NvChad/NvChad#1234]
**Describe the bug**

**To Reproduce**
1. Use `nvim ./directory` with `open_on_setup = true` nvim tree config property.

**Expected behavior**
NvimTree shows up.

**Desktop (please complete the following information):**
 - Operating System: macOS
 - Terminal: Alacritty, iTerm2
 - Version of Neovim: 0.8.0
 
 I need help on this one. What should be done to make the project file tree open immediately when a directory is selected as an entry point?

- [x] Tried autocmd in `init.lua`, but no luck

**Comment by siduck** [comment]
that alone wont work, you have to remove nvimtree's lazy loading so first add nvimtree into your chadrc's plugin remove section then add this in your custom plugins section 


```lua
   ["kyazdani42/nvim-tree.lua"] = {
      after = "base46",
      config = function()
         require "plugins.configs.nvimtree"
      end,
   },
```

do packersync

**Comment by idr4n** [comment]
@siduck what is the best approach to do this currently? I have added an autocmd which works fine but not sure if it is the best approach:

```lua
vim.api.nvim_create_autocmd("VimEnter", {
  group = vim.api.nvim_create_augroup("nvim-tree-enter", { clear = true }),
  callback = function()
    if vim.fn.argc() == 1 and vim.fn.isdirectory(vim.fn.argv(0)) == 1 then
      require("nvim-tree.api").tree.open()
    end
  end,
})
```

Also, how to make nvim-tree behave as vim-dirvish, that is, opening it in a full size window with a keybinding, e.g., "-".

**Comment by siduck** [comment]
@idr4n iirc that approach is in nvimtree docs so its the best approach. but i use this shell function instead

```bash
nv() {
  [ -n "$1" ] && [ -d "$1" ] && cd "$1" && shift
  nvim +'lua require("nvim-tree.api").tree.open()'  "$@"
}
```
