### ISSUE TITLE
Cannot override `nvim-cmp` mappings

### ISSUE THREAD

**Issue by BinhaoQin** [NvChad/NvChad#1236]
**Describe the bug**
Overriding `nvim-cmp` fails

**To Reproduce**
1. Put the following into plugin override table:
```lua
local cmp = require("cmp")
["hrsh7th/nvim-cmp"] = {
      mapping = {
         ["<C-CR>"] = cmp.mapping.confirm {
            behavior = cmp.ConfirmBehavior.Insert,
            select = true,
         },
         ["<CR>"] = cmp.mapping.close(),
      },
 }
```
2. custom configs fail to start

**Expected behavior**
Overrides default cmp mappings

**Desktop (please complete the following information):**
 - Garuda Linux
 - Kitty
 - 0.7.0

**Additional context**
It is probably because `cmp` is now lazy loaded and requiring `cmp` in config file fails.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/commit/771046a7385b22eb544f64d7e72f324cfb29e215

**Comment by siduck** [comment]
try this 

```lua

["hrsh7th/nvim-cmp"] =  function()
local cmp = require("cmp")

return {
      mapping = {
         ["<C-CR>"] = cmp.mapping.confirm {
            behavior = cmp.ConfirmBehavior.Insert,
            select = true,
         },
         ["<CR>"] = cmp.mapping.close(),
      },

}
 end
 ```

**Comment by BinhaoQin** [comment]
That works. Thank you very much!
