### ISSUE TITLE
diff (gitsigns) highlights reset when running Packer

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1237]
### **Describe the bug**
weird highlights while running `:PackerSync`, watch the gif below for more information. This only applies when running Packer, LspIntaller does not seem to have this behavior.

### **To Reproduce**
1. Open any files
2. `:PackerSync`

### **Expected behavior**
as we expect

### **Screenshots/Videos**
![Nvchad_Highlight_Packersync](https://user-images.githubusercontent.com/73665622/174484406-b9842707-c18e-47a7-a199-3751e65c9ca0.gif)

**Comment by siduck** [comment]
this seems like an issue with the lazyloading of gitsigns

![image](https://user-images.githubusercontent.com/59060246/174485291-239b9c85-df97-4bdf-8a3c-a1104dbc5f76.png)

Remove it and try this one, if it gets fixed then i'll look at the lazy loading code

**Comment by GreatestOfAllTimee** [comment]
does not seem to work either. 

![image](https://user-images.githubusercontent.com/73665622/174485488-01a172ee-4a76-4938-acb6-f495ca3bec00.png)

**Comment by GreatestOfAllTimee** [comment]
not only PackerSync but PackerCompile also seems to reset highlight.

**Comment by siduck** [comment]
> does not seem to work either.
> 
> ![image](https://user-images.githubusercontent.com/73665622/174485488-01a172ee-4a76-4938-acb6-f495ca3bec00.png)
> 
> EDIT: this screenshot on the lua file, the curly brackets turn orange. I think this has not completely reset the highlights

do a packersync after this change

**Comment by siduck** [comment]
> not only PackerSync but PackerCompile also happens
happens with packersync cuz we enabled compile after sync

**Comment by GreatestOfAllTimee** [comment]
> do a packersync after this change

yah ofcource I've done that

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/174487254-5b8fd6d1-79c6-4b99-ae7c-0ab9ffee1f59.mp4

Removing the lazyloading fixes it here tho

**Comment by GreatestOfAllTimee** [comment]
I'm not sure how this happened but I can't reproduce this

https://user-images.githubusercontent.com/73665622/174494537-7dd3d83b-c359-4716-853d-eaf014ac7c5f.mov

---

can you try comment on all `lewis6991/gitsigns.nvim` (which means uninstall gitsigns). after done uninstall, reinstall using your method above. see how it goes

**Comment by siduck** [comment]
fixed

**Comment by GreatestOfAllTimee** [comment]
no it's not 🤣 

![Nvchad_Highlight_Packersync2](https://user-images.githubusercontent.com/73665622/175493567-74e9c570-8085-4469-9ffb-60c4d24963aa.gif)

NOTE: I already update latest nvchad and do packersync/packercompile

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/175498000-0d4302b1-99a7-4c23-9122-7b50e8d233f6.mp4

It is fixed bruh, gitsign's lazy loading caused this and i showed a clear proof. Show me a clean installation of nvchad ( remove all nvim folders first ) then show me if the highlights persist

**Comment by siduck** [comment]
I thought only the resetting of gitsign highlights was the issue but this is another thing

**Comment by siduck** [comment]
Before and after packercompile 


![image](https://user-images.githubusercontent.com/59060246/175500505-6d7b5b02-19b1-45ed-a763-5c4aa169bdaa.png)


![image](https://user-images.githubusercontent.com/59060246/175500441-9b613fa4-2200-4607-b6f1-5bafa565d570.png)

**Comment by siduck** [comment]
i saw the same thing with diff related highlight groups, it was using cterm colors straight after packercompile. Very weird. Didnt know syntax highlights were facing the same issue too

**Comment by siduck** [comment]
@GreatestOfAllTimee 
![image](https://user-images.githubusercontent.com/59060246/175503152-b0f3f4bc-c4cc-499b-a742-969b0a785012.png)

Add this and it gets fixed, i think the highlights get broken cuz the packercompiled gets autoreloaded

**Comment by GreatestOfAllTimee** [comment]
yah this one works

what `auto_reload_compiled` do? shouldn't it be set to `true` right?

**Comment by GreatestOfAllTimee** [comment]
unrelated question, how do I disable this?

![Screenshot 2022-06-24 220515](https://user-images.githubusercontent.com/73665622/175552386-73cedc0f-3c39-4a9b-a593-aa930eb0030a.png)

**Comment by siduck** [comment]
> yah this one works
> 
> what `auto_reload_compiled` do? shouldn't it be set to `true` right?

dont worry thats not needed , i got another solution ( this was all related to vim.opt.bg setting multiple times when packercompile gets executed ) 


Also for the image you showed, just look at blankline config and disable the context part. override your config
