### ISSUE TITLE
Recent change to core.utils.load_override broke using functions for plugin override

### ISSUE THREAD

**Issue by endoze** [NvChad/NvChad#1239]
**Describe the bug**
[This recent change to core.utils broke using a function to configure plugin override](https://github.com/NvChad/NvChad/commit/9bca3eacaefd9857194372564767c0037bd6d67f#diff-a3350cff9394d63ea1bb7c03b41470afd48d9d9d6db859b0d176e7b761ad3779L153-L155)

**To Reproduce**
```lua
-- lua/custom/chadrc.lua
local M = {}

M.plugins = {
  override = {
    ["nvim-telescope/telescope.nvim"] = function()
      local actions = require('telescope.actions')

      return {
        defaults = {
          mappings = {
            i = {
              ["<C-j>"] = actions.move_selection_next,
              ["<C-k>"] = actions.move_selection_previous,
            }
          }
        }
      }
    end
  }
}

return M
```

**Expected behavior**
This configuration in chadrc.lua should add additional keybinds to telescope in insert mode for navigation.

**Desktop (please complete the following information):**
 - MacOS
 - iTerm2
 - NVIM v0.7.0

**Additional context**
The reason this recent change broke is previously the function returned a table, then this table was merged with the default configuration for any particular plugin. By combining all of the logic into one if/elseif/else statement, we lose merging the table returned from the function into the default_table.

The following could be fixed by reverting the code to something similar depending on needs:

```lua
-- lua/core/utils.lua

M.load_override = function(default_table, plugin_name)
   local user_table = M.load_config().plugins.override[plugin_name]

    if type(user_table) == "function" then
       user_table = user_table()
    end

    if type(user_table) == "table" then
       default_table = merge_tb("force", default_table, user_table)
    else
       default_table = default_table
   end

   return default_table
end
```

**Comment by siduck** [comment]
@endoze send a PR for it, busy atm
