### ISSUE TITLE
Unable to Make Italic Comments

### ISSUE THREAD

**Issue by irondeau** [NvChad/NvChad#1241]
**Describe the bug**
Using the hl_override property, I am unable to create italicized comments. May be related to issue #1233 

**To Reproduce**
1. Add the following property to the config file:
```lua
M.ui = {
  hl_override = {
    Comment = { italic = true },
  },
}
```

**Expected behavior**
Comments are italicized

**Screenshots**
![image](https://user-images.githubusercontent.com/25674784/174507701-04736371-8626-4fbe-b727-f4a4d5238be0.png)

**Desktop (please complete the following information):**
 - Operating System: Artix Linux
 - Terminal: Kitty
 - Version of Neovim: v0.7.0

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/174508160-e8f18aef-39b5-4a96-8537-97b68d2de98c.png)

**Comment by irondeau** [comment]
Turns out this is, in fact, a font issue.

**Comment by ckt114** [comment]
@irondeau What font did you ended up using? I used NerdFont but it's not working either.

**Comment by siduck** [comment]
> @irondeau What font did you ended up using? I used NerdFont but it's not working either.

try jetbrainsmono
