### ISSUE TITLE
jk as Esc with fresh installation of nvchad and re mapping in custom dir not working

### ISSUE THREAD

**Issue by barungh** [NvChad/NvChad#1243]
**mapping jk to Esc in custom dir does not work**

OS: Arch Linux
Neovim version: 0.7

with a fresh installation of nvchad, and remaping jk to Esc in custom dir as mentioned in #1206 it is not working

https://user-images.githubusercontent.com/12285528/174515822-2c5acbea-a170-4cc0-a0c4-b24ac295c70b.mp4

**Comment by siduck** [comment]
@barungh thats not how you define mappings, read our mappings doc!

**Comment by siduck** [comment]
M.mappings= {

M.abc = {
 ["jk']= {'<ESC>', 'escape normal mode'}
}

}
```

**Comment by barungh** [comment]
I did this, but to no avail 🙄

![Screenshot_2022-06-20-08-29-19_1366x768](https://user-images.githubusercontent.com/12285528/174517721-6686d816-dfa9-4861-b5db-b7509c13df6c.png)

**Comment by siduck** [comment]
![image](https://user-images.githubu:joy: ontent.com/59060246/174518044-28b1f488-d7a9-4245-9a18-e81eb4b5db25.png)

return M :joy

**Comment by barungh** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/174518062-179e9923-0575-4368-9fc9-d1384893b358.png)
> 
> return M 😂

🐮

**Comment by barungh** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/174518062-179e9923-0575-4368-9fc9-d1384893b358.png)
> 
> return M 😂

returning M too did not work, 

okay I will look into it, will find correct way to do it,
want to maintain my custom file,
sudden change is painful for me and my students
for now I directly edited the core mappings and it works
Your example config are also missing from docs, it would have been helpful

**Comment by siduck** [comment]
https://nvchad.github.io/config/Mappings#mappings-table-structure @barungh

**Comment by siduck** [comment]
```lua
local M = {}

M.misc = {
   i = {
      ["jk"] = { "<ESC>", "escape normal mode" },
   },
}

return M
```

**Comment by siduck** [comment]
it should work tho, i tested it myself :/

**Comment by siduck** [comment]
if it doesnt then definitely there's an issue with your custom config

**Comment by barungh** [comment]
I don't know what am I doing wrong, this is an ssh session to my student's Arch Linux machine
![image](https://user-images.githubusercontent.com/12285528/174521190-9852198b-40d3-4021-ad92-3a56f639dc7f.png)

**Comment by siduck** [comment]
no idea

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/174521795-944af075-a9a1-4dac-ae8d-5e6cf29b9428.mp4

**Comment by barungh** [comment]
> it should work tho, i tested it myself :/



> no idea

should it be `M.mappings = require "custom.mappings"`

or just `M.mappings = require "mappings"` because it is in the same folder ?

**Comment by siduck** [comment]
no custom.mappings

**Comment by barungh** [comment]
just did a fresh re installation of Nvchad again, implemented these settings 
and it worked 
thanks 😎

![image](https://user-images.githubusercontent.com/12285528/174523853-6d0e9e8e-77df-4b4b-a32d-4a38793d239c.png)

**Comment by siduck** [comment]
ofc lul, this is the new syntax. And you were using old nvchad so that mappings syntax didnt work for u. Update nvchad everday / once a week

**Comment by barungh** [comment]
> ofc lul, this is the new syntax. And you were using old nvchad so that mappings syntax didnt work for u. Update nvchad everday / once a week

ok sir 😁

**Comment by LeonHeidelbach** [comment]
@barungh If you want to make sure you always keep a working copy of NvChad around you can now use our new NvChadSnapshot feature, have a look https://github.com/NvChad/NvChad/issues/1221.
