### ISSUE TITLE
integrate vale to support syntax-aware writing

### ISSUE THREAD

**Issue by sangshuduo** [NvChad/NvChad#1245]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

Please see https://bhupesh.me/writing-like-a-pro-with-vale-and-neovim/ for details.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
this is more of user preferability as it involes null-ls

**Comment by siduck** [comment]
do it yourself :c
