### ISSUE TITLE
Ability to name which-key groups

### ISSUE THREAD

**Issue by lajoskvcs** [NvChad/NvChad#1246]
**Is your feature request related to a problem? Please describe.**
Right now if you register keys with which-key, you can't name them, so each group will be: `+prefix`.

**Describe the solution you'd like**
It would be amazing, if we can name these groups, so we can rely more on which-key.

**Describe alternatives you've considered**
-

**Additional context**

**Screenshot**
<img width="1267" alt="Screenshot 2022-06-20 at 17 12 07" src="https://user-images.githubusercontent.com/15230676/174632259-662c75e1-5e88-450f-9e05-2cf27e42afc7.png">

**Comment by LeonHeidelbach** [comment]
@lajoskvcs You can already do so, I implemented this quite some time ago but I think we are still missing documentation for it (maybe, I’m not sure). I won’t have time to add it this week but you can add groups using the `M.groups` key in your mappings table like this:

```lua
M.groups = {
  n = {
    ["<leader>"] = {
      c = { name = "code" },
      d = { name = "dap" },
      f = { name = "files" },
      g = { name = "git" },
      l = { name = "live server" },
      p = { name = "terms" },
      r = { name = "refactor" },
      t = { name = "telescope" },
      w = { name = "which-key/workspace" },
    },
  },
  v = {
    ["<leader>"] = {
      r = { name = "refactor" },
      t = { name = "markdown tables" },
    }
  }
}
```

You can find more info on this as well as example screenshots in my PR from back in the day https://github.com/NvChad/NvChad/pull/1092.

**Comment by lajoskvcs** [comment]
@LeonHeidelbach Thank you! Amazing!

**Comment by Mechanosec** [comment]
does not work for me(((

**Comment by siduck** [comment]
@Mechanosec check recently closed whichkey issues

**Comment by iamralch** [comment]
@siduck Groups do not work in the recent version. Is this feature still available?

**Comment by siduck** [comment]
> @siduck Groups do not work in the recent version. Is this feature still available?

just add your groups in your whichkey configs

**Comment by borea17** [comment]
> > @siduck Groups do not work in the recent version. Is this feature still available?
> 
> just add your groups in your whichkey configs

could you be more specific on how to do that?

**Comment by siduck** [comment]
> > > @siduck Groups do not work in the recent version. Is this feature still available?
> > 
> > 
> > just add your groups in your whichkey configs
> 
> could you be more specific on how to do that?

like how do you add groups to whichkey? you define it in your whichkey config right? 

read 
![image](https://user-images.githubusercontent.com/59060246/208637225-12db1c0d-213f-4d7e-8045-89be720abab0.png)

**Comment by borea17** [comment]
@siduck thx for the quick response! :) 

I was just wondering where exactly I should put this in the `NVChad` style config, i.e., where in the `custom` folder. I just started to use `NVChad` based on [this example config](https://github.com/NvChad/example_config), so maybe that is a stupid question. Still any help is very much appreciated :)

**Comment by siduck** [comment]
@borea17  

u should create a plugin definition in your custom plugins table so

[ 'whichkye blabla' ] = {
   config = function() 
       load the default config of whichkey first 
       
       then add your whichkey config here
   end
}

**Comment by borea17** [comment]
thx that helped :)  I ended up with this:

  ```lua
  ["folke/which-key.nvim"] = {
    disable = false,
    config = function()
      require("plugins.configs.whichkey")
      local present, wk = pcall(require, "which-key")
      if not present then
        return
      end
      wk.register(
        {
          -- add group
          ["<leader>"] = {
            f = {name="+file"},
          }
        }
      )
    end,
    setup = function()
      require("core.utils").load_mappings "whichkey"
    end,
  }
```

**Comment by xarthurx** [comment]
@siduck  coming back to this issue after some while.
Just to double check, the `M.groups` approach does not work now, and the recommended way to adding which-key group name is to use the default config, as shown here?

> thx that helped :) I ended up with this:
> 
> ```lua
> ["folke/which-key.nvim"] = {
>   disable = false,
>   config = function()
>     require("plugins.configs.whichkey")
>     local present, wk = pcall(require, "which-key")
>     if not present then
>       return
>     end
>     wk.register(
>       {
>         -- add group
>         ["<leader>"] = {
>           f = {name="+file"},
>         }
>       }
>     )
>   end,
>   setup = function()
>     require("core.utils").load_mappings "whichkey"
>   end,
> }
> ```

**Comment by siduck** [comment]
@borea17 the M.groups stuff isnt supported anymore so please check the above solution

**Comment by borea17** [comment]
@siduck the above solution is from me ;)

**Comment by stove-jeebs** [comment]
is there a way to do this with M.whichkey?

**Comment by siduck** [comment]
@stove-jeebs no

Edit: Yes, just add plugin=true to it and load those mappings in whcihkey config

**Comment by AidanJDeAngelis** [comment]
Hello! The above solution works except when keymaps are defined after which-key setup, such as the "<leader>l" LSP keybindings which are only created when the lsp on_attach method is called. Do you have any suggestions for how to ensure the group names appear in such cases?

**Comment by datcit241** [comment]
> thx that helped :) I ended up with this:
> 
> ```lua
> ["folke/which-key.nvim"] = {
>   disable = false,
>   config = function()
>     require("plugins.configs.whichkey")
>     local present, wk = pcall(require, "which-key")
>     if not present then
>       return
>     end
>     wk.register(
>       {
>         -- add group
>         ["<leader>"] = {
>           f = {name="+file"},
>         }
>       }
>     )
>   end,
>   setup = function()
>     require("core.utils").load_mappings "whichkey"
>   end,
> }
> ```

sorry where do I put this please? I put it into custom/plugins and inside the ```local plugins = {``` but it doesn't get called

**Comment by siduck** [comment]
@datcit241  that doenst load cuz its not a valid lazy nvim syntax, please check the default plugin list and you'll know the pattern!

**Comment by datcit241** [comment]
> @datcit241 that doenst load cuz its not a valid lazy nvim syntax, please check the default plugin list and you'll know the pattern!

can you be more specific? sorry I'm new, I want to add group names to which-key I'm happy with whatever the possible solution is

**Comment by siduck** [comment]
@datcit241 please check lua/plugins/init.lua file. please read https://nvchad.com/docs/config/plugins

**Comment by datcit241** [comment]
> @datcit241 please check lua/plugins/init.lua file. please read https://nvchad.com/docs/config/plugins

sorry, I do understand the syntax to install plugins with Lazy but I just don't know how to name which-key groups

**Comment by siduck** [comment]
@datcit241 then you cannot do it... please read all of nvchad.com docs from start to end, it'll save your time in future :/

**Comment by datcit241** [comment]
> @datcit241 then you cannot do it... please read all of nvchad.com docs from start to end, it'll save your time in future :/

I did XD it's just that there isn't anything related to this naming which-key groups I'm actually not quite new but I still don't understand the solution for this that's it, but I did read the docs carefully.

**Comment by borea17** [comment]
@datcit241 this is my config with lazy:

```
	{
		"folke/which-key.nvim",
		config = function(_, opts)
			dofile(vim.g.base46_cache .. "whichkey")
			require("which-key").setup(opts)
			local present, wk = pcall(require, "which-key")
			if not present then
				return
			end
			wk.register({
				-- add group
				["<leader>"] = {
					f = { name = "+file" },
				},
			})
		end,
		setup = function()
			require("core.utils").load_mappings("whichkey")
		end,
	},

```

**Comment by datcit241** [comment]
> @datcit241 this is my config with lazy:
> 
> ```
> 	{
> 		"folke/which-key.nvim",
> 		config = function(_, opts)
> 			dofile(vim.g.base46_cache .. "whichkey")
> 			require("which-key").setup(opts)
> 			local present, wk = pcall(require, "which-key")
> 			if not present then
> 				return
> 			end
> 			wk.register({
> 				-- add group
> 				["<leader>"] = {
> 					f = { name = "+file" },
> 				},
> 			})
> 		end,
> 		setup = function()
> 			require("core.utils").load_mappings("whichkey")
> 		end,
> 	},
> ```

That works, thank you <3. I was confused by 'create a plugin definition in the custom plugins table' but this is just as simple as overriding a plugin.
