### ISSUE TITLE
can't disable Bufferline default key mapping

### ISSUE THREAD

**Issue by AlexwannaCode** [NvChad/NvChad#1249]
**Describe the bug**
I tried disable Bufferline keymappings from  the custom/chadrc:
```lua
M.bufferline = {
   n = {
      ["<S-b>"] = "",
   },
}
-- or 
M.disabled = {
   n = {
      ["<S-b>"] = "",
   },
}

```
and also do a packerSync, but still not working

**Expected behavior**
Should disable default key mappings.

**Desktop (please complete the following information):**
 - Operating System: macOS 12.4
 - Terminal: iTerm2
 - Version of Neovim: v0.7.0

**Comment by siduck** [comment]
did you add these in your mappings table?

**Comment by wKoja** [comment]
In the custom/chadrc file you do something like 
```lua
M.mappings = require "custom.mappings"
```
And then within custom/mappings, it should look like this:
```lua
local M = {}

M.disabled = {
   n = {
      ["<S-b>"] = "",
   },
}

return M
```
That's how my mappings are set up.

**Comment by AlexwannaCode** [comment]
Thanks for helping out! after adding the mappings table, everything works fine
