### ISSUE TITLE
hl_override breaks after syncing with upstream

### ISSUE THREAD

**Issue by tonyage** [NvChad/NvChad#1250]
**Describe the bug**
CursorLine hl_override stopped working after syncing with upstream, CursorColumn still works though funny enough. I didn't make any change to my config after upstreaming. In fact I think all hl_overrides might be broken?

**To Reproduce**
I was 25 commits behind upstream before updating this morning.
```lua
hl_override = {
  CursorLine = { bg = "#313131" },
  CursorColumn = { bg = "#313131" }
}

-- set opts
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
```

**Expected behavior**
When overriding the hl group for cursorline and column I expect to see them on reload

**Screenshots**
![Screenshot_20220621_081746](https://user-images.githubusercontent.com/32802419/174808850-014894d1-d936-463b-ab00-abe8d2715488.png)

**Desktop (please complete the following information):**
 - Arch 
 - Alacritty
 - neovim v0.7.0

**Additional Context**
```lua
local colors = require("custom.themes.onedarkish").base_30

local M = {
  -- Neovim
  Comment = { italic = true },
  Conditional = { bold = true, italic = true },
  CursorLine = { bg = colors.one_bg2 },
  CursorColumn = { bg = colors.one_bg2 },
  Keyword = { bold = true, italic = true },
  MatchParen = { bold = true },
  SpellBad = { undercurl = true },
  SpellCap = { undercurl = true },
  String = { italic = true },
  Todo = { bg = colors.orange },
  Type = { bold = true },

  healthError = { fg = colors.red, },
  healthSuccess = { fg = colors.vibrant_green, },
  healthWarning = { fg = colors.orange },

  -- nvim-cmp
  CmpItemAbbrDeprecated = { strikethrough = true },

  -- NvimTree
  NvimTreeRootFolder = { bold = true },
  NvimTreeSpecialFile = { underline = true },
  NvimTreeSymlink = { fg = colors.cyan }
}

return M
```
this is my full hl_override.lua and I am not seeing keyword overrides or anything like that as well so it appears to not be limited to CusorLine/Column

**Comment by tonyage** [comment]
noticed this [commit](https://github.com/NvChad/NvChad/commit/20911604344929662d3db8f083e9a1a21700f040) added a new hl_add doesn't look like it applies since cursor options should be a default hl group, but I tried it anyways and still same behavior.

**Comment by siduck** [comment]
@tonyage if its not there in the base46 repo then you will have to use hl_add

**Comment by hubdev4** [comment]
Sorry asking here but how do I set this configs in lua?

```
:hi normal guibg=000000
:hi Cursor guifg=cornflowerblue guibg=cornflowerblue
:hi Cursor2 guifg=cornflowerblue guibg=cornflowerblue
:set guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50

```

**Comment by siduck** [comment]
for now just put all of this in vim.cmd ( [[ here ]] ) , change :hi to hi tho. Or u can use nvim_set_hl, read its docs. WIll fix this issue soon

**Comment by tonyage** [comment]
> @tonyage if its not there in the base46 repo then you will have to use hl_add

I see no change doing this and not to mention everything I am overriding appears to be in base46. it's literally just base neovim hl groups and some of nvchad core plugin stuff.

**Comment by tonyage** [comment]
@siduck this [diff](https://github.com/NvChad/base46/commit/cdc1dbba7174e431e1cd8643eaef1af9c187b285#diff-f9f3df0e6fdca783c593e8e02059280639870f14a7f2fb1cfbf4571c6af23137L149) may be the culprit? the value is always 'none' and doesn't actually get overriden?

**Comment by tonyage** [comment]
Yeah so just tested this changing 
``` lua
CursorLine = {
   bg = "theme.base01", -- from "none" 
   sp = "none",
 },```
in base46 plugin works which implies that hl override/add does not appear to be working when defined in user configs

**Comment by FelixKratz** [comment]
Works fine here, pretty sure your config errors out somewhere before applying the overrides for cursor:
![Screen Shot 2022-06-22 at 10 14 38](https://user-images.githubusercontent.com/22680421/174979124-2f92d46d-e99d-4760-98a4-c8d98b6ec15f.png)

**Comment by siduck** [comment]
> > @tonyage if its not there in the base46 repo then you will have to use hl_add
> 
> @siduck I see no change doing this and not to mention everything I am overriding appears to be in base46. it's literally just base neovim hl groups and some of nvchad core plugin stuff.

we dont have cursorcolumn defined so watchout

**Comment by tonyage** [comment]
> Works fine here, pretty sure your config errors out somewhere before applying the overrides for cursor: ![Screen Shot 2022-06-22 at 10 14 38](https://user-images.githubusercontent.com/22680421/174979124-2f92d46d-e99d-4760-98a4-c8d98b6ec15f.png)

logs don't show anything to track down, but I will dig later today

**Comment by siduck** [comment]
@tonyage disable tables one by one like M.plugins M.options etc
