### ISSUE TITLE
I'm new to vim, how can I split my windows?

### ISSUE THREAD

**Issue by nappalm** [NvChad/NvChad#1251]
Is it possible, with the default configuration of nvchad to do this?

![image](https://user-images.githubusercontent.com/35016608/174852679-d4646adb-5c49-4733-a02c-8915538772b0.png)

**Comment by siduck** [comment]
yes why not? Ctrl +x -> open file horizontal and Ctrl + v -> vertically , U can run these mappings whenever in nvimtree to a file or in telescope picker.  or sp/vsp etc will work too

![image](https://user-images.githubusercontent.com/59060246/174853749-723c06fc-8780-47ea-9517-b7fdcde725a4.png)

**Comment by glendell03** [comment]
> sp/vsp

Hello ctrl + v is not working :(
![image](https://user-images.githubusercontent.com/58845052/183385401-09df7810-6127-4893-8e8f-f84f628dde78.png)

**Comment by siduck** [comment]
@glendell03  do inside nvimtree i.e the cursor must be placed on the filename and also check the pinned issue, your config has issues! so fix them

**Comment by glendell03** [comment]
> @glendell03 do inside nvimtree i.e the cursor must be placed on the filename and also check the pinned issue, your config has issues! so fix them

I reinstall it and doesn't give me error anymore but split doesn't work
ctr + x works but ctrl + v does not do anything

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/183411885-77b8e9b9-11d0-4d02-8617-bc5c632b7e03.mp4

@glendell03 works fine here tho :]

**Comment by glendell03** [comment]
> 
> https://user-images.githubusercontent.com/59060246/183411885-77b8e9b9-11d0-4d02-8617-bc5c632b7e03.mp4
> 
> @glendell03 works fine here tho :] 

hmm? i guess it's a terminal issue? I'm using windows terminal wsl2

**Comment by siduck** [comment]
> > vid.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > @glendell03 works fine here tho :]
> 
> hmm? i guess it's a terminal issue? I'm using windows terminal wsl2

looks like it, try another OS in a vm and check

**Comment by glendell03** [comment]
> > > vid.mp4
> > >     
> > >   
> > > 
> > >   
> > > 
> > >   
> > > 
> > > 
> > > @glendell03 works fine here tho :]
> > 
> > hmm? i guess it's a terminal issue? I'm using windows terminal wsl2
> 
> looks like it, try another OS in a vm and check or ask this question in our discord server ( check link in readme badge ) and  ping a windows user 

ok thanks later I will ask 🙂
