### ISSUE TITLE
feature request: add a toggle cmp mapping

### ISSUE THREAD

**Issue by maxyz** [NvChad/NvChad#1257]
Problem:
nvim-cmp while useful it might get in the way, particularly when writing something new, documentation or simple texts. And having menus suggesting things while doing so can get distracting.

**Describe the solution you'd like**
It would be nice to have a default key mapping to disable the completer.

**Describe alternatives you've considered**
I could add a snippet in my custom configs, but I think this is a common enough problem that merits a default key.

**Additional context**
Some ways to obtain these behavior:
https://www.reddit.com/r/neovim/comments/rh0ohq/nvimcmp_temporarily_disable_autocompletion/
https://github.com/hrsh7th/nvim-cmp/issues/261#issuecomment-929790943

**Comment by siduck** [comment]
@maxyz this is more of a user preferability so wont be added, you can btw make an autocmd so it disables itself on specific file types
