### ISSUE TITLE
feature request: avoid cmp to take over "<CR>"

### ISSUE THREAD

**Issue by maxyz** [NvChad/NvChad#1258]
**Is your feature request related to a problem? Please describe.**
The current nvchad configuration preselects the first item in the menu of suggestions shown by cmp. That means that once triggered, it's basically impossible to avoid getting your text replaced.

**Describe the solution you'd like**
I think having to choose an option it's a better default behavior, please consider using:
```
  ["<CR>"] = cmp.mapping.confirm {
    behavior = cmp.ConfirmBehavior.Replace,
    select = false,
  },
```
As the default CR mapping.

**Describe alternatives you've considered**
I also considered increasing the timeout of the menu, but that makes it somewhat annoying to use, the same goes for having it disabled by default.

**Comment by siduck** [comment]
@maxyz can u show an example? i cant reproduce this

**Comment by nrg-Zero** [comment]
> @maxyz can u show an example? i cant reproduce this


```lua
   select = true,
```
https://user-images.githubusercontent.com/66226799/175431577-c6ab0fc1-d8a9-4e07-899f-24a1691b1740.mp4

with:
```lua
   select = false,
```
https://user-images.githubusercontent.com/66226799/175431953-674aaa4c-911b-46a6-99ff-9b73c9b06e33.mp4
