### ISSUE TITLE
Cannot NvChadUpdate

### ISSUE THREAD

**Issue by Dalot** [NvChad/NvChad#1260]
**Describe the bug**
Cannot run NvChadUpdate

**To Reproduce**
`:NvChadUpdate` or `<leader>uu`

**Expected behavior**
Update NvChad

**Screenshots**
![image](https://user-images.githubusercontent.com/8915574/175291060-d01ed9e4-4974-4844-b687-f6d8de02e8a4.png)
![image](https://user-images.githubusercontent.com/8915574/175291099-f4300b21-1310-443d-a5ab-57bf688f6a68.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Alacritty
 - 0.7

**Additional context**

**Comment by siduck** [comment]
did u make any changes in the default config? 

@LeonHeidelbach handle this!

**Comment by Dalot** [comment]
Oh, I never thought that could be an issue. Sorry about that. Just updated `git` and it's working. It's a somewhat recent change.

Thank you :+1:
