### ISSUE TITLE
Autocommands aren't working? Hard to tell how they should be configured

### ISSUE THREAD

**Issue by yungParrot** [NvChad/NvChad#1262]
**Describe the bug**
My autocommands don't seem to work. I have created an `autocmds.lua` file inside `~/.config/nvim/lua/custom` and required it inside `~/.config/nvim/lua/custom/init.lua`. I'm not sure if it's realted to Nvchad or my autocommands aren't written properly :thinking: 

**To Reproduce**
1. Create a `~/.config/nvim/lua/custom/autocmds.lua`:
```lua
local autocmd = vim.api.nvim_create_autocmd
local augroup = vim.api.nvim_create_augroup

augroup("CommitVimwikiOnSave")
autocmd("BufWritePost", {
  group = {"CommitVimwikiOnSave"},
  pattern = {"~/vimwiki/**/*.md"},
  callback = function ()
    print("saving wiki file")
  end
})
```
2. Require this file in `~/.config/nvim/lua/custom/init.lua`
```lua 

require "custom.autocmds"
```
3. Open the Vimwiki with `<leader>ww`
4. Save changes

**Expected behavior**
After step 4 I should see the output `saving wiki file` but nothing happens. Maybe the docs should have more examples on creating `autocmds`? I could find [only this](https://nvchad.github.io/config/Nvim%20lua%20stuff#autocmds--augroups) :confused: 

**Desktop (please complete the following information):**
 - Linux 5.15.45-1-lts
 - alacritty
 - NVIM v0.7.0

**Additional context**
This isn't exactly related to Vimwiki itself. I'm just not sure how to create autocommands in Nvchad :crying_cat_face: :cowboy_hat_face:

**Comment by siduck** [comment]
just add them in custom/init.lua

https://user-images.githubusercontent.com/59060246/175795185-836af23f-298f-43d3-aa9a-b88969186f5a.mp4

it works here well

**Comment by siduck** [comment]
maybe your autocmd is messed up

**Comment by yungParrot** [comment]
> maybe your autocmd is messed up

It seems like it :thinking: when I write my `autocmd` pattern as `~/vimwiki/**/*.md` it doesn't seem to find my vimwiki files and `*.md` seems to be good...  
If I get it to work maybe we could add some more examples [here](https://nvchad.github.io/config/Custom%20config#autocmds)?

**Comment by siduck** [comment]
@yungParrot that totally depends on the user, the user must know how to define autocmds either in lua or vimscript :p
