### ISSUE TITLE
Issue installing a pluggin

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1263]
i am trying to install this plugin https://github.com/chrisbra/csv.vim

i have tried by adding it in lua/custom/plugin/init.lua file like this but its not installed by packer. while other plugins are installed by packer.

secondly i cannot change the brightness in shade plugin by usnig these keybindings

```lua

return {

   ["goolord/alpha-nvim"] = {
            disable = false,
         },


   ["chrisbra/csv.vim"] = {},


   ["andreadev-it/shade.nvim"] = {
      module = "shade",
      config = function()
         require("shade").setup {
            overlay_opacity = 50,
            opacity_step = 1,
            exclude_filetypes = { "NvimTree" },
            keys = {
              brightness_up    = '<C-Up>',
              brightness_down  = '<C-Down>',
              toggle           = '<Leader>s',
            },
         }
      end,
   },
}

```

**Comment by tomasky** [comment]
maybe this:
```lua
    ["chrisbra/csv.vim"] = { ft = "csv", opt = true },

```

**Comment by siduck** [comment]
@tomasky no need to add opt cuz adding ft option already makes it opt i think

**Comment by siduck** [comment]
remove module option from shade option too, i lazyload it on a command. Ig you checked it from my config probably.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/175783243-15a82ee1-901e-491d-b874-82d963dbc586.mp4

csv works for me, again its your config issue!

**Comment by Aneeqasif** [comment]
thank you sooo much thanks thanks thanks :heart:

**Comment by Aneeqasif** [comment]
> maybe this:
> 
> ```lua
>     ["chrisbra/csv.vim"] = { ft = "csv", opt = true },
> ```

can u plz explain a little bit what this piece of code is doing. thanks

**Comment by siduck** [comment]
@Aneeqasif that code  means : packer will install csv.vim plugin as  an opt plugin, meaning that it will download the plugin   in .local/share/nvim/site/pack/packer/opt and the plugin will load only when your file has extension of csv
