### ISSUE TITLE
New tabufline fails whenever trying to save file

### ISSUE THREAD

**Issue by BinhaoQin** [NvChad/NvChad#1265]
**Describe the bug**
The new tabufline generates an error whenever `:w` is used. The following error is generated:
```
.config/nvim/lua/ui/tabline.lua:124: in function <.config/nvim/lua/ui/tabline.lua:123>                                               
E15: Invalid expression: v:lua.require('ui.tabline').run()
```

**To Reproduce**
1. Set to not lazy load tabufline
2. Open arbitrary file
3. Save file with `:w`

**Expected behavior**
Saving file does not interfere tabufline.

**Desktop (please complete the following information):**
 - Garuda Linux
 - Kitty
 - neovim 0.7.0

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/175760406-af0fdf0c-a58f-4374-9007-add7b821c82b.mp4

I cant reproduce this behaviour

**Comment by marcioflaviof** [comment]
I think this have some incompatibility with null-ls, when null-ls is active I get some errors in tabline
![image](https://user-images.githubusercontent.com/44372758/175782480-5fb1273e-9bac-4c4f-af7c-b73773f038cd.png)

**Comment by siduck** [comment]
@marcioflaviof yes im able to reproduce this, will try to fix soon

**Comment by jlaneve** [comment]
@siduck did your commit end up on main? Running into the same issue, updating NvChad doesn't fix it yet.

**Comment by siduck** [comment]
@jlaneve when does it happen to you? it occurs to me when formatting only

**Comment by siduck** [comment]
@jlaneve oops didnt know how that commit got removed from main, can you check now?

**Comment by jlaneve** [comment]
yep, it works! thank you @siduck
