### ISSUE TITLE
problems setting whichwrap in custom

### ISSUE THREAD

**Issue by BlameTroi** [NvChad/NvChad#1266]
Setting or appending to whichwrap throws errors or doesn't take depending on where in custom I try to set it.

**To Reproduce**
In custom/chadrc.lua if I try to set via = or append I get:

Error detected while processing /home/troi/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:0:
stack traceback:
        [C]: in function 'nvim_set_option_value'
        vim/_meta.lua: in function '_set'
        vim/_meta.lua: in function '__newindex'
        /home/troi/.config/nvim/lua/custom/chadrc.lua:8: in function 'user'
        /home/troi/.config/nvim/lua/core/options.lua:103: in main chunk
        [C]: in function 'require'
        /home/troi/.config/nvim/init.lua:2: in main chunk

If I try to set or append in custom/init.lua, no change is visible when I query via set whichwrap?.

I'm trying to add "b" and "w" to whichwrap, but no matter where I try, whichwrap remains:
whichwrap=<>[]hl,b,s

**Desktop (please complete the following information):**
Manjaro/Konsole/Neovim 0.7.0 release

This may be related to #694 but I am not sure. I've been able to change whichwrap in plain neovim and also in lunarvim without problems.

**Comment by siduck** [comment]
how are you overriding whichwrap?

``lua
M.options = {
   user = function()
      vim.opt.whichwrap = "<>[]hl,b,s"
   end,
}
```

Not sure how to test this but i think b works for me here but not s

**Comment by BlameTroi** [comment]
Hey. I think what was happening was that I had an invalid value inside the set string (w instead of s) and that was causing an error. Depending on where the set whichwrap was called, I would sometimes see an error message/stack trace, and sometimes not.

In custom/init.lua the follwing only logs "init.lua before":

```
vim.cmd [[:echom "init.lua before"]]
vim.opt.whichwrap = "<>[]hl,b,w"
vim.cmd [[:echom "init.lua after"]]
```
While in custom/chadrc.lua or in custom/options.lua (called from user function in chadrc.lua), I get the stack trace.

```
vim.cmd [[:echom "option.lua before"]]
vim.opt.whichwrap = "<>[]hl,b,w"
vim.cmd [[:echom "option.lua after"]]
```

```
option.lua before
Error detected while processing /home/troi/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:0:
stack traceback:
        [C]: in function 'nvim_set_option_value'
        vim/_meta.lua: in function '_set'
        vim/_meta.lua: in function '__newindex'
        /home/troi/.config/nvim/lua/custom/options.lua:41: in main chunk
        [C]: in function 'require'
        /home/troi/.config/nvim/lua/custom/chadrc.lua:7: in function 'user'
        /home/troi/.config/nvim/lua/core/options.lua:103: in main chunk
        [C]: in function 'require'
        /home/troi/.config/nvim/init.lua:2: in main chunk
```

So, the blame is mine for passing in a bad value, but the inconsistent handling is confusing. I'd say it's OK to close this, but the quiet failure from custom/init.lua causes some of my customizations to be not run.
Thanks.
