### ISSUE TITLE
new tabufline creates a tab for files that contain a swap file when choosing quit

### ISSUE THREAD

**Issue by appcreatorguy** [NvChad/NvChad#1268]
**Describe the bug**
When opening a file with a swap file, and choosing not to open it through `(Q)uit` in the dialog, a tab still appears for it.
Doing anything to it, like switching to it or closing it with the x button, reopens the swap file dialog, but still keeps the tab after choosing quit. 
```
Error detected while processing function TbKillBuf:
line    1:
E5108: Error executing lua /home/manasmengle/.config/nvim/lua/core/utils.lua:214: Vim(buffer):E325: ATTENTION
stack traceback:
        [C]: in function 'cmd'
        /home/manasmengle/.config/nvim/lua/core/utils.lua:214: in function 'tabuflinePrev'
        /home/manasmengle/.config/nvim/lua/core/utils.lua:24: in function 'close_buffer'
        [string "luaeval()"]:1: in main chunk
```
Using the close button also brings up the swap file dialog again, and gives this error after choosing quit, probbably bcos theres no buffer

**To Reproduce**
1. Edit a file in an instance of nvim to give it a swap file
2. Try to open it in another nvim instance
3. Choose `(Q)uit`
4. It appears in the buffer tab line

**Expected behavior**
When choosing quit at the swap file dialog, no tab should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/14041410/175774853-8ca0d5cb-ca8f-4835-a970-a664fd0b83d6.png)

![image](https://user-images.githubusercontent.com/14041410/175774838-ee2e1b81-de7a-4e87-aef4-039abdd42638.png)

![image](https://user-images.githubusercontent.com/14041410/175775731-cec267ff-8b75-4645-b880-727bd77e7eaf.png)

**Desktop (please complete the following information):**
 - Operating System: Linux
 - Terminal: Alacritty
 - Version of Neovim: v0.8.0 (nightly)

**Comment by appcreatorguy** [comment]
This might be a nvim issue, bcos the unopened buffers still exist in vim.api.nvim_list_bufs(), and so get added to the tabufline during the BufAdd autocmd

**Comment by siduck** [comment]
@appcreatorguy can you check this issue again?  I cant seem to reproduce this, probably got fixed in recent commit

**Comment by siduck** [comment]
i doubt if you are on the latest commit

**Comment by appcreatorguy** [comment]
Most likely not an NvChad related issue

**Comment by Faetu** [comment]
Hi @appcreatorguy 

How do you get rid of that «X» button on the top right?
<img width="1137" alt="image" src="https://github.com/NvChad/NvChad/assets/55803495/789ead5e-26e2-4058-99f6-2f3e36529011">
I want to remove both, the toggle button and the close button, if possible.

best regards

**Comment by Faetu** [comment]
nvm found it:

```
  tabufline = {
    show_numbers = false,
    enabled = true,
    lazyload = true,
    overriden_modules = function(modules)
      modules[4] = ""
    end,
  }
```
Got it by try and error... the wiki is more confusing me than helping.

**Comment by siduck** [comment]
@Faetu it is you who is confusing yourself!! the wiki is simple and clear, i tried your code and it works well here

https://github.com/NvChad/NvChad/assets/59060246/4e6d05c6-1940-4cd5-8286-39da290745e1
