### ISSUE TITLE
Can't load telescope extensions due to lazy loading

### ISSUE THREAD

**Issue by sheoak** [NvChad/NvChad#1269]
**Describe the bug**
I am confused about how to load Telescope extensions, not sure if it's a bug or undocumented.
**_Note**: the link to the forum is broken in the github issues templates._

For example I want to use : https://github.com/rmagatti/session-lens

I tried different ways but nothings works properly. The "most" functional thing I found was using "cmd" field in Packer:

```
   ["rmagatti/session-lens"] = {
       cmd = "SearchSession",
       config = function()
           require('session-lens').setup {
               path_display = {'shorten'},
           }
       end
   },
```

But then I need to run `:Telescope` at least one time first to load it (and session will never appear in Telescope list).
The plugin documentation explains that you can load the extension manually, but I'm pretty sur this cannot work with lazy loading:

```require("telescope").load_extension("session-lens")```

My guess is that Telescope should be loaded on `:SearchSession` call, and extension should be loaded on `:Telescope` call, but I can't find a way to do that. If you help me I can update the documentation and make a Pull Request if you wish.

Thanks!

**Comment by siduck** [comment]
put this in your custom plugins section 
```lua
  ["nvim-telescope/telescope.nvim"] = {
      module = "telescope",
  },
  ``` 
  Do packersync and reopen nvim

**Comment by sheoak** [comment]
So it's not compatible with lazy loading I suppose? It seems to work, thank you!

**Comment by siduck** [comment]
@sheoak the code i sent above is still lazy loading telescope, before telescope was lazy loaded to only its cmd but now it will lazy load whenever "telescope" module will be called which is most likely done by telescope related plugins. The above code in your custom plugins section merges with the default plugin list. 

So basically now telescope will lazyload at cmds + module

**Comment by sheoak** [comment]
Ah, so that's how you use module… I couldn't find the answer, thanks a lot!
