### ISSUE TITLE
Plenary plugin fails to update fia PackerSync

### ISSUE THREAD

**Issue by mcctuxic** [NvChad/NvChad#1271]
**Describe the bug**
While updateing plugins via PackerSync, Planery fails to update since some days.

**To Reproduce**
1.) :PackerSync 
2.) Watch output

**Expected behavior**
While updateing plugins via PackerSync, Planery will not produce a failure.

**Screenshots**
![plenaryfailed](https://user-images.githubusercontent.com/30279786/175815053-0844a74e-e5f7-4dcc-b97c-edde03587899.png)

**Desktop (please complete the following information):**
 - GENTOO LINUX updated on a daily base.
 - wezterm 20220625-194053-9dc19892
 - NVIM v0.8.0-dev+489-g3d4570647

**Additional context**
No additonal information is available.

**Comment by siduck** [comment]
This is normal and happens at times when plugin repos change a branch etc I think, remove plenary.nvim from the main pluginlist and do packersync, then add it back and do packersync
