### ISSUE TITLE
Question: a method to remove term buffers from the tabufline

### ISSUE THREAD

**Issue by atidyshirt** [NvChad/NvChad#1275]
As the title suggests, it would be nice to have a method to hide shell buffers from the tabufline

I am not suggesting to remove it from the jump list entirely (as this may be much harder to implement), but simply having it not shown in the tabufline (as an option, as I understand other users may want this displayed)

Screenshot
<img width="695" alt="Screen Shot 2022-06-27 at 2 08 02 PM" src="https://user-images.githubusercontent.com/20514752/175846905-abdb0aa0-a644-4de8-9a20-f0a824ef9489.png">

preferred display would exclude `zsh` buffer

**Comment by siduck** [comment]
just open that term buffer with nobuflisted option, should work ig

**Comment by siduck** [comment]
https://vi.stackexchange.com/questions/22119/making-terminal-buffer-unlisted

**Comment by atidyshirt** [comment]
Oh sorry, should have seen that!

Cheers for the quick reply :)
