### ISSUE TITLE
Tab-buf line using space in offset area

### ISSUE THREAD

**Issue by lucario387** [NvChad/NvChad#1276]
**Describe the bug**
When you open many buffers in one tabpage, the bufferline will take away the space that should have been offset only
**To Reproduce**
1. Clone NvChad from GitHub
2. Open a lot of files at the same time
3. Check bufferline

**Expected behavior**
It should work like how bufferline or other lines work, only taking space up to a certain amount in the bufline, and not trying to take the offset as well

**Screenshots**
![image](https://user-images.githubusercontent.com/29790821/175847793-610ebf3d-4fd6-4992-9d0d-e8206f0ef405.png)   
As I am opening NvimTree, the bufferline should not be taking away space from the bufferline (as it is offsetted), and it should also not cut the opened file in the middle like in the image above

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 22.04 LTS
 - Terminal: Kitty
 - Version of Neovim: 0.8.0 dev

**Additional context**

**Comment by siduck** [comment]
@lucario387 sorry for the late response, trying to thnk of a fix since ages now, It'll take a while :joy:
