### ISSUE TITLE
Bug: nvim only opens one buffer on startup

### ISSUE THREAD

**Issue by LeonHeidelbach** [NvChad/NvChad#1277]
**Describe the bug**
When launching nvim with any number of files (but more than one) like `nvim test.lua test2.lua`, only the first file will be opened in a buffer. This also applies to session plugins that try to open multiple buffers. Only one buffer is created.

**To Reproduce**
1. Type `nvim test.lua test2.lua`
2. Only `test.lua` will be opened

**Expected behavior**
All files from the parameter list should be opened.

@siduck this is a known issue.

**Comment by tomasky** [comment]
Even if `tabufline_opts.lazyload=false`, it wouldn't work, `bufferline.nvim` version works normally before

**Comment by waywardstrawberrykingdom** [comment]
Files are loaden just not shown. Using :bn will show them
