### ISSUE TITLE
Unable to override cmp config

### ISSUE THREAD

**Issue by nanomoeamezao** [NvChad/NvChad#1278]
**Describe the bug**
Trying to install github copilot plugin, which needs to be added as a cmp source.  Unable to override nvim-cmp settings from chadrc. Similar to #1236 

**To Reproduce**
1. Install and setup plugins in plugins/init.lua:
```
["zbirenbaum/copilot.lua"] = {
      config = function()
         vim.defer_fn(function()
            require("copilot").setup {
               cmp = {
                  enabled = true,
                  method = "getCompletionsCycling",
               },
            }
         end, 100)
      end,
   },
   ["zbirenbaum/copilot-cmp"] = {},
```
2. Put this into an override file
```
M.cmp = function()
   -- vim.opt.completeopt = "menu,menuone,noselect,noinsert"
   return {
      -- preselect = cmp.PreselectMode.None,
      sources = {
         { name = "copilot" },
         { name = "nvim_lsp" },
         { name = "luasnip" },
         { name = "buffer" },
         { name = "nvim_lua" },
         { name = "path" },
      },
   }
end
```
3. Override in chadrc
```
local plugin_conf = require "custom.plugins.configs"

M.plugins = {
   user = userPlugins,
   override = {
      ["hrsh7th/nvim-cmp"] = plugin_conf.cmp,
   },
}
```
After restart - copilot starts, but cmp source remains unused. 

**Expected behavior**
Copilot source is registered as ready by CmpStatus.

**Desktop (please complete the following information):**
 - Manjaro
 - Kitty
 - V 0.7.0

**Additional context**
Can be reproduced with any cmp config field (like preselect = cmp.PreselectMode.None and sorting). 
Everything works as expected when i edit cmp.lua of nvchad. Removing lazy-loading of cmp and copilot modules did not help to resolve the issue.

**Comment by songww** [comment]
It is caused by this line: https://github.com/NvChad/NvChad/blob/33550e9587e607f9ad56498660e75321a80e7be6/lua/core/utils.lua#L152

**Comment by songww** [comment]
This is not c-like switch. elif will not be executed when first if is reached.

**Comment by tomasky** [comment]
try  this , if this is ok ,then the function check has a bug

```lua
M.cmp =  {
      -- preselect = cmp.PreselectMode.None,
      sources = {
         { name = "copilot" },
         { name = "nvim_lsp" },
         { name = "luasnip" },
         { name = "buffer" },
         { name = "nvim_lua" },
         { name = "path" },
      },
   }
 
```

**Comment by nanomoeamezao** [comment]
Yep, this totally works. Not completely suitable, since most of cmp configs need the module imported and cmp itself is lazy here, but for now will do. Thank you.

**Comment by nanomoeamezao** [comment]
New commit works as intended. Thank you.
