### ISSUE TITLE
Wrong page in Read.me

### ISSUE THREAD

**Issue by marcioflaviof** [NvChad/NvChad#1283]
**Describe the bug**
When you click in Install from github readme page, it send us to a page not found

**To Reproduce**
1. Go to 'nvchad github'
2. Click on 'Install link'
3. See error

**Expected behavior**
Go to install page

**Screenshots**
![image](https://user-images.githubusercontent.com/44372758/175991498-c7086181-2cfb-4c56-ac94-a217553c35e7.png)

**Comment by siduck** [comment]
@marcioflaviof  https://nvchad.github.io/quickstart/install#pre-requisites

**Comment by siduck** [comment]
willl put it in next commit soon
