### ISSUE TITLE
how to disable unused default key binds ?

### ISSUE THREAD

**Issue by 0x736d** [NvChad/NvChad#1284]
**Describe the bug**
Can't figure out how to remove/disable unused default keymaps from which-key. When setting up different keybinds for some functionality(i.e lsp, telescope) which is also defined in default mappings, there is no way to remove/disable the default keybinds other than override them with different functionality.

**Screenshots**
![2022-06-27_20-30](https://user-images.githubusercontent.com/105538153/176005166-02bbd31d-1ae9-4a10-9ed4-88beb8a16e6a.png)

>How to get rid of these keymaps(not override them with different commands)? ...
![2022-06-27_22-00](https://user-images.githubusercontent.com/105538153/176005451-172828b9-ab00-417e-9ffe-313d01ce5d04.png)

**Additional Context**
using custom config for `whick-key` doesn't work(afik).

**Desktop (please complete the following information):**
 - PopOS
 - alacritty
 - neovim nightly (v0.8.0-dev+494-ge2f9d0332)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/176059229-81d66098-a6c5-4377-bbfd-2c955533436c.png)

add them in the disabled table

**Comment by biggerevil** [comment]
@siduck so I want to disable <TAB>, which can be seen on the 1 screen.
![изображение](https://user-images.githubusercontent.com/22119677/177056540-a7e108b7-98ec-446c-bc4e-94336674a920.png)

I did add <TAB> to M.disabled, but Tbufnext still gets triggered when I press <TAB> or <C-i>.
![изображение](https://user-images.githubusercontent.com/22119677/177056585-b12bc266-cd13-4c56-985b-fc9348978933.png)

How do I disable <TAB>?

**Comment by siduck** [comment]
M.disabled tabled should be in your mappings.lua file

**Comment by LinuxIsCool** [comment]
This is not working for me.

In mappings.lua:

```lua
---@type MappingsTable
local M = {}

M.disabled = {
  n = {
    ["<C-f>"] = "",
},
}

return M
```

Control f is still moving cursor down in normal mode.

**Comment by siduck** [comment]
@LinuxIsCool C-f is not even a nvchad mapping so that wont work. please check what mappings are available in core/mappings.lua. only those can be disabled with M.disabled table

**Comment by youguanxinqing** [comment]
My mappings.lua is as follow:
```lua
M.disabled = {
  n = {
    ["<leader>n"] = "",
  },
}
```

~~But it does not work for me~~.

Sorry, my mistake. It works for me!

**Comment by siduck** [comment]
@youguanxinqing now you should use vim.keymap.del!
