### ISSUE TITLE
Request for a basic demo for new user

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1286]
hy your config is too cool and i really really love it but as not so experienced with vim user i manytimes find it very very difficult to do some basic task and freak out to internet and some chill dude calm me down with a solution that looks very simple but for a beginner feels difficult. i recommended nvchad to some friends at uni we are using to vimscript (a litle bit) for config and they also find it difficult to do some basic task in lua.

As nvchad is now used by many users it will be really nice if one of cool maintainer guyz make a noob friendly video to demonstrate just simple things that a new user may need such as:

1- installing pluggins (common variants of this process, a user should know how to handle)
2- lazy loading and setting custom configs of plugins i-e options,keybindings etc
3- Rebinding default vim keys and setting custom mappings etc..
4- last but not least setting up LSP server for some common language like python etc,
5- any other thing u think will be nice to add in demo i-e packer related stuff or anything else ...

these things may seems trivial to experienced users but many people like me find it really exhausting to do. and i know best thing to do is READ THE DOCS but considering that things like packer have bazillions of different in docs it get even more confusing.

if someone from you guyz make such a tutorial it would be not only helpful for newbie nvchad users but overall it would be helpful for new nvim users and it will be a great help.  
Thanks in advance  :)

**Comment by siduck** [comment]
just read the docs from the start

**Comment by siduck** [comment]
i can make videos regarding showcasing workflow in nvchad but not basic tutorials etc. Docs are not confusing, if they are then point out which part of them is confusing.
