### ISSUE TITLE
Unable to override highlight-group (attributes) 

### ISSUE THREAD

**Issue by nanomoeamezao** [NvChad/NvChad#1291]
**Describe the bug**
I am trying to set LspReferenceText and other groups to use an underline instead of a white background. It is easy to do with vim.api.nvim_set_hl. Currently tried setting them in custom/init.lua and chadrc.options, but they are being overwritten by base46 theme initialization. If i source the init.lua file after - it produces expected behavior. 
Not sure if it would be useful as a feature to be able to override any hl group argument via chadrc.ui.hl_override, but i would like to know, where would be an appropriate place to override them manually after the theme was loaded, using  nvim api.

**To Reproduce**
1. Put this into init.vim
```
      vim.api.nvim_set_hl(0, "LspReferenceWrite", { underline = true, bg = #6CC644 })
      vim.api.nvim_set_hl(0, "LspReferenceRead", { underline = true, bg = #6CC644 })
      vim.api.nvim_set_hl(0, "LspReferenceText", { underline = true, bg = #6CC644 })

```
2. Restart nvim
3. Observe no changes, check :verbose highlight LspReferenceText returning theme-appropriate bg and fg
4. Source init.vim
5. See desired result in  :verbose highlight LspReferenceText

**Expected behavior**
LspReference hl groups are overridden and have underline.

**Desktop (please complete the following information):**
 - Manjaro
 - Kitty
 - V0.7.0

**Comment by nanomoeamezao** [comment]
That does not seem to do anything different.

```
M.ui = {
   theme = "nightfox",
   hl_add = {
      LspReferenceWrite = {
         underline = true,
         bg = "green",
      },
      LspReferenceRead = {
         underline = true,
         bg = "green",
      },
      LspReferenceText = {
         underline = true,
         bg = "green",
      },
   },
}
```

![image](https://user-images.githubusercontent.com/1780639/176212276-03fab8ba-2f38-48d4-a209-0475e02dc99a.png)

Fully updated and PackerSynch'd.

**Comment by siduck** [comment]
works fine for me here :/

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/176229953-adf6b8c3-6abf-4f43-924c-d106ee146d65.mp4

**Comment by nanomoeamezao** [comment]
This is weird. But since this is not a bug and works as intended issue can be closed. I will be digging around in my config and reinstalling nvchad i guess.

**Comment by cvincent00** [comment]
I have some problem. Do you find any solutions?
It is true that the highlight group setup works. But it will be recovered after LSP loaded.

before LSP load:
```
:hi LspReferenceRead
LspReferenceRead xxx guibg=#ff75a0
:hi LspReferenceWrite
LspReferenceWrite xxx guibg=#519aba
```

after LSP loaded:
```
:hi LspReferenceRead
LspReferenceRead xxx guifg=#efeff0 guibg=#54555b
:hi LspReferenceWrite
LspReferenceWrite xxx guifg=#efeff0 guibg=#54555b
```

It seems a incorrect order of initialization. Since it works after I put nvim_set_hl in lsp on_attach function.

**Comment by siduck** [comment]
@cvincent00  add in hl_override as i added that in our lsp integration of base46
