### ISSUE TITLE
Packer "keys" option does not lazy load plugin as expected

### ISSUE THREAD

**Issue by sheoak** [NvChad/NvChad#1292]
**Describe the bug**
When using the options `keys` in plugin configuration, plugin do not lazy load as expected when pressing the key.

**To Reproduce**
1. Add a new plugin with the key attribute in your `custom/plugins/init.lua` file:
```
   ["ggandor/leap.nvim"] = {
     keys = { "k" },
   },
```
2. Exit and run `:PackerSync`
3. Open a file and type `k`
4. Run `:PackerStatus` : leap has not been loaded as expected
5. Inspect `plugin/packer_compiled.lua`, compilation is similar to `Comment`, which also uses `keys` feature : 
```
  ["leap.nvim"] = {
    keys = { { "", "k" } },
    loaded = false,
    needs_bufread = false,
    only_cond = false,
    ...
  },
  ...
  ["Comment.nvim"] = {
    ...
    keys = { { "", "gc" }, { "", "gb" } },
    loaded = false,
    needs_bufread = false,
    only_cond = false,
    ...
  },
```

But does not appear in lazy loading : 
```
local module_lazy_loads = {
  ["^Comment"] = "Comment.nvim",
  -- leap is missing here
}
```

It appears in lazy-load keymaps: 
```
-- Keymap lazy-loads
time([[Defining lazy-load keymaps]], true)
vim.cmd [[noremap <silent> k <cmd>lua require("packer.load")({'leap.nvim'}, { keys = "k", prefix = "" }, _G.packer_plugins)<cr>]]
vim.cmd [[noremap <silent> gc <cmd>lua require("packer.load")({'Comment.nvim'}, { keys = "gc", prefix = "" }, _G.packer_plugins)<cr>]]
vim.cmd [[noremap <silent> gb <cmd>lua require("packer.load")({'Comment.nvim'}, { keys = "gb", prefix = "" }, _G.packer_plugins)<cr>]]
time([[Defining lazy-load keymaps]], false)
```

**Expected behavior**
Typing k should load leap plugin.

**Desktop (please complete the following information):**
 - Arch linux
 - Kitty
 - NVIM v0.7.0

**Comment by sheoak** [comment]
While writing the bug I realised that I had k remapped (I used a different keyboard layout) and that seems to be the reason (it works with other keys). I had missed this because the other key I tried is a special char and there might be another issue with that (currently debugging). I'm not sure if it's a bug or if it's incomatible with Packer lazy load system.

**Comment by sheoak** [comment]
After investigation, if I remap the key in my custom mappings.lua (loaded in chadrc.lua with M.mappings) then it doesn't work. Is it expected behaviour? Should the map be created on `config`?

**Comment by siduck** [comment]
if i recall correctly K is already used somewhere else, in lspconfig mapping I think

**Comment by sheoak** [comment]
This is "k", lowercase, not "K". But I have the same problem with any mapping that I add in custom/mappings.lua. I tried with "i" for example.

**Comment by sheoak** [comment]
Loading the mappings after leap is loaded works. But then I don't get which-key listing:

```
   ["ggandor/leap.nvim"] = {
    keys = { "k", "K", "gk", "è", "È" },
    config = function()
      vim.api.nvim_set_keymap("n", "k", "<Plug>(leap-forward)", { noremap = true })
    end
```

**Comment by sheoak** [comment]
I'm not sure, I will have a try. But it might be nice to update the documention? It's a bit tricky to figure out. If there is a repo for the documentation I can make a pull request.

**Comment by sheoak** [comment]
@siduck is this possible to add mappings dynamically to your mapping system, so that is appears in which-keys?

**Comment by siduck** [comment]
@sheoak its still wip, i will finish the site in a day or two https://nvchad.github.io/

**Comment by siduck** [comment]
> Loading the mappings after leap is loaded works. But then I don't get which-key listing:
> 
> ```
>    ["ggandor/leap.nvim"] = {
>     keys = { "k", "K", "gk", "è", "È" },
>     config = function()
>       vim.api.nvim_set_keymap("n", "k", "<Plug>(leap-forward)", { noremap = true })
>     end
> ```

i think cuz u didnt add it in your mappings, check the mappings docs or my dotfiles/nvchad repo's custom mapping section as a reference to add your mappings ( as well as show em in whichkey )

**Comment by sheoak** [comment]
@siduck do you mean adding them in `custom/mappings.lua`, like so?
```
local M = {}
M.leap = {
    n = {
        ["k"] = {"<Plug>(leap-forward)", "Leap Forward", opts = { noremap = false }},
    }
}
return M
```

This is how I was doing, this is the method that breaks lazy-loading using "keys".
The methods of loading them at config() call works, but then it's not in which-keys of course.
I don't know how to add them in which key from the config() method.

**Comment by sheoak** [comment]
Final solution for anyone looking to solve this:
```
   ["ggandor/leap.nvim"] = {
    keys = { "k", "K" },
    config = function()
      local utils = require 'core.utils'
      local leap_maps = require 'custom.mapping_lazy'.leap
      -- create mapping for which-key, dynamically, on lazy loading
      utils.load_mappings({ leap_maps })
    end
   },
```
