### ISSUE TITLE
Getting desperate with <BS> behavior

### ISSUE THREAD

**Issue by MimiValsi** [NvChad/NvChad#1294]
**Describe the bug**
<BS> behavior on Insert mode.
When I do <leader>tk and search for <BS> it says: v:lua.MPairs.autopairs_bs(1)

**Expected behavior**
So I get it right, <BS> is for Backspace key and it supposes to erase a character at once in Insert mode but here it just goes left. on Normal mode it goes to NerdTree if opened.
I'm terrible sorry to issue this here. It may be futile to everyone but can't get it right.

**Desktop (please complete the following information):**
 - Operating System: Arch
 - Terminal: I3wm + xterm
 - Version of Neovim: 0.7.0

**Comment by siduck** [comment]
whats tk

**Comment by MimiValsi** [comment]
oh darn sorry, forgot to had <leader>tk, it opens the key maps window

**Comment by siduck** [comment]
i dont get the issue

**Comment by MimiValsi** [comment]
The issue I'm having is that "Backspace" isn't behaving as it should. On Insert mode, instead of erasing word by word, it just make the cursor go left. To erase I need to hold "Shift" + "Backspace".

**Comment by siduck** [comment]
> The issue I'm having is that "Backspace" isn't behaving as it should. On Insert mode, instead of erasing word by word, it just make the cursor go left. To erase I need to hold "Shift" + "Backspace".

so this happens when leader tk is done  and u type in the prompt?

**Comment by MimiValsi** [comment]
It happens everywhere actually, Insert mode, within Telescope, etc

**Comment by MimiValsi** [comment]
https://user-images.githubusercontent.com/58744139/177409745-2fb8f2e5-4d57-4ba7-b4f5-62fd45bbb3db.MOV

Hope this help, what I'm trying to say :|

**Comment by siduck** [comment]
@MimiValsi i cant reproduce this issue, this looks like an issue from your end. Am I right? @LeonHeidelbach

**Comment by MimiValsi** [comment]
Oh that's interesting to know, I will keep searching then. At least I know that it only happens in Nvim with NvChad. :)

**Comment by siduck** [comment]
> Oh that's interesting to know, I will keep searching then. At least I know that it only happens in Nvim with NvChad. :)

very weird :/ , if backspace didnt work in nvchad then many wouldve reported this already. you're the first one

**Comment by MimiValsi** [comment]
It's ok. One last question if you don't mind. I may have find a clue but to confirm I'll need to disable or erase a package. Is there an option to it or must go manually?

**Comment by siduck** [comment]
> It's ok. One last question if you don't mind. I may have find a clue but to confirm I'll need to disable or erase a package. Is there an option to it or must go manually?

you can remove a package by the entering its name in the remove field of plugins field in chadrc, check the docs!

**Comment by LeonHeidelbach** [comment]
> @MimiValsi i cant reproduce this issue, this looks like an issue from your end. Am I right? @LeonHeidelbach

@siduck @MimiValsi seems like it. I've never had this issue and I used NvChad under Linux, Mac and Windows with all kinds of terminal emulators. The shown behavior in your video is actually correct for the visual mode, but it should not happen in insert mode.

**Comment by MimiValsi** [comment]
I may have found the issu, using :checkhealth, got this message:
## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION='XTerm(372)'

I have made some changes on my keyboard but didn't touch backspace key, odd.

**Comment by MimiValsi** [comment]
Ok so I'll pass this issue as completed. Discovered what causes my issue and it's Xterm! Installed Xfce4 to test and don't any problem. Came back to I3wm, don't know why but Xfce4 term overwrote Xterm and the problems gone. :) Hope this can help someone

**Comment by siduck** [comment]
@MimiValsi you can check out my dwm fork https://github.com/siduck/chadwm

**Comment by MimiValsi** [comment]
Sure thing. Already started but most tell I'm getting a hard time installing it ^^ Not enough EXP ^^ looks beautiful though

**Comment by ueaner** [comment]
Hi @siduck, Thank you for your great work.

Execute `:help keycodes` in vim, you can see:
```
notation         meaning               equivalent    decimal   value(s)
---------------------------------------------------------------------------------------------
<BS>             backspace             CTRL-H         8           *backspace*
```

In the `lua/core/mappings.lua:16` file `<C-h>` is mapped to `<Left>`, which changes the behavior of `<BS>` instead of the intuitively supposed `backspace` behavior . This configuration behavior is not easily discovered by the user.

https://github.com/NvChad/NvChad/blob/54b364932450706b7355818f01a929fd1a77861e/lua/core/mappings.lua#L9-L20

Maybe `navigate within insert mode` should be removed from `lua/core/mappings.lua` (the key is the mapping for `<C-h>`), defined in `custom` by users who need it. What do you think?

**Comment by siduck** [comment]
@ueaner oh sorry i didnt know that it was overriding default behavior! i made the change in the dev branch!

**Comment by lucario387** [comment]
> Maybe `navigate within insert mode` should be removed from `lua/core/mappings.lua` (the key is the mapping for `<C-h>`), defined in `custom` by users who need it. What do you think?

Just chiming in to say that `<C-h>` and `<BS>` disambiguation support has been inside neovim since neovim/neovim#5758, along side `<C-i>` and `<Tab>`, ...
Your terminal may not have supports for disambiguation, not neovim itself.

**Comment by ueaner** [comment]
@lucario387 Thanks for the link you shared, I'm using tmux with alacritty, Disambiguation support may be a long wait.

@siduck The `<Tab>` mapping also affects the neovim's `jumplist` behavior when using `<C-I>`.
https://github.com/NvChad/NvChad/blob/54b364932450706b7355818f01a929fd1a77861e/lua/core/mappings.lua#L85-L90

Can I disable the `<TAB>` mapping in tabufline? I usually use `<C-N>/<C-P>` to switch buffers.

**Comment by lucario387** [comment]
> Can I disable the <TAB> mapping in tabufline? I usually use <C-N>/<C-P> to switch buffers.
@ueaner you do exactly the same way as how you override backspace/<c-h>

**Comment by ueaner** [comment]
> > Can I disable the  mapping in tabufline? I usually use / to switch buffers.
> 
> @ueaner you do exactly the same way as how you override `backspace/<C-h>`

@lucario387 `M.disabled` does not apply to tabufline.

**Comment by siduck** [comment]
> > > Can I disable the  mapping in tabufline? I usually use / to switch buffers.
> > 
> > 
> > @ueaner you do exactly the same way as how you override `backspace/<C-h>`
> 
> @lucario387 `M.disabled` does not apply to tabufline.

weird, can you show what you did?

**Comment by ueaner** [comment]
@siduck 

`lua/custom/mappings.lua`:
```lua
-- lua/custom/mappings 
local M = {}

-- add this table only when you want to disable default keys
M.disabled = {
  i = {
    -- go to  beginning and end
    ["<C-b>"] = "",
    ["<C-e>"] = "",

    -- navigate within insert mode
    ["<C-h>"] = "",
    ["<C-l>"] = "",
    ["<C-j>"] = "",
    ["<C-k>"] = "",

    -- disable nvimtree `<C-n>` keymap, not work
    ["<C-n>"] = "",
    -- disable tabufline `<TAB>` keymap, not work
    ["<TAB>"] = "",
  },
}

M.nvimtree = {

  n = {
    -- disable nvimtree `<C-n>` keymap
    -- packer.nvim: Error running setup for nvim-tree.lua: vim/keymap.lua:0: rhs: expected string|function, got nil
    -- ["<C-n>"] = {},
    -- packer.nvim: Error running setup for nvim-tree.lua: /home/ueaner/.config/nvim/lua/core/utils.lua:70: attempt to index local 'mapping_ info' (a string value)
    -- ["<C-n>"] = "",
    -- toggle
    ["<leader>e"] = { "<cmd> NvimTreeToggle <CR>", "toggle nvimtree" },
  },
}

M.tabufline = {
  n = {
    -- disable tabufline `<TAB>` keymap, Got the same error as `<C-n>`
    -- ["<TAB>"] = {},
  }
}

return M

```

**Comment by lucario387** [comment]
@ueaner You are disabling <tab> for insert mode (`i`), not normal mode `n`

**Comment by ueaner** [comment]
@lucario387 Oh sorry, my bad. It works for me. Thanks.
And gets a message:
`[NvimTree] unknown option: mapping | see :help nvim-tree-setup for available configuration options`

**Comment by orhnk** [comment]
> **Note** For **Alacritty** terminal emulator users:
- Configure `key_bindings:` section from your `~/.config/alacritty/alacritty.yml` as following:

```yml
key_bindings: # DISCLAIMER! This heading is commented by default. Uncomment it!
  # Make <C-BS> work:
  - { key: Back, mods: Control, chars: "\x17" }
```
- From now on Alacritty `<C-BS>` is enabled and it will work everywhere!

-  [Reddit post](https://www.reddit.com/r/vim/comments/s1jvmb/comment/igkfckb/?utm_source=share&utm_medium=web2x&context=3)
