### ISSUE TITLE
New tabline does not update with multiple buffer workspaces (tabs)

### ISSUE THREAD

**Issue by DanielCardonaRojas** [NvChad/NvChad#1297]
Now that NvChad has tab scoped buffers (feature that I love) a few issues arise.

1. Alternate file does not update tabline (tab number and buffer file name) correctly if the alternate file  is  a different tab
2. LSP go to definition should should update tab number and buffer file name in tabbar.

**Comment by siduck** [comment]
> Alternate file does not update tabline (tab number and buffer file name) correctly if the alternate file is a different tab

This is a feature, you are supposed to open a file in one tab only and a tab will show buffers attached to it only, not from other tabs

**Comment by siduck** [comment]
this should be fixed by now i think so closing this
