### ISSUE TITLE
Bufferline is not shown on startup which causes a lot of issues with the tab indicator

### ISSUE THREAD

**Issue by Zaedus** [NvChad/NvChad#1298]
**Describe the bug**

**To Reproduce**
1. Open up any file or directory in nvim
2. Type `:tabnew`
3. Use eyes

**Expected behavior**
The bufferline should be shown by default or should get shown when a new tab is created.

**Screenshots**
![Kooha-07-01-2022-01-01-33](https://user-images.githubusercontent.com/42098470/176833747-16b1f5db-bcb6-485a-9868-825d7a3f1b15.gif)

**Desktop (please complete the following information):**
 - Operating System: Arch Linux x86
 - Terminal: kitty
 - Version of Neovim: v0.7.2

**Additional context**
None

**Comment by siduck** [comment]
just keep lazyload=false bruh
