### ISSUE TITLE
Tab is indenting with spaces in a project that uses tabs

### ISSUE THREAD

**Issue by JediMaster25** [NvChad/NvChad#1299]
Why isn't the default configuration detecting the used indentation? If a project already uses spaces it should use the same number of spaces, and if it uses tabs it should use tabs.

**Comment by siduck** [comment]
ive read this somewhere that lsp servers modify the indentation, open the file without lsp server and see if there are changes

**Comment by JediMaster25** [comment]
How do I disable the lsp server?

**Comment by siduck** [comment]
> How do I disable the lsp server?

just remove it from your lsp setup list for now

**Comment by JediMaster25** [comment]
I'm not using any custom configuration, so I don't think I have an lsp setup list.

**Comment by zbirenbaum** [comment]
The only thing which would cause this via the LSP is formatting, but that should only be run on write. Look into 'indentexpr' and read the help guide.

**Comment by siduck** [comment]
@JediMaster25 i here have 3 projects opened and the indentation seems right imo https://nvchad.github.io/themes/themelist

**Comment by JediMaster25** [comment]
I have cloned [spacedrive](https://github.com/spacedriveapp/spacedrive) and opened `core/src/file/cas/identifier.rs`. After pressing `o` on line 55 and writing `asdf` I then check that new line 56 and it's comprised of spaces instead of tabs, even though the rest of the file is comprised of tabs.

**Comment by JediMaster25** [comment]
Why would I want to replace all tabs with spaces? I would have to do that in many files and I then if I submit a pull request with all the indentation changed it wouldn't be accepted because they use tabs instead of spaces. Then I would have to undo all the changes and use tabs myself. So I would end up in the same place I'm now having wasted a lot of time.

I want to use the same indentation as the file I'm editing.

**Comment by zbirenbaum** [comment]
> > do gg=G and you will see all the tabs be replaced with spaces.
> 
> 
> 
> Why would I want to replace all tabs with spaces? I would have to do that in many files and if I submit a pull request with all the indentation changed it wouldn't be accepted because they use tabs instead of spaces. Then I would have to undo all the changes and use tabs myself. So I would end up in the same place I'm now having wasted a lot of time.

This is the purpose of formatters such as stylua. Edit how you are comfortable, then run a command prior to pushing. 

You will likely need a plugin or to write a fairly complex script to achieve what you are describing. A quick search turned this up, and I'm not sure if it does exactly what you need, but should set you on the right path: https://github.com/NMAC427/guess-indent.nvim

@siduck this is now waaay outside the scope of NvChad so it can probably be closed but up to you.

**Comment by siduck** [comment]
@JediMaster25  https://github.com/Abstract-IDE/penvim
