### ISSUE TITLE
Error while invoking nvim 

### ISSUE THREAD

**Issue by prankurverma** [NvChad/NvChad#1301]
**Describe the bug**
Getting errors from utils.lua file as the function "nvim_buf_get_option" is expecting a number argument but instead "*" is passed. 

**To Reproduce**
1. Install NeoVIM as mentioned in prerequisites on NvChad website
2. git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
3. Invoke neovim with: nvim

**Expected behavior**
Nvim must be invoked without lua compilation errors.

**Screenshots
![Screenshot from 2022-07-02 15-25-26](https://user-images.githubusercontent.com/15872685/176995682-2344a0aa-6c5a-4522-a272-36790004ba7f.png)
**

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Terminal
 - Version of Neovim: 0.7.2

**Comment by siduck** [comment]
This is impossible, we dont have hide_statusline functio at all . Please upddate nvchad

**Comment by siduck** [comment]
live grep hide_statusline in the config and you wont find this error

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/177028977-a38423f1-8916-44e8-9a2f-a620f2ff75d8.mp4
