### ISSUE TITLE
Statusline mode not changing after rebinding `:`

### ISSUE THREAD

**Issue by fpiem** [NvChad/NvChad#1304]
Hello,

In my custom configuration I have rebinded `;` to `:`, in order to avoid having to press shift when entering command mode. I have used the following snipped to perform this rebinding:

```lua
-- custom.mappings
M.core = {
  n = {
    [";"] = { ":", "Enter command mode" }
  }
}
```

The mapping seems to work, but when I enter command mode using the rebinded `;` the NVChad statusline still displays "Normal" as the mode:

![Screenshot from 2022-07-03 00-04-39](https://user-images.githubusercontent.com/77389987/177017359-57cb74f4-af8a-4fd0-8839-d26e5f20ea16.png)

The mode is updated correctly if I enter command mode by pressing `:`.

![Screenshot from 2022-07-03 00-05-58](https://user-images.githubusercontent.com/77389987/177017399-f5bb5080-dcf9-4a7b-9695-cbbabc450895.png)

Is this a bug in the NVChad statusline, or have I made a mistake in rebinding `:`? Please correct me if this is the case, I'm just starting out with NVChad and I'm still figuring things out.

Thanks in advance :)

**Comment by siduck** [comment]
```lua
nmap ; :
```

This works, so you are mapping it the wrong way

**Comment by fpiem** [comment]
I wrote that mapping according to the NVChad [docs](https://nvchad.github.io/config/Mappings#mapping-format). Should rebinds of key Neovim functionality not be done in this way?

**Comment by siduck** [comment]
@fpiem i think this is a whichkey issue

```lua
lua require("which-key").register { [";"] = { ":", "kek" } }
```

In cmd mode to reproduce this issue, vim.keymap.set() works

**Comment by siduck** [comment]
@LeonHeidelbach :runner:

**Comment by LeonHeidelbach** [comment]
@siduck @fpiem I do not have this issue with the exact mapping code you provided. It correctly switches to command mode after pressing semicolon.

![Screenshot_20220704_161917](https://user-images.githubusercontent.com/55194243/177173177-5217ff16-8c03-4bb9-a64d-fd86960bbe25.png)
