### ISSUE TITLE
Cursor hardly visible in light themes

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1305]
Switch to one_light theme -- try to find your cursor.

**Comment by siduck** [comment]
show image bruh

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177028437-b461a333-5417-4240-97d4-45d7c06f2a4b.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177028443-1f01700d-0682-4e30-9540-08fee8a25f9c.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177028451-1e7b4020-b35e-45ae-bdf9-0a6d50bc6add.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177028467-57d6f715-e453-4ea9-a5f4-39daa0ce624b.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177028473-88155add-38d4-439e-b37f-336dd3d66f52.png)

**Comment by siduck** [comment]
cursor is visible in all light themes, hence closing this

**Comment by danjenson** [comment]
![image](https://user-images.githubusercontent.com/4793438/177383111-14057ef3-f5da-49a0-bf82-0b698979e4fa.png)

**Comment by danjenson** [comment]
![image](https://user-images.githubusercontent.com/4793438/177383199-0c87bb53-f19d-480c-8fdc-a1bf89380c2c.png)

**Comment by danjenson** [comment]
![image](https://user-images.githubusercontent.com/4793438/177383290-9801cce8-3eb4-49a4-9d62-bde4a6f9daf7.png)

**Comment by danjenson** [comment]
my cursor is white regardless of the theme

**Comment by danjenson** [comment]
...it looks like it is getting the color palette somehow from the environment

**Comment by siduck** [comment]
> ...it looks like it is getting the color palette somehow from the environment

which terminal is this? looks like your system issue

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177447737-6fe70034-95b3-4606-af3d-b0cd115a56d0.png)

alacriftty with no config at all

**Comment by danjenson** [comment]
![image](https://user-images.githubusercontent.com/4793438/177447777-eebbc87f-bd48-40bf-83e0-d7e6f8779f07.png)
I just pywal to set my system theme for all modules, i.e. terminal, dunst, rofi, zathura, pywalfox, etc...

**Comment by danjenson** [comment]
if your themes are hardcoded but elements come from the environment, you will always get conflicts like this.

**Comment by siduck** [comment]
remove the link in your alacritty config that sets cursor color

**Comment by danjenson** [comment]
I could do that every time I update my theme (I have hotkeys to do this), but it seems like each theme should have a cursor color that works well with that theme, no?

**Comment by siduck** [comment]
im not sure what colors the cursor in nvim, tried TermCursor highlight group and doesnt work

**Comment by siduck** [comment]
try a vanilla nvim config and add only #fff as bg in it , if it doesnt work there too then i cant help

**Comment by siduck** [comment]
> This worked for me: https://stackoverflow.com/a/6230504/2909076 wiki: https://vim.fandom.com/wiki/Configuring_the_cursor

the whole thing? can you  just try if this works

highlight Cursor guifg=white guibg=black

**Comment by danjenson** [comment]
So, I think that just defines a highlight group; it becomes active when you assign it to guicursor, so the following two lines work:
```
highlight Cursor guifg=white guibg=black
set guicursor=n-v-c:block-Cursor
```

**Comment by siduck** [comment]
so whats this use for?

![image](https://user-images.githubusercontent.com/59060246/177660617-9c8b4cfd-3490-45a0-b347-f6b14ae5cd5a.png)

**Comment by tomasky** [comment]
but now my `   theme = "gruvbox"`  cursor backgroud is invisible when word`s color is white

**Comment by siduck** [comment]
@tomasky share pic and did u do packersync ( i added 2 commits for this issue )

**Comment by tomasky** [comment]
all plugins versioin  are latest

**Comment by tomasky** [comment]
![bugs](https://user-images.githubusercontent.com/1411118/177699347-6d9b51f8-84e6-44f7-8994-4a7835bb50d4.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177700963-b2c76209-5af7-443e-9335-8c1effdb7279.png)

looks fine here

**Comment by tomasky** [comment]
fresh default configs also have this problem

**Comment by siduck** [comment]
@tomasky tested alacritty, foot and st and they dont have this issue. But kitty does it :/

**Comment by siduck** [comment]
so i will revert this change

**Comment by tomasky** [comment]
my terminal  is ubuntu default built-in

**Comment by siduck** [comment]
@danjenson since this is a very rare edge case, you have to add this in your custom init.lua

```lua
-- set cursor
vim.opt.guicursor = "n-v-c:block-Cursor"
vim.opt.guicursor:append "i:ver100-iCursor"
vim.opt.guicursor:append "n-v-c:blinkon0"
vim.opt.guicursor:append "i:blinkwait10"
```

**Comment by tomasky** [comment]
you `git reset --hard` ? , packersync not works,i have to rm base46 plugin ,and reinstall

**Comment by siduck** [comment]
> you `git reset --hard` ? , packersync not works,i have to rm base46 plugin ,and reinstall

yea i did that

**Comment by danjenson** [comment]
@siduck , cursor is still invisible when not on text  or in insert mode in light themes:
![image](https://user-images.githubusercontent.com/4793438/177860510-c432bb43-8e88-493c-ad2c-0a04f3efe1cc.png)
![image](https://user-images.githubusercontent.com/4793438/177860635-a782f3d1-5427-4849-8554-ccf370f288ef.png)

**Comment by siduck** [comment]
@danjenson i didnt make this change in the base64 repo, you have to add the required code in your custom init.lua

**Comment by danjenson** [comment]
I added that code, and that is what happens after ^

**Comment by siduck** [comment]
> I added that code, and that is what happens after ^

does it work when you add it in defaults.lua of the integration dir in base46 repo?

**Comment by danjenson** [comment]
I don't have a `defaults.lua`
![image](https://user-images.githubusercontent.com/4793438/178084513-3418e118-0a01-431e-a243-b92456e7af9f.png)

**Comment by siduck** [comment]
i meant the base46 plugin, not the nvim config

**Comment by danjenson** [comment]
Where should I add it in base64 .. defaults.lua? It looks like it just returns a large table starting on line 4

**Comment by siduck** [comment]
> Where should I add it in base64 .. defaults.lua? It looks like it just returns a large table starting on line 4

at the first line

**Comment by danjenson** [comment]
No effect
![image](https://user-images.githubusercontent.com/4793438/178157588-37d7134c-2ab0-4c60-9441-b9bab77ee4ca.png)

**Comment by siduck** [comment]
bruh then even that doesnt work, what works :/

**Comment by siduck** [comment]
> So, I think that just defines a highlight group; it becomes active when you assign it to guicursor, so the following two lines work:
> 
> ```
> highlight Cursor guifg=white guibg=black
> set guicursor=n-v-c:block-Cursor
> ```
> 
> So, the way we might do this is to set the highlight group for the `Cursor` in each theme, and then later in the generic config or w/e, set `guicursor` using that highlight group.

you told that this work, so I told you to write the lua equivalent in the base46 repo. Idk why this shouldnt work :/ . Stop using pywal!

**Comment by danjenson** [comment]
yea my system theme is more important than my vim theme..

when I said it didn't work, I meant that it did the same thing as putting it in my chadrc.lua. The cursor is still white on blanks and invisible in insert modes. But, at least it's black when moving over other characters, even though it creates the added problem of making black characters unreadable.

**Comment by danjenson** [comment]
I think one problem is that the highlight group `iCursor` isn't defined anywhere...

**Comment by siduck** [comment]
> I think one problem is that the highlight group `iCursor` isn't defined anywhere...

yes so add it

**Comment by siduck** [comment]
those stuff create issues for rest of the users

**Comment by siduck** [comment]
> @danjenson since this is a very rare edge case, you have to add this in your custom init.lua
> 
> ```lua
> -- set cursor
> vim.opt.guicursor = "n-v-c:block-Cursor"
> vim.opt.guicursor:append "i:ver100-iCursor"
> vim.opt.guicursor:append "n-v-c:blinkon0"
> vim.opt.guicursor:append "i:blinkwait10"
> ```

.

**Comment by siduck** [comment]
yes because this will cause a huge breaking change for non pywal users. cant you add it in your chadrc options?

**Comment by siduck** [comment]
> but now my ` theme = "gruvbox"` cursor background is invisible when word`s color is white

.

**Comment by danjenson** [comment]
...yea it seems like `Cursor` and `iCursor` need to be set by theme...

**Comment by danjenson** [comment]
In the end, I just removed my system themes cursor colors...oh well

**Comment by siduck** [comment]
> ...yea it seems like `Cursor` and `iCursor` need to be set by theme...

you can add the same thing in your custom config :l

**Comment by Marskey** [comment]
may i ask you @siduck  what gui client did you use, its pretty

**Comment by siduck** [comment]
Hi @Marskey can you show a screenshot? I'm on phone so can't scroll properly to this issue as it's very long

**Comment by Marskey** [comment]
this one 
![Uploading 177028473-88155add-38d4-439e-b37f-336dd3d66f52.png…]()

**Comment by siduck** [comment]
> ![177028473-88155add-38d4-439e-b37f-336dd3d66f52](https://user-images.githubusercontent.com/13499986/224332929-a7f3d0d2-d9a0-4275-b433-961568a9360e.png)

@Marskey the above bar you mean? its from my dwm build , check chadwm repo of mine

**Comment by Marskey** [comment]
@siduck no, i mean the gui nvim you using, is it goneovim?

**Comment by siduck** [comment]
> @siduck no, i mean the gui nvim you using, is it goneovim?

That's just my terminal

**Comment by webel** [comment]
I ended up putting this in my init.lua

```lua
-- Set cursor color based on background
vim.cmd [[
  augroup CursorColor
    autocmd!
    autocmd ColorScheme * lua SetCursorColor()
  augroup END
]]

function SetCursorColor()
  if vim.o.background == "light" then
    vim.cmd [[
      highlight Cursor guifg=white guibg=black
      highlight iCursor guifg=white guibg=black
      set guicursor=n-v-c:block-Cursor
      set guicursor+=i:ver100-iCursor
      set guicursor+=n-v-c:blinkon0
      set guicursor+=i:blinkwait10
    ]]
  else
    vim.cmd [[
      highlight Cursor guifg=black guibg=white
      highlight iCursor guifg=black guibg=white
      set guicursor=n-v-c:block-Cursor
      set guicursor+=i:ver100-iCursor
      set guicursor+=n-v-c:blinkon0
      set guicursor+=i:blinkwait10
    ]]
  end
end

-- Run the function once on startup
SetCursorColor()
```

The vim.cmd doesn't work, I guess because it's not ColorScheme being invoked with base64.

But, that means I have to restart nvim if I switch theme. I'm sure there's a callback I can add when theme-switching or a better overall solution, but for now, that's what I got.

Sorry, lua/nvim noob, so if this is gibberish – oops.

**Comment by siduck** [comment]
@webel  can you show the images of with/without your change? I could add it in faq if its useful

**Comment by webel** [comment]
Sure! I'm at sea for a few days, will post as soon as Internet loads up
github.
