### ISSUE TITLE
theme colors are not correct when reopening nvim

### ISSUE THREAD

**Issue by mohad12211** [NvChad/NvChad#1308]
When I set a new theme using `<leader> th`, the theme colors are correct and everything is fine, if I close nvim and reopen it, the theme colors looks different and some colors are different.
(noticed it with `ayu-dark` and `vscode-dark`)

**To Reproduce**
1. Set a new theme (`ayu-dark` or `vscode-dark`)
2. reopen nvim
3. theme is set but not correct (come colors are off)

**Expected behavior**
theme should be displayed correctly.

**Video**

https://user-images.githubusercontent.com/51754973/177052827-a57862fc-ed67-42dc-b619-75d3db162599.mp4

 - Archlinux
 - tested with st, kitty, alacritty, wezterm
 - Neovim (v0.7.2)

**Comment by siduck** [comment]
is it fixed? @mohad12211

**Comment by mohad12211** [comment]
still same issue with ayu-dark

https://user-images.githubusercontent.com/51754973/177100693-f9205e3d-3c2d-4500-9339-746eb885627c.mp4

**Comment by siduck** [comment]
@mohad12211 only ayu-dark? and can you highlight which syntax color dont work?

**Comment by siduck** [comment]
ok do packersync and can u check it again

**Comment by mohad12211** [comment]
the problem with ayu-dark does seem to be fixed, I tried other themes and I noticed another very small problem with some of them.
the `#include` directive in the first line is different
left one is directly after changing the theme (correct one) and the right is after reopening nvim (wrong one)

wombat
![image](https://user-images.githubusercontent.com/51754973/177122882-296433d7-ddec-498c-8ebe-64338c4fc395.png)
palenight
![image](https://user-images.githubusercontent.com/51754973/177123349-7b5374ec-dc8f-46e4-bd9c-1defb3e03237.png)

**Comment by siduck** [comment]
@mohad12211 do packersync and check

**Comment by mohad12211** [comment]
Perfect, Thank you for your efforts!
