### ISSUE TITLE
Tabline adding No Name tabs that can't be closed. 

### ISSUE THREAD

**Issue by luismeramosr** [NvChad/NvChad#1310]
**Describe the bug**
The problem occurs after one of the next actions:
1. Going to the definition of something in code.
2. Using the quickfixlist.
3. Using a plugin like folke/todo-comments.nvim.
Then in the tabline appears a tab with the name "No Name" wich sometimes cannot be closed.
Using telescope to see the buffers only list one "No Name" buffer even if there are two.

**To Reproduce**
1. Go to main init.lua file.
2. Go to definition of core.utils.load_mappings()
3. Select one of the options below.
4. Try to close the "No Name" tab.

**Expected behavior**
No aditional tab called "No Name" should be added to the tabline
when opening the quickfixlist, using a plugin like todo-comments
or in general when opening a buffer that is not a file.

**Screenshots**
![image](https://user-images.githubusercontent.com/41213455/177188397-ed956b13-d4a7-4c16-ba98-c9a6a5a10c5d.png)
![image](https://user-images.githubusercontent.com/41213455/177188472-04052883-05de-454b-a499-2e284d281060.png)
![image](https://user-images.githubusercontent.com/41213455/177188740-764b2ea4-186b-455e-ac37-e906ad89b49c.png)
![image](https://user-images.githubusercontent.com/41213455/177188802-801e841a-e151-4246-a289-cbebfd95a6a7.png)

**Desktop (please complete the following information):**
 - Operating System: Linux
 - Terminal: Alacritty
 - Version of Neovim: 0.7.2

**Additional context**
I tested it re-installing NvChad again, just in case.

**Comment by asyncee** [comment]
I have the same issue.

**Comment by luismeramosr** [comment]
Telescope does work alright, i'll be using it more.

So in the mappings instead of:
![image](https://user-images.githubusercontent.com/41213455/177216057-7719929d-f45f-4215-bde0-f0633b1bcb4b.png)

This does the job:
![image](https://user-images.githubusercontent.com/41213455/177216125-414b953d-3c88-43cf-9351-1683a0d313ae.png)

**Comment by ericwq** [comment]
@siduck did u commit the fix? The problem still exist in the latest update.

**Comment by ericwq** [comment]
confirmed, thanks.
