### ISSUE TITLE
NVIM in ZSH on Windows causes integrated terminal issues

### ISSUE THREAD

**Issue by 13-05** [NvChad/NvChad#1312]
**Describe the bug**
Upon launching the integrated terminal in nvim, (`:terminal`), it throws the following error: `E475: Invalid value for argument cmd: 'C:Program FilesGitusr^Hinzsh.exe' is not executable.` 

**To Reproduce**
1. Launch zsh on windows
2. Inside zsh, run nvim
3. Inside nvim, run `:terminal`
4. It'll throw E475 (described above)

**Expected behavior**
The integrated terminal would open, without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/64506392/177405650-d3f90136-b6b9-4912-8764-f2c7ac37df74.png)

**Desktop (please complete the following information):**
 - Windows 11 Home, x64
 - ZSH inside Windows Terminal
 - NVIM v0.7.2
 
**Additional context**
Inside CMD or PowerShell this error isn't thrown, and it can be somewhat fixed in ZSH by setting `TERM` and `SHELL` to blank strings (`export SHELL=""; export TERM="";`), but that isn't really a viable long-term solution. Maybe the integrated terminal plugin using those environmental variables to determine what OS the user is running and, by effect, how to format the path?

**Comment by siduck** [comment]
does this happen when you do it with vanilla nvim? nvim --clean?

**Comment by 13-05** [comment]
ah it does, guess this issue shouldnt really be in a nvim customization repo, prolly just nvim itself. ill close this.

**Comment by siduck** [comment]
@13-05  I suggest you to try linux,  we keep getting bizarre issues from windows users here :grin:

**Comment by 13-05** [comment]
i might, but i just checked neovim's issues and found a [possible fix](https://github.com/neovim/neovim/issues/16646#issuecomment-1008167932) for my specific issue. btw, thanks for this awesome config, my first time really getting into using neovim and stuff because it's usable with this lol

**Comment by LeonHeidelbach** [comment]
@siduck @13-05 we had a similarly bizarre issue [here](https://github.com/NvChad/NvChad/issues/1300#issuecomment-1172878711).

**Comment by 13-05** [comment]
@LeonHeidelbach your git bash error (`/usr/bin/bash: /s: no file or directory`) was caused by not having a defined `&shellcmdflag`, at least that's why it happened for me. go into your `lua/custom/init.lua`, and add the following line:
```lua
vim.api.nvim_autocommand('autocmd VimEnter * let &shellcmdflag =\'-c\'')
```
this at least fixed that issue for me when using git bash.

**Comment by TrippleA-Ashaba** [comment]
> i might, but i just checked neovim's issues and found a [possible fix](https://github.com/neovim/neovim/issues/16646#issuecomment-1008167932) for my specific issue. btw, thanks for this awesome config, my first time really getting into using neovim and stuff because it's usable with this lol
> 
> edit:
> if anyone else comes across this problem in the future (idk if they will but just in case yk) heres what i did:
> in nvim's config, go to the `custom` folder you created to load stuff with nvchad. then, go to `init.lua` in that folder. add this line: `vim.api.nvim_command('autocmd VimEnter * let &shellcmdflag = \'-c\'')`, and then add the following line: `vim.api.nvim_command('autocmd VimEnter * let &shell=\'"C:/"Program Files"/Git/bin/bash.exe"\'')`, or whatever the path to your preferred terminal is, but replace the backslashes with forward slashes, and that way, every time nvim launches, it makes sure your terminal thing works!


Thank you very much for posting your solution, a year later and this problem still exists. I even dual booted Ubuntu just because of this issue. I persevered only because the Linux terminal sucks and has no ligatures. Glad I stayed awake scouring the web for a solution.

**Comment by ghost** [comment]
@TrippleA-Ashaba glad it helped! though, your statement about linux terminals not having ligatures is just plain false haha. i use linux now and my setup uses them:
(command: `echo "-> => === != *** &&& ~~"`)
![image](https://github.com/NvChad/NvChad/assets/64506392/2024744d-f88a-4872-b273-b281037d710d)

here's the documentation on one of the most popular linux terminal emulators for enabling ligatures (and actually, they're enabled by default!): https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.disable_ligatures


edit: sorry for the mention leon! i made a typo

**Comment by siduck** [comment]
> > i might, but i just checked neovim's issues and found a [possible fix](https://github.com/neovim/neovim/issues/16646#issuecomment-1008167932) for my specific issue. btw, thanks for this awesome config, my first time really getting into using neovim and stuff because it's usable with this lol
> > edit:
> > if anyone else comes across this problem in the future (idk if they will but just in case yk) heres what i did:
> > in nvim's config, go to the `custom` folder you created to load stuff with nvchad. then, go to `init.lua` in that folder. add this line: `vim.api.nvim_command('autocmd VimEnter * let &shellcmdflag = \'-c\'')`, and then add the following line: `vim.api.nvim_command('autocmd VimEnter * let &shell=\'"C:/"Program Files"/Git/bin/bash.exe"\'')`, or whatever the path to your preferred terminal is, but replace the backslashes with forward slashes, and that way, every time nvim launches, it makes sure your terminal thing works!
> 
> Thank you very much for posting your solution, a year later and this problem still exists. I even dual booted Ubuntu just because of this issue. I persevered only because the Linux terminal sucks and has no ligatures. Glad I stayed awake scouring the web for a solution.

many linux terminals support ligatures man, even my ST build https://github.com/siduck/st

**Comment by TrippleA-Ashaba** [comment]
@13-05 This definitely needs another thread .We are going away from topic🤣🤣. I didn't mean to shit on Linux, mint is my fav. I meant that the built-in terminal has no support for ligatures.

I say this coz my current system is a 15 yr old desktop Pentium dual core with 4gb ram. Very shitty. Can only run vim🤣. I can't afford installing the fancy kitty.  Even the non GPU tabby can't run without glitching.

That's why I was really happy you had the solution to the windows git bash. 
Until I upgrade, I will stick to windows for now. I will definitely be coming for cinnamon.

**Comment by siduck** [comment]
@TrippleA-Ashaba just use my chadwm and st terminal on your mint, i also had a 4gb ram & pentium HP laptop before 

![image](https://github.com/NvChad/NvChad/assets/59060246/25188b55-6316-43ba-a5e5-11de522cf559)

or use another tiling wm! your workflow would get very speed :)

**Comment by TrippleA-Ashaba** [comment]
@siduck Thank you very much for this. I really appreciate 

Although I don't understand half the shit that is going on. But I will in time 

Ps: Your work is really awesome
