### ISSUE TITLE
Color is incorrect when committing git changes

### ISSUE THREAD

**Issue by chuan137** [NvChad/NvChad#1317]
**Describe the bug**
Color is incorrect when committing git changes

**To Reproduce**
1. run `git commit -v`, the color of '-' changes is green and '+' changes is red

**Expected behavior**
expecting the revert behavior, the '-' changes in red and '+' in green

**Screenshots**
![image](https://user-images.githubusercontent.com/6780922/177719015-fecadc75-a4bd-466a-9f62-4898475f10f8.png)

**Desktop (please complete the following information):**
 - Operating System 
 macOS 12.4
 - Terminal
 iterm2
 - Version of Neovim 
 NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

**Additional context**

**Comment by siduck** [comment]
how are you checking the git diff?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177734030-6be0bb54-8425-4362-90ad-5d9203aeb01b.png)

looks fine here

**Comment by rockorager** [comment]
I had this happen too. I custom load Gitsigns without any lazy loading. Gitsigns is what’s setting the highlights, and it only loads for git repos. If you do certain git operations, the files load from a tmp directory and don’t load Gitsigns, and you don’t get the right highlights

**Comment by siduck** [comment]
@rockorager git highlights will work when you are in a git dir

**Comment by rockorager** [comment]
For me it showed up in ft= gitSendEmail

**Comment by siduck** [comment]
> For me it showed up in ft= gitSendEmail

weird :thinking:

**Comment by rockorager** [comment]
`git send-email` opens nvim with :pwd as /tmp/...

So those files aren't in a git dir, no gitsigns, no highlights. Easily enough fixed with disabling lazy load, or a ft load.

`git commit -v` does have pwd as the git dir (or, the dir you executed the command from), so I don't understand why that wouldn't work.

**Comment by tomasky** [comment]
If i comment this line ,the color is normal
```lua
--/lua/plugins/configs/treesitter.lua
 
-require("base46").load_highlight "syntax"
+-- require("base46").load_highlight "syntax"
 require("base46").load_highlight "treesitter"

```

**Comment by rockorager** [comment]
1. From a git repo, execute the following command: `git send-email --annotate -1`

Another way:
1. From a git repo, execute the following command: `git format-patch HEAD~1`
2. Move the file to a non-git repo and open it

**Comment by rockorager** [comment]
I'm not sure all the highlights, but DiffAdded is definitely used and links to Identifier, initially. After loading Gitsigns it is set to it's own value (green, in my case)

**Comment by siduck** [comment]
I viewed it in telescope and it looks normal 

![image](https://user-images.githubusercontent.com/59060246/178520511-37ae19f2-4b6a-487d-bec7-7851026b3ef7.png)

**Comment by tomasky** [comment]
@siduck  
```bash
export EDITOR=nvim
nvim some.lua
delete some lines in some.lua
git add .
git commit -v
```

**Comment by siduck** [comment]
this should be fixed by now, sorry for the delay guys!

**Comment by tomasky** [comment]
@siduck  i am waiting buffer picker feature .

**Comment by siduck** [comment]
> @siduck i am waiting buffer picker feature .

i still dont understand what it is :thinking:

**Comment by tomasky** [comment]
you can see bufferline.nvim`s  logics

**Comment by siduck** [comment]
> you can see bufferline.nvim`s logics. And when the same file name shows the directory

![image](https://user-images.githubusercontent.com/59060246/178653439-5b325d28-1eff-4346-9fc2-25ca33ce9d32.png)

what does buffer in view mean here

**Comment by tomasky** [comment]
This is to mark different buffers with different letters and then press letters to jump to that buffer. You can install buffeline.nvim to see the effect

**Comment by siduck** [comment]
ohh i get it now
