### ISSUE TITLE
Strange <nop> mappings with character 'Þ'

### ISSUE THREAD

**Issue by perseoGI** [NvChad/NvChad#1318]
With a fresh NvChad installation without any custom folder and everything up to date, some mappings are being created to \<nop\> having this strange character 'Þ' all in common. 
This is a petty because all mapped  

**To Reproduce**
1. :Telescope keymaps
2. Type <Space>  to see some of the mappings 
3. Or type the character 'Þ' to see all the mappings

**Screenshots**
![image](https://user-images.githubusercontent.com/26503843/177762187-b44218b8-6222-4433-8450-359be803a11f.png)
![image](https://user-images.githubusercontent.com/26503843/177762366-d9d5aacd-1acf-4c11-a04c-82fe76bfb932.png)

**Bad solution**
```viml
unmap >Þ
unmap @Þ
unmap [Þ
unmap ]Þ
unmap cÞ
unmap dÞ
unmap gÞ
unmap vÞ
unmap yÞ
unmap zÞ
unmap aÞ
unmap gÞ
unmap iÞ
unmap !iÞ
unmap !aÞ
unmap >iÞ
unmap >aÞ
unmap ciÞ
unmap caÞ
unmap diÞ
unmap daÞ
unmap guÞ
unmap g~Þ
unmap gUÞ
unmap viÞ
unmap vaÞ
unmap yiÞ
unmap yaÞ
unmap zfÞ
unmap guiÞ
unmap guaÞ
unmap g~iÞ
unmap g~aÞ
unmap <lt>Þ
unmap <C-W>Þ
unmap <Space>Þ
unmap <Space>Þ
unmap !Þ
unmap gUiÞ
unmap gUaÞ
unmap zfiÞ
unmap zfaÞ
unmap <lt>iÞ
unmap <lt>aÞ
unmap <Space>uÞ
unmap <Space>rÞ
unmap <Space>bÞ
unmap <Space>wÞ
unmap <Space>pÞ
unmap <Space>gÞ
unmap <Space>cÞ
unmap <Space>tÞ
unmap <Space>fÞ
unmap <C-H>Þ
unmap <C-K>Þ
unmap <C-N>Þ
unmap <C-S>Þ
unmap <C-W>Þ
unmap <C-G>Þ
```

**Desktop**
 - Operating System: Arch Linux
 - Terminal: Alacritty
 - Version of Neovim: latest (v0.7.2)
But this problem has been detected also on a MacOS system and on a WSL (ubuntu) and for a long period of time. 
 
I thought it could be one of my plugins but this is happening with a fresh clean install :(

**Comment by siduck** [comment]
are these default vim mappings? @LeonHeidelbach

**Comment by LeonHeidelbach** [comment]
@siduck @perseoGI I have no idea what these bindings are supposed to be useful for but as we do not set them ourselves I guess they have to be default neovim bindings, or one of our plugins sets them. However, I could not find anything on this in a quick Google search. The special character is apparently called the Icelandic/Old English thorn.

**Comment by tomasky** [comment]
The lunarvim has the same problem ,some mappings are also being created to <nop>,but not much

**Comment by tomasky** [comment]
I'm sure it's a which-key problem,because i dont use which-key,no this problem

**Comment by siduck** [comment]
> I'm sure it's a which-key problem,because i dont use which-key,no this problem

agreed, @LeonHeidelbach watchout!!

**Comment by tomasky** [comment]
```lua
M.plugins = {
    remove = { "folke/which-key.nvim" },
}
```

**Comment by perseoGI** [comment]
> ```lua
> M.plugins = {
>     remove = { "folke/which-key.nvim" },
> }
> ```

But this is throwing previous error, do I have to remove custom mappings description as it says [here](https://nvchad.github.io/config/Mappings#mapping-with-which-key-disabled)?

Isn't it possible to keep mappings description with which-key disable?

**Comment by siduck** [comment]
ok this isnt a nvchad issue, whichkey's design has this 

![image](https://user-images.githubusercontent.com/59060246/178507848-f88d2f56-a432-4e98-8092-53aed604cc43.png)

https://github.com/folke/which-key.nvim/issues/299

so closing this @LeonHeidelbach

**Comment by perseoGI** [comment]
Alright, nice! 

@siduck I have another question: I'm getting this error by the time I removed which-key plugin:

![image](https://user-images.githubusercontent.com/26503843/178524245-25cd1e5e-4d34-46d7-8dbb-dcee2cf14593.png)

And it is caused by my custom "un-mappings":
  ```lua
["<C-h>"] = "",  -- this format
["<C-h>"] = {},  -- or this other way will produce previous error
```
If I do this:

```lua
["<C-h>"] = nil 
```
Error is not thrown but neither the unmap is done, so, how can I unmap default mappings with which-key disabled?
Thank in advance, love your work :)

**Comment by siduck** [comment]
@perseoGI how did you remove whichkey? did you do packercompile? @tomasky do you get this issue as you dont use whichkey too

**Comment by perseoGI** [comment]
For removing it:
```lua
M.plugins = {
   remove = {
      "folke/which-key.nvim"
   },
}
```
And I have also tried to simply disable it with same result (error thrown):
```lua  
["folke/which-key.nvim"] = {
     disable = true,
},
```
PackerSync and Compile in each test ensure fresh Neovim restart, etc.

I'm not able to unmap default NvChad mappings without which-key :disappointed:

**Comment by tomasky** [comment]
remove this line, doc is out of date  I dont have this problem.
```lua
-- custom/init.lua
 require("core.utils").load_mappings()
```

**Comment by tomasky** [comment]
@perseoGI  see docs first , 
disable some mapping key :
```lua
M.disabled = {
  n = {
      ["<leader>h"] = "",
      ["<C-s>"] = ""
  }
}
```

**Comment by perseoGI** [comment]
> @siduck , @perseoGI remove this line, doc is out of date I dont have this problem.
> 
> ```lua
> -- custom/init.lua
>  require("core.utils").load_mappings()
> ```

I had this already comment but NvChad default mappings are loaded anyway

**Comment by perseoGI** [comment]
> @perseoGI see docs first , disable some mapping keys :
> 
> ```lua
> M.disabled = {
>   n = {
>       ["<leader>h"] = "",
>       ["<C-s>"] = ""
>   }
> }
> ```

Oh, my fault @tomasky I read fast and did not see "M.disabled" field, I'm sorry, thanks, this now works! 
Problem solved!

**Comment by tomasky** [comment]
@siduck  the doc needs to be improved

**Comment by perseoGI** [comment]
> @siduck the doc needs to be improved

That is true, I cannot lie hehe but as this repo has been making some breaking changes recently I understand that keeping docs up to date is hard and in some cases not worth. 
I found some difficulties on making my custom NvChad config. 
I think a bigger configuration example could be nice. [This](https://github.com/perseoGI/dotfiles/tree/master/dotfiles/neovim/nvchad/lua/custom) is my custom config. I would have liked to have some template like mine when I joined NvChad 2 months ago!

Maybe when I found some spare time I could help you guys! Awesome work!

**Comment by siduck** [comment]
@perseoGI my custom config is mentioned in the docs i think

**Comment by perseoGI** [comment]
> @perseoGI my custom config is mentioned in the docs i think

Yes, that helped me, but for example, you didn't have that unmap example hehe (that understandable because its your repo xD) 
As @tomasky it could be explicitly mentioned apart.
