### ISSUE TITLE
NvChad not recognizing custom plugins

### ISSUE THREAD

**Issue by majodu** [NvChad/NvChad#1319]
**Describe the bug**
PackerSync is cleaning out all my plugins in the custom folder. When moved to the main plugins folder they are properly installed. I uninstalled by removing  nvim in .local and .config.

**To Reproduce**
custom/plugins/init.lua
```
return {
    ["lepture/vim-jinja"] = {},
}
```
custom/chadrc.lua
```
local M = {}

M.plugins = {
   user = require "custom.plugins",
}
return M
```

 - Operating System: macOS monterey
 - Terminal : Alacritty
 - Version of Neovim: NVIM v0.7.0

**Comment by majodu** [comment]
Also broke when I had an empty mappings file local M = {} return M

**Comment by siduck** [comment]
> It broke when I had an empty mappings file local M = {} return M

having empty table still works for me so this is more likely your custom config issue
