### ISSUE TITLE
Live grep file preview is not working for directories containing empty spaces in their name

### ISSUE THREAD

**Issue by rodnring** [NvChad/NvChad#1320]
**Describe the bug**
Using <leader> fw and searching for a word, doesn't change the blank state of the file preview box
if any of the directory names in the path to project has empty space in its name.

UPDATE: This had nothing to do with the filetype, it was a problem with reading directories that 
had space in their names, when I changed my directory name from "Work Projects" to "work-projects"
the live grep preview worked fine again.

**To Reproduce**
1. Install clean NvChad configuration
2. Get inside a project directory which has '\' space escape in its unix name like 'Working\ Project'
3. Telescope live_grep (or <leader>fw) to open grep, type in anything.
4. Search for a keyword and watch the blank preview box

**Expected behavior**
I expected the preview box to show the part of file
that contained the keyword I've searched for.

**Screenshots**
From Alacritty: https://postimg.cc/rRDv8qny

**Desktop (please complete the following information):**
 - Manjaro
 - Alacritty (bash) and Yakuake (zsh) - verified the issue on both
 - Neovim 0.7.2-2

**Comment by siduck** [comment]
this is more of an upstream issue, of telescope.nvim so we cant help wtih this
