### ISSUE TITLE
Add a way to disable "Text" completions (cmp-buffer)

### ISSUE THREAD

**Issue by vvug** [NvChad/NvChad#1322]
I personally find "Text" completions from `cmp-buffer` annoying, and I'd like to disable those. Apparently there's not way to do it: I can't find documentation on how to disable plugins on https://nvchad.github.io/. Moreover `cmp-path` is loaded after `cmp-buffer`, so fully disabling `cmp-buffer` will interfere with loading `cmp-path`, I think.

Note that I don't want to disable Text completions for specific file types, but always.

**Describe the solution you'd like**

Add a way to disable completion plugins without blocking others.

**Comment by siduck** [comment]
you mean buffer completions?

**Comment by siduck** [comment]
override cmp config and put this in the table

```lua
sources = {
      { name = "luasnip" },
      { name = "nvim_lsp" },
      { name = "nvim_lua" },
      { name = "path" },
   },
   ```
