### ISSUE TITLE
No syntax highlighting, treesitter not working

### ISSUE THREAD

**Issue by vedantnn71** [NvChad/NvChad#1324]
**Describe the bug**
Syntax highlighting is not working, I tried removing and reinstalling nvchad twice but still doesn't work.

**To Reproduce**
1. Open neovim w/nvchad installed 
2. Open anyfile
3. Voila! No syntax highlighting
**Expected behavior**
Syntax highlighting / treesitter should be working.

**Screenshots**
![image](https://user-images.githubusercontent.com/70624701/178137943-e7d4e47d-91c0-4391-934d-c390cb968b6c.png)

**Desktop (please complete the following information):**
 - Freshly installed arco linux (rolling release)
 - St / all config is of author (@siduck)
 - Version of neovim: v0.8.0-dev+580-g45ba2e147

**Additional context**
I also tried installing multiple treesitter plugins, enabling it from neovim itself, but nothing worked :(

**Comment by siduck** [comment]
did u install c & tsx parser?

**Comment by siduck** [comment]
and when was the last time u updated nvchad

**Comment by vedantnn71** [comment]
yes I've installed lua, c, typescript, javascript, eslint, like everything and also have update yesterday

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/178138162-7f061af6-92a4-43fd-9ac9-f3964e0578f1.mp4

works here

**Comment by vedantnn71** [comment]
but not here , see :(
![image](https://user-images.githubusercontent.com/70624701/178138190-e2e5b445-cc06-4ac8-8bb5-a7412a006211.png)

**Comment by siduck** [comment]
ok delete the custom dir for now ( move it to some other dir )

and see

**Comment by vedantnn71** [comment]
which custom dir? you mean `~/.config/nvim`?

**Comment by siduck** [comment]
wait, use neovim v.0.7

**Comment by siduck** [comment]
i read it somewhere that 0.8 has filetype issues

**Comment by vedantnn71** [comment]
ohh okay thank but how? is there any way to downgrade it on arch 🤔

**Comment by siduck** [comment]
use this 
![image](https://user-images.githubusercontent.com/59060246/178138299-903d2092-89d9-417e-a9a1-2afe76128548.png)

or search for bob version manager

**Comment by vedantnn71** [comment]
thank you siddhart!
