### ISSUE TITLE
custom config not executed

### ISSUE THREAD

**Issue by lunw1024** [NvChad/NvChad#1326]
**Describe the bug**
After updating to the latest version of nvchad and neovim 0.7.2, nvchad stopped respecting my custom config. I tried to reinstall nvchad but didn't work. Seems like the files in the custom/ folder aren't even executed.

**To Reproduce**
1. create custom config in `lua/custom/`
2. run neovim
3. none of the custom configs work

**Expected behavior**
Custom configs work or an error is thrown.

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - neovim 0.7.2

**Comment by siduck** [comment]
please check the chadrc, it will obviously have some issues

**Comment by songww** [comment]
[pcall(require, "custom")](https://github.com/NvChad/NvChad/blob/86b3b6e96bad85727378a5849e89d2f65afe3cc7/init.lua#L12) 
The errors in custom config are always dropped here, and it would be more helpful for debug if the errors in it were shown.

**Comment by siduck** [comment]
I doubt, many people face this issue whenever they require something in the chadrc like a plugin which shouldnt be done 

![image](https://user-images.githubusercontent.com/59060246/178176895-2abfcba0-f0b3-484a-b8c2-541f02800aad.png)

Cuz that plugin's lazy loaded and its config has some chadrc stuff so the rest of the chadrc doesnt execute at all. 

This is the default behaviour, users must understand that chadrc is just supposed to have the structure of default_config.lua and it will override default_config.lua

**Comment by lunw1024** [comment]
Here is my chadrc.lua:
```lua
-- Just an example, supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:
M.ui = {
    theme = "chadracula",
}

M.options = {
    user = function()
        vim.opt.number = true
        vim.opt.mouse = "a"
        vim.opt.tabstop = 4
        vim.opt.shiftwidth = 4
        vim.opt.expandtab = true
    end,
}

M.plugins = {
    user = require "custom.plugins",
    override = require "custom.plugins.override",
    options = {
        lspconfig = {
            setup_lspconf = "custom.plugins.lspconfig",
        },
    },
}

M.mappings = {
    competitiest = {
        n = {
            ["<leader>ca"] = { "<cmd> CompetiTestAdd <CR>", "Competitest: Add testcase" },
            ["<leader>cr"] = { "<cmd> CompetiTestRun <CR>", "Competitest: Run testcases" },
        }
    }
}

return M
```

**Comment by lunw1024** [comment]
Also, even if I add a syntactically incorrect line at the top of chadrc.lua, nvim still doesn't throw an error or anything.

**Comment by tomasky** [comment]
this config  works, please offer plugins  dir custom config ,then we can test.
```lua
local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:
M.ui = {
    theme = "chadracula",
}

M.options = {
    user = function()
        vim.opt.number = true
        vim.opt.mouse = "a"
        vim.opt.tabstop = 4
        vim.opt.shiftwidth = 4
        vim.opt.expandtab = true
    end,
}

M.plugins = {
}

M.mappings = {
    competitiest = {
        n = {
            ["<leader>ca"] = { "<cmd> CompetiTestAdd <CR>", "Competitest: Add testcase" },
            ["<leader>cr"] = { "<cmd> CompetiTestRun <CR>", "Competitest: Run testcases" },
        }
    }
}

return M

```

**Comment by songww** [comment]
> [pcall(require, "custom")](https://github.com/NvChad/NvChad/blob/86b3b6e96bad85727378a5849e89d2f65afe3cc7/init.lua#L12) 

@lunw1024   just change this line to `require("custom")` , you will see the error.

**Comment by lunw1024** [comment]
> > [pcall(require, "custom")](https://github.com/NvChad/NvChad/blob/86b3b6e96bad85727378a5849e89d2f65afe3cc7/init.lua#L12)
> 
> @lunw1024 just change this line to `require("custom")` , you will see the error.

Still no errors. I'm pretty sure that chadrc.lua isn't even executed. 

here is the folder structure:
![image](https://user-images.githubusercontent.com/57162668/178186836-696ded9f-b89d-4ff0-8794-2870ef50dbc7.png)

and here are my custom config:

`chadrc.lua`
```lua
-- Just an example, supposed to be placed in /lua/custom/

local M = {}
ashsad -- to make an error
-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.options = {
    user = function()
        vim.opt.number = true
        vim.opt.mouse = "a"
        vim.opt.tabstop = 4
        vim.opt.shiftwidth = 4
        vim.opt.expandtab = true
    end,
}

M.plugins = {
    user = require "custom.plugins",
    override = require "custom.plugins.override",
    options = {
        lspconfig = {
            setup_lspconf = "custom.plugins.lspconfig",
        },
    },
}

M.mappings = {
    competitiest = {
        n = {
            ["<leader>ca"] = { "<cmd> CompetiTestAdd <CR>", "Competitest: Add testcase" },
            ["<leader>cr"] = { "<cmd> CompetiTestRun <CR>", "Competitest: Run testcases" },
        }
    }
}

return M
```

`init.lua`
```lua
-- example file i.e lua/custom/init.lua
-- load your globals, autocmds here or anything .__.
```

and all the files:
[custom.zip](https://github.com/NvChad/NvChad/files/9080861/custom.zip)

**Comment by tomasky** [comment]
@lunw1024  ,please check this config first. 

> this config works, please offer plugins dir custom config ,then we can test.
> 
> ```lua
> local M = {}
> 
> -- make sure you maintain the structure of `core/default_config.lua` here,
> -- example of changing theme:
> M.ui = {
>     theme = "chadracula",
> }
> 
> M.options = {
>     user = function()
>         vim.opt.number = true
>         vim.opt.mouse = "a"
>         vim.opt.tabstop = 4
>         vim.opt.shiftwidth = 4
>         vim.opt.expandtab = true
>     end,
> }
> 
> M.plugins = {
> }
> 
> M.mappings = {
>     competitiest = {
>         n = {
>             ["<leader>ca"] = { "<cmd> CompetiTestAdd <CR>", "Competitest: Add testcase" },
>             ["<leader>cr"] = { "<cmd> CompetiTestRun <CR>", "Competitest: Run testcases" },
>         }
>     }
> }
> 
> return M
> ```

**Comment by siduck** [comment]
@lunw1024 your plugins table seems suspicious, comment that table and see if it works.

**Comment by tomasky** [comment]
@lunw1024  ,this will be not works. watch out . @siduck ,this is an old question

```lua
local present, cmp = pcall(require, "cmp")

return {
    ["hrsh7th/nvim-cmp"] = {
        mapping = {
            ["<CR>"] = cmp.mapping.confirm {
                behavior = cmp.ConfirmBehavior.Insert,
                select = false,
            }
        }
    }
}
```

shoud be this:
```lua
return {
    ["hrsh7th/nvim-cmp"] = function()
	local cmp = require "cmp"
       return { mapping = {
            ["<CR>"] = cmp.mapping.confirm {
                behavior = cmp.ConfirmBehavior.Insert,
                select = false,
            }
        }
    }
   
end
```

**Comment by tomasky** [comment]
@siduck ,As I said before, this question will be asked many times If   don't do something

**Comment by siduck** [comment]
> @siduck ,As I said before, this question will be asked many times If don't do something

i will add the functional way of ovrriding config in the docs today

**Comment by lunw1024** [comment]
@tomasky thanks! the problem is resolved now. somehow my config worked in previous versions of nvchad, which was why this was especially confusing for me.

**Comment by siduck** [comment]
@tomasky 

which indentation looks good? the right one is our current one

https://cdn.discordapp.com/attachments/869557816430563370/995915747714936913/unknown.png

**Comment by tomasky** [comment]
me too, I have noticed this indent not aligned in current one,but dont  mention it

**Comment by tomasky** [comment]
me too, I have noticed this indent not aligned in current one,but no  mention it

**Comment by siduck** [comment]
yea our current one adds extra indent lines

![image](https://user-images.githubusercontent.com/59060246/178192741-84561ef6-169f-43ae-8e79-e66f2f243c43.png)


try shiftwidth=3 and lemme know if there are some bugs etc

**Comment by tomasky** [comment]
`shiftwidth=3` looks good, but if  the cursor is on that line, this indent thread moves to the right

**Comment by siduck** [comment]
> `shiftwidth=3` looks good, but if the cursor is on that line, this indent thread moves to the right

you get the same issue with `shiftwidth=2` too, this is an indentline feature, I'll try asking the author

**Comment by Clivern** [comment]
I fixed this by enabling editorconfig so it works per project config

```
vim.g.editorconfig = true
```

```
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# Set default charset
charset = utf-8

# 4 space indentation
indent_style = space
indent_size = 4

# Trim trailing whitespace
trim_trailing_whitespace = true

# Equivalent to vim.opt.number = true (not directly supported in EditorConfig)
# You might need to configure this in your editor separately

# Equivalent to vim.opt.mouse = "a" (not directly supported in EditorConfig)
# You might need to configure this in your editor separately

# Equivalent to vim.opt.expandtab = true
indent_style = space

# Equivalent to vim.opt.tabstop = 4 and vim.opt.shiftwidth = 4
indent_size = 4

# Equivalent to vim.opt.softtabstop = 4 (not directly supported in EditorConfig)
# This is typically handled by indent_size in most editors
```
