### ISSUE TITLE
statusline does not work

### ISSUE THREAD

**Issue by mmsaeed509** [NvChad/NvChad#1327]
after updating NvChad statusline does not work

![Screenshot_2022-07-11-02-46-00_3840x1080](https://user-images.githubusercontent.com/62524855/178169634-680f6714-230a-4227-90fc-ee8ec78c2770.png)

how to configure it again to be like that 

![Screenshot_2022-07-11-02-46-22_3840x1080](https://user-images.githubusercontent.com/62524855/178169742-d474bd3d-ae62-4b5d-8787-0873d7e0f722.png)

**Comment by siduck** [comment]
it works bruh :/ 

I removed nvim-gps because it was dead, you can override the statusline config yourself and add gps or nvim-navic component

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/commit/cd5d85a11b5eecaf12d9a9f420e8924ed6a214d7#commitcomment-77606986
