### ISSUE TITLE
how can highlight of the parent function can be disabled

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1330]
![image](https://user-images.githubusercontent.com/78728701/178735369-7330abb1-f238-49cb-8b0a-a043873e62e3.png)

This is in all type of files in different languages i have googled alot but i cannot get the solution of how to disable this , i would appreciate any help. Thanks

**Comment by siduck** [comment]
override indent-blankline config which is in the plugins/others.lua file, just disable the context related stuff
