### ISSUE TITLE
LSP Installer is not work for `rust_analyzer`

### ISSUE THREAD

**Issue by mrxiaozhuox** [NvChad/NvChad#1332]
use `LspInstall rust_analyzer` success, but the LspInfo can't found the `ra` info, and I can't start this server.

I've use `LspInstall rust_analyzer` and success to install this server.

**Expected behavior**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41265098/178959978-5f303c0d-6ee9-4c91-9657-faa344061450.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41265098/178960036-52b412a5-83ca-4eb6-9ed6-087775c5ed91.png">

- Neovim version: NVIM v0.7.0
- OS: MacOS Monterey
- Term: Hyper

**Comment by siduck** [comment]
make sure your cwd has cargo.toml & matches root_dir of rust_analayzer lsp

**Comment by mrxiaozhuox** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41265098/178961124-57dc9ca5-4bf3-4c98-a9c5-f60994a88a2d.png">

**Comment by siduck** [comment]
oh, just installing rust_analyzer wont work and you have to setup rust_analzyer lsp in  your custom lspconfig too. read our docs
