### ISSUE TITLE
Statusline `cwd` module not visible even when space is available

### ISSUE THREAD

**Issue by PROxZIMA** [NvChad/NvChad#1333]
**Describe the bug**
Statusline's `cwd` module not visible even when space is available.

**To Reproduce**
1. Open neovim with NvChad installed
2. Slowly reduce terminal width.
3. Statusline's `cwd` module disappears even when space is available,

**Expected behavior**
If space is available then the module should show itself.

**Screenshots**
visible:
![visible](https://user-images.githubusercontent.com/43103163/178964618-b228757c-b0c6-431b-8849-939f0cf88d26.png)
not visible:
![not visible](https://user-images.githubusercontent.com/43103163/178964607-6a12ce58-a21a-407f-bb83-c34b136ea19c.png)

**Desktop (please complete the following information):**
 - Operating System: Pop!_OS 22.04 LTS x86_64
 - Terminal: kitty 0.25.2
 - Version of Neovim: NVIM v0.7.2

**Comment by PROxZIMA** [comment]
Ikr. Is this how it should be done from custom folder only (also I had to tweak some icons like vim icon in `mode` module or folder icon in `cwd` module)?

```lua
-- custom/statusline.lua
local st_modules = require "ui.statusline.modules"

local sep_style = require("ui.icons").statusline_separators
local default_sep = require("core.default_config").ui.statusline.separator_style
local sepo_l = sep_style[default_sep]["left"]
local sepo_r = sep_style[default_sep]["right"]

new_sep_style = {
    left = " ",
    right = "  ",
}

local sep_l = new_sep_style["left"]
local sep_r = new_sep_style["right"]

local M = {}

M.mode = function()
   return st_modules.mode():gsub("", ""):gsub(sepo_r, sep_r)
end

M.fileInfo = function()
   return st_modules.fileInfo():gsub(sepo_r, sep_r)
end

M.cwd = function()
   return st_modules.cwd():gsub("", " "):gsub(sepo_l, sep_l)
end

M.cursor_position = function()
   return st_modules.cursor_position():gsub("", " "):gsub(sepo_l, sep_l)
end

return M
```

```lua
-- chadrc.lua
M.ui = {
    theme = "onedark",
    statusline = {
        override = require "custom.plugins.statusline"
    },
}
```

**Comment by siduck** [comment]
@PROxZIMA I will move statusline to our ui plugin today & add your fire separators too so it will get easy for you. Just wait a bit :D

**Comment by PROxZIMA** [comment]
Awesome!!. About the fire separator, it is actually 3 character wide. The issue is with the space between the left separator and its following icon(cwd, cursor_position). You can experiment with it.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/179151681-27653b55-dafb-444f-9d43-7dc7d1c4e204.png)
