### ISSUE TITLE
Allow configuration of vim.diagnostic.config

### ISSUE THREAD

**Issue by gmartsenkov** [NvChad/NvChad#1335]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

There doesn't seem to be a way to disable inline diagnostics in the custom config folder.
I have tried tried this from the docs:
```lua
-- chadrc.lua

M.options = {
   user = function()
      vim.diagnostic.config {
         virtual_text = false,
         signs = true,
         underline = true,
         update_in_insert = false,
      }
   end
}

```
**Describe the solution you'd like**

Have an option to enable/disable inline diagnostics or a way to override the whole config.

**Comment by siduck** [comment]
put it in your custom lspconfig

the vim.diagnostic table
