### ISSUE TITLE
Rust semantic highlighting

### ISSUE THREAD

**Issue by nothingIsSomething** [NvChad/NvChad#1336]
I'm enabling the option vim.g.lsp_semantic_enabled = 1, but the theme colors do not work with rust, I assume themes are not compatible with semantic highlighting or am I wrong?

**Comment by siduck** [comment]
whats semantic highlighting? any example of how rust syntax colors would look with it or withou tit

**Comment by nothingIsSomething** [comment]
it is an option of rust analyzer to give more colors to the syntax but it is the theme that does the coloring, lsp now supports it natively, https://github.com/prabirshrestha/vim-lsp/pull/1275 , you activate it with vim.g.lsp_semantic_enabled = 1

![image](https://user-images.githubusercontent.com/95933429/179151985-e5f0b833-7d0b-4f82-b43f-5a0fc565249e.png)

**Comment by siduck** [comment]
i cant differentiate much lul but nvchad looks fine too

**Comment by siduck** [comment]
https://www.reddit.com/r/rust/comments/ls5sx1/is_rustanalyzer_for_neovim_ever_going_to_support/

**Comment by siduck** [comment]
https://github.com/rust-lang/rust.vim/issues/424

**Comment by siduck** [comment]
idk if nvim lsp supports it

**Comment by ShooTeX** [comment]
https://github.com/neovim/neovim/pull/21100

looks like it's supported in nvim 0.9
