### ISSUE TITLE
tabufline has empty space on the left beginning

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#1338]
**Describe the bug**
tabufline has empty space on the left beginning when i open nvim-tree, my nvim-tree is on the right side
To be honest, tabufline is not very convenient

![tips](https://user-images.githubusercontent.com/1411118/179169875-7138aa41-0376-4fe8-92c1-6d340f5b1da9.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
oh thats cuz its  concaneted at the starting
![image](https://user-images.githubusercontent.com/59060246/179176270-9735c83f-4081-4fd0-85b2-b1ce9faaa1ee.png)

**Comment by siduck** [comment]
i'll try to fix

**Comment by tomasky** [comment]
No , problem remains

**Comment by siduck** [comment]
do packersync :l

**Comment by tomasky** [comment]
default nvim-tree config is ok, but my custom nvim-tree config not works.  I have check what's the difference:

```lua 
     adaptive_size = false,
```

**Comment by siduck** [comment]
@tomasky i put that to false and it still works

**Comment by tomasky** [comment]
it is so strange，if i remove my nvim-tree custom config ,it works ,i dont know why.

**Comment by siduck** [comment]
show your nvimtree config

**Comment by tomasky** [comment]
i known why . 
```lua
vim.g.nvimtree_side = options.view.side

-- check for any override
options = require("core.utils").load_override(options, "kyazdani42/nvim-tree.lua")

```

**Comment by siduck** [comment]
force-pushed!
