### ISSUE TITLE
NcChad ui modules not found

### ISSUE THREAD

**Issue by patya3** [NvChad/NvChad#1339]
**Describe the bug**
module 'nvchhad.ui.signature' not found, any ui modul not found, like nvchad.ui.renamer
It worked when i first install nvChad, but after time it stopped working.

**To Reproduce**
1. Open neovim and open a file
2. on every action it pops up

**Expected behavior**
Working as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/41230554/179174100-66ed4786-f8cc-4a46-aa72-25fe4e8b3e43.png)

**Desktop (please complete the following information):**
 - Operating System: windows 10
 - Terminal: PowerShell 7 (in windows terminal)
 - Version of Neovim: 0.7.2

**Comment by tomasky** [comment]
:PackerSync

**Comment by patya3** [comment]
> :PackerSync

I :PackerSync multiple times but nothing. Its not helping.

**Comment by tomasky** [comment]
<space+uu>

**Comment by rockorager** [comment]
I had a similar issue.

I was not lazy-loading NvimTree. I had to edit my custom load to have NvimTree load `after = "ui"`

**Comment by siduck** [comment]
@rockorager weird, nvimtree isnt even related to the ui plugin! update nvchad properly

**Comment by rockorager** [comment]
@siduck I think it's because I have nvimtree icons on, which needs nvim-web-devicons, which in turn [calls](https://github.com/NvChad/NvChad/blob/ce027efbe9569711b19f307f40c81e27f79ebb96/lua/plugins/configs/others.lua#L158) the ui plugin

**Comment by siduck** [comment]
@rockorager our ui plugin loads straight after base46 plugin or you wouldnt see the statusline and tabufline

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/179335746-1820a72f-7637-4257-bea0-e63a51e0cedb.mp4

works fine here

**Comment by rockorager** [comment]
If you prevent lazy loading nvimtree though, it fails. I can reproduce with a stock install and this base custom/chadrc.lua

```lua
local M = {}

M.plugins = {
	user = {
		["kyazdani42/nvim-tree.lua"] = {
			config = function()
				require("plugins.configs.nvimtree")
			end,
		},
	},
	remove = {
		"kyazdani42/nvim-tree.lua",
	}
}

return M
```

**Comment by rockorager** [comment]
It's not really an NvChad issue though, IMO. I just was trying to give some tips to OP. You can only make things work so far if people are changing the order of loading, haha

**Comment by siduck** [comment]
oh thats because you removed lazyloading of nvimtree xD, but why not just override the default config instead of redefining its packer config?

**Comment by rockorager** [comment]
@siduck #953. The `ignore_buffer_on_setup` option didn’t work for me, so I undid lazy loading.

**Comment by siduck** [comment]
how did u override it? @rockorager

**Comment by rockorager** [comment]
@siduck 

chadrc.lua:
```lua
M.plugins {
    override = {
        ["kyazdani42/nvim-tree.lua"] = custom.plugins.override.nvimtree
    }
}
```

custom/plugins/override.lua

```lua
M.nvimtree = {
   ignore_buffer_on_setup = true,
   ...
}
```

**Comment by siduck** [comment]
@rockorager i see the issue, nvimtree is lazyloaded on cmds so and this option works when nvimtree isnt loaded, you need to modify nvimtree's packer option i.e load it after any non lazyloaded plugin such as this 

```lua
["kyazdani42/nvim-tree.lua"] = {
      after = "nvim-web-devicons",
 }
 ```
 
 put this in your custom plugins section and do packercompile , reopen nvim
