### ISSUE TITLE
NvChad didn't install correctly on my Mac

### ISSUE THREAD

**Issue by TravisDart** [NvChad/NvChad#1342]
**Describe the bug**
I tried the ["Try in docker container"](https://nvchad.github.io/quickstart/install#try-in-docker-container) and that works fine. So, I tried to use NvChad instead of my previous config. I moved `~/.config/nvim` to another location, and ran the install command `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`. But, the editor looks like there are no plugins. I ran `:PackerInstall` and that asked to delete a bunch of files from `~/.local/share/nvim/site/pack/packer/`, but nvim was unchanged even after a restart. I swapped back my old config, ran `:PackerInstall` and everything works as it did before.

I have no idea why this fails. My only guess is that perhaps there's an artifact of my old config that's messing it up.

**Expected behavior**
I'm expecting the real install to look like the docker version.

**Screenshots**
This is a screenshot of running `:checkhealth`
![Screen Shot 2022-07-16 at 7 55 21 AM](https://user-images.githubusercontent.com/5155310/179354071-e45eca74-50ed-49aa-b828-cacc50a39239.png)

**Desktop (please complete the following information):**
 - Operating System: MacOS 12.4 (Monterey)
 - Terminal: I tried both Kitty and iTerm2
 - node.js: I tried both 14 and 17 (not sure if this matters)
 - Version of Neovim: 
 ```
$ nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

**Comment by shengjie77** [comment]
I got the same issue and removing `~/.local/share/nvim/` solves my problem.

**Comment by siduck** [comment]
idk much about docker and i dont use macos so cant help much!

**Comment by max397574** [comment]
perhaps try `:PackerSync`

**Comment by alipiry** [comment]
> I got the same issue and removing `~/.local/share/nvim/` solves my problem.

Yeah totally worked, thank you 🙌

**Comment by TravisDart** [comment]
> I got the same issue and removing `~/.local/share/nvim/` solves my problem.

Yes, this solved the problem. NvChad now works fine.

**Comment by gglanzani** [comment]
Would this warrant a mention in the docs @siduck ? :D

**Comment by siduck** [comment]
> Would this warrant a mention in the docs @siduck ? :D

done
