### ISSUE TITLE
problem with syntax highlighting

### ISSUE THREAD

**Issue by krypton612** [NvChad/NvChad#1344]
**Describe the bug**

I don't know why but the syntax highlighting doesn't work, install nvchad as the wiki indicates

**To Reproduce**
1. install nvchad

**Expected behavior**
expected nvchad to install without any problem, making syntax highlighting work

**Screenshots**

![Esta es una imagen de ejemplo](https://raw.githubusercontent.com/krypton612/krypton612/main/Captura%20de%20pantalla%20de%202022-07-12%2018-00-31.png)

**Desktop (please complete the following information):**
 - Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali5 (2022-07-04) x86_64 GNU/Linux
 - alacritty 0.11.0-dev (ebc6922e)
 - NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilado por runner@fv-az316-460

**Comment by siduck** [comment]
do u have python tsparser installed

**Comment by krypton612** [comment]
yes, if i bring it installed

![Esta es una imagen de ejemplo](https://raw.githubusercontent.com/krypton612/krypton612/main/Captura%20de%20pantalla%20de%202022-07-18%2001-08-07.png)

**Comment by siduck** [comment]
can u share that file so i could test it here?

**Comment by glendell03** [comment]
> Hi, I have the same issue; I just installed nvchad too
> 
> Edit: I have Neovim 8.0. I think that is the reason why I don't have the syntax highlighting I'll in a couple of hours

Hi! I have the same issue with you

**Comment by glendell03** [comment]
> With the `NVIM v0.7.2`, it works ! I just need to read the documentation carefully ahah

How to install v0.7.2 in ubuntu?
i try adding the stable ppa then it downloaded the 0.6 version

**Comment by ManishEntrupy** [comment]
Is there any fix for nv 0.8.0 @siduck ?

**Comment by krypton612** [comment]
everything seems to indicate that the version of neovim 0.7.0 has a problem, but the problem is solved by installing version 0.7.2

![resultado](https://raw.githubusercontent.com/krypton612/krypton612/main/Captura%20de%20pantalla%20de%202022-07-19%2000-46-15.png)

**Comment by siduck** [comment]
> Is there any fix for nv 0.8.0 @siduck ?

idk

**Comment by siduck** [comment]
@krypton612 yes you are supposed to use LTS version of neovim which is v0.7.2 currently

**Comment by tomasky** [comment]
@siduck  just remove this line at 0.8-dev ,filetype.lua mode is default now . 0.7 verrsion maybe not affect
```lua
g.did_load_filetypes = 0
```

**Comment by siduck** [comment]
> @siduck just remove this line at 0.8-dev ,filetype.lua mode is default now . 0.7 version maybe not affect
> 
> ```lua
> g.did_load_filetypes = 0
> ```

hm, ig users can add this in custom init.lua file

**Comment by siduck** [comment]
so filetype.lua is default from 0.7.2?

**Comment by tomasky** [comment]
no ,need remove this line ,not set it

**Comment by siduck** [comment]
> no ,need remove this line ,not set it

i removed it and it increases startuptime :/ 

![image](https://user-images.githubusercontent.com/59060246/179883979-f3d18e2a-8ef8-4798-ab65-9801658b43df.png)


Users are supposed to use the LTS version of nvim 0.7.2 and not the dev version cuz they will keep facing problems like this

**Comment by tomasky** [comment]
if remove this line,  i test it at 0.7.0 and 0.7.2 , the syntax highlighting works ,but dont kwnow others.

**Comment by siduck** [comment]
yes syntax highlighting works but startuptime increases by a lot,m 6 MS on my machine is like 30-40ms on other old machines

**Comment by tomasky** [comment]
why startuptime increases ?

**Comment by tomasky** [comment]
0.8 not need this lines:, maybe 0.7 needs
```lua
-- lua/core/options.lua
-- g.did_load_filetypes = 0
-- g.do_filetype_lua = 1

```

**Comment by siduck** [comment]
> why startuptime increases ?

idk

**Comment by tomasky** [comment]
maybe you can check the nvim version to handle this case. Remove this condition after 0.8 release just like lsp`s formatter
