### ISSUE TITLE
calling lua chunk on lua core init.lua

### ISSUE THREAD

**Issue by moeinkolivand** [NvChad/NvChad#1346]
i have nvim 0.6.1 and ubuntu 22.04
i remove the configs nvim and clone the repo (installation guide) and after running nvim get this error
error message
Error while calling lua chunk: /home/moein/.config/nvim/lua/core/init.lua:12: attempt t
o call local 'autocmd' (a nil value)

**Comment by tomasky** [comment]
read docs first:
 
## Pre-requisites
- You should be an existing vim user or keen to learn nvim + nvchad (through these docs)
- [Neovim 0.7.2](https://github.com/neovim/neovim/releases/tag/v0.7.2)
- If neovim's very old for your OS then consider trying this [neovim version manager](https://github.com/MordechaiHadad/bob)
- [Use a Nerd Font](https://www.nerdfonts.com/) in your terminal emulator.

**Comment by siduck** [comment]
update neovim version to 0.7.2!
