### ISSUE TITLE
Visual selection incorrect

### ISSUE THREAD

**Issue by xarthurx** [NvChad/NvChad#1348]
**Describe the bug**
After updating `nvChad` (last time 2 weeks ago), here is a bug:

Once I comment some lines for the first time, then it seems the selected area cannot be updated whatever I do after. 
So if I comment some other lines after, it will remember the previously selected area somehow.

**To Reproduce**
1. Select some lines.
2. `ctrl + /` comment.
3. Select some other lines.
4. Comment again.
5. See the error.

**Expected behavior**
Comment works as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/1921878/179497528-be222f2f-a492-49c9-be69-a09c9a99d337.png)

**Desktop (please complete the following information):**
 - Windows 11
 - GUI
 - Version of Neovim: newest stable.

**Comment by siduck** [comment]
it works for me, also can u use a terminal? Nvchad doesnt guarantee to work with gui nvim clients

**Comment by xarthurx** [comment]
> it works for me, also can u use a terminal? Nvchad doesnt guarantee to work with gui nvim clients

In my terminal, both `cmd` and `powershell` the comment shortcut does not work. So I don't know.

I've been using GUI for many years, and before today's update, nvChad works like a charm.

**Comment by xarthurx** [comment]
I don't do update daily. Last one was at the end of June...

**Comment by xarthurx** [comment]
I guess it might because of the introduction of the new UI system.

**Comment by siduck** [comment]
can you provide a video of this?

**Comment by xarthurx** [comment]
https://user-images.githubusercontent.com/1921878/179930293-560b1963-bd38-45c4-9b18-f24a713b89fe.mp4

Here, I (move the cursor --> select --> comment --> undo the option.) x n times.

**Comment by siduck** [comment]
can you try this in a terminal?

**Comment by xarthurx** [comment]
> 

As I said, `ctrl+/` does not work in my terminal (Windows). Is there a command I can do with `: commend` to comment the selected text?

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/179949715-d76498e3-ae58-4f84-8255-3cce5febd8c5.mp4

tested on neovide for you and it works for me

**Comment by siduck** [comment]
@xarthurx first try with vanilla nvchad (without custom dir )

**Comment by xarthurx** [comment]
I found out the issue. When I modify the comment shortcut some time ago, I don't have the `<ESC>` mapped.
It seems this has been changed on `nvchad` side at some point, and I didn't update it..

Now after I added the escape, everything works like a charm.
Sorry about this and thank you for your time.

```
   v = {
      ["<C-/>"] = {
         "<ESC>(this guy) <cmd>lua require('Comment.api').toggle_linewise_op(vim.fn.visualmode())<CR>",
         "蘒  toggle comment",
      },
   },
```

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/179953245-de513cb0-830d-4f02-a0a0-cd91f87056bb.png)

https://c.tenor.com/qdg13PqYbxMAAAAC/yes-baby.gif

**Comment by xarthurx** [comment]
You're amazingly efficient!
