### ISSUE TITLE
Visual Mode Visible Issue

### ISSUE THREAD

**Issue by aniimsh** [NvChad/NvChad#1349]
**Describe the bug**
In visual mode I cannot see the visual part I selected due to background is already highlighted, this bug are only in dark themes light theme works well

**To Reproduce**
1. Go to 'v mode'
2.Select lines
3.Then cannot see highlighted line (super rarely visible)

**Expected behavior**
To see the selected line visible in visual mode,

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/103873305/179503022-fb7cc9b5-1e8c-4f03-9553-cd88845af7b4.jpg)

**Desktop (please complete the following information):**
 - Fedora 36
 - Terminal: Alacritty, Kitty
 - Version of Neovim: v.0.7.2

**Comment by siduck** [comment]
i can see the selected line in the visual mode here tho :thinking:
