### ISSUE TITLE
Bug at two or more open buffers in neovim

### ISSUE THREAD

**Issue by KirovAI** [NvChad/NvChad#1353]
**Describe the bug**
If you open two files in INSERT MODE in neovim and switch between its
then in  files  will print two "z"  characters on cursor position:

![cursor_line_config](https://user-images.githubusercontent.com/105173528/179568558-236ee0b7-6788-473a-9afb-8859b5f30551.png)

![cursor_line_config](https://user-images.githubusercontent.com/105173528/179568883-d60b23d9-a257-40bd-ad7e-09417c09dacb.png)

**Comment by siduck** [comment]
doesnt happen with me, first go back to normal mode and then try to switch between buffers

**Comment by KirovAI** [comment]
video:

https://user-images.githubusercontent.com/105173528/179602756-e9c3b74f-1dfd-4f20-975c-67998971daf2.mp4

**Comment by KirovAI** [comment]
> doesnt happen with me, first go back to normal mode and then try to switch between buffers

I open files from nvimtree

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/179682965-ef575a54-4c3c-40c2-8ed6-b67bd1fda95c.mp4


doesnt happen with me, i hope you are using v0.7.2 and a terminal

**Comment by siduck** [comment]
also set nerdfonts in your terminal, icons are not showing at all

**Comment by KirovAI** [comment]
> also set nerdfonts in your terminal, icons are not showing at all

cuz i in console, if i launch neovim in WM-window all icons must be appeared

**Comment by KirovAI** [comment]
> simplescreenrecorder-2022-07-19_12.09.32.mp4
> 
> doesnt happen with me, i hope you are using v0.7.2 and a terminal
maybe cause of this problem WSL. I work on linux under it

**Comment by KirovAI** [comment]
Anyway thanks . 
offtopic:
Possible to disallowed all updates to my neovim custom preset?
I just want create git repository with stable preset of neovim that dont getiing all updates which can broken it. Of course I leave message with gratitude dedicated to you and reference to this repositor.  And references to your patreon , paypal and others donations systems
can I upload on github my current version of neovim?

**Comment by siduck** [comment]
> > simplescreenrecorder-2022-07-19_12.09.32.mp4
> > doesnt happen with me, i hope you are using v0.7.2 and a terminal
> 
> maybe cause of this problem WSL. I work on linux under it

hm if it nvchad works on linux then most likely wsl issue, does it work on windows?
