### ISSUE TITLE
Where did buffer tabs go?

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1354]
Just got used to buffer tabs, but now when I open a new file using Telescope or nvim-tree it replaces the current buffer. How can I get that old default behavior back, which opens a new buffer for every opened file? It also appears as though all the nice formatting is gone:
![image](https://user-images.githubusercontent.com/4793438/179819951-90e8f253-627b-4ecf-a123-9ec321895a29.png)

**Comment by siduck** [comment]
our tabufline is lazyloaded to 2+ buffers so when you have 2+ buffers opened then tabufline will load, you can disable this behaviour by disabling lazyload field in tabufline config 

https://nvchad.github.io/config/nvchad_ui#tabufline
