### ISSUE TITLE
Saving file shows an error msg

### ISSUE THREAD

**Issue by JinraeKim** [NvChad/NvChad#1356]
**Describe the bug**
With the same setting of #1355 (with and without tmux; it doesn't matter),
whenever I tried to save a file with `:w`, it shows an annoying error of

```
"a.py" 3L, 6B written
E828: Cannot open undo file for writing: /home/jinrae/.local/state/nvim/undo/%home%jinrae%a.py
Press ENTER or type command to continue
```

**Comment by KirovAI** [comment]
maybe you havent permissions? or your file-system is read-only

**Comment by JinraeKim** [comment]
> maybe you havent permissions? or your file-system is read-only

Honestly speaking, idk why but it has suddenly been fixed after reconnecting ssh.
Probably it was a temporary issue (yup, prob read-only).

Sorry guys...

**Comment by JinraeKim** [comment]
Or, I'm just curious, do I need `xclip` stuff for this? @KirovAI
