### ISSUE TITLE
lsp server not working

### ISSUE THREAD

**Issue by The-0Day** [NvChad/NvChad#1363]
**Describe the bug**
I set up lua server in ```lspconfig.lua```, but didn't get any suggestions.

**To Reproduce**
1. Open neovim with a ```go``` extension: ```nvim main.go```
2. Then just write a code: 
```
package main

import "fmt"

func main()  {
   fmt.P
}
```
3. should be seeing more suggestions such as ```Println```, but not happened

**Expected behavior**
Well the lsp server must show me all suggestions.

**Screenshots**
![image](https://user-images.githubusercontent.com/76570757/180600346-10593aa2-acf3-40b1-8416-ef32de144dcf.png)

**Desktop (please complete the following information):**
 - Operating System : ```Linux arch 5.18.10-zen1-1-zen```
 - Terminal : ```st```
 - Version of Neovim : 
 ```
 NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```
My ```lspconfig.lua``` file: https://termbin.com/azlvw

**Comment by tomasky** [comment]
:LspInstallInfo ,   Check whether gopls is successfully installed

**Comment by The-0Day** [comment]
> :LspInstallInfo , Check whether gopls is successfully installed

![image](https://user-images.githubusercontent.com/76570757/180609063-bb2575d3-dcaf-4e5c-bac3-d7f358b50270.png)
Looks like yes, ```gopls``` installed successfully. Any idea?

**Comment by tomasky** [comment]
check other languages lsp like lua,  and check `["hrsh7th/nvim-cmp"] ` config

**Comment by The-0Day** [comment]
> check other languages lsp like lua, and check `["hrsh7th/nvim-cmp"] ` config

No need now! Idk how but I just re-clone NvChad and now it works fine!
