### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by UserXGnu** [NvChad/NvChad#1364]
**Is your feature request related to a problem? Please describe.**
For users not really used to use nvim with lua configuration, it is really hard to grasp how to figure out all the keybindings.

**Describe the solution you'd like**
It would be very good if a simple list of keybindings to the key features of the configuration.

Thank you for all the good work!! ^^

**Comment by leftbones** [comment]
I'd like to add that there are a lot places in the docs that say something like "Add this in your plugin overrides section" with some code snippet, but it's not immediately clear where that is, or the snippet is incomplete so it's hard to figure out where that is.

**Comment by siduck** [comment]
@leftbones docs are supposed to be read sequentially, you cant just cherry pick certain parts of docs if you are a new nvchad user

**Comment by andrewstonedev** [comment]
Call me a smooth-brained ape too cause I read the docs (and the getting started with lua, and :vimtut) and I've taken it as far as dedicating acouple hours a day to learning vim over the last few weeks and while Nvchad is the best I've seen in terms of using plain language to explain what is going on, there's still a large amount of a priori knowledge required to achieve anything (not just Nvchad but the entirely of nvim ecosystem unfortunately) Given that Nvchad is the best I've seen over recent weeks, I'd love if you took it full circle and really made it beginner friendly
