### ISSUE TITLE
Setting to display tabs only on the tabufline

### ISSUE THREAD

**Issue by leftbones** [NvChad/NvChad#1365]
For people who don't ever use buffers, just tabs, it'd be nice to have a config to only show tabs on the tabufline and completely hide buffers, like vanilla Vim.

This would make it fall more in line with how a standard GUI editor works.

**Comment by siduck** [comment]
override tabufline config and disable bufferlist module. simple

https://nvchad.github.io/config/nvchad_ui#statusline--tabufline

```lua
    ["NvChad/ui"] = {
      tabufline = {
        overriden_modules = function()
          return {
            bufferlist = function()
              return "%#TblineFill#" .. "%="
            end,
          }
        end,
      },
      ```
      
      in your override section

**Comment by siduck** [comment]
that should go in your override section, tblinefill to add the hl group and "%=" adds empty space. read the docs before making issues!

**Comment by leftbones** [comment]
So, this does stop the buffers from appearing in the tabufline, but doesn't list tabs in the way buffers are displayed by default.

I did read the docs, they explain how to override modules, but without reading the source code, that doesn't mean much to the average user. Just a heads up, that's exactly the kind of thing people are talking about when they say they don't understand the docs or that the docs are too complicated!

**Comment by siduck** [comment]
you just need to override tablist module
