### ISSUE TITLE
how can i add themes like add the normal plugins.

### ISSUE THREAD

**Issue by FlyingAlaska** [NvChad/NvChad#1366]
I love so much this config of neovim, but when I want to add a theme, I find it is diffcult for me.
I want to add themes like a normal plugin, and call it. such as [the monokai.nvim](https://github.com/tanvirtin/monokai.nvim).

**Comment by siduck** [comment]
we already have monokai theme, press leader th. 

you cant add external theme plugins. Nvchad is heavily reliant on base46
