### ISSUE TITLE
[Bug]: Tabufline cannot be disabled

### ISSUE THREAD

**Issue by djpiper28** [NvChad/NvChad#1367]
**Describe the bug**
Tabufline cannot be disabled

**To Reproduce**
sample chadrc to disable it
```lua
-- Just an example, supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.ui = {
  theme = "gruvchad",
  transparency = true,
}

M.plugins = {
  user = require "custom.plugins",
  status = {
    dashboard = true,
    alpha = true,
  },
  options = {
    lspconfig = {
      setup_lspconf = "custom.plugins.lspconfig",
    },
  },
  override = {
    ["neovim/nvim-lspconfig"] = {
      config = function()
        require "plugins.configs.lspconfig"
        require "custom.plugins.lspconfig"
      end,
    },
    ["NvChad/ui"] = {
      tabufline = {
        enabled = false,
        lazyload = true,
        overriden_modules = nil,
      },
    }
  },
}

return M
```

**Expected behavior**
Tabufline should be disabled, it isn't.

**Screenshots**
n/a.

**Desktop (please complete the following information):**
 - Operating System: Garuda Linux (arch)
 - Terminal: konsole
 - Version of Neovim: 0.7.2?

**Additional context**

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/180650696-d7980fd7-4865-4786-b183-f6490338ddd0.mp4

works fine here, its your issue ig :/

**Comment by djpiper28** [comment]
I tried reinstalling and, then putting my config back and, it seems to work?. idk
