### ISSUE TITLE
Migration from lsp-installer to mason.nvim ?

### ISSUE THREAD

**Issue by ahhshm** [NvChad/NvChad#1368]
[`lsp-installer` will no longer be maintained](https://github.com/williamboman/nvim-lsp-installer/discussions/876) and [`mason.nvim`](https://github.com/williamboman/mason.nvim) is the officially recommended alternative which is from the same guy who created `lsp-installer`. Is the migration going to be happening any soon?

**Comment by siduck** [comment]
@ahhshm soon and only if its possible to lazy load it. Read https://github.com/williamboman/mason.nvim/discussions/122

**Comment by ahhshm** [comment]
Well, according to the README:
> mason.nvim is optimized to load as little as possible during setup. Lazy-loading the plugin, or somehow deferring the setup, is not recommended.

So I think it's not a big of a deal to not lazy load it.

**Comment by ahhshm** [comment]
Common, an unmaintained plugin is preferable that a plugin that could not be lazy-loaded?

**Comment by ahhshm** [comment]
Mason itself can't be lazy loaded but I think we can lazy load [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim) which does the lspconfig stuff.

**Comment by siduck** [comment]
Idk why can't Mason be lazyloaded, I just want to install the lspservers and just put the installation bin dir on my shell's path, not sure why it doesn't work :(

**Comment by ahhshm** [comment]
Why do you want to lazy-load it?

As I understood, Mason does a bunch of other things than installing lap servers. Mason.nvim is the core package that provides an API to other plugins. [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim) is the mason plugin that installs lap servers, exactly like "lsp-installer" and theoretically, it should be lazily loadable.
So you can load mason.nvim on setup and it's ok as it's very minimal. Just lazy-load `mason-lspconfig.nvim`. Mason.nvim has nothing to do with lap servers so you still can lazy-load them.
Again, I haven't tried this plugin yet.

**Comment by siduck** [comment]
i didnt lazy load it before  + lspconfig lazyloaded then LSP doesnt work at all so i had to remove lazyload of lspconfig which is a heavy plugin :/

**Comment by siduck** [comment]
Also we wont add mason-lspconfig.nvim ._.

**Comment by ahhshm** [comment]
@siduck I managed to get it working in like 15m without any problem. loading mason.nvim on setup only increased the load time by less than 1 millisecond!! Should I create a PR?

BTW, I also used `mason-lspconfig.nvim`. If you want the full functionality of lsp-installer you have to have it.

**Comment by siduck** [comment]
Even without lazyloading Mason.nvim, I face same error 

Check https://github.com/williamboman/mason.nvim/issues/126

Try without mason-lspconfig,  and no we will only use mason.nvim

**Comment by kagbodji** [comment]
> @siduck I managed to get it working in like 15m in a docker container without any problem. loading mason.nvim on startup only increased the load time by less than 1 millisecond!! Should I create a PR?
> 
> BTW, I also used `mason-lspconfig.nvim`. If you want the full functionality of lsp-installer you have to have it.

Mind sharing your config? Did you have to do anything extra beyond the config changes indicated in https://github.com/williamboman/nvim-lsp-installer/discussions/876?

**Comment by siduck** [comment]
@ahhshm also even 1 MS startuptime matters, if we can lazyload something without compromising anything then we will do it. 1-2MS on my machine is like around 10MS + on my older machine ( pentium + hdd )

**Comment by 00sapo** [comment]
I was going to move to nvchad from lvim, but without mason.nvim and with unmaintained plugins such as nvim-lsp-installer, it doesn;t make any sense

**Comment by ahhshm** [comment]
@00sapo I think NvChad did the migration and now It's using mason.nvim

**Comment by rollingmoai** [comment]
It would still be beneficial if `mason-lspconfig.nvim` was added.

**Comment by ahhshm** [comment]
@rollingmoai Yeah, mason-lspconfig.nvim is the recommended way to use mason with lspconfig. I also think it should be added because without that we lose the best feature of lsp-installer:  automatic installation of lsp servers

**Comment by ahhshm** [comment]
> > @siduck I managed to get it working in like 15m in a docker container without any problem. loading mason.nvim on startup only increased the load time by less than 1 millisecond!! Should I create a PR?
> > BTW, I also used `mason-lspconfig.nvim`. If you want the full functionality of lsp-installer you have to have it.
> 
> Mind sharing your config? Did you have to do anything extra beyond the config changes indicated in [williamboman/nvim-lsp-installer#876](https://github.com/williamboman/nvim-lsp-installer/discussions/876)?

Yeah, I just followed the migration guide. I don't know exactly what problems siduck was talking about but it was looking good when I installed it in a docker container.

**Comment by siduck** [comment]
> > > @siduck I managed to get it working in like 15m in a docker container without any problem. loading mason.nvim on startup only increased the load time by less than 1 millisecond!! Should I create a PR?
> > > BTW, I also used `mason-lspconfig.nvim`. If you want the full functionality of lsp-installer you have to have it.
> > 
> > 
> > Mind sharing your config? Did you have to do anything extra beyond the config changes indicated in [williamboman/nvim-lsp-installer#876](https://github.com/williamboman/nvim-lsp-installer/discussions/876)?
> 
> Yeah, I just followed the migration guide. I don't know exactly what problems siduck was talking about but it was looking good when I installed it in a docker container.

I wont add mason-lspconfig, mason.nvim is enough for us. Just list all the required packages in the ensure_installed field and :MasonInstallAll will install all of them

**Comment by siduck** [comment]
> @siduck I understand that startup time is very important for NvChad. That's why I stopped asking you to use mason.nvim. But it's also a good ready-to-use neovim configuration that people can use and get started with neovim very quickly. In my humble opinion, if something makes users' life easier it is worth compromising 1-2 milliseconds of startup time.
> 
> That's your project, you can do whatever you like and I respect that. I don't even use NvChad so I'm really not in a position to tell you what to do.
> 
> Also, that 1 millisecond is from a very very old machine that is like my little brother. 1MS on a modern average machine is around 10 or 20 MS on my machine.

it was our lspconfig which was lazyloaded and didnt work even when mason.nvim was not lazyloaded. I had to add 

```vim.cmd("silent! e") ``` for lspconfig in our lazyoad functions so everything works now! And we are still lazyloading mason.nvim at its cmds cuz we just use it for installing stuff and mason's packages bin path is set in our path already so we dont have to worry about it

**Comment by siduck** [comment]
read the everyone! https://nvchad.github.io/config/Lsp%20stuff#masonnvim

**Comment by ahhshm** [comment]
@siduck great job. glad to hear it's working now. Just want to say thank you for such an amazing project.

**Comment by siduck** [comment]
> @siduck great job. glad to hear it's working now. Just want to say thank you for such an amazing project.

but it seems like you wont use NvChad, it doesnt affect me but saddens me a lil xD

**Comment by ahhshm** [comment]
@siduck NvChad is great.  I really like the new way of customizing it. Great job. But I'm happy with my current config. I've had a couple of attempts to move my config to NvChad but it takes a decade to do :)

**Comment by siduck** [comment]
> @siduck NvChad is great. I really like the new way of customizing it. Great job. But I'm happy with my current config. I've had a couple of attempts to move my config to NvChad but it takes a decade to do :) (I have a lot of plugins)

you can still install all of those plugins on nvchad tho. But agreed, If I were a non nvchad user then I would just use my own config unless i care about the asethetics & lazyloading and some special nvchad features

**Comment by kagbodji** [comment]
> > @siduck NvChad is great. I really like the new way of customizing it. Great job. But I'm happy with my current config. I've had a couple of attempts to move my config to NvChad but it takes a decade to do :) (I have a lot of plugins)
> 
> you can still install all of those plugins on nvchad tho. But agreed, If I was a non nvchad user then I would just use my own config unless i care about the asethetics & lazyloading and some special nvchad features

It's funny, it was the opposite for me. I've been resistant to adopt pre-configured nvim instances because I have a very old and battle-tested config I've been using, and most of these vim configs required me to follow a pattern that was not aligned with my way of using vim. I also dreaded moving to Lua, I thought it'd be a daunting task to migrate my existing config, which is mostly vimscript/python. Nvchad is VERY configurable, which is what I like. The defaults are sensible, but they are super-easy to change. I've remapped a many key bindings, default vim opts, etc to suit my usage patterns, and am in the process of migrating plugins over (the core ones I used have already been added / replaced). What sold me was the UI config, themes and some UI elements were just what I wanted, and I didn't care to spend time setting those up. So thank you for this project!

**Comment by romeobalta** [comment]
> I also dreaded moving to Lua, I thought it'd be a daunting task to migrate my existing config, which is mostly vimscript/python. Nvchad is VERY configurable, which is what I like. The defaults are sensible, but they are super-easy to change. I've remapped a many key bindings, default vim opts, etc to suit my usage patterns, and am in the process of migrating plugins over (the core ones I used have already been added / replaced).

It was exactly the same for me. Moved to vim fulltime after having to use vscode for job reasons and I realised it would take me ages to rewrite everyting in lua and get used to it again. Found NvChad, looked exactly like what I wanted, so I just used it as a base and added very few tweaks on top of it (my custom folder also used siduck's custom config as a base). Got used to it in a day and I'm very happy with it. This project is great!
