### ISSUE TITLE
whichkey suggestions gone?

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1372]
Open nvim, type leader -> no suggestions. Also `<leader>uu` no longer shortcut for updates?

**Comment by danjenson** [comment]
Looks like my leader isn't working at all anymore...

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/180897523-19f1e262-b9de-4281-bd8c-6fa3d641cea8.png)

No change regarding whichkey was made so this seems like your system/config issue

**Comment by danjenson** [comment]
Did you change how the leader was defined? Because this is no longer working
![image](https://user-images.githubusercontent.com/4793438/180898951-38427da6-74bc-4b7e-a3b2-d6ac8bd2d5b7.png)

**Comment by danjenson** [comment]
yea, that shortcut is no longer observed. The leader is back to defaulting to space.

**Comment by tomasky** [comment]
see ,https://github.com/NvChad/NvChad/commit/6a789fa37df1deecaefd18337ab84aef331b5095

**Comment by tomasky** [comment]
@siduck  maybe you should add some changelogs

**Comment by siduck** [comment]
> Did you change how the leader was defined? Because this is no longer working ![image](https://user-images.githubusercontent.com/4793438/180898951-38427da6-74bc-4b7e-a3b2-d6ac8bd2d5b7.png)

oh yea you need to just put all your options into custom.init.lua

**Comment by siduck** [comment]
> @siduck maybe you should add some changelogs

where do I add that? Ig we are supposed to add them while releasing right?

**Comment by tomasky** [comment]
you also can add them at issues page just like neovim`s  breaking tips

**Comment by tomasky** [comment]
like this:
https://github.com/neovim/neovim/issues/14090

**Comment by siduck** [comment]
looks helpful, I'll do this next time

**Comment by tomasky** [comment]
Neovim 0.8 is still a long way off and has most breaking changes, I think you can adapt it now by adding version check and remove those checks when 0.8 released

**Comment by siduck** [comment]
> Neovim 0.8 is still a long way off and has most breaking changes, I think you can adapt it now by adding version check and remove those checks when 0.8 released

we just support 0.7.2

**Comment by siduck** [comment]
> Neovim 0.8 is still a long way off and has most breaking changes, I think you can adapt it now by adding version check and remove those checks when 0.8 released

ok I agree with this now, it'll save us time later when 0.8 releases

**Comment by cotko** [comment]
@siduck I also don't see whichkey suggestions any more. First I've removed ~/.config/nvim + ~/.cache/nvim then I also tried running clean setup via docker. If I pres space and wait, nothing happens (while space+uu prints nvchad is up to date for example). I'm on arch with neovim v0.7.2.

**Comment by tomasky** [comment]
@cotko  see breaking changes, 
Whichkey plugin is disabled by default now, just enable it like how you would enable alpha.nvim https://github.com/NvChad/NvChad/commit/74ad741e633d8435452ade6667b52efd8c879dda

**Comment by cotko** [comment]
@tomasky damn I had to remove ~/.local/share/nvim as well. Now it actually works if I enable it:)
