### ISSUE TITLE
lsp servers functionality gone

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1373]
Running `<leader>k` fails to show info. Even after installing appropriate lsp server with mason, it doesn't check anything:
![image](https://user-images.githubusercontent.com/4793438/180877149-26e69fe9-b289-4283-9c10-1a4f0ecf1b9a.png)

**Comment by danjenson** [comment]
Is there any chance we can create breaking changes on branches and test them before pushing to main? I update my system/nvim almost daily, which breaks nvim almost 50% of the time because of breaking changes or bugs from this repo.

**Comment by siduck** [comment]
this isnt a bug, your lsp is just not running. What does even lspinfo show? and check about nvchadsnapshots

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/180897894-feef3b1c-edf8-47aa-b89c-a294b7d97919.mp4

works totally fine here, i dont even code in python!

**Comment by danjenson** [comment]
Looks like it isn't recognizing the new mason installed lsp servers:
![image](https://user-images.githubusercontent.com/4793438/180898836-f24b4542-6d17-4f37-8a02-c2c09e27c4be.png)

**Comment by danjenson** [comment]
My lspconfig
![image](https://user-images.githubusercontent.com/4793438/180899073-4cc12b96-ca3a-4087-866f-af8b69b00cab.png)

**Comment by danjenson** [comment]
It's not loading any of the mason installed lsp servers
![image](https://user-images.githubusercontent.com/4793438/180900510-fe3a662c-9fc6-475e-9c03-86beda6046ab.png)

**Comment by tomasky** [comment]
i know some users will be confused， you not install lsp ,you installed formatter,you can manual install lsp

**Comment by danjenson** [comment]
what do you mean by manually installing lsp?

**Comment by danjenson** [comment]
I have 3 lsp severs installed: 
![image](https://user-images.githubusercontent.com/4793438/180909876-31e25210-b55d-4f76-b6dd-5b4ba87703d7.png)

**Comment by tomasky** [comment]
ok ,your  lsp are installed , then see https://github.com/NvChad/NvChad/commit/26fc9b5a6ce811a020c096922152e6e845fd0a3a

**Comment by danjenson** [comment]
So, @siduck , it looks like you have to manually add servers to the lspconfig.lua file, while before they were automatically integrated with lsp-installer, and not necessary. This probably bears mentioning somewhere in the documentation.

**Comment by siduck** [comment]
> So, @siduck , it looks like you have to manually add servers to the lspconfig.lua file, while before they were automatically integrated with lsp-installer, and not necessary. This probably bears mentioning somewhere in the documentation.

https://nvchad.github.io/config/Lsp%20stuff#masonnvim
