### ISSUE TITLE
Status line problem

### ISSUE THREAD

**Issue by krypton612** [NvChad/NvChad#1375]
[DESCRIPCION]
I was calm programming, I saw a new update of nvchad and when I did packersync I started receiving this from statusline

La expresión no es válida: v:lua.require('plugins.configs.nvchad_ui').statusline()

[INFO]

neovim 7.2
terminal alacritty
operation system kali

**Comment by s5k** [comment]
I have the same problem here.

**Comment by siduck** [comment]
show how it looks, i dont understand spanish

**Comment by tomasky** [comment]
Oh, again the obviously not the latest version of NVChad

**Comment by siduck** [comment]
users must update nvchad before they make any issue. Also @LeonHeidelbach 's upcoming feature will make the snapshot feature much better i.e users will be able to compress whole nvchad config ( default config + custom config + all packer  plugins ) into one single minimized file!! :exploding_head:

**Comment by tomasky** [comment]
@siduck , We all know upgrade is not convenient
