### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by ConanEdogawa1** [NvChad/NvChad#1381]
**Describe the bug**
Error executing vim.schedule lua callback: Vim:E6100: "state" is not a valid stdpath stack traceback:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Mac OS 
 - iterm2 
 - 0.8.0

**Additional context**
      [C]: in function 'stdpath'
        ~/.config/nvim/lua/core/options.lua:107: in function ~.config/nvim/lua/co
re/options.lua:106>

**Comment by siduck** [comment]
@tomasky

**Comment by tomasky** [comment]
please update to latest neovim nightly

**Comment by javidrashid** [comment]
I get a similar error after the latest udate::::

@siduck 


Error executing vim.schedule lua callback: vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        /Users/path/to/file/.config/nvim/lua/core/utils.lua:80: in function 'set_maps'
        /Users/path/to/file/.config/nvim/lua/core/utils.lua:98: in function 'load_mappings'
        /Users/path/to/file/.config/nvim/init.lua:5: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by siduck** [comment]
@javidrashid use 0.7.2, problem solved

**Comment by siduck** [comment]
oh wait, thats a whichkey issue. check https://github.com/NvChad/NvChad/issues/1442

**Comment by javidrashid** [comment]
I guess it is which-key. But I also suspect these 2 as well

{ "folke/which-key.nvim" },
{ "folke/Autosave.nvim" },
 and

Pocco81/AutoSave.nvim
Pocco81/TrueZen.nvim

**Comment by siduck** [comment]
update nvchad config to the latest & do packersync

**Comment by javidrashid** [comment]
Yes PackerSync fails to update the above plugins

which-key, autosave and Truezen

**Comment by siduck** [comment]
> Yes PackerSync fails to update the above plugins
> 
> which-key, autosave and Truezen

rm -rf ~/.local/share/nvim
rm -rf ~/.config/nvim/plugin 

open nvim
