### ISSUE TITLE
Characters rendering on SignColumn

### ISSUE THREAD

**Issue by dkeithdj** [NvChad/NvChad#1382]
**Describe the bug**
characters render on SignColumn

**To Reproduce**
1. Do `<S-k>` or any mapping that shows a floating window

**Screenshots**
![characterRendering](https://user-images.githubusercontent.com/42316655/181160149-5616d791-b6f0-4254-a96d-adae9eab22af.gif)

**Desktop**
 - Operating System (Windows 10 - WSL)
 - Terminal (Windows Terminal Preview)
 - Version of Neovim (v0.8.0-dev)

**Comment by tomasky** [comment]
Maybe   related to neovim,try to :PackerSync and  upate to the latest neovim 0.8.        Maybe related to terminal

**Comment by dkeithdj** [comment]
Tried with Alacritty, bug didn't showed so probably the due to the terminal.
will downgrade to a previous version of Windows Terminal to test if bug still shows up

**Comment by dkeithdj** [comment]
closing issue
