### ISSUE TITLE
LSP problem

### ISSUE THREAD

**Issue by Skulek** [NvChad/NvChad#1388]
Operating system  - Mac OS Monterey 12.4
Terminal - Kitty
Neovim 0.7.2

Hello - first of all i want to say thank you for work on that project - im trying to make this vim as my new development environment after years working with vs code
However i have some problems with configuring the LSP :(
So my folder structure is that : 
![image](https://user-images.githubusercontent.com/9392321/181261321-a12b6bfa-93ea-4cb2-bfda-e207cfa87862.png)

My chadrc looks like this : 
![image](https://user-images.githubusercontent.com/9392321/181262204-c82b69ed-700b-4910-8795-1d4a6c5242ea.png)

and my plugins/lspconfig.lua looks like this : 
![image](https://user-images.githubusercontent.com/9392321/181262322-052ef6f1-e90f-4cdd-8b23-22da8f439472.png)

I see in mason that the servers are installed but if i go for example in the html / ts or other type of file - is not working as it should 
![image](https://user-images.githubusercontent.com/9392321/181262726-86b719cf-4ce0-42cd-a161-c0d238ff9c8b.png)

example in html file
![image](https://user-images.githubusercontent.com/9392321/181263198-92c3a460-2c9c-4c92-a0cc-f579ca07db7a.png)

![image](https://user-images.githubusercontent.com/9392321/181263353-415a95b2-196f-4c84-920b-200d97f72a1d.png)

Thanks for your time,
Regards

**Comment by tomasky** [comment]
read breaking changes page first .

**Comment by tomasky** [comment]
```lua

["neovim/nvim-lspconfig"] = {
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.plugins.lspconfig"
    end,
},
```

**Comment by Skulek** [comment]
I have this line of code like that in lua/customplugins/init.lua

![image](https://user-images.githubusercontent.com/9392321/181265785-093ed4de-0edb-472c-852e-2327dee74d93.png)

**Comment by siduck** [comment]
@Skulek  https://github.com/NvChad/NvChad/commit/26fc9b5a6ce811a020c096922152e6e845fd0a3a#commitcomment-79261675

**Comment by Skulek** [comment]
@tomasky  thanks for help - anyway I'm still strugling with it - I even tried to add setup in the lua/plugins/lspconfig - I've ended up with added new server in lsp but it still dosent work as should 

After whole day of configure - I feel like an idiot xD

**Comment by siduck** [comment]
@Skulek check my custom config for reference https://github.com/siduck/dotfiles/tree/master/nvchad/custom

**Comment by Skulek** [comment]
now works like charm - thanks for help! 
This config should be as a sample in documentation :D

**Comment by siduck** [comment]
@Skulek my config is just an example and the docs you see is comprised of my config, just read docs sequentially

**Comment by LeviBorodenko** [comment]
@Skulek I would be interested in knowing what you did to fix your issue. I am facing the same problem.

**Comment by Skulek** [comment]
@LeviBorodenko -  I've just copied the config provided from @siduck in the nvim folder and changed it to my personal settings and it works

**Comment by siduck** [comment]
@Skulek my config must be used as a reference, dont copy it as it is. Follow the docs :raised_hands:
