### ISSUE TITLE
CMP override

### ISSUE THREAD

**Issue by ternenges** [NvChad/NvChad#1393]
**Describe the bug**
I Have been trying to modify cmp mapping options and also add experimental.ghost_text but it's not working, I don't know why it isn't working 

**To Reproduce**

**Expected behavior**

**Screenshots**
here is my config
![issue1.png](https://user-images.githubusercontent.com/102123629/181418826-c790e773-d175-48ea-8817-3ac2a7adb5ca.png)

![issue2.png](https://user-images.githubusercontent.com/102123629/181418855-f1d436b5-66e2-41a6-8945-6adb7f22e86f.png)

**Desktop (please complete the following information):**
 - Zorin os 16.1 x86_64
 - Gnome terminal
 - 0.8.0-dev

**Additional context**

I edit the default config and set ghost_text it worked then disabled it from the override it also worked. 

I realized that for the option to work it must be defined in the default config.
this wasn't true in overriding tree sitter plugins.

But for the mappings I can't find a way around it. 

I have looked at it for about two days now.

**Comment by Artorius-P** [comment]
I got the same problem. My chadrc got an error when I just added require "cmp" in my chadrc without  any other change.

**Comment by siduck** [comment]
show your chadrc

**Comment by ternenges** [comment]
here is my chadrc 



![Screenshot_20220728_124635.jpg](https://user-images.githubusercontent.com/102123629/181497623-306b3d6b-afad-4821-b533-481e1183b7c4.jpg)

**Comment by siduck** [comment]
@ternenges i will look onto this when my health becomes okay :raised_hands:

**Comment by ternenges** [comment]
@siduck I pray 🙏 for your fast recovery God Bless

**Comment by ternenges** [comment]
@tomasky here ->[custom configs](https://github.com/ternenges/nvchad)

**Comment by tomasky** [comment]
what is this?
```lua
--init.lua
require "custom.lsp.services"

```

**Comment by tomasky** [comment]
@ternenges ,try this:

```lua
  mapping = cmp.mapping.preset.insert({
      ['<C-b>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.abort(),
      ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
```

**Comment by ternenges** [comment]
@tomasky still not working, I tested on my Android, I will test on my desktop when I get home.

**Comment by Artorius-P** [comment]
> @ternenges ,try this:
> 
> ```lua
>   mapping = cmp.mapping.preset.insert({
>       ['<C-b>'] = cmp.mapping.scroll_docs(-4),
>       ['<C-f>'] = cmp.mapping.scroll_docs(4),
>       ['<C-Space>'] = cmp.mapping.complete(),
>       ['<C-e>'] = cmp.mapping.abort(),
>       ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
>     }),
> ```

It works for me. Thank you.

**Comment by tomasky** [comment]
These should be relevant to cmp plugin, please read cmp plugin changelogs or readme.md

**Comment by ahhshm** [comment]
I also have the same problem with Telescope.

**Comment by tomasky** [comment]
@ahhshm  provide custom configs ,i can test it.

**Comment by ahhshm** [comment]
> @ahhshm provide custom configs ,i can test it.


```lua
M.plugins = {
  override = {
    ["nvim-telescope/telescope.nvim"] = {
      defaults = {
        mappings = {
          i = {
            ["<C-j>"] = require("telescope.actions").move_selection_next,
            ["<C-k>"] = require("telescope.actions").move_selection_previous,
          },
        }
      }
    },
}
```

**Comment by tomasky** [comment]
try this, `require` must be used in a method
 
```lua
["nvim-telescope/telescope.nvim"] = function()
     return { defaults = {
        mappings = {
          i = {
            ["<C-j>"] = require("telescope.actions").move_selection_next,
            ["<C-k>"] = require("telescope.actions").move_selection_previous,
          },
        }
      }
    }
end
```

**Comment by ahhshm** [comment]
@tomasky Yeah, that works. Thank you so much. Shouldn't this be somewhere in the docs?

**Comment by tomasky** [comment]
@siduck  This has been modified for a long time, maybe you forgot to add the document about overriding options using function

**Comment by siduck** [comment]
> @tomasky Yeah, that works. Thank you so much. Shouldn't this be somewhere in the docs?
@ahhshm 
![image](https://user-images.githubusercontent.com/59060246/181782003-ae803292-2f93-41ae-b7b0-20197449b531.png)

**Comment by ahhshm** [comment]
> > @tomasky Yeah, that works. Thank you so much. Shouldn't this be somewhere in the docs?
> 
> ![image](https://user-images.githubusercontent.com/59060246/181782003-ae803292-2f93-41ae-b7b0-20197449b531.png)

I'm blind then :)

**Comment by tomasky** [comment]
I skipped that too, but I think this should be emphasized ,
these codes maybe outdate
```lua
-- we use a function here as we are calling a moodule (cmp)
-- so the function needs to return a table!
M.cmp = function()
   local cmp = require 'cmp' 

   return {
       ["<C-d>"] = cmp.mapping.scroll_docs(-8),
    }
end
```

**Comment by siduck** [comment]
its not outdated :grinning:

**Comment by tomasky** [comment]
no i mean this maybe not working:
```lua
return {
       ["<C-d>"] = cmp.mapping.scroll_docs(-8),
    }
```

**Comment by siduck** [comment]
@tomasky it will work

**Comment by siduck** [comment]
agreed, i forgot the mapping table

**Comment by tomasky** [comment]
i dont know ,i  didn't test it, they just reported it didn't work, cmp`s readme example this:
```lua
 mapping = cmp.mapping.preset.insert({
      ['<C-b>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.abort(),
      ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
```

**Comment by siduck** [comment]
@tomasky according to our cmp setup this will work 

![image](https://user-images.githubusercontent.com/59060246/181789043-9d4c1440-b1a3-4b5c-8a1a-7cfad575b61d.png)

**Comment by tomasky** [comment]
a typo, module
-- we use a function here as we are calling a moodule (cmp)

**Comment by tomasky** [comment]
and I still think this should be listed separately

**Comment by siduck** [comment]
> and I still think this should be listed separately

fixed

**Comment by tomasky** [comment]
oh ,i mean ,Don't add them with comments, because  comments are easy to ignore

**Comment by siduck** [comment]
> oh ,i mean ,Don't add them with comments, because comments are easy to ignore

i had to explain it so users wont get confused

**Comment by ternenges** [comment]
> > @ternenges ,try this:
> > 
> > ```lua
> >   mapping = cmp.mapping.preset.insert({
> >       ['<C-b>'] = cmp.mapping.scroll_docs(-4),
> >       ['<C-f>'] = cmp.mapping.scroll_docs(4),
> >       ['<C-Space>'] = cmp.mapping.complete(),
> >       ['<C-e>'] = cmp.mapping.abort(),
> >       ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
> >     }),
> > ```
> 
> It works for me. Thank you.

@Artorius-P show me what you did , I want to know what am doing wrong

**Comment by Artorius-P** [comment]
@ternenges [here](https://github.com/Artorius-P/nvchad-custom/blob/main/custom/plugins/override.lua)

**Comment by siduck** [comment]
@ternenges still having this issue?

**Comment by ternenges** [comment]
yeah may I am doing it wrong, I don't understand why it not working. I have checked everything and it looks ok.

**Comment by siduck** [comment]
> yeah maybe I am doing it wrong, I don't understand why it not working. I have checked everything and it looks ok.

![image](https://user-images.githubusercontent.com/59060246/182033970-45d293f0-d559-4113-86bc-4b7e4f41eb6d.png)

i didnt see experimental option in cmp docs and if  u use only treesitter value in that list table here then cmp will use treesitter source, so you have to write all cmp sources ( from default config too ) + treesitter

**Comment by ternenges** [comment]
yes there left out few of the feature in the docs, but if you look in the source under views you will find experimental and views options there. thanks for the support

**Comment by ternenges** [comment]
my current sollution this is 
i added nvim-cmp to remove option  {...  "hrsh7th/nvim-cmp" ...}
then added it to my custom and modified it directly.
modifing it directing is the only method that worked for me.

**Comment by siduck** [comment]
ok tell me what are you trying to do so i can test here

**Comment by siduck** [comment]
this wont work unless you install it https://github.com/ray-x/cmp-treesitter

**Comment by siduck** [comment]
@tomasky i tested this issue and works fine here in one go so closing this 

![image](https://user-images.githubusercontent.com/59060246/182413673-e6dd925c-898d-474f-9039-ec516a2746f2.png)

**Comment by EricDuminil** [comment]
Sorry to bother you again on a closed issue.

If I understood correctly, the config structure changed since you posted the above screenshots.

I simply want to set `['<CR>'] = cmp.mapping.confirm({ select = false })`, but I have no clue in which file it should happen, and with which command.

Could you please help me?

**Comment by antoineco** [comment]
@EricDuminil here is an example:

`~/.config/nvim/lua/custom/plugins.lua`

```lua
local overrides = require "custom.configs.overrides"

---@type NvPluginSpec[]
local plugins = {
  {
    "hrsh7th/nvim-cmp",
    opts = overrides.cmp,
  },
}

return plugins
```

`~/.config/nvim/lua/custom/configs/overrides.lua`

```lua
local M = {}

-- Prevent error during the initial Lazy bootstrap:
--   Error detected while processing ~/.config/nvim/init.lua:
--   Failed to load `custom.plugins`
--   ~/.config/nvim/lua/custom/plugins.lua:1: loop or previous error loading module 'custom.configs.overrides'
local cmp_ok, cmp = pcall(require, "cmp")

if cmp_ok then
  M.cmp = {
    mapping = {
      ["<CR>"] = cmp.mapping.confirm { select = false },
    },
  }
end

return M
```

**Comment by EricDuminil** [comment]
@antoineco Excellent, thank you very much!

For reference, I've used

```
M.cmp = {
    completion = {
      completeopt = "menu,menuone,noselect,noinsert",
    },
  mapping = {
    ["<CR>"] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Insert,
      select = false,
    },
  },
}
```
in `overrides.lua`, and it behaves exactly like I wanted. Thanks!

**Comment by huix9527** [comment]
> @EricDuminil here is an example:
> 
> `~/.config/nvim/lua/custom/plugins.lua`
> 
> ```lua
> local overrides = require "custom.configs.overrides"
> 
> ---@type NvPluginSpec[]
> local plugins = {
>   {
>     "hrsh7th/nvim-cmp",
>     opts = overrides.cmp,
>   },
> }
> 
> return plugins
> ```
> 
> `~/.config/nvim/lua/custom/configs/overrides.lua`
> 
> ```lua
> local M = {}
> 
> -- Prevent error during the initial Lazy bootstrap:
> --   Error detected while processing ~/.config/nvim/init.lua:
> --   Failed to load `custom.plugins`
> --   ~/.config/nvim/lua/custom/plugins.lua:1: loop or previous error loading module 'custom.configs.overrides'
> local cmp_ok, cmp = pcall(require, "cmp")
> 
> if cmp_ok then
>   M.cmp = {
>     mapping = {
>       ["<CR>"] = cmp.mapping.confirm { select = false },
>     },
>   }
> end
> 
> return M
> ```

This is the way

**Comment by siduck** [comment]
@huix9527 imo this is better solution

i'd suggest doing it in the opts function of cmp plugin table itself

```lua
  {
    "hrsh7th/nvim-cmp",
    opts = function()
      local opts = require "plugins.configs.cmp"
      local cmp = require "cmp"

      opts.completion = {
        completeopt = "menu,menuone,noselect,noinsert",
      }

      opts.mapping["<CR>"] = cmp.mapping.confirm { select = false }

      return opts
    end,
  }
  ```

**Comment by CoreyCole** [comment]
@siduck any idea why `<C-S-j>` works for me, but not `<C-S-k>` for select_prev_item? (`<C-p>` works fine but prefer `<C-S-k>`)

EDIT: It was my terminal hotkey capturing before nvim
```lua
  {
    "hrsh7th/nvim-cmp",
    opts = function()
      local opts = require "plugins.configs.cmp"
      local cmp = require "cmp"
      opts.mapping["<C-S-k>"] = cmp.mapping.select_prev_item {}
      opts.mapping["<C-S-j>"] = cmp.mapping.select_next_item {}
      opts.mapping["<CR>"] = cmp.mapping.close {}
      opts.mapping["<Tab>"] = cmp.mapping.confirm {
        behavior = cmp.ConfirmBehavior.Insert,
        select = true,
      }
      table.insert(opts.sources, { name = "crates" })
      return opts
    end,
  },
```

**Comment by siduck** [comment]
> @siduck any idea why `<C-S-j>` works for me, but not `<C-S-k>` for select_prev_item? (`<C-p>` works fine but prefer `<C-S-k>`)
> 
> ```lua
>   {
>     "hrsh7th/nvim-cmp",
>     opts = function()
>       local opts = require "plugins.configs.cmp"
>       local cmp = require "cmp"
>       opts.mapping["<C-S-k>"] = cmp.mapping.select_prev_item {}
>       opts.mapping["<C-S-j>"] = cmp.mapping.select_next_item {}
>       opts.mapping["<CR>"] = cmp.mapping.close {}
>       opts.mapping["<Tab>"] = cmp.mapping.confirm {
>         behavior = cmp.ConfirmBehavior.Insert,
>         select = true,
>       }
>       table.insert(opts.sources, { name = "crates" })
>       return opts
>     end,
>   },
> ```

no idea! try with minimal nvim config
