### ISSUE TITLE
terminal exit to normal mode

### ISSUE THREAD

**Issue by rice-cracker-2234** [NvChad/NvChad#1399]
how do i exit from terminal to normal mode?

**Comment by tomasky** [comment]
see `nvchad/lua/core/mappings.lua`

   ["<C-x>"] = { termcodes "<C-\\><C-N>", "   escape terminal mode" },

**Comment by siduck** [comment]
@rice-cracker-2234 Ctrl x , then Ctrl h/j/k/l to move to your prefered window or mouse ig

**Comment by rice-cracker-2234** [comment]
ty

**Comment by tomasky** [comment]
@siduck  Why can't I see this mapping by `:map`

**Comment by siduck** [comment]
> @siduck Why can't I see this mapping by `:map`

that shows a long list, check properly

**Comment by tomasky** [comment]
not found

**Comment by tomasky** [comment]
not found

**Comment by siduck** [comment]
> not found

ig probably cuz its in terminal mode

**Comment by tomasky** [comment]
not found

> > not found
> 
> ig probably cuz its in terminal mode

What does this mean?

if i open terminal mode, how i exec :map

**Comment by siduck** [comment]
check if other terminal mode mappings can be seen in :map

**Comment by tomasky** [comment]
not see

**Comment by siduck** [comment]
yea its not our issue 

```
lua vim.keymap.set('n','1',":TESTINGGGGGGGGGGGGGGGGG",{})
lua vim.keymap.set('t','1',":TESTINGGGGGGGGGGGGGGGGG",{})
```
