### ISSUE TITLE
Consider chadtree?

### ISSUE THREAD

**Issue by archiif** [NvChad/NvChad#1407]
**Is your feature request related to a problem? Please describe.**
I had my nvim lock up when navigating up to a slightly large directory while nvim's RAM usage gradually grows larger and larger (>1GB) forcing me to crash it.

**Describe the solution you'd like**
The problem did not occur when I tried out [ms-jpq/chadtree](https://github.com/ms-jpq/chadtree). What do you think of just replacing the current nvim-tree with this? I would also like to hear any other more/equally performant solutions if there are any.

I also have problems integrating it with nvchad since it replaced bufferline with its own built-in package that hardcodes nvim-tree as the sidebar offset, so it would be nice if the configurability on that area can be improved.

**Comment by siduck** [comment]
not at all, nvimtree is much preferred. No plugins from ms-jpq will be added. The commit messages are a mess and it'll get less support cuz of that ( less contributors too) nvimtree is already fast. 

I'll add an option in tabufline config so u can use custom width for the offset

**Comment by siduck** [comment]
nvm no need to add another option for it, all you have to do is override default module ( coverNvimtree) in tabufline 

![image](https://user-images.githubusercontent.com/59060246/182031743-60f0dca7-04c6-4d7d-9ffb-3aa2c85b43f3.png)

**Comment by siduck** [comment]
overriding tabufline docs https://nvchad.github.io/config/nvchad_ui#tabufline
