### ISSUE TITLE
clangd vs null-ls - multiple different client offset_encodings

### ISSUE THREAD

**Issue by toothlesslizard** [NvChad/NvChad#1408]
```
❯ nvim --version      
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
```
warning: multiple different client offset_encodings detected for buffer, this is not supported
rted yet 
```
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/428
https://github.com/neovim/neovim/pull/16694

Can you please help how to correctly set buffer encoding in nvchad?

**Comment by siduck** [comment]
just add it in your custom lspconfig
