### ISSUE TITLE
Option overrides with string values not updating

### ISSUE THREAD

**Issue by wsphillips** [NvChad/NvChad#1409]
**Describe the bug**
Similar to #694 it seems that trying to override options with string values (in  `custom/init.lua`) does not work. Other overrides in the same file `custom/init.lua` file _do_ get evaluated and update (e.g. those with integer and boolean values, like `tabstop`). I assumed I may have made some kind of syntax error, but I've tried multiple permutations of the different options with no luck...

**To Reproduce**
In `custom/init.lua`, try to set the value of an option involving strings. I have also tried with alternate syntax and combinations of single options, etc like:

```lua
-- examples of variants tried (also with or without other string valued options, etc)...
vim.opt.whichwrap:remove "<>[]hl"
vim.opt.whichwrap:remove {"<>[]hl"}
vim.opt.whichwrap = vim.opt.whichwrap - {"<>[]hl"}
vim.opt.whichwrap = ""
```

**Expected behavior**
String valued options should update

**Screenshots**
Current (non-working) `custom/init.lua`:
![](https://user-images.githubusercontent.com/27030706/182056633-aba413a5-8b4e-4ba8-8280-7cd503d670db.png)

**Desktop (please complete the following information):**
 - Fedora
 - Alacritty
 - Neovim 0.7 release

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/182060760-dbae51c1-4340-4ea3-bbb1-52dd3621a851.mp4

works fine here

**Comment by wsphillips** [comment]
Found it: 

`set vim.opt.colorcolumn = 92` was causing it to error before finishing the file. Removing it makes it all work.

**Comment by tomasky** [comment]
if init.lua not works ,usually some lines are blocked

**Comment by siduck** [comment]
> if init.lua not works ,usually some lines are blocked

if there's an error in one line then the lines after it wont apply
