### ISSUE TITLE
E15: Invalid expression: v:lua.require('nvchad_ui').tabufline()

### ISSUE THREAD

**Issue by rhinoxi** [NvChad/NvChad#1413]
**Describe the bug**
opening a .go file, and switch too another one, and `:w`.
shows error:
```
"~/test/test.go" 0L, 0B written                                                                                                                                
...e/pack/packer/opt/ui/lua/nvchad_ui/tabufline/modules.lua:95: Invalid buffer id: 12                                                                          
stack traceback:                                                                                                                                               
^I[C]: in function 'nvim_buf_get_name'                                                                                                                         
^I...e/pack/packer/opt/ui/lua/nvchad_ui/tabufline/modules.lua:95: in function 'add_fileInfo'                                                                   
^I...e/pack/packer/opt/ui/lua/nvchad_ui/tabufline/modules.lua:121: in function 'styleBufferTab'                                                                
^I...e/pack/packer/opt/ui/lua/nvchad_ui/tabufline/modules.lua:161: in function 'bufferlist'                                                                    
^I...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:10: in function <...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:2>                  
E15: Invalid expression: v:lua.require('nvchad_ui').tabufline() 
```
and the `:ls!` not showing any buffer with id 12 

#1265 found this similar issue.
if I disable null-ls, everything is fine.
null-ls commit: 02b5971

**To Reproduce**
see screenshots below.

**Expected behavior**
no error on saving file.

**Screenshots**
https://user-images.githubusercontent.com/4988151/182320042-0af81bed-5142-4706-8e9d-08e8447ec8d1.mp4

**Desktop (please complete the following information):**
 - Operating System: macOS
 - Terminal: kitty 0.25.1
 - Version of Neovim: 0.7.2

Thanks.

**Comment by Kisto17** [comment]
Same issue here, just open 2+ files randomly and save any of them, or save before opening the second file, this happens. Turn off lazy load for tabufline make it even worse while it can happen when you save without opening the second file.
