### ISSUE TITLE
Statusline is drawn incorrectly on certain terminals

### ISSUE THREAD

**Issue by ParadoxialN3** [NvChad/NvChad#1416]
![2022-08-02_21-16](https://user-images.githubusercontent.com/77250276/182506628-7900d915-a8a1-4ddb-898c-09d72e823770.png)

On newest NvChad, the statusline is drawn incorrectly on certain terminals. It appears to be drawn incorrectly on Alacritty, Kitty, st, and Black Box from what I could test.

Nothing shows up in :checkhealth as incorrect and weird as it might be GNOME Terminal seems to be the only one that draws it without issue. 

 - Operating System- Fedora 36
 - Terminal- Alacritty (rest mentioned above)
 - Version of Neovim-7.2

**Comment by ParadoxialN3** [comment]
I should also probably mention I am using JetBrainsMono Nerd Fonty so it isn't a nerd fonts issue.

**Comment by siduck** [comment]
not a nvchad issue

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/182509355-ff52bc34-3f8b-4686-a859-6f1bccf2c540.png)

looks like you are using Jetbrainsmono Nerd Font Mono

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/182509452-fb2b0498-10d0-4c03-ac6d-7ac2dd5915c9.png)

st

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/182510323-d786fd9f-c17c-4983-8c75-08f295c2564a.mp4

with kitty it works by default, alacritty with proper config works too

**Comment by htcosta** [comment]
Just set your font offset to 0.

eg:

```bash
font:
  normal:
    family: UbuntuMonoNerdFont
    style: Regular
  size: 14
  offset:
    x: 0
    y: 0
```
