### ISSUE TITLE
LSP not working on start, need to restart it on every file open

### ISSUE THREAD

**Issue by tushargoyalofficial** [NvChad/NvChad#1418]
**Describe the bug**
Most of the time I work with React/React Native. So, majorly I open tsx, ts, files. I also work on Deno projects as well. Whenever I open any file, it opened with all errors (I will be providing the screenshot). But when I restart LSP, they all got sorted and all LSP related stuff also starts working. But this I have to do for all files I am opening in same window. This started happen with recent updates

**Expected behavior**
LSP should start by detecting the file type while opening a file

**Screenshots**
![Screenshot from 2022-08-03 13-51-59](https://user-images.githubusercontent.com/24288879/182571425-e101b9de-1212-492a-b9fb-a9f38cf1e61e.png)
![Screenshot from 2022-08-03 14-36-32](https://user-images.githubusercontent.com/24288879/182571433-02f2faa9-90a0-47d5-95c8-6d048349fcab.png)

**Desktop (please complete the following information):**
 - Manjaro (Gnome Edition)
 - Kitty
 - 0.7.2

**Additional context**
My custom config dot files repo link:
https://github.com/tushargoyalofficial/nvim-dotfiles/tree/master/.config/nvim/nvchad/custom

**Comment by tomasky** [comment]
the lsp error report maybe normal ,because tsx filetype will call `tsserver` lsp, and i dont see your node_modules dir.
check :LspInfo

**Comment by tomasky** [comment]
your problem maybe should why the lsp server report lint errors and these lint errors disappear  after :lsprestart

**Comment by siduck** [comment]
not a nvchad issue, your cwd needs to match the root_pattern needed by the lsp server. Check tsserver's root_dir in lspconfig repo
