### ISSUE TITLE
Replace built-in plugins with a fork using Packer

### ISSUE THREAD

**Issue by archiif** [NvChad/NvChad#1419]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to have a quick temporary fix of some bug in a built-in plugin by either using someone's fork or my own. If the commit I want is made on the main repository but in a separate branch, I can just select that branch by using Packer. But there's no easy way to switch to entirely different repositories with Packer.

**Describe the solution you'd like**
Some configuration method to override the repository URL of a built-in plugin using Packer.

**Describe alternatives you've considered**
I guess I can just overwrite the repository folder in `nvim-data`, but that's not very clean.

**Comment by siduck** [comment]
https://nvchad.github.io/config/plugins#modify-plugin-definition-options just modify the branch here

**Comment by archiif** [comment]
@siduck
Yes, like I said you can modify the branch that way, but what if you want to replace `official/plugin.nvim` with `fork/plugin.nvim`. As far as I know there's no Packer option for this.

**Comment by siduck** [comment]
@archiif remove that `official/plugin.nvim` then! the remove table is useful for this and then put fork plugin into your custom plugins ,simple
