### ISSUE TITLE
Lspconfig issues

### ISSUE THREAD

**Issue by lucazz** [NvChad/NvChad#1420]
**Describe the bug**
I've just made the switch from my custom lua-based neovim config to nvchad and am now configuring LSP in it. 
When I open nvim, I get the following error message:
```
packer.nvim: Error running config for nvim-lspconfig: ...as.saboya/.config/nvim/lua/plugins/configs/lspconfig.lua:8: module 'nvchad_ui.lsp' not found:
^Ino field package.preload['nvchad_ui.lsp']
^Ino file './nvchad_ui/lsp.lua'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/nvchad_ui/lsp.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad_ui/lsp.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad_ui/lsp/init.lua'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/nvchad_ui/lsp.lua'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/nvchad_ui/lsp/init.lua'
^Ino file '/Users/lucas.saboya/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvchad_ui/lsp.lua'
^Ino file '/Users/lucas.saboya/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvchad_ui/lsp/init.lua'
^Ino file '/Users/lucas.saboya/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvchad_ui/lsp.lua'
^Ino file '/Users/lucas.saboya/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvchad_ui/lsp/init.lua'
^Ino file './nvchad_ui/lsp.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad_ui/lsp.so'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/nvchad_ui/lsp.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/Users/lucas.saboya/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvchad_ui/lsp.so'
^Ino file './nvchad_ui.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad_ui.so'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/nvchad_ui.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

What am I missing here, folks? 🤔 

**To Reproduce**
1. [Here's my custom configs](https://github.com/lucazz/dotfiles/tree/51fb288aed542e01751656b8e5ef2b3932db05af/nvim/custom)
5. Open neovim
6. See the error

**Expected behavior**
Neovim boots up

**Screenshots**
<img width="1800" alt="Screen Shot 2022-08-03 at 17 18 26" src="https://user-images.githubusercontent.com/6126301/182702314-78333018-4777-4f4f-9fcc-a061bdae9965.png">

**Desktop (please complete the following information):**
 - Operating System: macOS Monterey version 12.5
 - Terminal: alacritty 0.10.1 (2844606) 
 - Version of Neovim: 
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```

**Comment by lucazz** [comment]
Better yet, here are all my custom configs: 
https://github.com/lucazz/dotfiles/tree/master/nvim/custom

**Comment by siduck** [comment]
update nvchad and do packersync then reopen nvim

**Comment by lucazz** [comment]
Hello there, @siduck thanks for the help!
I did as you suggested: 

1. Updated nvchad w/ `:NvChadUpdate`:
<img width="711" alt="Screen Shot 2022-08-04 at 10 18 31" src="https://user-images.githubusercontent.com/6126301/182857034-32c06d15-3df6-4d05-82e9-0a74543447eb.png">
2. Synced packer packages w/ `:PackerSync`:
<img width="972" alt="Screen Shot 2022-08-04 at 10 18 50" src="https://user-images.githubusercontent.com/6126301/182857154-efe4216c-db28-4d19-b052-84ec71097422.png">
3. And re-opened Neovim, but I still get the same error message:
<img width="1670" alt="Screen Shot 2022-08-04 at 10 19 00" src="https://user-images.githubusercontent.com/6126301/182857265-c742f342-e894-478b-8111-2cdae1cbab3d.png">

Here's the output of `:checkhealth`, if it helps:
https://gist.github.com/lucazz/66ecc50a9a0e776433be32fcb3680bfa

**Comment by lucazz** [comment]
Interesting:
```
~  ❯❯❯ rm -rfv ~/.config/nvim/                                                                                                                               28ms
/Users/lucas.saboya/.config/nvim//init.lua
[...]
/Users/lucas.saboya/.config/nvim/
~  ❯❯❯ rm -rfv ~/.local/share/nvim/
/Users/lucas.saboya/.local/share/nvim//shada/main.shada
[...]
/Users/lucas.saboya/.local/share/nvim//site
/Users/lucas.saboya/.local/share/nvim//rplugin.vim
/Users/lucas.saboya/.local/share/nvim/
~  ❯❯❯ git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
~  ❯❯❯ ln -s ~/.dotfiles/nvim/custom/ ~/.config/nvim/lua/custom/
~  ❯❯❯ ls -lhart ~/.config/nvim/lua                                                                                                                          20ms
total 0
drwxr-xr-x   9 lucas.saboya  staff   288B Aug  4 11:02 core/
drwxr-xr-x   4 lucas.saboya  staff   128B Aug  4 11:02 plugins/
drwxr-xr-x  11 lucas.saboya  staff   352B Aug  4 11:02 ../
lrwxr-xr-x   1 lucas.saboya  staff    42B Aug  4 11:03 custom@ -> /Users/lucas.saboya/.dotfiles/nvim/custom/
drwxr-xr-x   5 lucas.saboya  staff   160B Aug  4 11:03 ./
~  ❯❯❯   
```

The first time it boots, it  boots just fine, as soon as I link in my custom files, the error pops back up: 
<img width="1800" alt="Screen Shot 2022-08-04 at 11 04 33" src="https://user-images.githubusercontent.com/6126301/182866939-954c70f4-4213-4b4e-8b6b-558cc4c44a28.png">

**Comment by siduck** [comment]
@lucazz leader cm, show the output!

**Comment by lucazz** [comment]
Here you go: 
<img width="1800" alt="Screen Shot 2022-08-04 at 14 08 49" src="https://user-images.githubusercontent.com/6126301/182910042-cab88e92-f12b-4654-a98f-f415b9bed659.png">

**Comment by lucazz** [comment]
My bad, you're probably looking for the out put of `<leaderr>cm` at `~/.config/nvim/`, right:
<img width="1800" alt="Screen Shot 2022-08-04 at 14 09 34" src="https://user-images.githubusercontent.com/6126301/182910182-9ec360a4-acf8-4e98-8410-94c80c808e9b.png">

**Comment by siduck** [comment]
ok now show steps to reproduce this! does this happen with vanilla nvchad ( just enable alpha directly in default plugins section )

**Comment by lucazz** [comment]
I've done the following: 
```
$ rm -rfv ~/.config/nvim
$ rm -rfv ~/.local/share/nvim
$ git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
$ git clone https://github.com/lucazz/dotfiles.git ~/.config/foo
$ ln -s ~/.config/foo/nvim/custom/ ~/.config/nvim/lua/custom
$ nvim +MasonInstallAll
$ nvim +PackerSync
$ nvim +PackerSync
```

Without my custom configs, vanilla nvchad works as expected, no errors. 
Enabling alpha also works w/o my overrides. 

I just don't know what in my custom files might be causing this.

**Comment by lucazz** [comment]
It's not related to alpha, actually.`nvim ~/.config/foo/nvim/custom/init.lua` also renders the same error: 
<img width="1800" alt="Screen Shot 2022-08-04 at 14 18 59" src="https://user-images.githubusercontent.com/6126301/182912021-19eeec7d-a859-4438-a7a6-6cbc265de911.png">

**Comment by siduck** [comment]
show your custom config ( git repo )

**Comment by lucazz** [comment]
There you go: 
https://github.com/lucazz/dotfiles/tree/master/nvim/custom

**Comment by siduck** [comment]
i dont see any shady stuff in it, can you try my custom dir
[custom.zip](https://github.com/NvChad/NvChad/files/9261899/custom.zip)
?

**Comment by lucazz** [comment]
yep, let me try that

**Comment by lucazz** [comment]
Your custom seem to work like a champ, let me try and iterate over yours merging my stuff in one step at a time.

**Comment by lucazz** [comment]
There you go, @siduck this works: 
https://github.com/lucazz/dotfiles/tree/master/nvim/custom

One final thing: 
Is it possible to customize Alpha's buttons the same way you're customizing it's header?

**Comment by siduck** [comment]
no, you need to copy the buttons function and rewrite default buttons too, just adding your buttons will show only your buttons as the buttons table is a list and not a dict
