### ISSUE TITLE
WhichKey: Your <leader> key for "n" mode in buf 0 is currently mapped to "<Cmd> TbufPick <CR>". WhichKey automatically creates triggers, so please remove the mapping

### ISSUE THREAD

**Issue by AjayShanker-geek** [NvChad/NvChad#1423]
`vim.g.mapleader = "\\"`
Remap my leader key to `\`

When`\` is pressed, error showed is E492: Not an editor command: TbufPick 

But facing with this issue, I also tried disabling the mapping, but it is not working.

**Screenshots**

<img width="1728" alt="Screenshot 2022-08-04 at 11 34 52 PM" src="https://user-images.githubusercontent.com/26241915/182889903-2bdee5d5-ad33-4b32-af04-556de415b7b9.png">

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/182903570-ff4587ec-a33e-4965-b321-0a75a4867ee9.png)

disable this key first , its used for tbufpick

**Comment by AjayShanker-geek** [comment]
Thanks!
