### ISSUE TITLE
Nvimtree does not show git icons and does not open on setup

### ISSUE THREAD

**Issue by TanZng** [NvChad/NvChad#1424]
**Describe the bug**
nvimtree does not show git icons and does not open on setup

**To Reproduce**
1. Add these config to the custom chadrc.lua

```lua
M.nvimtree = {
   open_on_setup = true,
   git = {
      enable = true,
   },
   renderer = {
      highlight_git = true,
      highlight_opened_files = "none",
      icons = {
         show = {
           git = true,
         },
       },
   },
}
```

2. Open nvim <file> (the file should be tracked by git)
3. The tree did not opened
4. Open the tree
5. Git icons are not there

**Expected behavior**
When open the nvim tree should be open
The tree should show git icons in files

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Terminal: wezterm
 - Version of Neovim: v0.7.2

**Additional context**

**Comment by TanZng** [comment]
Using these as an example https://github.com/siduck/dotfiles/blob/18baf448e9382f85cf790e4de67ffffe13b247f7/nvchad/custom/override.lua#L21-L34 the git icons start working but the tree still dies not open_on_setup

**Comment by siduck** [comment]
@TanZng to load nvimtree on startup i.e making open_on-setup will only work when you disable lazyloading of nvimtree as its loaded on cmds . Just load nvimtree after web-devicons plugin

**Comment by TanZng** [comment]
oh okay, how I disable lazyloading of nvimtree? 😅 Adding just 
```lua
M.plugins = {
   override = {
      ["kyazdani42/nvim-tree.lua"] = {
          lazy_load = false,
...
}
```
did not work :c

**Comment by siduck** [comment]
because there's no lazy_load field in it lol

      ["kyazdani42/nvim-tree.lua"] = {
  after = "nvim-web-devicons",
}

**Comment by TanZng** [comment]
Awesome thank you :D!
