### ISSUE TITLE
LSP not working

### ISSUE THREAD

**Issue by zapatagustin** [NvChad/NvChad#1428]
-Updated nvchad to latest version

-Installed lsp servers

it works with lua, not for javascript/typescript and python

![1659714580 screensht](https://user-images.githubusercontent.com/77631596/183115797-7292d4f6-b0d8-4b8e-bbf7-a2d0de967091.png)

 - Arch Linux
 - Kitty terminal
 - Nvim 0.7.2-3

--This is my Mason.lua file:

local present, mason = pcall(require, "mason")

if not present then
  return
end

vim.api.nvim_create_augroup("_mason", { clear = true })
vim.api.nvim_create_autocmd("Filetype", {
  pattern = "mason.nvim",
  callback = function()
    require("base46").load_highlight "mason"
  end,
  group = "_mason",
})

local options = {
        ensure_installed = {
        -- lua stuff
        "lua-language-server",
        "stylua",

        -- web dev
        "css-lsp",
        "html-lsp",
        "typescript-language-server",
        "deno",
        "emmet-ls",
        "json-lsp",
        "tailwindcss-language-server",
        "json-lsp",
        "python-lsp-server",
        -- shell
        "shfmt",
        "shellcheck",
      }, -- not an option from mason.nvim

  ui = {
    icons = {
      package_pending = " ",
      package_installed = " ",
      package_uninstalled = " ﮊ",
    },

    keymaps = {
      toggle_server_expand = "<CR>",
      install_server = "i",
      update_server = "u",
      check_server_version = "c",
      update_all_servers = "U",
      check_outdated_servers = "C",
      uninstall_server = "X",
      cancel_installation = "<C-c>",
    },
  },

  max_concurrent_installers = 10,
}

options = require("core.utils").load_override(options, "williamboman/mason.nvim")

vim.api.nvim_create_user_command("MasonInstallAll", function()
  vim.cmd("MasonInstall " .. table.concat(options.ensure_installed, " "))
end, {})

mason.setup(options)

**Comment by siduck** [comment]
just installing the lsp server binaries wont help, please read lsp docs in our site :/

**Comment by zapatagustin** [comment]
I followed the wiki, installed the language servers and run the MasonInstallAll. Forgot to mention it, sorry.

**Comment by siduck** [comment]
> I followed the wiki, installed the language servers and run the MasonInstallAll. Forgot to mention it, sorry.

show your chadrc and custom lspconfig then

**Comment by HummingBird24** [comment]
I'm having the same issues. 

custom/chadrc.lua

```
M.plugins = {
   user = require "custom.plugins",
   options = {
		lspconfig = {
			setup_lspconf = "custom.plugins.lspconfig",
		},
	},
}

```
custom/plugins/init.lua

```
return {
["neovim/nvim-lspconfig"] = {
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.plugins.lspconfig"
    end,
},
 ["williamboman/mason.nvim"] = {
      ensure_installed = {
        -- lua stuff
        "lua-language-server",
        "stylua",

        -- web dev
        "css-lsp",
        "html-lsp",
        "typescript-language-server",
        "json-lsp",
        "tailwindcss-language-server"

        -- shell
      },
    },
}

```

custom/plugins/lspconfig.lua

```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local servers = { "html","clangd", "cssls", "tsserver", "tailwindcss"}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end

```

MacOS 12.5
nvim v0.7.2

**Comment by zapatagustin** [comment]
Ok, this is my chadrc.lua:

local M = {}

M.plugins = {
   user = require "custom.plugins",
   options = {
		LspConfig = {
			setup_lspconf = "custom.plugins.lspconfig.lua",
		},
	},
}

M.ui = {
  theme = "catppuccin",
}

lpsconfig.lua:

local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local servers = {
      -- web dev
    "css-lsp",
    "html-lsp",
    "typescript-language-server",
    "deno",
    "emmet-ls",
    "json-lsp",
    "tailwindcss-language-server",
    "json-lsp",
    "python-lsp-server",
    -- shell
    "shfmt",
    "shellcheck",
}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end

return M

and the init.lua (I don't have the mason.lua here, should i?)

return {
["neovim/nvim-lspconfig"] = {
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.plugins.lspconfig"
    end,
}}

**Comment by zapatagustin** [comment]
added the mason.lua import in init.lua. Not working unfortunately.

**Comment by siduck** [comment]
completely wrong 

![image](https://user-images.githubusercontent.com/59060246/183226831-1067a155-f286-46e9-b14a-ec0d230a8ea7.png)


you didnt even read the docs :/ , closing this

**Comment by HummingBird24** [comment]
@siduck I read the docs. I added the options part to see if that would get it to work after seeing someone post about it on reddit. Even without options, it still doesn't work. Thanks for the help though

Sorry @zapatagustin for highjacking your issue. Lmk if you ever get it working.

**Comment by siduck** [comment]
> @siduck I read the docs. I added the options part to see if that would get it to work after seeing someone post about it on reddit. Even without options, it still doesn't work. Thanks for the help though
> 
> Sorry @zapatagustin for highjacking your issue. Lmk if you ever get it working.

because the option you added were outdated, they were removed ages ago

**Comment by HummingBird24** [comment]
@siduck I understand that now. I didn't return `M` from chadrc so now it's working fine. Sorry to bug you. I know it's gotta be annoying answering the same type of issue over and over again but I appreciate all the work you've put into this. Only been messing around with Nvim for a few weeks now trying to migrate from VSCode and configs like this are extremely helpful.

@zapatagustin Remove the options property and everything that belongs to it from your M.plugins and you should be okay.

**Comment by siduck** [comment]
@HummingBird24 if you are really new to nvchad then please read all of the docs from start and sequentially (start from post-install)

**Comment by HummingBird24** [comment]
@siduck Gotcha will do
