### ISSUE TITLE
Custom chadrc for lspconfig not working

### ISSUE THREAD

**Issue by tornoda** [NvChad/NvChad#1429]
**Describe the bug**

Custom chadrc for lspconfig not working.

Here is my config .
Works in this way: 

![image](https://user-images.githubusercontent.com/22449307/183126823-86b56af8-dc04-428d-899f-f362a2e1073b.png)

But, not working in this user custom way:

lspconfig.lua
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/22449307/183127091-2269d791-5e15-48b1-98ef-90c70355a50c.png">

chadrc.lua
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/22449307/183127428-c945b7da-cf2e-4a93-9213-119361987d32.png">

**To Reproduce**
As you see above

**Expected behavior**
Custom config works instead of modifing the source code of chad.

**Screenshots**
As you see above

**Desktop (please complete the following information):**
 - Operating System
 Mac os 12.3.1
 - Terminal
 Alacritty
 - Version of Neovim
<img width="609" alt="image" src="https://user-images.githubusercontent.com/22449307/183128016-637178b6-b468-4066-9cca-a01325af72eb.png">

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/183227011-d0a1a62c-bf72-44a5-a587-4a3f77514f9d.png)

load default lspconfig's config first in the config function

**Comment by tomasky** [comment]
@tornoda  ,try this:
```lua
["neovim/nvim-lspconfig"] = {
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.plugins.lspconfig" -- notice here, must place here
    end,
},
```

**Comment by tornoda** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/183227011-d0a1a62c-bf72-44a5-a587-4a3f77514f9d.png)
> 
> load default lspconfig's config first in the config function

It works. 
Thank you.
