### ISSUE TITLE
[question] Why do we disable providers?

### ISSUE THREAD

**Issue by kagbodji** [NvChad/NvChad#1432]
**Is your feature request related to a problem? Please describe.**
It seems providers [are disabled by default](https://github.com/NvChad/NvChad/blob/main/lua/core/options.lua#L102). I'm using the python provider for one of [my plugins](https://github.com/SkyLeach/pudb.vim). I am running into a problem where it's not possible to re-enable them in custom config. I'd like to understand why they are disabled, and if there is a way to enable them in custom config.

My `custom/init.lua` has the following:
```lua
vim.g.python3_host_prog = "~/.pyenv/versions/nvim/bin/python3"
vim.g.loaded_python3_provider = 1
```

This does not work, and errors out. `checkhealth` reports the following:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/30058890/183251879-9e0dbe49-51f8-4d9a-a31f-02ded6c51428.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/30058890/183251923-fae8c184-6a49-4757-b66c-bb6dbd8883f6.png">

If I disable the default mapping (and the additional mapping I've added to custom), things work as expected:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/30058890/183252053-9932456f-6a46-4fe6-8eac-6c6998eb83ca.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/30058890/183252152-9e6f236c-431d-4aff-8422-c9e43d14a073.png">

**Describe the solution you'd like**
I would like the ability to configure which providers are enabled. Perhaps have a `default_providers` list that is only loaded if no override is defined?

**Describe alternatives you've considered**
I could fork and modify the core config to meet my needs, but I would rather sync with master and keep all my changes in `lua/custom`

**Additional context**
N/A

**Screenshot**
N/A

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/1417

**Comment by siduck** [comment]
@kagbodji we keep it disable as this is a language specific stuff, you can however enable them back. Read the issue above i linked!
