### ISSUE TITLE
Tapping space should not move should not move the cursor to the right when in normal mode

### ISSUE THREAD

**Issue by shaun-mathew** [NvChad/NvChad#1433]
Currently entering whichkey using the default leader key \<Space> and attempting to leave
whichkey using the \<Space> key again, moves the cursor forward two spaces in normal mode.
I believe it would be better if the cursor didn't move at all, i.e. vim's default functionality for \<Space>, which is moving the cursor 1 space to the right, should be mapped to a \<NOP>.

**Comment by siduck** [comment]
this is a whichkey issue, happens in lunarvim too. So this is more like an upstream issue, cant help with this
