### ISSUE TITLE
Message "Could not update NVChad/base64" while updateing via PackerSync

### ISSUE THREAD

**Issue by mcctuxic** [NvChad/NvChad#1436]
**Describe the bug**
When using PackerSync for updateing I got the above described message.

**To Reproduce**
Update via PackerSync

**Expected behavior**
I got the message described above.

**Screenshots**

**Desktop (please complete the following information):**
Gentoo (updated daily
 - wezterm
 - current

**Additional context**
I learned from here, that I had to remove "NVChad/base64" and PackSync again. But I can't find anything appropiate - neither in the user related directories nor in the system related directories of nvim/NVChad.

**Comment by siduck** [comment]
@mcctuxic maybe there were some force pushes on that repo, so delete that plugin locally and then do packersync ( basically a reinstall of that plugin )

**Comment by mcctuxic** [comment]
On 08/06 08:36, Sidhanth Rathod wrote:

...yes, I know that I have to remove that plugin. But I have problems to
figure out what plugin needs to be removed...(see initial post)

**Comment by siduck** [comment]
> On 08/06 08:36, Sidhanth Rathod wrote: ...yes, I know that I have to remove that plugin. But I have problems to figure out what plugin needs to be removed...(see initial post)
> […](#)
> @mcctuxic maybe there were some force pushes on that repo, so delete that plugin locally and then do packersync ( basically a reinstall of that plugin ) -- Reply to this email directly or view it on GitHub: [#1436 (comment)](https://github.com/NvChad/NvChad/issues/1436#issuecomment-1207324199) You are receiving this because you were mentioned. Message ID: ***@***.***>

nvchad/base46

**Comment by siduck** [comment]
your title says it all!

**Comment by mcctuxic** [comment]
...I cannot find that plugin on the filesystem,though...

**Comment by siduck** [comment]
> ...I cannot find that plugin on the filesystem,though...
> […](#)
> On 08/06 09:37, Sidhanth Rathod wrote: your title says it all! -- Reply to this email directly or view it on GitHub: [#1436 (comment)](https://github.com/NvChad/NvChad/issues/1436#issuecomment-1207329728) You are receiving this because you were mentioned. Message ID: ***@***.***>

~/.local/share/nvim/site/pack/packer/start/base46
