### ISSUE TITLE
accessing undefined variable 'vim'

### ISSUE THREAD

**Issue by charludo** [NvChad/NvChad#1439]
**Describe the bug**
Using the global `vim` inside of any configuration file results in a "accessing undefined variable 'vim'" warning

**To Reproduce**
1. open any `.lua` file

**Expected behavior**
No warning for this particular global

**Additional context**
This warning is supposed to be suppressed by `globals = { vim }` in the [lspconfig file](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/lspconfig.lua).

Could this be connected to the recent switch to Mason?

Overriding the relevant config in chadrc has no effect either.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/lspconfig.lua#L60

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/183293141-8b474b21-424c-4deb-82e8-57a6bfa74751.png)

i dont see such warnings btw

**Comment by charludo** [comment]
Yep, `lua-language-server` is installed and appears to be working. `:LspInfo` also shows sumneko_lua as configured and started.

If this is not an NvChad issue, I apologize and will keep digging for now.

**Comment by charludo** [comment]
Sorry if this is a dumb question, but do you get any warnings at all?

Reproducing the example config for [lsp](https://nvchad.github.io/config/Lsp%20stuff) and [formatting/linting](https://nvchad.github.io/config/Format%20&%20lint), I don't receive any lua warnings, only errors.

Enabling one (`luacheck` or `selene` in `null-ls` config) results in (slightly different) warnings about the variable (as well as all other warnings, of course)

**Comment by charludo** [comment]
OK, nevermind. I'm still not quite sure what's going on, but apparently I *do* get warnings, just not all of them (i.e. line too long).

I'm going to assume that's intentional. Sorry for bothering you, have a nice Sunday.

**Comment by siduck** [comment]
> Sorry if this is a dumb question, but do you get any warnings at all?
> 
> Reproducing the example config for [lsp](https://nvchad.github.io/config/Lsp%20stuff) and [formatting/linting](https://nvchad.github.io/config/Format%20&%20lint), I don't receive any lua warnings, only errors.
> 
> Enabling a diagnostics builtin (`luacheck` or `selene` in `null-ls` config) results in (slightly different) warnings about the variable (as well as all other warnings, of course)

yes i get warnings

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/183319498-bdcef03a-a947-4592-9832-f45ee3b2f07a.mp4
