### ISSUE TITLE
which key popup menu stopped working

### ISSUE THREAD

**Issue by qeisar** [NvChad/NvChad#1441]
**Describe the bug**
Leader key <space> doesn't trigger which key pop-up menu anymore.

**Desktop:**
 - Operating System: macOS
 - Terminal: iTerm
 - Version of Neovim: 7.2

**Additional context**
I kinda doubt this was intentional, but if it was, could show me how to bring it back? and feel free to close this issue.

**Comment by Gladox114** [comment]
[I found something suspicous.](https://github.com/NvChad/NvChad/blob/8cb28557a9a848d394f87ee6fe94c8de5802ebc1/lua/plugins/init.lua#L205)
Compared to my backup, this wasn't there and the setup function also.

But removing this line doesn't change anything except that Packer.nvim doesn't ask me anymore to remove cache files. But its still not loaded in when executing :PackerStatus

**Comment by qeisar** [comment]
Just found out that this was intentional and mentioned as a breaking change [here](https://github.com/NvChad/NvChad/issues/1386). 

One can re-enable by through custom config:

```
M.plugins = {
   user = {
      ["folke/which-key.nvim"] = {
         disable = false,
      },
   },
}
```
