### ISSUE TITLE
Creating which-key groups with latest update generates a warning message at  startup

### ISSUE THREAD

**Issue by shaun-mathew** [NvChad/NvChad#1442]
**Describe the bug**
Previously, I had defined which-key groups like so in NvChad (+Vim Options group).
![2022-08-07_22-48](https://user-images.githubusercontent.com/16690478/183328514-39d01b69-995b-46fc-b6b6-2cd4556507b1.png)

However, with the latest update, I get a warning when launching NvChad with which-key enabled with my old mappings.
![2022-08-07_22-42](https://user-images.githubusercontent.com/16690478/183328352-0d6fe770-69e0-4999-8de4-188253a0327d.png)

The mappings are still working; however, I'm assuming there is a different way to define custom which-key mappings with groups using NvChad now that doesn't throw a warning.

**Desktop (please complete the following information):**
 - Archlinux 5.18.14-arch1-1
 - Kitty
 - NVIM v0.8.0-dev-nightly-4-ge9b58a619

**Comment by siduck** [comment]
at the time we partially support whichkey.nvim,  temporarily you can just override whichkey config and define your groups there

**Comment by shaun-mathew** [comment]
Seems to have worked, thanks! For anyone else wondering how to do this, in your chadrc.lua file do something like this:
```lua
local pluginConfs = require "custom.plugins.configs"

M.plugins = {
  user = require "custom.plugins",
  override = {
    ["folke/which-key.nvim"] = pluginConfs.whichkey
  }
}

```
Then in your custom/plugins/configs file create a table with a whichkey entry that returns a function like so:

```lua
local M = {}

M.whichkey = function()
  local wk = require("which-key")
  wk.register({
    h =   {
      name = "Harpoon",
      h = {"<cmd>echo hi<cr>", "Test"}
    }
  }, {prefix = "<leader>"}) --insert any whichkey opts here
  return {}
end

return M
```
Returning an empty table here, since NvChad expects a table to be returned; although, returning an empty table might not be the best.

**Comment by siduck** [comment]
```lua
["folke/which-key.nvim"] = {
config = function()
         require "plugins.configs.whichkey"
         
         -- add your whichkey stuff here i.e make another file 
         
          local wk = require("which-key")
  wk.register({
    h =   {
      name = "Harpoon",
      h = {"<cmd>echo 'hi'<cr>", "Test"}
    }
  }, {prefix = "<leader>"}) --insert any whichkey opts here
end
```
