### ISSUE TITLE
Error message on startup after optional which-key update

### ISSUE THREAD

**Issue by breenbo** [NvChad/NvChad#1443]
Hello,

first thank you a lot for your awesome work, which allows me to have neovim as my daily IDE and completely wipe out Webstorm without any feature loss -> so good :-).
Second, sorry for my english.

Since the last update (on MacOS and Arch Linux), I have the error message below.
I use which-key (I have 3 error similar messages without it) with some custom key-bindings. The error message go away if I remove them (by commenting `M.mappings = require "custom.mappings.mappings"` in `custom/chadrc.lua`.
The weird thing is that my custom mappings is loaded despite this message...

Thank you again.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/19366502/183354777-36ab16f5-4d6f-4cc9-a68e-512d3a2ec0f5.png">

**Comment by siduck** [comment]
i think you have whichkey groups! 

check out this issue to set whichkey groups 

https://github.com/NvChad/NvChad/issues/1442

If you still face this issue then i'll open the issue up!

**Comment by breenbo** [comment]
Thanks for your quick response. 
I have indeed group in my mapping file (as explained in the docs). But the fix you pointed didn't work, and it's getting worse when I try to simply remove which-key, by non overwrite the disable=true -> I have the warnings 3 times instead of just one with which-key installed.

Thank you.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/19366502/183532380-ff81501b-4800-4c0e-8c06-8d1addec3973.png">

**Comment by siduck** [comment]
@breenbo  mapping groups were removed from the docs, so dont add them directly in your custom mappings section. Our mapping function doesnt support that syntax. 

check the issue i linked and do it in  your custom whichkey config itself

**Comment by breenbo** [comment]
It's working, thx again :-)
