### ISSUE TITLE
missing things?

### ISSUE THREAD

**Issue by umop3plsdn** [NvChad/NvChad#1447]
**Describe the bug**
upon intial install whichkey isn't responding with <leader> at all. Also, the dashboard isn't showing when opening either. 

**To Reproduce**
1. Go to '...' new install
2. Click on '....' new install
3. Scroll down to '....' new install

**Expected behavior**
the leader "Space" key to open whichkey

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 Arch 
 - Terminal
 Alacritty
 - Version of Neovim
Both dev nightly .8.0 and stable .7.0

**Additional context**

**Comment by umop3plsdn** [comment]
I mean Alpha is not loading when when I referred to dashboard

**Comment by shaun-mathew** [comment]
Whichkey and Alpha are disabled by default. In your chadrc.lua file,
you can override their disabled status to false, like so:

```lua
M.plugins = {
   override = {
     ["goolord/alpha-nvim"] = { disable = false },
     ["folke/which-key.nvim"] = { disable = false}
  }
}
```

**Comment by umop3plsdn** [comment]
is there anything else other than creating the custom directory and copying the example chadrc.lua into it and adding that snippet you included? For some reason it still didn't load.

**Comment by siduck** [comment]
> Whichkey and Alpha are disabled by default. In your chadrc.lua file, you can override their disabled status to false like so:
> 
> ```lua
> M.plugins = {
>    override = {
>      ["goolord/alpha-nvim"] = { disable = false },
>      ["folke/which-key.nvim"] = { disable = false }
>   }
> }
> ```

this is wrong, these must me put under custom plugins section and then do packersync

**Comment by LeviBorodenko** [comment]
I find this very confusing. For the end user it just looked like which-key suddenly stopped working. I.e. it seemed like something broke after updating.

So what is the intended way to use which-key? Are we supposed to install which-key as a custom plugin or simply enable it in some config?

**Comment by siduck** [comment]
> I find this very confusing. For the end user it just looked like which-key suddenly stopped working. I.e. it seemed like something broke after updating.
> 
> So what is the intended way to use which-key? Are we supposed to install which-key as a custom plugin or simply enable it in some config?

```lua
     ["folke/which-key.nvim"] = { disable = false }
```

in your custom plugins section and reopen nvim & do packersync
