### ISSUE TITLE
How to disable ui.statusline

### ISSUE THREAD

**Issue by shaun-mathew** [NvChad/NvChad#1448]
I'm trying to add a couple of statusline components to NvChad's statusline, but it doesn't seem to be possible
to do it without modifying core NvChad/ui files. I'd like to keep NvChad's base config untouched, so I've opted
for disabling the statusline plugin temporarily and using [feline](https://github.com/feline-nvim/feline.nvim) as my
statusline plugin for now. However, I can't seem to figure out how to disable the statusline plugin. I've tried
setting enabled to false, like it shows in the docs for tabufline, but that doesn't seem to work for me.

**Comment by siduck** [comment]
why do you want to not use inbuilt statusline btw? its the fastest of all , anyways put this under custom plugins section 

```lua

  ["NvChad/ui"] = {
    config = function()
      require("plugins.configs.others").nvchad_ui()
      vim.opt.statusline = ""
    end,
  },
  ```

**Comment by shaun-mathew** [comment]
How do I add new statusline components to the statusline? Also I was thinking of customizing winbar and feline let's you do this quite easily.

**Comment by siduck** [comment]
> How do I add new statusline components to the statusline? Also I was thinking of customizing winbar and feline let's you do this quite easily.

check the overriden_modules field of statusline 

https://nvchad.github.io/config/nvchad_ui#override-statusline-modules

**Comment by shaun-mathew** [comment]
This only allows me to modify existing modules (see returned table: https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/statusline/init.lua) or am I mistaken? I'm trying to add new modules.

**Comment by siduck** [comment]
yes, where are you trying to add the module? that example shows adding a module next to the `mode` module

**Comment by siduck** [comment]
oh wait i remember that winbar is not a statusline thing

statusline uses the statusline option : ```vim.opt.statusline```
winbar uses winbar option : ```vim.opt.winbar```

**Comment by siduck** [comment]
https://github.com/fgheng/winbar.nvim/blob/main/lua/winbar/winbar.lua#L129

**Comment by siduck** [comment]
ok u can either use feline.nvim or https://github.com/fgheng/winbar.nvim or wait till v0.8 of neovim then i'll add winbar support to our ui plugin, its no where related to the statusline plugin!

**Comment by saumyajyoti** [comment]
> why do you want to not use inbuilt statusline btw? its the fastest of all , anyways put this under custom plugins section , reopen nvim and do packercompile
> 
> ```lua
>   ["NvChad/ui"] = {
>     config = function()
>       require("plugins.configs.others").nvchad_ui()
>       vim.opt.statusline = ""
>     end,
>   },
> ```

Will it cause other statusline plugin to malfunction? Do we need to set any load order?

**Comment by siduck** [comment]
> > why do you want to not use inbuilt statusline btw? its the fastest of all , anyways put this under custom plugins section , reopen nvim and do packercompile
> > ```lua
> >   ["NvChad/ui"] = {
> >     config = function()
> >       require("plugins.configs.others").nvchad_ui()
> >       vim.opt.statusline = ""
> >     end,
> >   },
> > ```
> 
> Will it cause other statusline plugin to malfunction? Do we need to set any load order?

i dont think so
