### ISSUE TITLE
Multiple plugings not loaded like nvim-tree

### ISSUE THREAD

**Issue by kamalkech** [NvChad/NvChad#1449]
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:70: bad argument #1 to 'ipairs' (table expected, got string)                 
Please check your config for correctness

when tap ```nvim .``` should see navbar with all files but i can t see any thing
when i tap :NvimTreeToggle i get this error : 
```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:70: bad argument #1 to 'ipairs' (table expected, got string)                 
Please check your config for correctness
```

for packer status check this:
![image](https://user-images.githubusercontent.com/1313428/183541275-af0f7cc5-26d9-4146-b566-77b290151c02.png)

any idea to fixe those issues, NB i follow ur official documenation!

**Comment by siduck** [comment]
its normal, those plugins are lazy loaded. 

press Ctrl + n to open it

**Comment by siduck** [comment]
works fine
https://user-images.githubusercontent.com/59060246/183542177-8e01db4c-fba4-48fb-ae34-d06cda23df90.mp4

update nvchad and reopen nvim, run packersync. Reopen nvim

**Comment by kamalkech** [comment]
![image](https://user-images.githubusercontent.com/1313428/183542969-72722776-185e-4edd-afdd-271da3194bbf.png)

i follow "update nvchad and reopen nvim, run packersync. Reopen nvim"
but still not working and the question why few plugins still not loaded ??!!
![image](https://user-images.githubusercontent.com/1313428/183543410-64a8f407-9afb-4b11-a063-bf5d467e105e.png)

**Comment by siduck** [comment]
@kamalkech press Ctrl N

**Comment by siduck** [comment]
lazyloaded plugins wont be loaded from the start! simple

**Comment by kamalkech** [comment]
@siduck i know that s reason my question is how can fixe this issue :)

**Comment by siduck** [comment]
> @siduck i know that s reason my question is how can fixe this issue :)

you want to load nvim-tree on startup?

**Comment by siduck** [comment]
load it after ui plugin and enable that option in nvimtree ( open at setup )

**Comment by kamalkech** [comment]
@siduck i need to load all plugins because need theme, can u share documentation about to show how can update config of plugins and thank u for ur help

**Comment by siduck** [comment]
@kamalkech why do you want to load plugins at the start? its use-less. for example to open nvimtree you just have to press `Ctrl + n`

or :NvimTreeToggle

**Comment by kamalkech** [comment]
@siduck ok thank u
