### ISSUE TITLE
Why you skip loading mappings by default ?

### ISSUE THREAD

**Issue by ahhshm** [NvChad/NvChad#1450]
**Describe the bug**
I just updated NvChad and wired things are happening. First, when I ran `PackerSync` for the first time, it asked me if I wanted to remove `packer.nvim` and I said yes! I mean why it should ask me this question? Second, the mappings won't be loaded automatically. I don't understand why. You set `plugin = true` for every mapping section and then [skipped loading them](https://github.com/NvChad/NvChad/blob/01b17d2ad6d47008b27f38bff7fa490f56fae03f/lua/core/utils.lua#L102)! Why?

**Comment by siduck** [comment]
hm thats for lazyloading the mappings too, for example if a plugin gets disabled then its mappings get disabled too so we load mappings in the setup call of that plugin

**Comment by ahhshm** [comment]
Let's go through an example. `plugin=true` in the mapping section of the nvim-tree plugin. So the mappings should be loaded in the setup function of the plugin. This is the setup function:
```lua
setup = function()
   require("core.utils").load_mappings "nvimtree"
end,
```
I expect the `load_mappings` function to load all the mappings related to the nvim-tree plugin. But in the `load_mappings` function, you check for mapping sections that **don't** have `plugin=true` and load them:

```lua
local function set_mappings()
    for name, section in pairs(mappings) do
      -- skip mapping section with plugin=true
      if not lazyload_mappings_list[name] then
        --  load mappings
      end
  end
end
```
So the `nvim-tree` mappings won't be loaded. Am I correct?

**Comment by ahhshm** [comment]
Also, how should I load my non-plugin mappings? looks like they won't be loaded by default

**Comment by siduck** [comment]
> Also, how should I load my non-plugin mappings? looks like they won't be loaded by default

mappings without `plugin=true` will be loaded by default, no need to manually load them. Dont worry about it 

check the `add_mappingSection_toList` function above

**Comment by siduck** [comment]
nvimtree mapping work fine here tho
