### ISSUE TITLE
Default mappings aren't working

### ISSUE THREAD

**Issue by AlexNomadrg** [NvChad/NvChad#1451]
**Describe the bug**
mappings from lua/core/mappings.lua are not working

**To Reproduce**
1. install NvChad
2. cry

**Expected behavior**
mappings working

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System arch 5-18 gnu/linux
 - Terminal kitty
 - Version of Neovim NVIM v0.7.2

**Additional context**
my chadrc https://termbin.com/bgyt

**Comment by siduck** [comment]
they work, how slow are you pressing the mappings/

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/183632760-a1ce42d1-3ea8-411b-8226-044c2e8bc0e1.png)

require ' core.mappings' is invalid, you are supposed to give the path of your custom mappings, read the docs!

**Comment by AlexNomadrg** [comment]
ok thank you
