### ISSUE TITLE
lsp / misson others command

### ISSUE THREAD

**Issue by kamalkech** [NvChad/NvChad#1453]
i load plugin manually re-open nvim then cannot access to others command lsp like go to definition on another file ! probably i missing same thing ?!

![image](https://user-images.githubusercontent.com/1313428/183740679-5e4b11b0-df94-4b16-9b94-b786ce43976d.png)

![image](https://user-images.githubusercontent.com/1313428/183740338-5f88939a-1fae-42c2-abb8-00ce401a8655.png)

![image](https://user-images.githubusercontent.com/1313428/183740216-12bd45cc-bc76-4da2-94e2-691169e42356.png)

**Comment by siduck** [comment]
its useless to see lsp commands without a file opened and lspconfig plugin is loaded when there's a file in the buffer

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/183781876-2cb41da8-0e49-4775-8430-415d4c0c784a.mp4

**Comment by kamalkech** [comment]
@siduck its ok i have all what u share on this video but how can jump and open file class when hover on name class i try to use keymap "gd" but not working, example: 

![image](https://user-images.githubusercontent.com/1313428/183785682-759ba693-cb55-4042-8bd8-0c0b2ecdc687.png)

![image](https://user-images.githubusercontent.com/1313428/183785793-9b6bf07f-d252-48c7-8522-7706fee98f95.png)

**Comment by siduck** [comment]
thats because you dont have tsserver setup in your custom lspconfig :/ 

https://nvchad.github.io/config/Lsp%20stuff

**Comment by kamalkech** [comment]
![image](https://user-images.githubusercontent.com/1313428/183799133-d0b91c1a-c8a3-40e8-9deb-0fe7fcea11ea.png)

![image](https://user-images.githubusercontent.com/1313428/183800222-87536c37-70e9-4379-a6fa-bf62bb2b6e7d.png)

the documentation on ur official site not very clair :(

**Comment by kamalkech** [comment]
with all respect, cannot understand why u close

**Comment by siduck** [comment]
> with all respect, cannot understand why u close, but i found ur video youtube that s very clear https://www.youtube.com/watch?v=B-bK-FJ--H8 ;) thank man

the issue is closed because this isnt an issue. You wont see lspconfig related commands ( LspInfo, LspStart and so on ) if there is no file opened currently. Lspconfig loads when you open a file, this happens only for the first time

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/183806665-c7439537-0c91-4ca9-a6fc-831d78beaa8e.mp4

gd works fine in tsserver here btw
