### ISSUE TITLE
Go To Definition with OmniSharp

### ISSUE THREAD

**Issue by BButner** [NvChad/NvChad#1456]
**Describe the bug**
Go To Definition mapping not working with OmniSharp. I have OmniSharp up and running showing me errors/hints/etc, however using Go To Definition seems to just highlight the word I'm currently over?

**To Reproduce**
1. Setup LSP for OmniSharp
2. Open up a C# Project and attempt to use "gd" key map

**Expected behavior**
Goes to the definition

**Screenshots**
![image](https://user-images.githubusercontent.com/39167186/183968255-8468ced1-df5c-49a6-82e0-74ceb131b789.png)

**Desktop (please complete the following information):**
 - Windows
 - Windows Terminal
 - Neovim 0.7.2

**Additional context**
I'm still learning Vim/NeoVim, so solid chance I'm just doing something wrong. Any advice is appreciated! :)

**Comment by siduck** [comment]
show your lspinfo

**Comment by BButner** [comment]
> 

![image](https://user-images.githubusercontent.com/39167186/183976896-ebd3876a-cd5a-444a-92bd-98aaa84221f7.png)

**Comment by BButner** [comment]
@siduck I should have been more clear... It seems like its every mapping that's not working, not just gd.

**Comment by siduck** [comment]
@BButner if this happens with vanilla nvim then this isnt a nvchad issue!

**Comment by BButner** [comment]
> @BButner if this happens with vanilla nvim then this isnt a nvchad issue!

All the LSP mappings work fine if I open up Lua or TypeScript projects, seems to be just OmniSharp having issues with the bindings

**Comment by siduck** [comment]
https://github.com/neovim/neovim/issues/13827

**Comment by siduck** [comment]
https://www.reddit.com/r/neovim/comments/q1xvn1/lsp_go_to_definition_does_not_work_with_omnisharp/

**Comment by siduck** [comment]
so not a nvchad issue? :thinking:

**Comment by siduck** [comment]
Will port panda theme in nvchad 2.0 @BButner

**Comment by PoSayDone** [comment]
@BButner, how did you manage to set up omnisharp? LspInfo says that cmd is not defined, but I defined it in init.lua like nvim-lspconfig docs says. 
![image](https://user-images.githubusercontent.com/29358657/188267308-68852ed4-19a6-4f2e-8103-096ca28c615b.png)
![image](https://user-images.githubusercontent.com/29358657/188267334-612e9a71-29e6-4a33-93ad-3ea3b6a05992.png)
