### ISSUE TITLE
Mapping group names no longer work in the latest version

### ISSUE THREAD

**Issue by archiif** [NvChad/NvChad#1464]
**Describe the bug**
I like to have group names in my whichkey menu, but this longer works after NvChad switches to a plain `vim.keymap.set`

**To Reproduce**
Add this to your `mapping.lua`
```lua
local M = {}
M.map = {
  n = {
    ["<leader>"] = {
      f = {
        name = "+file",
        s = { "<cmd> w <CR>", "Save file" },
      },
    },
  },
}
return M
```

**Expected behavior**
Mapping group names should work.

**Desktop (please complete the following information):**
 - Windows 10
 - Wezterm
 - v0.8.0-dev-739-ge59bc078d

**Comment by siduck** [comment]
@archiif thats the wrong syntax, please check the mappings syntax in our docs and this https://github.com/NvChad/NvChad/issues/1442
