### ISSUE TITLE
Clone one tab file

### ISSUE THREAD

**Issue by kamalkech** [NvChad/NvChad#1472]
if tap :q or :bd all tab files closed, so my question how can i close one tab file using with shortcut like all IDE ?? thank u

![image](https://user-images.githubusercontent.com/1313428/184446658-36868718-ef89-4bdf-82ab-2b021c3d6e0b.png)

**Comment by doubleChu** [comment]
These "tabs" are actually "buffers" in vim, the default shortcut to close a buffer in NvChad is SPACE + x .

**Comment by siduck** [comment]
do leader x or make a command out of ```require("core.utils").close_buffer()`

**Comment by kamalkech** [comment]
@doubleChu leader(space) + x not working
@siduck which file need to add ```require("core.utils").close_buffer()``` ??

**Comment by kamalkech** [comment]
@doubleChu @siduck thank ;)

**Comment by gatspy** [comment]
> do leader x or make a command out of `require("core.utils").close_buffer()`

After closing, it turned out like this.

<img width="603" alt="image" src="https://github.com/NvChad/NvChad/assets/804446/887e6a6a-fc5d-4dae-b540-a3faf1048be4">

**Comment by siduck** [comment]
@gatspy what are u trying to do!
