### ISSUE TITLE
NvimTree / Open by default

### ISSUE THREAD

**Issue by kamalkech** [NvChad/NvChad#1477]
how can i configure to open by default navbar nvimtree, i mean run comment :NvimTreeOpen when tap nvim.

I propose to create a discord account to post all questions instead create tasks here :), thank u ;)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/184560085-d5af4ce6-efaf-4d66-ad7a-f48e6215d5e4.png)

join our communties here!

**Comment by siduck** [comment]
enable open_on_setup option in nvimtree config (override default nvimtree config) and make nvimtree load after the ui plugin
