### ISSUE TITLE
'MasonInstallAll' command does not work

### ISSUE THREAD

**Issue by imkasen** [NvChad/NvChad#1483]
## Problem

Today I clean and reinstall NvChad on Debian11, and it seems that the custom configuration of `mason.nvim` can't be loaded. When I run `MasonInstallAll`, only `lua-language-server` will be installed which is in the default configuration.

## My Configuration

``` Lua
-- custom/chadrc.lua
local M = {}
local override = require "custom.plugins.override"
M.plugins = {
    override = {
        -- ...
        ["williamboman/mason"] = override.mason,
    },
    -- ...
}
-- ...
return M
```

``` Lua
-- custom/plugins/override.lua
local M = {}
-- ...
M.mason = {
    ensure_installed = {
        "bash-language-server",
        "clangd",
        -- ...
    },
}
-- ...
return M
```

**Comment by siduck** [comment]
because mason is not the plugin name :/ its mason.nvim
