### ISSUE TITLE
lua error on loading python file

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1486]
**Describe the bug**
i am facing following errors in nvim on loading a python file and toggling sidebar (nvim tree ig) respectively what should i do

**Screenshots**
on loading python file

![nvim_error](https://user-images.githubusercontent.com/78728701/185418717-f39ff3f5-6d9f-46db-ab87-97081a203f4e.png)

on toggling sidebar
![nvim](https://user-images.githubusercontent.com/78728701/185418827-c8b233a8-4c8e-4641-9bfe-4b4a091955ca.png)

 
**Desktop (please complete the following information):**
 - Operating System Manjaro linux
 - Terminal kitty
 - Version of Neovim

**Comment by siduck** [comment]
please update nvchad and then reopen nvim, do packersync. Reopen nvim
