### ISSUE TITLE
NvChad tree icons not work

### ISSUE THREAD

**Issue by mmsaeed509** [NvChad/NvChad#1494]
after updating NvChad, the NvChad tree work without icons

![Screenshot_2022-08-20-06-42-59_3840x1080](https://user-images.githubusercontent.com/62524855/185757713-24849547-3197-412c-a8b2-11883dfde6c3.png)
 
how to make the NvChad tree looks like that permanently

![Screenshot_2022-08-20-06-41-13_3840x1080](https://user-images.githubusercontent.com/62524855/185757771-86ac5d9c-f549-4d01-8c0c-2c879d65ab1f.png)

**Comment by siduck** [comment]
its your terminal issue, not a nvchad issue! We didnt even made any changes to the folder icon since ages. I hope you are not using iterm :/
