### ISSUE TITLE
Need help on setting flutter-tools plugin with lspconfig

### ISSUE THREAD

**Issue by esperaking81** [NvChad/NvChad#1495]
Hello !
I love NvChad.
It's been weeks since I'm trying to set it up with flutter-tools. 

The plugin works but I can't use lspconfig on_attach and capabilities in flutter-tools.setup() function.

How can I do that ?

**Comment by siduck** [comment]
use our on_attach capabilities from the default lspconfig.lua

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/185769771-dbfdda73-d56c-4d1a-9349-e456d5430761.png)

these

**Comment by esperaking81** [comment]
Hello !
Thanks for your swift response !

I've tried that before and got this in my custom/plugins/configs/flutter-tools.lua file
`Error running config for flutter-tools.nvim: ...attempt to index a boolean value.`

Thanks for helping me @siduck

**Comment by esperaking81** [comment]
Never mind @siduck, I was the one doing it wrong all that time.
In my flutter-tools.lua file, I was declaring the variables directly inside the file instead of declaring them in the flutter_tools.setup = function()...end scope.

But still, gD or K mappings are not working on a flutter dart file. Well, I'll look into that.

Lua is amazing, and NvChad with it!

**Comment by barungh** [comment]
This worked for me 👇🏻  @esperaking81 
![Screenshot 2022-08-21 102625](https://user-images.githubusercontent.com/12285528/185776478-e3610892-6fc7-44a6-91d3-1c407175ac1d.jpg)

**Comment by esperaking81** [comment]
Hello @barungh 
Thanks for helping out !

Can I see what your custom.lspconfig looks like ?
I can get the plugin to work. 
I just don't have lsp capabilities like go to definition, type definition, hover for documentation and so on...

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/185792825-1e5c4447-92ab-43e0-8cce-a9df8ba6c719.png)

this is completely wrong

**Comment by siduck** [comment]
https://nvchad.github.io/config/Lsp%20stuff

**Comment by siduck** [comment]
> Hello ! Thanks for your swift response !
> 
> I've tried that before and got this in my custom/plugins/configs/flutter-tools.lua file `Error running config for flutter-tools.nvim: ...attempt to index a boolean value.`
> 
> Thanks for helping me @siduck

show your custom folder ( put it in a github repo so it gets easy for me)

**Comment by esperaking81** [comment]
I've been able to deal with it.
I had to add `after = "nvim-lspconfig"` to flutter-tools plugin definition to get it working.

I pushed my configs on my repo at [https://github.com/esperaking81/nvchad-configs.git](Personal NvChad Configs) for anyone else to see if needed.

@siduck If you allow so, I'll try to add something on the docs to help someone else in the future. It may seems funny, but it really took me some days to get this working.

I hope one day I'll be able to build for neovim too.

**Comment by siduck** [comment]
@esperaking81 thats easy! i didnt properly know that flutters.nvim is a lsp related plugin or i'd help you right away. LSP related plugins need to be loaded after lspconfig plugin, The same way we load null-ls after lspconfig ( this is mentioned in the docs too )

**Comment by esperaking81** [comment]
Alright, I'll try to be better understand the docs next time.
Thanks for your valuable time.

I was wondering, should I use those custom on_attach and capabilities on flutter-tools.nvim or just properly setup null-ls or do both ?

I am a little bit confused.

**Comment by siduck** [comment]
@esperaking81  yes use the same on_attach , capabilities provided in our default lspconfig 

as per fluttertoools docs

![image](https://user-images.githubusercontent.com/59060246/185796133-e8b13fa4-e771-4424-8294-c2402e91bebb.png)

**Comment by barungh** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/185792825-1e5c4447-92ab-43e0-8cce-a9df8ba6c719.png)
> 
> this is completely wrong

![image](https://user-images.githubusercontent.com/12285528/185796320-ec7fe9aa-d3ae-4091-b27d-853ee822d650.png)

This is what is instructed in documentation, 
also in one of your instructional screencast

**Comment by barungh** [comment]
> I've been able to deal with it. I had to add `after = "nvim-lspconfig"` to flutter-tools plugin definition to get it working.
> 
> I pushed my configs on my repo at [Personal NvChad Configs](https://github.com/esperaking81/nvchad-configs.git) for anyone else to see if needed.
> 
> @siduck If you allow so, I'll try to add something on the docs to help someone else in the future. It may seems funny, but it really took me some days to get this working.
> 
> I hope one day I'll be able to build for neovim too.

Dosen't *flutter-tools* docs says that it does not depend on nvim-lspconfig ?

also last year when I was setting up the this plugin, I came to know that everything is lazy loaded so removed a line

[read that here](https://github.com/NvChad/NvChad/issues/335)

**Comment by esperaking81** [comment]
It doesn't depend on nvim-lspconfig. We are using exported on_attach and capabilities from lspconfigs here. And because nvim-lspconfig is lazy_loaded, we need that **after** line in flutter-tools to make sure that nvim-lspconfig is called before we try to make use of on_attach and capabilities.

**Comment by barungh** [comment]
Got it @esperaking81 

Haven't worked on Flutter for a while, I think I need to update my config

Thanks for sharing your config

My config is in Github , but not updated for Flutter , 
so didn't feel right to share 😑

**Comment by esperaking81** [comment]
It's fine.
Thanks y'all !

**Comment by aeke** [comment]
> I've been able to deal with it. I had to add `after = "nvim-lspconfig"` to flutter-tools plugin definition to get it working.
> 
> I pushed my configs on my repo at [Personal NvChad Configs](https://github.com/esperaking81/nvchad-configs.git) for anyone else to see if needed.
> 
> @siduck If you allow so, I'll try to add something on the docs to help someone else in the future. It may seems funny, but it really took me some days to get this working.
> 
> I hope one day I'll be able to build for neovim too.

Thank you @esperaking81 
Your config solved my problem.

**Comment by esperaking81** [comment]
You are welcome @aeke . Happy to help
