### ISSUE TITLE
Error while calling lua chunk autocmd error

### ISSUE THREAD

**Issue by Xolo-Gamerz** [NvChad/NvChad#1496]
**Describe the bug**
After cloning the repo and starting nvim the error shows up
```lua
Error detected while processing /home/xolo/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/xolo/.config/nvim/lua/core/init.lua:16: attempt to call local 'autocmd' (a nil value)
stack traceback:
        /home/xolo/.config/nvim/lua/core/init.lua:16: in main chunk
        [C]: in function 'require'
        /home/xolo/.config/nvim/init.lua:5: in main chunk
Press ENTER or type command to continue
```

**To Reproduce**
1.Clone the repo
2.Start nvim

**Expected behavior**
The error shouldnt occur

**Screenshots**
![image](https://user-images.githubusercontent.com/90712689/185774522-772e21ab-b288-447d-9038-cbce2053f8f1.png)

**Desktop (please complete the following information):**
 - WSL2 Ubuntu 22.0.4
 - Windows Terminal
 - Latest

**Comment by Jawny** [comment]
having the same issue

**Comment by siduck** [comment]
use neovim v0.7.2
