### ISSUE TITLE
extend /example to show common tasks

### ISSUE THREAD

**Issue by lantos-lgtm** [NvChad/NvChad#1497]
**Is your feature request related to a problem? Please describe.**
Following documentation on the website is not 100% clear on how to setup nvchad

**Describe the solution you'd like**
extend the example in the example folder in the github to show how to do common tasks
- show how to add another plugin.
```lua
-- in example/chadrc.lua
M.plugins = {
  user = {
    ["wakatime/vim-wakatime"] = {},
  }
}
```
- show how to extend the lsp
```lua
-- in example/chadrc.lua
M.options = {
  lspconfig = {
     servers = { "html" }
  }
}
```
-- show how to extend keyboard mappings

**Describe alternatives you've considered**
I've been looking at google and searching chadrc.lua for other peoples chadrc files
follow the docs https://nvchad.github.io/config/Walkthrough
but it would be much easier to have an example that can follow using a folder structure. That will new users from 0 to 90% fairly quickly.

**Additional context**
- none

**Screenshot**
- none

**Comment by esperaking81** [comment]
I agree. If possible, a recipe section in the docs. 
I think I'll submit a pull request to add that if I am done configuring NvChad for flutter.

**Comment by siduck** [comment]
-- in example/chadrc.lua
M.options = {
  lspconfig = {
     servers = { "html" }
  }
}

this is totally wrong, please read lsp docs of ours

**Comment by siduck** [comment]
https://github.com/siduck/dotfiles/tree/master/nvchad/custom

will tidy up the docs after some time
