### ISSUE TITLE
Default leader key not working

### ISSUE THREAD

**Issue by Tylerwbrown** [NvChad/NvChad#1501]
**Describe the bug**
I've used nvchad before, and am using lunarvim atm, and haven't had issues with using space as the leader key. It usually pops up a set of bindings at the bottom, and still does in lunarvim, but doesn't in nvchad.

I uninstalled neovim and reinstalled it (I was on 0.7.0, and so I upgraded to 0.7.2 because I noticed that was in the requirements), and the behavior is the same. 

Interestingly, space+e does still open the file explorer, but no other space/leader bindings I've tried have worked.

I have also tried 3 different terminal emulators just to be sure it's not something weird with space not coming across properly, but it works in insert mode.

I have also tried it via the docker installation and the behavior is the same.

**To Reproduce**
1. Install neovim 0.7.2 (bob install 0.7.2)
2. Install nvchad via `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim` (PackerSync pulls everything down fine)
3. Go into nvim 
4. Space doesn't function as a leader key.

**Expected behavior**
Space to work as the leader key.

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - gnome terminal, kitty, hyper
 - zsh, bash
 - 0.7.2

**Comment by Tylerwbrown** [comment]
Oh, nevermind, I must've misremembered nvchad having `https://github.com/folke/which-key.nvim`, I've tried a few other leader keybindings, they just don't align with what I'm used to so normal things weren't working for me.

**Comment by Tylerwbrown** [comment]
Thought I figured it out but I didn't, here's a list of some bindings that don't work for what it's worth:

`space+u+k`
  - expected: view keymappings
  - actual: moves one space to the right, undoes the previous action, and goes up a line (standard vim bindings)

`shift+t`
  - expected: open a new buffer
  - actual: nothing
  
Some bindings do work though, namely
`space+f+f` - does properly bring up the find files panel
`space+/` - comments out the current line

**Comment by Tylerwbrown** [comment]
Here's my `:PackerStatus`
![image](https://user-images.githubusercontent.com/5498594/186045290-a833a2a0-72de-49f3-8d01-a74e6bdf2b56.png)

**Comment by siduck** [comment]
> I've used nvchad before, and am using lunarvim atm, and haven't had issues with using space as the leader key. It usually pops up a set of bindings at the bottom, and still does in lunarvim, but doesn't in nvchad.

Please check the pinned issue

**Comment by Patrick-web** [comment]
> Here's my `:PackerStatus` ![image](https://user-images.githubusercontent.com/5498594/186045290-a833a2a0-72de-49f3-8d01-a74e6bdf2b56.png)

Install which key
