### ISSUE TITLE
Discuss default mapping of `<S-b>`

### ISSUE THREAD

**Issue by dmonad** [NvChad/NvChad#1504]
Hi there,

thanks for this project! It got me excited to discard my old config and start fresh with awesome defaults :)

I wonder if remapping `B` to creating a new buffer was a mistake. I use the default mapping of `B` to jump over words quite extensively. Wouldn't it make more sense, conceptually, to use `<leader>-b` instead because `<leader>-x` is already used to close a buffer?

https://github.com/NvChad/NvChad/blob/4a5a927de8587c9c42e7a2dcac837956c411eaac/lua/core/mappings.lua#L61

I already found out how to disable this keymap, but I'm just curious about the intention of the default. If you are not open to discussing this just close this issue.

**Comment by siduck** [comment]
didnt know that it was a default mapping. Ok ive tried leader + b and its slow :c

**Comment by dmonad** [comment]
That's a very fair argument ^^

I guess the default mapping is gonna confuse a lot of users who learned  `:vimtutor:` and struggle to find out where this mapping was defined and how to best reset it (definitely not me :sweat_smile: ). So maybe just not make this a default mapping.

**Comment by siduck** [comment]
agreed, @Akianonymus @zbirenbaum @LeonHeidelbach any recommendations for the new keybind?

**Comment by Akianonymus** [comment]
Just remove it, lol.

use leader+b for this and change leadder+bc to leader+cc in core/mappings.lua

**Comment by siduck** [comment]
oh totally forgot about bc!
