### ISSUE TITLE
gitsigns.nvim not loading

### ISSUE THREAD

**Issue by tynguyen2k1** [NvChad/NvChad#1505]
**Describe the bug**
I just updated some recent changes then gitsigns not loaded, I don't know if it's because of packer.

**Expected behavior**
gitsigns loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/64082226/186236061-e65a66ff-ac9d-4f44-933f-a57e8429eb0d.png)

**Desktop (please complete the following information):**
 - Operating System: Arch
 - Terminal: Kitty
 - Version of Neovim: v0.7.2

**Additional context**
Default config

**Comment by lanc3r** [comment]
Same here

**Comment by lucario387** [comment]
For now, please go inside `core/lazy_load.lua`, and add one space after `git rev-parse`.   
After the changes, it should be: `"git rev-parse " .. vim.fn.system(...)`

**Comment by lanc3r** [comment]
> For now, please go inside `core/lazy_load.lua`, and add one space after `git rev-parse`.
> After the changes, it should be: `"git rev-parse" .. " " .. vim.fn.system(...)` (notice the space right after the rev-parse, it was removed, please add it back)
Thanks @lucario387 . This helps. There's typo though. 
It should be `"git rev-parse " ..'

**Comment by tynguyen2k1** [comment]
@lucario387,  Thanks a lot

**Comment by lucario387** [comment]
@lanc3r I intentionally edited my comments to make the space a different string, so that someone in the future reading this will understand it's for separating 2 arguments and not for useless spacing (I hope)
