### ISSUE TITLE
can not enable which-key plugin

### ISSUE THREAD

**Issue by hankji** [NvChad/NvChad#1507]
**Describe the bug**
user custom plugin override like this:
M.plugins={
  override={
     ["folke/which-key.nvim"] = {
        disable = false,
     },
  },
}

it is not work. Try to trace the code, the file "plugins/configs/whichkey.lua" was not load.

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - zsh
 - NVIM v0.8.0-dev-775-g27ce21ac8

**Comment by siduck** [comment]
please read the docs, you clearly dont know what the override field does
