### ISSUE TITLE
Statusline will disappear after :Alpha

### ISSUE THREAD

**Issue by AllenDang** [NvChad/NvChad#1509]
**Describe the bug**
Statusline will disappear after switch to dashboard with cmd `:Alpha`.

**To Reproduce**
1. Open any file from `:Telescope oldfiles`. Status line works normal.
2. Execute command `:Alpha`, switch to dashboard.
3. Open any file from `:Telescope oldfiles`.
4. Statusline disappear.

**Expected behavior**
Statusline always be there when editing file.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: macOS v12
 - Terminal: iTem2
 - Version of Neovim: NVIM v0.8.0-dev-937-gb1eaa2b9a

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/pull/1500
