### ISSUE TITLE
Update NvChad will delete ftplugin folder

### ISSUE THREAD

**Issue by AllenDang** [NvChad/NvChad#1510]
**Describe the bug**
After `<leader>uu`, the ftplugin folder in `~/.config/nvim` will be deleted.

**Expected behavior**
ftplugin folder should not be deleted.

**Desktop (please complete the following information):**
 - Operating System: macOS 12
 - Terminal: iTem2
 - Version of Neovim: NVIM v0.8.0-dev-937-gb1eaa2b9a

**Comment by siduck** [comment]
@AllenDang i gitignored it!
