### ISSUE TITLE
remapping completion to <C-y>

### ISSUE THREAD

**Issue by jaredmcqueen** [NvChad/NvChad#1512]
I'm trying to override completion so that Control+y or <C-y> accepts the completion, instead of the default of enter.

It seems that any calls to `cmp` in my `override.lua` is messing me up.  Do I need some imports in there?

custom/override.lua:
```
M.cmp = {
	mapping = {
		["<C-y>"] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Replace,
			select = false,
		}),
	},
}
```

chadrc.lua:
```
M.plugins = {
	override = {
		["hrsh7th/nvim-cmp"] = override.cmp,
	},
	user = require("custom.plugins"),
}
```

**Comment by siduck** [comment]
read the cmp example here https://nvchad.github.io/config/plugins#override-default-config-of-a-plugin
