### ISSUE TITLE
Can't seem to install any new lsp servers with mason

### ISSUE THREAD

**Issue by AdamJSoftware** [NvChad/NvChad#1513]
**Describe the bug**
Anytime I now try to add a new lsp server, I get the following error:
[lspconfig] Cannot access configuration for <SERVER>. Ensure this server is listed in `server_configurations.md` or added as a custom server.

I've tried this with a json-lsp and a few others. Here is my config. Any idea what I am missing?

```
// custom/plugins/lsp-config.lua
local servers = { "html", "cssls", "clangd", "ccls", "eslint", "tsserver", "gopls", "pylsp", "rust_analyzer" ,"json-lsp"}
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
```

```
// custom/chadrc.lua
M.plugins = {
  options = {
      lspconfig = {
         setup_lspconf = "custom.plugins.lspconfig",
      },
   },
   user = require "custom.plugins"
}

return M
```

**Comment by siduck** [comment]
options = {
      lspconfig = {
         setup_lspconf = "custom.plugins.lspconfig",
      },
   },
   user = require "custom.plugins"
}

this is wrong :c , read pinned issue

**Comment by AdamJSoftware** [comment]
I set it to this and now lsp doesn't seem to work at all

```
local M = {}
M.options, M.ui, M.mappings, M.plugins = {}, {}, {}, {}

M.plugins = {
  override = {},
  remove = {},
  user = {}

}


return M
```

I didn't want to add M.mappings = require "core.mappings" as doing so causes all of the keybindings to no longer work.

**Comment by siduck** [comment]
why add empty tables?

**Comment by siduck** [comment]
please read https://nvchad.github.io/config/Mappings and https://nvchad.github.io/config/Lsp%20stuff 

If you're new to nvchad then please read docs from the starting 

my custom config https://github.com/siduck/dotfiles/tree/master/nvchad/custom can be taken as an example
