### ISSUE TITLE
http://nvchad.com down

### ISSUE THREAD

**Issue by haydnjonesdesign** [NvChad/NvChad#1515]
**Describe the bug**
Looks like the nvchad.com has expired and documentation can't be accessed.

**To Reproduce**
1. Go to 'http://nvchad.com'

**Expected behavior**
Website loads instead getting:

nvchad.com
Happy to see your domain with Hostinger!
Your domain is active and is using Hostinger nameservers. Take the recommended steps below to continue your journey with Hostinger.

**Comment by haydnjonesdesign** [comment]
Seems to be back up! Nvmind.

**Comment by siduck** [comment]
@haydnjonesdesign its down again. Im trying to get a free SSL certificate from cloudflare but it doesnt seem to work :(

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/187015897-8bb31dd2-d5f0-4bab-a97a-3537bef9953b.png)


ok i have removed the cloudflare ssl, ig we have to wait for 24 hours

**Comment by siduck** [comment]
https://stackoverflow.com/questions/54059217/how-to-fix-domain-does-not-resolve-to-the-github-pages-server-error-in-github

**Comment by siduck** [comment]
nvchad.com

Its working now :D
