### ISSUE TITLE
Autocmd "BufDelete" won't be triggered after <leader>x

### ISSUE THREAD

**Issue by AllenDang** [NvChad/NvChad#1516]
**Describe the bug**
core.util.close_buffer invokes vim.cmd("sient! confirm bd") will skip all buf unload related autocmd, which makes impossible to do any stuff after a buf is deleted.

**To Reproduce**
1. Define a autocmd with event "BufDelete".
2. Open any file, press <leader>x.
3. Predefined autocmd is not triggered.

**Expected behavior**
Autocmd with event "BufDelete" should be invoked.

**Comment by siduck** [comment]
show your autocmd

**Comment by AllenDang** [comment]
I've deleted the script, but I've tested with ":bd" on same file buffer, the autocmd is triggered. If I'm using ":silent! confirm bd", autocmd is skipped.

**Comment by siduck** [comment]
> I've deleted the script, but I've tested with ":bd" on same file buffer, the autocmd is triggered. If I'm using ":silent! confirm bd", autocmd is skipped.

what if you remove silent! from that function?

**Comment by AllenDang** [comment]
A quick test, here is the autocmd definition.
```lua
autocmd({ "BufDelete" }, {
	group = vim.api.nvim_create_augroup("buf_delete_trigger_test", { clear = true }),
	pattern = "*",
	callback = function(params)
		vim.notify(string.format("Ok, I've triggered: %s", params.file))
	end,
})
```
1. `:bd`, triggered.
2. `:confirm bd`, triggered.
3. `:silent confirm bd`, NOT triggered.

**Comment by siduck** [comment]
```lua
vim.schedule(function()
      vim.notify(string.format("Ok, I've triggered: %s", params.file))
 end)
 ```

**Comment by siduck** [comment]
`silent` silences the output

**Comment by siduck** [comment]
@Akianonymus why do we have silent in the first place?

**Comment by siduck** [comment]
```lua
autocmd({ "BufWipeOut" }, {
  callback = function(params)
    if vim.bo.buflisted then
      vim.notify(string.format("Ok, I've triggered: %s", params.file))
    end
  end,
})
```

We will change bd to bw ( bufwipeout )

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/commit/39c42ca2bfb2ce7e2858de959f3b0f19681eea8d

**Comment by Akianonymus** [comment]
WHy bufwipeout ? Just remove the silent.

**Comment by siduck** [comment]
> WHy bufwipeout ? Just remove the silent.

because once we delete a buffer, we dont want it back. But it'll still be in nvim's memory. bufwipeout completely deletes the buffer and removes it from nvim's buffer too.

**Comment by Akianonymus** [comment]
bdelete makes the buffer unlisted, but doesn't purge marks, options, the buffer name, the buffer number, and so on. If you reload the buffer that information is retained (less what may be modified by autocommands), which may be useful because

    it allows you to keep using any marks, or the buffer number, you may have in your short-term memory.
    it prevents vim from having to reparse viminfo for the relevant information (trading the cost of keeping that info in RAM for the cost of reading that file from the disk, which is admittedly something we don't generally need to consciously worry about that much on modern computers).

bwipeout, on the other, gets rid of all of that (everything that is associated with the buffer), so that if you reopen the buffer it will be as if vim never saw that buffer before during this session.

---

I am sure some people would like their marks and other info to be preserved, maybe add a config option whether to use bd or bw.

**Comment by siduck** [comment]
i doubt if people would want to have their buffer info preserved,  if someone comes with an issue then i'll switch to bd

**Comment by Akianonymus** [comment]
> i doubt if people would want to have their buffer info preserved, if someone comes with an issue then i'll switch to bd

I am literally saying i have an issue, i want my marks to be preserved.

Do change to bd, but keep a option to change to bwipeout.

ALso, you make it seem like by preserving it slows down vim or something. Even neovim suggests not to use bwipeout unless required.

![image](https://user-images.githubusercontent.com/32216346/187055878-f3c97eab-431d-4311-9230-eb912c74c194.png)
