### ISSUE TITLE
Auto inserting comments

### ISSUE THREAD

**Issue by nt888** [NvChad/NvChad#1517]
**Description**
Whenever I press o, O or Enter (when the cursor is on a commented line) a comment is automatically inserted on a new line

**To Reproduce**
1. Open some source code file
2. Move cursor to commented line
3. Press o/O, or Enter (in insert mode)
4. See error (comment on new line)

**Expected behavior**
No new line comment auto insertion

**Desktop (please complete the following information):**
 - Linux arch 5.19.3-arch1-1 x86_64 GNU/Linux
 - Alacritty
 - NVIM v0.7.2

**Additional context**
This doesn't seem to work for me:
https://github.com/NvChad/NvChad/blob/696559863ba8368e3aee953ee7de3561934d4abe/lua/core/options.lua#L58-L59

However, manually entering `set formatoptions-=cro` fixes the problem in the current instance

Also when I try to create an autocmd it doesn't work:
```lua
vim.api.nvim_create_autocmd("BufEnter", {
  pattern = "*",
  command = "set formatoptions-=cro",
})
```

**Comment by siduck** [comment]
@nt888 thx also this is due to filetype overriding formatoptions so i created autocmd for this
 
 https://github.com/NvChad/NvChad/commit/39c42ca2bfb2ce7e2858de959f3b0f19681eea8d
