### ISSUE TITLE
NEED YOUR SUGGESTION | Proposal to simplify plugin management |

### ISSUE THREAD

**Issue by musjj** [NvChad/NvChad#1518]
**Is your feature request related to a problem? Please describe.**
I feel that the current plugin management framework can be greatly simplified and thus be more flexible. Right now, we need to handle 3 separate tables just to manage and configure our plugins: `user`, `override` and `remove`. I find this unnecessarily complicated, awkward and limiting, when there's a much simpler way that would give the user a lot more flexibility and control.

**Describe the solution you'd like**

`plugins/configs/plugin.lua`
First the plugin configuration should return the options table to be passed to `setup()`:
```lua
vim.opt.opt_foo = true

local options = {
  opt_bar = true,
}

return options
```

`plugins/init.lua`
Then, we move the `setup()` call to the packer `config` recipe. We then can pass the whole plugin table to the user's config and let them do whatever they want with the table:
```lua
vim.cmd "packadd packer.nvim"

local plugins = {
  ["author/plugin.nvim"] = {
    config = function()
      local options = require "plugins.config.plugin"
      require("plugin").setup(options)
    end,
  },
}

local present, custom = pcall(require, "custom.plugins")

if present then
  plugins = custom(plugins)
else

require("core.packer").run(plugins)
```

`custom/plugins.lua`
In the user configuration, we can now manipulate the plugins table with great freedom:
```lua
return function(plugins)
  -- Modify options table
  plugins["author/plugin.nvim"].config = function()
    local options = require "plugins.config.plugin"
    options.opt_bar = false
    require("plugin").setup(options)
  end

  -- Modify repository URL
  plugins["fork/plugin.nvim"] = plugins["author/plugin.nvim"]

  -- Remove plugin
  plugins["author/plugin.nvim"] = nil

  -- Add our own plugin
  plugins["our/own.plugin"] = {}

  return plugins
end
```

What do you think? I feel that this method of configuration is a lot nicer that what we currently have. Any suggestions for improvements are welcome.

**Comment by siduck** [comment]
the current implementation is already very simple :l

**Comment by siduck** [comment]
please read this section well https://nvchad.com/config/plugins

**Comment by musjj** [comment]
Have you read my suggestions? Please have some considerations before hurrying to close it.
The current implementation is simple, but it still adds unnecessary abstractions that makes plugin management awkward and unnatural.
With the modifications I suggested above, plugin configuration can be unified into one place and manipulated using Lua primitives instead of special nvchad abstractions. This reduces the learning curve of new users and will also let users with advanced setup to have a cleaner configuration structure.
Instead of having to go back and forth between `user`, `override` and `remove`, you can now manage and configure plugins in one place with one thing.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/187067810-fc6a7608-2aa9-4431-939d-7c9778a6cc3e.png)

This doesnt work, it will then use that key name from the default table

**Comment by siduck** [comment]
And this will be yet another breaking change which all users hate

**Comment by siduck** [comment]
@Akianonymus what do you think :joy:

**Comment by musjj** [comment]
>This doesnt work, it will then use that value from the default table key

What do you mean? Setting a table key to `nil` will remove that key in Lua. Since we no longer have to use config merging functions, the defaults won't be loaded.

>And this will be yet another breaking change which all users hate

A breaking change is very unfortunate and a thing I personally don't like either, but this repository seem to break *really* often anyways and make no promises of stability in the first place, so I would assume a lot of users of this config are prepared for that.

**Comment by siduck** [comment]
oh ok i read the post properly now and this seems a lil better imo except for the override thing

**Comment by siduck** [comment]
@lucario387 what do you think about this syntax?

**Comment by siduck** [comment]
@zbirenbaum

**Comment by siduck** [comment]
The worst part for this is that it'll bring yet another breaking change but remove many functions that deal with plugins in nvchad and make things cleaner

**Comment by Akianonymus** [comment]
@musjj Actually most of your suggestions were in nvchad at some point, i did most of them, like returning the plugin configs than executing them, disabling just by removing the plugin entry, etc. But got lost somewhere, idk, most probably i messed it up.

Returning the plugin configs - Good idea

---
> 
>  -- Remove plugin
>  plugins["author/plugin.nvim"] = nil

Good idea, but you have to use false, empty string or something, nil won't work as it just vanishes as it is passed.

---
>  -- Modify repository URL
>  plugins["fork/plugin.nvim"] = plugins["author/plugin.nvim"]

That will just replace the existing table, anyway, to modify url will have to add a wrapper.

WE can just

```
plugins["author/plugin.nvim"] = plugins["fork/plugin.nvim"]
plugins["fork/plugin.nvim"] = false
```

That old url config is fetched and disabled too, yes a extra line but i prefer this than handling it in config.

---

@siduck regarding it being a breaking change, i can work something out to not make it a breaking change ( well, no promises ).

**Comment by lucario387** [comment]
If anything, I'm ok with removing the `override` table. I'm not exactly sure how much more or less overhead it will become, but realisitically speaking, changing one pointer should lead to less overhead than many key value pairs.

**Comment by lucario387** [comment]
I don't really see the point of using the `override` table. To override something, you gotta read the docs anyway to know what you need to change and to change into.    
Maybe I'm in the wrong with this, but for me, to effectively override any NvChad setups, I would just copy the code from `lua/plugins` to `custom` then change it to what I want. Then, I get exactly what I expect, and if some breaking changes happen, I will get noticed about it through the update window of NvChad and Packer, and to adapt from that.

**Comment by siduck** [comment]
@musjj to use a fork of a plugin, one could just disable the author plugin then install the fork plugin

```lua
plugins["author/plugin.nvim"] = false,
plugins["fork/plugin.nvim"] = {}
```

**Comment by siduck** [comment]
@Akianonymus i'll work on this soon and let you know when to review :joy:

**Comment by musjj** [comment]
@Akianonymus 

>Good idea, but you have to use false, empty string or something, nil won't work as it just vanishes as it is passed.

Isn't it fine in this case? As far as I know, the modified table should be passed directly to `packer.startup`, so setting it to `nil` will just delete that key and thus the plugin should never get loaded/installed.

>plugins["author/plugin.nvim"] = plugins["fork/plugin.nvim"]
>plugins["fork/plugin.nvim"] = false

Yes, this is what I did in the sample code (except with `nil`), but I guess I wasn't being very clear with it.

But I wonder if it's really possible to do this without breaking current configs.

**Comment by siduck** [comment]
@musjj so this is almost the same as before except for the overriding part 

```lua
M.plugins = {

  -- Install plugin
  ["Pocco81/TrueZen.nvim"] = {},

  -- Override plugin definition options
  ["goolord/alpha-nvim"] = {
    disable = false,
    cmd = "Alpha",
  },

  -- Override plugin config
  ["williamboman/mason.nvim"] = {
    config = function()
      local config = require "plugins.configs.mason"
      config.ensure_installed = { "html-lsp", "clangd" }

      require("mason").setup(config)
    end,
  },

  -- remove plugin
  ["neovim/nvim-lspconfig"] = {
    disbable = true,
  },
}
```

**Comment by musjj** [comment]
Hmm, is this how it was configured in the past? Why was it changed?

**Comment by lucario387** [comment]
> Hmm, is this how it was configured in the past? Why was it changed?

Almost similar to that actually.   
After the very big change to not use conditional variables for plugin disabliing, it moved to almost like that.   
But shortly after, one of the maintainers of this repo noticed significant startuptime increase if the syntax for removing plugins were to be like what siduck just showed, so it was quickly separated into `disable` and `user` of today. `override` however was before both, and has been simplified by a lot.

**Comment by siduck** [comment]
@lucario387 what about this?
 
 ```lua
  -- remove plugin
  ["neovim/nvim-lspconfig"] = false,
  ```
  
  This will remove a plugin completely but i have to modify one function in utils.lua to keep skip keys with false value in overall plugin table

**Comment by lucario387** [comment]
I'm okay with it. @musjj what abt u?

**Comment by musjj** [comment]
@lucario387 
@siduck 
I'm not sure why `false` + util function is necessary here.
My original idea is that we pass the plugin table to the user, let them modify it before returning it, then we pass that modified table to `packer.startup()`. 
Now that the user have full control of the plugin table, we don't need to have custom semantics for disabling plugins or overriding options (but of course we need to refactor the options loading a bit so that the user can have better access to it).
Is there something that would prevent this to work? While this is an armchair guess, there shouldn't be any performance overhead with this method.

**Comment by lucario387** [comment]
@musjj ye with your setup, aside from the using forked  repo, is fine
but i have no rights to decide  here so i will go with whatever siduck decides is nice according to him

**Comment by siduck** [comment]
@musjj those are necessary because the native syntax seems ugly and cluttered

**Comment by siduck** [comment]
and the native way of doing this will break 100% breaking changes where mine will just have 30%

**Comment by musjj** [comment]
Hmm, actually thinking about it, if you're willing to "clutter" nvchad's internal `plugins/init.lua` a little bit, you can allow the native way of option configuration without breaking current configs. Example:

```lua
local plugins = {
  ["author/plugin.nvim"] = {
    config = function()
      local options = require "plugins.config.plugin"
      options = require("core.utils").load_override(options, "author/plugin.nvim")
      require("plugin").setup(options)
    end,
  },
}
```

This way users can now obtain nvchad's default opts table and do stuff with it, while not breaking current configs that use the `override` table.

**Comment by zbirenbaum** [comment]
I’ll give some thought to this too. I think we have already made changes like this around 4/5 times now in the last 6 months, so it would be good to have system we can stick with. I don’t love that we still have to control which plugins are loaded from chadrc so setting one to false like you did above to disable it in the plugin table seems like a good idea to me @siduck

**Comment by tomasky** [comment]
I want to talk about ，whether it's easier for users or simpler for NVChad code

**Comment by lucario387** [comment]
> I want to talk about ，whether it's easier for users or simpler for NVChad code

In this case tbf, it's easier for both.   
From NvChad's side, the code won't have to do up to three checks for each plugin:
1. Whether the plugin is removed
2. Whether the plugin's loading order is altered (on start or specific event, or something)
3. Whether a plugin's default config is changed

If it becomes a unified plugins table, check no.3 is no longer needed, and checks no.1 and no.2 is combined into one.

From the user side, let's be real it's a chore to manage 3 tables compared to only 1, so it's gonna be easier too

**Comment by siduck** [comment]
@lucario387 @tomasky only thing that might get lengthy is the override stuff

**Comment by siduck** [comment]
Which do you prefer?

```lua
  -- Override plugin config
  ["williamboman/mason.nvim"] = {
    config = function()
      local config = require "plugins.configs.mason"
      config.ensure_installed = { "html-lsp", "clangd" }

      require("mason").setup(config)
    end,
  },
  ```
  
  OR THIS :
  
  ```lua
  ["williamboman/mason.nvim"] = {
   override_options = {
        ensure_installed = { "html-lsp", "clangd" }
   }
  }
  ```

**Comment by siduck** [comment]
@tomasky @lucario387 @Akianonymus @zbirenbaum @musjj  I like the 2nd one, I know we have to add some extra code from our side for it but it gets easier for USER as this is more easier than before cuz we had to add override table in chadrc and add that plugin key name they name in it too. 

I dont like the first one cuz its lengthy , I know its less bloated & more native cuz we dont have to add any extra code for it but its upto users liking, After all they need to decide it!

**Comment by lucario387** [comment]
The question now becomes
- Should the user partially override plugin configs
- Should the user always completely override plugin configs, so that it is then unrelated to default config provided by nvchad

**Comment by lucario387** [comment]
If your wants is the first, then ye, the 2nd syntax looks fine.

If instead, you want the second one, then the first looks better. It doesn't matter what's inside `config()`, it won't be used at all once overridden by the user

**Comment by siduck** [comment]
@lucario387 users usually override partially, If they want to completely remove those options then they can override that `config` function of the plugin defintion area

**Comment by tomasky** [comment]
yea, override_options is easier and better

**Comment by siduck** [comment]
@musjj https://github.com/NvChad/NvChad/pull/1531 

I wanted to make it 100% native but then the plugin definition syntax of custom plugins would look different than the default plugin definiton syntax so that would add confusion, so I just put the old method of keeping custom plugins a table but better

**Comment by musjj** [comment]
@siduck 
Sorry, couldn't check the thread yesterday, but I wish there was a bit more discussion before committing the breaking change.
Anyways, why not go with https://github.com/NvChad/NvChad/issues/1518#issuecomment-1233096673
This will not add any breaking change (the classic `override` table will still work), while still allowing users to access and modify the default options table directly if they want to. The `false` syntax thing should also work on top of this.

**Comment by siduck** [comment]
@musjj the PR is ready to merge! what do you think?

**Comment by Akianonymus** [comment]
Hold your horses, definitely not ready to merge. @musjj idea is good, it should not be a breaking change. Atleast for a month or so, with a depreciation warning, just like neovim handles outdated apis.

**Comment by siduck** [comment]
so you're going to print the depreciation warning every time the user opens nvim or after packersync?

**Comment by siduck** [comment]
done supporting old syntax, https://github.com/NvChad/NvChad/pull/1531/commits/4389cef1cb218ec72f71211afbb69e0eeb7589e0 

yall can test it now

**Comment by Spell28** [comment]
Oh shit, here we go again

**Comment by siduck** [comment]
@Spell28 old method is still supported for a month so dont worry

**Comment by tomasky** [comment]
@siduck  This doesn't work .    The reason is, this  `plugins/init.lua`    file is going to be a lot of stuff, we need to  require other modules from other config file
```lua
local configs = require "custom.configs"

return {
  ["kyazdani42/nvim-tree.lua"] = {
    override_options = configs.nvimtree,
  },

```

**Comment by siduck** [comment]
show your configs.nvimtree file @tomasky 

overrides works perfect for me

**Comment by tomasky** [comment]
sorry ,i mean the  custom/plugins/init.lua file

**Comment by siduck** [comment]
@tomasky it will still work, my updated config : 

![image](https://user-images.githubusercontent.com/59060246/189328709-84f45218-ddcb-423b-8ff8-25a456fbc3f3.png)

**Comment by tomasky** [comment]
yes ,it works ,sorry ,I missed this

```lua
M.plugins = require "custom.plugins"

```

**Comment by p5a0u9l** [comment]
This broke my config and took a while to fix. please don't make changes like this frequently and without very good reason.

**Comment by Akianonymus** [comment]
@p5a0u9l Old configs are still working, it's not a breaking change, well it's not supposed to be.

**Comment by tomasky** [comment]
if we have a breaking change every month or two, I not think  it's that frequent

**Comment by siduck** [comment]
> if we have a breaking change every month or two, I not think it's that frequent

chadrc is perfect now I think so I dont think we will have any breaking changes related to syntax

**Comment by lucario387** [comment]
guess i will stick with old syntax for as long as i can ig.
It's better cause i can actually force autostart some plugins easier than the loophole needed in new syntax

**Comment by siduck** [comment]
just load the plugin after base46

**Comment by lucario387** [comment]
Loading a plugin after one plugin is different from loading one directly
Yes it will be loaded basically at startup, but there will be some time till it's loaded

**Comment by lucario387** [comment]
i won't comment on this further as I've accepted to seding/manually changing the files, i'm fine with that

**Comment by siduck** [comment]
> Loading a plugin after one plugin is different from loading one directly Yes it will be loaded basically at startup, but there will be some time till it's loaded

base46 is very light, idk what heavy & shady plenary.job you're using there which needs plenary at start :thinking:

**Comment by siduck** [comment]
i'd just use vim.loop or make a lil wrapper out of it

**Comment by fullstopslash** [comment]
At this point I'm aware there's going to be a breaking change every couple of weeks with this project, but honestly now I'd just like to see a real straightforward guide to what I have to change to get a config nvchad "standard" again after the change. Till the next breaking change y'all!

**Comment by Akianonymus** [comment]
@lucario38 What does force autostart means ? How did you do it before ?

P.S: I force start a lot of stuff in my custom config, i am failing to see how it is related to config structure

**Comment by siduck** [comment]
@fullstopslash the chadrc is perfect now so no more syntax related breaking change, https://github.com/NvChad/NvChad/commit/d61946d3bfa304e8924120888611d64ee9f98f51#commitcomment-83488329

**Comment by lucario387** [comment]
> @lucario387 What does force autostart means ? How did you do it before ?

@Akianonymus I did it in the most unintuitive way possible, and that's to change the setup() func of packer to PackerLoad it.
And then I change to the next step after, which is to directly alter the `plugins/init.lua` packer configs, as there was no actual option to tell Packer that I want a plugin to be load on star.

**Comment by siduck** [comment]
@lucario387 `rm_default_opts` exists

**Comment by lucario387** [comment]
> @lucario387 `rm_default_opts` exists

Of course, but that's not a thing 2 days ago. 
I have since updated it to the new syntax

**Comment by Akianonymus** [comment]
@lucario387 Can you show me the changes ? I will help you out if i can, i do it somewhat similarly, but never modifying the core config.

What do you mean by star ? Is it start ?

**Comment by siduck** [comment]
yes start

**Comment by lucario387** [comment]
Ye i meant force start
Now that `rm_default_opts` exist, I am fine with it now
(Besides, If all else fails, I can just enforce PackerLoad inside custom/init.lua ig)
