### ISSUE TITLE
Unable to override vim.notify with nvim-notify plugin

### ISSUE THREAD

**Issue by shaun-mathew** [NvChad/NvChad#1519]
**Describe the bug**
I've been trying to figure out how to replace vim's default notification handler ui with [nvim-notify](https://github.com/rcarriga/nvim-notify),
but it does not seem to work probably due to how plugins in the custom folder are being loaded. If I PackerSync after the plugin is installed, but don't quit vim, calling ```:lua vim.notify("Test notification")``` invokes nvim-notify's plugin, but upon reopening vim and calling ```:lua vim.notify("Test notification")```, vim's default notification daemon is called. I've tested it with a clean NvChad config and
it doesn't work there either. Trying with a clean init.lua (No NvChad) works.

**To Reproduce**

1. Install [nvim-notify](https://github.com/rcarriga/nvim-notify) by adding the following to custom/plugins/init.lua:
```lua
  ["rcarriga/nvim-notify"] = {
    config = function()
       require("notify").setup()
       vim.notify = require("notify")
    end
  }
```
(I've also tried taking the function outside custom/plugins/init.lua and tried invoking like so ```config = configs.notify()```)
2. Close and open neovim and run ```:PackerSync```.
3. Close and open neovim
4.  Call ```:lua vim.notify("Test")```

**Expected behavior**
nvim-notify's notification pops up
![image](https://user-images.githubusercontent.com/16690478/187085189-aad52cbe-ccec-442a-9408-a57a154e4736.png)

**Screenshots of Current Behaviour**
calling ```:lua vim.notify("Test Notification")``` not invoking nvim-notify ui
![image](https://user-images.githubusercontent.com/16690478/187085264-3336ffe6-3747-4b59-bafe-d779c582aff4.png)

**Desktop:**
 - Archlinux
 - Kitty
 - NVIM v0.8.0-dev-967-g523600ea6

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/187088857-0f21a312-e0a7-4630-96e8-ac848522fa41.mp4

not a nvchad issue and I tested your code here, Works perfectly

**Comment by shaun-mathew** [comment]
Hmm, the issue I have is very bizarre. When I open up Neovim with no arguments like you did,
vim.notify calls nvim-notify correctly. However, if open up any filetype e.g. init.lua the notification does not work. Can you
confirm that this works?

**Comment by siduck** [comment]
oh yes it doesnt work on filetypes, weird :/ 

 btw this plugin works with non nvchad config?

**Comment by lucario387** [comment]
> oh yes it doesnt work on filetypes, weird :/ 
> 
> 
> 
>  btw this plugin works with non nvchad config?

Well, it is because of your lspconfig if i were to guess.   
Because that has will override vim.notify when calling lspconfig, while nvim-notify will probably be called before that (or later, race condition kek)
