### ISSUE TITLE
Telescope's argument candidates are not working for the first time

### ISSUE THREAD

**Issue by ywpkwon** [NvChad/NvChad#1520]
When running `:Telescope <tab>` for the first time, the menu shows subfolders (instead of true telescope arguments). Once running `:Telescope find_files` (by manually typing `find_files` argument), running `:Telescope <tab>` displays possible telescope arguments.

Here is the behavior.
![Screencast-2022-08-28T18:38:48-07:00](https://user-images.githubusercontent.com/18429284/187106275-b600e185-ff73-4166-ac7e-67a0d50c9669.gif)

 - Operating System: Same on Ubuntu 18.4 & 22.04
 - Terminal: Kitty
 - Version of Neovim: `v0.7.2`, `v0.8.0-dev`

This is my first experience with the NvChad. 
- I just cloned `NvChad` (so it should be the latest)
- I don't have any custom configs. 

Any advice please?
How to solve this? What am I doing wrong here?

**Comment by blackode** [comment]
can you try `<space>ff` and see it is working or not?

**Comment by ywpkwon** [comment]
@blackode `<space>ff` just works. Either manual `:Telescope find_files` (i.e., manual typing) or `<space>ff` once, `:Telescope <tab>` starts to display correct argument choices.

Before any of these first activations, `:Telescope <tab>` displays subfolders as arguement candidates (which seems wrong).

**Comment by siduck** [comment]
because telescope is lazyloaded, remove its lazyloading ( for example load it at VimEnter event )
