### ISSUE TITLE
Cannot use `VimtexView` command from `VimTex`

### ISSUE THREAD

**Issue by xarthurx** [NvChad/NvChad#1526]
**Describe the bug**
I apologize for reporting this bug as it needs some pre-requisite knowledge for LaTeX and a bit of effort to set up the testing environment.
But as I've done quite some testing to locate the bug, I feels this is highly possible something embedded in the `nvChad` settings.
I'll try to describe it clearly.

**What you need**:
- `nvChad`
- `VimTex` plugin
- a pdf viewer, `SumatraPDF` for windows, or others listed here: https://github.com/lervag/vimtex
- a TEX environment, `MikTeX` for windows, `TexLive` for Linux.
- Perl to run `latexmk` (for Windows, you can install it from `winget` or `scoop`)
- Make sure the neovim and the pdfview are both 64bit or 32bit

---
`VimTex` is a plugin for `Latex` writing and provide many useful integrations.

Using the minimal example at the end of: 
https://github.com/lervag/vimtex/issues/new?assignees=&labels=bug&template=issue_report.yml

which is 
**minimal.vim**
```
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
" Add relevant options and VimTeX configuration below.
```
**minimal.tex**
```
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```
and run:
```
nvim -u minimal.vim minimal.tex
```
I can compile the minimal example and use `VimtexView` to open the default pdf viewer `SumatraPDF` on my windows machine.

However, once I use the configuration of `nvChad`, even with only `vimtex` plugin enabled and minimal default settings:
```
  ["lervag/vimtex"] = {
    ft = { "tex", "bib" },
  },
```
The compilation works, but calling `VimtexView` cannot open the PDF viewer.

The key here is something is blocking the vim command `:VimtexView` to start the PDF viewer from `nvChad`.

 
**To Reproduce**
1. Install the above requirement
2. Open the minimal example with minimal `nvChad` settings
3. Compile the `tex` file with `:VimtexCompile`
4. Open the viewer with `:VimtexView`
5. Cannot open the viewer

**Expected behavior**
I can open the pdf viewer from `nvchad`

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - Powershell
 - 0.7.2

**Comment by siduck** [comment]
I installed the plugin and vimtexview works fine

![image](https://user-images.githubusercontent.com/59060246/187624654-934fe6f1-867c-40c2-a190-e76fef4f30ca.png)

**Comment by xarthurx** [comment]
@siduck  Then, it might be a Windows issue? Do we have Windows developers?

**Comment by siduck** [comment]
@lucario387 probably

**Comment by siduck** [comment]
> @siduck Then, it might be a Windows issue? Do we have Windows developers?

does VimTexView command work with non nvchad config?

**Comment by siduck** [comment]
> > > @siduck Then, it might be a Windows issue? Do we have Windows developers?
> > 
> > 
> > 
> > does VimTexView command work with non nvchad config?
> 
> Yes. If I use the minimal configuration and minimal Tex example (both shown above), I can call out the PDF viewer.

Hmm try removing the default plugin list whole table in options.lua and check again

**Comment by xarthurx** [comment]
> > > > @siduck Then, it might be a Windows issue? Do we have Windows developers?
> > > 
> > > 
> > > does VimTexView command work with non nvchad config?
> > 
> > 
> > Yes. If I use the minimal configuration and minimal Tex example (both shown above), I can call out the PDF viewer.
> 
> Hmm try removing the default plugin list whole table in options.lua and check again

No luck.

**Comment by xarthurx** [comment]
OK, I stupidly commend out things little by little, it turns out the problem is caused by the following piece of code for modifying `nvterm` to use `pwsh` from one issue in the issue list of `nvchad`.

```
------------------------------------------------------
--  nvTerm.
------------------------------------------------------
if vim.fn.has('win32') == 1 then
   vim.opt.shell = 'pwsh.exe -nol'
   vim.opt.shellcmdflag = '-nop -c'
   vim.opt.shellquote = '"'
   vim.opt.shellxquote = ''
   vim.opt.shellpipe = '| Out-File -Encoding UTF8 %s'
   vim.opt.shellredir = '| Out-File -Encoding UTF8 %s'
end
```

**Comment by siduck** [comment]
hmm then its fixed now ig! not a nvchad issue right, good to close? :thinking:
