### ISSUE TITLE
How to apply custom key mappings to Whichkey?

### ISSUE THREAD

**Issue by ywpkwon** [NvChad/NvChad#1528]
I tried adding some key mappings. But I don't think `Whichkey` doesn't apply.
For example, here is my `custom/mappings.lua`:
```lua
local M = {}
M.navigation = {
  n = {
    ["H"] = { "^", "beginning of line" },
    ["L"] = { "$", "end of line" },
  }
}
```

The screenshot video shows the `H` and `L` functionally work well (`beginning of line` and `end of line`, respectively). Of course, `Telescope keymaps` shows they are there. However, `Whichkey` still displays `H` and `L` are `Home line of window (top)` and `Last line of window`, respectively, which should be updated.
![Screencast-2022-08-31T00:55:03-07:00](https://user-images.githubusercontent.com/18429284/187627407-502633c7-e4fa-406a-8afc-1e75a59dc8be.gif)

How can I update this information while I'm using `custom/mappings`?

**Comment by siduck** [comment]
@ywpkwon whichkey shows mapping info mostly from leader keys

**Comment by siduck** [comment]
can you do it with non nvchad config?

**Comment by siduck** [comment]
no idea

**Comment by ViiEx** [comment]
@ywpkwon  It is kinda of a late reply but have you tried to set up the which key?

From their docs I imagine that the following could work

```lua
local wk = require("which-key")

local mappings = {
  H = { "^", "Beginning if line" },
  L = { "$", "End of line" },
}

local opts = {
  mode = "n",
  noremap = true,
  nowait = true,
}

wk.register(mappings, opts)
```

You may want to refer at there [repo](https://github.com/folke/which-key.nvim) for more info

**Comment by siduck** [comment]
this is a whichkey bug, I tried this in whichkey config and it doesnt register but it does it for leader, ctrl etc keys
```lua
vim.keymap.set("n", "H", "^", { desc = "Beginning of line" })
```

So what you can do is still use the current ( navigation table in your custom mappings ) and register with whichkey

```lua
 ["folke/which-key.nvim"] = {
    disable = false,

    config = function()
      require "plugins.configs.whichkey"

      local mappings = {
        H = { "^", "Beginning of line" },
        L = { "$", "End of line" },
      }

      require("which-key").register(mappings, {})
    end,
  },
  ```
  make sure to packercompile
