### ISSUE TITLE
Fresh Install of NvChad giving neorg related error

### ISSUE THREAD

**Issue by tushargoyalofficial** [NvChad/NvChad#1529]
**Describe the bug**
I made a fresh install of NvChad. Add configs as per SiDuck dotfiles. On restarting nvim, whenever I do any operations, I am seeing this error. Before updating today, all was working fine.

**To Reproduce**
1. Install NvChad
2. Use Siduck's custom nvchad dotfiles
3. Sync packages
4. You will start seeing error like at time of file search, opening a file

**Expected behavior**
This should not come

**Screenshots**
![image](https://user-images.githubusercontent.com/24288879/187871658-086559dd-4d7b-4937-8aa8-3cb893bd2511.png)

**Desktop (please complete the following information):**
 - Manjaro Linux (Arch)
 - Kitty, Gnome
 - Version of Neovim - 7.2

**Additional context**
Not at the moment

**Comment by siduck** [comment]
dont use latest neorg, use this tag     tag = "0.0.12",

**Comment by tushargoyalofficial** [comment]
It's working fine now. There is an update to neorg package. Just updated all the packages. Working fine now, thanks. You can close this issue
