### ISSUE TITLE
Breaking changes could be added as new releases

### ISSUE THREAD

**Issue by yungParrot** [NvChad/NvChad#1535]
What do you think about creating new releases when new breaking changes have been added?
I think it would make more sense to release a new version e.g. `2.0` and add it here 👉 https://github.com/NvChad/NvChad/releases instead of creating issues e.g. https://github.com/NvChad/NvChad/issues/1386

It gets a bit confusing when after an NvChad update something doesn't work and finding what caused it isn't that straightforward 😿
Maybe adding [semantic versioning](https://semver.org/) could make submitting new updates/issues easier? The users would know what works and what doesn't with each NvChad version 🤠

**Comment by siduck** [comment]
@yungParrot #1386 could be the last major breaking change I think

**Comment by yungParrot** [comment]
@siduck wouldn't it be easier for you to tag newer versions? Even though no new breaking changes are planned, I think maybe having one place for all release information could result in less issues 🤔
