### ISSUE TITLE
Need help to install custom plugin

### ISSUE THREAD

**Issue by mcctuxic** [NvChad/NvChad#1536]
I have a more general question:
How can I configure/install a plugin, which installation description
is totally based on vimscript and I want lua only.

More specifically, I want to install this plugin:
https://github.com/alaviss/nim.nvim

Is there any documentation about installing/configuring of 
"vimscript only" plugins somewhere?

**Comment by siduck** [comment]
@mcctuxic it will be the same as configuring lua plugins

```lua
['alaviss/nim.nvim'] = {
   config = function()
      -- stuff 
   end
}
```

**Comment by siduck** [comment]
but that nim.nvim works for ncm2 and asyncomplete.vim. We use nvim-cmp so I doubt if it will work with that. 

What you can do is write nvim-cmp source for that plugin or not use it. 

Also you just need to enable nim-lsp for nim support right? why this plugin
