### ISSUE TITLE
Keymap Overrides Should not need exact case matching

### ISSUE THREAD

**Issue by ariel-frischer** [NvChad/NvChad#1537]
**Is your feature request related to a problem? Please describe.**
 I was trying to override the `tabufline` mapping of `["<TAB>"]` but instead I wrote `["<Tab>"]` which didn't override anything but should be a valid vim mapping of the tab key.  So I think these override should have a bit more leeway. It's a small improvement but I think it is useful.

**Comment by siduck** [comment]
Just write the exact keyname, ["<TAB>"] is basically a key in the default mapping table's tabufline's table. It would be a lil bloat to add functions which that convert all the keys into the same case ( either uppercase or lowercase ) then both the default/user mapping tables get merged. So I dont think we will add this.

**Comment by Akianonymus** [comment]
I think this is a genuine issue, it's doesn't make sense user have to write the exact thing.

It should be according to neovim rules.

**Comment by siduck** [comment]
@Akianonymus then we have to lowercase or upppercase all the keys in the mapping tables ( default/custom ) 

so <C-s> will become <C-S> or <c-s> too? lowercasing/uppercasing one key like `<TAB>` will mess up others

**Comment by siduck** [comment]
and I dont want to write another set of functions & conditions for this simple thing. 

its just the issue with <TAB> and its excusable ig

**Comment by Akianonymus** [comment]
> and I dont want to write another set of functions & conditions for this simple thing.
> 
> its just the issue with and its excusable ig

You don't need to

https://github.com/NvChad/NvChad/pull/1542

**Comment by siduck** [comment]
> > and I dont want to write another set of functions & conditions for this simple thing.
> > its just the issue with and its excusable ig
> 
> You don't need to
> 
> #1542

will this convert 'K'  ( shift + k ) into k ?

**Comment by tomasky** [comment]
I don't use KeyMap Overrides, but I don't think it's necessary, it's easy to introduce new problems

**Comment by Akianonymus** [comment]
Opinions don't matter if it's a bug, let's not make this a ostrich problem.

Also, regarding new problems, do test and tell what bug is introduced. I will try to improve.

I have tested it for all possible stuff i think, see the commit message.

**Comment by siduck** [comment]
@Akianonymus tested it and works well, good to merge.

**Comment by Akianonymus** [comment]
Well i found a bug, seems like this will be difficult to solve without complicating stuff.

**Comment by siduck** [comment]
> Well i found a bug, seems like this will be difficult to solve without complicating stuff.

hehe great :grin:
