### ISSUE TITLE
which key is not working on fresh install

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1539]
**Describe the bug**
which key is not working in fresh install, i cant even see it in :PackerStatus

**Desktop (please complete the following information):**
 - Manjaro
 - kittyl
 - NVIM v0.7.2

**Additional context**
i am a totall beginner and trying to get into nvim and leave vscode, but looking at the complexity of things here seems like first i need to improve my lua programming skill before using nvim. i have copies stuff from others config and added some stuff if u want me to post my nvim custom folder i can put it here.

**Comment by gglanzani** [comment]
It stopped working for me — I think I did an upgrade to main yesterday

**Comment by Aneeqasif** [comment]
> 

what should i do

**Comment by MatthewCushing** [comment]
It's currently disabled by default if you look in the packer plugin file.  It's a plugin that's much better off user configured anyways.  Just remove the WhichKey config and add it yourself, shouldn't have a problem then.  Or you might be able to see why you're running into issues with it and just override some of it instead.

**Comment by siduck** [comment]
enable it, read the docs and then do packersync
```lua
['folke/which-key.nvim'] = {disable = false}
```
in  your custom plugins section
