### ISSUE TITLE
help needed in luasnip

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1540]
**Is your feature request related to a problem? Please describe.**
i am trying to have lua snip configured but i am not getting any where and just frustratingly working on it from past 4 hours tried different things but failed , i am following this [tutorial](https://github.com/ziontee113/luasnip-tutorial) it seems that with normal nvim it should be easy but i dont know how to get it working in nvchad. please help me a bit in this issue.
**Describe the solution you'd like**
lua snip working perfectly with my snippets in my snippets folder

**Comment by siduck** [comment]
modify luasnip's config function https://nvchad.com/config/plugins#modify-plugin-definition-options ( read the docs!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!)
