### ISSUE TITLE
Formatting keybinding doesn't work with rust-tools plugin

### ISSUE THREAD

**Issue by kvzn** [NvChad/NvChad#1541]
Any idea please?

```lua
-- custom/mappings.lua file

local M = {}

M["rust-tools"]= {
  plugin = true,

  n = {
    ["<leader>fm"] = {
      function()
        vim.lsp.buf.formatting {}
      end,
      "rust-tools formatting",
    },
  },
}

return M
```

**Comment by siduck** [comment]
@kvzn <leader>fm is already a default plugin, why are you even defining it again?

**Comment by kvzn** [comment]
> @kvzn fm is already a default plugin, why are you even defining it again?

Hi boss, `fm` doesn't work with `rust-tools` so I tried custom mapping, but it still doesn't.

**Comment by siduck** [comment]
> > @kvzn fm is already a default plugin, why are you even defining it again?
> 
> Hi boss, `fm` doesn't work with `rust-tools` so I tried custom mapping, but it still doesn't.

hmm you should try running that lua function 

```lua
lua vim.lsp.buf.formatting()
```
run this in command mode

**Comment by kvzn** [comment]
@siduck someone said that `rust-tools` has its own logic of `lsp` maintaining, this might lead to the conflict with `NvChad`, (sorry I can't find the page now)

**Comment by krolyxon** [comment]
none of the lsp keybindings will work with rust-tools plugin,

**Comment by siduck** [comment]
how are you both defining rust_tools in your custom plugins section? share a screenshot

**Comment by siduck** [comment]
your on_attach is empty

**Comment by siduck** [comment]
so not a nvchad issue!

**Comment by kvzn** [comment]
> ```lua
> on_attach = require("plugins.configs.lspconfig").on_attach
> ```

Genius!

**Comment by siduck** [comment]
@krolyxon which neovim version are you using?

**Comment by krolyxon** [comment]
> @krolyxon which neovim version are you using?

i am using version 0.7.2, i guess thats the latest one on arch.
but why the document formatting and document range formatting is set to ``false``?

**Comment by siduck** [comment]
probably cuz many use null-ls for formatting so the formatters defined by null-ls are given more priority and inbuilt lsp's formatter are disabled. But yes this is more of a user preference so I'll remove this

**Comment by siduck** [comment]
I suggest you to just define rustfmt in your null-ls config 

https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#rustfmt

**Comment by siduck** [comment]
my null-ls config : 

![image](https://user-images.githubusercontent.com/59060246/189006586-48071d28-cfb0-4750-8aa9-a04922d65991.png)
