### ISSUE TITLE
nvchad/nvim-colorizer and which-key has been removed since last update

### ISSUE THREAD

**Issue by modsyan** [NvChad/NvChad#1544]
**Describe the bug**
nvchad/nvim-colorizer and which-key has been removed since last update

**Expected behavior**
colorization does not working 
only one yellow color 

**Screenshots**
https://user-images.githubusercontent.com/82670636/188889205-353e4fd6-08fb-4354-887b-4db2f9ee6d20.png

**Desktop (please complete the following information):**
 - Operating System Archlinux
 - Terminal alacritty
 - Version of Neovim leatest

**Additional context**

**Comment by siduck** [comment]
re-install it
