### ISSUE TITLE
Telescope file browser doesn't use the theme

### ISSUE THREAD

**Issue by Rik034** [NvChad/NvChad#1545]
**Describe the bug**
When I open Telescope file browser without opening Telescope first, the file browser doesn't use the theme.

**To Reproduce**
1. Open Telescope file browser (require'telescope'.extensions.file_browser.file_browser()
2. See bug

**Expected behavior**
Telescope file browser should use the theme like the other extensions

**Screenshots**

https://user-images.githubusercontent.com/60218806/188985267-ed33d6ac-418d-45d2-bb59-e9ee78d24616.mp4

**Desktop (please complete the following information):**
 - Operating System: Arch Linux (kernel 5.19.6-xanmod1-1-x64v2)
 - Terminal: Alacritty
 - Version of Neovim: 0.7.2

**Comment by lucario387** [comment]
That's more of an upstream issue? idk   

Can you reproduce this behavior if you are using neovim without NvChad's configuration?

**Comment by siduck** [comment]
@lucario387 no, i think he forgot to load that extension :thinking: 

@Rik034 put this into your override 

```lua
["nvim-telescope/telescope.nvim"] = {
      extensions_list = { "themes", "terms", "file_browser" },
}
```

**Comment by Rik034** [comment]
> 

Thanks, this fixed it.
