### ISSUE TITLE
Keystroke `p` is interpreted as paste command

### ISSUE THREAD

**Issue by ericwq** [NvChad/NvChad#1546]
**Describe the bug**
keystroke `p` is interpreted as paste command for LSP placeholder.

**To Reproduce**
see the movie, when I typed `c.session.Encrypt()`, the editor mark the placeholder for parameter. 
when I typed the `p`, the behavior is wrong, it should give me `px` hint instead of paste content to the editor.

**Expected behavior**
keystroke `p` should be normal p character.

**Video recording**
[![asciicast](https://asciinema.org/a/U0X2KMUNTzrn9nngmL6PoyYyk.svg)](https://asciinema.org/a/U0X2KMUNTzrn9nngmL6PoyYyk)

**Desktop (please complete the following information):**
 - Operating System :  docker desktop 4.11.1 (84025) running on macOS Monterey 12.5.1
 - Terminal ： Kitty
 - Version of Neovim 0.7.2

**Comment by lucario387** [comment]
@ericwq Problem detected, will push a fix soon   
In the mean time, please go into `core/mappings.lua`, change the `M.general`, the `v` table to `x`
The end result should be something like this 
![image](https://user-images.githubusercontent.com/29790821/189102074-c8e317ab-1ea2-4c77-9b85-1868503e8cf7.png)

**Comment by Akianonymus** [comment]
Sorry, but i how to reproduce this ? I saw the video and have no clue what happened, please elaborate.

**Comment by lucario387** [comment]
> Sorry, but i how to reproduce this ? I saw the video and have no clue what happened, please elaborate.

Before the latest commit: when you press p after selecting a snippet in insert mode, you will paste whatever is in the register. Alongside that, typing j, k in select mode will move up and down a line, which should not be a thing.    
After the commit: This will no longer happen, and typing j,k,p in select mode will make you enter insert mode and insert those characters.

**Comment by Akianonymus** [comment]
> 

ooh, makes sense, thank you for explaining.

**Comment by ericwq** [comment]
yes, it's solved. thanks @lucario387
