### ISSUE TITLE
Failed to update NvChad/nvim-colorizer.lua

### ISSUE THREAD

**Issue by tushargoyalofficial** [NvChad/NvChad#1550]
**Describe the bug**
After updating, when packer updating all, getting an error "Failed to update NvChad/nvim-colorizer.lua"

**To Reproduce**
1. :PackerClean
2. :PackerSync

**Expected behavior**
It should get updated without any issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/24288879/189126802-ee76bdb0-c9a2-476f-9475-b6c405a896a5.png)

**Desktop (please complete the following information):**
 - Manjaro Linux (Arch)
 - Kitty
 - Neovim 7.2

**Comment by Akianonymus** [comment]
Just `rm -rf ~/.local/share/nvim/site/pack/packer/opt/nvim-colorizer.lua`
