### ISSUE TITLE
Jump forward `<C-i>` just switch buffer

### ISSUE THREAD

**Issue by dvogt23** [NvChad/NvChad#1551]
**Describe the bug**
After jumping through files with `<C-o>` it should be possible to jump forward with `<C-i>` but this just jump to the next buffer, instead of forward the jumplist.

**To Reproduce**
1. Open source code file with lsp included
2. Jump to definition of a function usage
3. Jump deeper into other definitions
4. Jump back sometime with `<C-o>`
5. Jump "forward" with `<C-i>` (just goto next buffer instead)

**Expected behavior**
Jump forward in jumplist...

**Screenshots**
I did just goto definition and jump back with C-o. With C-i wanna jump forward, but it move to next buffer.

![Kapture 2022-09-08 at 15 22 39](https://user-images.githubusercontent.com/9352647/189133477-cab5b05a-93a8-449f-9018-fa93f2b5d244.gif)

BTW same for jump between search with `/text` and `n` sometimes jump back and forward not possible...

**Comment by Akianonymus** [comment]
Is this different from the behaviour with `nvim -u None` ?

**Comment by dvogt23** [comment]
Ahw damn, its missing in nvim 😢 `vim -u None` works ...

**Comment by Akianonymus** [comment]
@dvogt23 Maybe create a issue in neovim github repo.

**Comment by dvogtfstr** [comment]
ye will do... doc says it should be possible https://neovim.io/doc/user/motion.html#CTRL-I

**Comment by anstadnik** [comment]
The problem is that if `<Tab>` is mapped it also maps `<C-i>` which is a vital feature of nvim. [Link](https://stackoverflow.com/a/16209534)
Adding `<Tab>` to disabled mapping list fixed the issue, though IMHO it should not be mapped by default.

**Comment by fernandovmacedo** [comment]
`CTRL-i` and `<TAB>` works fine in Neovim. To fix the issue in Nvchad, you have to change the mapping of `<TAB>` in `lua/core/mappings.lua:85`. 

I have changed the original mapping to `S-TAB` and deleted the `goto prev buffer` that was mapped to `S-TAB`.

**Comment by gam-phon** [comment]
Using Mac, in Alacritty config file:
```
key_bindings:
   - { key: I, mods: Control, chars: "\x1b[105;6u" }
```
This fix the issue for me. Now I can use ```Tab``` and ```Ctrl-I```

**Comment by LinuxIsCool** [comment]
@gam-phon You are a genius. Thanks for sharing that!!! So amazing to be able to have `<c-i>` seperate from `<TAB>`

BTW I'm on linux and it's working.

**Comment by gam-phon** [comment]
@LinuxIsCool Thanks. I am happy that was helpful.

**Comment by cloversmith** [comment]
> @gam-phon You are a genius. Thanks for sharing that!!! So amazing to be able to have `<c-i>` seperate from `<TAB>`
> 
> BTW I'm on linux and it's working.

hey, this doesn't work in alacritty for me i'm on linux, did you just add exact same line?

i'm on fedora 40 with x

though in kitty terminal it works by adding this `map ctrl+i send_text all \x1b[105;6u`
