### ISSUE TITLE
Cursive fonts like in VSCode

### ISSUE THREAD

**Issue by tushargoyalofficial** [NvChad/NvChad#1552]
**Is your feature request related to a problem? Please describe.**
I was a VSCode user for very long time. I was using Cascadia Code font with Font ligatures and cursive font. Now I am fully switched to NVIM. If by any chance, can you add some themes with cursive font support with other themes.

**Describe the solution you'd like**
Smooth fonts with cursive letter and font ligatures 

**Describe alternatives you've considered**
No alternatives.

**Additional context**
None

**Screenshot**
![image](https://user-images.githubusercontent.com/24288879/189134641-996f48a2-f98a-402b-95f7-7042583a69c4.png)

**Comment by lucario387** [comment]
How is this in any part related to NvChad's, or bigger, Neovim's configuration?
It takes the font from `guifont`, and if not set, your terminal's font
So if you want some fancy font inside Nvim, set such font to be the default terminal font

**Comment by siduck** [comment]
not a nvchad issue
