### ISSUE TITLE
error running config for ui

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1556]
**Describe the bug**
updated nvchad and this error is comming again and again
![image](https://user-images.githubusercontent.com/78728701/189423302-b010d586-0795-4562-a5d5-d9111214bcd3.png)

**Desktop (please complete the following information):**
 - manjaro
 - Terminal : kitty
 - Version of Neovim : NVIM v0.7.2

**Additional context**
was working fine before update

**Comment by Aneeqasif** [comment]
and also i cant understand the error this plugin syntax is depricated use new one , which syntax is new one i think i have did the same as mentioned on website

**Comment by Spell28** [comment]
new syntax must be:
chadrc.lua
`
local overrides = require "custom.override"

M.plugins = {
     ["goolord/alpha-nvim"] = {
       disable = false,
       override_options = overrides.alpha,
     },
}
`
override.lua (or something)
`
M.alpha = {
  header = {
    type = "text",
    val = logo,
    opts = {
      position = "center",
      hl = "AlphaHeader",
    },
  },
}
`

**Comment by Spell28** [comment]
new syntax must be:
chadrc.lua
```
local overrides = require "custom.override"

M.plugins = {
     ["goolord/alpha-nvim"] = {
       disable = false,
       override_options = overrides.alpha,
     },
}
```
override.lua (or something)
```
M.alpha = {
  header = {
    type = "text",
    val = logo,
    opts = {
      position = "center",
      hl = "AlphaHeader",
    },
  },
}`

**Comment by siduck** [comment]
new plugin syntax example https://github.com/NvChad/example_config

**Comment by siduck** [comment]
also please do packersync, I'm unable to reproduce your error

**Comment by Aneeqasif** [comment]
> 
 got it , thanks for help.
