### ISSUE TITLE
having issue in python support

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1558]
**Describe the bug**
so i am trying to install [vim-jukit](https://github.com/luk400/vim-jukit) which needs python support and i have tried all things on the internet but it is not working `echo has(python3)` returns 0 ,
py3 print('cool')
`E319: No "python3" provider found. Run ":checkhealth provider"     `
checkhealth provider gives

![image](https://user-images.githubusercontent.com/78728701/189483173-471905f7-3524-4232-8869-f1d50c942535.png)

**things i have tried **
- python -m pip uninstall neovim pynvim     
- python -m pip install --user --upgrade pynvim
- `vim.g.python3_host_prog = '/usr/bin/python3' `
   `vim.g.python2_host_prog = '/usr/bin/python2'`
  ` vim.g.loaded_python3_provider=1`

also 
`vim.cmd([[ let g:loaded_python3_provider=1`

**Desktop (please complete the following information):**
 - Operating System : manjaro
 - Terminal: kitty
 - Version of Neovim : 0.7.2

**Additional context**
[vim-jukit] python3 support missing! (`:echo has('python3')` returned 0) 
Press ENTER or type command to continue   

i get this also on startup

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/1417

**Comment by Aneeqasif** [comment]
> #1417

this worked and the required plugin is working but when i press C-n for nerdtree it got following error

![image](https://user-images.githubusercontent.com/78728701/189495906-b258ad84-46c8-4563-a996-1cd1d59da5d3.png)

**Comment by Aneeqasif** [comment]
one more thing that u might can help me with
how should i write 
` <localleader>li  <Plug>(vimtex-info)                n `
[this kind](https://darkalexwang.github.io/2016/09/27/vimtex-default-key-mappings/)  of keymapings in lua
