### ISSUE TITLE
No longer able to force plugin to load on startup if it's lazyload by default

### ISSUE THREAD

**Issue by lucario387** [NvChad/NvChad#1559]
**Describe the bug**
Before the new syntax change, one can remove a plugin through `plugin.remove` then re-add them in `plugin.user` to complete override them (force the plugin to load on start as an example).

With the new syntax, this is no longer possible

**To Reproduce**
Example plugin: `plenary.nvim`

- Install NvChad
- Create `custom/chadrc.lua` with the following content
```lua
local M = {}
M.plugins = {
	["nvim-lua/plenary.nvim"] = {
             module = "", -- cannot set module=nil, as then nothing will happen
	},
}
return M
```
- Check `~/.local/share/nvim/site/pack/packer/start`

**Expected behavior**
Before the syntax change: We can force load plenary.nvim on startup, and find `plenary.nvim` inside `start`
Now: It is no longer possible, will always show in `opt`

**Desktop (please complete the following information):**
 - Operating System: Arch Linux 
 - Terminal: kitty
 - Version of Neovim: NVIM v0.8.0-dev-1060-g22a88c425e

**Additional context**
OS, Terminal and Neovim version should not matter, this is a parsing issue

**Comment by lucario387** [comment]
New (old) bug returning, fun ig.

**Comment by lucario387** [comment]
To be more specific, before the syntax change, with a default plugin table such as

```lua
M.plugins = {
    ["foo"] = {
        module = "bar",
    }
}
```

and a custom table like

```lua
-- custom/chadrc.lua
M.plugins = {
    remove = {
        "foo",
    },
    user = {
      ["foo"] = {
          module = nil,
      },
    }
}
```

will result in a table like below

```lua
M.plugins = {
    ["foo"] = {},
}
```

With the new syntax, this will always be

```lua
M.plugins = {
    ["foo"] = {
        module = "bar",
    }
}
```

**Comment by siduck** [comment]
load plenary at VimEnter
