### ISSUE TITLE
Errors in user config cause silent failure

### ISSUE THREAD

**Issue by Algorhythm-sxv** [NvChad/NvChad#1560]
## Previously this issue was titled "NvChad cannot find custom/chadrc.lua on Windows 10", which was a symptom of the underlying issue

**Describe the bug**
A syntax error somewhere in the user configuration from `chadrc.lua` causes configuration to silently fail and fall back on default config

**To Reproduce**
1. Introduce a syntax error in `chadrc.lua` or in a `require`d file

**Expected behavior**
An error or at least a warning is reported

**Desktop (please complete the following information):**
 - Operating System: Windows 10
 - Terminal: cmd.exe, Neovide
 - Version of Neovim: 0.7.2

**Comment by VuiMuich** [comment]
Same on:
- Operating System: Linux, 5.19.1-3-MANJARO
- Terminal: Alacritty 0.10.1
- Version of Neovim: 0.7.2

**Comment by lucario387** [comment]
Can you elaborate more about the reproduction procedure
I cannot reproduce the above behavior in base nvchad

**Comment by Algorhythm-sxv** [comment]
Unfortunately I don't know if this is specific to the system I'm running on (company laptop, nvchad works fine on my linux desktop) or a Windows issue in general, I just detailed the steps I went through to get to this point. I don't know enough about nvim/lua to be able to say where `require` would look for `custom.chadrc`. I just tried doing a fresh install and I have reproduced the problem.

What influences where `require` looks for files? Are there any changes I can make to core/utils.lua that might give better diagnostics on what is actually going wrong?

**Comment by siduck** [comment]
does your chadrc return a table? 

ok use this folder as your custom folder https://github.com/NvChad/example_config 

and re-open nvim & do a packersync

**Comment by Algorhythm-sxv** [comment]
Here is the content of my chadrc.lua, copied from my working linux system:

```lua
M = {}

M.ui = {
  theme = "kanagawa"
}

M.plugins = require "custom.plugins"
M.mappings = require "custom.mappings"

return M
```
Cloning the example config works, `:PackerSync` installs the 2 new plugins. Very confusing

**Comment by Algorhythm-sxv** [comment]
Confusing because the chadrc from the example repo is detected but the chadrc I made is not. The code inside should work fine, it's the same from my working linux machine, but chadrc.lua in the exact same location just isn't getting run at all. I can even introduce a syntax error and not get any errors when starting nvim.

**Comment by siduck** [comment]
does this chadrc work on your windows machine :

```lua
local M = {}

M.ui = {
   theme = "gruvchad"
}

return M
```

**Comment by Algorhythm-sxv** [comment]
That works, the theme is changed correctly. Digging into my config revealed that there was a typo in my mappings.lua file. Fixing that made chadrc run correctly and my plugins were installed.

I won't close this issue immediately since I think it is a bug that errors in the user config silently break everything... If there is a way to get error details from `pcall(require, ...)` or avoid it by properly testing the existence of the chadrc.lua file I think that should be done.

I could have a go at this a bit later and make a PR, unless that would be trivial for a more experienced lua programmer

**Comment by VuiMuich** [comment]
I used the `chadrc.lua` from the example repo and for me the problem was, that I hadn't populated `~/.config/nvim/lua/custom/plugins` so commenting out the import solved.
```lua
local M = {}

M.ui = {
  theme_toggle = { "everforest", "everforest_light" },
  theme = "everforest",
}

-- currently don't have custom plugin set, so don't try to import as it makes chadrc.lua fail silently
-- M.plugins = require "custom.plugins"

-- check core.mappings for table structure
M.mappings = require "custom.mappings"

return M
```

**Comment by dgmora** [comment]
I had a similar issue. While there is documentation, it is not complete and it's not easy to understand what has to go into what file. For instance, [here](https://nvchad.com/config/plugins#install-remove-plugins--override-them) it mentions only one of the required lines in chadrc). There are also no errors, so I was trying to enable `whichkey` but the plugin wasn't getting installed. If there'd be at least an error, it would be easier to see what's the issue. I could only get what was going on after finding this github issue.

**Comment by siduck** [comment]
you can refer to https://github.com/NvChad/example_config

**Comment by dgmora** [comment]
> hi @dgmora if you use the dev branch of nvchad, you wont face this issue. errors wont be swallowed again!

Ah nice, didn't see that!
