### ISSUE TITLE
Any way to use nvchad visual enhancements in custom nvim configuration

### ISSUE THREAD

**Issue by asyncee** [NvChad/NvChad#1561]
Hi, I love nvchad and currently trying to move my neovim's configuration to it.

But actually the process is going bad. I have met following issues migrating from [my current configuration](https://github.com/asyncee/dotfiles/tree/master/nvim):

1. Silent failures while adding extra plugins to `custom/plugins/init.lua`: sometimes vim just ignores whole configuration and loads with defaults. That may happen if there are typo, or maybe plugin requires another plugin or maybe one just applied wrong configuration. I have found no information in logs about the reasons of such behavior, it looks like configuration errors are muted.
2. Some plugins became incompatible with each other: `which-key` and `legendary.nvim` are not working together in any configuration (i tried multiple different approaches to configure them) and giving an error about `which-key` having an already defined trigger.
3. Can't disable mappings. Doing everything exactly as said in documentation but default mappings still working.

So the question is: are there any way to use best of nvchad (tabufline, statusline, themes) with my custom configuration?

Thanks.

**Comment by siduck** [comment]
please read the docs well. 

2. Remove lazyloading of whichkey if that helps and if it still doesnt work then its not a nvchad issue 
3. Check the disable field in the mapping docs 

No you cant use nvchad visual enhancements in your config
