### ISSUE TITLE
There is no way to remove `module` option from plugins

### ISSUE THREAD

**Issue by cj** [NvChad/NvChad#1565]
**Describe the bug**
There is no way to remove `module` option from here https://github.com/NvChad/NvChad/blob/main/lua/plugins/init.lua#L3. https://github.com/sindrets/diffview.nvim does not work with `module = "plenary"`

**To Reproduce**
Install https://github.com/sindrets/diffview.nvim, the plugin will not load.

```
  ["sindrets/diffview.nvim"] = {
    requires = "nvim-lua/plenary.nvim",
  },
```

**Expected behavior**
`:DiffviewOpen` cmd to work

**Desktop (please complete the following information):**
 - osx 12.5.1
 - Item 3.4.16
 - NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by cj@cj-air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

**Comment by siduck** [comment]
```lua
["nvim-lua/plenary.nvim"] = { rm_default_opts = true }
```
in your custom config. Read https://github.com/NvChad/NvChad/commit/2e5aa786ef542990f2b0808bc7c3cfdfd9218f0b#commitcomment-83692486

**Comment by lucario387** [comment]
Use the new rm_default_opts option in your plenary-nvim override to make it use only your configuration

**Comment by cj** [comment]
@siduck @lucario387 Thank you - that worked!
