### ISSUE TITLE
Parser not available for language tsserver

### ISSUE THREAD

**Issue by griffinevans** [NvChad/NvChad#1567]
**Describe the bug**
When opening a file after copying the example custom configuration, I get an error:
`packer.nvim: Error running config for nvim-treesitter: ...cker/opt/nvim-treesitter/lua/nvim-treesitter/
install.lua:377: Parser not available for language tsserver`
This happens even when I completely uninstall and reinstall nvchad.

**Desktop (please complete the following information):**
 - Operating System Linux 5.19.8-arch1-1
 - Terminal kitty
 - Version of Neovim 0.7.2

**Additional info**
This only happens with the example custom configuration, so I assume it's an issue there.

**Comment by siduck** [comment]
typescript javascript tsx 

these are the parser names

**Comment by guicattani** [comment]
@griffinevans you need to remove `tsserver` from `lua/custom/plugins/lspconfig.lua` and `lua/custom/plugins/overrides.lua` :)
