### ISSUE TITLE
Alpha no longer open by default with disable=false

### ISSUE THREAD

**Issue by bkalbs-wm** [NvChad/NvChad#1568]
**Describe the bug**
I just updated my config using the new plugin syntax outlined in #1518 and have got everything working the way it was before the update. The one exception is that I can no longer get the Alpha dashboard to open by default when starting `nvim`. Before the syntax update, setting `["goolord/alpha-nvim"] = { disable = false }` did the trick, but this is no longer the case for me.

I am not certain if this is a bug, or if I missed something in the config update, but I did not see anything specific in the docs or in the issue thread, and I mostly copied from the [Example Config](https://github.com/NvChad/example_config) to update the plugin config. Other than opening by default, everything else about Alpha is working as expected for me.

I also checked the Alpha issue queue but nothing jumped out at me there. Apologies if this is not the correct place to post this.
 
**To Reproduce**
After updating to the new config syntax, in your custom folder, override the `disable` property in the Alpha config and open `nvim`. 
ex. `["goolord/alpha-nvim"] = { disable = false }`

**Expected behavior**
Expected: Alpha dashboard should be open by default. 
Actual: Must use cmd `:Alpha` to open regardless of the `disable` setting.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: _OSX 10.15_
 - Terminal: _iTerm 3.4_
 - Version of Neovim: _v0.7.2_

**Additional context**
Here is my config in `/.config/nvim/lua/custom/plugins/init.lua`
```
local overrides = require "custom.plugins.overrides"

return {

  ["goolord/alpha-nvim"] = {
    disable = false,
    cmd = "Alpha",
    override_options = overrides.alpha,
  },

  ["neovim/nvim-lspconfig"] = {
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.plugins.lspconfig"
    end,
  },

  -- override default configs
  ["kyazdani42/nvim-tree.lua"] = {
    override_options = overrides.nvimtree,
  },

  ["williamboman/mason.nvim"] = {
    override_options = overrides.mason,
  },

  ["kdheepak/lazygit.nvim"] = {},
}
```

and my overrides at `/.config/nvim/lua/custom/plugins/overrides.lua`
```
local M = {}

M.nvimtree = {
   open_on_setup = true,
   open_on_setup_file = true,
   git = {
    enable = true,
  },

  renderer = {
    highlight_git = true,
    icons = {
      show = {
        git = true,
      },
    },
  },
}

M.alpha = {
  header = {
    val = {
      "             ___            ___  ",
     "            (o o)          (o o) ",
    "           (  V  ) bkalbs (  V  ) ",
    "           --m-m------------m-m--",
    "                                     ",
    "    Your day is going to be a real hoot!  ",
    },
  },
}

M.mason = {
  ensure_installed = {
    "lua-language-server",
    "stylua",
    "css-languageserver",
    "html-lsp",
    "typescript-language-server",
    "graphql-lsp",
    "golangci-lint-langserver",
    "golangci-lint",
    "yaml-language-server",
    "phpactor",
    "docker-langserver",
  },
}

return M

```

**Comment by lucario387** [comment]
Remove the cmd = "Alpha" line

**Comment by bkalbs-wm** [comment]
@lucario387 ah thank you. That worked. Its weird bc I did try removing that line last night and it didn't seem to do anything, but I think I maybe I forgot to do another `:PackerSync` last time. After removing that line and `:PackerSync` it's all good now. Apologies for the noise, but I appreciate the quick help.
