### ISSUE TITLE
Add Volar extension

### ISSUE THREAD

**Issue by vnepluev** [NvChad/NvChad#1569]
Hi! Add pls Volar ext to editor. Vue 2 > Vue 3

**Comment by siduck** [comment]
@vnepluev we dont add language related things, vue is helpful to you but not to others, just read our custom lspconfig docs and setup volar lsp . SIMPLE

**Comment by vnepluev** [comment]
Setup install already package Vue 2. May be change this package to Vue 3 (Volar)?

**Comment by siduck** [comment]
check volar section in lspconfig server configurations readme

**Comment by vnepluev** [comment]
Thx, im new user vim. It would be nice to make a cheat sheet on the main editor commands

**Comment by siduck** [comment]
> Thx, im new user vim. It would be nice to make a cheat sheet on the main editor commands

there already many, check quickref.me/vim
