### ISSUE TITLE
Pressing the p key in normal state of `nvim` has a certain chance of triggering `nvim` jamming 

### ISSUE THREAD

**Issue by nerdneilsfield** [NvChad/NvChad#1571]
**Describe the bug**

Pressing the p key in normal state of `nvim` has a certain chance of triggering `nvim` jamming 

**To Reproduce**
1. Go to ' any edit page'
2. Click on 'p'

That jamming would not always trigger.

**Expected behavior**

Trigger the `yank` function.

**Screenshots**

No screenshots yet.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Terminal: Windows Terminal to ssh to Ubuntu server
 - Version of Neovim: v0.7.2

**Additional context**
No more additional context

**Comment by siduck** [comment]
Im unable to reproduce this issue. Copy something ( yank , go to visual mode and press y) and then in normal mode press p to paste

**Comment by siduck** [comment]
show a video of your behaviour so I can try to produce it here

**Comment by nerdneilsfield** [comment]
I found the issue was caused by [cmp-tabnine](https://github.com/tzachar/cmp-tabnine)
