### ISSUE TITLE
How to disable arrow keys?

### ISSUE THREAD

**Issue by nanofiles** [NvChad/NvChad#1573]
Hello

I have problem with disable arrow keys. I want to learn to use HJKL keys.

I added to mappings.lua

```
M.disabled = {
	n = {
		["<Up>"] = "",
		["<Down>"] = "",
		["<Left>"] = "",
		["<Right>"] = "",
	},
}
```

But this doesn't work. What I should add to mappings to disable arrow keys?

OS: Arch Linux
Terminal: kitty

**Comment by siduck** [comment]
the disabled field is for disabling default keys used in nvchad. just map all arrow keys to `<Nop>`
```lua
M.abc = {
  n = {
    ["<Up>"] = { "<Nop>", "abc" },
  },
```
