### ISSUE TITLE
Theme toggle broken

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1578]
**Describe the bug**
Set a dark theme and light theme, then use `<leader>tt` and it will only partially change the theme.

![image](https://user-images.githubusercontent.com/4793438/191329653-1216db52-62c1-46eb-b456-1e250af307cb.png)

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/191391438-09d20d3c-f79e-4d85-a476-e2522947bd01.mp4

totally looks like your terminal issue. I cant even reproduce this

**Comment by siduck** [comment]
Also fyi theme toggle related code wasnt even touched since months so its obviously an issue at your end, I tried with different terminals and it works for me.

**Comment by danjenson** [comment]
Try enabling `andreadev-it/Shade.nvim` as you have in your custom config, then switch themes

**Comment by danjenson** [comment]
can we make this compatible with `Shade.nvim`?
