### ISSUE TITLE
Chad does not respect custom config options

### ISSUE THREAD

**Issue by gegnew** [NvChad/NvChad#1582]
As described:

> @siduck it should be
> 
> ```lua
> local enable_providers = {
>       "python3_provider",
>     }
> for _, plugin in pairs(enable_providers) do
>     vim.g["loaded_" .. plugin] = nil
>     vim.cmd("runtime " .. plugin)
> end
> ```
> 
> in `custom/init.lua`, yes?
> 
> This does not work for me. Nor does:
> 
> ```lua
> vim.g['loaded_python3_provider'] = nil
> vim.cmd("runtime python3_provider")
> ```
> 
> However, running those manually _after_ starting nvim does work. It seems like something is still borked in the order of how options are getting loaded.
> 
> For instance:
> 
>     * If I set `opt.scrolloff = 3` in `custom/init.lua`, then Nvim picks it up fine (`:set scrolloff` returns '3'). Note that `scrolloff` is _not_ set in `core/options.lua`.
> 
>     * If I set `opt.updatetime = 150` (it is set to 250 in `core/options.lua`), then `:set updatetime` returns 250

I think this is a bigger issue

_Originally posted by @gegnew in https://github.com/NvChad/NvChad/issues/1230#issuecomment-1250937643_

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/191513253-a2f14a17-ad89-4183-aff8-cb708b6d56ae.mp4

enabling providers do work

**Comment by siduck** [comment]
opt.updatetime works in custom/init.lua

https://user-images.githubusercontent.com/59060246/191514156-26ff3a20-d3d2-4a1e-9732-e49dec2f08d4.mp4

**Comment by martin-braun** [comment]
I also had problems loading additional Lua files from my `custom/init.lua`. Lua can't load relative paths, I had to require files with `require("custom.file")` to get the file loaded from the same path. No error was thrown on fail, I guess it is silent due to `pcall`.

**Comment by gegnew** [comment]
It turns out the issue is just that anything below an incorrect config line is not read, and silently fails

**Comment by martin-braun** [comment]
@gegnew Yes, the silent error thing is annoying. I think it is the case for syntax highlighting, so you can install Lua and run init.lua and chadrc.lua to make sure you are free of errors. Also on debugging I have to print two lines to block Neovim to show the output, because it would often just eat single-line prints.
