### ISSUE TITLE
Error setting up vimspector in nvchad - Editor commands and functions not available

### ISSUE THREAD

**Issue by h4r1337** [NvChad/NvChad#1583]
I tried to configure vimspector as the debug adapter for my neovim NvChad setup, but unfortunately I am not able to use any editor commands of vimspector.

![image](https://user-images.githubusercontent.com/72344536/191481410-b9575aa0-65d6-47c1-8174-49c6960d27a4.png)
This is how it shows when I try to run `:call vimspector#Launch()`
Here from the `:PackerStatus` command output it is clear that the plugin is installed. I don't know why the command is not available
![image](https://user-images.githubusercontent.com/72344536/191484104-e849f42a-dbe1-4e7d-9caa-3bf9e1310c8b.png)

**Neovim version:**
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457
```
**Config:** https://github.com/h4r1337/dotfiles/tree/main/config/nvchad

I'm not sure whether this is an NvChad bug or not.

**Comment by siduck** [comment]
yes this doesnt work for me too, does this plugin work only for vim and older nvim versions?

**Comment by h4r1337** [comment]
Is that really necessary to disable these providers? Or is there any way to override only these changes?

**Comment by siduck** [comment]
@h4r1337 

```lua
local enable_providers = {
      "python3_provider",
    }
for _, plugin in pairs(enable_providers) do
    vim.g["loaded_" .. plugin] = nil
    vim.cmd("runtime " .. plugin)
end
```

Thats for the table above default_providers. 

and for the default_providers
```lua
vim.g.['loaded_ruby_provider'] = 1
```

**Comment by h4r1337** [comment]
@siduck 
Thanks, that works fine for me...
Should we add a note or  something on this issue?
Also I couldn't find any useful resources from NvChad docs to implement a debugger support to my config. So I think it would be much better if you could add something like a note for other users somewhere...
If there's nothing left to discuss we can close this issue.

**Comment by siduck** [comment]
@h4r1337 so vimspector works now?

**Comment by siduck** [comment]
Also i think users will use nvim-dap more, Its upto them!
