### ISSUE TITLE
packer.nvim: nvim/lua/plugins/configs/statusline.lua:8: loop or previous error loading module 'base46'

### ISSUE THREAD

**Issue by DeyunLuo** [NvChad/NvChad#1584]
when I open nvim，I have the error
NvChad is already update the latest and rerun PackerSync.
<img width="1229" alt="Screen Shot 2022-09-21 at 23 44 53" src="https://user-images.githubusercontent.com/32233191/191550220-66bbceb7-9c78-497a-aebf-63ac10f4c232.png">
#1195

**Comment by siduck** [comment]
unable to reproduce this error. do a clean install.
