### ISSUE TITLE
Going back a word not working (capital B)

### ISSUE THREAD

**Issue by jamesla** [NvChad/NvChad#1585]
I am trying to go back a word (whitespace) which in vim is normally capital b.

However nvchad just creates an empty buffer?

Is this expected behaviour in nvchad? If so how can I revert to the normal vim behavior?

**Comment by siduck** [comment]
update your nvchad to the latest, Shift + b was an old command and it got removed long ago.

https://user-images.githubusercontent.com/59060246/191631287-eedd2c56-1d87-4e31-a309-93bf28182a10.mp4




![image](https://user-images.githubusercontent.com/59060246/191631346-124a4cd8-e5a1-47c4-b3c3-ff17c309dfb6.png)
