### ISSUE TITLE
NvChad not loading plugins automatically on startup

### ISSUE THREAD

**Issue by jamesla** [NvChad/NvChad#1593]
I am having an issue where my packer plugins are not initializing correctly.

Effectively it initialises fine the first time but then I have to run :PackerSync every time I open nvim. I made a quick video.

https://user-images.githubusercontent.com/5243178/192068190-032c992e-d0bf-45a6-abaf-7eff9b5e7c0f.mp4

I initially thought this was a packer problem however after posting here https://github.com/wbthomason/packer.nvim/issues/1077 he  seems to think that it's because packer is not being initialised properly and since that's done by nvchad I'm hoping I can get some help here.

I've made my whole `~/.config/nvim` directory available here: https://github.com/jamesla/nvchad

Steps to reproduce:

1. uninstall nvim
2. copy my configs in place to `~/.config/nvim`
3. open nvim
4. it will initialise as normal
5. close nvim
6. open it and it won't have loaded anything
7. you can manually load packer with `packadd packer.nvim` and then run `:PackerSync` and it should work however next time you reopen it you will need to do it again.

I have no idea what I have done to break this so any help is greatly appreciated

**Comment by siduck** [comment]
plugins are lazy loaded

**Comment by siduck** [comment]
also this looks like a nixos issue, cant help.

**Comment by jamesla** [comment]
I am using nixos but it's nothing to do with nixos as I have reproduced on my mac.

If you take a look at my linked configs and follow the steps to install you'll see it's not a nixos thing.

**Comment by siduck** [comment]
@jamesla does this happen with vanilla nvchad config? ( with no custom config at all )

**Comment by jamesla** [comment]
I just uninstalled nvchad and then deleted ~/.config/lua/custom on macos and nvchad works fine (just without my config)

**Comment by siduck** [comment]
so your custom config is the issue :fearful:

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/192077232-08ce1845-91ca-47eb-874e-0ad401a4bd6b.png)

:thinking:
