### ISSUE TITLE
nvim tree adaptive_size always reset other splited window ratio to 0.5

### ISSUE THREAD

**Issue by theowenyoung** [NvChad/NvChad#1597]
**Describe the bug**

There is a report on https://github.com/NvChad/nvterm/issues/22 , but it seems that it isn't an issue of nvterm. it seems about nvim tree. 

When nvim tree is active, then press `<M-h>`, split a terminal window below, then switch the window to the main window by `<C-x><C-w>k`, the terminal window height will be resized to `0.5` ratio.

I also record a video screenshot:

https://user-images.githubusercontent.com/62473795/192158974-b51effac-c43f-4378-afc0-f5b1eb5669bd.mov

when change `adaptive_size` to `false`, it will be fixed. but I'm new to vim, I don't know how to fix it without changing the option.

https://github.com/NvChad/NvChad/blob/27560319cc4cf753e5a4d8713f82206d84a70d61/lua/plugins/configs/nvimtree.lua#L26

**To Reproduce**

The whole operations:

```
nvim
:edit test.txt
<C-n>
<C-l>
<M-h>
<C-x><C-w>k
```

**Expected behavior**

do not change the window size.

**Desktop (please complete the following information):**
 - Operating System: Macos
 - Terminal: terminal.app
 - Version of Neovim: 0.8.0

**Additional context**

**Comment by theowenyoung** [comment]
It seems even `adaptive_size = true` when I select the file from `nvim tree`, the terminal window is still set to 0.5 ratio.

**Comment by siduck** [comment]
yep this is a nvimtree issue so closing this.

**Comment by Elandig** [comment]
This fixes this issue: https://github.com/NvChad/nvterm/issues/22#issuecomment-1369720875

I believe NvChad should make it a default, it is so annoying imho.
