### ISSUE TITLE
Cannot change clipboard to unnamed in custom/init.lua

### ISSUE THREAD

**Issue by tsetsee** [NvChad/NvChad#1605]
**Describe the bug**
Cannot change clipboard to "unnamed" in custom/init.lua. It always shows clipboard=unnamedplus. 

**Expected behavior**
`set clipboard?` -> `clipboard=unnamed`

**Desktop (please complete the following information):**
 - Operating System - ArchLinux 5.19.11-arch1-1
 - Terminal - Konsole
 - Version of Neovim - 
 ```
 NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/192694780-59e60ddd-83b0-459c-adfd-2112678d9475.mp4

works fine here

**Comment by tsetsee** [comment]
It's working right after I comment the line (vim.go.EditorConfig_exclude_patterns).
```lua
vim.opt.cursorline = true
vim.opt.timeoutlen = 500
-- vim.go.EditorConfig_exclude_patterns = {'fugitive://.*', 'scp://.*'}
vim.opt.clipboard = "unnamed"
vim.opt.nofoldenable = true

```

**Comment by siduck** [comment]
@tsetsee so most probably that option is invald or something's wrong with its syntax. 

If such is the case then anything after the line wont execute.

**Comment by tsetsee** [comment]
ok thanks
