### ISSUE TITLE
packer.nvim: Error running config for base46: ...are/nvim/site/pack/packer/opt/base46/lua/base46/init.lua:63: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by WingDust** [NvChad/NvChad#1606]
**Describe the bug**

**To Reproduce**
`nvim` report `packer.nvim: Error running config for base46: ...are/nvim/site/pack/packer/opt/base46/lua/base46/init.lua:63: bad argument #1 to 'pairs' (table expected, got nil)`
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System mac
 - Terminal iterm2
 - Version of Neovim 0.7.2

**Additional context**

**Comment by siduck** [comment]
rm -rf .local/share/nvim

and reopen nvim
