### ISSUE TITLE
indent lines disappear when I start moving the cursor

### ISSUE THREAD

**Issue by AlexNomadrg** [NvChad/NvChad#1607]
**Describe the bug**
no indent lines. It started happening after I updated nvchad

**To Reproduce**
1. open a file
2. move cursor 

**Expected behavior**
yes indent lines

**Screenshots**
not screenshot but video

VIDEO: https://youtu.be/B2Sxw5RD4l0

**Desktop (please complete the following information):**
 - Operating System linux (i use arch btw)
 - Terminal kitty
 - Version of Neovim latest version available in arch repos

**Additional context**
nvchad.lua: https://pastebin.com/qKV19NTx

i want my lines back ;(

**Comment by siduck** [comment]
no clue! does this happen with all the languages?

**Comment by asher-gh** [comment]
I noticed something similar with context highlighting and changing the `IndentBlanklineContextStart` table in the `hl_overridees` worked out for me.

**Comment by siduck** [comment]
what did you change? @asher-gh

**Comment by asher-gh** [comment]
```
M.overrides = {
	IndentBlanklineContextStart = { bg = "darker_black" },
}
```

**Comment by siduck** [comment]
hmm doesnt the current one look a little lighter than editor bg ? so it should be visible

**Comment by siduck** [comment]
@AlexNomadrg any updates on this?

**Comment by Lucifer-02** [comment]
@siduck Btw, How to customize indent color?
![image](https://user-images.githubusercontent.com/84069686/231331697-dd71457a-bad6-420b-bd0c-c0905125d7c5.png)
You can see it has a pretty matte color
I checked "indent-blankline.nvim" repo but could not find instructions to change color in this case.

**Comment by siduck** [comment]
> @siduck Btw, How to customize indent color? ![image](https://user-images.githubusercontent.com/84069686/231331697-dd71457a-bad6-420b-bd0c-c0905125d7c5.png) You can see it has a pretty matte color I checked "indent-blankline.nvim" repo but could not find instructions to change color in this case.


https://nvchad.com/docs/config/theming 
https://github.com/NvChad/base46/blob/v2.0/lua/base46/integrations/blankline.lua

**Comment by Lucifer-02** [comment]
> > @siduck Btw, How to customize indent color? ![image](https://user-images.githubusercontent.com/84069686/231331697-dd71457a-bad6-420b-bd0c-c0905125d7c5.png) You can see it has a pretty matte color I checked "indent-blankline.nvim" repo but could not find instructions to change color in this case.
> 
> https://nvchad.com/docs/config/theming https://github.com/NvChad/base46/blob/v2.0/lua/base46/integrations/blankline.lua

After a day of trying, I was able to follow your instructions
