### ISSUE TITLE
Matchit plugin not working

### ISSUE THREAD

**Issue by tsjordan-eng** [NvChad/NvChad#1610]
With a new install of the latest NvChad, the Matchit plugin does not work. It works for single characters, but not for matching words.

It is enabled by default in neovim. You can test this by opening an xml file. The `%` key in normal mode lets you jump from xml tag to its match. 

It works without the NvChad config: `nvim -u /dev/null`.

I searched the code but couldn't find anything that directly remaps the `%` key or disables `matchit`.

**Comment by siduck** [comment]
its disabled by default, enable it in  your custom init.lua

```lua
vim.g.loaded_matchit = 0
```

**Comment by tsjordan-eng** [comment]
ah yes, thanks! I added
`vim.g.loaded_matchit = nil` because `0` didn't work

This can be closed.
