### ISSUE TITLE
format stylua not working

### ISSUE THREAD

**Issue by DeyunLuo** [NvChad/NvChad#1613]
![Screen Shot 2022-09-29 at 17 33 25](https://user-images.githubusercontent.com/32233191/192996475-8aefeeaf-0fd8-43cf-b299-4bb76779dce2.png)

**custom/chadrc.lua**
```
-- Just an example, supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.ui = {
  theme = "onedark",
  -- theme = "chadracula",
}

M.mappings = require "custom.mappings"

M.init = require "custom.init"

local plugin_confs = require "custom.plugins.configs"

M.plugins = {
  user = {
    ["williamboman/mason.nvim"] = plugin_confs.mason_nvim,
    ["kyazdani42/nvim-tree.lua"] = plugin_confs.nvimtree,
    ["neovim/nvim-lspconfig"] = plugin_confs.lspconfig,
    ["jose-elias-alvarez/null-ls.nvim"] = plugin_confs.null_ls,
  }
}

return M
```
**custom/plugins/configs.lua**
```
local M = {}

M.mason_nvim = {
  ensure_installed = {
    -- lua stuff
    "lua-language-server",
    "stylua",
    "clangd",
    "clang-format",

    -- shell
    "shfmt",
    "shellcheck",

    "goimports",
    "gopls",
  },
}

M.nvimtree = {
  git = {
    enable = true,
  },
  view = {
    side = "left",
    width = 20,
  },
}

M.lspconfig = {
  config = function()
    require "plugins.configs.lspconfig"
    require "custom.plugins.lspconfig"
  end,
}

M.null_ls = {
  after = "nvim-lspconfig",
  config = function()
    require "custom.plugins.null-ls"
  end,
}

return M
```
**custom/plugins/null-ls.lua**
```
local present, null_ls = pcall(require, "null-ls")

if not present then
   return
end

local b = null_ls.builtins

local sources = {

   -- webdev stuff
   b.formatting.deno_fmt,
   b.formatting.prettier,

   -- Lua
   b.formatting.stylua,

   -- Shell
   b.formatting.shfmt,
   b.diagnostics.shellcheck.with { diagnostics_format = "#{m} [#{c}]" },
}

null_ls.setup {
   debug = true,
   sources = sources,
}
```

----------
can't find stylua in bottom right corner，my mac already install stylua
leader fm is also not working
![Screen Shot 2022-09-29 at 17 38 18](https://user-images.githubusercontent.com/32233191/192997582-55057061-badc-41b7-8755-c498d4f5d39b.png)

**Comment by siduck** [comment]
show lspinfo output

**Comment by DeyunLuo** [comment]
> show lspinfo output

![Screen Shot 2022-09-29 at 18 29 26](https://user-images.githubusercontent.com/32233191/193008297-4ac2fc70-966c-4db6-a099-42db87668d29.png)
![Screen Shot 2022-09-29 at 18 29 48](https://user-images.githubusercontent.com/32233191/193008364-4e833630-279c-4f60-9a76-72ffb01433ec.png)

**Comment by siduck** [comment]
open a lua file and run this command `lua vim.lsp.buf.formatting()`

**Comment by DeyunLuo** [comment]
> open a lua file and run this command `lua vim.lsp.buf.formatting()`

![Screen Shot 2022-09-29 at 18 43 15](https://user-images.githubusercontent.com/32233191/193011101-647b720e-ecf4-487b-a34f-c7136cb04dd3.png)

**Comment by siduck** [comment]
open terminal in nvim and then run 

`stylua yourluafile`

**Comment by DeyunLuo** [comment]
> open terminal in nvim and then run
> 
> `stylua yourluafile`
-------
when I use stylua in terminal, It's ok.
![Screen Shot 2022-09-29 at 19 53 58](https://user-images.githubusercontent.com/32233191/193025067-96225539-9972-466e-8359-87095b8a3e88.png)

**Comment by siduck** [comment]
show :LspInfo

> > show lspinfo output
> 
> ![Screen Shot 2022-09-29 at 18 29 26](https://user-images.githubusercontent.com/32233191/193008297-4ac2fc70-966c-4db6-a099-42db87668d29.png) ![Screen Shot 2022-09-29 at 18 29 48](https://user-images.githubusercontent.com/32233191/193008364-4e833630-279c-4f60-9a76-72ffb01433ec.png)

null-ls isnt even here

**Comment by siduck** [comment]
expected lspinfo 
![image](https://user-images.githubusercontent.com/59060246/193763725-08d00491-72d4-4b46-826e-6ba56837bdcb.png)
