### ISSUE TITLE
Lsp not working for rust

### ISSUE THREAD

**Issue by ayush-india** [NvChad/NvChad#1615]
**Describe the bug**
When i try to edit a rust file i want the lsp to show completion but it does not do that.

**To Reproduce**
1. nvim main.rs
the it shows this error
![send](https://user-images.githubusercontent.com/99461867/193248487-7dbec74b-9ccb-44f5-819b-7285b029a6bb.png)

**Expected behavior**
Give lsp completions :)
**Screenshots**

**Desktop (please complete the following information):**
 - Operating System lubuntu 20.04
 - Terminal qterminal
 - Version of Neovim 0.8

**Comment by bryant-the-coder** [comment]
show ur config

**Comment by Dalot** [comment]
I am also having trouble setting up a Rust environment but in your case, if you are trying to set the `lspconfig`, it's `rust_analyzer` and not `rust-analyzer`

**Comment by ayush-india** [comment]
> show ur config

Which chadrc or init.lua

**Comment by bryant-the-coder** [comment]
the place where u set rust_analyzer

**Comment by ayush-india** [comment]
btw here is my config check the mine branch

https://github.com/ayush-india/.nvim/tree/mine

**Comment by siduck** [comment]
https://github.com/ayush-india/.nvim/blob/mine/lua/custom/plugins/lspconfig.lua#L5 

not rust_analyzer here at all.

**Comment by Dalot** [comment]
I got it working by installing the [rust-tools](https://github.com/simrat39/rust-tools.nvim) and removing `rust_analyzer` from `lspconfig`

`plugins/init.lua`
```lua
// ...
  ["simrat39/rust-tools.nvim"] = {
    after = "nvim-lspconfig",
    config = function()
      require "custom.plugins.rust-tools"
    end,
  },
// ...
```

`plugins/rust-tools.lua`
```lua
local rt = require("rust-tools")

rt.setup({
  server = {
    on_attach = function(_, bufnr)
      -- Hover actions
      vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
      -- Code action groups
      vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
    end,
  },
})

return rt
```

**Comment by ayush-india** [comment]
Thanks all of you for the quick help
