### ISSUE TITLE
error while installation

### ISSUE THREAD

**Issue by devSajan** [NvChad/NvChad#1617]
after running the installation command we can see the error message at the bottom of the screen

error: /usr/bin/ld: cannot find -lstdc++

 - Operating System: Ubuntu 20.4
 - Terminal: Konsole
 - Version of Neovim: 0.7.2
 - Shell: zsh

![image](https://user-images.githubusercontent.com/95337022/193392120-edc12636-1430-4645-9f0e-05fd7c6b0097.png)

**Comment by 0x736d** [comment]
Looks like you do not have `libstdc++` installed which is required by [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter#requirements).

**Comment by bryant-the-coder** [comment]
[try this(https://github.com/nvim-treesitter/nvim-treesitter/wiki/Linux-Support#ubuntudebian)

**Comment by siduck** [comment]
not a nvchad issue!

**Comment by devSajan** [comment]
I had to follow these steps to fix the error
https://github.com/facebookresearch/CodeGen/issues/30#issuecomment-984242414

```
$ ldconfig -p | grep libstdc++
$ sudo ln -s /lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libstdc++.so
```
