### ISSUE TITLE
Help needed to override config for colorizer

### ISSUE THREAD

**Issue by ywpkwon** [NvChad/NvChad#1618]
I'm following the NvChad's custom config method. (touching `lua/plugins/override.lua`) -- I was able to override `M.treesitter` or `M.mason`.

I would like to override the colorizer config so I can set `RRGGBBAA = true`.

I'm trying 
```
local M = {}
M.treesitter = { ... }
M.mason      = { ... }
M.colorizer  = {
  user_default_options = {
    RRGGBBAA = true, 
  },
}
return M
```
But it doesn't have any effect.

In the `mason` and `treesitter` cases, there are specific files like `plugins/configs/{maon,treesitter}.lua`. In the `colorizer` case, the original config is in the `plugins/configs/others.lua` --- I don't know if this is related.

Can anyone please let me know how to have custom colorizer config?

**Comment by siduck** [comment]
https://github.com/ywpkwon/NvChadPaul/blob/main/chadrc.lua#L18 

this syntax is outdated, please check the override docs

**Comment by siduck** [comment]
also @ywpkwon just check the table of colorizer in others.lua
