### ISSUE TITLE
`gq` word wrapping not working.

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1619]
Did something change recently because word wrapping with a visual highlight and then `gq` no longer does anything.

**Comment by danjenson** [comment]
Looks like it's probably a conflict with `formatexpr` in the new release: https://github.com/neovim/neovim/releases/tag/v0.8.0

Running `nvim --clean file.md` without nvchad works fine with `gq`.

**Comment by siduck** [comment]
nvim --clean works because there are no plugin running.

![image](https://user-images.githubusercontent.com/59060246/194057048-feab0cf6-3c1b-47fb-9c83-cce41a7c155a.png)

so not a nvchad issue.

**Comment by danjenson** [comment]
Looks like it is null-ls related with the recent update in nvim: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1131
