### ISSUE TITLE
client.resolved_capabilities is deprecated

### ISSUE THREAD

**Issue by kartorias1** [NvChad/NvChad#1624]
**Describe the bug**
Seems like the maintainer have already updated the config in _/nvim/lua/plugins/configs/lspconfig.lua_ to **client.server_capabilit
ies**.

But I still get the following warning:
"Accessing client.resolved_capabilities is deprecated, update your plugins or configuration to access client.server_capabilities instead. The new key/value pairs in server_capabilities directly match those defined in the language server protocol."

**To Reproduce**
Just open any files or projects that have LSP support.

**Expected behavior**
No warning.

**Screenshots**
![Screenshot_2022-10-08-10-47-05_1920x1080](https://user-images.githubusercontent.com/65721247/194686697-e0655028-f525-4751-b135-5eba394a8252.png)

**Desktop (please complete the following information):**
 - Operating System: ArchLinux
 - TerminalP: Kitty
 - Version of Neovim: 0.8.0

**Comment by siduck** [comment]
update nvchad. I removed 0.7 related stuff and we dont eeven use resolved_capabilities now

![image](https://user-images.githubusercontent.com/59060246/194687105-7b0fcbcb-f9f5-4395-999a-443c1e2694fd.png)

**Comment by tomasky** [comment]
maybe you have updated nvchad.
maybe you should update yourself lspconfig or try to execute `PackerSync`

**Comment by kartorias1** [comment]
> update nvchad. I removed 0.7 related stuff and we dont eeven use resolved_capabilities now
> 
> ![image](https://user-images.githubusercontent.com/59060246/194687105-7b0fcbcb-f9f5-4395-999a-443c1e2694fd.png)


I have already updated NvChad, do packer sync multiple times, but the issue still there.

**Comment by tomasky** [comment]
go to nvchad install dir and  git log to check the nvchad version ,  or  reinstall nvchad

**Comment by kartorias1** [comment]
> check your lsp config first, and go to nvchad install dir and git log to check the nvchad version , or reinstall nvchad

My lsp config is the same as the one described in NvChad docs, just added multiple language server in the `server` table.

My `git log` output:
![Screenshot_2022-10-08-11-34-57_1920x1080](https://user-images.githubusercontent.com/65721247/194688519-c0ab9fc0-8631-46d3-93e4-430c5873b9f5.png)

Everything seems fine and that's weird

**Comment by siduck** [comment]
Do you have this issue without custom folder? Remove it , onen nvim, do packersync, open vim again

**Comment by kartorias1** [comment]
> Do you have this issue without custom folder? Remove it , onen nvim, do packersync, open vim again

Seems like the issue comes from my custom folder, so I will deal with it myself. Thank you all for the support.

**Comment by siduck** [comment]
@kartorias1 your rice looks nice, which bar is it?

**Comment by kartorias1** [comment]
> @kartorias1 your rice looks nice, which bar is it?

That's Eww widget, config by its own defined language called Yuck, there is also a plugin that enable syntax highlight for it. The best thing is it use scss to style the element.
