### ISSUE TITLE
`disabled` keymaps are case-sensitive

### ISSUE THREAD

**Issue by martin-braun** [NvChad/NvChad#1627]
**Describe the bug**
`disabled` keymaps seem to be case sensitive:

```lua
M.disabled = {
    n = {
        ["<leader>b"] = "", -- will disable space b and not open a new buffer
        ["<Leader>b"] = "", -- will not work, but it's a valid Vim key identifier and identical to <leader>b
    }
}
```

**To Reproduce**
See above, just edit your keymaps and test it yourself.

**Expected behavior**
`disabled` keymaps should have the same tolerance as Neovim has with normal keymaps

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: macOS
 - Terminal: iTerm2
 - Version of Neovim: 0.8.0

**Comment by siduck** [comment]
key names in lua tables are case sensitive so i doubt if this is a nvchad issue!

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/1537

**Comment by martin-braun** [comment]
@siduck I'm not sure where the problem exactly is rooted from, but reading the linked issue makes it clear what's probably happening. While I can use `<leader>`, `<Leader>` or even `<LEADER>` on new mappings, I have to use the very exact key names (case-sensitive) to allow NvChad/Neovim/Vim to erase the mappings again. 

Does the disabled key values get passed to `unmap` eventually? Then, it would be a Vim issue, so that Vim expects the same key names. In that case Neovim or NvChad could circumvent the issue by converting all key names of special keys between `<` and `>` to lower-case before passing them to Vim. 

If on the other hand `disabled` keys will be used to clean the NvChad mappings before they are passed to Vim the same method could work to identify the keys, but it would be significantly slower, since indexing the entries wouldn't work without iterating and converting all key name identifiers on the mappings tables.

I hope this makes sense. I have no issue with this bug, now that I know about, but if this isn't documented, a hint would be preferable, i.e. "`disabled` key names need to match the original definition case-sensitive`. That could lead to quite a burden though, as I need to trial and error to find the correct format that was originally used to define the mapping (or I find the mapping in the appropriate place).

Thank you.

**Comment by siduck** [comment]
@martin-braun we merge lua key values ( from user mappings ) to the default mappings for overriding, disabling mappings and you know you can have multiple keys of same name but different casing like 

```lua
local M = {
 
   ['abc'] = ...
   ['ABC'] = ...
    ['Abc'] = ...
   
   }
   
   And so on! So the user has to write exact keyname ( if he's trying to disable or override default keybinds ) . We can probably convert all the mappings into the same case but that'll add complexity to the code base cuz 
  mappings inside `< > ` are case insensitive like 
  
   <C+X> is same as <C + x> 
   
    but <leader>ff is not the same as <leader>Ff

**Comment by martin-braun** [comment]
@siduck yep, exactly. If I'm not mistaken this issue could be solved by simply converting all contents between `<` and `>` to lowercase, but it would cripple startup time. 

Thanks for the info how `disabled` table keys are handled. 

You are right, it would add more complexity to it. Simply converting as described above would work, but it would require some additional caching to prevent slower loading times.

Is there a way to print all keymaps case sensitive to figure out the correct required format? Telescopes keymaps explorer displays the values in a converted format, it even converts the `<leader>` to the appropriate key, like `<Space>`.

Thanks.

**Comment by siduck** [comment]
@martin-braun required format? as long as the keymap's valid it should work

**Comment by martin-braun** [comment]
@siduck "valid" means to have an exact match, which is the topic of this issue. Here is an example.

If I show the keymaps in Telescope I see this: 

<img width="776" alt="Screen Shot 2022-10-10 at 5 23 29 PM" src="https://user-images.githubusercontent.com/24259245/194901180-2c2afbd3-c987-4262-a6c8-995b1ee5193f.png">

Now I try to disable "goto next buffer" like so: 

```lua
M.disabled = {
    n = {
        ["<Tab>"] = "", -- undo buffer navigation
        ["<S-Tab>"] = "", -- undo buffer navigation
    },
}
```

This does not work, only "goto previous buffer" will be disabled, because the initial keymaps of `tabufline` use `<TAB>` and `<S-Tab>` (notice the inconsistency btw.)

My question was: How to print all maps, or is it enough to inspect `lua/core/mappings.lua`?

**Comment by siduck** [comment]
@martin-braun `map` command or just look through the mappings.lua. 

Dont worry I'll soon create a keybind cheatsheet that shows all the mappings ( including user ones )

Recently I learned printing text to buffer, i was able to make a dashboard with it! So i'll remove alpha.nvim plugin and add my minimal dashboard ( 150 ~ LOC )

![image](https://user-images.githubusercontent.com/59060246/194908763-ad388f67-5515-4a9b-a66d-267b793f8010.png)
