### ISSUE TITLE
nvim-treesitter[lua]: Error during compilation         /usr/bin/ld: cannot find -lstdc++ collect2: error: ld returned 1 exit status Press ENTER or type command to continue

### ISSUE THREAD

**Issue by demorsick** [NvChad/NvChad#1629]
when i start neovim i get the error
`nvim-treesitter[lua]: Error during compilation        
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
`
**To Reproduce**
open,using neovim,any file with any extension such as .c .py .rs .hs .asm etc..

**Screenshots**
![Screenshot from 2022-10-09 11-53-43](https://user-images.githubusercontent.com/67763488/194750318-adbc4071-602d-49ff-ad79-b0808f054da4.png)

**Desktop (please complete the following information):**
Fedora Linux 36 (Workstation Edition) x86_64 
gnome-terminal 
NVIM v0.7.2

**Comment by siduck** [comment]
not a nvchad issue, install gcc or clang ( make too ) and use 0.8.0

**Comment by demorsick** [comment]
gcc is already installed,now I've also installed nvim 0.8,but it still doesn't work

**Comment by demorsick** [comment]
https://user-images.githubusercontent.com/67763488/194752701-7630578d-1b86-4c96-a576-755b57b9c0b2.mp4

**Comment by tomasky** [comment]
dnf install glibc-static libstdc++-static

**Comment by demorsick** [comment]
it worked thanks
