### ISSUE TITLE
Add support for Up and Down arrow keys in cmp

### ISSUE THREAD

**Issue by tabotkevin** [NvChad/NvChad#1631]
The current cmp configuration options does not have support for Up and Down arrow key during selection in auto-complete which is an issue for users who are used to using the Up and Down arrow keys.

It will be nice to have support Up and Down arrow keys during auto-complete selections.

**Comment by siduck** [comment]
@tabotkevin just override cmp config for this

**Comment by siduck** [comment]
```lua

  ["hrsh7th/nvim-cmp"] = {
    override_options = function()
      local cmp = require "cmp"

      return {
        mapping = {
          ["<Up>"] = cmp.mapping.select_prev_item(),
          ["<Down>"] = cmp.mapping.select_next_item(),
        },
      }
    end,
  },
 ```

**Comment by zubko** [comment]
Thanks for the solution, but I’m new to NVChad and there were some recent changes so ChatGPT is way off in its suggestions.

Where would I put this config with the most recent starter setup?

**Comment by siduck** [comment]
@zubko in any file of your plugins/ dir or just plugins/init.lua

**Comment by zubko** [comment]
Thanks @siduck 
I found this answer https://github.com/NvChad/NvChad/discussions/2608#discussioncomment-10927214 which helped me to organize the code.
