### ISSUE TITLE
invalid key: replace_keycodes

### ISSUE THREAD

**Issue by dai-re** [NvChad/NvChad#1633]
![SmartSelect_20221011-132346_Termux](https://user-images.githubusercontent.com/112737993/195012240-7248bd39-e993-4492-8acb-0c4724b7e094.jpg)

Help.

**Comment by siduck** [comment]
how to reproduce this? and   please show your custom mappings

**Comment by dai-re** [comment]
I just installed NvChad!, haven't set anything up yet.

**Comment by siduck** [comment]
are you using 0.8v of neovim?

**Comment by dai-re** [comment]
0.7.2

**Comment by siduck** [comment]
update to 0.8

**Comment by dai-re** [comment]
Thanks 😊
