### ISSUE TITLE
Consider switching to neo-tree

### ISSUE THREAD

**Issue by oddlama** [NvChad/NvChad#1634]
Recently there's been a big discussion over on https://github.com/nvim-tree/nvim-tree.lua/issues/1613 whether it is worthwhile to develop nvim-tree and neo-tree in parallel. The conclusion is that both will be continued, but nvim-tree aims to be more of a "batteries-included" opinionated default while neo-tree is considered to be the more customizable tree with a better code-base (it started later and could reuse all the work done in plenary and nui.vim).

While I have been using nvim-tree for the past years, I recently switched to neo-tree because it has amazing customization possibilities (git shortcuts, buffer tree lists, ...) and handles directory merging better than nvim-tree. I think it might be worth a look for NvChad, too? Let me know what you think.

**Comment by siduck** [comment]
i'll still use nvimtree, if it gets dead then neo-tree and it depends on plenary!

**Comment by airtonix** [comment]
I'll be swapping out nvimtree for neo-tree 👍🏻

**Comment by siduck** [comment]
> I'll be swapping out nvimtree for neo-tree 👍🏻

why? :thinking:

**Comment by DelinQu** [comment]
I agree; I switched to neo-tree recently because of some features, e.g., better ignore, UI, and git, even though there are still some limitations compared with vim-tree.
