### ISSUE TITLE
Formating (leader + fm) no longer works after recent update

### ISSUE THREAD

**Issue by AdamJSoftware** [NvChad/NvChad#1635]
**Describe the bug**

Whenever I run format (leader + fm). I get the following error message:
E5108: Error executing lua: /home/adam/.config/nvim/lua/core/mappings.lua:232: attempt to call field 'format' (a nil value)
stack traceback:
        /home/adam/.config/nvim/lua/core/mappings.lua:232: in function </home/adam/.config/nvim/lua/core/mappings.lua:231>

I'm assuming there's nothing wrong in my config as it is originating from core/mappings

**Comment by siduck** [comment]
update neovim to 0.8
