### ISSUE TITLE
statusline can display current code context ?

### ISSUE THREAD

**Issue by DeyunLuo** [NvChad/NvChad#1636]
when i view the [nvchad_ui/statusline/modules.lua](https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/statusline/modules.lua)
not find an option to config the current code context? need config nvim-gps or nvim-navic ?
doc also not mention this.
I want config like this 
<img width="951" alt="WeChatWorkScreenshot_bef4a2a3-6361-4f2e-8b1e-5288f98b4f63" src="https://user-images.githubusercontent.com/32233191/195749977-22c1d2a8-2c7e-4805-8976-c8f9cf0e3bfa.png">

**Comment by siduck** [comment]
https://gist.github.com/siduck/8d6f892d282fb5cbdf4cf623dd50b481

**Comment by DeyunLuo** [comment]
> https://gist.github.com/siduck/8d6f892d282fb5cbdf4cf623dd50b481

when I config link above gist and run PackerInstall、PackerCompile.
It also can't work.

**chadrc.lua**
<img width="949" alt="Screen Shot 2022-10-14 at 17 35 36" src="https://user-images.githubusercontent.com/32233191/195814654-ea8c02d0-fe07-4a61-8141-6cf347f6b987.png">

**configs.lua**
<img width="793" alt="Screen Shot 2022-10-14 at 17 36 28" src="https://user-images.githubusercontent.com/32233191/195814842-4e71fc27-97aa-45e3-ab14-255a95c3c1b9.png">

**nvchad_ui.lua**
<img width="862" alt="Screen Shot 2022-10-14 at 17 37 12" src="https://user-images.githubusercontent.com/32233191/195815039-ad021386-59fc-410e-a6a3-c03ee2ff6465.png">

**lspconfig.lua**
<img width="856" alt="Screen Shot 2022-10-14 at 17 37 28" src="https://user-images.githubusercontent.com/32233191/195815104-fde51635-d71c-48e8-b48a-f2c554ce5d3a.png">

**Comment by siduck** [comment]
do packercompile and look at the error message. And if you're not familiar with nvchad syntax then please read the docs. The gist is helpful
