### ISSUE TITLE
Probably missed a breaking change?

### ISSUE THREAD

**Issue by Qpernicus** [NvChad/NvChad#1637]
I updated NvChad recently and probably missed some change, but can't figure out WHAT, or WHERE to fix.

**Describe the bug**
Whenever i open a file (either new or already existing), go to insert mode, and press Enter i Get an Error and need to use Ctrl+Enter to go to next line.

**To Reproduce**
1. Go to a random file, of empty/new file
2. Press the ENTER key

**Expected behavior**
When i press Enter i want to go te next line.

**The Error**
E5108: Error executing lua: ...m/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/keymap.lua:250: invalid key: r
eplace_keycodes
stack traceback:
        [C]: in function 'nvim_set_keymap'
        ...m/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/keymap.lua:250: in function 'set_map'
        ...m/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/keymap.lua:132: in function 'callback'
        ...vim/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/misc.lua:13: in function 'fallback'
        ...site/pack/packer/opt/nvim-cmp/lua/cmp/config/mapping.lua:181: in function 'on_keymap'
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
        ...m/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/keymap.lua:118: in function <...m/site/pack/packer
/opt/nvim-cmp/lua/cmp/utils/keymap.lua:112>

**Desktop (please complete the following information):**
 - Arch
 - Kitty
 - Version of Neovim: aur/neovim-git 0.7.0.r67.g5c53e29ca9-1 (+250 13.22) (Out-of-date: 2022-09-07) (Installed: 0.7.0.r675.g8ba64dd3ad-1)

I am relative noob, and can't even find above file location so this is probably a PEBCAK, but i could use some help

**Comment by siduck** [comment]
update to neovim 0.8
