### ISSUE TITLE
null-ls formatting on save

### ISSUE THREAD

**Issue by nanomoeamezao** [NvChad/NvChad#1638]
**Describe the bug**
The null-ls wiki example for enabling the formatting on save functionality (https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts) does not seem to work. Null ls logs indicate no lsp calls for formatting are made automatically. The manual formatting  works fine.
It was working fine before the 0.8 transition. There is an older issue indicating that it is probably not a null-ls issue, but something else - https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/1055. 

The autocommand is being created and can be viewed with 
```
:verbose au BufWritePre
```

**To Reproduce**
1. Set null ls config to something like this with builtin formatters:
```
local null_ls = require "null-ls"

local b = null_ls.builtins

local sources = {
  -- Proto
  b.diagnostics.buf.with { args = { "lint" } },
  -- b.formatting.buf,

  -- Yaml\json
  b.formatting.prettierd.with { filetypes = { "yaml", "toml", "json" } },
  b.diagnostics.yamllint,
  b.diagnostics.jsonlint,

  b.diagnostics.checkmake,

  -- b.formatting.pg_format,
  b.formatting.sqlfluff.with { extra_args = { "--dialect", "postgres" } },

  -- Lua
  b.formatting.stylua,
  b.diagnostics.luacheck,
  b.diagnostics.sqlfluff.with { extra_args = { "--dialect", "postgres" } },

  -- Shell
  b.formatting.shfmt,
  -- b.diagnostics.shellcheck.with { diagnostics_format = "#{m} [#{c}]" },
  b.diagnostics.shellcheck,

  -- Go
  b.formatting.gofumpt,
  b.diagnostics.golangci_lint.with {
    args = { "run", "--fix=false", "--out-format=json", "$DIRNAME", "--path-prefix", "$ROOT" },
    extra_args = { "-c", vim.fn.getenv "GOPATH" .. "/utils/.golangci.yml" },
  },

  -- Git
  b.code_actions.gitsigns,
}

local M = {}

local lsp_formatting = function(bufnr)
    vim.lsp.buf.format({
        filter = function(client)
            -- apply whatever logic you want (in this example, we'll only use null-ls)
            return client.name == "null-ls"
        end,
        bufnr = bufnr,
    })
end

-- if you want to set up formatting on save, you can use this as a callback
local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

-- add to your shared on_attach callback
local on_attach = function(client, bufnr)
    if client.supports_method("textDocument/formatting") then
        vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
        vim.api.nvim_create_autocmd("BufWritePre", {
            group = augroup,
            buffer = bufnr,
            callback = function()
                lsp_formatting(bufnr)
            end,
        })
    end
end

M.setup = function()
  null_ls.setup {
    debug = true,
    sources = sources,
    debounce = 100,
    -- format on save
  on_attach = on_attach,
  }
end

return M
```
2. Open any file for which the formatters you have set up
3. Check the formatting function

**Expected behavior**
Manual formatting works, auto formatting is performed, log entries for both are present in :NullLsLog

**Screenshots**
![image](https://user-images.githubusercontent.com/1780639/196003275-8055285f-af05-47ff-bef3-efad37062fc9.png)

**Desktop (please complete the following information):**
 - Operating System: Manjaro
 - kitty 0.26.3
 - Version of Neovim: 0.8 stable

Does anyone have a working solution to this?

**Comment by nanomoeamezao** [comment]
Also should i create a similar issue for null-ls?

**Comment by siduck** [comment]
```lua
 on_attach = function()
    vim.api.nvim_create_autocmd("BufWritePost", {
      callback = function()
        vim.lsp.buf.format()
      end,
    })
  end,
  ```
  
  in your null-ls setup table

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/196012082-4fd727fd-f1b7-4ab6-b66e-fcb83e5886ae.mp4

**Comment by nanomoeamezao** [comment]
For future refrence: I found the issue, it was cause by loading the netman package.

**Comment by siduck** [comment]
oh boii , weird

**Comment by robbash** [comment]
Hey. I'm new to NvChad (great work btw!).
To get this working properly I had to change your snippet to hook into `BufWritePre`. Not sure if that creates other caveats or if it's a legit way to do it?
Cheers

**Comment by siduck** [comment]
> Hey. I'm new to NvChad (great work btw!). To get this working properly I had to change your snippet to hook into `BufWritePre`. Not sure if that creates other caveats or if it's a legit way to do it? Cheers

sounds okay to me
