### ISSUE TITLE
plugin symbols-outline.nvim lost color

### ISSUE THREAD

**Issue by ericwq** [NvChad/NvChad#1639]
**Describe the bug**
As the following picture shows, plugin `simrat39/symbols-outline.nvim` lost its color. Please see the right side of the screen.
I report this bug, because `simrat39/symbols-outline.nvim` doesn't update since Aug 29.
![Screen Shot 2022-10-18 at 17 47 28](https://user-images.githubusercontent.com/1501146/196397674-aa79a504-7965-422f-ae09-27528026525c.png)

**To Reproduce**
1. add `simrat39/symbols-outline.nvim` by `NvChad` plugin mechanism
```lua
	-- symbols-outline
	-- https://github.com/simrat39/symbols-outline.nvim
	["simrat39/symbols-outline.nvim"] = {
		after = "nvim-lspconfig",
		setup = function()
			require("core.lazy_load").on_file_open "symbols-outline.nvim"
		end,
		config = function()
			local opts = {
				show_guides = false,
				auto_close = true,
				show_symbol_details = false,
			}
			require("symbols-outline").setup(opts)
		end,
	},
```
3. open any treesitter supported file.
4. type cmd `:Symbolsoutline`
5. See the right side of the screen.

**Expected behavior**
The right side screen should look like this:
<img width="1514" alt="Screen Shot 2022-10-18 at 17 57 18" src="https://user-images.githubusercontent.com/1501146/196399352-231b13cc-206a-4597-b7e2-54a5a47ce2cd.png">

**Desktop (please complete the following information):**
 - Operating System: docker desktop v4.12 MacOS Monterey
 - Terminal: alacritty or kitty
 - Version of Neovim: 0.8

**Additional context**
no

**Comment by ericwq** [comment]
It should be the recent commits of NvChad cause the problem.  I think 6 days ago, everything is fine.

**Comment by siduck** [comment]
@ericwq do those icons depend on treesitter hl groups? if yes then its an upstream issue probably.

Recently alll TS*hlgroups were removed for example `TSVariable` was removed, its replacement `@variable`

if symbolsoutlines plugin still uses the old tshlgroups then this isnt a nvchad issue

**Comment by ericwq** [comment]
I don't know the implementation of `simrat39/symbols-outline.nvim`.  Thanks for the explanation.
