### ISSUE TITLE
Highlight on Yank Not Working

### ISSUE THREAD

**Issue by LSleutsky** [NvChad/NvChad#1641]
**Describe the bug**
I am trying to use an autocmd that I have used in many other nvim configs before, which highlights the text that is being copied/yanked, but when adding this autocmd to my `custom/init.lua` file, nothing happens:

```lua
vim.api.nvim_create_autocmd("TextYankPost", { callback = function() vim.highlight.on_yank({ higroup = 'IncSearch', timeout = 200 }) end })

```

**To Reproduce**
1. Put the above autocmd into your config.
2. Try to copy/yank text.
3. Observe that no highlight happens.

**Expected behavior**
The copied/yanked text is highlighted for the predetermined amount of time as defined by the autocmd.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - MacOS Monterey 12.6
 - iTerm2
 - `NVIM v0.9.0-dev-136-gfad558b6a`

**Additional context**
Not sure what I am doing wrong, or if I'm adding this autocmd to the wrong place, but I am trying to avoid having to install a text highlighting on yank plugin, since Neovim is supposed to be able to do this natively if I'm not mistaken.

Any thoughts...?

**Comment by LSleutsky** [comment]
Sorry, had a typo in my code and I kept on completely overlooking it. Works fine, closing this.

**Comment by siduck** [comment]
no worries, all good!
