### ISSUE TITLE
lsp no loaded in windows

### ISSUE THREAD

**Issue by acfuns** [NvChad/NvChad#1643]
**Describe the bug**
lsp no loaded in windows, prompt：Spawning language server with cmd: `clangd` failed. The language server is either not installed, missing from PATH, or not executable.
I guess it is a problem with the ENV loading Mason.
The terminal in NVIM can get environment variables, and Clangd can be started.
It is completely normal on Linux.

**To Reproduce**
1. install nvchad in windows11 and windows terminal.
2. git nvchad:example_config.
3. add clangd lspconfig and install clangd in mason.
4. open xxx.cpp

**Expected behavior**
Load the LSP normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/55129666/197005486-7550dd9f-2379-4457-9c96-c0019938384e.png)
![image](https://user-images.githubusercontent.com/55129666/197006374-5e21fff0-c15c-4aaa-9235-25eb5f5f820e.png)
![image](https://user-images.githubusercontent.com/55129666/197007269-2e92e16d-f1e7-4b02-aa3b-79f340136cb5.png)

**Desktop (please complete the following information):**
 - Operating System windows11 22H
 - Terminal windows terminal
 - Version of Neovim 0.8.0

**Comment by acfuns** [comment]
I add clangd env, but no effect.
![image](https://user-images.githubusercontent.com/55129666/197035480-c2736305-2b66-42c0-bde3-7630d1458d52.png)

**Comment by siduck** [comment]
install clangd from mason and install clang binary in your system.

**Comment by acfuns** [comment]
rust deno more no effect, LSP can only be installed manually,By mason no effect.

**Comment by acfuns** [comment]
Lspconfig is having problems accessing the CMD and should be inconclusive

**Comment by siduck** [comment]
> Lspconfig is having problems accessing the CMD and should be inconclusive

manually write the cmd name then, for pylsp .

**Comment by acfuns** [comment]
https://github.com/neovim/nvim-lspconfig/issues/2032#issuecomment-1200413852
I think this is the key to the problem.
