### ISSUE TITLE
Whichkey plugin doesn't work

### ISSUE THREAD

**Issue by mahmood601** [NvChad/NvChad#1645]
Whichkey.nvim doesn't work when  I press leader key and I don't see a popup

**Mobile
 - Android arm 64 / termux
 - Neovim v0.8.0

**Comment by siduck** [comment]
its disabled by default, put this in your custom plugins section and then reopen nvim & do packersync
```lua
  ["folke/which-key.nvim"] = { disable = false }
  ```

**Comment by mahmood601** [comment]
It works. Thanks! ❤️

**Comment by siduck** [comment]
> It works. Thanks! heart

brother dont forget to read surah kahf :heart:

**Comment by mahmood601** [comment]
I'll do that. Thanks again

**Comment by Morakhiyasaiyam** [comment]
> It works. Thanks! ❤️

How you made it work for termux?

**Comment by mahmood601** [comment]
> > It works. Thanks! ❤️
> 
> How you made it work for termux? 

I think now you should go into the  `custom` directory in plugins.lua and add in `plugins`
```
{
  "folke/which-key.nvim", 
   enabled = true,
}
```
If your problem was in syntax, this is the solution
if you need more information, please read the docs in <a href = "https://nvchad.com/docs/config/plugins">Nvchad Docs</a>

**Comment by siduck** [comment]
> > > It works. Thanks! heart
> > 
> > 
> > How you made it work for termux?
> 
> I think now you should go into the `custom` directory in plugins.lua and add in `plugins`
> 
> ```
> {
>   "folke/which-key.nvim", 
>    enabled = true,
> }
> ```
> 
> If your problem was in syntax, this is the solution if you need more information, please read the docs in [Nvchad Docs](https://nvchad.com/docs/config/plugins)

its already enabled by default now! so no need of enabled option!
