### ISSUE TITLE
golang lsp format not working

### ISSUE THREAD

**Issue by fengtianru117** [NvChad/NvChad#1646]
I follow the doc and install gopls , every works fine except format.Please give me some advice!
I got this error:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/27802344/197355319-d2dd7421-0343-4610-a24c-85d9edb65bf7.png">

I am sure the lsp is up and other lsp feature works fine.

lspinfo:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/27802344/197355306-64ea4f48-0e5f-4556-80b5-373cd3f262d4.png">

neovim version:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/27802344/197355229-2844c814-5e81-43b4-84b0-b0ceed6dbe72.png">

custom.plugins.lspconfig.lua:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/27802344/197355264-49384447-bc26-46b4-9ada-a86707fbb858.png">

**Comment by fengtianru117** [comment]
By the way,i can see the gopls process in background.

**Comment by siduck** [comment]
the default on_attach function which you use in your custom lspconfig contains this 

![image](https://user-images.githubusercontent.com/59060246/197367593-aee0ec26-d219-489d-95f3-97fd660d9507.png)


Which disables formatter of lsps

**Comment by siduck** [comment]
so what you can do is just remove those 2 lines and make a new on-attach function for gopls lspconfig section

**Comment by fengtianru117** [comment]
Thanks a lot!
