### ISSUE TITLE
When opening files, nvim issues W18: Invalid character in group name

### ISSUE THREAD

**Issue by AstroShen** [NvChad/NvChad#1647]
**Describe the bug**
When opening a file, nvim issues a chain of errors "W18: invalid charaacter in group name"

**To Reproduce**
The issues happened to Ubuntu 22 and centos7, but okay with ubuntu 20.
I check help W18, saying the problem is about wrong hlgroup.
I guess this is due to some theme hlgroup settings, but this is no way to debug where the problem message come from.  

**Expected behavior**
No W18 issue when opening file.

**Screenshots**
![捕获](https://user-images.githubusercontent.com/30562065/197436712-4d533b76-1b2e-4e2d-97d3-41565d5b12b7.PNG)

**Desktop (please complete the following information):**
 - ubuntu 22
 - WSL 2
 - 0.7.2

**Additional context**

**Comment by siduck** [comment]
update to 0.8 neovim
