### ISSUE TITLE
Diffview Plugin Not Working

### ISSUE THREAD

**Issue by LSleutsky** [NvChad/NvChad#1650]
**Describe the bug**
I am trying to install the `sindrets/diffview.nvim` [plugin](https://github.com/sindrets/diffview.nvim) into NvChad, but no matter what I do, it just does not work. Any command I run from the plugin's docs, I get an error message saying that command is not an editor command.

I've tried implementing it with a custom config, with no config, straight how the plugin's wiki recommends, and with the default NvChad format of installing/using custom plugins, and still get nowhere. And of course I reload Neovim after updating my custom config, and I have also ran the appropriate and applicable Packer commands in trying to get this plugin functional.

Does anyone have this plugin installed and working in their config? If so, can you please help!?

**To Reproduce**
1. Try to install the `sindrets/diffview.nvim` plugin, which is found [here](https://github.com/sindrets/diffview.nvim)
2. After reloading Neovim and ensuring the plugin was properly installed, try to run an editor command like `DiffviewOpen` in your git-enabled project
3. See the command line error message, for any `diffview` commands.

**Expected behavior**
For the `sindrets/diffview.nvim` plugin to properly work, and be usable for working with git projects in NvChad.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - _MacOS Monterey 12.6_
 - _iTerm2_
 - _NVIM v0.9.0-dev-163+gec33edc7b_

**Additional context**
N/A

**Comment by siduck** [comment]
diffview needs plenary and we lazyloaded plenary on plenary module so whenever some plugin asks for plenary, plenary plugin loads up. But idk why it doesnt happen with diffview so what you can do is just un-lazyload plenary

```lua
 ["sindrets/diffview.nvim"] = {
      after = "plenary.nvim",
      config = function()
         require("diffview").setup()
      end,
   },

 ["nvim-lua/plenary.nvim"] = {rm_default_opts = true } 
 ```

**Comment by LSleutsky** [comment]
Thank  you very much for that info! Was that somewhere in the docs that I might have missed, cause I would have never known about the `rm_default_opts` parameter. Did I miss that? Or is this just one of those isolated things for this particular plugin...?

**Comment by siduck** [comment]
@LSleutsky  rm_default_opts just uses the plugin definition by the user.

by default the plugin definition values gets merged with the default plugin definition values soo.  the docs will be updated soon

**Comment by TheBigFish** [comment]
Hi @siduck ,

I'm not familiar with Neovim, but I encountered a similar issue with the DiffView plugin. Following the suggestions above, I added the following code to my Nvchad custom plugins.lua:

```lua
local plugins = {

  ["sindrets/diffview.nvim"] = {
    after = "plenary.nvim",
    config = function()
      require("diffview").setup()
    end,
  },

  ["nvim-lua/plenary.nvim"] = { rm_default_opts = true },
  -- Override plugin definition options
  
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      -- format & linting
      {
        "jose-elias-alvarez/null-ls.nvim",
        config = function()
          require "custom.configs.null-ls"
        end,
      },
    },
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
    end, -- Override to setup mason-lspconfig
  },
...
}
```
Unfortunately, this didn't work for me. I attempted to make some changes:
```lua
local plugins = {

  {
    "nvim-lua/plenary.nvim",
    rm_default_opts = true,
  },

  {
    "sindrets/diffview.nvim",
    dependencies = {
      --"nvim-lua/plenary.nvim",
      "nvim-lua/plenary.nvim",
      "TimUntersberger/neogit",
    },
    config = function()
      require("diffview").setup()
    end,
    after = "plenary.nvim",
  },
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      -- format & linting
      {
        "jose-elias-alvarez/null-ls.nvim",
        config = function()
  }
...
}
```
Unfortunately, this change also didn't solve the issue. Do you have any suggestions?

**Comment by siduck** [comment]
@TheBigFish hint in the docs https://nvchad.com/docs/config/plugins

**Comment by TheBigFish** [comment]
Hello @siduck
I've read the documentation at https://nvchad.com/docs/config/plugins and added `rm_default_opts = true` in `custom/plugins.lua`, as shown below:
```lua
local plugins = {
  {
    "nvim-lua/plenary.nvim",
    rm_default_opts = true,
  },
  {
    "sindrets/diffview.nvim",
    dependencies = {
      --"nvim-lua/plenary.nvim",
      "nvim-lua/plenary.nvim",
      "TimUntersberger/neogit",
    },
    config = function()
      require("diffview").setup()
    end,
    after = "plenary.nvim",
  },
```
However, it still doesn't seem to be working. Any suggestions on how to resolve this issue?

**Comment by siduck** [comment]
@TheBigFish the solution here seems outdated cuz of packer and nvchad v1.0 syntax being used
 ```lua
  {
    "sindrets/diffview.nvim",
    cmd = {'DiffviewOpen', 'DiffviewToggleFiles'},
    dependencies = {
      "TimUntersberger/neogit",
    },
    config = function()
      require("diffview").setup()
    end,
  }, 
  
  ```
  
  i'd lazy load it on its cmds!
