### ISSUE TITLE
Is it possible to avoid loading lua-lsp with nvchad defaults?

### ISSUE THREAD

**Issue by nanomoeamezao** [NvChad/NvChad#1651]
**Is your feature request related to a problem? Please describe.**
Id like to try using neodev.nvim, but it sets up its own lua lsp. But also lua-lsp is being loaded with some configuration, provided by nvchad when lua/plugins/configs/lspconfig is loaded. Is there a good way to avoid that, but still load the file? 

**Describe the solution you'd like**
Save the default lua-language-server setup as an export in lua/plugins/configs/lspconfig and have users load the default, if needed?

**Alternative**
Maybe there is a good way to drop the default server is another one is being set-up?

**Comment by siduck** [comment]
@nanomoeamezao load neodev.nvim after lspconfig or override default lspconfig, add your own lspconfig in its plugin definition
