### ISSUE TITLE
~20x `Error detected while processing BufReadPost Autocommands for "*":` when opening file

### ISSUE THREAD

**Issue by AlexanderHOtt** [NvChad/NvChad#1652]
**Describe the bug**
When opening a file through <kbd>\<leader\></kbd><kbd>e</kbd>, the error message 
```
Error detected while processing BufReadPost Autocommands for "*":
W18: Invalid character in group name
```

shows up.

**To Reproduce**
1. Fresh install neovim, packer sync, exit
1. open nvim without any arguments
2. <kbd>\<leader\></kbd><kbd>e</kbd>
3. select a file
4. there should be ~20 errors in the command box

**Expected behavior**
there should not be any errors

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System:
Ubuntu
 - Terminal:
Konsole + Zsh
 - Version of Neovim:
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

**Additional context**
This only happens for the first file or telescope fuzzy finder that gets opened. Every file after that works. I think this has to do with an autocommand that is being lazy loaded.

**Comment by siduck** [comment]
update to neovim 0.8

**Comment by Griiid** [comment]
The installation instruction in https://nvchad.com/quickstart/install still says:
`[Neovim 0.7.2](https://github.com/neovim/neovim/releases/tag/v0.7.2), if your distro/OS doesn't have it then try [neovim version manager](https://github.com/MordechaiHadad/bob).`

Who can update this?

**Comment by siduck** [comment]
@Griiid i will update it tomorrow.
