### ISSUE TITLE
 Fresh install, insert mod, cursor is overlay by the filename path prompts

### ISSUE THREAD

**Issue by laowalter** [NvChad/NvChad#1653]
**Describe the bug**
After fresh installation, when edit a file in insert mode, there is _a current filename prompts_ in the same line.  it overlap the cursor sometimes, make input confuse. can not even display the input char.

**To Reproduce**
Just fresh install, then create a file named main.py for example, insert a line like "from abc import cde",  at the same time the noisy prompt **[main.py + ( ~/tmp) - NVIM** come out. When you leave insert mode and re-enter insert mode to modify "abc", then the  **[main.py + ( ~/tmp) - NVIM**  overlay input cursor, make input messy.

**Expected behavior**

Find a way to disable this filename prompts.

**Screenshots**
Something like this:

https://raw.githubusercontent.com/laowalter/NvChad_custom/main/bugs/bug1.png
https://raw.githubusercontent.com/laowalter/NvChad_custom/main/bugs/bug2.png

**Desktop (please complete the following information):**
 - Gentoo Linux
 - TurboVNC 3.0.1
 - Neovim 0.8.0-r1

**Additional context**
Just test, this bug happend in windows putty env, or turbo vnc 3.0 (did not try other version).

**Comment by laowalter** [comment]
no comments

**Comment by siduck** [comment]
@laowalter hmm so there are non nvchad users who face this issue https://www.reddit.com/r/neovim/comments/yn88g8/weird_cmp_behavior_in_wezterm_and_alacritty_but/

Can you make a minimal config? like lspconfig plugin with cmp?

**Comment by siduck** [comment]
and what happens when you set `opt.title = true` to false in `core/options.lua`?

**Comment by siduck** [comment]
ok this is not a nvchad issue anymore, nvim-cmp has some issues with `opt.title` probably

check https://www.reddit.com/r/neovim/comments/yn88g8/comment/ivcykh5/?context=3

so for now just `vim.opt.title = false` in your `custom/init.lua`

**Comment by perivarlura** [comment]
this is still an issue, so perehaps it shoult be made a default setting or informed somewhere, as it was quite annoying before I found this bug and set the setting.

**Comment by siduck** [comment]
@perivarlura its a cmp issue, cmp gets messed up with the title option idk why

**Comment by perivarlura** [comment]
would it not be an idea to add the flag to the standard config until it's
fixed, was what I was thinking/ asking, to avoid that newbies in nvim like
me spends a lot of tine figuring out where the problem is?

besides from this, I love your work, and even more as the puzzle pieces
falls together with my learn by drowning tactics 🙂

tor. 17. nov. 2022, 10:04 skrev Sidhanth Rathod ***@***.***>:

**Comment by siduck** [comment]
@perivarlura noted, i will make a push a change tonight :)

**Comment by perivarlura** [comment]
🙂👍

tor. 17. nov. 2022, 12:28 skrev Sidhanth Rathod ***@***.***>:
