### ISSUE TITLE
Which disabled by default?

### ISSUE THREAD

**Issue by imadjamil** [NvChad/NvChad#1654]
https://github.com/NvChad/NvChad/blob/dc669313c1e3e4348c65d622734e57d7459b6f83/lua/plugins/init.lua#L196

I have it working after commenting out the above line. Is this an intentional behavior?

**Comment by siduck** [comment]
dont comment it , just enable it in your custom plugins like

```lua
['whichkyeblabla'] = {disable =false}
```

**Comment by imadjamil** [comment]
Ok, thanks. So it is dosabled by default.
