### ISSUE TITLE
NVChad UI & Noice fighting over notifications

### ISSUE THREAD

**Issue by lucazz** [NvChad/NvChad#1656]
**Describe the bug**
 Hello there everyone, I'm having a weird error while trying to use noice.vim:
Whenever I open a file with neovim I get two distinct behaviours:

1. I'm greeted w/ 3 banner messages aboutvim.lsp.handlers["textDocument/hover"], vim.lsp.handlers["textDocu,ent/signatureHelp"] and vim.notify being overwritten by another plugin
2. Poorly formated Workspace loading messages on the lower right side

**To Reproduce**

1. Install nvchad
2. Install noice.vim
3. open any file with neovim

**Expected behavior**
 One should be able to use noice.vim alongside nvchard w/o issues

**Screenshots**
https://user-images.githubusercontent.com/6126301/198719312-09231736-75f6-423f-ba86-32c79b5d7ac7.mov

**Desktop (please complete the following information):**
 - macOS Ventura
 - Alacritty 
 - NVIM v0.8.0

```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"
```
Here's my dotfiles: https://github.com/lucazz/dotfiles/tree/master/nvim/custom

**Comment by siduck** [comment]
load your notify function  in custom lspconfig

**Comment by siduck** [comment]
there would be some code to load the setup call of noicd plugin, just add that line in your custom lspconfig , at the bottom

**Comment by siduck** [comment]
hmm, this code gets loaded in default lspconfig https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/lsp.lua#L11

so what you can do is replace default lspconfig with yours or load noice nvim code after custom lspconfig

**Comment by siduck** [comment]
just add `require("noice").setup()` in your custom lspconfig

**Comment by anstadnik** [comment]
This way noice can be loaded either after lspconfig or always.
If noice is loaded (setup called) once in config for noice, then if setup is called for the second time apparently things are not set. So those can't be combined

**Comment by anstadnik** [comment]
Instead this would work:
```lua
      vim.notify = require("noice").notify
      vim.lsp.handlers["textDocument/hover"] = require("noice").hover
      vim.lsp.handlers["textDocument/signatureHelp"] = require("noice").signature
```
Like in NvChad/ui#29.
However, IMO it's not the best solution, but I don't see other approaches without modifying NvChad's or noice core code which I want to avoid at all cost.

**Comment by anstadnik** [comment]
However, not sure that it always works. I seem to still have problems

**Comment by siduck** [comment]
@anstadnik the other approach is not using our on_attach function as it contains some code calling our signature module

```lua

M.on_attach = function(client, bufnr)
  client.server_capabilities.documentFormattingProvider = false
  client.server_capabilities.documentRangeFormattingProvider = false

  utils.load_mappings("lspconfig", { buffer = bufnr })

  -- if client.server_capabilities.signatureHelpProvider then
  --   require("nvchad_ui.signature").setup(client)
  -- end
end
```

**Comment by ashb** [comment]
Anyone coming along this now, it's easier with NvChad v2.5: in `chadrc.lua`

```lua
M.lsp = {signature = false}
```

**Comment by elferherrera** [comment]
@ashb that no longer works 
is there another solution for it?

**Comment by siduck** [comment]
> @ashb that no longer works is there another solution for it?

show your chadrc

**Comment by elferherrera** [comment]
```
---@type ChadrcConfig
local M = {}

M.ui = {
  theme = "catppuccin",
  tabufline = {
    enabled = false,
  },
  telescope = {
    style = "bordered"
  },
  statusline = {
    theme = "vscode_colored",
    separator_style = "default",
    overriden_modules = nil,
  },
  cheatsheet = { theme = "grid" },
}
M.plugins = "custom.plugins"
M.mappings = require("custom.mappings")

return M
```

**Comment by siduck** [comment]
@ashb  and where is lsp.signature = false in your ui? nowhere!! i hope you migrate to nvchad v2.5 too,check the news page on nvchad.com

**Comment by elferherrera** [comment]
I see. I'm using v2.0 and there is a new version. Need to update my config

**Comment by FirthR5** [comment]
> Anyone coming along this now, it's easier with NvChad v2.5: in `chadrc.lua`
> 
> ```lua
> M.lsp = {signature = false}
> ```
This works wow, Thank you

**Comment by gatspy** [comment]
I also encountered the same problem, how can I solve it?

**Comment by siduck** [comment]
> I also encountered the same problem, how can I solve it?

read the above solution

**Comment by MusherM** [comment]
> Anyone coming along this now, it's easier with NvChad v2.5: in 现在任何人遇到这个，使用 NvChad v2.5 都更容易：在`chadrc.lua`
> 
> ```lua
> M.lsp = {signature = false}
> ```

It helps! Thx for your effort
