### ISSUE TITLE
Code action UI regression

### ISSUE THREAD

**Issue by Freyskeyd** [NvChad/NvChad#1662]
**Describe the bug**
After upgrading to the last version, `code action` popup seems to have a different style and lose some readability.

**To Reproduce**
- Open a file with LSP
- Trigger the popup of code action
 
**Expected behavior**
Having a popup that are delimited by border or different color

**Screenshots**
![Screenshot 2022-11-03 at 11 58 23](https://user-images.githubusercontent.com/1394604/199704408-42f570b1-e200-4fae-836a-f29657f520ee.png)

**Desktop (please complete the following information):**
 - Operating System: Mac
 - Terminal: iterm2
 - Version of Neovim: 0.8

**Comment by siduck** [comment]
how do you get the code action popup? it just gets into the cmdline for me

**Comment by Freyskeyd** [comment]
using `<leader>ca` mapping

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/199709078-1fa80b55-79d0-4f21-8c4a-acb26cbfca61.png)

we dont add any popup for it, i think you're using some plugin for it

**Comment by Freyskeyd** [comment]
Mmhh I will check that, thanks and sorry :x

**Comment by jotihojr** [comment]
@siduck anything new here? I still having the same problems with code actions.

**Comment by siduck** [comment]
@jotihojr  we dont handle it at all. plz check your plugins

**Comment by jotihojr** [comment]
@siduck worked it out...
just merged (didn't alter nvChad) the following to telescope opts
```
	extensions_list = { "ui-select" },
	extensions = {
		["ui-select"] = {
			require("telescope.themes").get_dropdown({}),
		},
	},
```
and added `"nvim-telescope/telescope-ui-select.nvim"` to my plugins
Works after the first call into telescope because of lazy loading.

**Comment by siduck** [comment]
@jotihojr  make your opts a function that returns a    table , so your   require* wont break lazy loading

**Comment by jotihojr** [comment]
@siduck the example above was only an excerpt.
Unlike `tbl_deep_extend`, `merge_opts` below "deep merges" tables _and_ sub-tables; key values are also extended. For example, `defauls.border` will be overwritten and `ui-select` will be appended to `extensions_list`.

`custom/plugins/init.lua`
```lua
...
{
	"neovim/nvim-lspconfig",
	dependencies = {
		"nvim-telescope/telescope.nvim",
	},
	...
},
{
	"nvim-telescope/telescope.nvim",
	opts = function()
		local t = utils.merge_opts(
			require("plugins.configs.telescope"),
			require("custom.plugins.configs.telescope")
		)
		-- vim.print(t)
		return t
	end,
},
{
	"nvim-telescope/telescope-ui-select.nvim",
},
...
```
`custom/plugins/configs/telescope.lua`
```lua
return {
	defaults = {
		border = true,
	},
	extensions_list = { "ui-select" },
	extensions = {
		["ui-select"] = {
			require("telescope.themes").get_dropdown({}),
		},
	},
}
```

Hope that clarifies the configuration for windowed `code-actions`.
