### ISSUE TITLE
Lualine Icon issue

### ISSUE THREAD

**Issue by yinxiangshi** [NvChad/NvChad#1663]
Env: MacOS 12, iterm 2, nvim nightly build.

As shown in the pic:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/32014575/199873096-34306ae7-f468-4324-be86-5b45c874d3c5.png">

**Comment by yinxiangshi** [comment]
Font: Main font: Jet Brains mono, Non ASCILL font: nerd font

**Comment by siduck** [comment]
not a nvchad issue, use JetbrainsMono Nerd Font as your main font.

**Comment by yinxiangshi** [comment]
It works! Thanks! @siduck
