### ISSUE TITLE
LSP Formatting Mapping (<leader>fm) Doesn't Work

### ISSUE THREAD

**Issue by tsjordan-eng** [NvChad/NvChad#1664]
**Describe the bug**
When I do the leader-fm shortcut to format the buffer I get  an error that `format` is `nil`.

**To Reproduce**
1. Open a buffer that you have a language server running on that can format
2. Type <leader>fm (usually space-bar fm)

**Expected behavior**
The buffer should be formatted

**Screenshots**
```
E5108: Error executing lua: /home/tsjorda/.config/nvim/lua/core/mappings.lua:232: attempt to call field 'format' (a nil value)                                                        stack traceback: 
home/tsjorda/.config/nvim/lua/core/mappings.lua:232: in function </home/tsjorda/.config/nvim/lua/core/mappings.lua:231>
```

**Desktop (please complete the following information):**
 - WSL
 - Bash
 - Version of Neovim: 0.7.0

**Additional context**

I believe the following line should be changed from `format` to `formatting` https://github.com/NvChad/NvChad/blob/main/lua/core/mappings.lua#L232

It works when I add the following to my custom mappings file:
```lua
M.lspconfig = {
  n = {
    ["<leader>fm"] = {
      function()
        vim.lsp.buf.formatting()
      end,
      "lsp formatting",
    }
  }
}
```

**Comment by siduck** [comment]
update neovim to 0.8
