### ISSUE TITLE
nvim-treesitter error

### ISSUE THREAD

**Issue by morpheuslord** [NvChad/NvChad#1674]
I have been using nvim on my windows machine and wanted a cool theme for it with all my extensions in it so i chose nvchad and after installing nvim-treesitter is showing up errors like in the below images:
 
![nvim @ LAPTOP-V17Q7F9M 09-11-2022 23_13_03](https://user-images.githubusercontent.com/70637311/201056896-40115996-6f94-44c8-b5a1-fac3745a5044.png)
![Command Prompt - nvim 10-11-2022 15_11_58](https://user-images.githubusercontent.com/70637311/201056927-b4233dc5-3e96-492b-8831-12c099a8c5e4.png)
Please let me know how to correct this error.

**Comment by siduck** [comment]
probably some windows related issue and do you have neovim 0.8?

**Comment by morpheuslord** [comment]
yes, I am using 0.8 cause for some reason many of the plugins won't work on 0.7

**Comment by siduck** [comment]
does this happen with linux?

**Comment by morpheuslord** [comment]
No only on windows i don't know why in the error if we see properly there is some kind of UNIX command exec so might be that the compatibility is low i have no clue on that kind of things

**Comment by siduck** [comment]
hmm cant help then :(

**Comment by morpheuslord** [comment]
no problem, I need to adjust without tree-sitter I guess this issue might get resolved in the future.

**Comment by bryant-the-coder** [comment]
try. removing the nvim-treesitter directory. and let it reinstall again.
i encounter this problem before. and this is not nvchad issue

**Comment by bryant-the-coder** [comment]
linux has the `rm -rf` or the `rmdir` command iirc

**Comment by bryant-the-coder** [comment]
@morpheuslord

**Comment by morpheuslord** [comment]
I tried and it did not work 🤷‍♂️

**Comment by siduck** [comment]
@morpheuslord remove all neovim related dirs and then reinstall nvchad

**Comment by morpheuslord** [comment]
tried it removed from the local AppData dir and also from the Program Files dir but still no result.

**Comment by siduck** [comment]
idk then :/ , please use a sane OS!

**Comment by morpheuslord** [comment]
i guess i need to just switch completely to linux windows is retarded

**Comment by morpheuslord** [comment]
thanks for all the support man i will try using nvchad on my VM or on my wsl machine
