### ISSUE TITLE
What is the correct way to load a source - cmp

### ISSUE THREAD

**Issue by axdank** [NvChad/NvChad#1683]
Hi!,  I am trying to use the [crates.nvim](https://github.com/Saecki/crates.nvim) plugin, but I can't get the autocompletion to work (the autocompletion stops working for any source), is there any correct way to load the source required by the plugin.

I have tried with these options, but it doesn't work https://github.com/Saecki/crates.nvim#nvim-cmp-source.
I tried this way too, but it stops autocomplete. 

![imagen](https://user-images.githubusercontent.com/55039048/202206753-b477423b-7418-475d-b568-165ad4f06628.png)

what I expect:
![imagen](https://user-images.githubusercontent.com/55039048/202207054-5903a93d-810b-45fb-b51d-0f165a40c8ca.png)

I get nothing :laughing:: 
![imagen](https://user-images.githubusercontent.com/55039048/202207288-eeb52130-dcd7-49d6-b41f-856551120546.png)

I also tried adding in overriding `/custom/plugins/override.lua`
![imagen](https://user-images.githubusercontent.com/55039048/202208226-52e9e77e-2c22-4925-ba65-ef2b84fed9fd.png)

`custom/plugins/init.lua`
![imagen](https://user-images.githubusercontent.com/55039048/202208599-ca1ca89d-bd1a-4695-b389-a447b7491eb3.png)

**Comment by siduck** [comment]
["hrsh7th/nvim-cmp"] = {
  override_options = {
    sources = {
      { name = "nvim_lsp" },
      { name = "buffer" },
      { name = "nvim_lua" },
      { name = "path" },
      { name = "luasnip" },
      { name = "crates" },
    },
  },
}

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/202226974-238eaaa3-957d-4cc1-b6ec-f7b0f4ee158b.png)

this is not needed and remove it , use the cmp override before

**Comment by siduck** [comment]
```lua
 ['saecki/crates.nvim']  = {
    event = {"BufRead Cargo.toml"}
    tag = 'v0.3.0',
    config = function()
        require('crates').setup()
    end,
}
```

**Comment by siduck** [comment]
dont load it after cmp

**Comment by siduck** [comment]
then reopen nvim and do packercompile

**Comment by siduck** [comment]
@axdank dont worry, i will test it tomorrow for you :smiley:

**Comment by siduck** [comment]
@axdank really sorry, a lil busy these days. Can you please try asking it in any of our communities? ( discord, telegram, matrix )  maybe someone might help you there

**Comment by siduck** [comment]
btw it works completely fine here 
![image](https://user-images.githubusercontent.com/59060246/203762089-e3e575f9-7cc5-4150-9939-48c6e29795ba.png)

**Comment by siduck** [comment]
```lua

  ["hrsh7th/nvim-cmp"] = {
    override_options = {
      sources = {
        { name = "luasnip" },
        { name = "nvim_lsp" },
        { name = "buffer" },
        { name = "nvim_lua" },
        { name = "path" },
        { name = "crates" },
      },
    },
  },
  
   ["saecki/crates.nvim"] = {
    tag = "v0.3.0",
    event = { "BufRead Cargo.toml" },
    config = function()
      require("crates").setup()
    end,
  },

**Comment by mainrs** [comment]
@axdank Could you please share your final configuration? I cannot get the package to work...

**Comment by axdank** [comment]
hi @mainrs i use mi own configuration, without any distribution, but this is my crates plugin config:

I think you need to add this inside your crates plugin config:

```lua
  src = {
    cmp = {
      enabled = true,
    },
  },
```

final like this:
```lua
require("crates").setup({
  popup = {
    autofocus = true,
    show_version_date = true,
  },
  null_ls = {
    enabled = false,
    -- name = "crates.nvim",
  },
  src = {
    cmp = {
      enabled = true,
    },
  },
})
---@diagnostic disable-next-line: missing-fields
require("cmp").setup.buffer({ sources = { { name = "crates" } } })
```

Hope this can help you :smiley:

**Comment by mainrs** [comment]
@axdank Thank you! The thing is, I get an invalid key error when enabling `src.cmp`. I run hash 8437522, which is the v0.4.0 tag: https://github.com/Saecki/crates.nvim/releases/tag/v0.4.0

I installed it like this:

```lua
{
    "saecki/crates.nvim",
    tag = "v0.4.0",
    lazy = false,
    -- event = { "BufRead Cargo.toml" },
    config = function()
      require("crates").setup({
        popup = {
          autofocus = true,
          show_version_date = true,
        },
        null_ls = {
          enabled = false,
        },
        src = {
          cmp = {
            enabled = true,
          },
        },
      })
    end,
  },
  {
    "hrsh7th/nvim-cmp",
    override_options = {
      sources = {
        { name = "luasnip" },
        { name = "nvim_lsp" },
        { name = "buffer" },
        { name = "nvim_lua" },
        { name = "path" },
        { name = "crates" },
      },
    },
  },
``` 

__Edit:__ I removed the `v0.4.0` tag and it loads fine now. But it still does not provide completions... This is soooo frustrating.

**Comment by axdank** [comment]
@mainrs try this: 

```lua
{
    "saecki/crates.nvim",
    tag = "v0.4.0",
    lazy = false,
    -- event = { "BufRead Cargo.toml" },
    config = function()
      require("crates").setup({
        popup = {
          autofocus = true,
          show_version_date = true,
        },
        null_ls = {
          enabled = false,
        },
        src = {
          cmp = {
            enabled = true,
          },
        },
      })
      require("cmp").setup.buffer({ sources = { { name = "crates" } } })
    end,
  },
  {
    "hrsh7th/nvim-cmp",
    override_options = {
      sources = {
        { name = "luasnip" },
        { name = "nvim_lsp" },
        { name = "buffer" },
        { name = "nvim_lua" },
        { name = "path" },
      },
    },
  },
```

remove crates source in nvim-cmp and add ```require("cmp").setup.buffer({ sources = { { name = "crates" } } })``` next to crates setup

**Comment by mainrs** [comment]
This works, thank you very much!!!!!
