### ISSUE TITLE
Can't disable nvim standard virtual text

### ISSUE THREAD

**Issue by AdamJSoftware** [NvChad/NvChad#1684]
I'm trying to install https://git.sr.ht/~whynothugo/lsp_lines.nvim which I got working. However, disabling the standard diagnostics don't seem to work. I added the following in my chadrc and it seems that nothing has changed 

```
vim.diagnostic.config({
  virtual_text = false,
  virtual_lines = true,
});
```

Are you using some custom plugin to show diagnostics? Or am I supposed to put that code snippet somewhere else?

**Comment by siduck** [comment]
do it in your custom lspconfig
