### ISSUE TITLE
The TypeScript LSP running twice when opening .tsx and .ts files.

### ISSUE THREAD

**Issue by asrul10** [NvChad/NvChad#1687]
**Describe the bug**
The TypeScript LSP running twice when opening `.tsx` and `.ts` files.

**To Reproduce**
1. Open a `.ts` file
2. Then open a `.tsx` file in new buffer

**Expected behavior**
I am not sure but it should run `tsserver` once right?

**Screenshots**
![image](https://user-images.githubusercontent.com/8002919/202615356-ada0bf37-d0ba-4dad-b182-f5a6f5a1e486.png)
![image](https://user-images.githubusercontent.com/8002919/202615534-c47d89c8-a460-4747-98b7-a484fc86f59b.png)

**Desktop (please complete the following information):**
 - Operating System = WSL Ubuntu 22.04
 - Terminal = Windows Terminal
 - Version of Neovim = 0.8.1

**Additional context**
`tsserver` running twice hogging my ram 🥲

**Comment by siduck** [comment]
cant reproduce, show your custom lspconfig

**Comment by asrul10** [comment]
```lua
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"

local servers = {
  -- HTML CSS
  "html",
  "cssls",
  "tailwindcss",

  -- TypeScript, JavaScript
  "tsserver",

  -- PHP
  "intelephense",
  "eslint",

  -- Go
  "gopls",
}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
```

Here full custom config https://github.com/asrul10/nvchad-custom

**Comment by siduck** [comment]
@asrul10 does this happen for all ts/tsx files?

**Comment by asrul10** [comment]
Yes, but when I just open a ts/tsx file, only one tsserver is running.

It only happens when I open both ts and tsx files.

**Comment by siduck** [comment]
i cant reproduce 
![image](https://user-images.githubusercontent.com/59060246/202670033-a96dfea9-f80f-40d3-9669-7d3a29ba456a.png)

**Comment by asrul10** [comment]
Hmm, that's strange.

My project is on a monorepo with turborepo.

Is it possible because of it?

I'll get back, I'll try compare the project with monorepo and not.

**Comment by asrul10** [comment]
![image](https://user-images.githubusercontent.com/8002919/202678947-4f6d9653-fd3f-4fac-ae38-2601134d103f.png)

Yes, it is because of the monorepo structure. I try another project without monorepo and the tsserver is not running twice.

**Comment by siduck** [comment]
if it happens with this too https://github.com/nvim-lua/kickstart.nvim then this isnt a nvchad issue, test it!

**Comment by asrul10** [comment]
![image](https://user-images.githubusercontent.com/8002919/202837977-dd74e851-db3b-4cf0-aef5-77707b7a0c72.png)

Confirmed it's not nvchad issue.

I close the issue, thanks.

**Comment by siduck** [comment]
@asrul10 all good man! if you need quick help then ask it in our communities ( discord, telegram, matrix servers ) . You'd find help faster there when im not present

**Comment by luovkle** [comment]
I have been experiencing the same problem, so far I have not found a definitive solution. But something that may help to fix the problem temporarily is to go back to a commit of nvim-lspconfig where this problem is not found.

I have tried going back to commit 22c87d6 and everything seems to work fine.

```sh
cd ~/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig/
git checkout 22c87d6
```

It may not be the most elegant solution, but it can be useful for people who do not have time for these mistakes.
