### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by siduck76** [NvChad/NvChad#169]
I always wanted to use those fancy vim frameworks but they felt slow , ugly and lots of stuffs added by default , So I had to create NvChad to function neovim as I want on my potato pc while still being fast and beautiful.

**Comment by Pocco81** [comment]
NvChad was the first nvim config I used when I first transitioned form Vim to NeoVim. It's truly been a blessing to have such a reliable yet fast config that served very well as a foundation for my very own config. Thanks for putting so much effort into this!

**Comment by Akianonymus** [comment]
Nvchad, the configuration we need but we don't deserve, xD.

**Comment by G-Rowell** [comment]
NvChad makes NeoVim feel like a proper editor for programming,
whilst still remaining lighter & faster than any GUI based IDE :smile:

**Comment by JavaCafe01** [comment]
I got lazy

**Comment by CTZxVULKAN** [comment]
NvChad is blazing fast, its minimal and gets the job done. 
My earlier nvim config was super powerful and could tackle almost anything when i was coding wether be it intellisense formating highlighting etc however vimsript is really slow and the config felt bloated. Getting Nvcode and then customising it to my own workflow has been gr8t. I am now an absolute chad infront of my friends who still use M$ word to code.

This might sound like a scammy review and i was not paid to say this lamo :)

**Comment by siduck76** [comment]
This issue increases the issue number count  , hence Bloat xD
