### ISSUE TITLE
custom chadrc errors/swallowed masked

### ISSUE THREAD

**Issue by mattbdc** [NvChad/NvChad#1690]
Getting to grips with nvchad now however spent a good few hours struggling blindly with a failing custom.chadrc - should the error get checked in core.utils  (no else branch on the error check) - how about if error ends with "not found" then remain silent - otherwise print the error (and terminate) ?  silence seems the wrong choice here but I must admit I'm new here. I temporarily replaced the pcall wrappred require custom.chadrc in core.utils here so I fail fast but obvious one can be smarter here for the expected non-exceptional case where custom.chadrc isn't found

I'm wondering if this is desirable before proceeding - I realize one could potentially test if this is failing by requiring via :lua require("custom.chadrc") via the command mode in a nvim instance but I think that's several hours down the line from hour 0 - and people are likely to tweak in custom before hour 7 imo..  are we optimizing for performance at the cost of approach-ability ?

**Comment by siduck** [comment]
i will soon remove the things that were preventing errors to show up, example https://github.com/NvChad/NvChad/blob/main/lua/core/utils.lua#L12 

@Akianonymus had added it previously

**Comment by mattbdc** [comment]
https://github.com/NvChad/NvChad/blob/main/lua/core/utils.lua#L16 you might be able to catch some config mistakes intelligently but you won't catch everything as you have no else branch here

what if there's a typo, a bad variable, a print(nonexist + 1) just to illustrate

**Comment by mattbdc** [comment]
```
if chadrc_exists then
    -- merge user config if it exists and is a table; otherwise display an error
    if type(chadrc) == "table" then
      config.mappings = M.remove_disabled_keys(chadrc.mappings, config.mappings)
      config = merge_tb("force", config, chadrc) or {}
    else
      error "chadrc must return a table!"
    end
 else
   if not chadrc.endswith("not found:") then
    print("loading custom.chadrc threw an error - check your custom.chadrc and any downstream requires")
     print(chadrc)
   end 
 end
```

i dont know if endswith existss

**Comment by siduck** [comment]
@mattbdc we cant print the "chadrc not found" error everytime, because there are users who just want to use vanilla nvchad i.e without chadrc etc then according to your code, they will get that "chadrc not found" warning every time which isnt good.

**Comment by mattbdc** [comment]
Note the NOT, if it isn't found the error message ends with not found and thus we remain silent

**Comment by siduck** [comment]
hmm i dont think there's an endwith function in lua

**Comment by siduck** [comment]
also `pcall(require, 'custom.chadrc')` itself indicates that its trying to call `custom/chadrc.lua` so i dont think the last `else` statement is needed

**Comment by mattbdc** [comment]
We want to know when it fails, when that failure isn't because it doesn't exist

**Comment by ii14** [comment]
> i will soon remove the things that were preventing errors to show up, example https://github.com/NvChad/NvChad/blob/main/lua/core/utils.lua#L12

This still silences errors. It only errors if the return value is invalid, but all errors inside the module will be ignored.

I'd suggest to just not use `require` in the first place. Instead search for the file and just run it if it exists.
```lua
local path = vim.api.nvim_get_runtime_file('nvchad.lua', false)[1]
if path then dofile(path) end
```
By doing this you don't even have to put the configuration inside `lua/` directory. It can be just `~/.config/nvim/nvchad.lua` or something like that.
If you want to keep backwards compatibility, you can use `lua/custom/init.lua` and/or `lua/custom.lua`.

**Comment by mattbdc** [comment]
> > I think you're missing the point - endswith we are just testing string it could be a regex with a $ if needed, there always a way to test a string even if we go caveman I mention it to say I'm just pseudo coding here but focus on the intent
> 
> i mean chadrc variable there is just a module, i dont see why endswith is being used there. iirc endswith is used strings right so why use it there?

chadrc isn't a module when it errors. when chadrc_exists is false chadrc is not a module

**Comment by mattbdc** [comment]
I agree with ii14, test the path and if exists just require the module, problem solved - errors no longer swallowed. 

If we're all agreed with this solution I will submit a PR (unless you want to do honours @ii14 ?) leaving the paths intact for now (i.e. custom.chadrc)

**Comment by mattbdc** [comment]
> > I think you're missing the point - endswith we are just testing string it could be a regex with a $ if needed, there always a way to test a string even if we go caveman I mention it to say I'm just pseudo coding here but focus on the intent
> 
> i mean chadrc variable there is just a module, i dont see why endswith is being used there. iirc endswith is used strings right so why use it there?

This might help:

```
  ~ cat bad.lua 
local a = nil + 1
➜  ~ cat main.lua 
local chadrc_exists, chadrc = pcall(require, "bad")

print("exists: " .. tostring(chadrc_exists))
if not chadrc_exists then
  print(type(chadrc))
end
➜  ~ lua main.lua 
exists: false
string
➜  ~ 
```
