### ISSUE TITLE
Shade and Mason might have some conflicts

### ISSUE THREAD

**Issue by lijunzh** [NvChad/NvChad#1696]
**Describe the bug**
When `shade` is installed using the following config:
```lua
	["andreadev-it/shade.nvim"] = {
		-- opt = true,
		config = function()
			local present, shade = pcall(require, "shade")

			if not present then
				return
			end

			shade.setup({
				overlay_opacity = 50,
				opacity_step = 1,
				exclude_filetypes = { "NvimTree" },
			})
		end,
	},
```
The Mason was is unexpectedly dimmed and no text can be seen as demonstrated in the figure below:

![Screen Shot 2022-11-24 at 9 04 25 AM](https://user-images.githubusercontent.com/9093413/203815442-c6aaa663-260a-4192-8087-44ac01ac7c67.png)

When the above code block is commented, the mason window is shown correctly as following:

![Screen Shot 2022-11-24 at 9 05 38 AM](https://user-images.githubusercontent.com/9093413/203815658-6e6e3180-f874-4045-988c-1746fcc4ea95.png)

**To Reproduce**
See description.

**Expected behavior**
Mason window should show correctly when shade is installed (which works before I upgraded)

**Screenshots**
See description.

**Desktop (please complete the following information):**
 - MacOS
 - Alacritty
 - NVim v0.8.1

**Comment by lijunzh** [comment]
Maybe we can consider add something for `mason` in the `exclude_filetypes` field?

**Comment by lijunzh** [comment]
I followed the configuration of `shade` here: https://github.com/siduck/dotfiles/blob/master/nvchad/custom/plugins/shade.lua

**Comment by siduck** [comment]
hi @lijunzh this isnt a nvchad issue. Also shade.nvim doesnt support excluding dimming of filetypes,  But you can try this fork https://github.com/andreadev-it/Shade.nvim 

This PR is un-merged https://github.com/sunjon/Shade.nvim/pull/30 so uses its fork ( check readme for excluding filetype option )
