### ISSUE TITLE
Rust-tools with nvchad 

### ISSUE THREAD

**Issue by traderdude123** [NvChad/NvChad#1697]
How do you make NvChad work with rust tools. 

I got it working with rust_analyzer , but rust-tools says not to install rust_analyzer. 

I m using (https://github.com/simrat39/rust-tools.nvim)

Is there any tutorial or steps to get this working with nvchad. 

I even tried the suggestion posted by other who faced this issue, but the nvchad configuration has changed i guess.

Please help. I m about to give up neovim and go to clion.

**Comment by siduck** [comment]
load it after lspconfig

**Comment by traderdude123** [comment]
I found coc-rust-analyzer works better with vim. 

ditching rust-tools.nvim.

closing the issue.

**Comment by pwnwriter** [comment]
hey @traderdude123 , Ayo. How did you setup rust.tools in nvchad ? A lil' guide will be very helpful :)

**Comment by siduck** [comment]
> hey @traderdude123 , Ayo. How did you setup rust.tools in nvchad ? A lil' guide will be very helpful :)

just load rust_tools after lspconfig plugin
