### ISSUE TITLE
Diagnostics goto next mapping

### ISSUE THREAD

**Issue by ljnsn** [NvChad/NvChad#1698]
https://github.com/NvChad/NvChad/blob/54b364932450706b7355818f01a929fd1a77861e/lua/core/mappings.lua#L216-L221

Not sure whether this is intentional or not, but I think it would make more sense for the mapping for going to next diagnostic were `]d` instead of `d]`, like it's for moving between hunks as well, for example (`[c` and `]c`).

If intentional, no problem I can easily overwrite this, otherwise happy to make a PR.

On a side note, I think the description should also be `goto next`, like it is for `goto prev`, instead of `goto_next`.

**Comment by siduck** [comment]
this has been fixed in the dev branch.
