### ISSUE TITLE
How to enable nvim-cmp plugin featrue: buffer cmp for search, and path for command mode

### ISSUE THREAD

**Issue by saibing** [NvChad/NvChad#1699]
**Describe the bug**
I can not find a correct place to config nvim-cmp support: buffer cmp for search, and path for command mode
```lua
  -- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline({ '/', '?' }, {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
      { name = 'buffer' }
    }
  })

  -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })
```

**To Reproduce**

**Expected behavior**

The behavior as [feat: buffer cmp for search, and path for command mode](https://github.com/LunarVim/LunarVim/commit/9509cadf402fd85f8a184fe334f870d701fdc48a)

**Screenshots**

![image](https://user-images.githubusercontent.com/5676390/204125214-e5ec0293-1777-45f5-8f36-c84c7cdecf35.png)

**Desktop (please complete the following information):**
 - Operating System:  Ubuntu 22.04
 - Terminal: Windows Terminal 
 - Version of Neovim 0.8

**Additional context**

**Comment by siduck** [comment]
```lua
["hrsh7th/nvim-cmp"] = {
    config = function()
      local cmp = require "cmp"

      cmp.setup.cmdline({ "/", "?" }, {
        mapping = cmp.mapping.preset.cmdline(),
        sources = {
          { name = "buffer" },
        },
      })

      -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
      cmp.setup.cmdline(":", {
        mapping = cmp.mapping.preset.cmdline(),
        sources = cmp.config.sources({
          { name = "path" },
        }, {
          { name = "cmdline" },
        }),
      })

      require "plugins.configs.cmp"
    end,
  },
  ```
  
  in your custom plugins table

**Comment by siduck** [comment]
this cmp cmdline feature looks very nice! i will include it in v2.0 release of nvchad :D

**Comment by chuan137** [comment]
adding this to my dotfile, it however broken my auto command to open at last position. I have this in init.lua. Maybe because of lazy loading?

> autocmd("BufRead", {
> 	pattern = { "*" },
> 	command = [[call setpos(".", getpos("'\""))]],
> })

**Comment by siduck** [comment]
@chuan137 show your full custom init.lua
