### ISSUE TITLE
Is this the correct keymap?

### ISSUE THREAD

**Issue by sha5010** [NvChad/NvChad#1700]
https://github.com/NvChad/NvChad/blob/54b364932450706b7355818f01a929fd1a77861e/lua/core/mappings.lua#L209-L221

The default keymap on line 216 is `d]`, but shouldn't it be `]d` correctly?

**Comment by siduck** [comment]
@sha5010 its fixed in the dev branch, v2.0 will be arriving soon.

**Comment by sha5010** [comment]
Oh, I'm sorry.
I didn't check the fixed commit on the dev branch.
I look forward to the new version being released.
Thanks.
