### ISSUE TITLE
Can't set vim options in custom/init.lua

### ISSUE THREAD

**Issue by tsjordan-eng** [NvChad/NvChad#1701]
**Describe the bug**
When I set vim settings in custom/init.lua some don't take effect.
ex:
```lua
vim.g.rainbow_comment_prefix = '#' -- custom plugin global
vim.o.wrap = false -- vim builtin, don't wrap lines
```
**To Reproduce**
1. put vim options like the ones above in your init file and they don't take effect.

**Expected behavior**
The options set there should take effect.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Terminal
 - Version of Neovim: 0.8.0

**Additional context**
N/A

**Comment by siduck** [comment]
if those options are invalid then they wont work like that. please use vim.opt

**Comment by tsjordan-eng** [comment]
This still doesn't work with `vim.opt`. I can't see where these options would be overwritten or ignored. Is there another place for them?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/204446478-3367b361-cbf2-4789-b6d0-d7a2fd27ffc7.png) we have this set in our default options config, idk if there's a difference between wrap and whichwrap

**Comment by tsjordan-eng** [comment]
`wrap` enables the wrapping, `whichwrap` allows easy movement between line of a wrap.

Oddly enough lines like:
```lua
vim.g.loaded_matchit = nil
vim.g.loaded_tar = nil
vim.g.loaded_tarPlugin = nil
```

work to make nvim enable matchit and tar plugins that are disabled by NvChad by default. But the settings above don't seem to stick.

**Comment by siduck** [comment]
@tsjordan-eng to enable default vim plugins 

```lua
 local enable_providers = {
      "python3_provider",
      "matchit",
      -- and so on
    }
    
    for _, plugin in pairs(enable_providers) do
      vim.g["loaded_" .. plugin] = nil
      vim.cmd("runtime " .. plugin)
    end
    ```

**Comment by tsjordan-eng** [comment]
My lines to enable vim plugins *do* work (as does your loop). But trying to set other variables for other plugins doesn't seem to work.

**Comment by siduck** [comment]
> My lines to enable vim plugins _do_ work (as does your loop). But trying to set other variables for other plugins doesn't seem to work.

which variables?

**Comment by tsjordan-eng** [comment]
The ones in my original post:
```
vim.g.rainbow_comment_prefix = '#' -- custom plugin global
vim.o.wrap = false -- vim builtin, don't wrap lines
```

**Comment by tsjordan-eng** [comment]
uh... I rearranged some lines and the `vim.o.wrap = false` now works. The other one must be an issue with rainbow CSV.

Sorry about this, I'm trying to wrap my mind around this config as opposed to typical nvim lua config (I come from vim config)
