### ISSUE TITLE
Java lsp (jdtls) not activating

### ISSUE THREAD

**Issue by IBugraGezer** [NvChad/NvChad#1705]
**Describe the bug**
I followed the instructions on this page [https://nvchad.com/config/Language Server Protocol](url) 
Installed jdtls via mason. 
Lua lsp works fine but java lsp not.
When run :LspInfo on any java file, i get this
![Screenshot from 2022-12-07 02-04-41](https://user-images.githubusercontent.com/72858973/206043723-7f73dc0c-e87c-4877-8e68-4c91ca2166e8.png)

**To Reproduce**
1. git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
2. Create ~/.config/nvim/lua/custom folder
3. Create custom/chadrc.lua file
```
local M = {}
M.plugins = require "custom.plugins"
return M
```
4. Create custom/plugins/init.lua file
```
return {
  ["neovim/nvim-lspconfig"] = {
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.plugins.lspconfig"
    end,
  },
}
```
5. Create custom/plugins/lspconfig.lua file
```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local servers = { "jdtls"}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
```
6. Run :PackerCompile
7. Run :MasonInstall jdtls
8. Open any java file and run :LspInfo

**Expected behavior**
Jdtls lsp should be attached but not

**Screenshots**
Added

**Desktop (please complete the following information):**
 - Fedora 36
 - bash
 - 0.8.1

**Comment by siduck** [comment]
make sure your cwd matches the root_dir pattern defined in lspconfig plugin for jdtls

**Comment by IBugraGezer** [comment]
> make sure your cwd matches the root_dir pattern defined in lspconfig plugin for jdtls

sorry, how do i check it?

**Comment by Alexis12119** [comment]
Can you try this?
```
local home = vim.env.HOME
local jdtls_path = vim.fn.stdpath "data" .. "/mason/packages/jdtls/"
local equinox_version = "1.6.400.v20210924-0641"

if vim.fn.has "mac" == 1 then
  WORKSPACE_PATH = home .. "/workspace/"
  OS_NAME = "mac"
elseif vim.fn.has "unix" == 1 then
  WORKSPACE_PATH = home .. "/workspace/"
  OS_NAME = "linux"
else
  WORKSPACE_PATH = home .. "/workspace/"
  OS_NAME = "win"
end

lspconfig.jdtls.setup {
  on_attach = require("plugins.configs.lspconfig").on_attach,
  capabilities = require("plugins.configs.lspconfig").capabilities,
  cmd = {
    -- 💀
    "java", -- or '/path/to/java17_or_newer/bin/java'
    -- depends on if `java` is in your $PATH env variable and if it points to the right version.

    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=ALL",
    "-Xms1g",
    "--add-modules=ALL-SYSTEM",
    "--add-opens",
    "java.base/java.util=ALL-UNNAMED",
    "--add-opens",
    "java.base/java.lang=ALL-UNNAMED",
    -- 💀
    "-jar",
    jdtls_path .. "plugins/org.eclipse.equinox.launcher_" .. equinox_version .. ".jar",
    -- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       ^^^^^^^^^^^^^^
    -- Must point to the                                                     Change this to
    -- eclipse.jdt.ls installation                                           the actual version

    -- 💀
    "-configuration",
    jdtls_path .. "config_" .. OS_NAME,
    -- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        ^^^^^^
    -- Must point to the                      Change to one of `linux`, `win` or `mac`
    -- eclipse.jdt.ls installation            Depending on your system.

    "-data",
    WORKSPACE_PATH,
  },
}
```

**Comment by IBugraGezer** [comment]
> make sure your cwd matches the root_dir pattern defined in lspconfig plugin for jdtls

sorry, what is cwd? how can i check it?

**Comment by IBugraGezer** [comment]
> Can you try this? This is what i did to make jdtls work
> 
> ```
> local home = vim.env.HOME
> local jdtls_path = vim.fn.stdpath "data" .. "/mason/packages/jdtls/"
> local equinox_version = "1.6.400.v20210924-0641"
> 
> if vim.fn.has "mac" == 1 then
>   WORKSPACE_PATH = home .. "/workspace/"
>   OS_NAME = "mac"
> elseif vim.fn.has "unix" == 1 then
>   WORKSPACE_PATH = home .. "/workspace/"
>   OS_NAME = "linux"
> else
>   WORKSPACE_PATH = home .. "/workspace/"
>   OS_NAME = "win"
> end
> 
> lspconfig.jdtls.setup {
>   on_attach = require("plugins.configs.lspconfig").on_attach,
>   capabilities = require("plugins.configs.lspconfig").capabilities,
>   cmd = {
>     -- 💀
>     "java", -- or '/path/to/java17_or_newer/bin/java'
>     -- depends on if `java` is in your $PATH env variable and if it points to the right version.
> 
>     "-Declipse.application=org.eclipse.jdt.ls.core.id1",
>     "-Dosgi.bundles.defaultStartLevel=4",
>     "-Declipse.product=org.eclipse.jdt.ls.core.product",
>     "-Dlog.protocol=true",
>     "-Dlog.level=ALL",
>     "-Xms1g",
>     "--add-modules=ALL-SYSTEM",
>     "--add-opens",
>     "java.base/java.util=ALL-UNNAMED",
>     "--add-opens",
>     "java.base/java.lang=ALL-UNNAMED",
>     -- 💀
>     "-jar",
>     jdtls_path .. "plugins/org.eclipse.equinox.launcher_" .. equinox_version .. ".jar",
>     -- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       ^^^^^^^^^^^^^^
>     -- Must point to the                                                     Change this to
>     -- eclipse.jdt.ls installation                                           the actual version
> 
>     -- 💀
>     "-configuration",
>     jdtls_path .. "config_" .. OS_NAME,
>     -- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        ^^^^^^
>     -- Must point to the                      Change to one of `linux`, `win` or `mac`
>     -- eclipse.jdt.ls installation            Depending on your system.
> 
>     "-data",
>     WORKSPACE_PATH,
>   },
> }
> ```

not works :(
i paste it to my custom init.lua

**Comment by Alexis12119** [comment]
> > make sure your cwd matches the root_dir pattern defined in lspconfig plugin for jdtls
> 
> my project folder contains pom.xml ![Screenshot from 2022-12-07 09-40-17](https://user-images.githubusercontent.com/72858973/206107151-e35f14b2-8917-43a3-b8da-cbf24899d951.png) did you mean this?

Can you try the code again?

**Comment by IBugraGezer** [comment]
![Screenshot from 2022-12-07 10-09-27](https://user-images.githubusercontent.com/72858973/206111931-a4ff66ed-4d9d-42ce-aa81-e03fc19e40a0.png)
this is my init.lua
"step 3" is not printing

**Comment by IBugraGezer** [comment]
I solved it by clearing jdtls cache
`rm -rf ~/.cache/jdtsl`
