### ISSUE TITLE
plugin not loaded

### ISSUE THREAD

**Issue by ryannewcomer** [NvChad/NvChad#1711]
**Describe the bug**
hi, i just download nvchad and use it for web dev. but when i run :PackerStatus,  and i saw that not all the plugin is loaded. i need to run :PackerLoad plugiin ot load it. And when i open nvim again, the plugin is not loaded again even i run :PackerSync

**To Reproduce**
1.run :PackerStatus
2. see error

**Expected behavior**
I expect that all the plugin should be loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/88273136/207438729-f715d785-a1bd-49d7-8492-176bad6cae43.png)
![image](https://user-images.githubusercontent.com/88273136/207438860-8205705d-47e8-400b-b235-f143c5e2a3e4.png)

**Desktop (please complete the following information):**
 - Operating System: window 11 Home v 22H2
 - Terminal: PowerShell 7 on window termianl
 - Version of Neovim: 
 NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-11

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

**Additional context**
no

**Comment by siduck** [comment]
this is normal, 90% of plugins in nvchad are lazy loaded.
