### ISSUE TITLE
Unable to override nvim-tree config

### ISSUE THREAD

**Issue by qejecooo** [NvChad/NvChad#1725]
Hi! I'm new to NvChad, and I want it to enable nvim-tree by default when I open nvim. I saw an issue here, how to do it, but still it doesn`t work.

lua/custom/chadrc.lua:
```
  local M = {}
  M.plugins = {
    ["google/vim-searchindex"] = {},

    default_plugin_config_replace = {
      ["kyazdani42/nvim-tree.lua"] = {
        after = "nvim-web-devicons",
        open_on_setup = true,
       },
     },
  }

  M.ui = {
    theme = "ayu-dark",
  }

  return M
```
Extra: PackerCompile works only once, and if I`m trying to use it again it is throwing and error, is that okay?

Expected result: nvimtree opens automatically on nvim start

OS: Ubuntu 20.04 via ssh through Powershell(if that matters)

Thanks a lot!

**Comment by siduck** [comment]
the syntax is totally outdated, read our docs please!!

**Comment by siduck** [comment]
```lua
local M = {}

M.plugins = {
  ["google/vim-searchindex"] = {},

  ["kyazdani42/nvim-tree.lua"] = {
    event = "VimEnter",
    override_options = {
      open_on_setup = true,
    },
  },
}

M.ui = {
  theme = "ayu-dark",
}

return M
```
