### ISSUE TITLE
Language Server does not work

### ISSUE THREAD

**Issue by RIGIK93** [NvChad/NvChad#1728]
**Describe the bug**
Seems like language server's not working. There's no recognition of variables, function, libraries. It's all just marked as text. No error detection.

**To Reproduce**
1. Install neovim
2. Install NvChad
3. Install cpptools in Mason

**Expected behavior**
- Errros should be detected
- libraries should be detected
- variables, function, etc. should be detected

**Screenshots**
![1](https://i.imgur.com/punGFrn.png)
![image](https://user-images.githubusercontent.com/54111742/210127164-aab64027-50e2-403b-a5ed-aaddc7875b36.png)

**Desktop (please complete the following information):**
 - Operating System: Debian 11
 - Terminal: Konsole (Debian default)
 - Version of Neovim: 8.0

**Additional context**
I tried using `kickstart.nvim` config, and it worked fine.

**Comment by siduck** [comment]
please enable the lsp server in your custom lspconfig

**Comment by siduck** [comment]
and i dont see docs for cpptools in nvim-lspconfig readme, how does it even work for you?
