### ISSUE TITLE
whichkey doesn't work 

### ISSUE THREAD

**Issue by jatins** [NvChad/NvChad#1735]
**Describe the bug**
whichkey mapping seems to be `<leader>wK` based on mappings.lua https://github.com/NvChad/NvChad/blob/main/lua/core/mappings.lua#L365-L383

```
M.whichkey = {
  plugin = true,

  n = {
    ["<leader>wK"] = {
      function()
        vim.cmd "WhichKey"
      end,
      "which-key all keymaps",
    },
    ["<leader>wk"] = {
      function()
        local input = vim.fn.input "WhichKey: "
        vim.cmd("WhichKey " .. input)
      end,
      "which-key query lookup",
    },
  },
}
```

However pressing that key combination does not seem to do anything.

**To Reproduce**
Press `Space + w + shift + k`

**Expected behavior**
which key panel should show up

**Screenshots**
<img width="1087" alt="whichkey" src="https://user-images.githubusercontent.com/1556536/210758264-c7343ab7-3e1f-499d-a1c4-42a1b8088549.png">

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Terminal: iTerm
 - Version of Neovim
```
$ nvim --version                                                                                                                                                        
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Additional context**
there is an error shown in screenshot above, maybe that's relevant?

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/210759274-4a13a899-0770-4daa-b1a0-0f4992296799.mp4
works fine here, u need to press it fast

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/210760054-f5785fd8-8571-46a3-a088-a18e6bdc0f7c.mp4

https://user-images.githubusercontent.com/59060246/210759274-4a13a899-0770-4daa-b1a0-0f4992296799.mp4
works fine here, u need to press it fast

**Comment by jatins** [comment]
<img width="471" alt="whichkey command" src="https://user-images.githubusercontent.com/1556536/210774337-b7219dc0-33d1-4022-99b2-88f70a86ac08.png">

Hmm, looks like I don't have `:WhichKey` command available either. Any idea why that might be? I tried `PackerClean` and 'PackerSync' but no luck

**Comment by siduck** [comment]
@jatins , its disabled by default! add this in  your custom plugins table

['folke/which-key.nvim'] = { disable = false }

**Comment by jatins** [comment]
thanks, just for reference adding following lines to chadrc.lua worked

```
-- lua/custom/chadrc.lua

M.plugins = {
  ["folke/which-key.nvim"] = { disable = false }
}
```
