### ISSUE TITLE
How to install custom plugin correctly? 

### ISSUE THREAD

**Issue by hitchhooker** [NvChad/NvChad#1738]
![image](https://user-images.githubusercontent.com/15621959/211133345-23ae77cc-456e-467a-bdf4-2bd5d1b44bc9.png)

I have tried to follow my best docs and editing .config/nvim/lua/custom/plugins/init.lua file to add copilot.lua.

Is there some unmentioned extra steps required for installing? better-escape doesnt seem to work either that exist in config file. 
Have initiated :PackerSync which didnt help. Do I need to use :PackerInstall package/name even when configs in use?

**Comment by siduck** [comment]
check our example_config repo and read the docs well

**Comment by hitchhooker** [comment]
'''  -- Install a plugin
  ["max397574/better-escape.nvim"] = {
    event = "InsertEnter",
    config = function()
      require("better_escape").setup()
    end,
  },'''

**Comment by hitchhooker** [comment]
clearing nvim folders and reinstalling solved.

**Comment by siduck** [comment]
> clearing nvim folders and reinstalling solved.

cool :grimacing:

**Comment by siduck** [comment]
> clearing nvim folders and reinstalling solved.

probably was a packer issue, im adding lazy.nvim from v0.2 release

**Comment by nmsobri** [comment]
Sorry for hijacking this, how do I install plugin that have a dependency on another plugin?
Specifically, I want to install this [https://github.com/kevinhwang91/nvim-ufo#installation](https://github.com/kevinhwang91/nvim-ufo#installation)

**Comment by siduck** [comment]
@nmsobri its better for you to seek help in our communities ( discord etc ) check readme badges for links

["ufo blabla"] =  {
   requires = "blabla "
 }
