### ISSUE TITLE
Where is the dashboard config coming from?

### ISSUE THREAD

**Issue by hrqmonteiro** [NvChad/NvChad#1742]
I am trying just to copy your dashboard config, and i searched on everything and couldn't find??

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/alpha.lua

@hrqmonteiro  alpha's config might look complex and confusing, in few weeks nvchad v2.0 will release and i made our own dashboad module whose config is really easy
