### ISSUE TITLE
Idea for 2.0: Put core into external Plugin

### ISSUE THREAD

**Issue by vypxl** [NvChad/NvChad#1750]
**Is your feature request related to a problem? Please describe.**
Currently, the NvChad core resides in this repository, which is supposed to be cloned into `~/.config/nvim`. User configuration resides in `~/.config/nvim/custom` and is gitignored. That makes it hard to have a personal dotfiles repository because the NvChad repo and personal files are in the same place. Additionally, NvChad has to be updated manually (albeit via a shortcut inside neovim), instead of the package manager updating it like any other plugin.

**Describe the solution you'd like**
I discovered that the new [LazyVim](https://github.com/LazyVim/LazyVim) premade config (not to be confused with the new package manager) works by having a small bootstrap script that should be committed into the user's own repository, which loads the package manager and the LazyVim plugin. See [LazyVim starter](https://github.com/LazyVim/starter).

It would be nice to have NvChad work in this way too, for the reasons stated above.

**Describe alternatives you've considered**
The current system works, it could be kept.
It's just a little inconvenient for users like me who track their dotfiles with git.

**Additional context**

I think the 2.0 release would be a good time to introduce this, as it might break some user configurations.

Implementation-wise, I don't know how much effort it would take, but I think implementing it should just involve some restructuring, some changed require paths and of course updated documentation.

**Comment by siduck** [comment]
why not just symlink? ` ln -s mydotfiles/custom/ ~/.config/nvim/lua/custom`

**Comment by vypxl** [comment]
That is what I'm currently doing :)

This solution has only one problem: no automatic setup. You would have to clone NvChad manually before using nvim.

I have a little init.vim script that does that and creates the link and deletes itself afterward, but that's ugly

**Comment by vypxl** [comment]
Another caveat: People browsing my dotfiles repo are confused because they don't know nvchad, and look into the nvim directory instead of the nvchad directory

**Comment by siduck** [comment]
> That is what I'm currently doing :)
> 
> This solution has only one problem: no automatic setup. You would have to clone NvChad manually before using nvim.
> 
> I have a little init.vim script that does that and creates the link and deletes itself afterward, but that's ugly

yep  thats the only thing you can do

**Comment by siduck** [comment]
think nvchad as a package, like whenever setting up your system, you would install some packages for your setup right? just add git clone command of nvchad or you could make a package for this, something like this probably https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nvchad-git
