### ISSUE TITLE
Proper way to change icon color in nvim-tree

### ISSUE THREAD

**Issue by Ethanol48** [NvChad/NvChad#1752]
I can change the color of icons but an error occurs

**To Reproduce**
1. Go to 'custom.chadrc'
2. input the following code for M.plugins

```lua 
-- Nvimtree
["nvim-tree/nvim-tree.lua"] = {
    override_options = overrides.nvimtree,
     setup = function()
       require'nvim-web-devicons'.setup {
         override = {
           ["lua"] = {
             icon = "",
             color = "#f7f7f7"
           }
         },
       }
     end,
  },
```

3. Restart nvim

when restarting will output with error:
 
<img width="1440" alt="Screenshot 2023-01-24 at 18 18 38" src="https://user-images.githubusercontent.com/96821054/214364720-f00565a9-0f3d-41e6-9a7e-3396f99126c9.png">

restarting nvim the changes will be made in this case the icon of lua files will be white;

<img width="169" alt="Screenshot 2023-01-24 at 18 30 42" src="https://user-images.githubusercontent.com/96821054/214365593-6a878e05-5521-4895-8123-03ae46e04d7e.png">

but the custom keymaps made for nvim-tree don't work 

and when openning more than one file, this error occurs:
<img width="1138" alt="Screenshot 2023-01-24 at 18 22 13" src="https://user-images.githubusercontent.com/96821054/214365033-38c124cf-1dcb-4474-946e-c4c499ad0d09.png">

and the tabline breaks:

<img width="838" alt="Screenshot 2023-01-24 at 18 29 58" src="https://user-images.githubusercontent.com/96821054/214365243-f0553dbe-2fc7-4333-879c-9f3de24c15d8.png">

to change the icon color in nvim-tree you have to change it in ```require "nvim-web-devicons".setup{}``` and add an field ```overwrite = {}``` with the icons you want to change

What would be the correct way to do it?

 - MacOS
 - Alacritty
 - v0.8.2

**Comment by siduck** [comment]
@Ethanol48 use hl_override

```lua

M.ui = {

    hl_override = {
        
         DevIconlua = {
              
               fg = "red" 
               
          }
          
    }
    
    
  }

**Comment by Ethanol48** [comment]
Thanks !, another question is there a list of all the elements, is there a reference?

**Comment by siduck** [comment]
> Thanks !, another question is there a list of all the elements, is there a reference?

https://github.com/NvChad/base46/blob/master/lua/base46/integrations/devicons.lua

in the same integrations folder you will see various highlight groups of many plugins
