### ISSUE TITLE
print the error when require chadrc

### ISSUE THREAD

**Issue by Marskey** [NvChad/NvChad#1754]
M.load_config = function()
  local config = require "core.default_config"
  local chadrc_exists, chadrc = pcall(require, "custom.chadrc")

  if chadrc_exists then
    if type(chadrc) == "table" then
      config.mappings = M.remove_disabled_keys(chadrc.mappings, config.mappings
      config = merge_tb("force", config, chadrc) or {}
    else
      error "chadrc must return a table!"
    end
  else
    print(chadrc)
  end

  config.mappings.disabled = nil
  return config
end

**Comment by siduck** [comment]
already done in v2.0 branch
