### ISSUE TITLE
open_on_setup is now deprecated

### ISSUE THREAD

**Issue by dan003400** [NvChad/NvChad#1755]
https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup

https://github.com/NvChad/NvChad/blob/b9ec202f79148f60be142f88b11a01d7292b4e74/lua/plugins/configs/nvimtree.lua#L16

**Comment by siduck** [comment]
thanks for reporting, removed.

**Comment by dan003400** [comment]
I removed it from my config and I still see the deprecation warnings whens starting up nvim. Any ideas?

**Comment by siduck** [comment]
> I removed it from my config and I still see the deprecation warnings whens starting up nvim. Any ideas?

packercompile

**Comment by siduck** [comment]
i suggest you to try the v2.0 branch, it uses lazy.nvim and you wouldnt have to run packercompile after every change :nerd_face:

**Comment by dan003400** [comment]
Just updated to latest commit and also tried a packercompile and packersync since then but still seeing the error when opening the tree for the first time.

**Comment by dan003400** [comment]
Ah, looks like we also have to remove `ignore_ft_on_setup`. This finally removed my warnings.
