### ISSUE TITLE
Integrate with mason-lspconfig.nvim

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#1758]
mason-lspconfig.nvim facilitates interactions between mason and lspconfig, i.e. translates server names, makes sure they're registered, etc. For example. julia-lsp in mason is julials in lspconfig.

I'd like to be able to specify my language servers once in mason-lspconfig and have them automatically registered and loaded with lspconfig using that plugin.

Unfortunately, I can't seem to get this to work with the nvchad plugin system -- it never loads mason-lspconfig or it gets caught in a loop with mason.

**Comment by siduck** [comment]
no plans for it, do it in your custom config.

**Comment by danjenson** [comment]
That causes all hell to break loos with the nvchd_ui

![image](https://user-images.githubusercontent.com/4793438/216123726-7fc0dd78-2e8f-4476-8933-96db31b25105.png)


relevant part of `init.lua`:
```lua
	-- based on this: https://github.com/lucazz/dotfiles/pull/12/files
	["williamboman/mason.nvim"] = {
		rm_default_opts = true,
	},
	["neovim/nvim-lspconfig"] = {
		rm_default_opts = true,
	},
	["williamboman/mason-lspconfig.nvim"] = {
		after = "mason.nvim",
		config = function()
			require("mason-lspconfig").setup({
				automatic_installation = true,
				ensure_installed = { "sumneko_lua", "rust_analyzer", "pyright", "julials" },
			})
			require("plugins.configs.lspconfig")
		end,
	},
```

**Comment by siduck** [comment]
add , after = ui to mason and then after="mason.nvim" to nvim-lspconfig

**Comment by rokonio** [comment]
Looks like this is for an older version of Lazy, but how would you do it now ?

**Comment by siduck** [comment]
> Looks like this is for an older version of Lazy, but how would you do it now ?

check our example_config repo's featureful branch
