### ISSUE TITLE
NvChad doesn't load when running under root on Ubuntu 18.04

### ISSUE THREAD

**Issue by varp** [NvChad/NvChad#1761]
**Describe the bug**
I connect to ubuntu (18.04.5) server by SSH. When run nvim under unprivileged user, all is fine. NvCahd starts automatically install config and plugins on the first run. When I do the same under root nothing is happen. I get plain window of NVim, without run of NvChad on the first run.
I goes to root user after connect to server by: `sudo -iE`

**To Reproduce**
1. Connect to a Ubuntu 18.04.5 by SSH with unprivileged user 
2. Install nvim using snap `sudo snap install --beta nvim --classic`
3. Go to root by `sudo -iE`
4. Install NvChad and run nvim by `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
5. See nothing related to NvChad is happen on the first run 

**Expected behavior**
Fully load and featured NvChad )

**Screenshots**
Under unprivileged user
<img width="1440" alt="Screenshot 2023-02-04 at 20 13 28" src="https://user-images.githubusercontent.com/504685/216780599-0dfbcc81-c36d-4866-b683-66a1b885157a.png">
Under root user
<img width="1439" alt="Screenshot 2023-02-04 at 20 14 03" src="https://user-images.githubusercontent.com/504685/216780595-58dc45b0-5cbf-41e2-af35-6fe93b6aed0f.png">

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.04.5
 - Terminal: iTerm2
 - Version of Neovim: 0.8.2 

**Additional context**

**Comment by varp** [comment]
I think, possibly, it's caused by some config option difference in ~/.bashrc for unprivileged and privileged user, but I can't guess which one

**Comment by siduck** [comment]
thats normal, one thing you could do is copy your nvim dir to `/root/.config/nvim` , Im not sure if this is the right way but it works
