### ISSUE TITLE
GitSigns lazy loading not working

### ISSUE THREAD

**Issue by lynerlok** [NvChad/NvChad#1762]
**Describe the bug**
When I want to edit a project created with git, gitsigns.nvim not loading. I can load it manually and it works !

**To Reproduce**
1. Create a dummy git repo
2. Change dir to this repo
3. Create some files
4. exec `nvim .`
5. Navigate to a file with NvimTree
6. Run `:PackerStatus`

**Expected behavior**
In git project, gitsigns should load automatically. 

**Desktop (please complete the following information):**
 - Fedora Linux 37
 - Gnome-terminal
 - Nvim 0.8.2

**Comment by siduck** [comment]
open a file

**Comment by lynerlok** [comment]
I'm sorry but if I open a file concerned by versioning nothing happens…

Here a video of my problem. Maybe I made a mistake :/

https://user-images.githubusercontent.com/46053115/217034148-b6eff61c-7fd2-4acc-8aba-145cb37a608c.mp4

**Comment by siduck** [comment]
https://0x0.st/oC3k.mp4

works fine here

**Comment by lynerlok** [comment]
> https://0x0.st/oC3k.mp4
> 
> works fine here

Ok, this confirm that I've a problem on my side, maybe my config is broken, I checked that ! Thank you !

**Comment by lynerlok** [comment]
@siduck Hi ! I found the solution of my problem with gitsigns lazy loading.

I put the solution here if another user encounter this problem.

For a strange reason, in my Fedora and ZSH the error code isn't `-1` but `128`, so the gitsigns lazy loading function look like this :

```
M.gitsigns = function()
  autocmd({ "BufRead" }, {
    group = vim.api.nvim_create_augroup("GitSignsLazyLoad", { clear = true }),
    callback = function()
      vim.fn.system("git -C " .. vim.fn.expand "%:p:h" .. " rev-parse")
      if vim.v.shell_error == 128 then -- REPLACE -1 by the correct error code 128
        vim.api.nvim_del_augroup_by_name "GitSignsLazyLoad"
        vim.schedule(function()
          require("packer").loader "gitsigns.nvim"
        end)
      end
    end,
  })
end
```
and it works like a charm !

**Comment by siduck** [comment]
@lynerlok i dont use zsh and no idea about it! i'll add 128 error along with -1 in the condition too ( v2.0 branch ) . Thanks for catching out the but!
