### ISSUE TITLE
Weird thing 

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#1764]
**Describe the bug**
Surprise I'm still here siduck 😹. just a quick question, what is that thing (screenshot below)? I have never seen it before. I'm not sure if this is because of Nvchad itself or other plugins, cause after updated Nvchad (weeks ago) I didn't see that.

Q: Question, how can I remove/disable that?

**Screenshots**
![weird_taste](https://user-images.githubusercontent.com/73665622/217546897-25ebf150-7c14-44d2-a638-0340516e9b94.png)

**To Reproduce**
1. Open any file (ex: `nvim init.lua`)

**Desktop (please complete the following information):**
 - NVIM v0.8.3 Release

**Additional context**

**Comment by siduck** [comment]
not a nvchad thing, we didnt even mess with winbar yet.

**Comment by carlisia** [comment]
I think this comes with the latest upgrade of lspsaga.
