### ISSUE TITLE
E492: Not an editor command: TbufPick

### ISSUE THREAD

**Issue by mcctuxic** [NvChad/NvChad#1765]
**Describe the bug**
Start nvim with NVChad installed. In normal mode press backslash
"E492: Not an editor command: TbufPick" is displayed.
This blocks all Lisp plugins which utilize the Lisp REPL
(nvslime and others, which uses the slime/sly protocol)

**To Reproduce**
Start nvim with NVChad installed. In normal mode press backslash
"E492: Not an editor command: TbufPick" is displayed.

**Expected behavior**
There is no error. TbufPick can be found.
NVim without NVChad does not show this behaviour.

**Screenshots**

**Desktop (please complete the following information):**
GENTOO linux, updated daily.
wezterm
NVIM v0.9.0-dev-895+g0fc9a232e-dirty (error recognized previously)
NVChad just updated and checked before submitting.

**Additional context**

**Comment by siduck** [comment]
its useless to run tbufpick when there is just one buffer meaning that nvchad's tabufline is loaded only when there are 1+ files ( this happens for the first time ) and tbufpick is a tabufline command so watchout

**Comment by siduck** [comment]
\ is mapped to tbufpick in nvchad btw
