### ISSUE TITLE
Can't rewrite telescope config.

### ISSUE THREAD

**Issue by sunshinfight** [NvChad/NvChad#1769]
**Describe the bug**
I want to change the icon of telescope 'prompt_prefix', I read doc and clone [example_config](https://github.com/NvChad/example_config), It's work fine. then I add the rewrite code to 'custom/plugins/init.lua', but the font of telescope prompt prefix is not changed.

**To Reproduce**
1. `git clone git@github.com:NvChad/example_config.git`
2. move  this example config to `nvm/lua/custom/`
3. add config to `nvm/lua/custom/plugins/init.lua`. like screenshot blow.
` ["nvim-telescope/telescope.nvim"] = {
    override_options = {
      prompt_prefix = "   ",
      -- prompt_prefix = " ",
    },
  },
`
4. restart neovim 
5. not work, try PackerSync, not work

**Expected behavior**
change my telescope prompt_prefix.

**Screenshots**
this is my config screenshot in `nvm/lua/custom/plugins/init.lua`, the unicode can render correctly by Iterm2.
![CleanShot 2023-02-11 at 15 23 47@2x](https://user-images.githubusercontent.com/11806637/218246612-eae3df39-5ef5-4337-90dd-4995209db93b.jpg)

**Desktop (please complete the following information):**
 - Operating System: Macos 13.2
 - Terminal: Iterm3 v3.4.19
 - Version of Neovim: v0.8.3

**Additional context**
- nvchad: eac36d4
- git diff to head: none
- less ~/.cache/nvim/packer.nvim.log: 
.../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:682: No plugin selected!

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/218247336-78eb325d-6c5e-41ff-8513-48a95b21583b.png)

u forgot the "defaults" table, promptprefix comes under that boi

**Comment by sunshinfight** [comment]
Thanks,sorry to bother you with a low level mistake.@@

**Comment by siduck** [comment]
> Thanks,sorry to bother you with a low level mistake.@@

no worries,  you can ask it in our telegram group, matrix/discord servers
