### ISSUE TITLE
Error when running `:PackerSync` on a clean install

### ISSUE THREAD

**Issue by jleguina** [NvChad/NvChad#1772]
**Describe the bug**
Running `:PackerSync` on a clean install results in the following compilation error:
```vi
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:91: Vim:E492: Not an editor command: PackerSync 
Please check your config for correctness
```
When using my own config, this issue results in several unidentified commands.

**To Reproduce**
[Screencast from 12-02-23 17:34:23.webm](https://user-images.githubusercontent.com/92868166/218327253-17b72fe9-1614-4997-9f1d-82c86715a612.webm)

**Expected behavior**
Successful compilation.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 22.04.1
 - Terminal: GNOME
 - Version of Neovim: 0.8.3

Thanks.

**Comment by siduck** [comment]
@jleguina do a clean installation of nvchad, backup old neovim config and rm -rf .local/share/nvim

**Comment by siduck** [comment]
@jleguina not a nvchad issue, idk why packer commands are not available after packercompile. we're using lazy.nvim in v2.0 branch and it'll be released in this month.

And for your solution, just dont run packercompile before running another packer command or reopen nvim
