### ISSUE TITLE
Dashboard does not open on start.

### ISSUE THREAD

**Issue by Ghostdev84** [NvChad/NvChad#1774]
Dashboard does not open when i open neovim

**Comment by 1-minute-to-midnight** [comment]
`cd ~/.config/nvim/lua/plugins/init.lua`

search for alpha-nvim and change `disable=true` to `disable=false`

**Comment by siduck** [comment]
hi @Ghostdev84 dashboard is disabled by default and to enable it just override dashboard plugins's plugin definition




```lua
  ["goolord/alpha-nvim"] = {
    disable = false,
  },
```

reopen neovim and run packersync 

i hope you know where to add it! https://nvchad.com/config/plugins

**Comment by siduck** [comment]
v2.0 will be released this month which uses lazy.nvim and it has our own dashboard module!
