### ISSUE TITLE
Problems installing on windows

### ISSUE THREAD

**Issue by Zakaria-ouertani** [NvChad/NvChad#1775]
## Description and steps to reproduce

1) Run this command
```git clone https://github.com/NvChad/NvChad %USERPROFILE%\AppData\Local\nvim --depth 1 && nvim ```
Cloning completes successfully

2) nvim starts downloading the plugins but always fails on a lot of them
![image](https://user-images.githubusercontent.com/75418838/219198334-e88486e2-0598-435f-bda7-8cad0b94715e.png)

3) then shows these errors
![image](https://user-images.githubusercontent.com/75418838/219198858-ac7a0f79-8b1f-48df-845f-10496f5af9fc.png)

4) Then proceeds to show this screen and almost all features don't work
![image](https://user-images.githubusercontent.com/75418838/219198998-e6908f93-f7a0-4955-b23a-baafb2ea07e7.png)

## Expected behavior
Install nvchad

## Desktop Information
 - Windows 10 21h1
 - Terminal: cmd (conhost) 
 - Neovim 0.8.3

## Additional context
I installed nvchad successfully in the past but wanted to update it now.

**Comment by siduck** [comment]
@Zakaria-ouertani do you have network issues?

**Comment by jamesnolanverran** [comment]
My install went into C:\Users\userAppDataLocalnvim\ instead of C:\Users\user\AppData\Local\nvim\

**Comment by siduck** [comment]
git clone https://github.com/NvChad/NvChad $HOME\AppData\Local\nvim --depth 1 && nvim

**Comment by siduck** [comment]
from nvchad.com

**Comment by jamesnolanverran** [comment]
Yes that's exactly what I did. It's not a problem for me personally, I moved it manually. Just an fyi that it happened and I thought it might be related to this issue.

**Comment by siduck** [comment]
> Yes that's exactly what I did. It's not a problem for me personally, I moved it manually. Just an fyi that it happened and I thought it might be related to this issue.

weird, you probably mistyped

**Comment by jamesnolanverran** [comment]
I didn't type. I copied directly from the site using the copy thing, and I even double checked my terminal history to make sure.

**Comment by jamesnolanverran** [comment]
Maybe you need to use // for windows? Not sure.

**Comment by siduck** [comment]
> Maybe you need to use // for windows? Not sure.

very weird

**Comment by siduck** [comment]
we have many windows users but they never got this issue

**Comment by jamesnolanverran** [comment]
I am using git bash on windows where a single '\' is an escape character and that is what caused the problem with me.

**Comment by Zakaria-ouertani** [comment]
> @Zakaria-ouertani do you have network issues?

No I don't

When i try to git clone one of the failed ones manuall (like telescope) it works fine

**Comment by siduck** [comment]
very weird. @Zakaria-ouertani did you remove old neovim dirs?

**Comment by siduck** [comment]
> > very weird. @Zakaria-ouertani did you remove old neovim dirs?
> 
> Yes all i even uninstalled neovim and reinstalled
> 
> I doubt this makes a difference but i installed nvim with chocolatey, scoop, winget, and [bob](https://github.com/MordechaiHadad/bob) and each time Iinstalled nvchad with the same issue.

can you just install neovim 0.8.3 with one of them?

**Comment by Zakaria-ouertani** [comment]
> > > very weird. @Zakaria-ouertani did you remove old neovim dirs?
> > 
> > 
> > Yes all i even uninstalled neovim and reinstalled
> > I doubt this makes a difference but i installed nvim with chocolatey, scoop, winget, and [bob](https://github.com/MordechaiHadad/bob) and each time Iinstalled nvchad with the same issue.
> 
> can you just install neovim 0.8.3 with one of them?

i currently only have 0.8.3 using bob

**Comment by Zakaria-ouertani** [comment]
nvim and nvim-data folders are empty

**Comment by siduck** [comment]
does kickstart.nvim work for you? or can   you try cloning the v2.0 branch?

**Comment by Zakaria-ouertani** [comment]
@siduck 

When i clone v2.0 it the installation works fine
![image](https://user-images.githubusercontent.com/75418838/219435357-859a6e65-56ba-41ab-8b61-27bb6ff432ab.png)


But when i go to the update tab it show this
![image](https://user-images.githubusercontent.com/75418838/219435656-1daf29b8-28be-474f-8002-33c189d96a3a.png)

**Comment by siduck** [comment]
@Zakaria-ouertani ok this looks like your OS issue to me. show me your system specs

**Comment by Zakaria-ouertani** [comment]
> @Zakaria-ouertani ok this looks like your OS issue to me

Ok i'll see what i can do and come back here when if i found what tye problem.
