### ISSUE TITLE
NVChad UI didn't display 

### ISSUE THREAD

**Issue by tensingnightco** [NvChad/NvChad#1776]
**Describe the bug**
When first opening neovim, The task bar disappeared
![image](https://user-images.githubusercontent.com/86961588/219320615-c02b3b1e-5cf6-4a0b-b4e7-fffb530d7e30.png)
Tried to solve the problem by typing `:PackerSync` 
![image](https://user-images.githubusercontent.com/86961588/219321255-dc278c3c-8eac-43c1-bccb-bf94ce89868d.png)
For some reasons, the nvim-tree plugin installation seemed to be failed, and the UI is back again 
![image](https://user-images.githubusercontent.com/86961588/219322515-563c7073-7c02-4b39-b9f8-cb23ebb10c76.png)
But nvim-tree still managed to display while the UI failed to display
![image](https://user-images.githubusercontent.com/86961588/219322768-b39a2df3-50af-45ef-bfd3-f4091b3015f5.png)
Then I was trying to type `:PackerSync` in the hope of making things happen again but this time nvchad didn't understand my command
![image](https://user-images.githubusercontent.com/86961588/219323318-2ba2cd0d-5e3d-4c86-b60a-ee15653b7396.png)

**Expected behavior**
Packer command should work 
The UI should display 

**Desktop (please complete the following information):**
 - Operating System: Linux Mint 21.1 "Vera" Cinnamon Edition
 - Terminal: GNOME Terminal
 - Version of Neovim: v0.9.0-dev-964+g1539f7136

**Comment by siduck** [comment]
@tensingnightco does this happen with neovim 0.8.3?

**Comment by siduck** [comment]
try doing a clean installation of nvchad too

**Comment by tensingnightco** [comment]
I tried, and it works, even on neovim pre-releases version. Thank you for helping

**Comment by siduck** [comment]
@tensingnightco its recommended to only use the stable release tho! use neovim 0.8.3
