### ISSUE TITLE
Use alpha-nvim at nvim start

### ISSUE THREAD

**Issue by Jay-boo** [NvChad/NvChad#1777]
**Describe the bug**
Hi , I'am a new with neovim, and i'am struggling with nvChad configuration:
I can't use alpha-nvim

**To Reproduce**
I doesn't change core directory and I added custom directory with chadrc.lua , init.lua and mapping.lua and a plugins sub directory. In custom/plugins/init.lua i just add this 
```
local plugins={
  ["goolord/alpha-nvim"] = {
    disable=false,
    cmd="Alpha"


  },



}

```
I can use :Alpha command and it work perfectly.

**Expected behavior**
But i 'd like to get this dashboard when starting vim with nvim bash command

**Screenshots**
![image](https://user-images.githubusercontent.com/81867817/219717657-c916434b-ab12-4a8e-b095-484e9748214a.png)

:Alpha command working perfectling after vim start

**Desktop (please complete the following information):**
 - Operating System : WIndows 11 using WSL2 with Debian distribution
 - Terminal : Tabby
 - Version of Neovim: 8.0

**Additional context**

**Comment by siduck** [comment]
remove cmd line , open nvim do packersync
