### ISSUE TITLE
treesitter/highlighter: Error executing lua:

### ISSUE THREAD

**Issue by tgh12** [NvChad/NvChad#1780]
**Describe the bug**
I am install NVchad on my mac successfully, but when i am open the init.lua i found this error 
vim.cmd "packadd packer.nvim" treesitter/highlighter: Error executing lua:

**To Reproduce**
I try to Update the "nvim-treesitter" plugin but still same issue
**Expected behavior**
still having trouble after trying  update the plugin
**Screenshots**
<img width="1273" alt="Error" src="https://user-images.githubusercontent.com/6009328/219832936-236e0cae-cff2-433b-a9d5-2896350a6c56.png">

**Desktop (please complete the following information):**
 - Mac osx Big Sur
 - Terminal: ITerminal 2
 - Version of Neovim  v0.8.3
**Additional context**
I dont want to Disable the "nvim-treesitter" plugin

**Comment by siduck** [comment]
@tgh12  rm -rf .local/share/nvim and reopen neovim

**Comment by tgh12** [comment]
@siduck thank you for replay 
I run the comm and rm -rf .local/share/nvim and reopen neovim
the Neovim open but when i open init.lus file still have same error !!

**Comment by siduck** [comment]
@tgh12 can u do a clean nvchad installation? also show nvim -v output

**Comment by tgh12** [comment]
I wii try thanks

**Comment by tgh12** [comment]
@siduck i remove the previous installation and start from the very beginning 
the problem now with the Neovim i install it but the config folder is hidden 
sothat i can not reach to init.lua file

**Comment by siduck** [comment]
> @siduck i remove the previous installation and start from the very beginning the problem now with the Neovim i install it but the config folder is hidden sothat i can not reach to init.lua file

rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim

**Comment by Milano25** [comment]
Who are you and what are you talking about??

**Comment by tgh12** [comment]
@Milano25  I am new programmer try to install and use Nvchad correctly as python text editor

**Comment by siduck** [comment]
@tgh12 do a  clean nvchad installation ( delete old nvim dirs )
