### ISSUE TITLE
Packer does not seem to work after a fresh install or from the Docker container

### ISSUE THREAD

**Issue by jcmorrow** [NvChad/NvChad#1781]
Hey! This seems like a cool project! I have used vim for years, but recently have found myself using VSCode more and more, just for small quality of life things which take a lot of configuring in vim. I find this project really promising in that dimension, it feels like this puts VSCode levels of productivity within reach with vim which is really cool! Thanks for all of your work on it, if there is anything I can do to help debug what I'm about to report, please let me know!

**Describe the bug**

`:PackerCompile` and `:PackerSync` do not work from the docker image or from a fresh installation, I get the following error:

```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:91: Vim:E492: Not an editor command: PackerSync           
Please check your config for correctness                                                                                                        
Press ENTER or type command to continue   
```
I noticed this happening with my fresh install, so I tried it on the docker image to see if there was something I was missing, but `Packer` commands don't seem to work in either environment for me. On my fresh install I can run `:PackerSync` *once*, but if I run it a second time I get:

```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:91: Vim:E492: Not an editor command: PackerSync           
Please check your config for correctness                                                                                                        
Press ENTER or type command to continue   
```

**To Reproduce**
1. Use the website's recommended command:
```
  docker run -w /root -it --rm alpine:edge sh -uelic '
    apk add git nodejs neovim ripgrep alpine-sdk --update
    git clone https://github.com/NvChad/NvChad ~/.config/nvim
    nvim
    '
```
2. Notice the error message after `:Mason` runs on startup: 
![CleanShot 2023-02-18 at 17 42 42@2x](https://user-images.githubusercontent.com/5903784/219907608-2ad17ba8-4752-4e7c-98cc-33a3adf88ea3.png)
3. Run `:PackerSync`
4. Get an error message:
<img width="1427" alt="CleanShot 2023-02-18 at 17 43 37@2x" src="https://user-images.githubusercontent.com/5903784/219907623-b601da10-515e-4303-905c-7e516e348fa9.png">

**Expected behavior**
A fresh install and/or the docker container work.

**Desktop (please complete the following information):**
 - Mac OSX 12.0.1 (Monterey)
 - kitty
 - NVIM v0.8.1 (LuaJIT 2.1.0-beta3)

**Comment by siduck** [comment]
dont run packer commands if you have done packersync or packer compile before

**Comment by siduck** [comment]
@jcmorrow v2.0 will use lazy.nvim so no packer issues anymore!!

```bash
 docker run -w /root -it --rm alpine:edge sh -uelic '
    apk add git nodejs neovim ripgrep alpine-sdk --update
    git clone https://github.com/NvChad/NvChad ~/.config/nvim -b v2.0
    nvim
    '
 ```

**Comment by jcmorrow** [comment]
>  dont run packer commands if you have done packersync or packer compile before

But... those commands don't work. That's what I'm reporting.

If V2.0 will fix it I guess it's maybe not worth the effort, but then it would probably be wise to make sure that people coming to the project start on 2.0. It's very unclear from the website that 1.0 is no longer supported.

**Comment by jcmorrow** [comment]
Also, I think you need to add `npm` to get installed into that container:

```
 docker run -w /root -it --rm alpine:edge sh -uelic '
    apk add git nodejs npm neovim ripgrep alpine-sdk --update
    git clone https://github.com/NvChad/NvChad ~/.config/nvim -b v2.0
    nvim
    '
```

Otherwise I get `npm is not executable` errors when using it.

**Comment by siduck** [comment]
i have to update the command, npm/nodejs were required in old nvchad. now they're not

**Comment by jcmorrow** [comment]
Also - v2.0 works great, I didn't even have to do lsp config, just installed what I wanted with `Mason` and it worked. Pretty awesome!

**Comment by jcmorrow** [comment]
> i have to update the command, npm/nodejs were required in old nvchad. now they're not

I dunno, when I fired up the command you posted it looked like `Mason` was trying to `npm install` things, which was failing (I did not look too closely). If that's the case, seems like maybe it's still needed?

**Comment by siduck** [comment]
@jcmorrow if you use any mason binary that needs npm to install then its needed

**Comment by siduck** [comment]
also try https://github.com/NvChad/example_config/tree/v2.0 for a starting point

**Comment by Milano25** [comment]
As long you don't report the same report and ask the same questions you
understood.
Good luck
