### ISSUE TITLE
Cpecials symbols crash

### ISSUE THREAD

**Issue by simafrus** [NvChad/NvChad#1782]
I`ve install nvchad and when i opened it i saw this arabian interface. I try to install jetbrains mono font, like similar issue recommends, but it didnt help

![image](https://user-images.githubusercontent.com/107239964/219933303-e873f79a-8d2f-458f-8ff9-5e8e45bb80b1.png)

**Comment by siduck** [comment]
install the nerd font version and set it in your terminal as default font
