### ISSUE TITLE
Autocompletion Where are U

### ISSUE THREAD

**Issue by Jay-boo** [NvChad/NvChad#1786]
**Describe the bug**
Hi, I can't have autocompletion for  other language server than lua. 

**To Reproduce**
 Clone latest commit of this repo
:PackerSync
:Mason Install lua-language-server pyright

**Expected behavior**
I'd like to have real autocompletion not snippet for python.

Lua autocompletion works but not python 's one:
Lua autocompletion works : 
![image](https://user-images.githubusercontent.com/81867817/220177315-268953d3-9575-4493-82d1-a72a463aedb7.png)

![image](https://user-images.githubusercontent.com/81867817/220176969-f503443e-cddc-47e8-9819-15c5b8801e5c.png)

Python autocompletion:
![image](https://user-images.githubusercontent.com/81867817/220177057-492cb4e7-f60c-4a26-8171-0bdde0154e6f.png)
Using LspInfo in the .py file 
![image](https://user-images.githubusercontent.com/81867817/220177164-cd95777e-4b94-44bc-9179-09dfdda67893.png)

**Desktop (please complete the following information):**
 - Operating System : WSL 2 Debian
 - Terminal : Tabby
 - Version of Neovim : 8.0

**Additional context**

**Comment by siduck** [comment]
Hi @Jay-boo you need to setup custom lspconfig for the lsp servers you want. Pls check the lsp section in our docs.
