### ISSUE TITLE
:Cheatsheet is not a command

### ISSUE THREAD

**Issue by samuelnihoul** [NvChad/NvChad#1791]
On NVChad.netlify.app, Cheatsheet.nvim is listed as a feature. However :Cheatsheet is not recognized as an editor command. After installation with packer from plugins/init.lua, :Cheatsheet gives a Telescope error.

![image](https://user-images.githubusercontent.com/69475809/220623589-1b4cc572-ffcd-4e94-bdb2-425f0bc1c1b5.png)

**Comment by samuelnihoul** [comment]
This problem should reproduce on a clean nvchad/nvchad install.

**Comment by siduck** [comment]
cheethsheet.nvim was added before but got removed too. I did update the docs. can you show where you saw it?

**Comment by siduck** [comment]
also @samuelnihoul for now just do leader tk  ( leader is space in nvchad ) . From v2.0 we have our own cheatsheet
