### ISSUE TITLE
Install problem on Mac M2

### ISSUE THREAD

**Issue by COil** [NvChad/NvChad#1792]
**Describe the bug**

Error after initial installation when opening nvim. 
I don't see the tree browser either.

**To Reproduce**

I have just done the git checkout, after running nvim I have these kinds of errors : 

<img width="992" alt="Capture d’écran 2023-02-22 à 19 45 05" src="https://user-images.githubusercontent.com/177844/220728242-198e6bd2-6652-4469-87ec-5536fc4600b3.png">

**Expected behavior**
no warning.

**Desktop (please complete the following information):**
 - Operating System : macOS Ventura 13.2.1 
 - Terminal : fishshell
 - Version of Neovim : 0.8.3

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilé par brew@Ventura-arm64.local
Features: +acl +iconv +tui
See ":help feature-compile"
         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim
```

**Additional context**

**Comment by siduck** [comment]
:TSUpdate , try that command. Also did you did a clean nvchad installation?

**Comment by COil** [comment]
I tried with docker, I have an error with `lua-language-server` and arm64:

<img width="960" alt="Capture d’écran 2023-02-27 à 19 56 18" src="https://user-images.githubusercontent.com/177844/221656882-e0494115-0a9f-4730-8812-7e65508fdc29.png">

Same result when running Docker with the `--platform linux/amd64`option.

**Comment by siduck** [comment]
> can confirm, Operating System : newest macos Terminal : wezterm Version of Neovim : newest release
> 
> most likely a treesitter issue because this happens on my other config before I did a fresh install of nvchad

is gcc installed?

**Comment by snowy-shadow** [comment]
Macos come preinstalled with clang. 
Only started having this issue when updating to nvim V8 so I am suspecting its a treesitter issue

**Comment by COil** [comment]
> @COil that isnt a nvchad issue, composer isnt installed globally in your system :/

No, it was when using the Docker image, so I suppose the composer error is "normal".

**Comment by siduck** [comment]
> > @COil that isnt a nvchad issue, composer isnt installed globally in your system :/
> 
> No, it was when using the Docker image, so I suppose the composer error is "normal".

oh cool then, I dont have any idea about docker

**Comment by siduck** [comment]
> Macos come preinstalled with clang. Only started having this issue when updating to nvim V8 so I am suspecting its a treesitter issue

does gcc work on m1?

**Comment by COil** [comment]
```
gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by siduck** [comment]
> ```
> gcc --version
> Apple clang version 14.0.0 (clang-1400.0.29.202)
> Target: arm64-apple-darwin22.3.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> ```

rm -rf ~/.local/share/nvim and reinstall nvchad

**Comment by COil** [comment]
I'll do another try when I have more time, thanks.

**Comment by Tarmstrong95** [comment]
Closed but want to confirm this solved my issue

> > ```
> > gcc --version
> > Apple clang version 14.0.0 (clang-1400.0.29.202)
> > Target: arm64-apple-darwin22.3.0
> > Thread model: posix
> > InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> > ```
> 
> rm -rf ~/.local/share/nvim and reinstall nvchad

**Comment by COil** [comment]
OK thanks for the comment.
