### ISSUE TITLE
How to install custom plugins in the branch v2.0

### ISSUE THREAD

**Issue by ayush-india** [NvChad/NvChad#1794]
**Describe the bug**
I am unable to install a plugin in the branch v2.0 

**To Reproduce**
Just add a plugin to lua/cutsom/plugins/init.lua file 

**Expected behavior**
Install that plugin

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System lubuntu 20.04
 - Terminal qterminal 
 - Version of Neovim NVIM v0.9.0-dev-661+ga37c686d2

**Additional context**

**Comment by ayush-india** [comment]
![screen01](https://user-images.githubusercontent.com/99461867/221802719-1a23f62c-e5b3-488e-9444-de64cda969be.png)

**Comment by siduck** [comment]
@ayush-india  it uses lazy.nvim syntax , check example_config repo of ours ( v2.0 branch )
