### ISSUE TITLE
v2.0: strange indentation behaviour in plaintext files

### ISSUE THREAD

**Issue by dudoug** [NvChad/NvChad#1805]
**Describe the bug**

Indentation seems to jump around when editing files without an active treesitter config.

**To Reproduce**

* Open this text file:
  ```
  abc
    def
    ghi
  
  jkl
    mno
  pqr 
  ```
* Position the cursor at the end of `def`, `ghi` or `mno`
* Press return
* Notice how the previous line sometimes gets un-indented

**Expected behavior**

Previous line stays as-is

**Screenshots**

n/a

**Desktop (please complete the following information):**

 - Operating System: Fedora 37
 - Terminal: GNOME Terminal, but also happens in Neovide
 - Version of Neovim: 0.8.3

**Additional context**

n/a

**Comment by siduck** [comment]
so not really an issue as you failed to provide any evidences. Also there were no changes done in v2.0 related to indenting. Probably your custom config has some changes.

**Comment by doubleChu** [comment]
> so not really an issue as you failed to provide any evidences. Also there were no changes done in v2.0 related to indenting. Probably your custom config has some changes.

Hmm I didn't open this issue, maybe you should mention @dudoug.

**Comment by siduck** [comment]
> > so not really an issue as you failed to provide any evidences. Also there were no changes done in v2.0 related to indenting. Probably your custom config has some changes.
> 
> Hmm I didn't open this issue, maybe you should mention @dudoug.

thx for correcting, done!
