### ISSUE TITLE
Recent Files Not Working

### ISSUE THREAD

**Issue by LSleutsky** [NvChad/NvChad#1806]
**Describe the bug**
When working in my workspace that I always work in, all of a sudden with the latest update I did of NVChad, the `Telescope oldfiles` functionality is not working. It only ever shows the files that are in the `~/.config/nvim/lua` folder (_and doesn't even include the `custom` folder_).

I did not change any config options or do anything else other than running `<leader>uu` inside of NVChad (_while on my machines root `~` directory, if that matters to anyone_)

**To Reproduce**
1. Open NVChad in a directory that has files in it.
2. Open some of those files, make edits or don't, doesn't really matter.
3. Close out of NVChad.
4. Go back into NVChad, and either from the `Alpha` page, or by entering the command `Telscope oldfiles`, notice that the recently opened files do not show in the list.

**Expected behavior**
That the recently opened files I was working in show up in the recently opened files list.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - MacOS Ventura 13.2.1
 - iTerm2 Nightly Build 3.5.20230308-nightly
 - NVIM v0.9.0-dev-1178+g46d4d420e-dirty

**Additional context**
I've tried in other terminals (_kitty, alacritty_), as well as on a stable version of Neovim, but the results are the same. This used to work great, and I'm not sure if it's the specific latest update that caused this or not, but I'm not really sure how to get around it. It's like the working directory is hard-coded to the `~/.config/nvim/lua` path... 🤷🏻

**Comment by siduck** [comment]
hi @LSleutsky i tried to follow your steps but it works for me here

**Comment by siduck** [comment]
https://0x0.st/Hic2.mp4

nvchad doesnt mess with shada file or configure telescope's oldfiles functionality, so this doesnt have anything to do with nvchad I think

**Comment by LSleutsky** [comment]
> https://0x0.st/Hic2.mp4
> 
> nvchad doesnt mess with shada file or configure telescope's oldfiles functionality, so this doesnt have anything to do with nvchad I think

Right so, you seem to be checking files in the main `.config` folder that `nvim` lives in, and those are the only files that show up in the `Oldfiles` panel for me. The issue is with recent files when working in other folders outside of `~/.config`.

If that too works for you, then I don't know if this is an issue with the Silicon MacBooks, as I am now using it on an M2 MacBook Pro.

I dono....

**Comment by siduck** [comment]
@LSleutsky at the end in the video you can see that im able to view recent files from `~/solidjs dir`
