### ISSUE TITLE
there is a tip 'nothing in register' when I press p to paste something

### ISSUE THREAD

**Issue by U-DI-Page** [NvChad/NvChad#1807]
**Describe the bug**
why I can't use y and p to copy and paste, It doesn't work and show the tip 'nothing in register'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
do you have xclip/wl-clipboard installed ( LINUX )

**Comment by siduck** [comment]
show a video

**Comment by U-DI-Page** [comment]
https://user-images.githubusercontent.com/14305674/224222371-c3e0f4c3-730e-4604-9374-3351dfb373af.mp4

@siduck

**Comment by siduck** [comment]
@U-DI-Page i cant seem to produce this issue :/ 

do 

nvim -u NONE

**Comment by U-DI-Page** [comment]
no，vanilla nvim is ok @siduck

**Comment by siduck** [comment]
i cant think of any reason why this shouldnt work man, only clipboard related thing we do in nvchad is this 

![image](https://user-images.githubusercontent.com/59060246/224226206-8d7f26b4-5405-4087-9184-0174e33a332d.png)

(core/options.lua)

**Comment by siduck** [comment]
does the copy option from right click menu work?

**Comment by U-DI-Page** [comment]
@siduck The right click menu also didn't work, but if I delete the option `opt.clipboard = "unnamedplus"`,'y&p' is ok,right click menu still no work.

**Comment by siduck** [comment]
> @siduck The right click menu also didn't work, but if I delete the option `opt.clipboard = "unnamedplus"`,'y&p' is ok,right click menu still no work.

are you  using linux?

**Comment by U-DI-Page** [comment]
@siduck yes

**Comment by U-DI-Page** [comment]
@siduck ok,it's the problem, I didn't install xclip, now the problem is solved, thanks for your help, have a good day!
