### ISSUE TITLE
Breaking Changes ( v1.0 to v2.0 )

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#1809]
- Take your own time in migrating to v2.0,  v2.0 release is in a separate branch so technically you can still use old nvchad :grinning: 

## Lazy.nvim replaces packer.nvim 

- So the `M.plugins` variable in chadrc expects a string now.
 
```lua
--  before 
M.plugins = require "custom.plugins"

--  now
M.plugins = "custom.plugins"
```

- Also old plugin syntax has some slight changes now ( as per lazy.nvim's syntax ) 

 
```lua
-- before
["some plugin" ] = { options } 
 
-- now
{
  "some plugin",
   options
}
```
check https://github.com/folke/lazy.nvim#examples for examples

- `overriden_opts` is now `opts`

## NvChad ui options

- These options can now be directly changed from chadrc file 

```lua
-- before 
["NvChad/ui"] = {
     override_opts = {
         statusline = {
             separator_style  = "round" 
          }
     }
}

-- now 
M.ui = {
    statusline = {
         separator_style = "round"
     }
}
```

## Alpha-nvim is replaced 

- Its replaced by our own dashboard module which has an easier config 
-  https://github.com/NvChad/NvChad/blob/v2.0/lua/core/default_config.lua#L50

**Comment by zane-monster** [comment]
I found the ture Url.
https://nvchad.com/news/v2.0_migration

**Comment by philipp-zettl** [comment]
> v2.0 release is in a separate branch so technically you can still use old nvchad 

Seems like the current installation using
```shell
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
```
is unexpected behavior. Since `v2` was promoted to default branch, above mentioned command defaults to new `v2` branch, not `<v2` within the `main` branch.

This broke an installation script that imports my custom config.
Maybe someone else ends up in the same position as me, therefore a simple
```shell
git clone -b main https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
```
would do the trick
