### ISSUE TITLE
Lua lsp not working after changing custom/configs/lspconfig.lua

### ISSUE THREAD

**Issue by ayush-india** [NvChad/NvChad#1810]
**Describe the bug**
I just updated from main to v2.0 and saw that i do not need to configure lua_lsp because the its done in the plugins folder. So i removed the for loop which configures all the lsp's (i only use 3). But then suddeny lua lsp didn't worked with some error.
[my config](https://github.com/ayush-india/nvim) **use the main branch**

**To Reproduce**
Just clone my config and try to edit a lua file. (It could be that their is some cache issues idk)

**Expected behavior**
Give me completion as usual.

**Screenshots**
![nuts](https://user-images.githubusercontent.com/99461867/224536210-3c1a68dc-42f6-445d-9196-4cbd2c83bdba.png)

**Desktop (please complete the following information):**
 - Operating System Lubuntu(20.04) a flavour of ubuntu
 - Terminal qterminal
 - Version of Neovim NVIM v0.9.0-dev-661+ga37c686d2
Thanks for making such a great config

**Comment by siduck** [comment]
hi @ayush-india , show your custom plugins table. Did you forget to rename plugin paths?

**Comment by ayush-india** [comment]
@siduck  HI, 
Idk what are you asking i think you can find it in my config

**Comment by siduck** [comment]
You're not supposed to use main branch, you're meant to use custom config.

Reinstall nvchad  and press y when it asks for Chadrc starter, reopen nvim and Lua lsp should be working.
