### ISSUE TITLE
Help with custom mappings - different mapping based on filetype

### ISSUE THREAD

**Issue by MineRock** [NvChad/NvChad#1811]
Hello, I really liked this project and am using it as my default config right now. I wanted to make a Compile-and-Run key mapping so it becomes easier for me to code and I made this to detect filetype in custom/mappings.lua
```
local function filetype()
  if vim.cmd("echo &filetype") == "rust"
  then
    return {"<cmd> term rustc % && %:r <CR>", "run rust program"}
  else
    return {"<cmd> lua echo vim.bo.filetype<CR>", vim.cmd("echo &filetype")}
  end
end
```
In M.general, I've set the mapping as follows, 
```
["<leader><F10>"] = filetype(),
```
But the mapping doesn't work. I changed the else command to the above to see what it was returning and it just returned a blank value. I perhaps need the mapping to load after the filetype has loaded in, but I have no clue how I could do that. Could you help me or direct me to some resources? Thanks!

Edit: I am on v2.0 branch right now.

**Comment by ayush-india** [comment]
Try to follow the mapping guide lines (how to make custom mappings)

**Comment by siduck** [comment]
```lua

M.blabla = {

  n = {

    ["<leader>cc"] = {
      function()
        if vim.bo.ft == "rust" then
          vim.cmd "term rustc % && %:r"
        else
          vim.notify(vim.bo.ft)
        end
      end,

      vim.bo.ft == "rust" and "run rust program" or vim.bo.ft,
    },
  },
}
```

**Comment by igordertigor** [comment]
I have a similar issue, but @siduck's solution doesn't quite work. Unfortunately, the custom mappings guide is relatively silent about this as well. I have a bunch of shortcuts for unicode characters, that I want to activate when typing markdown, but not elsewhere (ideally, I would even want them turned off when I'm in a markdown code block). As a consequence, I can't call a function when hitting the respective key, but I just don't want the key to be mapped at all. I would expect that this would somehow need to modifiy the `M` table, but I can't quite figure out how. Here is what I have:
```lua
M.markdown = {
  i = {
    ["->"] = {"→", "right arrow", opts = {nowait = true}},
    ["~>"] = {"⇝", "leads to arrow", opts = {nowait = true}},
    ["=>"] = {"⇒", "implies arrow", opts = {nowait = true}},
  }
}
```
Shortened a bit, but you get the point. The mappings work, but they work for all files.

In vimscript, I would accomplish something this using `autocmd FileType md ...`. How would I do that in lua and in a way to have it picked up by nvchad?

**Comment by siduck** [comment]
what does even "→" do? @igordertigor

**Comment by igordertigor** [comment]
@siduck , keep in mind that this is insert mode. So → just enters the respective unicode character.

**Comment by siduck** [comment]
@igordertigor 

```lua
local autocmd = vim.api.nvim_create_autocmd

autocmd("FileType", {
  callback = function()
    if vim.bo.ft == "markdown" then
      vim.keymap.set("i", "->", "→", { nowait = true })
      vim.keymap.set("i", "~>", "⇝", { nowait = true })
      vim.keymap.set("i", "=>", "⇒", { nowait = true })
    else
      vim.keymap.set("i", "->", "", { nowait = true })
      vim.keymap.set("i", "~>", "", { nowait = true })
      vim.keymap.set("i", "=>", "", { nowait = true })
    end
  end,
})
``` 

 something like this

**Comment by igordertigor** [comment]
Oh, cool. and you have that in `mappings.lua` or elsewhere? Looks more like `init.lua` to me.

**Comment by siduck** [comment]
@igordertigor custom init.lua. your usecase is  a bit complex so just using vim.keymap.set will do

**Comment by igordertigor** [comment]
Thank you.

**Comment by igordertigor** [comment]
Ok, @siduk, that kind of works, with one exception: If I open a non-markdown file, the key maps aren't unset, but they are set to "", so typing `->` will now be expanded to nothing at all.

**Comment by siduck** [comment]
> Ok, @siduk, that kind of works, with one exception: If I open a non-markdown file, the key maps aren't unset, but they are set to "", so typing `->` will now be expanded to nothing at all.

the code i gave was just an example, adjust that else statement's logic so it'd unmap those keys, i dont have much idea about it!

**Comment by igordertigor** [comment]
I don't know much about nvim's lua configuration (hence the question) and felt that you did. There doesn't seem to be an unmap function there (expected `vim.keymap.unset("i", "->")` or something along those lines).  I appreciate your input on this. It turns out, it's `vim.keymap.del("i", "->")`.

**Comment by BrunoKrugel** [comment]
> @igordertigor
> 
> ```lua
> local autocmd = vim.api.nvim_create_autocmd
> 
> autocmd("FileType", {
>   callback = function()
>     if vim.bo.ft == "markdown" then
>       vim.keymap.set("i", "->", "→", { nowait = true })
>       vim.keymap.set("i", "~>", "⇝", { nowait = true })
>       vim.keymap.set("i", "=>", "⇒", { nowait = true })
>     else
>       vim.keymap.set("i", "->", "", { nowait = true })
>       vim.keymap.set("i", "~>", "", { nowait = true })
>       vim.keymap.set("i", "=>", "", { nowait = true })
>     end
>   end,
> })
> ```
> 
> something like this

but in this way we wont have the keybinds listed in nvcheatsheet
