### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by Wuelle** [NvChad/NvChad#1814]
**Describe the bug**
The top-links in the [`README.md`](https://github.com/NvChad/NvChad#readme) link to [nvchad.github.io](https://nvchad.github.io) which is a dead link, it should instead be [nvchad.com](https://nvchad.com).

![image](https://user-images.githubusercontent.com/58120269/224721271-5bfd692b-5f49-4d44-9f44-e9e477bae292.png)

**To Reproduce**
Click one of the links above and notice the `404 not found`
![image](https://user-images.githubusercontent.com/58120269/224721832-06213369-f2e1-468a-8c49-14d74bdb46c1.png)

**Expected behavior**
Expected the links to take me to [nvchad.com](https://nvchad.com).

**Comment by siduck** [comment]
hi @Wuelle , thanks for correcting. I forgot to update them. Done now https://github.com/NvChad/NvChad/commit/11f30badfaf0e8861926aee8bf9ee7b0785f469c
