### ISSUE TITLE
Default config results in error

### ISSUE THREAD

**Issue by Focus172** [NvChad/NvChad#1817]
**Describe the bug**
Upon running the clear old cached nvim plugins and running the default install command for the first time, plugins fail to load with stack trace. 

**To Reproduce**
1. Delete old nvim config in ~/.config/nvim and ~/.cache/nvim
2. Run install command `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
3. See error

**Expected behavior**
NvChad launches without breaking.

**Screenshots**
![Install](https://user-images.githubusercontent.com/94580748/224893955-f451bbb5-7329-4639-bacb-e1109c325e43.png)
![Error](https://user-images.githubusercontent.com/94580748/224893871-cc65a9c7-5d3b-4f97-a1c6-52aae859ece3.png)

**Desktop:**
 - Artix Linux 6.2.2
 - Allacritty 0.11.0
 - Neovim 0.8.3

**Additional context**
I was able to fix this problem to minimal success by editing the code in this way. It allows nvim to boot as expect but many key bindings are missing.
![fix?](https://user-images.githubusercontent.com/94580748/224894024-a4b1e4ae-807c-476d-89b7-57f0689464e2.png)

**Comment by siduck** [comment]
rm -rf ~/.local/share/nvim
