### ISSUE TITLE
mason override doesn't work

### ISSUE THREAD

**Issue by aiPenguin** [NvChad/NvChad#1818]
**Describe the bug**

I installed NvChad with template. But the mason override settings in the /custom/overrides.lua didn't work. There was still only Lua-language-server installed. 

And when I ran `<leader>fm` in a lua file, I got an error. 
> [null-ls] failed to run generator: ....local/share/nvim/lazy/null-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)

**To Reproduce**

Error 1:
1. Install NvCahd with command `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
2. Reopen nvim
3. Run ':MasonInstallAll'

Error 2:
1. Open overrides.lua with nvim
2. Run `<leader>fm`
3. See error

**Expected behavior**

The other language servers and linters mentioned in overrides.lua in template should be installed.

The formatter for lua files should work.

**Screenshots**
<img width="789" alt="CleanShot 2023-03-14 at 12 38 47@2x" src="https://user-images.githubusercontent.com/46262493/224989787-694c4982-b36a-4be8-a152-fd8d4ed3204c.png">

<img width="548" alt="CleanShot 2023-03-14 at 12 39 27@2x" src="https://user-images.githubusercontent.com/46262493/224989985-b11d578a-886d-465f-8e3c-822a082ae6fc.png">

<img width="830" alt="CleanShot 2023-03-14 at 12 40 51@2x" src="https://user-images.githubusercontent.com/46262493/224990393-8f473fa0-7e7e-414a-9a39-b7bf02519556.png">

<img width="522" alt="CleanShot 2023-03-14 at 12 41 37@2x" src="https://user-images.githubusercontent.com/46262493/224990468-712a3748-678c-4395-9ed2-459f3f56b992.png">

**Desktop (please complete the following information):**
 - Operating System MacOS
 - Terminal iterm2
 - Version of Neovim v0.8.3

**Additional context**

**Comment by siduck** [comment]
hi @aiPenguin , show your custom plugins file
