### ISSUE TITLE
Can't install v2.0

### ISSUE THREAD

**Issue by joaosamouco** [NvChad/NvChad#1819]
**Describe the bug**
After following the installation instructions, I'm not able to properly start nvim.

```sh
Error detected while processing /home/joaosamouco/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/joaosamouco/.config/nvim/lua/core/utils.lua:79: attempt to i
ndex a nil value
stack traceback:
        /home/joaosamouco/.config/nvim/lua/core/utils.lua:79: in function 'load_mappings'
        /home/joaosamouco/.config/nvim/lua/plugins/init.lua:29: in main chunk
        [C]: in function 'require'
        /home/joaosamouco/.config/nvim/init.lua:20: in main chunk
Press ENTER or type command to continue
```

**To Reproduce**
1. Backup `~/.config/nvim`
2. `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1`
3. `nvim`

**Expected behavior**
Should be able to run nvim with NvChad.

**Desktop (please complete the following information):**
 - Arch Linux
 - Allacrity
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

**Comment by siduck** [comment]
rm -rf .local/share/nvim
