### ISSUE TITLE
error at line 79 in utils.lua

### ISSUE THREAD

**Issue by MiftikCZ** [NvChad/NvChad#1820]
**Describe the bug**
all needed is in the screenshot 

**To Reproduce**
1. just use the install link for linux, then open nvim

**Expected behavior**
to make it work

**Screenshots**
![Snímek obrazovky_2023-03-14_13-37-11](https://user-images.githubusercontent.com/89579269/225003365-fd3819c8-4aef-4294-9dab-bf5cc7ee140b.png)

**Desktop (please complete the following information):**
 - endevaours os with linux 6.2.5-arch1-1
 - alacritty
 - 0.8.0.r1472.g4b9bb3a184-1

**Additional context**

**Comment by siduck** [comment]
rm -rf .local/share/nvim
