### ISSUE TITLE
formatter Php - not working 

### ISSUE THREAD

**Issue by Andreius-14** [NvChad/NvChad#1822]
**Describe the bug**
i have a problem  i want to formatting code but not working
i've installed php-cs-fixer using mason

**Expected behavior**
i hope the code was formattered to have an  ordered code similar to prettier

**Screenshots**
my file null-ls.lua 
![image](https://user-images.githubusercontent.com/55065774/225153380-176e4d3a-e8c9-450f-b2e0-31f145d25602.png)
Extra: Linter phpcs work fine

when using shortcut i get this  [<leader> + fm]
![image](https://user-images.githubusercontent.com/55065774/225154076-e232ae04-99f8-4914-a2df-d15a9590abf4.png)

**Desktop **
 - Manjaro xfce 
 - kity
 - NVIM v0.8.3
 
Extra: Increible actualizacion por cierto , Espero puedan orientarme

**Comment by siduck** [comment]
hi @Andreius-14 make sure you enable php  lsp in your custom lspconfig

**Comment by Andreius-14** [comment]
hi @siduck this is the file lspconfig.lua . could you tell me if there is any mistake, [Se lo agradeceria]
![image](https://user-images.githubusercontent.com/55065774/225175274-1ff4b462-22d9-40ef-98ea-9472a3024a7a.png)

**Comment by siduck** [comment]
hi @Andreius-14 , open a php file and show me output of LspInfo command

**Comment by Andreius-14** [comment]
@siduck ,ok no problem here it is 
![image](https://user-images.githubusercontent.com/55065774/225176235-e3ee5646-d823-4abf-af52-b504d2e9b311.png)
![image](https://user-images.githubusercontent.com/55065774/225176543-d306b6dc-a9ca-4308-a1a8-01fb8f50bc15.png)
is referring to that right?

**Comment by siduck** [comment]
@Andreius-14  I mean run LspInfo command  
![image](https://user-images.githubusercontent.com/59060246/225177561-48cbdb8e-94a6-4755-8159-fe347436bd3b.png)

**Comment by Andreius-14** [comment]
ok @siduck  here it is 
![image](https://user-images.githubusercontent.com/55065774/225177879-471ca121-6831-4855-b94f-91fa57944e0d.png)

**Comment by siduck** [comment]
intelephsense isnt attached to the buffer @Andreius-14  so the formatting in null-ls doesnt work

**Comment by Andreius-14** [comment]
How would I fix this, I thought I just added this line @siduck . [lamento la molestia]
![image](https://user-images.githubusercontent.com/55065774/225179014-517d7140-2483-4183-a2ba-ae0945e789e1.png)

**Comment by siduck** [comment]
@Andreius-14  ask help on our discord/telegram/matrix server. I dont use php so cant help much.

**Comment by Andreius-14** [comment]
ok @siduck thanks for the help
