### ISSUE TITLE
I think what is commented here should be custom.plugins.lspconfig

### ISSUE THREAD

**Issue by aoeivux** [NvChad/NvChad#1826]
I don't know if it's appropriate to raise an issure here

<img width="1440" alt="Lspconfig" src="https://user-images.githubusercontent.com/74446305/225485324-b3540c14-4388-4978-b470-1068b8c20e9a.png">

**Comment by siduck** [comment]
hi @aoeivux , as we're using "custom.plugins" meaning custom/plugins.lua only for storing custom plugins table. We cant use the word plugins again as our plugin configs dir name 

Thats cuz lazy.nvim will try to source everything in that dir as plugin tables which we dont want 

![image](https://user-images.githubusercontent.com/59060246/225491702-6d14e461-a564-4bd4-b974-b49931b8a305.png)
