### ISSUE TITLE
error when opening nvim

### ISSUE THREAD

**Issue by ryannewcomer** [NvChad/NvChad#1830]
**Describe the bug**
when i open nvim, there are some error about your lua file

**To Reproduce**
1. nvim
2. see erro

**Expected behavior**
i expected i can open nvim

**Screenshots**
![Screenshot_20230316_210907](https://user-images.githubusercontent.com/88273136/225753676-6fb0dc7d-864a-470c-925a-324e5f7ea939.png)

**Desktop (please complete the following information):**
 - Operating System: manjaro
 
![Screenshot_20230316_211211](https://user-images.githubusercontent.com/88273136/225753786-d6cca47e-59a1-4725-b3fa-1eb722504d15.png)

 - Terminal: konsole
 - Version of Neovim
 nvim v0.8.3

**Additional context**

**Comment by siduck** [comment]
rm -rf .local/share/nvim before installing (  its mentioned in the docs )
