### ISSUE TITLE
E867: (NFA) Unknown operator '\zh'

### ISSUE THREAD

**Issue by zgpio** [NvChad/NvChad#1832]
**Describe the bug**
```
E867: (NFA) Unknown operator '\zh'
E5113: Error while calling lua chunk: C:\Users\zhaoguopan\AppData\Local\nvim/lua/core/init.lua:77: Failed to set autocmd
stack traceback:
        [C]: in function 'nvim_create_autocmd'
        C:\Users\zhaoguopan\AppData\Local\nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        C:\Users\zhaoguopan\AppData\Local\nvim\init.lua:1: in main chunk
```
**To Reproduce**
1. Error reported immediately after restarting nvim after plug-in installation

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System  Windows  10
 - Terminal
 - Version of Neovim      ~~NVIM v0.9.0-dev-1045+ga601d0311~~  NVIM 0.8.3

**Additional context**

**Comment by siduck** [comment]
@zgpio use 0.8.3

**Comment by zgpio** [comment]
Okay, I thought the document had the minimum version requirements

**Comment by zgpio** [comment]
Oh, no, 0.8.3 can also be reproduced

**Comment by siduck** [comment]
@zgpio when does this happen? 

try this 

remove all nvim dirs first 

then reinstall nvchad

**Comment by zgpio** [comment]
After I installed the plugin, restarting NVIM turned into this

**Comment by zgpio** [comment]
this is my pattern table { "C:\\Users\\zhaoguopan\\AppData\\Local\\nvim\\lua\\custom\\chadrc.lua" },  it seems nvim_create_autocmd can not process this, if I set pattern to "*",  I can start nvim without error

**Comment by siduck** [comment]
> this is my pattern table { "C:\Users\zhaoguopan\AppData\Local\nvim\lua\custom\chadrc.lua" }, it seems nvim_create_autocmd can not process this, if I set pattern to "*", I can start nvim without error

share your custom config

**Comment by zgpio** [comment]
```      
        local M = {}
                M.ui = {
                  theme = "onedark",
               }
              return M
```

**Comment by zgpio** [comment]
https://github.com/neovim/neovim/issues/22698#issue-1628805890

**Comment by zgpio** [comment]
Consider repairing it？ patterns = vim.tbl_map(vim.fs.normalize, patterns)

**Comment by lucario387** [comment]
Yep do it @siduck 
Wrap the patterns like his suggestions

**Comment by Dianshii** [comment]
@lucario387 I manually sync my `core/init.lua` code like below, but the same ERROR still occur.

```lua
-- reload some chadrc options on-save
local sep = vim.loop.os_uname().sysname:find "windows" and "\\" or "/"

vim.api.nvim_create_autocmd("BufWritePost", {   -- line 77 here
  pattern = vim.fn.glob(
    vim.fs.normalize(vim.fn.stdpath("config") .. "/lua/custom/**/*.lua"),
    true,
    true,
    true
  ),
```
I feel like it's definitely something related to sys language since me and @zgpio are both chinese, and the "Unknown operator" '\zh' could mean chinese, but somehow in my case it's operator '\zf' ... I have no idea what zf is...
```
could not source "$VIM\sysinit.vim"
sourcing "C:\Users\zfydo\AppData\Local\nvim\init.lua"
                                                     Error detected while processing C:\Users\zfydo\AppData\Local\nvim\init.lua:
E867: (NFA) Unknown operator '\zf'
E5113: Error while calling lua chunk: C:\Users\zfydo\AppData\Local\nvim/lua/core/init.lua:77: Failed to set autocmd
stack traceback:
	[C]: in function 'nvim_create_autocmd'
	C:\Users\zfydo\AppData\Local\nvim/lua/core/init.lua:77: in main chunk
	[C]: in function 'require'
	C:\Users\zfydo\AppData\Local\nvim\init.lua:1: in main chunk
finished sourcing C:\Users\zfydo\AppData\Local\nvim\init.lua
```

**Comment by zgpio** [comment]
> @lucario387 

I mean
vim.fs.normalize(glob(...))

**Comment by lucario387** [comment]
> > @lucario387 
> 
> I mean
> vim.fs.normalize(glob(...))

@zgpio i just pushed anotehr pr with your version. Can you try it out?

**Comment by Dianshii** [comment]
@lucario387 It works now and I've been using it normally since that fix. Ty👍👍👍

**Comment by lucario387** [comment]
Great to hear that
