### ISSUE TITLE
Telescope.nvim plugin configuration using opts field and function() results in error

### ISSUE THREAD

**Issue by arunanshub** [NvChad/NvChad#1836]
## Describe the bug
 
I have encountered an issue while configuring Telescope.nvim. Specifically, I attempted to override the configuration by utilizing a `function()` in the `opts` field of plugins ([as documented here](https://nvchad.com/docs/config/plugins#Managing_custom_plugins)).

Within the function, I required the `"telescope.actions".close` function. The code block looks like this:

```lua
-- nvim/lua/custom/plugins.lua
{
  "nvim-telescope/telescope.nvim",
  opts = function()
    local actions = require "telescope.actions"
    return {
      defaults = {
        mappings = {
          i = { ["<esc>"] = actions.close },
        },
      },
    }
  end,
},
```

## To Reproduce

1. Open `~/.config/nvim/lua/custom/plugins.lua`
2. Add the following piece of code:

   ```lua
   local plugins = {
     {
       "nvim-telescope/telescope.nvim",
       opts = function()
         local actions = require "telescope.actions"
         return {
           defaults = {
             mappings = {
               i = { ["<esc>"] = actions.close },
             },
           },
         }
       end,
     },
   }

   return plugins
   ```

3. Save and exit Neovim
4. Open Neovim
5. In normal mode, execute `:Telescope keymaps`.

## Expected behavior

Based on the provided configuration code block, the expected behavior is that the Telescope.nvim plugin should be configured with the specified keybinding overrides for the insert mode, where pressing the `<Esc>` key should trigger the `telescope.actions.close` function.

## Screenshots

![bug-report-nvchad](https://user-images.githubusercontent.com/48434243/225954692-43dae92e-c272-480f-82ab-23880a248a45.png)

## Desktop (please complete the following information)

 - Operating System: **Manjaro Linux: Kernel Version 6.1.19**
 - Terminal: **Konsole**
 - Version of Neovim: **v0.8.3**

**Comment by siduck** [comment]
hi @arunanshub 

```lua
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      defaults = {
        mappings = {
          i = { ["<esc>"] = require("telescope.actions").close },
        },
      },
    },
  }
  ```
  This works, Also it will work even if you define the actions variable somewhere else, like above your table. Didnt know lazy.nvim supported upvalues! I'll definitely update our docs :)

**Comment by arunanshub** [comment]
But that means telescope will run at startup. Also, previous version of NvChad had no such issue and it was able to lazy load just fine. 😕

**Comment by siduck** [comment]
> But that means telescope will run at startup. Also, previous version of NvChad had no such issue and it was able to lazy load just fine. confused

it wont, i just checked!

**Comment by siduck** [comment]
oh wait it does, bruh wait

**Comment by siduck** [comment]
the plugin loaded doesnt show up in lazy profile but with --startuptime it does

**Comment by siduck** [comment]
```lua
  {
    "nvim-telescope/telescope.nvim",
    opts = function()
      local actions = require "telescope.actions"
      return {
        defaults = {
          mappings = {
            i = { ["<esc>"] = actions.close },
          },
        },
      }
    end,
  },
  ``` 
  
  @folke how do we have opts tables which contain upvalues?

**Comment by folke** [comment]
You're doing it wrong.

Opts are evaluated at plugin load time.

If opts is a table it'll get merged in the parent table.

If it's a function, then the second parameter to that function is the parent's resolved opts table.

You can make changes to that table. And return nothing.

Or you can return en entirely new table. If you return a new table, that will be used instead of merging and will as such fully override the parent's opts

**Comment by folke** [comment]
> hi @arunanshub 
> 
> ```lua
>   {
>     "nvim-telescope/telescope.nvim",
>     opts = {
>       defaults = {
>         mappings = {
>           i = { ["<esc>"] = require("telescope.actions").close },
>         },
>       },
>     },
>   }
>   ```
>   This works, Also it will work even if you define the actions variable somewhere else, like above your table. Didnt know lazy.nvim supported upvalues! I'll definitely update our docs :)

This will indeed automatically load the plugin when during spec loading

**Comment by arunanshub** [comment]
> You're doing it wrong.
> 
> Opts are evaluated at plugin load time.
> 
> If opts is a table it'll get merged in the parent table.
> 
> If it's a function, then the second parameter to that function is the parent's resolved opts table.
> 
> You can make changes to that table. And return nothing.
> 
> Or you can return en entirely new table. If you return a new table, that will be used instead of merging and will as such fully override the parent's opts

Here's a prototype:

```lua
{
  "nvim-telescope/telescope.nvim",
  opts = function(_, opts)
    opts = vim.tbl_deep_extend("force", opts, {
      defaults = {
        mappings = {
          i = { ["<esc>"] = require("telescope.actions").close },
        },
      },
    })
    return opts
  end,
}
```

**Comment by siduck** [comment]
> > You're doing it wrong.
> > Opts are evaluated at plugin load time.
> > If opts is a table it'll get merged in the parent table.
> > If it's a function, then the second parameter to that function is the parent's resolved opts table.
> > You can make changes to that table. And return nothing.
> > Or you can return en entirely new table. If you return a new table, that will be used instead of merging and will as such fully override the parent's opts
> 
> Here's a prototype:
> 
> ```lua
> {
>   "nvim-telescope/telescope.nvim",
>   opts = function(_, opts)
>     opts = vim.tbl_deep_extend("force", opts, {
>       defaults = {
>         mappings = {
>           i = { ["<esc>"] = require("telescope.actions").close },
>         },
>       },
>     })
>     return opts
>   end,
> }
> ```

cool this works, btw @folke is there any cleaner solution to this? :thinking:

**Comment by folke** [comment]
@siduck of course :)

```lua
{
  "nvim-telescope/telescope.nvim",
  opts = {
    defaults = {
      mappings = {
        i = {
          ["<esc>"] = function()
            require("telescope.actions").close()
          end,
        },
      },
    },
  },
}
```

**Comment by folke** [comment]
I highly recommend you checking out the LazyVim spec files, to see how I do some of those things

**Comment by siduck** [comment]
> @siduck of course :)
> 
> ```lua
> {
>   "nvim-telescope/telescope.nvim",
>   opts = {
>     defaults = {
>       mappings = {
>         i = {
>           ["<esc>"] = function()
>             require("telescope.actions").close()
>           end,
>         },
>       },
>     },
>   },
> }
> ```

![image](https://user-images.githubusercontent.com/59060246/226095929-293f6318-fb00-4fd5-a1f2-9331209b47b4.png)

**Comment by folke** [comment]
You need to add `...`. 

```lua
@siduck of course :)

```lua
{
  "nvim-telescope/telescope.nvim",
  opts = {
    defaults = {
      mappings = {
        i = {
          ["<esc>"] = function(...)
            require("telescope.actions").close(...)
          end,
        },
      },
    },
  },
}
```

**Comment by siduck** [comment]
wew thx that works :0

**Comment by folke** [comment]
That's really just regular Lua though. no special things happening here...

**Comment by arunanshub** [comment]
> You need to add `...`.
> 
> ```lua
> {
>   "nvim-telescope/telescope.nvim",
>   opts = {
>     defaults = {
>       mappings = {
>         i = {
>           ["<esc>"] = function(...)
>             require("telescope.actions").close(...)
>           end,
>         },
>       },
>     },
>   },
> }
> ```

Thanks for the solution @folke and @siduck! Having the document that shows why this solution works would be helpful.

**Comment by siduck** [comment]
> You need to add `...`.
> 
> ```lua
> {
>   "nvim-telescope/telescope.nvim",
>   opts = {
>     defaults = {
>       mappings = {
>         i = {
>           ["<esc>"] = function(...)
>             require("telescope.actions").close(...)
>           end,
>         },
>       },
>     },
>   },
> }
> ```

why doesnt it work here?

```lua
{
    "hrsh7th/nvim-cmp",
    opts = {
      mapping = {
        ["<Up>"] = function(...)
          require("cmp").mapping.select_prev_item(...)
        end,
      },
    },
  },
 ```

**Comment by folke** [comment]
You probably need to `return` that? No idea. This is just lua. Lazy doesn't do anything special. Not sure what cmp expects here
