### ISSUE TITLE
ruff-lsp not working

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/NvChad#1846]
**Describe the bug**
i am using ruff lsp but for some reason it is not working it attaches to the buffer but do not work like leads-a-s donot work , gd , gD donot work and message is shown that no info is available.

**Expected behavior**
lsp keybinding work properly like go to def

**Screenshots**
![image](https://user-images.githubusercontent.com/78728701/226409411-654a7cba-daee-45f7-a541-a84ad2d3a916.png)

**Desktop (please complete the following information):**
 - Operating System arco 
 - Terminal alacritty
 - Version of Neovim 0.8

**Additional context**
lsp config in custom dirr is
```lua
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"

-- if you just want default config for the servers then put them in a table
-- local servers = { "ruff_lsp","pyright", "lua_ls", "marksman","bashls", "ltex","fortls","cmake","jsonls"}
-- local servers = {"pyright", "lua_ls", "marksman","bashls", "ltex","fortls","cmake","jsonls"}
local servers = { "ruff_lsp", "lua_ls", "marksman","bashls", "ltex","fortls","cmake","jsonls"}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
--
local config = {
    -- disable virtual text
    virtual_text = false,
    -- show signs
    update_in_insert = true,
    underline = true,
    severity_sort = true,
    float = {
      focusable = false,
      style = "minimal",
      border = "rounded",
      source = "always",
      header = "",
      prefix = "",
    },
  }
--
vim.diagnostic.config(config)

```

**Comment by siduck** [comment]
@Aneeqasif not a nvchad issue, feel free to open this issue if ruff_lsp works with non nvchad configs
