### ISSUE TITLE
Highlight overrides not working

### ISSUE THREAD

**Issue by ckt114** [NvChad/NvChad#2030]
**Describe the bug**
Highlights overrides are not working.

**To Reproduce**
1. Edit `custom/highlights.lua`
2. Add `fg = "#00cc00"` and `ctermfg = "#00cc00"` to the `Comment` section
3. Restart neovim
4. Run `:hi` and search for `Comment`

**Expected behavior**
The foreground color should be bright green.

**Screenshots**
`custom/highlights.lua`
![image](https://github.com/NvChad/NvChad/assets/573808/36716d91-2248-4df1-acae-c60b2199232f)

`Comment` didn't change.
![image](https://github.com/NvChad/NvChad/assets/573808/6b98d1f1-d0bd-4ac3-a0f4-7605abd32a8c)

**Desktop (please complete the following information):**
 - MacOS Ventura 13.3
 - Kitty or wezterm
 - Version of v0.9.0

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/7f9cc0c1-16c2-455d-9f3b-10af476e3fbb

unable to reproduce and also cterm stuff isnt supported by base46

**Comment by ckt114** [comment]
It is not helpful to just close the ticket and said that it's not reproducible. I wouldn't have put in a ticket if it's working as expected. I did exactly what you did and it isn't working that's why I put in this ticket for help. What do you suggest me doing to troubleshoot instead?

**Comment by ckt114** [comment]
Also, I'm getting error below now and even though I've removed `fg = "#00ccff"` from the highlights.lua the error doesn't stop.

```
Error detected while processing /Users/ckt114/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/ckt114/.local/share/nvim/nvchad/base46/defaults:0: Invalid highlight color: '#00ccff','
stack traceback:
        [C]: in function 'nvim_set_hl'
        /Users/ckt114/.local/share/nvim/nvchad/base46/defaults: in function </Users/ckt114/.local/share/nvim/nvchad/base46/defaults:0>
        [C]: in function 'dofile'
        /Users/ckt114/.config/nvim/init.lua:19: in main chunk
Press ENTER or type command to continue
```

**Comment by nelson777** [comment]
He have also closed my issue without the problem being solved. @siduck don't you see this doesn't help anyone ? Specially you guys ? In my case I'm trying to choose a compatible IDE for Copilot. I tested LunarVim, AstroVim and was giving NvChad a go. This attitude doesn't help me to choose you guys. My issue was a failed installation! I couldn't even run it.
