### ISSUE TITLE
Theme switcher Report Failure

### ISSUE THREAD

**Issue by LYK-love** [NvChad/NvChad#2154]
**Describe the bug**
When I use `<leader>th` to toggle theme switcher and select one theme. I always get following words:
![image](https://github.com/NvChad/NvChad/assets/74082944/0d9bfa57-d284-435a-bf1e-bd829e46ccbf)

I don't know why this occurs. The theme will be switched sussceefully. But how to eliminate these words? 

**To Reproduce**
1.  Just install NvChad. Don't change any config. Then open it.
2.  use `<leader>th` to toggle theme switcher and select one theme. 
3. You'll get those failure words.

**Desktop (please complete the following information):**
 - Operating System: MacOS 13.2.1
 - Terminal: iTerm2
 - Version of Neovim: v0.9.1

**Comment by siduck** [comment]
make sure chadrc exists
