### ISSUE TITLE
how to sync colors from plugins that are not in base46

### ISSUE THREAD

**Issue by ngtuonghy** [NvChad/NvChad#2254]
Questions 1: colors not sync (barbecue.nvim)
![image](https://github.com/NvChad/NvChad/assets/116539745/bedded98-49a9-465e-b25e-e1cac3f77059)
Questions 2; icon not loaded when changing theme (nvim-web-devicons)
![1690781180044](https://github.com/NvChad/NvChad/assets/116539745/73149466-ce88-44c2-9e4e-feaf4b372301)

**Comment by siduck** [comment]
@ngtuonghy define highlight groups via hl_add https://nvchad.com/docs/config/theming
