### ISSUE TITLE
Syntax highlighting colorscheme incorrect for Latex files when using vimtex

### ISSUE THREAD

**Issue by mvds314** [NvChad/NvChad#2378]
**Describe the bug**
I want to use vimtex for syntax highlighting LaTeX, as people claim it is better that treesitter this filetype.

When I open neovim, and open a LaTeX file right away, the highlighting color do no match the NvChad theme (onedark in my case), but resembes one of the vim default themes (not sure which one).

**To Reproduce**
1. Install vimtex, set up NvChad with any theme (onedark)
```
2. Disable treesitter for latex like [so](https://github.com/lervag/vimtex/issues/2469):
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = { "html", "css", "bash", "python", "latex", "json", "lua", "vim", "yaml" },
    },
	config = function(_, opts)
	  -- https://www.reddit.com/r/neovim/comments/xqogsu/turning_off_treesitter_and_lsp_for_specific_files/
      require "nvim-treesitter.configs".setup {
	    highlight = { enable = true, -- false will disable the whole extension
                      disable = { "tex", "latex" }, -- list of language that will be disabled
					  use_languagetree = true,
					},
	  }
    end,
  },
```

4. Open neovim
5. open a Latex file, syntax highlighting does not look good (it resembles one of the vim default themes, not sure which one).
6. Then switch (leader+t+h) to the selected theme of NvChad

**Expected behavior**
Step 6 should not be required

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Terminal: neovim-qt

**Comment by siduck** [comment]
add event="VeryLazy" for vimtex plugin

**Comment by mvds314** [comment]
Tried it like so: `{ "lervag/vimtex", ft = "tex", event="VeryLazy"},`

But it does not solve the problem.
Syntax highlighting still looks like this (intially):
![image](https://github.com/NvChad/NvChad/assets/4789270/387bfd63-a53c-456e-ab59-ac20de86107f)
After I switch theme (manually), it looks like this:
![image](https://github.com/NvChad/NvChad/assets/4789270/dfbb4571-dff3-4d53-9f91-b6667da57a6b)
Meaning the onedark theme, as all other files look.
