### ISSUE TITLE
ToggleTerm `<leader>w` toogles number too

### ISSUE THREAD

**Issue by laraib07** [NvChad/NvChad#241]
**Describe
After closing terminal in window( leader w) number line gets toggled.

**To Reproduce**
1. Leader w
2. Exit terminal

**Expected behavio**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System : Android 11
 - Terminal : termuz
 - Version of Neovim 0.5

**Additional context**

**Comment by siduck76** [comment]
@G-Rowell is working on it , check https://github.com/akinsho/nvim-toggleterm.lua/issues/84

**Comment by G-Rowell** [comment]
Can confirm, am working on it :smile: 
Will keep ya'll updated 

Ty for making this issue tho

**Comment by G-Rowell** [comment]
Should be solved by PR: https://github.com/NvChad/NvChad/pull/275

When it is merged
