### ISSUE TITLE
light theme : bubby

### ISSUE THREAD

**Issue by siduck76** [NvChad/NvChad#242]

**Comment by siduck76** [comment]
cute light colorscheme!

**Comment by G-Rowell** [comment]
@siduck76 
Is this a duplicate of https://github.com/NvChad/NvChad/issues/243?

**Comment by siduck76** [comment]
> @siduck76
> Is this a duplicate of #243?

nah lol

**Comment by siduck76** [comment]
light themes are very tough to make IMO , so i'll add this probably after 1.0v
