### ISSUE TITLE
mappings cheetsheet 

### ISSUE THREAD

**Issue by siduck76** [NvChad/NvChad#244]
mappings cheetsheet popup ( not whichkey )

**Comment by G-Rowell** [comment]
I've done a bit or work on this!
I'd love to be the assignee & one to do it :smile:

**Comment by siduck76** [comment]
> I've done a bit or work on this!
> I'd love to be the assignee & one to do it

could you show how does it look? I wouldnt want to use cheatsheet.nvim either 

something like this but styled with Highstr.nvim 

![image](https://user-images.githubusercontent.com/59060246/129441705-0f73a722-a662-46a4-b2cb-826a15285394.png)

**Comment by G-Rowell** [comment]
That isn't interactive and don't see how it looks remotely as good *or remotely as functional!* as `cheatsheet.nvim`, 
there also certainly won't be enough space to show all the NvChad mappings if we set it like that image you provided

**Comment by siduck76** [comment]
> That isn't interactive and don't see how it looks remotely as good _or remotely as functional!_ as `cheatsheet.nvim`,
> there also certainly won't be enough space to show all the NvChad mappings if we set it like that image you provided

I'll try doing this myself and let you know , if it wont work out then we will go with cheatsheet.nvim

**Comment by siduck76** [comment]
HighStr.nvim didnt go well , so I'll test cheatsheet.nvim 

so far :Cheatsheet looks like this 

![image](https://user-images.githubusercontent.com/59060246/129480182-918c758e-0d28-4869-a5c6-5086f27efdd6.png)

**Comment by siduck76** [comment]
Ok so I think we can do this without using any plugin. The main concept is to loop through the mapping table in chadrc , this way it is dynamic too + no need to define mappings in some file.

**Comment by siduck76** [comment]
# Concept 

- Suppose this is the table which is about to getting printed : 

![image](https://user-images.githubusercontent.com/59060246/129482394-88a94e15-72b7-412e-b6cf-05074b4b6f62.png)

- Stuffs to do when printing the table :

![image](https://user-images.githubusercontent.com/59060246/129482421-9deceeec-66d0-4416-b9e4-ede5b6be4ef8.png)

**Comment by siduck76** [comment]
> Ok so I think we can do this without using any plugin. The main concept is to loop through the mapping table in chadrc , this way it is dynamic too + no need to define mappings in some file.

@Akianonymus what do you think of this?

**Comment by siduck76** [comment]
```
for index, data in pairs(mappings) do
    print("\n")
    print(index .. "\n")

    for key, val in pairs(data) do
        print(key, "  |  " .. val)
    end
end

```

![image](https://user-images.githubusercontent.com/59060246/129497746-436c5448-6c14-4e6b-8505-27edb0b2f144.png)

**Comment by Akianonymus** [comment]
> > Ok so I think we can do this without using any plugin. The main concept is to loop through the mapping table in chadrc , this way it is dynamic too + no need to define mappings in some file.
> 
> @Akianonymus what do you think of this?

Fetching the mappings isn't a problem, mainly how to make the floating window and stuff.

**Comment by siduck76** [comment]
> > > Ok so I think we can do this without using any plugin. The main concept is to loop through the mapping table in chadrc , this way it is dynamic too + no need to define mappings in some file.
> > 
> > 
> > @Akianonymus what do you think of this?
> 
> Fetching the mappings isn't a problem, mainly how to make the floating window and stuff.

https://github.com/fhill2/floating.nvim#readme

**Comment by G-Rowell** [comment]
I think we're reinventing the wheel here imo


There are already plugins to display mappings

**Comment by siduck76** [comment]
> I think we're reinventing the wheel here imo
> 
> There are already plugins to display mappings

only whichkey is dynamic but its annoying to use . 

https://github.com/sudormrfbin/cheatsheet.nvim/issues/7 if this gets resolved then we'll use this.

**Comment by G-Rowell** [comment]
> > I think we're reinventing the wheel here imo
> > 
> > There are already plugins to display mappings
> 
> only whichkey is dynamic but its annoying to use . 
> 
> https://github.com/sudormrfbin/cheatsheet.nvim/issues/7 if this gets resolved then we'll use this.

So those are for sure fair points


But I think the ideal solution is to make a PR upstream to provide that functionality, rather than make our own new plugin

**Comment by siduck76** [comment]
> > > I think we're reinventing the wheel here imo
> > > There are already plugins to display mappings
> > 
> > 
> > only whichkey is dynamic but its annoying to use .
> > [sudormrfbin/cheatsheet.nvim#7](https://github.com/sudormrfbin/cheatsheet.nvim/issues/7) if this gets resolved then we'll use this.
> 
> So those are for sure fair points
> 
> But I think the ideal solution is to make a PR upstream to provide that functionality, rather than make our own new plugin

yes ,we could add a PR to cheatsheet.nvim only
