### ISSUE TITLE
theme toggle 

### ISSUE THREAD

**Issue by siduck76** [NvChad/NvChad#245]
theme toggle keybind between light and dark theme

**Comment by G-Rowell** [comment]
Is the Telescope theme switcher not enough?

**Comment by siduck76** [comment]
> Is the Telescope theme switcher not enough?

it is , but what if the user wants to switch between two of his fav themes ( most likely one dark theme and one light theme) so he could simply press a mapping and the theme toggles.

**Comment by G-Rowell** [comment]
I feel like this is moving towards `bloat` territory, 

the user can just create their own mapping for that very niche case. 

I don't know anyone who switches themes regularly in the first place

**Comment by G-Rowell** [comment]
Like, 
I thought the whole idea of NvChad, was a minimal & sensible IDE, which is simple & bloat free such that the user can easily add their own configs/extras for their own niche cases

Or at least put stuff like this in the wiki or an optional opt-in extras area

**Comment by siduck76** [comment]
> I feel like this is moving towards `bloat` territory,
> 
> the user can just create their own mapping for that very niche case.
> 
> I don't know anyone who switches themes regularly in the first place

light theme at day and dark theme at night xd?

**Comment by siduck76** [comment]
> Like,
> I thought the whole idea of NvChad, was a minimal & sensible IDE, which is simple & bloat free such that the user can easily add their own configs/extras for their own niche cases
> 
> Or at least put stuff like this in the wiki or an optional opt-in extras area

yes we'll add it in the wiki , someone could provide code for this so it gets newbie friendly since none including me knows how theme switcher works.

**Comment by G-Rowell** [comment]
I know how the theme switcher works, so does Aki.

I think we should consider some more disable/enable flags for these things like theme switchers & nice features

**Comment by siduck76** [comment]
> I know how the theme switcher works, so does Aki.
> 
> I think we should consider some more disable/enable flags for these things like theme switchers & nice features

agreed , if the theme switcher is gonna be added in the config then for sure there will be an option for it and it will be disabled by default .

**Comment by siduck76** [comment]
Soo the basic idea is :

**Comment by siduck76** [comment]
local fav_themes = { "onedark", "onelight"}   -- onelight doesnt exist as of now xD , just a theme name.

local toggle_theme = function()
   if current theme is onelight then 
      change current theme to onedark 
   --  do all the stuffs to reload theme like require statusline etc 
   
   change current to onelight
   -- do all stuff to reload theme
end

**Comment by G-Rowell** [comment]
@siduck76 

Should this be closed due to the main commit #245?

**Comment by ashincoder** [comment]
closing, as commit #245 enhancement has been added
