### ISSUE TITLE
Splitscreen crashing if .js file is opened from file tree after the split screen is created

### ISSUE THREAD

**Issue by Breezee-ops** [NvChad/NvChad#2453]
**Describe the bug**
NvChad crashes and exits out when I try to open a javascript file with a vertical splitscreen in place.

**To Reproduce**
1. Open a random file that is not a javascript file.
2. Go into Normal mode and :vsp or :vsplit
3. Open any .js file
4. Crash and sadness

**Expected behavior**
Doesn't crash and lets me open the file in the screen I choose from the A - B selection point

**Screenshots**
Minutes before destruction:
<img width="1280" alt="image" src="https://github.com/NvChad/NvChad/assets/77127626/21a15ebb-8f3e-4103-991e-fafe11ad01dc">
upon opening .js file. When I press either A or B nvim crashes and quits out:
<img width="1280" alt="image" src="https://github.com/NvChad/NvChad/assets/77127626/9da8d89b-cbd7-4213-abfc-20adf35b3b8c">

**Desktop (please complete the following information):**
 - Windows 11
 - Powershell oh-my-posh
 - 0.9.4

**Additional context**
I'm enjoying NvChad but a more stable development environment would be imperative since losing progress for no reason at a random point is pretty hard.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/203d983c-fca7-45d4-8b1b-423153d756c4


unable to reproduce. please make a video and show me.

**Comment by siduck** [comment]
show me output of mes command
