### ISSUE TITLE
customization for the colorizer

### ISSUE THREAD

**Issue by insidersbuilt** [NvChad/NvChad#255]
how can i add my custom settings to the colorizer 

![image](https://user-images.githubusercontent.com/87114084/129474923-dc278782-917a-465d-8514-708111af913c.png)

and also can any one tell me what the &it;<leader&gt;fw does because it open the teliscope some live grep but it deos not do anything. It worked once a long time ago but now how can i make it work am i missing something

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/129476507-2e39a126-cece-443f-8953-05bafc107c49.png)

dont use ()'s

**Comment by insidersbuilt** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/129476507-2e39a126-cece-443f-8953-05bafc107c49.png)
> 
> dont use ()'s

**Comment by insidersbuilt** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/129476507-2e39a126-cece-443f-8953-05bafc107c49.png)
> 
> dont use ()'s

it does not works

**Comment by ashincoder** [comment]
to add custom settings for colorsizer:
lua```
M.colorizer = function()
    local present, colorizer = pcall(require, "colorizer")
    if present then
           colorizer.setup({ "*" }, {
    RGB = true, -- #RGB hex codes
    RRGGBB = true, -- #RRGGBB hex codes
    RRGGBBAA = true, -- #RRGGBBAA hex codes
    rgb_fn = true, -- CSS rgb() and rgba() functions
    hsl_fn = true, -- CSS hsl() and hsla() functions
    css = true, -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
    css_fn = true, -- Enable all CSS *functions*: rgb_fn, hsl_fn
  })
        vim.cmd("ColorizerReloadAllBuffers")
    end
end
```

**Comment by siduck76** [comment]
> > ![image](https://user-images.githubusercontent.com/59060246/129476507-2e39a126-cece-443f-8953-05bafc107c49.png)
> > dont use ()'s
> 
> i copied the settings from the chris@machine blog and i worked but can you explain i know you are not here for explaining things but help me
> 
> why is there <leader>fw live-grep and it does nothing

dont do live grep in home folder , cd into some folder and do live grep!
