### ISSUE TITLE
[Feature] Arrow separator for statusline

### ISSUE THREAD

**Issue by n6v26r** [NvChad/NvChad#2557]
Hey! the statusline separator_style appears to have an arrow option, but it behaves just like block.

![Screenshot from 2023-12-13 20-33-52](https://github.com/NvChad/NvChad/assets/108262765/45584301-73ec-4070-aa0f-6913cd65478a)

This is what is looks like:
![Screenshot from 2023-12-13 20-34-04](https://github.com/NvChad/NvChad/assets/108262765/8dc79f31-4576-44a0-9afb-62cec0865be4)

Could we get a proper arrow separator style?

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/5cf9eabc-d6c5-476e-8d44-f054d7f82c8c)
