### ISSUE TITLE
1-2 sec freeze after saving buffer

### ISSUE THREAD

**Issue by mculp** [NvChad/NvChad#262]
**Describe the bug**
Whenever I save a file, I get a 1-2 second hang. I believe this started after I added Ruby to LSP, but I've tried re-installing NvChad to get default settings and everything and it's still occurring. It happens with non-ruby files too.

**To Reproduce**
possible steps to reproduce the behavior:
1. enable Ruby support for LSP
2. `:w` any file

**Expected behavior**
I expect saving a file/buffer to be snappy.

**Desktop (please complete the following information):**
 - MacOS 10.15.7
 - Kitty 0.22.2

```
NVIM v0.6.0-dev+1517-geece0735f
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210712-8087-tydiqd/build/config -I/tmp/neovim-20210712-8087-tydiqd/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210712-8087-tydiqd/build/src/nvim/auto -I/tmp/neovim-20210712-8087-tydiqd/build/include
Compiled by mculp@Matts-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-eece073/share/nvim"
```

Any tips on how to debug the issue?

**Comment by siduck76** [comment]
could you provide a video or such to demonstrate this behaviour? @mculp

**Comment by G-Rowell** [comment]
Hmmmm, @mculp 

I think a better priority for debugging might be to check 2 things:
Can you give us the output of:
- `:checkhealth` this does as the name says
- `:au` this will list all of the auto-commands that you have

Understandably frustrating, we'll see if we can help!

It's 1am in my timezone so I might have to come back to this when I wake up tomorrow

**Comment by mculp** [comment]
So I narrowed it down to nvimtree. Here's a recording. Notice how the cursor just disappears for 1-2 sec after saving after I open nvimtree. Even if I close the nvimtree pane, once it's been loaded, the behavior still occurs

https://www.loom.com/share/2406553c09924040a94036fa5d1b8c77

**Comment by siduck76** [comment]
you sure ,you're using latest version of nvchad? cuz there was a mapping in older version which had some lag.

**Comment by mculp** [comment]
Updated yesterday, but I can try updating again

```
❯ git log                                                                                                                                                                                                  Tue Aug 17 13:21:35 2021
commit eaaefc236d1c0f3b0c6309bbb86a29067b5c515f (grafted, HEAD -> main)
Author: siduck76 <siduckk76@protonmail.com>
Date:   Mon Aug 16 19:04:09 2021 +0530

    add one-light (#243)
```

**Comment by mculp** [comment]
I found this, will try it out

https://github.com/kyazdani42/nvim-tree.lua/issues/549

**Comment by mculp** [comment]
> you are using fish as an editor shell (which might be fixed in the future), try set shell=/bin/bash in your vim config.

This was the problem! Thanks, I'll close this now.

**Comment by G-Rowell** [comment]
Ahhhh, glad it's fixed!
