### ISSUE TITLE
How do I navigate between terminals?

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#264]
I can't find a way to move via keybindings between vim and split terminal other than the mouse.

**Comment by G-Rowell** [comment]
Hi @se7en-x230,

it's done in the standard vim way, with `<CNTL> + w + (h,j,k,l)`.

We'll likely change these bindings at some point to make it easier,
hope this helps

**Comment by Akianonymus** [comment]
see `h moving-windows` for more info.
