### ISSUE TITLE
HTML autocompletion not working

### ISSUE THREAD

**Issue by DylanSatow** [NvChad/NvChad#265]
**Is your feature request related to a problem? Please describe.**
This seems like it should be simple, but I just can't get it to work. When I type <div>, I want it to automatically add a </div>, and when I click return in the center of a tag, I want it to space the tags properly. It seems like there is some obscure setting missing.

**Describe the solution you'd like**
I would like to be able to autoclose tags.

**Additional context**
I'm on the most recent version of Mac OS X, and I am using the new M1 chip. I am also running on Iterm2 and the most recent version of NVIM.

**Comment by G-Rowell** [comment]
Hi Dylan,

NvChad doesn't come with language specific configuration, that's up to the user to decide.

Can you try `:LspInstall html` to start off with?

G

**Comment by DylanSatow** [comment]
Hey,

I already installed the language server. When I just type div, I can autocomplete it to <div></div>, but this doesn't really work for me, as there is no easy way to quickly added attributes. It seems like I just need to change something really small, but I can't find what it is.

Thanks

**Comment by siduck76** [comment]
> Hey,
> 
> I already installed the language server. When I just type div, I can autocomplete it to
> 
> , but this doesn't really work for me, as there is no easy way to quickly added attributes. It seems like I just need to change something really small, but I can't find what it is.
> Thanks

dont type div , type <di and you will see the completion

**Comment by G-Rowell** [comment]
Hmmmm, 

I've sent a message to the other maintainers, they know about more about the LSP side of things.

Hopefully we'll get you sorted ASAP

**Comment by siduck76** [comment]
@DylanSatow works for me 

![image](https://user-images.githubusercontent.com/59060246/129727323-913e3635-8bc6-4bd8-a365-07dadd25e31e.png)

**Comment by siduck76** [comment]
dont use < , if you need snippets 

![image](https://user-images.githubusercontent.com/59060246/129727397-58da96eb-d20c-42d2-94a3-c3c6c61d7dae.png)

**Comment by siduck76** [comment]
add this in your pluginlist.lua :

```
  use {
      "alvan/vim-closetag",
      event = "InsertEnter",
   }
```

**Comment by G-Rowell** [comment]
Hmmmmm, 

this would certainly be part of [LuaSnip](https://github.com/L3MON4D3/LuaSnip/), 

try the [Nice configs](https://github.com/L3MON4D3/LuaSnip/wiki/Nice-Configs)
and [examples](https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua)

**Comment by DylanSatow** [comment]
> add this in your pluginlist.lua :
> 
> ```
> use {
>       "alvan/vim-closetag",
>       event = "InsertEnter",
>   }
> ```

When I install it, where should I add the installation option code? It is intended for a standard .vimrc, and it doesn't work in the init.lua file. Is there a separate file in this setup for config code like that for plugins?

**Comment by siduck76** [comment]
> > add this in your pluginlist.lua :
> > ```
> > use {
> >       "alvan/vim-closetag",
> >       event = "InsertEnter",
> >   }
> > ```
> 
> When I install it, where should I add the installation option code? It is intended for a standard .vimrc, and it doesn't work in the init.lua file. Is there a separate file in this setup for config code like that for plugins?

give me the config , i'll tell.

**Comment by DylanSatow** [comment]
" filenames like *.xml, *.html, *.xhtml, ...
" These are the file extensions where this plugin is enabled.
"
let g:closetag_filenames = '*.html,*.xhtml,*.phtml'

" filenames like *.xml, *.xhtml, ...
" This will make the list of non-closing tags self-closing in the specified files.
"
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx'

" filetypes like xml, html, xhtml, ...
" These are the file types where this plugin is enabled.
"
let g:closetag_filetypes = 'html,xhtml,phtml'

" filetypes like xml, xhtml, ...
" This will make the list of non-closing tags self-closing in the specified files.
"
let g:closetag_xhtml_filetypes = 'xhtml,jsx'

" integer value [0|1]
" This will make the list of non-closing tags case-sensitive (e.g. `<Link>` will be closed while `<link>` won't.)
"
let g:closetag_emptyTags_caseSensitive = 1

" dict
" Disables auto-close if not in a "valid" region (based on filetype)
"
let g:closetag_regions = {
    \ 'typescript.tsx': 'jsxRegion,tsxRegion',
    \ 'javascript.jsx': 'jsxRegion',
    \ 'typescriptreact': 'jsxRegion,tsxRegion',
    \ 'javascriptreact': 'jsxRegion',
    \ }

" Shortcut for closing tags, default is '>'
"
let g:closetag_shortcut = '>'

" Add > at current position without closing the current tag, default is ''
"
let g:closetag_close_shortcut = '<leader>>'

**Comment by siduck76** [comment]
look , local g:anything='abc' will change into vim.g.anything='abc'

So i'll help with some : 

```
use {
      "alvan/vim-closetag",
      event = "InsertEnter",
      setup = function()
       add config here
      end 
  }

**Comment by siduck76** [comment]
also let g:anything="xyz" , will turn to vim.g.anything = "xyz" , I suggest you learning some lua :)

**Comment by DylanSatow** [comment]
Yeah I just need to sit down and read some documentation. 

My hopefully last issue is that lua doesn't like this statement because of the collon

closetag_regions = {
    'typescript.tsx': 'jsxRegion,tsxRegion',
    'javascript.jsx': 'jsxRegion',
    'typescriptreact': 'jsxRegion,tsxRegion',
    'javascriptreact': 'jsxRegion',
     }

**Comment by siduck76** [comment]
closetag_regions = {
typescript.tsx=  { 'jsxRegion','tsxRegion'},
javascript.jsx= 'jsxRegion',
}

should work i think
