### ISSUE TITLE
Weird Artifact When Using Theme

### ISSUE THREAD

**Issue by CommanderGL** [NvChad/NvChad#2678]
**Describe the bug**
There is a weird artifact at pane corners when using a theme with NvChad.

**To Reproduce**
1. Install NvChad
2. Switch to Catppuccin
3. Open up a couple panes

**Expected behavior**
Functional with theme.

**Screenshots**
![Screenshot from 2024-02-17 15-21-03](https://github.com/NvChad/NvChad/assets/85912189/813bf974-fcd9-4df3-a7a2-ff1c25677ffd)

**Desktop (please complete the following information):**
 - Debian 12
 - Alacritty
 - v0.9.5

**Comment by siduck** [comment]
thats not   nvchad issue, its related to nvimtree. nothingwe can do about!

**Comment by CommanderGL** [comment]
okay
