### ISSUE TITLE
Guidance with default_config.lua

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#273]
I guess default_config is the custom settings file.

I added:
-- test to add "start edit where last left the file" from options.lua in default_config 
`vim.cmd [[ au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif ]]`

Is that the correct way and file to add that feature?

**Comment by siduck76** [comment]
@se7en-x230  dont mess with default_config  , chadrc.lua is the user config . edit that!

**Comment by se7en-x230** [comment]
Thanks

**Comment by G-Rowell** [comment]
We're adding some documentation to this very soon!
