### ISSUE TITLE
TikTok checker

### ISSUE THREAD

**Issue by mqku** [NvChad/NvChad#274]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by mqku** [comment]
Tik

**Comment by siduck76** [comment]
Tiktok? what does that mean

**Comment by G-Rowell** [comment]
Ummmm, you've provided no description. :laughing: 

Happy to open this again if you do provide any info
