### ISSUE TITLE
Overriding mappings from on_attach

### ISSUE THREAD

**Issue by malinka-2233** [NvChad/NvChad#2759]
Hey! I recently migrated to 2.5 and i can not figure out a proper way to override  the mappings from default on_attach functions of plugins, provided by nvchad.

Like this one https://github.com/NvChad/NvChad/blob/32d8a1fdffdc8faf17f8ac8091d44764d61277a3/lua/nvchad/configs/gitsigns.lua#L22

I cant do it in my mappings.lua file, since they are being loaded after, i think.

Do i have to override the on_attach myself in my plugins/init.lua? Or is there a better way?

Also, thank you so much for updating the nvchad, i love the new version.

**Comment by siduck** [comment]
```lua
{
   "blabla gitsigns", 
   opts = {
        on_attach = function(bufnr)
          require("nvchad.configs.gitsigns).on_attach(bufnr)
          
          now add your mappings here :)
        end
   }
 }
  ```
