### ISSUE TITLE
Cheatsheet has disabled plugins listed (eg. netrw inbuilt plugin)

### ISSUE THREAD

**Issue by G-Rowell** [NvChad/NvChad#276]
**Describe the bug**
The cheatsheet plugin will show disabled plugin mappings even if they are disabled.
For example, it will show `netrw` inbuilt file manager for vim, mappings

**To Reproduce**
1. In `chadrc.lua` change `plugin_status.cheatsheet = true`
2. Do `:PackerSync`
3. Restart NeoVim
4. Run cheatsheet with `<leader> + d + k`
5. Search for & see the `netrw` mappings, these should not be there as that inbuilt plugin in disabled

**Expected behavior**
No inbuilt & disabled plugins should appear in the cheatsheet

**Screenshots**
![image](https://user-images.githubusercontent.com/3367398/129856711-77973374-2cb4-4d01-9259-3888e3006ead.png)

**Desktop (please complete the following information):**
No :chad :

**Additional context**
No :chad :

**Comment by siduck76** [comment]
> **Describe the bug**
> The cheatsheet plugin will show disabled plugin mappings even if they are disabled.
> For example, it will show `netrw` inbuilt file manager for vim, mappings
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. In `chadrc.lua` change `plugin_status.cheatsheet = true`
> 2. Do `:PackerSync`
> 3. Restart NeoVim
> 4. Run cheatsheet with `<leader> + d + k`
> 5. Search for & see the `netrw` mappings, these should not be there as that inbuilt plugin in disabled
> 
> **Expected behavior**
> No inbuilt & disabled plugins should appear in the cheatsheet
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/3367398/129856711-77973374-2cb4-4d01-9259-3888e3006ead.png)
> 
> **Desktop (please complete the following information):**
> No :chad :
> 
> **Additional context**
> No :chad :

This issue should go in cheatsheet.nvim repo.

**Comment by G-Rowell** [comment]
> > **Describe the bug**
> > The cheatsheet plugin will show disabled plugin mappings even if they are disabled.
> > For example, it will show `netrw` inbuilt file manager for vim, mappings
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. In `chadrc.lua` change `plugin_status.cheatsheet = true`
> > 2. Do `:PackerSync`
> > 3. Restart NeoVim
> > 4. Run cheatsheet with `<leader> + d + k`
> > 5. Search for & see the `netrw` mappings, these should not be there as that inbuilt plugin in disabled
> > 
> > **Expected behavior**
> > No inbuilt & disabled plugins should appear in the cheatsheet
> > **Screenshots**
> > **Desktop (please complete the following information):**
> > No :chad :
> > **Additional context**
> > No :chad :
> 
> This issue should go in cheatsheet.nvim repo.

No, because it's a config issue. 
If you read the README of cheatsheet.nvim, it tells you how to disable these features

**Comment by G-Rowell** [comment]
See this section: https://github.com/sudormrfbin/cheatsheet.nvim#configuration

**Comment by ashincoder** [comment]
@siduck76 I don't think cheatsheet can be a replacement for which-key. Cause if u forget a keybind it is no efficient and pratical to check cheatsheet. I think it is much better to use which-key. May I know why u did not choose which-key.

**Comment by G-Rowell** [comment]
I do think there is some good value in whichkey tbh


Hmmmmmm ........

**Comment by siduck76** [comment]
> @siduck76 I don't think cheatsheet can be a replacement for which-key. Cause if u forget a keybind it is no efficient and pratical to check cheatsheet. I think it is much better to use which-key. May I know why u did not choose which-key.

I dont like pressing space and waiting for it to popup ,  I wanted a cheatsheet in which we could search and navigate .

**Comment by siduck76** [comment]
https://github.com/sudormrfbin/cheatsheet.nvim/issues/8

**Comment by G-Rowell** [comment]
We could honestly have both?

Because I'm tempted to install `whichkey` personally

And then we can have them both disabled but have `enable mapping helpers` in the docs?

Dunno but hmmm..... :thinking:

**Comment by siduck76** [comment]
> We could honestly have both?
> 
> Because I'm tempted to install `whichkey` personally
> 
> And then we can have them both disabled but have `enable mapping helpers` in the docs?
> 
> Dunno but hmmm.....

nah only one! :angry:

**Comment by ashincoder** [comment]
> > @siduck76 I don't think cheatsheet can be a replacement for which-key. Cause if u forget a keybind it is no efficient and pratical to check cheatsheet. I think it is much better to use which-key. May I know why u did not choose which-key.
> 
> I dont like pressing space and waiting for it to popup , I wanted a cheatsheet in which we could search and navigate .

I mean u don't have to wait u can adjust the speed with `vim.opt.timeoutlen`lua

**Comment by ashincoder** [comment]
I don't know why the backface to whichkey cause it can be lazyloaded. It can be configured easily. The time interval can be changed. Why ??. Whichkey is more versatile and more efficient.

**Comment by siduck76** [comment]
> I don't know why the backface to whichkey cause it can be lazyloaded. It can be configured easily. The time interval can be changed. Why ??. Whichkey is more versatile and more efficient.

can we search stuff in whichkey? cheatsheet.nvim is integrated well with telescope.

**Comment by ashincoder** [comment]
we just have to take a look . We don't even have to search

**Comment by siduck76** [comment]
> we just have to take a look . We don't even have to search

agreed. I want whichkey to show all nvchad configs like this : 

https://cdn.discordapp.com/attachments/869561752906514472/876864282984349727/vim_cheatsheet-aa3d676c.png

**Comment by ashincoder** [comment]
Don't u know whichkey. It is like integrated popup which shows all the keybindings

**Comment by ashincoder** [comment]
It doesn't show in the terminal like u have shown

**Comment by siduck76** [comment]
> It doesn't show in the terminal like u have shown

Ik , I meant showing a popup in neovim with all nvchad mappings.

**Comment by ashincoder** [comment]
U may have to hardcord it to show the description

**Comment by siduck76** [comment]
> U may have to hardcord it to show the description

oh :l , cheatsheet.nvim already does it.

**Comment by ashincoder** [comment]
It does but don't u think whichkey.nvim is more friendly and efficient

**Comment by siduck76** [comment]
> It does but don't u think whichkey.nvim is more friendly and efficient

I'll have to think about it , if someone works on showing all nvchad keybinds + their desc in whichkey then Im gonna consider replace it with cheatsheet.nvim

**Comment by siduck76** [comment]
https://github.com/NvChad/NvChad/issues/244#issuecomment-899061592

**Comment by ashincoder** [comment]
MM. It would be great to work on it.

**Comment by ashincoder** [comment]
Shall we remove the bug label.

**Comment by siduck76** [comment]
@G-Rowell https://github.com/sudormrfbin/cheatsheet.nvim/issues/8#issuecomment-902432744

**Comment by ashincoder** [comment]
@G-Rowell can u rename this issue to Adding whichkey.

**Comment by ashincoder** [comment]
And also @siduck76 could u specify which color do u wanna use for the which key background. Just specifiy the hexcode

**Comment by siduck76** [comment]
> And also @siduck76 could u specify which color do u wanna use for the which key background. Just specifiy the hexcode

use darker_black 

colors.darker_black , so it will work on all themes.

**Comment by siduck76** [comment]
@ashincoder keep this on hold for 2+ weeks , we wont be adding any new feaures till then . we need to clean the config , debloat stuff , refactor and make config more and more faster xD

**Comment by siduck76** [comment]
we gotta get the issues count to 0 too , also my exams are there in next month :c .

**Comment by siduck76** [comment]
anyways https://github.com/sudormrfbin/cheatsheet.nvim/commits?author=sudormrfbin @G-Rowell

**Comment by ashincoder** [comment]
Okee.
