### ISSUE TITLE
‏ tiktok checker

### ISSUE THREAD

**Issue by locc4** [NvChad/NvChad#278]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by locc4** [comment]
- [ ] ‏ tiktok checker 
@G-Rowell ![image](https://user-images.githubusercontent.com/89132719/129876223-1bd81a4d-7d36-4e93-a656-d6759ce1d584.jpeg)[[[[rfr]()]()]()]()

**Comment by siduck76** [comment]
@locc4 STOP

**Comment by locc4** [comment]
> @locc4 STOP

كلزق😂
