### ISSUE TITLE
Install git clone not working

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#286]
The install instructions on the install page 
`git clone git@github.com:NvChad/NvChad.git ~/.config/nvim --depth 10 && nvim +PackerSync`
asks for fingerprint and gives 
`Please make sure you have the correct access rights and the repository exists.`

**Comment by kimjoaoun** [comment]
Have you tried cloning the repository using the HTTPS url?

**Comment by siduck76** [comment]
@se7en-x230 https://nvchad.netlify.app/docs/Getting%20started/Setup#install

**Comment by se7en-x230** [comment]
`git clone https://github.com/NvChad/NvChad.git ~/.config/nvim --depth 10 && nvim +PackerSync` 
Works fine.

So I guess the the entry is not correct on the install page

**Comment by G-Rowell** [comment]
We're in the middle of updating our docs,
the issue caused by cloning with `git clone git@github.com:NvChad/NvChad.git ~/.config/nvim --depth 10 && nvim +PackerSync`
is that you don't have git SSH keys set up

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Check this out


The HTTP link works fine though, so no real issue with just using that

**Comment by joelash** [comment]
Semi-related issue but following these I get the following error on the `nvim +PackerSync`

```
Error detected while processing command line:
E492: Not an editor command: PackerSync
```

**Comment by joelash** [comment]
> Semi-related issue but following these I get the following error on the `nvim +PackerSync`
> 
> ```
> Error detected while processing command line:
> E492: Not an editor command: PackerSync
> ```

Looks like I didn't have the right version of nvim installed, my bad

**Comment by ammmir** [comment]
+1

**Comment by G-Rowell** [comment]
> > Semi-related issue but following these I get the following error on the `nvim +PackerSync`
> > ```
> > Error detected while processing command line:
> > E492: Not an editor command: PackerSync
> > ```
> 
> Looks like I didn't have the right version of nvim installed, my bad

Thank you very much for following up with what caused your issue!

Much appreciated :)
