### ISSUE TITLE
Unable to use my custom theme 

### ISSUE THREAD

**Issue by slfg** [NvChad/NvChad#289]
After creating a theme (both the lua file and the base16) I'm unable to use my custom theme, it gives me an error when selecting the theme with space + t + h saying the following:

`Error: Cannot load highlights plugin!
Error: Not able to realod all plugins.`

**Comment by siduck76** [comment]
@slfg you need to add it on nvim base16 repo

**Comment by slfg** [comment]
how to?

**Comment by pathakraul** [comment]
Inside this path `$HOME/.local/share/nvim/site/pack/packer/opt/nvim-base16.lua/lua/themes` 
This is on ubuntu

**Comment by siduck76** [comment]
> Inside this path `$HOME/.local/share/nvim/site/pack/packer/opt/nvim-base16.lua/lua/themes`
> This is on ubuntu

I dont think this should be done!! 

any nvim-base16 updates would remove that

**Comment by pathakraul** [comment]
Without that it was not working, though I agree that its not a solution

**Comment by siduck76** [comment]
> Without that it was not working, though I agree that its not a solution

yes , @slfg could you show how your theme works?

**Comment by siduck76** [comment]
@slfg for the time being you can add what @pathakraul said.
