### ISSUE TITLE
Chad user configs javascript

### ISSUE THREAD

**Issue by ddiaz2380** [NvChad/NvChad#291]
Is it possible to have a javascript LspInstall?

**Comment by siduck76** [comment]
:LspInstall typescript

**Comment by siduck76** [comment]
This has js stuff too Ig

**Comment by ddiaz2380** [comment]
Yes but it is not pure javascript

**Comment by G-Rowell** [comment]
Hi @ddiaz2380,

consider checking out our docs

https://nvchad.netlify.app/docs/Getting%20started/Post%20Install

**Comment by siduck76** [comment]
> Yes but it is not pure javascript

I dont think lspconfig has a javscript lsp

**Comment by ddiaz2380** [comment]
ok thx!

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/130030031-45125ebc-92cc-480a-8c36-e6438280f613.png)
