### ISSUE TITLE
Setup page should clarify Node usage

### ISSUE THREAD

**Issue by ccope** [NvChad/NvChad#301]
I prefer to avoid depending on Node.js in my configs if possible. The plugin is fully written in Lua, and is using nvim-lsp (also lua), so I was curious what might need it. As far as I can tell, the only thing that may require Node.js is some of the LSP servers?

**Comment by JustSage** [comment]
Yes, LspInstall depends on npm to install lsp's.

**Comment by G-Rowell** [comment]
Yeah, understandably wanting to avoid it for a NeoVim config,

but as Sage said, it's a requirement for several language servers I believe.

You do raise a good point, 
let's leave this open until we add some kind of note about this to our docs

G

**Comment by siduck76** [comment]
has been added.
