### ISSUE TITLE
Load last session shortcut from dashboard is outdated

### ISSUE THREAD

**Issue by Eduruiz** [NvChad/NvChad#303]
**Describe the bug**
The load last session from dashboard shows the shortcut `SPC s l` but the working one is `<leader>l` according to `chadrc 

**To Reproduce**
1. Look at the dashboard xD

**Expected behavior**
Dashboard shortcuts reflect the actual ones

**Screenshots**
![19-08-21--21:34:04](https://user-images.githubusercontent.com/1951631/130161186-8c500401-2f96-4ce5-ad74-a10c8cf09d43.jpg)

**Comment by G-Rowell** [comment]
Yup!

Can confirm this,
I'll update it now

**Comment by G-Rowell** [comment]
@Eduruiz 

Fixed with this PR,
will close when it's merged 

https://github.com/NvChad/NvChad/pull/304


Thanks for letting us know!! :smile:
