### ISSUE TITLE
Kite completion support

### ISSUE THREAD

**Issue by vlermandac** [NvChad/NvChad#305]
For some reason when Kite shows completion suggestions the cursor automatically goes to the end of the line, which makes it useless.

**Comment by siduck76** [comment]
could you provide a video of your behaviour?

**Comment by vlermandac** [comment]
Sure

https://user-images.githubusercontent.com/68314874/130182123-d2260f0d-0f55-417a-a6e3-e91edbf0dc30.mp4

**Comment by siduck76** [comment]
@vlermandac I dont think we have kite added by default , how did you added it?

**Comment by siduck76** [comment]
Enough info isnt given :l . Also we didnt add kite . @G-Rowell shall we close this issue?

**Comment by G-Rowell** [comment]
Hi @vlermandac,

as NvChad **doesn't provide any specific language support** we might close this.
Also it seems like you haven't provided any information that we've asked for.

The idea with NvChad is that it's a foundation config that you can customize to suit your own programming language


I hope you've managed to figure it out over the past few days,
all the best.
G
