### ISSUE TITLE
You absolutely do not remap 'X'

### ISSUE THREAD

**Issue by schiptsov** [NvChad/NvChad#309]
'X' is the standard binding for deleting a char before the cursor, which goes back to ancient times and is nice and "logical" one.

Imagine closing the damn buffer when one tries to delete a character.

This is beyond frustration. This is a pure rage.

**Comment by mTvare6** [comment]
Yes, older versions of this had so many vanilla vim keybinds bound to something bad too

**Comment by siduck76** [comment]
> Yes, older versions of this had so many vanilla vim keybinds bound to something bad too

agreed , I'll try removing S-x

**Comment by G-Rowell** [comment]
@schiptsov I think we could probably use some kinder language, 

I understand your frustration, however the mappings are deliberately easy to change.
Furthermore, every single NvChad contributor has put their own free time into this.

I think there is a more reasonable way to voice this issue.


I do however, agree, I didn't really use that mapping much at all and felt this made sense, it was also a natural evolution of previous NvChad iterations.

I'm more than happy to look into this is the coming days and see what other default mapping we can provide instead.

In the meantime, simply change lua/chadrc.lua Line: 123

From:       close = "<S-x>",
To whatever mapping you wish & restart.

G

**Comment by G-Rowell** [comment]
Having missed the title and just read it,

Dmitrii, I wish to be explicit,
anyone and everyone is welcome in NvChad.
This of course extends to you as much as any other member in the community.

All of the team do however require that respectful discussion takes place.
A more constructive issue title could be `default close mapping conflicts with core Vim bind`.
Please avoid such titles like this in the future.

**Comment by siduck76** [comment]
> Having missed the title and just read it,
> 
> Dmitrii, I wish to be explicit,
> anyone and everyone is welcome in NvChad.
> This of course extends to you as much as any other member in the community.
> 
> All of the team do however require that respectful discussion takes place.
> A more constructive issue title could be `default close mapping conflicts with core Vim bind`.
> Please avoid such titles like this in the future.

or "Avoid using vanilla vim bind"

**Comment by Akianonymus** [comment]
Changed in the pr: https://github.com/NvChad/NvChad/pull/311

**Comment by schiptsov** [comment]
> A more constructive issue title could be `default close mapping conflicts with core Vim bind`.
> Please avoid such titles like this in the future.

The pr has been intentionally made emotional, but there was no wish to make it rude or disrespectful. It is just a matter of style.

Now about respectful discussion. The idea of just to make a neovim look like vscode is a bit shallow, so to speak. The better approach, it seems, to make neovim better than vscode, to keep everything that is vimish and add something that is nice, but do not contradicts with vim's "phylosophy" and established practices.

For example, there is a lot (almost 40 years) of thought and effort behind default (classic) key bindings (https://www.flickr.com/photos/sermoa/5421396271).
The ergonomics is are not incidental an should be considered as a small miracle of software engineering. (https://karma-engineering.com/lab/wiki/Tools/Neovim). Most of old-school vi users do not use backspace or even arrows (see below).

And, of course, there is no shortage of videos about how really cool default vim keys are (https://youtu.be/OnUiHLYZgaA)

So, there are a few suggestions. Do not remap, leave everything as it is by default. Add separate config where users could add their own favorite plugins (ALE, Whichkey-nvim, you know).There, perhaps, should be a separate file for LSP server setups (people might want to use already installed stuff).

By the way, I use https://github.com/takac/vim-hardtime and suggest it as a sort of test for your configuration - if everything woks in this mode - perfect. Again, lots of people never touch backspace or arrow keys.

As for window stuff, which is a most resent innovation, ^W jk seems to fit well, so window bindings, at least in theory, should go behind ^W prefix, so switching between the tree or an outline could be "natural" and uncluttered.

It seem you are after aesthetics first, which is good (I liked the Tokyo wallpaper and theme!) but try to dig deeper into vi and vim as you go ;)

**Comment by siduck76** [comment]
@schiptsov its not just about aesthetics , I just wasnt aware that S-x was a default vim bind. Also making neovim look like vscode, We arent trying to do that :p . I could just simply use a gui ide but I would miss vim , hence made nvim's UI look better with a functional file tree + nerdfont icons , I see no bad in it.

**Comment by G-Rowell** [comment]
Despite what @schiptsov implies,
I do wish to make it clear to anyone reading:

## **Anyone who comes to NvChad is welcome, regardless of capability or experience. They merely need to bring with them friendliness & effort**
