### ISSUE TITLE
Evergreen doesn't seem to work.

### ISSUE THREAD

**Issue by GiantGlint** [NvChad/NvChad#313]
Everytime I try to switch to everforest (with space+t+h or setting it in lua/chadrc.lua) I get a lot of errors and the theme does not switch.

**To Reproduce**
1. Open neovim.
2a. Press `space + t + h` and select everforest.
2b. Open the lua/chadrc.lua file and change the current theme to `everforest`.
3:. See error

**Expected behavior**
It probably should apply everforest to neovim.

**Screenshots**
Error if I try to change the theme with `space + t + h`
![image](https://user-images.githubusercontent.com/85619855/130306011-0796c9ee-5de4-480a-9a0d-6559afdf5052.png)
Error if I edit the configuration file manually.
![image](https://user-images.githubusercontent.com/85619855/130306035-41710c3b-bb75-4406-8644-c9873cd101ca.png)

**Desktop (please complete the following information):**
 - Operating System: Arch Linux
 - Terminal: Kitty
 - Version of Neovim: neovim 0.5.0-1

I apologize if this is the wrong place for this error.

**Comment by G-Rowell** [comment]
Hi @GiantGlint,

I've just tested and this may have been fixed.

Would you update, then verify whether this is fixed or not?

Thanks!
G

**Comment by G-Rowell** [comment]
Most likely the issue will be solved with `:PackerSync` to update plugins

**Comment by siduck76** [comment]
also its everforest , not evergreen lol

**Comment by GiantGlint** [comment]
It works, thanks for your help. I ran `:PackerSync` and all was good! Thankyou.
