### ISSUE TITLE
How to lock Terminal Window in Neovim to prevent accidental edits?

### ISSUE THREAD

**Issue by kervanaslan** [NvChad/NvChad#3134]
I am a new user and not very familiar with the terminology, but I will do my best to explain the problem.

Summary of the problem: When the terminal is in "Insert" mode and I click on one of the open file tabs (which I do frequently), the terminal disappears, and the file content appears within the terminal window.

Please see the screencast first : https://youtu.be/i3WLWNL_DY8

In this screencast, it can be seen that the classic `:term` command is used, but I am also experiencing the same problem when using `space+h`.

**Steps to reproduce**

Show tree : `space+e`

Insert a terminal in the bottom pane: `space+h`

Open two files by clicking in the tree view.

Click on the terminal and enter insert mode by pressing i.

Click on the file in the top pane that I opened previously.

Here’s the problem: The file content gets inserted into the terminal, and the terminal disappears.

As a result, how can I lock the terminal window, so it stays locked and can't be modified by any other actions?

**Comment by siduck** [comment]
this isnt a nvchad issue at all

**Comment by kervanaslan** [comment]
@siduck You're right, but I'm so new to NvChad and Neovim that I have no idea what could be causing this or where to seek help. Could you give me some suggestions?

**Comment by siduck** [comment]
because its normal in nvim.

you're focused on window which has terminal buffer, now if u open any other buffer for example

e filename 

then terminal buf will be replaced with new one


btw u can access hidden terminals in <leader>pt

**Comment by siduck** [comment]
use the winfixbuf option

**Comment by siduck** [comment]
```lua
local autocmd = vim.api.nvim_create_autocmd

autocmd("TermOpen", {
  callback = function(args)
    local win = vim.fn.bufwinid(args.buf)
    vim.wo[win].winfixbuf = true
  end
})
```
