### ISSUE TITLE
Cannot enable NvChad options

### ISSUE THREAD

**Issue by jasmcaus** [NvChad/NvChad#315]
**Describe the bug**
Just installed NvChad configs yesterday, and been trying to poke around with the settings. Out of the box, everything was super. I realized you also had further options for dashboard, treesitter, etc, so as mentioned in the `lua/chadrc.lua` file, in the *plugin_status* area, I've set all the "true" values to "false" so as to enable all of the options. However, when I try to `:PackerSync` or `:PackerCompile`, I run into the following error (ignore the *Failed update*, my internet is lazy)

![image](https://user-images.githubusercontent.com/61184127/130310234-3bc790ff-ab6e-4c3c-a7d9-f59559ca5995.png)

While this says it's a `packer.nvim` issue, I know the error boils down to the way something is handled in `lua/pluginList.lua`. 
Admittedly, I'm new to Lua, so I wasn't able to find anything useful. I don't think this has happened with anyone else so far, so I'm curious why this NVim is yelling at me.

**To Reproduce**
1. Go to `lua/chadrc.lua`
2. Set `true` to `false` in `plugin_status`
3. Run `:PackerSync` or `:PackerCompile`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Kali Linux
 - Terminal: qterminal
 - Version of Neovim: NVIM v0.6.0-dev+162-g2ae9ff128

**Additional context**
Note that this error happens regardless of whether I change even one pluginStatus to `false`. The only plugin that seems to work  after setting to `false` without throwing an error is the `lua/dashboard.lua`.

**Comment by G-Rowell** [comment]
Hi, looking into this now

**Comment by G-Rowell** [comment]
Hey there @jasmcaus,

so

> in the plugin_status area, I've set all the "true" values to "false" so as to enable all of the options.

In the lines above there is a comment:
```
-- enable and disable plugins (false for disable)
M.plugin_status = {
```

I think you have a misconception regarding how to enable & disable plugins.
`false` will disable a plugin in NvChad,

`true` will enable them.

As to the error, make sure you run `:PackerSync`,
the likely issue is that you are removing/disabling plugins that are required for other plugins to work.

Eg. `A needs B`, **disable B, but enable A**, `error caused`

**Comment by G-Rowell** [comment]
Can you try to change the values back?
I think clearing this up will probably solve your problem?

Let me know what happens, :smile: 

G

**Comment by jasmcaus** [comment]
@G-Rowell, thanks for the update! 
That was confusing because I had this in my recent fork of NvChad:
```
-- enable and disable plugins (true for disable)
```
as opposed to `false for disable`.

This is fixed now. Thank you!
