### ISSUE TITLE
Idea: Opening a file buffer cd's nvim to its location

### ISSUE THREAD

**Issue by HoolaBoola** [NvChad/NvChad#319]
By default, opening NvimTree while editing a file deep in your filesystem often opens the view from the home folder (`~`)

Adding the following line to, for example, `options.lua` causes the current nvim window to `cd` into the folder the file is located in

`vim.cmd [[ autocmd BufEnter * if &buftype != "terminal" | lcd %:p:h | endif ]]`

The vim command consists of:
- `autocmd` to launch the command on `BufEnter` events
- `if &buftype != "terminal"` checks that the buffer is not a terminal (would cause an error text when entering a term buffer)
- `lcd %:p:h` changes the working directory of the current window (not others) to change to the directory of the current file

This command could also be just entered to the user configuration file `chadrc.lua`, like I've done, but I wonder if it would be a good idea to include that by default (or commented out in the default configuration)

**Comment by siduck76** [comment]
Thanks for this @HoolaBoola
