### ISSUE TITLE
Dotfile request

### ISSUE THREAD

**Issue by diogox** [NvChad/NvChad#320]
Not related to the project, but I can't resist asking for this [bar's](https://raw.githubusercontent.com/siduck76/dotfiles/master/rice%20flex/dashboard-nvim.png) dotfiles, if possible :pray:

**Comment by Mangeshrex** [comment]
just the bar? you can get here = github.com/siduck76/dotfiles

**Comment by diogox** [comment]
Thank you, I appreciate it! :raised_hands:
