### ISSUE TITLE
Yellow color from the one-light theme is not readable

### ISSUE THREAD

**Issue by Simre1** [NvChad/NvChad#322]
When using the one-light theme, text colored in yellow is unreadable.

![one_light](https://user-images.githubusercontent.com/9306729/130331153-7c484bb2-abc1-4b04-abb8-6acefb75cdc4.png)

I am using the current version of NvChad along with nvim nightly 0.6.

**Comment by siduck76** [comment]
@Simre1 https://github.com/NvChad/nvim-base16.lua/commit/de110d2ca629fe71a6bd3d454d4ab68511f0a038 , Do :PackerSync
