### ISSUE TITLE
"Some plugin change completeopt on insert mode: Last set from anonymous :source!" error while typing in insert mode

### ISSUE THREAD

**Issue by Um1aut** [NvChad/NvChad#323]
![image](https://user-images.githubusercontent.com/80593546/130332260-a07a0e87-024d-4dab-952e-432de3933430.png)
Just while using clear nvchad

**Comment by siduck76** [comment]
Check options.lua and remove the line with completeopt

**Comment by Um1aut** [comment]
> Check options.lua and remove the line with completeopt

![image](https://user-images.githubusercontent.com/80593546/130332563-6e513078-3c5a-490f-86f9-03c747df77db.png)
The same. Btw appears after typing something after ;

**Comment by siduck76** [comment]
I wouldn't suggest using coc in nvchad unless you know what you're doing.

**Comment by Um1aut** [comment]
> I wouldn't suggest using coc in nvchad unless you know what you're doing.

yeah, so how to disable coc?

**Comment by siduck76** [comment]
> > I wouldn't suggest using coc in nvchad unless you know what you're doing.
> 
> yeah, so how to disable coc?

We don't have that in our config  , use latest NvChad config lul

**Comment by Um1aut** [comment]
> > > I wouldn't suggest using coc in nvchad unless you know what you're doing.
> > 
> > 
> > yeah, so how to disable coc?
> 
> We don't have that in our config , use latest NvChad config lul

btw I am using it

**Comment by siduck76** [comment]
> > > > I wouldn't suggest using coc in nvchad unless you know what you're doing.
> > > 
> > > 
> > > yeah, so how to disable coc?
> > 
> > 
> > We don't have that in our config , use latest NvChad config lul
> 
> btw I am already using it

Oh , but we don't have Coc.nvim , so remove it the way you installed.

**Comment by Um1aut** [comment]
> > > > > I wouldn't suggest using coc in nvchad unless you know what you're doing.
> > > > 
> > > > 
> > > > yeah, so how to disable coc?
> > > 
> > > 
> > > We don't have that in our config , use latest NvChad config lul
> > 
> > 
> > btw I am already using it
> 
> Oh , but we don't have Coc.nvim , so remove it the way you installed.
lmao, I didn't install something

**Comment by Um1aut** [comment]
I just used clear nvchad

**Comment by Um1aut** [comment]
I think the best way is just to turn off the errors lmao

**Comment by siduck76** [comment]
> I just used clear nvchad

yes we don't have coc.nvim lol , you added it so remove it .

**Comment by Um1aut** [comment]
> > I just used clear nvchad
> 
> yes we don't have coc.nvim lol , you added it so remove it .

Lol, I just followed the setup instruction, that's it, I didn't add something in the .config/nvim directory)
![image](https://user-images.githubusercontent.com/80593546/130348337-2ce101bf-1c23-4055-ab07-21b49e6f8af3.png)

**Comment by Um1aut** [comment]
maybe some vim plugins and nvim are in conflict

**Comment by Um1aut** [comment]
cause I use both of them

**Comment by siduck76** [comment]
> cause I use both of them

no , you need to remove the completopt line from options.lua and compe so coc would work or just remove coc.nvim lol

**Comment by Um1aut** [comment]
> > cause I use both of them
> 
> no , you need to remove the completopt line from options.lua and compe so coc would work or just remove coc.nvim lol

How much time I need to say you that I didn't install coc.nvim and removed this line
![image](https://user-images.githubusercontent.com/80593546/130349795-85126864-7657-47cf-803c-eca950855053.png)

**Comment by Um1aut** [comment]
maybe lsp installed it by default

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/130349853-feb8b807-c8f5-49f5-a83d-9513321d02fc.png)

not at all

**Comment by siduck76** [comment]
clearly shows coc.nvim dude

**Comment by Um1aut** [comment]
> clearly shows coc.nvim dude

bruh I swear god that just cloned and packed all your plugins, installed lsp and ts(https://nvchad.netlify.app/getting-started/post-install/) and that's all.

**Comment by G-Rowell** [comment]
@Um1aut 

Have you ever used Vim or NeoVim before?

We're trying to help & debug this issue, and the current problem is that we can't understand how you are getting this error if `coc.nvim` is not installed.

Can you tell me the output of these commands please:
- enter the `cd ~/.config/nvim` dir
- update the git repo `git fetch --all`
- `git rev-list HEAD | head -1`
  - output of this please!
and

- `git diff origin/HEAD > diffOut.txt`
  - (and upload this file ofc).

**Comment by Um1aut** [comment]
> @Um1aut
> 
> Have you ever used Vim or NeoVim before?
> 
> We're trying to help & debug this issue, and the current problem is that we can't understand how you are getting this error if `coc.nvim` is not installed.
> 
> Can you tell me the output of these commands please:
> 
>     * enter the `cd ~/.config/nvim` dir
> 
>     * update the git repo `git fetch --all`
> 
>     * `git rev-list HEAD | head -1`
>       
>       * output of this please!
> 
> 
>     * `git diff origin/HEAD > diffOut.txt`
>       
>       * (and upload this file ofc).
> 
> 
>     * upload of `~/.cache/nvim/packer.nvim.log`
> 
> 
> ### These will greatly help us with debugging this for you, though we all have limited time due to uni exams.
> 
> G
![image](https://user-images.githubusercontent.com/80593546/130350353-aaff8f07-e283-467b-960a-a3feb94a16b4.png)

**Comment by Um1aut** [comment]
![image](https://user-images.githubusercontent.com/80593546/130350368-3009b154-2b5c-4e5b-b770-3e1d1828d44e.png)

**Comment by Um1aut** [comment]
and diffout is clear

**Comment by G-Rowell** [comment]
Thank you, looking into this

**Comment by G-Rowell** [comment]
Can you run in NeoVim
-  `:CocInfo`
- `:checkhealth`

And show the outputs here @Um1aut

**Comment by Um1aut** [comment]
![image](https://user-images.githubusercontent.com/80593546/130350944-f2458ca1-7a38-42c7-a5df-e657045d28ff.png)
![image](https://user-images.githubusercontent.com/80593546/130350987-01fe580c-56fc-441f-8f40-324896ae696a.png)

**Comment by siduck76** [comment]
this clearly shows that coc.nvim is installed , remove it.

**Comment by G-Rowell** [comment]
I know this must be pretty frustrating, 
I have one last easy one. I'll for sure have enough info after this to test myself

In NeoVim:
`:PackerSync`

The upload the `~/.cache/nvim/packer.nvim.log` file again.

**Comment by G-Rowell** [comment]
I think you need to try 

`rm -r /usr/share/nvim/runtime/pack/coc`

This should hopefully fix

**Comment by Um1aut** [comment]
> I think you need to try
> 
> `rm -r /usr/share/nvim/runtime/pack/coc`
> 
> This should hopefully fix

thanks)

**Comment by G-Rowell** [comment]
Let me know if that fixed it :)

**Comment by Um1aut** [comment]
> Let me know if that fixed it :)

Ofc that fixed because of I have just deleted coc that alerted the problem
