### ISSUE TITLE
Input lagging and displacing when nvim-compe is active

### ISSUE THREAD

**Issue by MMNN321** [NvChad/NvChad#324]
**Describe the bug**
Input is lagging and displacing when nvim-compe's completion menu is active and switching from input to normal mode back to input mode

**To Reproduce**
1. Install NvChad and a language server (i tested it with typescript and rust; The slower the language server, the bigger the effect)
2. Open a file that starts the language server
3. Type something until you see the completion menu
4. Press `<Escape>` and `a` and write new characters

**Expected behavior**
I expected the same experience like before when I was in insert mode

**Screenshots**
![](https://i.imgur.com/l5vqaEU.gif)

**Desktop:**
 - OS: Arch Linux
 - Terminal: kitty
 - Version: nvim-git: v0.6.0-dev+164-g50b30de20

**Additional context**
This effect is active as long as the cursor stays in that line.
After leaving the line, it displays the content correctly.

**Comment by amistyrain** [comment]
me too

**Comment by MMNN321** [comment]
I found my problem. Neovim 0.5 works as it should. It seems, that this config conflicts with version 0.6 (minimal test config with nvim-compe is working on 0.6).

**Comment by siduck76** [comment]
oh yes , btw why using 0.6?

**Comment by MMNN321** [comment]
I had nvim-git 0.5-beta installed but packer was complaining. I then upgraded neovim to the newest release
