### ISSUE TITLE
Packer compile happening on every startup

### ISSUE THREAD

**Issue by Reptarsrage** [NvChad/NvChad#325]
**Describe the bug**
Every time Neovim is opened, packer runs some code and prompts for the user to restart neovim.

**To Reproduce**
1. This happens every time the program is launched

**Expected behavior**
I would expect that this only occurs automatically once, when the program is first launched. Having to interact with this pop-up each time the program is launched is frustrating.

**Screenshots**
![image](https://user-images.githubusercontent.com/4110575/130334391-6359a8f0-751e-49f4-8f93-1988a1b8b04c.png)

**Desktop (please complete the following information):**
 - Microsoft Windows 10 Pro 10.0.19043 Build 19043
 - neovim 0.6.0-beta

**Comment by siduck76** [comment]
When was the last time you updated nvchad config?

**Comment by buip** [comment]
it happens to me too!

**Comment by Reptarsrage** [comment]
I was on commit `6206a9e` (2 days ago), but I just pulled  `44ae017` (75 minutes ago) and am having the same issue.

I cleared out the old plugins & data folders (`~\AppData\Local\nvim`, `~\AppData\Local\nvim-data`), and ran `nvim +'hi NormalFloat guibg=#1e222a' +PackerSync` as per the setup instructions [here](https://nvchad.netlify.app/getting-started/setup/). After that, every time nvim is opened it gives me the above prompt.

**Comment by barungh** [comment]
It is compiling telescope media plugin on every launch

![image](https://user-images.githubusercontent.com/12285528/130349638-b97fa657-73f8-4c4b-a1b0-dc398ebb506c.png)

**Comment by Akianonymus** [comment]
disable media extension from config, restart neovim and PackerSync

**Comment by siduck76** [comment]
oh yea telescope media wont work for windows , disable it

**Comment by Akianonymus** [comment]
I will add a check if the system has uzerberg, then try to load media files extension

**Comment by barungh** [comment]
Done , but after that packer is compiling/syncing/updating on every launch, How do I stop that ?

![image](https://user-images.githubusercontent.com/12285528/130350367-f042ac34-3afd-4ff6-8145-2ebcc0d68f2e.png)

**Comment by Akianonymus** [comment]
Update your local repo and try again, i have pushed some fixes. May help

**Comment by barungh** [comment]
> Update your local repo and try again, i have pushed some fixes. May help

Yes it solved the problem ( compilation on every launch )

but, 

now, `<leader>ff`     invokes fetching of telescope fzf plugin , nvchad/extensions, then 
Telescope stops working

with previous releases `:Telescope find_files` was working great

**Comment by Akianonymus** [comment]
probably telescope fzf extension if not working

**Comment by barungh** [comment]
> probably telescope fzf extension if not working

but fzf works fine on my Powershell ( may be this info will help you )

![image](https://user-images.githubusercontent.com/12285528/130358492-887011b0-ded9-4933-8071-b7ac6ad9fd9e.png)

**Comment by Akianonymus** [comment]
It's a different thing

https://github.com/nvim-telescope/telescope-fzf-native.nvim

Anyway, try this, it will give use more info

replace this code
```
if not pcall(function()
   for _, ext in ipairs(extensions) do
      telescope.load_extension(ext)
   end
end) then
   -- This should only trigger when in need of PackerSync, so better do it
   print "After completion of PackerCompile, restart neovim."
   -- Trigger packer compile on PackerComplete, so it properly waits for PackerSync
   vim.cmd 'autocmd User PackerComplete ++once lua print "Waiting for PackerCompile.." require("packer").compile()'
   vim.cmd 'autocmd User PackerCompileDone ++once echo "Packer Compile done, restart neovim."'
   require "plugins"
   loadstring('require("packer").update(' .. packer_repos .. ")")()
end
``` 

with

```
for _, ext in ipairs(extensions) do
      telescope.load_extension(ext)
   end
```


in lua/plugins/configs/telescope.lua

**Comment by barungh** [comment]
![image](https://user-images.githubusercontent.com/12285528/130359504-df29ad39-e104-4d7e-8cbf-a99d8423cf27.png)


It produces this error , after above configuration, then,
it opens up the telescope file search window

**Comment by Akianonymus** [comment]
It cannot find the fzf module, probably why not working.

Remove it from telescope.lua

about fixing this properly, do you have make installed and available as a command ?

try making binaries for this repo externally andd see if that works

https://github.com/nvim-telescope/telescope-fzf-native.nvim

**Comment by Reptarsrage** [comment]
Thanks @Akianonymus, disabling "the nvim-telescope/telescope-media-files.nvim" plugin fixed the issue. FYI you can install the fzf command line tool on windows via chocolatey: https://community.chocolatey.org/packages/fzf

**Comment by G-Rowell** [comment]
Glad it's fixed!
Aki has been doing some amazing work.


Closing, reopen if need be
G

**Comment by barungh** [comment]
> It cannot find the fzf module, probably why not working.
> 
> Remove it from telescope.lua
> 
> about fixing this properly, do you have make installed and available as a command ?
> 
> try making binaries for this repo externally andd see if that works
> 
> https://github.com/nvim-telescope/telescope-fzf-native.nvim

I installed make in my windows machine , `choco install make`
and, 
after that,
Telescope works fine, fuzzy finding seems to work,
but when I press enter on any file, i get this error

```
recovery impossible lua ...\packer\opt\telescope.nvim\lua\telescope\actions\set.lua:134: Vim(edit):E303: Unable to open swap file for "lib\main.dart  
```

any help regarding this ? 

I am very much set up on my windows machine 🙏 

![image](https://user-images.githubusercontent.com/12285528/130393972-4a60d8f0-d0a8-4af7-9ef2-56d8189785e8.png)

**Comment by OnePieceJoker** [comment]
> > Update your local repo and try again, i have pushed some fixes. May help
> 
> Yes it solved the problem ( compilation on every launch )
> 
> but,
> 
> now, `<leader>ff` invokes fetching of telescope fzf plugin , nvchad/extensions, then
> Telescope stops working
> 
> with previous releases `:Telescope find_files` was working great

I'm also having this problem and when I use `:Telescope find_files` the problem persists

**Comment by buip** [comment]
I also still have same issue even after disabling the plugin

**Comment by G-Rowell** [comment]
@barungh @buip @OnePieceJoker 

Sorry for missing this,
in the future I'd welcome you to use the `reopen and comment` button, so that this appears in the main issue list.
(otherwise we won't see it, like what's just happened!!)

I think the current plan is to remove `Telescope-media` as it's not very useful anyway.
This should solve this problem.
@siduck76 


G

**Comment by siduck76** [comment]
Yea it will be disabled by default now , ugghh windowsss :c

**Comment by siduck76** [comment]
Yea it will be disabled by default now , ugghh windowsss :c

**Comment by siduck76** [comment]
> I also still have same issue even after disabling the plugin

I doubt if telescope-fzf-native with make is causing this issue.

**Comment by ashincoder** [comment]
@Akianonymus @G-Rowell @siduck76 I do have the same error.

https://user-images.githubusercontent.com/83629316/130804682-1b4e67e4-86a4-40bb-b4de-d163f825b9c5.mp4

**Comment by siduck76** [comment]
@ashincoder do you still have this error :rofl:

**Comment by siduck76** [comment]
> > > Update your local repo and try again, i have pushed some fixes. May help
> > 
> > 
> > Yes it solved the problem ( compilation on every launch )
> > but,
> > now, `<leader>ff` invokes fetching of telescope fzf plugin , nvchad/extensions, then
> > Telescope stops working
> > with previous releases `:Telescope find_files` was working great
> 
> I'm also having this problem.
> 
> I tried to disable the plugin, but the configuration did not work.
> 
> **Desktop (please complete the following information):**
> 
> * NVIM v0.5.0
> * macOS Big Sur Version 11.2.3
> 
> ![image](https://user-images.githubusercontent.com/25676220/130553780-f58ade3b-46fd-41f2-bc7c-001776cf7935.png)

after disabling , you need to do packersync to make the changes

**Comment by vpeopleonatank** [comment]
I 'm still facing this issue like @ashincoder

**Comment by siduck76** [comment]
> I 'm still facing this issue like @ashincoder

which OS?

**Comment by vpeopleonatank** [comment]
> > I 'm still facing this issue like @ashincoder
> 
> which OS?

Pop-os 20.04

**Comment by siduck76** [comment]
> > > I 'm still facing this issue like @ashincoder
> > 
> > 
> > which OS?
> 
> Pop-os 20.04

neovim version? show nvim -v

**Comment by vpeopleonatank** [comment]
> > > > I 'm still facing this issue like @ashincoder
> > > 
> > > 
> > > which OS?
> > 
> > 
> > Pop-os 20.04
> 
> neovim version? show nvim -v

Here is my nvim -v
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck76** [comment]
> > > > > I 'm still facing this issue like @ashincoder
> > > > 
> > > > 
> > > > which OS?
> > > 
> > > 
> > > Pop-os 20.04
> > 
> > 
> > neovim version? show nvim -v
> 
> Here is my nvim -v
> 
> ```
> NVIM v0.5.0
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
> Compiled by runner@fv-az242-526
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "
> /home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```

could you show me a video in which you execute the following commands : 

```
rm -rf ~/.config/cache/nvim
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim

git clone https://github.com/NvChad/NvChad ~/.config/nvim && nvim +PackerSync
```

**Comment by vpeopleonatank** [comment]
I still face this issue :D

https://user-images.githubusercontent.com/30976876/131276071-96a2c5e4-8503-42df-817c-7f60e10e1581.mp4

**Comment by siduck76** [comment]
can you try 0.5 appimage or binary from nvim releases?

**Comment by barungh** [comment]
I am using Nvchad on my windows machine and also Arch Linux machine ,

for Windows machine , I disabled Telescope plugins , and added a forked version of [LspInstaller](https://github.com/nazo6/lspinstall.nvim) 
which installs the Language servers nicely

![image](https://user-images.githubusercontent.com/12285528/131277894-ae53d3d1-bec4-4b93-be3a-f8988d35502a.png)

Now I can work on my Windows machine

I tweaked few key bindings though

What I disabled:

![image](https://user-images.githubusercontent.com/12285528/131278214-f0507fa7-0421-4163-a81b-d48c52d0b094.png)

@vpeopleonatank 

I was getting the same error , until I installed `make` on my Windows machine 
`choco install make`  on Windows powershell

so whatever OS you are using make sure you have utilities like `make` C-compiler etc.

like 
`$ sudo pacman -S base-devel` for Arch based linux

**Comment by vpeopleonatank** [comment]
> can you try 0.5 appimage or binary from nvim releases?

I use latest release 0.5 appimage here https://github.com/neovim/neovim/releases/download/v0.5.0/nvim.appimage

**Comment by siduck76** [comment]
@vpeopleonatank I doubt if make properly works on your system :c

**Comment by vpeopleonatank** [comment]
> @vpeopleonatank I doubt if make properly works on your system :c

`make` exists on my system :+1: 
![image](https://user-images.githubusercontent.com/30976876/131281569-b7857779-fe7a-4702-893b-69543a6b0f19.png)

**Comment by ashincoder** [comment]
It happens sometime for me.

**Comment by siduck76** [comment]
@vpeopleonatank go to ~/.local/share/nvim/site/pack/packer/start/telescope-fzf-native.nvim/ 

and delete the build dir , run make and show me the output

**Comment by siduck76** [comment]
@vpeopleonatank can you check now?

**Comment by vpeopleonatank** [comment]
After remove and install nvchad again, this issue has gone. Thank you.

**Comment by siduck76** [comment]
> After remove and install nvchad again, this issue has gone. Thank you.

Thanks to @Akianonymus
