### ISSUE TITLE
Folder glyphs

### ISSUE THREAD

**Issue by meaz** [NvChad/NvChad#327]
I've downloaded a nerd font as requested, but the folder icon is messed up for some reasons. I've tried to get some other font, but it is still the same. Any idea?

![vim](https://user-images.githubusercontent.com/13604424/130337615-24cbbd98-4289-4135-b179-b590de7fd70b.png)

**Comment by siduck76** [comment]
Just downloading won't work , set your terminal font as that nerdfont .

**Comment by siduck76** [comment]
If its alacritty then take reference from this config https://paste.sh/G5RP3sQm#QPvbAX8BibYrQ-umZh29PKe_

**Comment by G-Rowell** [comment]
@siduck76 

That weblink is broken for me
`Decryption failed (Error: Malformed UTF-8 data)`

Though I do agree that the most likely issue is that the terminal emulator font is not set.

**Comment by siduck76** [comment]
updated link https://paste.sh/0XeNd1CQ#-lNJAwPYiNX4etSgfAbRLygo
