### ISSUE TITLE
Enabling NVimTree by default?

### ISSUE THREAD

**Issue by jasmcaus** [NvChad/NvChad#328]
**Describe the bug**
This is not a bug per se, but I was wondering if, like the dashboard, one could enable Nvimtree to open when `nvim .` is run in the terminal?

**Comment by siduck76** [comment]
g.nvim_tree_auto_open = 0 to 1 in nvimtree.lua 

and remove the cmd line of nvimtree in pluginlist

**Comment by MeiramSh** [comment]
@siduck76  I had the same issue, so I tried to do what you suggested here.
But I didn't have pluginList.lua file, so I thought that I should edit init.lua file inside plugins folder instead. After I commented out cmd line of nvimtree in init.lua, nvimtree started to work as expected (e.g. Nvimtree open whenever I open the directory with it). However, after that nvim stopped to display proper Icons for files.
![image](https://user-images.githubusercontent.com/71583853/131228785-4de6c2bc-8743-4650-90c4-41acec145bd1.png)
Before the changes you suggested, icons were like this
![image](https://user-images.githubusercontent.com/71583853/131228897-50c3668a-7943-4dca-b0e5-6637fdd62713.png)

**Comment by siduck76** [comment]
@MeiramSh oh thats probably cuz webdevicons is lazy loaded and nvimtree isnt . so load nvimtree after webdevicons 

after = "nvim-web-devicons"

(put this in the packer config of nvimtree)

**Comment by MeiramSh** [comment]
@siduck76 Awesome, that fixed everything

**Comment by harry-xiaomi** [comment]
Auto open does not work if I add `after = "nvim-web-devicons"`, but otherwise I would not get the right icons. Anything I did wrong?

```diff
diff --git a/lua/plugins/configs/nvimtree.lua b/lua/plugins/configs/nvimtree.lua
index 4387569..44c4d6e 100644
--- a/lua/plugins/configs/nvimtree.lua
+++ b/lua/plugins/configs/nvimtree.lua
@@ -12,7 +12,7 @@ g.nvim_tree_add_trailing = 0 -- append a trailing slash to folder names
 g.nvim_tree_allow_resize = 1
 g.nvim_tree_auto_close = 0 -- closes tree when it's the last window
 g.nvim_tree_auto_ignore_ft = { "dashboard" } -- don't open tree on specific fiypes.
-g.nvim_tree_auto_open = 0
+g.nvim_tree_auto_open = 1
 g.nvim_tree_disable_netrw = 1
 g.nvim_tree_follow = 1
 g.nvim_tree_git_hl = 1
diff --git a/lua/plugins/init.lua b/lua/plugins/init.lua
index ff4c3a2..5b370ef 100644
--- a/lua/plugins/init.lua
+++ b/lua/plugins/init.lua
@@ -273,13 +273,14 @@ return packer.startup(function()
    -- file managing , picker etc
    use {
       "kyazdani42/nvim-tree.lua",
-      cmd = { "NvimTreeToggle", "NvimTreeFocus" },
+      opt = false,
       config = function()
          require "plugins.configs.nvimtree"
       end,
       setup = function()
          require("core.mappings").nvimtree()
       end,
+      after = "nvim-web-devicons",
    }

    use {
```

**Comment by siduck76** [comment]
remove opt=false too , and do :PackerSync

**Comment by harry-xiaomi** [comment]
Same problem without `opt = false`.

**Comment by siduck76** [comment]
dont open just "nvim" , do nvim . to see the tree auto-opened

**Comment by harry-xiaomi** [comment]
That's it. Thank you!

**Comment by Diego77777777777** [comment]
****

**Comment by vntrungld** [comment]
How can we make nvim tree open when we don't specify the filename?

**Comment by siduck76** [comment]
> How can we make nvim tree open when we don't specify the filename?

nvim .

**Comment by vntrungld** [comment]
In `NERD Tree`, we suggest this code to pre-open nvim when we don't specify the filename:
```vim
" Start NERDTree when Vim is started without file arguments.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | NERDTree | endif
```
I wonder how we can do it in NVimTree, I will look around

**Comment by adamwojt** [comment]
Having issue with both `nvim` and `nvim .`. I have `auto_open` option enabled. Any ideas?

**Comment by siduck** [comment]
> Having issue with both `nvim` and `nvim .`. I have `auto_open` option enabled. Any ideas?

remove cmd line from nvimtree plugin's definition in packer config

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/142745965-f45f03d3-b619-4369-a151-a362817847a9.png)
and do packercompile

**Comment by siduck** [comment]
lemme know if that works , if yes then I'll add an option for this in the chadrc

**Comment by adamwojt** [comment]
@siduck it works, thanks. strangely `nvim .` makes it focus on tree and it works well
 but when opening different folder, ex. `nvim folder` the tree is not focused:
![image](https://user-images.githubusercontent.com/45100954/142747147-30009649-2306-41f7-8235-564d645654d9.png)
