### ISSUE TITLE
Try in docker

### ISSUE THREAD

**Issue by V1RE** [NvChad/NvChad#330]
When trying out configs such as NvChad, I always spin up a new docker container as to not mess with my own configuration.

As an example, [zsh4humans](https://github.com/romkatv/zsh4humans/#try-it-in-docker) has this docker section so you can easily try it out without worrying about making backups and installing the correct dependencies.

**Comment by G-Rowell** [comment]
I this a suggestion for NvChad to incorporate?

I'm personally not a huge fan of the all too common curl, into sh: `sh -c "$(curl <script url>)` 

Furthermore, for the most part users can `mv ~/.config/nvim ~/.config/NeovimBackup`, as faster method for most cases.

I'm of course still open to a discussion on this!
There are other members that may have a different view point on this

**Comment by V1RE** [comment]
Here's a [demo](https://asciinema.org/a/RxE9FOZg1p8AgEQkAhPb6tGMj) showcasing how you can quickly try out NvChad by just pasting a command.

As you can see in the demo, i screwed my personal config up by moving it, trying out nvchad, removing nvchad and copying my old config back. Using docker would ensure you wont accidentally screw your old config up.

I've created a PR here #333

**Comment by siduck76** [comment]
merged the pr!
