### ISSUE TITLE
'mappings' has been deprecated please refer to the BufferLineGoToBuffer section of the README

### ISSUE THREAD

**Issue by jasmcaus** [NvChad/NvChad#332]
**Describe the bug**
Got the following bug whenever I try to open nvim (using NvChad configs)
```
'mappings' has been deprecated please refer to the BufferLineGoToBuffer section of the README
```

**Desktop (please complete the following information):**
 - Operating System: Kali
 - Terminal: qterminal
 - Version of Neovim: v0.6.0-dev+166-g8331cd13c

**Additional context**

**Comment by siduck76** [comment]
@jasmcaus update your nvchad config !

**Comment by jasmcaus** [comment]
Tbh, this was the config I pulled from here yesterday. It worked fine then, but started yelling at me today

**Comment by siduck76** [comment]
> Tbh, this was the config I pulled from here yesterday. It worked fine then, but started yelling at me today

do packersync then , mappings has already been removed from bufferline config , please re-check

**Comment by G-Rowell** [comment]
@jasmcaus,

We've currently being doing some major re-structuring of NvChad, to hopefully improve it for everyone!

Big credit to Akianonymus for the work

Try run `:PackerSync` as SiDuck said, then let us know if this issue still persists.


G

**Comment by jasmcaus** [comment]
Okay, I've switched to the latest config. Love the file structure! 
Also, quick question: does running :PackerSync update nvchad configs as well?

**Comment by siduck76** [comment]
> Okay, I've switched to the latest config. Love the file structure!
> Also, quick question: does running :PackerSync update nvchad configs as well?

No , it compiles whole nvchad config into one! So if you make any significant changes like change in the packer conf  , you do packersync!
