### ISSUE TITLE
Help needed to setup user defined plugin - Flutter-tools

### ISSUE THREAD

**Issue by barungh** [NvChad/NvChad#335]
**Describe the bug**
[Flutter-tools](https://github.com/akinsho/flutter-tools.nvim) not working

What am I doing wrong here ?

```
use {
  'akinsho/flutter-tools.nvim', 
  after = 'nvim-lua/plenary.nvim',
  config = function()
    require("flutter-tools").setup({}) -- use defaults
  end
}
```
![image](https://user-images.githubusercontent.com/12285528/130360944-2771ca29-5480-4fa9-8895-e2bfb4ca7ea0.png)

**Comment by siduck76** [comment]
wym not working?

**Comment by G-Rowell** [comment]
Hi @barungh,

I'm not sure if the NvChad team can support you too much here,
as this problem isn't with NvChad, but more with your own plugin configuration.

Suggested resources:
- [Flutter tools README](https://github.com/akinsho/flutter-tools.nvim#flutter-toolsnvim)
- [Packer README](https://github.com/wbthomason/packer.nvim)

See this except from the Flutter README:
```
Installation

.....

or using packer.nvim

use {'akinsho/flutter-tools.nvim', requires = 'nvim-lua/plenary.nvim'}

This plugin depends on plenary.nvim, please make sure it is installed.
Warning

    flutter tools does not depend on nvim-lspconfig. The two can co-exist but please ensure you do NOT configure dartls using lspconfig. It will be automatically set up by this plugin instead.

    You might encounter issues using this plugin on the master channel of flutter.
```

We may be able to answer some questions, but we can't even replicate this as it's not NvChad.


G

**Comment by barungh** [comment]
It is working , 

![image](https://user-images.githubusercontent.com/12285528/130380338-f7186f40-2490-470d-ab28-fd70ab116784.png)

***What I did***
![image](https://user-images.githubusercontent.com/12285528/130380559-71cd5da1-f212-41d1-810b-a40ba847a249.png)

- created a flutter-tools.lua file inside nvim/lua/plugins/configs
- in nvim/lua/plugins/init.lua added these lines  

```
use {
  'akinsho/flutter-tools.nvim', 
  config = function()
    require "plugins.configs.flutter-tools"
  end,
}
```

**Comment by gheron772** [comment]
This setting refers to nvchad, flutter-tools.

```
["akinsho/flutter-tools.nvim"] = {
  requires = {{"nvim-lua/plenary.nvim"},},
  config = function()
    require("flutter-tools").setup()
  end,
},
```

**Comment by siduck** [comment]
> This setting refers to nvchad, flutter-tools.
> 
> ```
> ["akinsho/flutter-tools.nvim"] = {
>   requires = {{"nvim-lua/plenary.nvim"},},
>   config = function()
>     require("flutter-tools").setup()
>   end,
> },
> ```

```lua
["akinsho/flutter-tools.nvim"] = {
  after  = "plenary.nvim",
  config = function()
    require("flutter-tools").setup()
  end,
},
```

**Comment by gheron772** [comment]
> > This setting refers to nvchad, flutter-tools.
> > ```
> > ["akinsho/flutter-tools.nvim"] = {
> >   requires = {{"nvim-lua/plenary.nvim"},},
> >   config = function()
> >     require("flutter-tools").setup()
> >   end,
> > },
> > ```
> 
> ```lua
> ["akinsho/flutter-tools.nvim"] = {
>   after  = "plenary.nvim",
>   config = function()
>     require("flutter-tools").setup()
>   end,
> },
> ```

With 'after' config. failed to load

```bash
requires = {{"nvim-lua/plenary.nvim"},},
• flutter-tools.nvim
	url: "https://github.com/akinsho/flutter-tools.nvim"
	path:
	"~\AppData\Local\nvim-data\site\pack\packer\start\flutter-tools.nvim"
	opt: false

• plenary.nvim
	url: "https://github.com/nvim-lua/plenary.nvim"    
	path:    
	"~\AppData\Local\nvim-data\site\pack\packer\opt\plenary.nvim"    
	opt: true

after  = "plenary.nvim",
opt = false,
• flutter-tools.nvim (not loaded)
	url: "https://github.com/akinsho/flutter-tools.nvim"
	path:
	"~\AppData\Local\nvim-data\site\pack\packer\opt\flutter-tools.nvim"
	opt: true

• plenary.nvim (not loaded)     
	url: "https://github.com/nvim-lua/plenary.nvim"     
	path:     
	"~\AppData\Local\nvim-data\site\pack\packer\opt\plenary.nvim"     
	opt: true
```

**Comment by siduck** [comment]
ooh oops, i forgot we lazyload plenary on plenary module, so remove requires/after line itself
