### ISSUE TITLE
Lua is not installing

### ISSUE THREAD

**Issue by insidersbuilt** [NvChad/NvChad#337]
This is the error from lua lsp
![image](https://user-images.githubusercontent.com/87114084/130363282-1904d862-a397-47e4-816b-7c4d8fabac81.png)
and this is the error from ts lsp
![image](https://user-images.githubusercontent.com/87114084/130363878-90f50a4c-01ea-4134-bc4d-31af1a141f24.png)

i don't know lua lsp does not installs

**Comment by siduck76** [comment]
you sure , your internet connection is ok?

**Comment by insidersbuilt** [comment]
> you sure , your internet connection is ok?

yes

**Comment by G-Rowell** [comment]
Hi @insidersbuilt,

Can I confirm that you are trying to `:LspInstall lua`?

This issue does seem pretty weird, as it's correctly downloading a file, but not recognising the file as valid.

Can you run:
`:PackerSync`

Then, can you please provide the following:
- `git rev-list HEAD | head -1`
    output of this please!
- `git diff origin/HEAD > diffOut.txt`
    upload of this please if it outputs anything!
- upload of ~/.cache/nvim/packer.nvim.log
    (we'll save this debugging for the moment, just the first 2 please)

G

**Comment by insidersbuilt** [comment]
> Hi @insidersbuilt,
> 
> Can I confirm that you are trying to `:LspInstall lua`?
> 
> This issue does seem pretty weird, as it's correctly downloading a file, but not recognising the file as valid.
> 
> Can you run:
> `:PackerSync`
> 
> Then, can you please provide the following:
> 
> * `git rev-list HEAD | head -1`
>   output of this please!
> * `git diff origin/HEAD > diffOut.txt`
>   upload of this please if it outputs anything!
> * upload of ~/.cache/nvim/packer.nvim.log
>   (we'll save this debugging for the moment, just the first 2 please)
> 
> G

solved  using this script

mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions

npm install coc-emmet coc-css coc-html coc-tsserver --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod

**Comment by insidersbuilt** [comment]
> Hi @insidersbuilt,
> 
> Can I confirm that you are trying to `:LspInstall lua`?
> 
> This issue does seem pretty weird, as it's correctly downloading a file, but not recognising the file as valid.
> 
> Can you run:
> `:PackerSync`
> 
> Then, can you please provide the following:
> 
> * `git rev-list HEAD | head -1`
>   output of this please!
> * `git diff origin/HEAD > diffOut.txt`
>   upload of this please if it outputs anything!
> * upload of ~/.cache/nvim/packer.nvim.log
>   (we'll save this debugging for the moment, just the first 2 please)
> 
> G

yes at that time i was using :Lsp but then i switched to coc

**Comment by G-Rowell** [comment]
> solved using this script
