### ISSUE TITLE
can i install coc-css alongside the lsp because the lsp does not have a good support or completion for the --webkit 

### ISSUE THREAD

**Issue by insidersbuilt** [NvChad/NvChad#338]

**Comment by siduck76** [comment]
I doubt if compe and coc would conflict :l , either you have to remove lspconfig+compe to use coc or just use lspconfig+compe.

**Comment by siduck76** [comment]
@insidersbuilt show completions with both coc and nvim lsp  , I'll check with lspconfig devs on gitter
