### ISSUE TITLE
Reorganization broke things

### ISSUE THREAD

**Issue by IYake** [NvChad/NvChad#343]
**Describe the bug**
From the head a65368aed97ca843a4265077b2b9089c611f2c29 to commit 9ffddb6b524aaef2bc2b1b89f52875a452781908, I get the error

```
packer.nvim: Error running setup for nvim-bufferline.lua: [string "..."]:0: module 'mappings' not found:
^Ino field package.preload['mappings']
^Ino file './mappings.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/mappings.lua'
^Ino file '/usr/local/share/lua/5.1/mappings.lua'
^Ino file '/usr/local/share/lua/5.1/mappings/init.lua'
^Ino file '/usr/share/lua/5.1/mappings.lua'
^Ino file '/usr/share/lua/5.1/mappings/init.lua'
^Ino file '/home/me/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/mappings.lua'
^Ino file '/home/me/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/mappings/init.lua'
^Ino file '/home/me/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/mappings.lua'
^Ino file '/home/me/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/mappings/init.lua'
^Ino file './mappings.so'
^Ino file '/usr/local/lib/lua/5.1/mappings.so'
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/mappings.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```
But before 9ffddb6b524aaef2bc2b1b89f52875a452781908, the error isn't present. So I'm thinking reorganizing the files broke things.

**To Reproduce**
1. ```git checkout HEAD```
2. ```nvim```

**Desktop (please complete the following information):**
 - Operating System: Windows 10
 - Terminal: Windows Terminal with WSL
 - Version of Neovim: v0.6.0-dev

**Comment by IYake** [comment]
My bad... turns out I needed to run ```PackerUpdate``` first before updating nvchad. I removed packages I didn't want before so it seemed to be expecting those. Needing to remake/verify the Packer should either be automatically done or specified somewhere in the docs.

**Comment by G-Rowell** [comment]
Hi @IYake,

I've just tested this opening NeoVim on an up-to-date NvChad and I do not get any errors

Do you know if there is anything specific that causes this problem?

Can you run:
`:PackerSync`

Then, can you please provide the following:
- `git rev-list HEAD | head -1`
  output of this please!
- `git diff origin/HEAD > diffOut.txt`
  upload of this please if it outputs anything!
- ~~`upload of ~/.cache/nvim/packer.nvim.log`~~
  (we'll save this debugging for the moment, just the first 2 please)
  
  
  G

**Comment by IYake** [comment]
The git diff didn't output anything. But doing ```:PackerSync``` _did_ fix the issue. I had to hold enter until all these packer errors gave up and I could type it in. Thanks!

**Comment by G-Rowell** [comment]
Awesome, glad it's fixed :smile:
Have a good day!


G
