### ISSUE TITLE
Telescope media_files does not works

### ISSUE THREAD

**Issue by insidersbuilt** [NvChad/NvChad#344]
telescope media files does not works media files option is not available in the command line like 
:Telescope media 

completion is not available

**Comment by G-Rowell** [comment]
Hi @insidersbuilt,

Can you please provided the requested information when you created this issue:
- mainly what OS

Can you run:
`:PackerSync`

Then, can you please provide the following:
- `git rev-list HEAD | head -1`
  output of this please!
- `git diff origin/HEAD > diffOut.txt`
  upload of this please if it outputs anything!
- ~~`upload of ~/.cache/nvim/packer.nvim.log`~~
  (we'll save this debugging for the moment, just the first 2 please)


G

**Comment by insidersbuilt** [comment]
It does not shows anything it does not opens the telescope media

**Comment by insidersbuilt** [comment]
> It does not shows anything it does not opens the telescope media

i am new to nvim and also the github so i don't know what you are talking about

**Comment by G-Rowell** [comment]
So

1. What OS are you using?
2. Run `git rev-list HEAD | head -1` and show me the output
3. `git diff origin/HEAD > diffOut.txt` and show me the output


Without these I can't help or even start to debug your issue :smile:

G

**Comment by insidersbuilt** [comment]
> So
> 
> 1. What OS are you using?
> 2. Run `git rev-list HEAD | head -1` and show me the output
> 3. `git diff origin/HEAD > diffOut.txt` and show me the output
> 
> Without these I can't help or even start to debug your issue 
> 
> G
![image](https://user-images.githubusercontent.com/87114084/130385731-56f194cd-5455-4e23-a510-e9503503a823.png)
I don't have the media_files option here the last version i was using had that

**Comment by G-Rowell** [comment]
Hi @insidersbuilt, as my previous comment, **I need to know the following otherwise I cannot help**

1.    What OS are you using?
2.    Run `git rev-list HEAD | head -1` and show me the output
3.    Run `git diff origin/HEAD` and show me the output

`Without these I can't help or even start to debug your issue`

If you don't want to provide these, we can agree to close this issue?
