### ISSUE TITLE
In the NvChad the telescope search bar problem 

### ISSUE THREAD

**Issue by insidersbuilt** [NvChad/NvChad#346]
in the telescope the search bar is at the top but the pointer on the files is at the bottom which is kind of annoying the pointer should be on the top below the telescope search bar so in the telescope settings you should change the descending to asending to remove the conflict 

i just wanted to share that so that that should be on the master branch 

Thanks!

**Comment by siduck76** [comment]
I think you need to check telescope config

**Comment by chakrihacker** [comment]
Check if you installed ripgrep or not

**Comment by G-Rowell** [comment]
I think, if I understand @insidersbuilt correctly,

[they want this option changed to `ascending`](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/telescope.lua#L22), I've tried it myself and seems to do what insider is trying to describe.

I think it's a reasonable change imo, I'd be slightly in favour

@siduck76
