### ISSUE TITLE
some problems in code completeion

### ISSUE THREAD

**Issue by Marcotsept** [NvChad/NvChad#348]
First, How can I auto-complete with the first suggestion, when I type in  "tab" 

<img width="751" alt="Screenshot 2021-08-23 at 15 39 57" src="https://user-images.githubusercontent.com/17099973/130409824-9c48f2c4-527b-4f0b-b987-7cb36e881056.png">

Second,  when I type in "Ctrl + n" cannot get a correct suggestion. I expected the result is like the first question suggestion list.

<img width="573" alt="Screenshot 2021-08-23 at 14 46 01" src="https://user-images.githubusercontent.com/17099973/130410182-837b1db8-4372-447e-a4bc-633dcf5a6ee2.png">

these may be my approach problems, please to the help me. Thanks

**Comment by G-Rowell** [comment]
Hi @Marcotsept 

1. Press `<enter>` to select an entry from the drop down list
2. `<CNTL> + n` is for opening / closing the NerdTree on the left, in your example you have an empty line selected, you probably can't use any auto-complete on an empty line. Try with a function/var instead maybe?

G

**Comment by Marcotsept** [comment]
Thanks @G-Rowell
