### ISSUE TITLE
Add keymapping to focus nvimtree.lua

### ISSUE THREAD

**Issue by chakrihacker** [NvChad/NvChad#349]
**Is your feature request related to a problem? Please describe.**
Currently, if you want to focus nvim tree, you have to double press ctrl + n 

**Describe the solution you'd like**
This can be simplified by adding a dedicated keymap that focuses nvim tree from your current buffer

**Describe alternatives you've considered**
I added to custom config

**Additional context**
n/a

**Screenshot**
n/a

**Comment by G-Rowell** [comment]
Try `<CNTL> + w + (h, j, k, l)` to swap windows, this is a default Vim keybind.

We'll likely map these to something easier / shorter v. soon.

I think this is good to close?
Feel free to re-open if you have any more questions!


G

**Comment by G-Rowell** [comment]
Hope this helps btw!
:smile:

(again, feel free to re-open if you need)

**Comment by Akianonymus** [comment]
> Try `<CNTL> + w + (h, j, k, l)` to change selected window, this is a default Vim keybind.
> 
> We'll likely map these to something easier / shorter v. soon.
> 
> I think this is good to close?
> Feel free to re-open if you have any more questions!
> 
> G

You actually missed his point, he doesn't want to intuitively look for nvim tree then thing nvim tree is in the right postion, so will use h.

He wants a mapping just for focusing the nvim tree in the current buffer, doesn't matter where the cursor currently is. First is use ctrl + w + key mapping, but can be tedious if multiple splits are open. 

It's most a vscode/sublime thing to have a mapping for such thing. Quite useful maybe.

**Comment by siduck76** [comment]
> > Try `<CNTL> + w + (h, j, k, l)` to change selected window, this is a default Vim keybind.
> > We'll likely map these to something easier / shorter v. soon.
> > I think this is good to close?
> > Feel free to re-open if you have any more questions!
> > G
> 
> You actually missed his point, he doesn't want to intuitively look for nvim tree then thing nvim tree is in the right postion, so will use h.
> 
> He wants a mapping just for focusing the nvim tree in the current buffer, doesn't matter where the cursor currently is. First is use ctrl + w + key mapping, but can be tedious if multiple splits are open.
> 
> It's most a vscode/sublime thing to have a mapping for such thing. Quite useful maybe.

yes its useful , even nerdtree has it . I doubt if nvim has a default mapping for it

**Comment by G-Rowell** [comment]
My apologies for missing the point,
Due to the authors phrasing I assumed they weren't aware of the default mapping binds.

It's something we could incorporate, but I'd be against it, as it becomes one specific niche bind, that for nearly all cases only moves one window to the left.
Furthermore, myself I'm not a fan of leaving NvimTree open due to being able to keep multiple files open in the bufferline, it just ends up being wasted screen space for my use case there.

Though these two points are somewhat subjects, so ofc, happy to be over-rulled



@chakrihacker did I misunderstand you? Do you specifically mean a bind to focus NvimTree from any window?

**Comment by G-Rowell** [comment]
The way I understood this:
>if you want to focus nvim tree, you have to double press ctrl + n

The "***have** to double press...*" would imply to me that the author wasn't aware of the window selection keybinds.

Though ofc again, I could be wrong

**Comment by siduck76** [comment]
@chakrihacker added

**Comment by chakrihacker** [comment]
Yes, thanks for the amazing response time

**Comment by se7en-x230** [comment]
Just learned that ctrl + h focuses nvimtree ...
