### ISSUE TITLE
Lsp not showing document and not have find definition option. 

### ISSUE THREAD

**Issue by Oscuro1111** [NvChad/NvChad#352]
Autocompletion work properly but following issues make it not usable like IDE
1.Lsp Not showing document when over function(Is there any shortect key like :LspDefinition?) .
2.No option available for checking definition of functions.(like vim ctrl+i and ctrl+o).

here how can i watch its doc or declration or definition if it other function.
![issue](https://user-images.githubusercontent.com/47146033/130460899-c063a5e4-6029-40ea-980c-32979c1d549b.png)

**Comment by Oscuro1111** [comment]
> Check lspconfig.lua file , it has many mappings.

ok but what it means "gd" in defintion call

![issue2](https://user-images.githubusercontent.com/47146033/130463400-7c591463-dd1d-47b3-9859-618d18f937fb.png)

**Comment by paulo-santana** [comment]
"go to definition"

**Comment by Oscuro1111** [comment]
> "go to definition"

ok but how i can read it and  know which shortcut to use?
<Cmd>? what it is?

**Comment by paulo-santana** [comment]
In short, `<CMD>` a virtual key that only vim can press. It behaves like when you press `:`, but it doesn't show in the command prompt.

Read it this way: the left string is the sequence of keys of the mapping, the right string is what this mapping will do.

When you press `g` and then `d`, vim will press it's `:` equivalent (the `<CMD>` virtual key), and then it will type `lua vim.lsp.buf.definition()<CR>` in its own virtual prompt. This will just call this function in the builtin LSP client.

**Comment by siduck76** [comment]
Ig this is resolved
