### ISSUE TITLE
Not an editor command: PackerSync

### ISSUE THREAD

**Issue by jakbin** [NvChad/NvChad#353]
**Describe the bug**
Not an editor command: PackerSync

**To Reproduce**
1. when run this command "nvim +'hi NormalFloat guibg=#1e222a' +PackerSync"
2. it show this error :-

![nvchad](https://user-images.githubusercontent.com/65591973/130462324-c848a9dc-9b13-4799-8dcd-f97e9fdbe522.png)

**Desktop (please complete the following information):**
 - Operating System :- parrot os 
 - Terminal :- mate terminal with hack nerd font regular
 - Version of Neovim :- 0.5

**Comment by jasmcaus** [comment]
Is there a `packerInit.lua` in your configurations?

**Comment by siduck76** [comment]
how old is your config?

**Comment by Gitter499** [comment]
II have the same problem. I only get error "E492"

**Comment by donymvarkey** [comment]
Same here as well.

**Comment by G-Rowell** [comment]
Will look into this today

**Comment by siduck76** [comment]
show nvim -v

**Comment by G-Rowell** [comment]
And `git rev-parse --short HEAD` too please!

**Comment by jakbin** [comment]
> And `git rev-parse --short HEAD` too please!

In which directory ?

**Comment by jakbin** [comment]
> Is there a `packerInit.lua` in your configurations? 

I followed install tutorial.

**Comment by topazas** [comment]
Ubuntu PPA is still on 0.4.4, PAckerSync returns this error. With AppImage'd 0.5 it works.

**Comment by siduck76** [comment]
so this aint any nvchad issue , please use 0.5v

**Comment by G-Rowell** [comment]
@topazas Glad it's fixed!

**Comment by jakbin** [comment]
> show nvim -v

![nvchad1](https://user-images.githubusercontent.com/65591973/130632118-de37faab-fedd-418b-93ca-392b1318e42a.png)

**Comment by G-Rowell** [comment]
@jakbin 
Do you still have this issue?

**Comment by jakbin** [comment]
> Is there a `packerInit.lua` in your configurations?

![nvchad2](https://user-images.githubusercontent.com/65591973/130632775-6a9fc938-2a7b-4977-bf75-f77cc2f4431b.png)

**Comment by G-Rowell** [comment]
> @jakbin 
> Do you still have this issue?

@jakbin

**Comment by jakbin** [comment]
> how old is your config?

i latest config from installation tutorial.

**Comment by jakbin** [comment]
> > @jakbin
> > Do you still have this issue?
> 
> @jakbin

yes

**Comment by G-Rowell** [comment]
Can you run

`git rev-parse --short HEAD`

And show me the output please

**Comment by jakbin** [comment]
> Can you run
> 
> `git rev-parse --short HEAD`
> 
> And show me the output please

tell me directory

**Comment by G-Rowell** [comment]
In the NeoVim config directory, that's where you installed NvChad

**Comment by jakbin** [comment]
> Can you run
> 
> `git rev-parse --short HEAD`
> 
> And show me the output please

b57cb6c

**Comment by jakbin** [comment]
> so this aint any nvchad issue , please use 0.5v

![nvchad1](https://user-images.githubusercontent.com/65591973/130632118-de37faab-fedd-418b-93ca-392b1318e42a.png)

**Comment by G-Rowell** [comment]
You need to update NvChad

`git pull origin --rebase`

Is probably appropriate for this case

**Comment by jakbin** [comment]
> You need to update NvChad
> 
> `git pull origin --rebase`
> 
> Is probably appropriate for this case

![nvchad3](https://user-images.githubusercontent.com/65591973/130647860-4200a84d-2aeb-43a9-8a9a-2ca64a59b074.png)
