### ISSUE TITLE
Alternative Keyboard Layout (Colemak) -- Accessibility

### ISSUE THREAD

**Issue by calligraffiti** [NvChad/NvChad#354]
Greetings,

I've been trying to change the default keys. I have been using the following vim script in my vimrc/init.vim for years:
```
" {{{ Settings Keybindings

  " Remapping for Coleak
  " ----------------------
  " get control-j back, so switch it with ctrl-n at qwerty position of j
  imap <c-n> <cr>
  cmap <c-n> <cr>
  inoremap <c-j> <c-n>
  cnoremap <c-j> <c-n>

  " rotate some keys about to get qwerty "hjkl" back for movement
  map n <down>
  map e <up>
  map i <right>

  " move these keys to their qwerty positions because they are
  " in the way of hjkl (and E for J)
  noremap k n
  noremap K N
  noremap f e
  noremap u i
  noremap U I
  noremap l u
  noremap L U
  noremap N J
  noremap E K
  noremap I L

  " this is the only key that isn't in qwerty or colemak position
  noremap j e
  noremap J E
```
I'm pretty new to lua. I tried converting it over, and some of this is working (j,k disabled, u working as insert) but I can't seem to get the rest to stick:
```
map ('i', '<C-n>', '<CR>', opts)
map ('c', '<C-n>', '<CR>', opts)
map ('', '<C-j>', '<C-n>', opts)
map ('', '<C-j>', '<C-n>', opts)

map('', "<n>", "<Down>", opts)
map('', "<e>", "<Up>", opts)
map('', "<i>", "<Right>", opts)
-- map('i', '<C-k>', '<Up>', opts)

--  move these keys to their qwerty positions because they are
--  in the way of hjkl (and E for J)
map('n', 'k', 'n', opts)
map('n', 'K', 'N', opts)
map('n', 'f', 'e', opts)
-- etc
```

**Comment by G-Rowell** [comment]
Hi,

while I've never used an alternative layout, I love the idea of making this more accessible to those who choose to do so.
Will look at this as soon as I can :smile:

**Comment by G-Rowell** [comment]
Heyo @calligraffiti,

just checking in here!

I'd love to support Colemak users,
we also have a custom config overhaul with PR #465 which will probably help with doing this.

There also may be some more mappings which are `hard-coded` (IE. don't draw from the `lua/core/mappings.lua` file.

One tricky issue regarding this will be plugin mappings, that are default to a QWERTY layout.

---

What can we do to help you out more with this? It should be reasonably close to achievable currently.

G

**Comment by igranic8720** [comment]
Fellow colemak-er, definitely didn't think I'd find this issue. Would love to see it in nvchad. I always found it easiest to keep most key-binds the same other than h,j,k,l, and i. Most fulltime colemak-ers seem to do the same as switching/translating to qwerty is quite common for us.  Also, some keybinds are binded to sensical/representative keys, so really i don't change much outside of the stock vim keybinds. A good example is d for delete.  Sorta just makes sense, even if it moves. 

Thanks calligraffiti. I didn't think this was something someone else was looking into. There's probably a dozen of us.

AIso thanks to G-Rowell for picking this issue up. means a lot that nvchad is actively listening to it's users. No matter the niche.

**Comment by G-Rowell** [comment]
@calligraffiti @igranic8720 

So I guess I have three small questions (as someone who wishes to support this, but doesn't use Colemak/dvorak):

1. Do we need to change all mappings? or only a select few?
   - it seems like ideally all, but it is feasible to do just a select few as a hotfix for the meantime. is this correct?
2. Do we need any way to swap between colemak/dvorak mappings & normal mappings?
   - if so this would be best suited to our `extensions` repo I think, rather than being inside the base config directly
   - **2.5** we would need some way of easily changing all the mappings in the config?
3. If no to 2, how would we advertise/apply these mappings?
   - could have a section on our website for this? (In FAQ or advanced configuration?)
   - it would probably not be ideal to copy-paste the mappings in I think, so back to **2.5**

---   

This relates a lot to #465, which is an overhaul for the custom config section of NvChad.
Such an overhaul could be the key solution to this problem, as it would fully enable users to do things like move to Colemak/dvorak.

It may be reasonable to provide a sample config file for colemak/dvorak when #465 is merged?


Hmmmmm, opinions?


G

**Comment by igranic8720** [comment]
1. In my opinion, only a select few which are location dependant. These have been noted above.  h,j,k,l,i and the ways in which calligrafitti had mentioned were great.

2. It would be nice, especially for other layouts like azerty and other languages later on down the line. Going back and forth would be nice as well since people i usually work with could use my kb on vim when im in person.

2.5 100% yes. This may be tricky though. So, maybe configs could be kb layout specific, and then could be swapped and edited?

3. Advertise on the readme? Also this approach tor development would open the door to alternate layouts in general. Thus on the way to azerty or other layouts for eu and abroad outside na/uk. Section on the website would work great.  Could also see adoption earlier from other languages if the config is easier to do in one spot imo.

Outside of actual advertisement, I would think the option would come up on startup of  nvim sorta like a language picker. Although that's easier said than done.

This could be amazing.  I already have friends trying out NVChad.  I can only imagine what alternate kb support could do for this project outside of the 12 colemak users.

In regards to #465 Totally reasonable. Would definitely daily drive that config.

Love this project. Again thanks for everything G-Rowell and NVChad.

**Comment by G-Rowell** [comment]
So I think we have a great spot on our website for this,

the [`Post Install page`](https://nvchad.netlify.app/getting-started/post-install), we could list keyboard layout here.

---

I think a `first install / initial startup of NvChad` prompt for keyboard is somewhat tricky to do nicely,
we've tried to avoid having an installer for NvChad.

Though this is for sure something possible to implement from a technical perspective,
[`NvChad/extensions`](https://github.com/NvChad/extensions) is a good place for this kind of thing.

---

Advertising on the README could for sure be an option

---

**Comment by calligraffiti** [comment]
I agree with @igranic8720. Most folks who have en-devoured to change too many keys find themselves in a constant battle trying to get every plugin and vim like application to work on the same page. Really it's just about those 'hjkl' keys. Everything else becomes muscle memory with Vim and Emacs, but pressing Y to 'move down' and N to 'move up' is not just awkward, it's completely deranged! ;)

Re: Question 2: Most folks who use alternative keyboard layouts are quite adept at changing the keys themselves with very little help. I just think they need to know if it's possible, and where to do it. So regardless of the layout, Colemak vs. Dvorak, etc., there's not really much of a difference. Once they find where to change those 5 basic controls within 'Move Mode', they're usually all set. If someone wants to add another custom key binding, they just copy and paste the one above and edit it to the key they wish to change. Does that align with your views too @igranic8720?

Re: Question 2.5: Almost never would anyone change all the keys. It just adds complexity. I'm a little eccentric in that I map the 'u' key, (the position 'i' is on a qwerty layout) to enter 'Insert Mode'.

And yes, I think the 'Post Install' section is the perfect place for it! Also if there were some reference within the chadrc file. I think that's probably the first place most folks would look, even if it were just a comment pointing to the keybindings.lua file, or whatever solution it is.

**Comment by G-Rowell** [comment]
I do think that aiming just change `h, j, k, l` is way more feasible (though probably still not non-trivial),
as many plugins have `hidden default mappings`, EG: Telescope's open in vertical split mappings.

Over the next day or so I'll have to look through and see what would be impacted by changing `h, j, k, l`.

**Comment by calligraffiti** [comment]
Exactly right. Though when you have collisions with plugins, like telescope for example, it's easy enough to go into the plugins config and change 'h' to <CR> 'h' or leader 'h' for example. All Dvorak users keys (h, j, k, l) change, but for Colemak users 'h' is the same as QWERTY. So 'j', 'k' and 'l' are the most essential changes. So what do do with the 'i' and 'u' keys?

*My own preferences:*
  * 'j' remaps to 'n' (move-down)
  * 'k' remaps to 'e' (move-up)
  * 'l' remaps to 'i' (move-left)
  * 'i' remaps to 'u' (enter Insert Mode)
  * 'u' remaps to 'l' (Undo)

'e' is the only functionality lost to me without more tweaks (move to end of word), which sucks, but it's still better than trying to fly around with the 'y' for down, and the 'k' key for up.

Sorry that was overly explained, but what I'm trying to say is you shouldn't bare the burden of keybinding collisions inside of plugins. That should 100% be on the user to figure out. And most plugins have documentation on how to customize those preferences. E.g. say I wished to change the toggle key in nvimtree from control + 'n' to CR + 'k'. Obviously I can do that in within chadrc and any keybindings within nvimtree I can change within 'g.nvim_tree_bindings' in the /plugins/configs/nvimtree.lua file. But again, that shouldn't be something you need to be concerned with. I think the biggest challenge is how do folks like myself (and the 10 other brave souls, by @igranic8720's estimates), update NvChad without loosing our keybinding preferences?

**Comment by G-Rowell** [comment]
Oh updating without losing those keybindings is relatively trivial thankfully!

You can already do so with `chadrc` but #465 will greatly improve it too

**Comment by igranic8720** [comment]
I do agree with you 100% on the hjkli switching. Colemak is different than other layouts though.  It was an upgrade to qwerty, not a replacement for some other use like another language.  The minimal hand switching for keys makes most keybinds still make sense.  Dvorak is not as simple to remap.  The other reason for supporting more configs would be to support languages outside of english where vim shorthands may be different. For example yank makes little sense in english as is.  Verbose/representative keybinds are not really possible for azerty  users as is for example.  this opens the door for different language support for NVChad.
@G-Rowell @calligraffiti

**Comment by G-Rowell** [comment]
Yeah,

must say that I don't have any experience with anything other than QWERTY & English,

so these kinds of comments for sure help me to understand!

---

I'm pretty certain we've had a fair few users who speak Mandarin using NvChad, so it'd be a lovely byproduct to support them more too.


G

**Comment by igranic8720** [comment]
You guys really are the best, I really like this project. I hope it takes off as much as spacevim or the other large vim distributions/configs/whatever.  I actually never expected this kind of support for kb layouts and languages. I just stumbled upon this issue, and I couldn't be happier with your openness to the idea.  Really cool to hear its getting wider adoption in the world, especially in china with mandarin.

Colemak will probably be the easiest because of the similarity and the others may take time to translate the bindings. Thanks for caring about the community of NvChad.

**Comment by G-Rowell** [comment]
Thank you so much 😁 

I'm going to be mindful of unnecessary complexity or bloat, as with any PR, but I certainly think we can find a way to do this!
Once #465 get's merged we'll take a good proper look into this!!!! 🚀 🎉

**Comment by G-Rowell** [comment]
@calligraffiti @igranic8720 

Hey you two,
The big custom overhaul PR #465 is merged!

We can now have a look at adding support for this.

I'm thinking we can add some `chadrc` option to do this?

We also now have proper support for custom mappings.

**Comment by macarthy** [comment]
> 12 colemak users.

13

**Comment by macarthy** [comment]
Hey @calligraffiti  is this working for you now, with the new custom folder etc .?

> Thanks G-Rowell!
> 
> This project is astounding! The more I dig the more perfect it seems. I'm just about convinced that my old rc files need to be retired, with honor, to init.heaven.
> 
> I made a little progress. Forgive the code is a bit 'inelegant' as they say. Just getting my head around Lua here. I created a file called _keybinds.lua_ in the _lua/core/_ directory. This works great. My preference is to change the bare minimum to avoid keybind collisions with other plugins, etc. I know the placement is not ideal, if I were worried about files being overwritten with a uu, etc, but that may be part of a bigger problem, e.g. where should I put my own plugins if I want to add them? I wonder if instead of a chadrc there shouldn't be an entire directory of overrides, e.g. **'/user'/** with it's own init, plugins, keybinds, etc.? I do understand that this may not be the intent of the project. It's more an app now then a stack of config files. In any case, I'm learning so much by deconstructing your hard work!
> 
> I suppose the following could be implemented as variables within chadrc, or as a drop-in file or plugin. For Dvorak or Colmak, etc., the basic is just remapping 'j' k' 'l' and 'i' for insert, but it really depends on the user. There are a lot of folks that like to replace 'i' with 's' and 'a' with 't', for example, but that requires still more shuffling of keys, which is generally more trouble than it's worth in my opinion.
> 
> **core/keybinds.lua:**
> 
> ```
> local config = require("core.utils").load_config()
> 
> local map = vim.api.nvim_set_keymap
> local opts = {noremap = true, silent = true}
> local xpr = {noremap = true, expr = true}
> 
> -- Colemak Keybindings {{{
>   ----------------------
>    map('n', 'n', 'j', opts)
>    map('x', 'n', 'j', opts)
>    map('o', 'n', 'j', opts)
>    map('n', 'e', 'k', opts)
>    map('x', 'e', 'k', opts)
>    map('o', 'e', 'k', opts)
>    map('n', 'i', 'l', opts)
>    map('x', 'i', 'l', opts)
>    map('o', 'i', 'l', opts)
> 
>    -- Colemak Insert
>    map('n', 'u', 'i', opts)
>    map('n', 'U', 'I', opts)
>    map('x', 'u', 'i', opts)
>    map('x', 'U', 'I', opts)
>    map('o', 'u', 'i', opts)
>    map('o', 'U', 'I', opts)
> 
>    -- Undo/redo
>    map('n', 'l', 'u', opts)
>    map('x', 'l', ':<C-U>undo<CR>', opts)
>    map('n', 'gl', 'u', opts)
>    map('x', 'gl', ':<C-U>undo<CR>', opts)
>    --  map('n', 'Z', '<C-R>', opts)
>    --  map('x', 'Z', ':<C-U>undo<CR>', opts)
> 
>    -- Colemak Windows
>    map('n', '<C-W>h', '<C-W>h', opts)
>    map('x', '<C-W>h', '<C-W>h', opts)
>    map('n', '<C-W>n', '<C-W>j', opts)
>    map('x', '<C-W>n', '<C-W>j', opts)
>    map('n', '<C-W>e', '<C-W>k', opts)
>    map('x', '<C-W>e', '<C-W>k', opts)
>    map('n', '<C-W>i', '<C-W>k', opts)
>    map('x', '<C-W>i', '<C-W>k', opts)
> 
>    -- window & tab controls
>    map('n', '<leader>ss', ':sp<space>', opts)
>    map('n', '<leader>vs', ':vsp<space>', opts)
>    -- tab controls -- ctrl-t makes a new tab
>    map('n', '<C-t>', '<Esc>:tabnew<CR>', opts) -- Check collision!
>    -- shift T turn a split window into a tab
>    map('n', '<S-T>', '<Esc><C-w>T', opts) -- Check collision!
>    map('n', 'te', ':tabnext<CR>', opts)
>    map('n', 'tn', ':tabprev<CR>', opts)
>    map('n', 'th', ':tabfirst<CR>', opts)
>    map('n', 'ti', ':tablast<CR>', opts)
> 
> -- }}}
> ```

**Comment by calligraffiti** [comment]
Greetings @macarthy, yeah, this approach is a game changer. However, I'm still importing a custom 'keybinds.lua' file with the core init.lua. e.g:
```
local core_modules = {
   "core.custom",
   "core.options",
   "core.autocmds",
   "core.mappings",
   "core.keybinds",
}
```
Everything else I've tried breaks. I'm not sure putting this much code within M.mappings = {} is the best place for it. It really should be it's own separate file for a variety of reasons.

Do you have a suggestion as to how I could keep keybinds.lua on it's own, perhaps within the custom directory, for example, and not touch the core init.lua file?

**Comment by macarthy** [comment]
Why not puts it in ``` custom/plugins/colemak.lua```  and  require it in custom/init.lua ``` require custom.plugins.colemak.lua ``` 

Wrap it in the hook system  
``` 
hooks.add("setup_mappings", function(map)
        map('n', 'ti', ':tablast<CR>', opts)
 end)
 ```

I think that should work? @G-Rowell ? @calligraffiti ? @igranic8720 ?

**Comment by G-Rowell** [comment]
> 
> 
> Why not puts it in ` custom/plugins/colemak.lua` and require it in custom/init.lua `require custom.plugins.colemak.lua`
> 
> Wrap it in the hook system
> 
> ```
> hooks.add("setup_mappings", function(map)
>         map('n', 'ti', ':tablast<CR>', opts)
>  end)
> ```
> 
> I think that should work? @G-Rowell ? @calligraffiti ? @igranic8720 ?

+1

The `hooks.add("setup_mappings"............` system is designed for this, so hopefully that work!

Does it work for you two?

Also of note, I'll probably have to add a small `default_config` / `chadrc` option to disable any problematic qwerty keybinds,
any suggestions on what you want me to add an enable/disable flag for?

**Comment by calligraffiti** [comment]
Just adding `require custom.keybindings.lua` within the custom/init.lua file causes an error on my system:
"*E5113: Error while calling lua chunk: /home/calligraffiti/.config/nvim/init.lua:4: attempt to concatenate global 'module' (a function value)*"

My keybindings.lua file is 114 lines, and has local parameters set at the top of the file. I really think all of that should remain outside of the chadrc file. That little snippet is great if there were one or two things that needed tweaking, but a whole colemak file is a bit much. Specially when everything would have to be written long hand e.g.: `vim.api.nvim_set_keymap ('n', 'n', 'j', {noremap = true, silent = true})` etc.

I know it's not quite the spirit of the project, but have you thought about this scenario:
 1. chadrc.lua is active by default. Move all of the 'little configs' that are super common, e.g. leader map, tab settings, etc. (Why create over-rides, and more lines of configuration, when they are so commonly customized?)
 2. create a 'mappings.lua' or a 'keybinds.lua' in /custom/ by default, already linked, and ready to customize. (These are also routinely edited, even when another keyboard layout, such as colemak, isn't deployed)
 3. Create a 'plugins.lua' page within '/custom/' already linked with sample syntax (Right now if I add a plugin within 'chadrc.lua' such as `use "custom.plugins.vimwiki.lua"` I get an error: *"Warning: ../.config/nvim/lua/custom/chadrc.lua is present but sourcing failed"* (btw, this version of vimwiki is converted to lua and works with my other lua configs.)

Seems like when I make these changes directly in '/core/' everything seems to work, but then I can't really upgrade the build easily. Unfortunately, I seem to keep getting thrown to the mate when I attempt edits within the '/custom/' dir. I know... mostly because I still need to get a firmer grip on Lua, but it should be fairly intuitive and easy here; shouldn't it?

**Comment by siduck76** [comment]
@calligraffiti  chadrc's just meant to edit the general options ( like mapleader, globals etc) and some options of all default nvchad plugins , if you want to add a new plugin then add it in custom/init.lua and not chadrc.lua. I hope you have read the new config docs :/ 

https://nvchad.github.io/config

**Comment by calligraffiti** [comment]
> @calligraffiti chadrc's just meant to edit the general options ( like mapleader, globals etc) and some options of all default nvchad plugins , if you want to add a new plugin then add it in custom/init.lua and not chadrc.lua. I hope you have read the new config docs :/
> 
> https://nvchad.github.io/config

Thank you @siduck76, I did actually mean */custom/init.lua/*, but I did not use the correct formatting. However I'm still getting that *'E5113:'* error. I believe because I'm addressing the plugin path wrong.
```
 use {
   "custom.plugins.vimwiki.lua",
   config = function()
     require("custom.plugins.vimwiki")
   end
 }
```
I'm sorry this is very off topic, and is probably not the best place for my plugin issue; but just so others understand what my silliness I respond inline. ;)

Maybe more on topic, where do you recommend placing my plugin configs?

**Comment by macarthy** [comment]
Why not add these empty folders to the custom directory . Stick a .keep file in each to keep git happy 

```plugins ( plugin configs )
mappings
autocmds
highlights```

**Comment by siduck76** [comment]
> Why not add these empty folders to the custom directory . Stick a .keep file in each to keep git happy
> 
> ```
> plugins ( plugin configs )
> mappings
> autocmds
> highlights
> ```

I talked about it with @G-Rowell and he told that wasnt a good idea :laughing:

**Comment by macarthy** [comment]
Well I think it is :-)  It will allow a common structure across the
community and if people start sharing their custom dirs it would be easy to
find what you are looking for.
It has been said of ruby on rails that it most important feature was empty
folders

In fact maybe <SPACE>up  should push your custom config to a examples repo

Just my thoughts

**Comment by siduck** [comment]
idk much about keyboard layouts and the issue creator doesnt seem to reply so i will close this

**Comment by calligraffiti** [comment]
> @macarthy @calligraffiti
> 
> How are your COLEMAK setups now by the way?
> 
> What can I do? (sorry, been out of the loop & super busy)

Heya @G-Rowell,

Sorry I know this issue has been marked closed. I've been out of pocket for a spell.

I'm still adding a line to core_modules within the root 'init.lua' file e.g.:
```
local core_modules = {
   "custom.keybinds",
}
```

This method is an improvement as I can protect my custom 'keybinds.lua' file within the 'custom' directory, but I still have to add back this line after an update to relink my keybindings. Not a huge deal, but also not ideal. Any suggestions?

Someone suggested loading custom keybindings by way of plugins, but I'm not sure how to go about that.

**Comment by siduck** [comment]
cant you load    "custom.keybinds" in custom/init.lua file?

**Comment by calligraffiti** [comment]
> cant you load "custom.keybinds" in custom/init.lua file?

Forgive me my Lua comprehension is still a bit nascent. The first thing I did was to try including it within my custom/init.lua file, but I must be formatting it incorrectly or addressing the file incorrectly. I can not seem to get it to work for me.

**Comment by calligraffiti** [comment]
> > cant you load "custom.keybinds" in custom/init.lua file?
> 
> Forgive me my Lua comprehension is still a bit nascent. The first thing I did was to try including it within my custom/init.lua file, but I must be formatting it incorrectly or addressing the file incorrectly. I can not seem to get it to work for me.

Huh, well never mind. I swear I tried a `require "custom.keybinds"` before to no avail, but this time it worked!

I'll post my full solution below in case others come looking for this info.

Thanks *everyone* on this issue for your help!

**Comment by calligraffiti** [comment]
# Alternative Keyboad Layout Instructions
- colemak -dvorak -maltron -azerty -qwertz

1. Create a file in your ~/.config/nvim/lua/custom directory `keybinds.lua`.
2. Add your keyboard configuration (I included my own Colemak layout below)
3. Require the file within your `init.lua` in your ~/.config/nvim/lua/custom/ directory. Add this line:
    `require "custom.keybinds"`

That's all there is to it. If you have created your own alternative layouts please post them here to help the community.

Here is my Colemak layout or `keybinds.lua` file. You may customize it to your preferences:
```
local config = require("core.utils").load_config()

local map = vim.api.nvim_set_keymap
local opts = {noremap = true, silent = true}
local xpr = {noremap = true, expr = true}

-- Colemak Keybindings {{{
   ----------------------
   map('n', 'n', 'j', opts)
   map('x', 'n', 'j', opts)
   map('o', 'n', 'j', opts)
   map('n', 'e', 'k', opts)
   map('x', 'e', 'k', opts)
   map('o', 'e', 'k', opts)
   map('n', 'i', 'l', opts)
   map('x', 'i', 'l', opts)
   map('o', 'i', 'l', opts)

  -- Colemak Insert
   map('n', 'u', 'i', opts)
   map('n', 'U', 'I', opts)
   map('x', 'u', 'i', opts)
   map('x', 'U', 'I', opts)
   map('o', 'u', 'i', opts)
   map('o', 'U', 'I', opts)

   -- Undo/redo
   map('n', 'l', 'u', opts)
   map('x', 'l', ':<C-U>undo<CR>', opts)
   map('n', 'gl', 'u', opts)
   map('x', 'gl', ':<C-U>undo<CR>', opts)

   -- Colemak Windows
   map('n', '<C-W>h', '<C-W>h', opts)
   map('x', '<C-W>h', '<C-W>h', opts)
   map('n', '<C-W>n', '<C-W>j', opts)
   map('x', '<C-W>n', '<C-W>j', opts)
   map('n', '<C-W>e', '<C-W>k', opts)
   map('x', '<C-W>e', '<C-W>k', opts)
   map('n', '<C-W>i', '<C-W>k', opts)
   map('x', '<C-W>i', '<C-W>k', opts)

   -- window & tab controls
   map('n', '<leader>ss', ':sp<space>', opts)
   map('n', '<leader>vs', ':vsp<space>', opts)
   -- tab controls -- ctrl-t makes a new tab
   map('n', '<C-t>', '<Esc>:tabnew<CR>', opts) -- Check collision!
   -- shift T turn a split window into a tab
   map('n', '<S-T>', '<Esc><C-w>T', opts) -- Check collision!
   map('n', 'te', ':tabnext<CR>', opts)
   map('n', 'tn', ':tabprev<CR>', opts)
   map('n', 'th', ':tabfirst<CR>', opts)
   map('n', 'ti', ':tablast<CR>', opts)

-- }}}

-- {{{ Improvments
   map('n', '<leader><space>', ':set hlsearch!<CR>', opts)
   map('n', '<leader>sl', ':set wrap linebreak<CR>', opts)

   -- highlight last inserted text
   map('n', 'gV', '`[v]`', opts)

   -- turn on spell checker - ]s and [s to move, z= for suggestions
   map('n', '<leader>spl', ':set spell spelllang=en_us<CR>', opts)
   map('n', '<leader>nspl', ':set nospell<CR>', opts)
   map('n', '<leader>S', ':FixWhitespace<CR>', opts)

-- }}}
```

**Comment by siduck** [comment]
> > > cant you load "custom.keybinds" in custom/init.lua file?
> > 
> > 
> > Forgive me my Lua comprehension is still a bit nascent. The first thing I did was to try including it within my custom/init.lua file, but I must be formatting it incorrectly or addressing the file incorrectly. I can not seem to get it to work for me.
> 
> Huh, well never mind. I swear I tried a `require "custom.keybinds"` before to no avail, but this time it worked!
> 
> I'll post my full solution below in case others come looking for this info.
> 
> Thanks _everyone_ on this issue for your help!

yep it worked this time since we had mad many changes regarding hooks , i totally removed that xD. cleaned up a lot! check the breaking changes issue

**Comment by appleboblin** [comment]
> 

How do I map colemak now? Can't seem to find a way without any bugs

**Comment by siduck** [comment]
@appleboblin read mapping docs

**Comment by appleboblin** [comment]
I've got it to work after modifying my existing config.

**Comment by CBroz1** [comment]
Has anyone translated the above Colemak remapping to the current `mappings.lua` format?

**Comment by MathiasOdlund** [comment]
Bumping this. I would like Colemak to be an available layout choice in the config.

**Comment by RockClapps** [comment]
I am surprised nobody has mentioned vim's `langmap` option. More specifically, I add `vim.opt.langmap = 'hjklHJKLneioNEIO;neioNEIOhjklHJKL'` to rebind just my `hjkl` to `neio` for colemak use. It alleviates a lot of manual mapping issues by just sort of translating one key to another in all modes and contexts except insert. It's only problems in my experience are that:
1. It doesn't seem to apply to `<C-` shortcuts
2. Whichkey bindings will show their original letters, despite actions following the langmap
3. One niche case with my nvchad setup where `vi` will transition whichkey to showing the keys for visual insert, but instead actually did the thing it was supposed to given my mapping and moved the cursor up. However, it doesn't actually show that it moved the cursor up, but following up with another action like `d` confirms this is the case
4. When following up to rebind `<C-i>`, you can't without messing up `tab` because bash treats them as the same key

Maybe nvchad or upstream whichkey can fix these problems but it's pretty workable in the meantime

**Comment by siduck** [comment]
@RockClapps thats whichkey issue, ask there once
