### ISSUE TITLE
Telescope does not shows me preview of the media

### ISSUE THREAD

**Issue by insidersbuilt** [NvChad/NvChad#355]
telescope does not shows me the preview of the media files even i have installed the uezerburg 
![image](https://user-images.githubusercontent.com/87114084/130511360-44d655eb-77ce-4ca5-ae3a-eb400b01bb67.png)

**Comment by chebro** [comment]
@insidersbuilt the extension only works with the media plugin which is mapped to `<leader>fp`.

**Comment by ashincoder** [comment]
To open media files use `:Telescope media_files`

**Comment by insidersbuilt** [comment]
> s

but i don't see the media files popup after pressing &lt;leader&gr;fp i think i have some error with my uezerburg can you send the page whre from you installed uezerbug i tried to install it from their github page but first it was not working then some how i installed it now i think if ueaerburg is not loaded then telescope wont show you the media files

**Comment by insidersbuilt** [comment]
![image](https://user-images.githubusercontent.com/87114084/130570200-0e8b186b-36ef-4196-99bd-bf6d8796bf04.png)
i have reinstalled uezerbug now the media files opens but does not shows me the preview

**Comment by insidersbuilt** [comment]
![image](https://user-images.githubusercontent.com/87114084/130570390-cabe7901-fac2-43e9-aaf1-0a59e84740f4.png)
Reinstalled uezerburg and now it works

**Comment by glmsmoura** [comment]
Is there a way to search files with media at the same time? I guess ranger could do that.
