### ISSUE TITLE
Lazy loading plugins by command invocation is prone to breakage/confusion

### ISSUE THREAD

**Issue by ccope** [NvChad/NvChad#356]
**Describe the bug**
I frequently invoke `:Gdiffsplit` from fugitive, but it doesn't seem to be available with the nvChad configs ("E492: Not an editor command: Gdiffsplit"). I'm not sure how to add a keybinding for it either, but I usually like to type in the command.

**To Reproduce**
1. Open a file in neovim inside a git repo
2. Run `:Gdiff`
3. See error

**Expected behavior**
Plugin should open a vertical split with the last commit (or optionally a specified commit/branch)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Alacritty
 - Neovim 0.5.0
 - NvChad 1.0 as well as 09f6c4c

**Comment by ccope** [comment]
Ugh ok, I finally found the cause of the problem. The line where packer loads the fugitive plugin sets which commands trigger lazy loading, and only `:Git` is specified. I never use `:Git` so `:Gdiff` never became available. I'm kind of skeptical of lazy-loading functionality based upon command invocation unless the plugin really only has one or two commands.

**Comment by 21eleven** [comment]
I have opened a PR that fixes this. It includes the fugitive commands: `Gdiff`, `Gdiffsplit`, `Gvdiffsplit`, `Gw` and `Gwrite` to trigger loading. Should be sufficient yea?

**Comment by ccope** [comment]
Good enough for me, though other users might still use some other stuff (maybe Gbrowse? but it needs another plugin now)

**Comment by Akianonymus** [comment]
Do not merge this now, i have better implemention which i will pr today

**Comment by siduck76** [comment]
> **Describe the bug**
> I frequently invoke `:Gdiffsplit` from fugitive, but it doesn't seem to be available with the nvChad configs ("E492: Not an editor command: Gdiffsplit"). I'm not sure how to add a keybinding for it either, but I usually like to type in the command.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open a file in neovim inside a git repo
> 2. Run `:Gdiff`
> 3. See error
> 
> **Expected behavior**
> Plugin should open a vertical split with the last commit (or optionally a specified commit/branch)
> 
> **Desktop (please complete the following information):**
> 
> * Ubuntu 20.04
> * Alacritty
> * Neovim 0.5.0
> * NvChad 1.0 as well as [09f6c4c](https://github.com/NvChad/NvChad/commit/09f6c4c06776d8586f22de7ed71acfd5098d23f5)

yes added it
