### ISSUE TITLE
Telescope <space> fa files all

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#360]
Nice move to include by default the hidden files in the nvim-tree.
 
Could the team consider to have a Telescope keybinding that includes hidden files as well?
I understand that setting `<space> ff` to include the hidden files by default is a bad idea as it will slow down the process.

But maybe a separate keybinding like `<space> fa` would be something worse thinking about.

**Comment by G-Rowell** [comment]
My proposed mapping would be `<leader> + f + F` or `<leader> + F + F`

It's an interesting idea certainly, I'd be in favour of it.

We are currently handing a whole lot of cleanup and bug fixes rn, so we may take a bit to get to this.


G

**Comment by Akianonymus** [comment]
> My proposed mapping would be `<leader> + f + F` or `<leader> + F + F`
> 
> It's an interesting idea certainly, I'd be in favour of it.
> 
> We are currently handing a whole lot of cleanup and bug fixes rn, so we may take a bit to get to this.
> 
> G

You realize how tedious that will be to execute ?

**Comment by se7en-x230** [comment]
Any sane keybinding will do. I just thought ff (find file) and fa (find all) or f. (find dot files). Whatever is free and easy to remember/execute.

**Comment by G-Rowell** [comment]
> You realize how tedious that will be to execute ?

Just hold `<shift>` while pressing `<space>` then `f`?

Don't think it'd be that tedious imo

**Comment by Akianonymus** [comment]
@G-Rowell I definitely didn't know that's how to press, thank you 😂.

Anyway, fa makes more sense imo, ff is find files and fa is find all files

what's wrong with this ?

**Comment by siduck76** [comment]
yea I agree with aki

**Comment by siduck76** [comment]
@se7en-x230 I hope this is added by now

**Comment by se7en-x230** [comment]
Excellent. Thanks
