### ISSUE TITLE
Telescope move through the list with ctrl j/k

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#361]
I might be wrong but I thought it was a feature before the list view was reversed.

Moving through the Telescope list is now only possible with the arrow keys and not by ctrl + j/k.
If it is possible to re(add) that again would be nice as using the arrow keys is "clunky".

**Comment by ashincoder** [comment]
Isn't <ctrl>n and <ctrl>p used to move through the list

**Comment by se7en-x230** [comment]
Thanks.  j/k would be easier but that works as well.
