### ISSUE TITLE
Can't set custom mappings, some options unsupported in chadrc.lua

### ISSUE THREAD

**Issue by phatsk** [NvChad/NvChad#366]
**Describe the bug**
I started using NvChad about a month ago, when things like `options.lua` still existed. Last night I decided to `:PackerUpdate` which broke the theme colors and rendered everything useless. I backed up my config folder and checked out the latest NvChad to find that the entire structure has been reorganized. 

I had a bunch of my own preferences for things like line wrapping, tabs, etc, all sorted in `options.lua` previously. I've updated most of these to the new `chardrc.lua`, however, some options are unsupported (e.g. `M.options.wrap = false` does nothing). 

I attempted to set these manually with lua commands in `chadrc.lua`, but this breaks _everything_ in that file and nothing gets set.

The same happens if I attempt to create custom mappings e.g. I use `<TAB>` to switch between window splits (I remapped my Leader to `,`):

```lua
map("n", "<TAB>", "<C-w>w", opt)
map("n", "<S-TAB>", "<C-w>W", opt)
```
Placing these mappings inside of `chardrc.lua` similarly causes the entire file to not be used, falling back to defaults.

My question is: where do custom options and mappings go now that things like `options.lua` are no longer used? For mappings, I've hacked them into the mapping section for `vim_fugitive` in `lua/core/mappings.lua` but this feels _extremely_ bad, and there's no clear documentation that addresses this that I've been able to find.

**Desktop (please complete the following information):**
 - Operating System: MacOS 10.15.3
 - Terminal: iTerm 2 Nightly
 - Version of Neovim: v0.5.0

**Comment by HoolaBoola** [comment]
I have stuff like `vim.cmd [[ vim_command ]]` in my chadrc.lua to accomplish what the current configurations don't allow (yet)

For example:
`vim.cmd [[ nmap <silent> <C-l> :wincmd l<CR> ]]`
That allows me to press Ctrl+L to move to a window split on the right.

For you, I suggest trying this:
`vim.cmd [[ nmap <Tab> :wincmd w<CR> ]]`
And the same for Shift-Tab

I don't know if there's a better or easier way to do it

**Comment by siduck76** [comment]
yea for the time being just put all your mappings in
vim.cmd( [[ here ]])

**Comment by phatsk** [comment]
Thanks, I'll try that and see what happens. For some reason my mappings were breaking it last night.

**Comment by Eduruiz** [comment]
@HoolaBoola can you help me here? where exactly do you put the 
```
vim.cmd [[ nmap <silent> <C-l> :wincmd l<CR> ]]
```
in your `chadrc.lua`? I tried some stuff but nothing worked as I expected :(

**Comment by G-Rowell** [comment]
@Eduruiz 

It should work in `chadrc.lua` outside of a function, so place it at the bottom of the file, but before the `return M` 

Let me know if this doesn't work

**Comment by Eduruiz** [comment]
@G-Rowell thanks for the quick answer, unfortunately, it didn't work. maybe I'm just too noob :smile:   
this is the very end of my file:
```
vim.cmd [[ nmap <leader><leader> :nohlsearch<CR> ]]
return M
```

**Comment by siduck76** [comment]
I suppose this is resolved!

**Comment by G-Rowell** [comment]
@siduck76 
Bruh??? Read this

> @G-Rowell thanks for the quick answer, unfortunately, it didn't work. maybe I'm just too noob smile

**Comment by G-Rowell** [comment]
@Eduruiz 

Looks like we've lost some functionality with our big re-structure, you're right that placing it in `chadrc.lua` doesn't work.

I've already got some functionality to provide for this, so I'll make a note.

Meanwhile, just add the line to the bottom of your `init.lua`, eg
`vim.cmd[[ set cmdheight=10 ]]`

NOTE: this will be overwritten with the next NvChad update, when this happens move all your stuff to the new user space function in `chadrc.lua`.

Let's leave this open for now I think


G

**Comment by G-Rowell** [comment]
@Eduruiz @phatsk @HoolaBoola 

My PR: https://github.com/NvChad/NvChad/pull/314

Should provide some good functionality for everyone to customise on-top of NvChad, with things like custom mappings & whatnot.

:smile:
G

**Comment by G-Rowell** [comment]
PR: #368 does an even better job,
it will replace my proposed PR #314 I think

**Comment by G-Rowell** [comment]
@phatsk 

Seems we are good to close this?

Assuming it can by lack of response.

---

PR #465 will even further improve the custom config functionality, though you should be able to do this right now.

G
