### ISSUE TITLE
Copying test with mouse 

### ISSUE THREAD

**Issue by macarthy** [NvChad/NvChad#370]
**Describe the bug**
I chouldn't copy text on the Mac 

**To Reproduce**
1. Go to a file
2. Click on hightlight line with mouse 
3. <C-c>
4 . try to paste  to another app 

I added

 map("", "<LeftRelease>", '"*ygv', opt)
to  mapping lua and now it works .

**Comment by TomWright** [comment]
I can't seem to copy either - where exactly did you add the new mapping line?

**Comment by ashincoder** [comment]
keymappings are added in mappings.lua

**Comment by ashincoder** [comment]
``
