### ISSUE TITLE
Enable custom plugin   and  lists of linters and Lsp servers to be installed 

### ISSUE THREAD

**Issue by macarthy** [NvChad/NvChad#371]
**Is your feature request related to a problem? Please describe.**

I'd like a why to automatically install my list to linters and lsp servers 

**Describe the solution you'd like**

Perhaps a file per language m that sepecify the normal tabs etc put also has a list of parsesm lspServer etc

**Comment by siduck76** [comment]
there wouldnt be an automatic way for this . You have to add it yourself since nvchad doesnt come with supporting any language . Just add whatever you want. ( once the custom hooks PR gets merged )

**Comment by siduck76** [comment]
@macarthy setting up null-ls.nvim is fairly easy , check a quick example : 

https://nvchad.github.io/config#setup-formatting-and-linting
