### ISSUE TITLE
I'd like to turn off some options in the plugins 

### ISSUE THREAD

**Issue by macarthy** [NvChad/NvChad#372]
**Is your feature request related to a problem? Please describe.**

the virtual text in lsp dianostics is very distracting, I would perfect a sidebar icon and an underlineding the issue , hover over the line the issue and maybe show it in the status bar

**Describe the solution you'd like**
I'd would prefer a sidebar icon and an underlined issue, that you could hover over to get info 

In general if we could create a {{filename}}.local.lua file that defines extra plugins  or mapping etc that would not get trashed on the up that would be great

I'd really like hop.nvim  and test-vim

**Comment by benjamin-shih** [comment]
Hey,

I found that if you would like to just disable the virtual text, you can navigate to /lua/plugins/configs and in lspconfig.lua edit the virtual_text variable to false as such: 
```
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
virtual_text = false,
-- {
--   prefix = "",
--   spacing = 0,
-- },
signs = true,
underline = true,
update_in_insert = false, -- update diagnostics insert mode
})
```

**Comment by macarthy** [comment]
Yeah that is what I did but it gets trashed on update.

**Comment by siduck76** [comment]
> Yeah that is what I did but it gets trashed on update.

no worries , https://github.com/NvChad/NvChad/pull/368 has been merged to test branch and soon it'll get merged to main!

**Comment by G-Rowell** [comment]
Hey @macarthy @benjamin-shih 

The PR by Morten & I, #465 will fix this!

It currently has an `override` for changing the `lsp diagnostics`, which is exactly what you seem to want!
You'll be able to `override` this from within your `lua/custom/` area, so it will be protected from conflicts hopefully!


Should we close this when the PR is merged?

G

**Comment by siduck76** [comment]
the PR is merged , check the config docs https://nvchad.github.io/config
