### ISSUE TITLE
Need help to install plugins like NerdTree which are not in lua

### ISSUE THREAD

**Issue by pathakraul** [NvChad/NvChad#373]
Hi,

I need to help to install the plugins which are not in lua, I needed NerdTree with NvChad. I don't know if plugins which are not in lua can be installed with Packer.

Is there a way to install?

**Comment by siduck76** [comment]
You install them the same way you install lua plugins

**Comment by siduck76** [comment]
Nerdtree is really gonna make nvim slow , good luck

**Comment by NarutoXY** [comment]
Packer supports all vim plugins. You can install vimscript and python plugins the same way you install lua plugins. It might be good to have a look on packer.nvim wiki.

**Comment by pathakraul** [comment]
> Nerdtree is really gonna make nvim slow , good luck

Yeah, I can observe that now.

**Comment by pathakraul** [comment]
Which plugin recommend for C/C++ symbols window??

**Comment by G-Rowell** [comment]
> Which plugin recommend for C/C++ symbols window??

Probably best to do some researching!!
Google is a good friend,

I don't know of any community members who primarily use C/C++

**Comment by siduck76** [comment]
I hope this is resolved!
