### ISSUE TITLE
Why non-standard colorschemes?

### ISSUE THREAD

**Issue by marcomayer** [NvChad/NvChad#397]
I guess I'm mostly curious as it's easy to work around but why do you not simply use the "official" colorschemes of the included themes? Like gruvbox and nord for example. Most users probably like having a consistent experience throughout their terminals.

Might consider changing this or adding "original"-themes :-)

**Comment by siduck76** [comment]
> Great, thanks for the replies! @siduck76 I'd be happy to have the standard nord scheme (https://www.nordtheme.com/docs/colors-and-palettes) and gruvbox-dark (https://github.com/morhetz/gruvbox) so they match with my other terminals.

done

**Comment by marcomayer** [comment]
wow, that was quick! thanks! Next time I'll add it myself and commit a PR.
