### ISSUE TITLE
PackerSync fails on clean install

### ISSUE THREAD

**Issue by morten-olsen** [NvChad/NvChad#399]
**Describe the bug**
`PackerSync` fails on newly install NvChad

If i remove line 180-231 from `lua/plugins/init.lua` (luasnips + cmp) `PackerSync` works fine, so seems to be related to that.

**To Reproduce**
1. Remove the `/plugin` folder
2. Open neovim and run `PackerSync`
3. `PackerSync`fails with `Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:214: Index out of bounds`

**Expected behavior**
No errors on `PackerSync`

**Desktop (please complete the following information):**
 - Operating System: Arch Linux + Sway
 - Terminal: termite & kitty
 - Version of Neovim: v0.6.0-dev+166-g8331cd13c

**Comment by siduck76** [comment]
could you use 0.5?

**Comment by morten-olsen** [comment]
@ siduck76  You are so absolutely right, downgrading to 0.5.0 removed the issue :+1:

**Comment by wbthomason** [comment]
@siduck76 Do you know of a change in v0.6.0 that causes this issue? I'm trying to track down this bug on `packer`'s side.

**Comment by siduck76** [comment]
@wbthomason 

Im not sure , I use v0.5. The issue might be with our lazy loading module afterall since it works if I removed the lazy_load function call from setup function of some [plugins](https://github.com/NvChad/NvChad/blob/main/lua/plugins/init.lua#L101) 

our lazy load [function](https://github.com/NvChad/NvChad/blob/main/lua/plugins/init.lua#L101)

**Comment by siduck76** [comment]
Try it yourself :

```
packer_lazy_load = function(plugin, timer)
   if plugin then
      timer = timer or 0
      vim.defer_fn(function()
         require("packer").loader(plugin)
      end, timer)
   end
end
```

```
setup = function()
         require("core.utils").packer_lazy_load "yourplugin"
 end,
 ```

**Comment by wbthomason** [comment]
Yeah, there's some interaction between `vim.defer_fn` and `packer`'s async logic (e.g. https://github.com/wbthomason/packer.nvim/issues/583), but I haven't figured out what just yet.
