### ISSUE TITLE
How to customize?

### ISSUE THREAD

**Issue by 7c78** [NvChad/NvChad#401]
1. I want to disable smooth scroll. I set `neoscroll` to `false` in `chadrc.lua`, but it does not work.
2. I installed nerd fonts and materialdesignicons but the fonts seem not working correctly.
Nvim-tree
![nvim1](https://user-images.githubusercontent.com/42330300/131235890-be6e4940-bfc9-4a7b-92ec-47337b82f251.png)
Galaxyline
![nvim2](https://user-images.githubusercontent.com/42330300/131235891-bfb1c50e-a397-4f24-9a20-0fa2a99f090c.png)
fonts
![nvim3](https://user-images.githubusercontent.com/42330300/131235892-410ec1ad-c0d2-4fb9-af38-38ab77e1b7cf.png)

**Comment by siduck76** [comment]
you need to set the fonts in your terminal too . And your filemanage doesnt look like the one in windows so why windows compatible font?

**Comment by siduck76** [comment]
Do :PackerSync after disabling neoscroll , works for me :/

**Comment by 7c78** [comment]
Thank you.
1. I run `:PackerSync` and it works.

2. > And your filemanage doesnt look like the one in windows so why windows compatible font?

What do you mean? I follow your instruction and set fonts to my terminal, then everything is good now.

**Comment by siduck76** [comment]
oh that was a typo lul , I mean your filemanager looks like nautilus , thunar etc , which are on linux and you were using windows compatible font which felt weird

**Comment by 7c78** [comment]
I use the default filemanager of ubuntu 20.04. JetBrainsMono, which I downloaded at https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip, include these Windows compatible fonts.
