### ISSUE TITLE
When file contains error, the Lsp messes the layout

### ISSUE THREAD

**Issue by kriive** [NvChad/NvChad#403]
**Describe the bug**
When using NvChad after installing `:LspInstall cpp`, and the file being edited contains some errors the writing flow is rendered unusable.

**To Reproduce**
1. Open a file called main.c
2. Write an invalid C code
3. See your writing prompt behaving weirdly

**Expected behavior**
It should keep the error prompt at a distance and writing should not misbehave

**Screenshots**
[![asciicast](https://asciinema.org/a/fdI3f3T1MyeMf9DltkKBnHsk8.svg)](https://asciinema.org/a/fdI3f3T1MyeMf9DltkKBnHsk8)

**Desktop (please complete the following information):**
 - Fedora 34 with sway
 - terminal: foot 1.8.2
 - neovim: v0.6.0-dev+198-g81f4de08b

**Comment by siduck76** [comment]
why neovim 0.6? use 0.5

**Comment by siduck76** [comment]
works fine for me :l

**Comment by kriive** [comment]
Oooooopsies, using 0.5 works fine! Feel free to close this. Super nice project btw
