### ISSUE TITLE
Incorrect icons

### ISSUE THREAD

**Issue by jpleyvat** [NvChad/NvChad#404]
**Describe the bug**
I have this icons. 

![image](https://user-images.githubusercontent.com/20483919/131269312-8d07ba36-cd6d-4f69-bed8-01a31d2398a5.png)

Can you guys help me to get the ones you show in the repo?

**To Reproduce**
1. Clean install then open nvim

**Expected behavior**
![image](https://user-images.githubusercontent.com/20483919/131269312-8d07ba36-cd6d-4f69-bed8-01a31d2398a5.png)

**Desktop (please complete the following information):**
 - Operating System: Arcolinux
 - Terminal: Kitty
 - Version of Neovim: 0.5.0

**Comment by siduck76** [comment]
Your terminal issue , install nerdfonts and set a nerdffont in kitty. You should've known this :c .

**Comment by jpleyvat** [comment]
Thank you. Sorry. Bad weekend 😞
