### ISSUE TITLE
Gitignore chadrc

### ISSUE THREAD

**Issue by Shivansh-007** [NvChad/NvChad#408]
**Is your feature request related to a problem? Please describe.**
Since the user-config is written to `chadrc.lua`, so if any changes are done it would be edited. Thus when you do a `git rebase` to upstream(origin), it won't accept it until one commits it into the index.

**Describe the solution you'd like**
I would like to `.gitignore` `chadrc.lua` as one can already see the config options in `default_config.lua`, soo when the user installs NvChad they could make a copy of it. We could make a simple script with these three commands (cloning config, making a config copy and then running packer-sync).

**Describe alternatives you've considered**
This is the only possible solution that I can think of.

**Comment by G-Rowell** [comment]
`.gitignore`ing `chadrc.lua` won't work as we want it in our git repo (which conflicts with having it in `.gitignore`).

We are currently in the process of overhauling the user config part of NvChad.

My suggested method is to `git add -Av` your files and commit them `git pull origin --rebase`, and then rebase your commits on top of pulled/updated files.

I think this is good to close?
We appreciate the issue & thought.

Hope this helps,
G

**Comment by Shivansh-007** [comment]
That would do but what's the reason for having it inside the repo, we already have `default_config.lua`? Which is basically a chadrc template when the user clones the config.

**Comment by morten-olsen** [comment]
Think the upside to having it inside the repo is that if breaking chances are introduced to chadrc you would get a merge conflict indicating the changes, instead of stuff just starting to not work or break

**Comment by morten-olsen** [comment]
Guess another way of dealing with it would be to copy it on start up if it does not exists, but that would most likely require some sort of model validation to avoid breaking changes going unnoticed

**Comment by Shivansh-007** [comment]
You can have a command to compare the outer structure of the default config and the `chadrc`, and if structural changes are found or a key is missing it can display them to the user and give them the option if it should add them or the user would like to do it.

**Comment by Shivansh-007** [comment]
I know about that, but I dunno how that solves my issue.

**Comment by G-Rowell** [comment]
Hi there @Shivansh-007,

we can't `.gitignore` `chadrc.lua`,

so there are two solutions,
1. use the in-built NvChad updater
2. commit your changes locally (this could also be great for keeping track of your changes), then `git pull --rebase`

My PR #465 will greatly improve the custom config situation, soz for the delay!!


G

**Comment by G-Rowell** [comment]
Hi @Shivansh-007 

I think this is good to close now,
as we have merged the custom config overhaul in #465.

G

**Comment by Shivansh-007** [comment]
Hey @siduck76 @G-Rowell,

I have been on a break due to my exams and I wasn't able to comment. This does partially mention my issue, the other part that is missing is that the "user specific config" is not `.gitignore`d, so when updating them we either need to stash & commit them or copy them to a tmp place and paste them back in after updating.

Also great work on the new config overhaul.

**Comment by Shivansh-007** [comment]
Looks, like this got reverted in 5bf92c524689642f839ec99b7253f06a7ffdd56c. Why was this done so @siduck76? There is no commit description.

**Comment by siduck76** [comment]
> Looks, like this got reverted in [5bf92c5](https://github.com/NvChad/NvChad/commit/5bf92c524689642f839ec99b7253f06a7ffdd56c). Why was this done so @siduck76? There is no commit description.

contents in the nvimtree wont be visible at all , and telescope's find_files too :/
