### ISSUE TITLE
Doom One Theme

### ISSUE THREAD

**Issue by Shivansh-007** [NvChad/NvChad#409]
Particularly inspired by this one https://github.com/NTBBloodbath/doom-one.nvim

Something looking like this (akin's setup)...

![image](https://user-images.githubusercontent.com/69356296/131347902-d464473a-72cf-4f17-a281-11d5c4abcc7c.png)

**Comment by siduck76** [comment]
PR's are welcomed for this ;(

**Comment by Shivansh-007** [comment]
Well, I will give it a try, _be ready to change all of it_ ;(

**Comment by siduck76** [comment]
> Well, I will give it a try, _be ready to change all of it_ ;(

just add the syntax theme ( nvim-base16 theme ) https://github.com/chriskempson/base16/blob/master/styling.md

I'll add the nvchad highlights theme :D

**Comment by ashincoder** [comment]
@siduck76 here local base0 = "#1B2229"
local base1 = "#1c1f24"
local base2 = "#202328"
local base3 = "#23272e"
local base4 = "#3f444a"
local base5 = "#5B6268"
local base6 = "#73797e"
local base7 = "#9ca0a4"
local base8 = "#DFDFDF"
local base9 = "#E6E6E6"

local grey = base4
local red = "#ff6c6b"
local orange = "#da8548"
local green = "#98be65"
local yellow = "#ECBE7B"
local blue = "#51afef"
local dark_blue = "#2257A0"
local magenta = "#c678dd"
local light_magenta = utils.Lighten(magenta, 0.4)
local violet = "#a9a1e1"
local cyan = "#46D9FF"
local white = "#efefef"

-- local bg = "#121317"
local bg = "#14151a"
local bg_alt = "#21242b"
local bg_highlight = "#21252a"
local bg_popup = "#3E4556"
local bg_statusline = bg_popup
local bg_highlighted = "#4A4A45"

local fg = "#bbc2cf"
local fg_alt = "#6e767d"
local fg_highlight = utils.Lighten(fg, 0.2)

local tag = utils.Mix(blue, cyan, 0.5)

**Comment by siduck76** [comment]
@ashincoder the theme must be in this format first 
  
  https://github.com/NvChad/nvim-base16.lua/blob/master/lua/themes/blossom-base16.lua

**Comment by hsheikhali1** [comment]
Looks like the base colours are there but how exactly do we use them?

**Comment by siduck76** [comment]
> Looks like the base colours are there but how exactly do we use them?

i'll add the doom theme myself after 2 days so wait up!

**Comment by hsheikhali1** [comment]
@siduck76 if you can get me up to speed I can help out :)

**Comment by siduck76** [comment]
> @siduck76 if you can get me up to speed I can help out :)

currently need help with the updater!

![image](https://user-images.githubusercontent.com/59060246/134782446-63ba5247-c30e-4517-9408-4a5b03d6b01e.png)

ik some paths need to be changed , but im busy with writing overall config docs rn :)

**Comment by hsheikhali1** [comment]
I'll take a look when I can 🙂

**Comment by siduck76** [comment]
> @siduck76 if you can get me up to speed I can help out :)

https://nvchad.github.io/contribute#how-to-submit-themes

**Comment by G-Rowell** [comment]
> ik some paths need to be changed , but im busy with writing overall config docs rn :)

I've changed most of the paths in my WIP branch though?

**Comment by siduck76** [comment]
> > ik some paths need to be changed , but im busy with writing overall config docs rn :)
> 
> I've changed most of the paths in my WIP branch though?

there are still some that need to be changed i think , maybe in the extensions/nvchad/init.lua

**Comment by siduck76** [comment]
https://github.com/NvChad/nvim-base16.lua/commit/3efab6817be364a9ee004f6afc91fdcd4ee72b2e
