### ISSUE TITLE
Add nvim-hlslens

### ISSUE THREAD

**Issue by Shivansh-007** [NvChad/NvChad#410]
I think this is something a lot of users would like to have and hence I am suggesting it here. The plain `/` nvim command is boring, you don't know how many suggestions are there, how are left to go and how are already passed. And it is FAAAAAAAAAAST 💨

![Example Usage](https://user-images.githubusercontent.com/17562139/115105257-5a0f6f00-9f90-11eb-92cf-801fe73a45fb.gif)

**Comment by siduck76** [comment]
ig we'll just have the basic functionality , once the custom hook feature gets merged in the main branch , the user will be able to add own config and plugins etc
