### ISSUE TITLE
colorscheme autocommand not getting executed

### ISSUE THREAD

**Issue by martindemello** [NvChad/NvChad#418]
**Describe the bug**
I added the following to `.config/nvim/lua/core/autocmds.lua`:

```
-- Set colorscheme bg to black
vim.cmd [[ au ColorScheme * highlight Normal guibg=black ]]
```

 but it does not get triggered when I start nvim (I assume because the colorscheme gets set before autocommands are read in). 

Where should I put the autocommand so that it gets read early enough?
 
**Desktop (please complete the following information):**
 - Operating System: linux
 - Terminal: terminator
 - Version of Neovim: 0.5

**Comment by G-Rowell** [comment]
This likely won't work, as NvChad doesn't use normal colour schemes.

NvChad doesn't use normal colour schemes as we set a whole lot of plugin colours for you, if we were to use the in-built colour scheme then many plugins wouldn't have their colours set properly.

Check out this folder: https://github.com/NvChad/NvChad/tree/main/lua/colors

**Comment by martindemello** [comment]
ah, thanks. is there a hook to do what i want (essentially apply a theme and then set the Normal background to black) or do i need to edit highlights.lua directly?

**Comment by G-Rowell** [comment]
Hmmmm, there may be a solution in the coming days.

as we are right in the middle of testing a PR to greatly improve the custom user config for this.

I can take a look today or tomorrow as soon as I have the time!

**Comment by G-Rowell** [comment]
For now you could edit `highlights.lua`, or even better, edit a colourscheme in `lua/colors/themes/`

Though this is a hack, and not a long-term solution

**Comment by martindemello** [comment]
thanks, looking forward to seeing the new custom config :)
