### ISSUE TITLE
Green background colour outside of tmux

### ISSUE THREAD

**Issue by TomWright** [NvChad/NvChad#419]
**Describe the bug**
When using tmux nvim displays as expected, but outside of tmux I get a green background. It doesn't look like the theme is correctly applying.

I'm using the standard Apple Terminal.

**To Reproduce**
1. Open apple terminal
2. `$ nvim`

**Expected behavior**
The standard nvchad theme.

**Screenshots**
In tmux:
![image](https://user-images.githubusercontent.com/935867/131684779-dd2b87a3-4d80-45d2-9a46-87f9aae78f62.png)

Outside of tmux:
![image](https://user-images.githubusercontent.com/935867/131684853-fdd65044-2eaa-44fe-b78c-4e334a7052f4.png)

**Desktop (please complete the following information):**
 - Operating System: Big Sur 11.5.2
 - Terminal: Apple Terminal 2.11
 - Version of Neovim: 1.0.0

**Additional context**

**Comment by siduck76** [comment]
https://github.com/NvChad/NvChad/issues/2

**Comment by siduck76** [comment]
itermmmmm :angry:

**Comment by TomWright** [comment]
Ah sorry. Such an idiot. Iterm solved the problem

**Comment by sbritorodr** [comment]
If someone read this, just install [iTerm2](https://iterm2.com/).
