### ISSUE TITLE
Why dashboard wont open firstly?

### ISSUE THREAD

**Issue by dessasin** [NvChad/NvChad#420]
Every neovim opening its starts with blank buffer. Dashboard should show at first I thing..

**Comment by G-Rowell** [comment]
The team has decided that `Dashboard` should not show by default. (it is enabled by default though).

Currently we don't have a `nice way` to show the dashboard on VimEnter, we will have a proper way next week though.

**Comment by siduck76** [comment]
@dessasin  https://github.com/NvChad/NvChad/wiki#dashboard
