### ISSUE TITLE
Better escape custom esc_insertmode in chadrc doesn't get applied

### ISSUE THREAD

**Issue by ZeroX-DG** [NvChad/NvChad#422]
**Describe the bug**
I want to customize the `esc_insertmode` shortcut in chadrc to `jj` but it doesn't seem to apply. After debugging, I found that no matter what you put in `esc_insertmode`, the result always get overrided with the default config. So I have to edit the default config file & it works.

**To Reproduce**
1. Go to chadrc
2. Change `M.mappings.plugin.esc_insertmode` to `jj` or add `jj` to the list.
3. Restart & the shortcut doesn't applied

**Expected behavior**
The new `esc_insertmode` shortcut should be applied

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Terminal: Kitty
 - Version of Neovim: 0.6.0-dev

**Comment by siduck76** [comment]
you need to set the mapping in  chadrc.lua 
![image](https://user-images.githubusercontent.com/59060246/131782802-a21d65b7-bcf2-4f30-bdd5-f428367b1838.png)


Also I suggest not using 0.6v! use 0.5 

```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim
```

**Comment by ZeroX-DG** [comment]
@siduck76 I did set the mapping in chadrc.lua but it doesn't get applied. It could be a neovim issue but I'm not sure. I'll downgrade it to 0.5 to see how it goes.

**Comment by ZeroX-DG** [comment]
Nope, that didn't work, I'm on 0.5.0 and I still get that bug
![nvimbug](https://user-images.githubusercontent.com/12984316/131799358-9e3f9112-fdd7-4d70-b9f9-fc3d7d1ad1dc.gif)

**Comment by ashincoder** [comment]
> you need to set the mapping in chadrc.lua
> ![image](https://user-images.githubusercontent.com/59060246/131782802-a21d65b7-bcf2-4f30-bdd5-f428367b1838.png)
> 
> Also I suggest not using 0.6v! use 0.5
> 
> ```
> sudo add-apt-repository ppa:neovim-ppa/stable
> sudo apt-get update
> sudo apt-get install neovim
> ```

And also @siduck76 it doesn't matter really which neovim version is used. nvim 0.5.0 is the stable one but version really doesn't matter. You have to have version above 0.5.0

**Comment by siduck76** [comment]
> > you need to set the mapping in chadrc.lua
> > ![image](https://user-images.githubusercontent.com/59060246/131782802-a21d65b7-bcf2-4f30-bdd5-f428367b1838.png)
> > Also I suggest not using 0.6v! use 0.5
> > ```
> > sudo add-apt-repository ppa:neovim-ppa/stable
> > sudo apt-get update
> > sudo apt-get install neovim
> > ```
> 
> And also @siduck76 it doesn't matter really which neovim version is used. nvim 0.5.0 is the stable one but version really doesn't matter. You have to have version above 0.5.0

0.6v got us tons issues lately

**Comment by G-Rowell** [comment]
0.6 is bringing lots of issues,

I & Morten are working on a big overhaul of the user custom config which will fix this

**Comment by siduck76** [comment]
@ZeroX-DG update nvchad config and try adding multiple keys

**Comment by ZeroX-DG** [comment]
@siduck76 Confirm that the bug is fixed. Thank you so much for your great work!
