### ISSUE TITLE
Kotlin Icon not showing

### ISSUE THREAD

**Issue by rafa-acioly** [NvChad/NvChad#427]
**Describe the bug**
With a fresh `NvChad` installation the kotlin icons are not showing.

I'm using Jetbrains Mono Regular, I've also tried change the font to FiraCode.

![Captura de tela de 2021-09-03 11-28-02](https://user-images.githubusercontent.com/11068059/132021996-5302f29b-3694-430c-bb93-2c896858cc49.png)

**Comment by siduck76** [comment]
oh sorry I forgot to mention in the docs! you need material design icon font for this

**Comment by rafa-acioly** [comment]
Are you going to add it to the docs? 

Can you tell me how can I install it?

**Comment by siduck76** [comment]
> Are you going to add it to the docs?
> 
> Can you tell me how can I install it?

https://materialdesignicons.com/ download the fonts 

and put them on ~/.local/share/fonts folder, idk about macos/windows
