### ISSUE TITLE
Ctrl+Backspace deltes previous word

### ISSUE THREAD

**Issue by kamack38** [NvChad/NvChad#428]
How can I add that `Ctrl+Backspace deltes` previous word?

**Desktop:**
 - Windows 10
 - Windows Terminal
 - v0.5.0

**Comment by bjesus** [comment]
I've added `vim.cmd [[ inoremap <C-BS> <C-w> ]]` to my `chadrc.lua`. Note that you might need to adjust your terminal to support it, see https://old.reddit.com/r/neovim/comments/okbag3/how_can_i_remap_ctrl_backspace_to_delete_a_word/

**Comment by kamack38** [comment]
Where in `chadrc.lua` shall I put it?

**Comment by bjesus** [comment]
Just before the `return M` at the end of file.

**Comment by kamack38** [comment]
It doesn't work.

**Comment by bjesus** [comment]
Well I have this line in my config and it works fine, so I would assume it actually works but your terminal isn't configured to pass the key correctly. 

I would look for advice here: https://github.com/microsoft/terminal/issues/755 (perhaps `{ "keys": "ctrl+backspace", "command": { "action": "sendInput", "input": "\u0017" },` is what you need?)

To confirm that it works you can try using a different terminal application. I'm using Alacritty and I had to adjust the keybinding by adding the following to my config:
```
key_bindings:
  - { key: Back, mods: Control, chars: "\x17" }
```

**Comment by kamack38** [comment]
I've added 
```
vim.api.nvim_set_keymap('i', '<C-BS>', '<C-W>', {noremap = true})
```
into `chad.rc` and
```json
{  
       "command": { "action": "sendInput", "input": "\u0017"},
       "keys": "ctrl+backspace"
},
```
Into `settings.json` and It works!

**Comment by kamack38** [comment]
Is there any way to add *the same* functionality, but for `Ctrl + Del` ?

**Comment by kamack38** [comment]
I've found that this setting works for `pwsh` (PowerShell 7.1.4) and `GitBash`, but it doesn't work for `Powershell 5.1`, but this ain't problem for me :)

**Comment by reactVishnu** [comment]
> Is there any way to add _the same_ functionality, but for `Ctrl + Del` ?

Hey, Did u able to find any workaround for ctrl + del? @kamack38

**Comment by kamack38** [comment]
> > Is there any way to add _the same_ functionality, but for `Ctrl + Del` ?
> 
> Hey, Did u able to find any workaround for ctrl + del? @kamack38 

Yes I did, I used the sendInput option with the following character sequence: `"input": "\u001B\u0064"`

**Comment by kamack38** [comment]
I think this is the thing I changed in my Windows Terminal, but I haven't used it since because I've switched to Linux. However I think it should work in any Terminal, because as far as I remember I've been using a similar thing in the kitty terminal.

**Comment by reactVishnu** [comment]
I'll check and let u know

**Comment by reactVishnu** [comment]
Hi , mine is working . I add this to my chadrc.lua file for deleting a word after the cursor,
vim.api.nvim_set_keymap('i', '<C-Del>', '<Esc>ldwi', {noremap = true})

**Comment by Sumanthbhumi** [comment]
hey can you send the correct keymap, i don't think it is correct. @reactVishnu

**Comment by reactVishnu** [comment]
HI
My Both command  @Sumanthbhumi 
`vim.api.nvim_set_keymap('i', '<C-BS>', '<C-W>', {noremap = true})
`
`vim.api.nvim_set_keymap('i', '<C-Del>', '<Esc>ldwi', {noremap = true})
`

**Comment by reactVishnu** [comment]
Let me know if it works? @Sumanthbhumi

**Comment by Sumanthbhumi** [comment]
`vim.api.nvim_set_keymap('i', '<C-BS>', '<C-W>', {noremap = true}) ` this works fine but second isn't working, I think it's may be cause of .json setting, would you care to show yours. Thanks! @reactVishnu

**Comment by reactVishnu** [comment]
okay, i use powershell btw, here's the settings.json file code for Ctrl + Del.

Path
C:\Users\Name\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
```
{
            "keys": "ctrl+del",
            "command":
            {
                "action": "sendInput",
                "input": "\u001B\u0064"
            }

}
```

**Comment by Sumanthbhumi** [comment]
> okay, i use powershell btw, here's the settings.json file code for Ctrl + Del.
> 
> Path C:\Users\Name\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
> 
> ```
> {
>             "keys": "ctrl+del",
>             "command":
>             {
>                 "action": "sendInput",
>                 "input": "\u001B\u0064"
>             }
> 
> }
> ```

yup! works fine now but if cursor is at the end, it deletes the previous second character lol and sometimes last character and goes to normal mod. I know there is defiantly workaround for it, but i don't use it very often so i am fine with it
