### ISSUE TITLE
help for install and using this plugin on windows

### ISSUE THREAD

**Issue by grimgort** [NvChad/NvChad#429]
hello,
I don't understand how to have the icons in neovim on a windows computer. I can't find how to do it on the internet... If anyone can help me it would be great
thanks
![image](https://user-images.githubusercontent.com/44238325/132037609-ea46b629-1153-446c-8a0b-af6c676dd879.png)

**Comment by siduck76** [comment]
Install jetbrainsmono windows compatible nerdfont and set that in your terminal! If you're new then just chrck nerdfonts repo's readme to know further

**Comment by marwan38** [comment]
@grimgort Ask siduck said. Go to https://www.nerdfonts.com/ and get the font that you want.

Open the windows terminal settings, that's pretty easy to get to. You click your profile (default, or whichever you're using) then go to appearance and it'll be one of the first things you see.

**Comment by grimgort** [comment]
I changed my font but nothing works:
![image](https://user-images.githubusercontent.com/44238325/132174442-57b56fed-24e2-461c-beaa-6b8b674781d7.png)

**Comment by grimgort** [comment]
With install.ps1 script from nerd-font repo, it s working. My bad. thanks
