### ISSUE TITLE
Add options for eslint and prettier

### ISSUE THREAD

**Issue by hsheikhali1** [NvChad/NvChad#431]
**Is your feature request related to a problem? Please describe.**
I'd like to start using nvchad full time since I love the overall configuration.. however at work we rely on tools like:
prettier, stylelint, and eslint.. And I have no idea how to get this in..

**Describe the solution you'd like**
Can we add a clean way to configure prettier? Maybe something we can add to `chardrc.lua`

**Describe alternatives you've considered**
There are no alternatives to eslint and prettier ;)

**Additional context**
Here is a screenshot of what the solution could look like. This works in my own personal config.. but would love to see it in nvchad
<img width="1448" alt="Screen Shot 2021-09-05 at 5 23 30 PM" src="https://user-images.githubusercontent.com/14851850/132141821-dae34a8e-7af0-4cb7-aa7b-783a90e22746.png">

**Screenshot**
<img width="1448" alt="Screen Shot 2021-09-05 at 5 21 46 PM" src="https://user-images.githubusercontent.com/14851850/132141787-f4153c07-adf6-44c4-a785-8d7ecb2003a6.png">

**Comment by marwan38** [comment]
I've stuck mine directly into the lspconfig file (similar to your setup) for now. I've heard that they plan to replace neoformat with null-ls soon, if so  then setting these up would become much easier to do and wouldn't need modification of the core files.

**Comment by felippepuhle** [comment]
@marwan38 can you put more infos about your `lspconfig` setup with `NvChad`? thanks!

**Comment by marwan38** [comment]
@felippepuhle It's all here: https://github.com/marwan38/NvChad/blob/main/lua/plugins/configs/lspconfig.lua#L109. I'm

**Comment by hsheikhali1** [comment]
So I tried to add my own linters and it doesn't work? In fact I get this lol..
<img width="1154" alt="Screen Shot 2021-09-12 at 4 39 04 PM" src="https://user-images.githubusercontent.com/14851850/133002126-266aa497-aa2a-4314-890c-37d8a7a9580d.png">

**Comment by hsheikhali1** [comment]
@marwan38 does this actually work? I tried literally copy-paste and it doesn't work

**Comment by hsheikhali1** [comment]
@marwan38 see how this does nothing ? :/
![image](https://user-images.githubusercontent.com/14851850/133007373-d1c1b1d1-7b02-4acc-a1be-a02368635a07.png)

Here is what my config looks like
![image](https://user-images.githubusercontent.com/14851850/133007430-da933aa7-6d90-4ee0-a390-e8d35e701643.png)

**Comment by marwan38** [comment]
> @marwan38 see how this does nothing ? :/
> ![image](https://user-images.githubusercontent.com/14851850/133007373-d1c1b1d1-7b02-4acc-a1be-a02368635a07.png)
> 
> Here is what my config looks like
> ![image](https://user-images.githubusercontent.com/14851850/133007430-da933aa7-6d90-4ee0-a390-e8d35e701643.png)

You have 2 different variables  nvim_lsp and lspconfig, not sure which does what. You are also calling setup twice.. you need to call it once. Change and add onto your if condition..

**Comment by hsheikhali1** [comment]
Yeah I ran an update and looks like the whole way they are handling lsp changed hence the two difference variables.. nice catch ! I've been staring at this all day and didn't catch that.

Yeah, wasn't sure if I should since it wasn't working but once I do, I'll slowly add it.. I forked the project so yeah lol thanks @marwan38

**Comment by marwan38** [comment]
@hsheikhali1 add in the lua lsp, it'll point it out straight away.
@siduck76 @G-Rowell I think nvchad should come with the lua lsp configured out of the box. Every user will end up installing it anyway.

**Comment by hsheikhali1** [comment]
Yeah I think it should be setup by default. I got it all working the way I want it to now which is dope ! Thanks again for helping.

**Comment by G-Rowell** [comment]
@marwan38,
I think starting with lua configured out of the box is a good idea, as we expect all NvChad users to do some very minimal config work.

Though I think we should have an option to disable this? (have enabled by default though).

Thank you v. much for helping Hsh!

---

@hsheikhali1,

sounds like this is solved? Is this good to close?

Btw, my PR #465  will greatly improve the custom config situation




G

**Comment by siduck76** [comment]
the user can now integerate his config well , check the docs 

https://nvchad.github.io/config

**Comment by javidrashid** [comment]
@siduck  How do I kick in the linting or formatting/prettier for my ts files, I have the config set up properly and it all looks good 

Running :LspInfo gives me this....

```
2  client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, pid: 34232, bufnr: [1])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /path/to/project
 	cmd:             typescript-language-server --stdio
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [1])
 	filetypes:       javascriptreact, jsonc, typescriptreact, typescript, markdown, javascript, json, html, css, lua, sh, cuda, cs, cpp, java, c
 	autostart:       false
 	root directory:  /path/to/project
 	cmd:             nvim

```

I am unable to kick in the linting or fomatting for my code. Do I need to fire any commands to lint/format my code?

Thanks

**Comment by siduck** [comment]
> @siduck How do I kick in the linting or formatting/prettier for my ts files, I have the config set up properly and it all looks good
> 
> Running :LspInfo gives me this....
> 
> ```
> 2  client(s) attached to this buffer: 
>  
>  Client: tsserver (id: 1, pid: 34232, bufnr: [1])
>  	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
>  	autostart:       true
>  	root directory:  /path/to/project
>  	cmd:             typescript-language-server --stdio
>  
>  Client: null-ls (id: 2, pid: 5001, bufnr: [1])
>  	filetypes:       javascriptreact, jsonc, typescriptreact, typescript, markdown, javascript, json, html, css, lua, sh, cuda, cs, cpp, java, c
>  	autostart:       false
>  	root directory:  /path/to/project
>  	cmd:             nvim
> ```
> 
> I am unable to kick in the linting or fomatting for my code. Do I need to fire any commands to lint/format my code?
> 
> Thanks

check our format & linting docs

**Comment by yusiwen** [comment]
> > @siduck How do I kick in the linting or formatting/prettier for my ts files, I have the config set up properly and it all looks good
> > Running :LspInfo gives me this....
> > ```
> > 2  client(s) attached to this buffer: 
> >  
> >  Client: tsserver (id: 1, pid: 34232, bufnr: [1])
> >  	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
> >  	autostart:       true
> >  	root directory:  /path/to/project
> >  	cmd:             typescript-language-server --stdio
> >  
> >  Client: null-ls (id: 2, pid: 5001, bufnr: [1])
> >  	filetypes:       javascriptreact, jsonc, typescriptreact, typescript, markdown, javascript, json, html, css, lua, sh, cuda, cs, cpp, java, c
> >  	autostart:       false
> >  	root directory:  /path/to/project
> >  	cmd:             nvim
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am unable to kick in the linting or fomatting for my code. Do I need to fire any commands to lint/format my code?
> > Thanks
> 
> check our format & linting docs

Where is the format & linting docs, plz? I cannot find them on official website, and search with no results

**Comment by siduck** [comment]
@yusiwen no docs needed for it. Just use nvim lint and conform plugin, conform plugin is even added by default in nvchad
