### ISSUE TITLE
LuaSnips error when entering insert mode

### ISSUE THREAD

**Issue by tannerellen** [NvChad/NvChad#432]
**Describe the bug**
On a fresh install of NVChad entering insert mode or accessing anything that uses insert mode (like telescope) results in an error:

"Error executing vim.schedule lua callback: ...k/packer/opt/LuaSnip/lua/luasnip/loaders/from_vscode.lua:70: bad argument #1 to 'concat' (table expected, got nil"

**To Reproduce**
1. Install NVChad
2. enter insert mode "I"
3. error is shown

**Expected behavior**
No error should be shown

**Screenshots**
<img width="1280" alt="luasnips-error" src="https://user-images.githubusercontent.com/930897/132257001-e670b15f-4aea-49b0-8a16-31eeb88ff99e.png">

**Desktop (please complete the following information):**
 - Operating System: Ubuntu
 - Terminal: iTerm 2
 - Version of Neovim: 0.5

**Additional context**

**Comment by procoder-me** [comment]
![nvchad](https://user-images.githubusercontent.com/87576846/132257181-d9ee68bc-dcfe-4d16-8d1a-0e7b674322ed.png)
It is caused somewhere here,

**Comment by tannerellen** [comment]
I am no longer able to reproduce this issue. I don’t see any upstream updates from any of the snippet plugins that would explain a fix. Feel free to close this issue if appropriate.

**Comment by siduck76** [comment]
This looks like an upstream issue , if you face this again then file an issue on the luasnip repo
