### ISSUE TITLE
running neovim gives this error.

### ISSUE THREAD

**Issue by onlyvip** [NvChad/NvChad#435]
![image](https://i.imgur.com/qpxMheC.png)
i dont know what might be causing it. 
my neovim version:
https://ezup.dev/p/ret5jg

**Comment by siduck76** [comment]
> ![image](https://camo.githubusercontent.com/9740bd5d72533364b161d57c4eef4b4705d272fc383dc29c5ea8697dec535099/68747470733a2f2f692e696d6775722e636f6d2f7170784d6865432e706e67)
> i dont know what might be causing it.
> my neovim version:
> https://ezup.dev/p/ret5jg

feline.nvim ( the statusline plugin ) has changed its config today ,so Ig we need to update our config too. just press enter to skip the error for now. I have an exam tomorrow so cant help today ;(

**Comment by marcomayer** [comment]
@siduck76 #438 should fix this.

**Comment by siduck76** [comment]
> @siduck76 #438 should fix this.

thanks a lot!
