### ISSUE TITLE
Request for a dedicated Discussions Section in github / a matrix room or discord server.

### ISSUE THREAD

**Issue by CTZxVULKAN** [NvChad/NvChad#441]
The project has quiet matured and grown over time and has a stable user base now .

It would be nice if we had a discussions section ( people could discuss Q/A over there instead of making new issues every time over petty thing ), a dedicated discord server would be great for people loving this project to hang out and discuss stuff and if we want to go full Foss why not a matrix room ?

Allowing like minded people passionate for this project to chat and discuss matters together will help in the growth of the project with fresh ideas and more contributors.

Please share your thoughts on this :)

**Comment by siduck76** [comment]
discord server https://discord.com/invite/gADmkJb9Fb

**Comment by siduck76** [comment]
The matrix room is still on the way , Idk how to bridge a discord channel with a matrix group . feel free to help with its integration :)

**Comment by CTZxVULKAN** [comment]
Sure I know how to bridge a matrix room with a discord server.
I can help with that.
Do you have an existing matrix room or should i create one ?
