### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by HypsterOP** [NvChad/NvChad#444]
**Describe the bug**
Error while launching neovim

**To Reproduce**
1. Launch Neovim
2. Sync packages
3. Launch neovim again and you will see the error.

**Screenshots**
[Screen Shot](https://ibb.co/8Xd6GX0)

**Desktop (please complete the following information):**
 - Windows
 - Windows Terminal
 - 0.5.0

**Additional context**
I hope you can fix it.

**Comment by CT3** [comment]
I get a similar error on windows cement out lsp-install (as it only works for Linux) and see if you still get the error

**Comment by siduck76** [comment]
ig the current lspinstall isnt working properly for windows , it works for linux/macos

**Comment by siduck76** [comment]
we're thinking of removing lspinstall and make the lspconfig easier

**Comment by HypsterOP** [comment]
> 
> 
> we're thinking of removing lspinstall and make the lspconfig easier

Ok! Notify me when it comes out. :)

**Comment by CT3** [comment]
We could go for 
https://github.com/williamboman/nvim-lsp-installer
instead it has both linux and windows support

**Comment by HypsterOP** [comment]
> We could go for
> https://github.com/williamboman/nvim-lsp-installer
> instead it has both linux and windows support

Let me give it a try!

**Comment by siduck76** [comment]
> I get a similar error on windows comment out lsp-install (as it only works for Linux) and see if you still get the error

ive removed lspinstall , update your config 
https://github.com/NvChad/NvChad/commit/4c025cd1bf67264fd4f12747569c2cbb042e7093

and write the language's lsp name as per lspconfig's config.md
