### ISSUE TITLE
install on nixos cwctype not found plugin treesitter

### ISSUE THREAD

**Issue by Vertecedoc4545** [NvChad/NvChad#446]
**Describe the bug**

**To Reproduce**
install nixos
install neovim
install nvchad 
   (on the command nvim +'hi NormalFloat guibg=#1e222a' +PackerSync you will see this error:
   (nvim-treesitter[lua]: Error during compilation
     src/scanner.cc:2:10: fatal error: 'cwctype' file not found
     #include <cwctype>
         ^~~~~~~~~)
**Expected behavior**
installation correctelly finished

**Desktop (please complete the following information):**
 - NixOs
 - alacritty
 - v0.5.0

**Comment by NarutoXY** [comment]
I'm using neovim v0.6 on nixOS and it solved this problem. Maybe that will help.

**Comment by NarutoXY** [comment]
https://github.com/nix-community/neovim-nightly-overlay/

**Comment by siduck76** [comment]
> https://github.com/nix-community/neovim-nightly-overlay/

dang mjlbach himself manages this build :0

**Comment by G-Rowell** [comment]
@Vertecedoc4545 

As NarutoXY said, does NeoVim 0.6 solve this issue?

**Comment by Vertecedoc4545** [comment]
it solves the error

**Comment by Vertecedoc4545** [comment]
THANKYOU!!!
