### ISSUE TITLE
Is there a way to install only NvChad colorschemes as plugin?

### ISSUE THREAD

**Issue by qvieth** [NvChad/NvChad#449]
NvChad's color schemes are so good, but it seems like there isn't a way to install only the color schemes. Perhaps an instruction on how to set it up would be really helpful for many vim users.

**Comment by siduck76** [comment]
if this plugin works on vim then lemme know https://github.com/norcalli/nvim-base16.lua

**Comment by qvieth** [comment]
Oh https://github.com/norcalli/nvim-base16.lua only works for neovim,  so can these colorschemes be install as plugin on neovim? Thanks @siduck76 !

**Comment by siduck76** [comment]
> Oh https://github.com/norcalli/nvim-base16.lua only works for neovim, so can these colorschemes be install as plugin on neovim? Thanks @siduck76 !

yep

**Comment by marwan38** [comment]
I was playing around with my own nvim config and wanted to install these colorschemes (Because they're the best i've seen), on a barebones nvim config. Would it work if i installed this plugin and just set `colorscheme nordchad` for example?

**Comment by siduck76** [comment]
> I was playing around with my own nvim config and wanted to install these colorschemes (Because they're the best i've seen), on a barebones nvim config. Would it work if i installed this plugin and just set `colorscheme nordchad` for example?

the base16 plugin does the syntax coloring and the hl_themes in base16's repo manages the highlight themes ( whole ui ) which is set by some of the config files in nvchad , Ig it'd take some effort to make it work standalone.

**Comment by siduck76** [comment]
but its possible!
