### ISSUE TITLE
Issue with Inserting Text on Normal Install of NvChad

### ISSUE THREAD

**Issue by 23danielsuh** [NvChad/NvChad#450]
**Describe the bug**
Whenever I type something into Neovim, it acts very weirdly, and adds seemingly random characters. See video below for more details. 

**To Reproduce**
1. Install Ubuntu
2. Install neovim 0.6
3. Install NvChad with git
4. Open c++ file with lspinstall clangd installed

**Expected behavior**
The behavior should act normally, with none of this happening

**Desktop (please complete the following information):**
Ubuntu
Kitty
Neovim 0.6

https://user-images.githubusercontent.com/63919918/132760167-a9aca4e2-80f8-471b-9b71-8397077d46bd.mp4

**Comment by siduck76** [comment]
use neovim 0.5 :/

**Comment by siduck76** [comment]
also lsp diagnostics are gonna update in normal mode by default , if you want to update them in insert mode too then there's an option like update_insert in lspconfig , set that as true

**Comment by tydra-wang** [comment]
the same problem.

> use neovim 0.5 :/

I'm using NVIM v0.6.0-dev+155-g15b736d6e
