### ISSUE TITLE
lspinstall not download language server feature

### ISSUE THREAD

**Issue by grimgort** [NvChad/NvChad#451]
Hello,

LSPinstall doesn't download the language server executables. Info: I am behind a proxy
![image](https://user-images.githubusercontent.com/44238325/132819276-cd45b39e-4c87-4175-96a6-0169c27db8a2.png)

**Comment by siduck76** [comment]
ive removed lspinstall , update your config 
https://github.com/NvChad/NvChad/commit/4c025cd1bf67264fd4f12747569c2cbb042e7093

and write the language's lsp name as per lspconfig's config.md
