### ISSUE TITLE
how add linters in nvchad

### ISSUE THREAD

**Issue by imSafdarAwan** [NvChad/NvChad#452]
i wanna add eslint for the js how can i add that or maybe add null-ls in the nvchad

**Comment by siduck76** [comment]
https://github.com/NvChad/NvChad/issues/431

**Comment by imSafdarAwan** [comment]
> #431

but this is a feture request not a bug or something

**Comment by siduck76** [comment]
> > #431
> 
> but this is a feture request not a bug or something

read the conversations

**Comment by imSafdarAwan** [comment]
> > > #431
> > 
> > 
> > but this is a feture request not a bug or something
> 
> read the conversations

sorry sorry i was on something else

**Comment by siduck76** [comment]
@G-Rowell will soon add a custom hooks PR so the user can integrate his config well with nvchad!

**Comment by hsheikhali1** [comment]
So I've tried to add my linter configuration that works directly into lspconfig but for some reason things aren't working ?

**Comment by siduck76** [comment]
> So I've tried to add my linter configuration that works directly into lspconfig but for some reason things aren't working ?

wym things arent working

**Comment by siduck76** [comment]
you need to know how nvchad config works https://nvchad.github.io/config . So it'll get easy to add new plugins , their configs etc

**Comment by hsheikhali1** [comment]
@siduck76 so I followed these instructions after installing `null-ls` and eslint + prettier isn't registering for my typescript files >.> Any idea why?

**Comment by hsheikhali1** [comment]
Nvm got it working :)

**Comment by ArshiAAkhavan** [comment]
i have the same problem here with `null-ls` not taking any action

can you guide me through your fix?
