### ISSUE TITLE
LspInstall is not found

### ISSUE THREAD

**Issue by A-Siam** [NvChad/NvChad#454]
**Describe the bug**
LspInstall is not found

**To Reproduce**
Fresh installation of nvchad 
```bash
$ git clone https://github.com/NvChad/NvChad ~/.config/nvim
$ nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
```

**Expected behavior**
To have LspInstall according to the [docs](https://nvchad.netlify.app/getting-started/post-install#install-lsp-servers)

**Screenshots**
![lspinstall not found](https://i.imgur.com/9ZvjOO3.png)

**Desktop (please complete the following information):**
 - Operating System: Arch Linux
 - Terminal: Xfce4-terminal
 - Version of Neovim: 0.5

**Comment by shift-d** [comment]
It was removed in 4c025cd1bf67264fd4f12747569c2cbb042e7093
