### ISSUE TITLE
`<leader>e` mapped twice by default

### ISSUE THREAD

**Issue by abalmos** [NvChad/NvChad#455]
**Describe the bug**
`<leader>e` is mapped twice by default. [Once to `NvimTreeFocus`](https://github.com/NvChad/NvChad/blob/d0980b7109b3098d22b16cdd78c98386ba6182b3/lua/default_config.lua#L172) and once to [<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>](https://github.com/NvChad/NvChad/blob/d0980b7109b3098d22b16cdd78c98386ba6182b3/lua/plugins/configs/lspconfig.lua#L34)

**To Reproduce**
Use `<leader>e` on a line with an error and see nvim-tree open.

**Expected behavior**
To see the line diagnostics. Seems `<leader>e` is pretty widely assigned to this.

**Comment by abalmos** [comment]
Actually, it may be that none of `lspconfig`'s mappings are being applied anymore.

**Comment by siduck76** [comment]
> Actually, it may be that none of `lspconfig`'s mappings are being applied anymore.

could you change <space>e to <space>da and check if it works?

**Comment by abalmos** [comment]
Sorry, I just figured out that I have two problems. 

One is a nasty conflict between this morning's version of NvChad and `rust-tools`. Removing `rust-tools` and adding `rust_analyzer` to the new `plugins.lspconfig.servers` table restores the old `<leader>e` behavior. Of course that means I am not using `rust-tools` anymore. I'll try to figure that one out. I assume the problem lies with `rust-tools` loading `lspconfig` for rust itself.

The initial issue remains, `<leader>e` is mapped twice. I recommend mapping `nvim-tree`'s focus command to something else.
