### ISSUE TITLE
Mappings in ./lua/plugins/configs/lspconfig.lua doesn't work

### ISSUE THREAD

**Issue by A-Siam** [NvChad/NvChad#456]
**Describe the bug**
Mappings in `./lua/plugins/configs/lspconfig.lua` doesn't work

**To Reproduce**
The default installation of nvchad

**Expected behavior**
Mapping in lspconfig.lua to work

**Desktop (please complete the following information):**
 - Operating System Arch Linux
 - Terminal Xfce4-terminal
 - Version of Neovim 0.5

**Comment by abalmos** [comment]
I am seeing the same thing. Are you using a plugin that configures lsp by itself like `rust-tools`? If so, I think the problem is we don't get NvChad's `on_attach` function then.

**Comment by A-Siam** [comment]
@abalmos I use lspinstall, I'm not sure if it changes some lsp configuration and no other plugins

**Comment by siduck76** [comment]
> @abalmos I only use lspinstall, I'm not sure if it changes some lsp configuration or not.

Lspinstall has been removed  , check post install in setup section of our site

**Comment by A-Siam** [comment]
Done, using the setup steps in docs and installing `typescript-language-server` manually fixed it

**Comment by A-Siam** [comment]
But

**Comment by A-Siam** [comment]
@siduck76 we should install language servers manually right?

**Comment by siduck76** [comment]
> @siduck76 we have to install language servers manually right?

Yep   and just add their names in server table in chadrc 

Check the docs for more info
