### ISSUE TITLE
nvim crashes every update

### ISSUE THREAD

**Issue by benja-pieri** [NvChad/NvChad#459]
Hello, I'm Ben and I really love NvChad, it is very useful!  Everytime that i update with <leader + uu> nvim crashes with some problems and I need to reinstall NvChad,  I'm attaching the screenshot with the errors that are displayed after the update, hope that helps. 
![Captura de tela de 2021-09-10 19-58-06](https://user-images.githubusercontent.com/55410870/132926318-d76de9e2-73b1-4088-9c80-66c0d458673f.png)

**Comment by siduck76** [comment]
Is this neovim 0.5?

**Comment by nikey02** [comment]
> Hello, I'm Ben and I really love NvChad, it is very useful! Everytime that i update with <leader + uu> nvim crashes with some problems and I need to reinstall NvChad, I'm attaching the screenshot with the errors that are displayed after the update, hope that helps.
> ![Captura de tela de 2021-09-10 19-58-06](https://user-images.githubusercontent.com/55410870/132926318-d76de9e2-73b1-4088-9c80-66c0d458673f.png)

It happens also with me too 
I have to reinstall

**Comment by benja-pieri** [comment]
> Is this neovim 0.5?

yes.
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

**Comment by siduck76** [comment]
does the same issue happen with vanilla nvchad? try latest version

**Comment by nikey02** [comment]
> try latest version

It works with latest version for me

**Comment by siduck76** [comment]
> > try latest version
> 
> It works with latest version for me

oh ok so close this issue if you feel like
