### ISSUE TITLE
Can' overwrite mapping set by a plugin

### ISSUE THREAD

**Issue by dgmora** [NvChad/NvChad#462]
**Describe the bug**
I tried to change the mapping of nvimtree toggle, but that didn't work. It seems neoscroll interferes with it.

**To Reproduce**
Change nvimtree config in `chard.lua` to:

```lua
nvimtree = {
  toggle = "<C-e>"
}
```
Restart. `<C-e>` should open nvimtree. But it doesn't it, starts scrolling.

**Expected behavior**
Since the mapping is defined by the user, I would expect that whatever you declare in `chadrc.lua` is applied after what either nvchad or the plugin defines. I also tried it doing it with just `nvim_set_keymap` and it also didn't work.
After disabling neoscroll, the mapping was working.

**Desktop (please complete the following information):**
 - MacOS Big Sur 11.4
 - Alacritty
 - Nvim Latest HEAD

**Comment by siduck76** [comment]
> **Describe the bug**
> I tried to change the mapping of nvimtree toggle, but that didn't work. It seems neoscroll interferes with it.
> 
> **To Reproduce**
> Change nvimtree config in `chard.lua` to:
> 
> ```lua
> nvimtree = {
>   toggle = "<C-e>"
> }
> ```
> 
> Restart. `<C-e>` should open nvimtree. But it doesn't it, starts scrolling.
> 
> **Expected behavior**
> Since the mapping is defined by the user, I would expect that whatever you declare in `chadrc.lua` is applied after what either nvchad or the plugin defines. I also tried it doing it with just `nvim_set_keymap` and it also didn't work.
> After disabling neoscroll, the mapping was working.
> 
> **Desktop (please complete the following information):**
> 
> * MacOS Big Sur 11.4
> * Alacritty
> * Nvim Latest HEAD

change neoscroll mappings then : 

https://github.com/karb94/neoscroll.nvim#options

**Comment by siduck76** [comment]
add this to your config for now! @G-Rowell is working  on the custom hooks PR which will make user's config integerating with nvchad easier + wont get wiped off after update.

**Comment by dgmora** [comment]
That was the thing, I didn't want to modify too much nchad config, since it's going away on update. I'll wait for that then

**Comment by G-Rowell** [comment]
@dgmora 

Heyo, 
I've got a PR that will be merged in the next day or so: #465 

This will greatly improve the custom config situation!

Feel free to look the PR over and let me know if you have any suggestions?

Glancing through your issue (without properly debugging it), I would assume that you'd need to change the nvimtree + neoscroll mappings?


G
