### ISSUE TITLE
clipboard not working?

### ISSUE THREAD

**Issue by JoakoV3** [NvChad/NvChad#463]
**Describe the bug**
I tried using the clipboard which is set to unnamedplus and it doesn't work. I tested it with other configs and that works. 
**To Reproduce**
1. Go to 'yy'
2. Click on 'p'
3, It is just pasting what neovim clipboard has on it. not system .
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Windows with WSL
 - Terminal
 - alacritty
 - Version of Neovim
0.6 dev

**Comment by siduck76** [comment]
can you use 0.5? the docs do mention that 0.5 is needed :( . Idk if this relates to the problem but try

**Comment by imSafdarAwan** [comment]
> **Describe the bug**
> I tried using the clipboard which is set to unnamedplus and it doesn't work. I tested it with other configs and that works.
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'yy'
> 2. Click on 'p'
>    3, It is just pasting what neovim clipboard has on it. not system .
>    **Expected behavior**
>    A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Operating System
> * Windows with WSL
> * Terminal
> * alacritty
> * Version of Neovim
>   0.6 dev

check the health byt```:checkhealth``` and the see if the clipboard is ok if not then you have to install the clipboard tool that could contact with the nvim so it can acces the system clipboard 
by the way i got the same prob twice i just reinstalled the tool that nvim required that wasn't working
look at the help menue for the nvim if you don't find the solution then comment below for more help i will try to help you

**Comment by G-Rowell** [comment]
This is likely an issue with `Windows Subsystem for Linux`,

could you show the output of `:checkhealth` like imSafdar suggested?

Hope we can fix this!

G

**Comment by JoakoV3** [comment]
![image](https://user-images.githubusercontent.com/58125197/133317416-5ac06311-75e7-4da6-8398-3faa8d6ca975.png)

everything is ok unless that

**Comment by G-Rowell** [comment]
Yeah, this for sure shows that there is a problem.

This should solve it: feel free to @ me if this issue persists!
https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl
