### ISSUE TITLE
 Error running config for bufferline.nvim

### ISSUE THREAD

**Issue by hellisabove** [NvChad/NvChad#464]
**Describe the bug**
When opening nvim after installing the configuration and plugins, the error shows whenever I press to enter insert mode or when starting neovimm

**To Reproduce**
1. install NvChad
2. start neovim as instructed in the instalation process
3. wait for plugins to install
4. quit and reopen nvim
5. See error

**Expected behavior**
packer.nvim: Error running config for bufferline.nvim: ...packer/opt/bufferline.nvim/lua/bufferline/colors.lua:71: attempt to index gl
obal 'bit' (a nil value)

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System Gentoo Linux
 - Terminal st
 - Version of Neovim v0.5.0

**Additional context**

**Comment by hellisabove** [comment]
Solved it by compiling neovim from the git repo as the one in the gentoo repos is older.

**Comment by siduck76** [comment]
> Solved it by compiling neovim from the git repo as the one in the gentoo repos is older.

yep 0.5v stable release must be used
