### ISSUE TITLE
Cursor not visible in light themes

### ISSUE THREAD

**Issue by laraib07** [NvChad/NvChad#467]
**Describe the bug**
Cursor is hardly visible in blossom and not at all visible in one-light.

**To Reproduce**
1. Change theme to one-light or blossom
2. See yourself.

**Expected behavior**
Cursor must be dark colored.

**Screenshots**
![Screenshot_20210914-182650886 (1)](https://user-images.githubusercontent.com/25507825/133261815-e89624a6-ec70-4ac5-9013-22e6b9dea0ad.jpg)
![Screenshot_20210914-182754058 (1)](https://user-images.githubusercontent.com/25507825/133261820-ccbe81e6-0bb6-49e1-8e6c-2b72714b816b.jpg)

**Desktop (please complete the following information):**
 - Operating System : android 12
 - Terminal : termux
 - Version of Neovim : 0.5

**Additional context**
I am on latest config.

**Comment by G-Rowell** [comment]
Oh damn for sure!
Thanks for the issue, we'll have to get to this soon! :)

**Comment by siduck76** [comment]
cursor in blossom 
![image](https://user-images.githubusercontent.com/59060246/133300081-84cc451e-e6df-43ba-a188-fe193da1b0c8.png)

**Comment by siduck76** [comment]
cursor in onelight
![image](https://user-images.githubusercontent.com/59060246/133300271-c6587275-b2dd-41f0-b9dc-e8ddeb5e0953.png)

**Comment by laraib07** [comment]
Then why the cursor is not visible on termux.

**Comment by siduck76** [comment]
> Then why the cursor is not visible on termux.

probably termux issue :(

**Comment by G-Rowell** [comment]
We've had a fair few UI & colour issues with Termux,
it's rather strange and we're not yet sure why Termux causes it

**Comment by G-Rowell** [comment]
@laraib07 

I think this is good to close now?
