### ISSUE TITLE
Hide folder and filename section in statusline for small screens

### ISSUE THREAD

**Issue by laraib07** [NvChad/NvChad#468]
**Is your feature request related to a problem? Please describe.**
For small screens, say on termux, folder name and filename takes up a lot of space. There is no need to show filename, we can see it in bufferline anyway.

**Describe the solution you'd like**
Put check-width condition in  folder and filename sections. 

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
![Screenshot_20210914-183643973 (1)](https://user-images.githubusercontent.com/25507825/133263544-12a080e4-daf6-4685-8081-11eef1c86083.jpg)

**Comment by siduck76** [comment]
I was planning to this soon but my exams! PR's are welcome <3 

https://github.com/famiu/feline.nvim

**Comment by siduck76** [comment]
this must be fixed now @laraib07
