### ISSUE TITLE
DONT HATE ME: Missing Icons on clean install

### ISSUE THREAD

**Issue by ricbermo** [NvChad/NvChad#471]
**Describe the bug**
As the title says, I'm missing one icon, the find file icon (Dashboard)

**To Reproduce**
1. Clean Install
2. enable the dashboard
3. Open neovim

**Expected behavior**
All Icons in the dashboard should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/2601363/133519199-df4b9891-8040-4bd1-b014-a8fd46d69048.png)

**Desktop (please complete the following information):**
 - Operating System: Mac OS 11.5.2
 - Terminal: iTerm2, build: 3.4.10
 - Version of Neovim: NVIM v0.5.0

**Additional context**
I'm using JetBrains as the terminal font.
![image](https://user-images.githubusercontent.com/2601363/133519319-625a19e7-4a78-4f10-b177-a982b50db7f7.png)

I also read on another issue something about material icons so I downloaded and installed that font.
I checked out your custon `st` and `xresources` and I could see that u are using JetBrains

**Comment by G-Rowell** [comment]
Hello,

hmmmm, it does seem like you have a Nerd Font, maybe try a different Nerd Font?
(maybe there is a specific issue with that single font from the Nerd font team?)


G

**Comment by ashincoder** [comment]
@ricbermo could u check with kitty terminal. https://github.com/kovidgoyal/kitty

**Comment by siduck76** [comment]
can you try 1st or last icon from here ?

![image](https://user-images.githubusercontent.com/59060246/133581830-31e97cfd-e72a-4863-936d-5b1cb8a6b67d.png)

**Comment by ricbermo** [comment]
@siduck76 using the last one worked.
![image](https://user-images.githubusercontent.com/2601363/133603969-3cb87c78-65cb-468a-8161-3b1379def606.png)
@ashincoder I dind't know about Kitty. Thanks for sharing.

**Comment by ricbermo** [comment]
@siduck76 hello, I think there's one small typo on the dashboard, as you can see from the screenshot I'm seeing version 0.5 (installed from master), in fact, if you go [here](https://github.com/NvChad/NvChad/blob/v1.0/lua/plugins/dashboard.lua) the version is not updated.

**Comment by siduck76** [comment]
> @siduck76 hello, I think there's one small typo on the dashboard, as you can see from the screenshot I'm seeing version 0.5 (installed from master), in fact, if you go [here](https://github.com/NvChad/NvChad/blob/v1.0/lua/plugins/dashboard.lua) the version is not updated.

oh oof , I'll remove it!
