### ISSUE TITLE
Green screen after install

### ISSUE THREAD

**Issue by vndee** [NvChad/NvChad#472]
**Describe the bug**
I have follow the [install instruction](https://nvchad.netlify.app/getting-started/setup) but after that I've got a green screen like this:
![](https://i.imgur.com/oS9jeF8.png)

**Desktop (please complete the following information):**
 - Operating System: macOS Big Sur 11.4
 - Terminal: macOS built-in terminal version 2.11
 - Version of Neovim: v0.5.0

Please help me, thanks.

**Comment by ashincoder** [comment]
did u do `:PackerCompile`

**Comment by siduck76** [comment]
Set true colors in iterm

**Comment by ashincoder** [comment]
https://github.com/NvChad/NvChad/issues/2

**Comment by ludonghai715** [comment]
set true color in xshell
