### ISSUE TITLE
lsp install plugin is not installed why

### ISSUE THREAD

**Issue by imSafdarAwan** [NvChad/NvChad#473]
why did the lsp install plugin is not installed in the nvchad

**Comment by siduck76** [comment]
It's removed  , check the recent closed issues .

Also this : 
https://nvchad.netlify.app/getting-started/post-install#install-lsp-servers

**Comment by imSafdarAwan** [comment]
> It's removed , check the recent closed issues .
> 
> Also this :
> https://nvchad.netlify.app/getting-started/post-install#install-lsp-servers

oh so we are going back to use the lspconfig itself

**Comment by rafa-acioly** [comment]
This was one of the best features, why do we killed it?

**Comment by siduck76** [comment]
> This was one of the best features, why do we killed it?

adding it yourself wont be hard!
