### ISSUE TITLE
Arduino-ls add

### ISSUE THREAD

**Issue by Adrplayer** [NvChad/NvChad#474]
Hi there, Im sorry for ask for help about this.

I have problems with adding the arduino-language-server :
https://github.com/arduino/arduino-language-server

and I find this info in lspconfig : 
https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#arduino_language_server

But i dont know how to add this in the nvchad config. I hope you can help me, sorry for need your help ( I think it's a silly question) and thanks for your help.

**Comment by siduck76** [comment]
https://nvchad.netlify.app/getting-started/post-install#install-lsp-servers
