### ISSUE TITLE
[not a feature request, but a help request] Why the nerd fonts not working in my NvChad.

### ISSUE THREAD

**Issue by ronnin** [NvChad/NvChad#475]
![image](https://user-images.githubusercontent.com/100691/133707308-7a1a0bf8-b603-4742-816a-a63145350a22.png)

I'm using iTerm2 v3.4.10.
Many nerd fonts have been tried, but none of them are working in NvChad. 

Please help me out. Thanks a lot.

One more question：How to edit all files in the directory? Isn't it "nvim ~/workspace/k8s/jenkins/"? Just as shown on the homepage of "https://nvchad.netlify.app/".

**Comment by G-Rowell** [comment]
In most shells (like BASH, ZSH.....etc), `~/workspace/k8s/jenkins/" will expand to `/home/ronnin/workspace/k8s/jenkins`,

try `~/workspace/k8s/jenkins/*`

**Comment by G-Rowell** [comment]
In regards to the font issue, this could be several things:

1. Wrong font (not using a proper Nerd Font
    - this is probably not your issue
2. A bug in the terminal emulator (iTerm2)
    - try using a different terminal emulator?

**Comment by ronnin** [comment]
> In most shells (like BASH, ZSH.....etc), `~/workspace/k8s/jenkins/` will expand to `/home/ronnin/workspace/k8s/jenkins/`,
> 
> try `~/workspace/k8s/jenkins/*`

nvim opens all files under directory, by 'nvim ~/workspace/k8s/jenkins/*'. 
How to show the panels on the left & right sides, just as shown on the homepage of "https://nvchad.netlify.app/" ?

**Comment by G-Rowell** [comment]
The left panel is opened by `<CTRL> + n`,
the right side panel is a normal Vim split. 😄 

See: https://nvchad.netlify.app/getting-started/post-install

**Comment by ronnin** [comment]
> In regards to the font issue, this could be several things:
> 
> 1. Wrong font (not using a proper Nerd Font
>    
>    * this is probably not your issue
> 2. A bug in the terminal emulator (iTerm2)
>    
>    * try using a different terminal emulator?

![image](https://user-images.githubusercontent.com/100691/133719188-b0b4141a-3945-4257-a2a0-b7184cb6a6ab.png)
Indeed, the fonts works in Mac built-in Terminal, dosen't work in iTerm2. 

The default background color of NvChad is so Green. How to change it?

**Comment by G-Rowell** [comment]
Yeah, this is for sure an issue with iTerm2 then,

NvChad background is not green by default.


Maybe you don't have full colour mode enable in iTerm?

**Comment by ronnin** [comment]
> Yeah, this is for sure an issue with iTerm2 then,
> 
> NvChad background is not green by default.
> 
> Maybe you don't have full colour mode enable in iTerm?
![image](https://user-images.githubusercontent.com/100691/133727283-ddf335e3-6398-44d5-8b5c-acf9f17dd50e.png)

I don't know.  I checked, and iTerm2 and Terminal are both with xterm-256color setting.

**Comment by siduck76** [comment]
#2

**Comment by G-Rowell** [comment]
@ronnin 

I think this is okay to close?

> Okay the issue was with Mac Terminal, it didn't support 24 bit color so I was facing the issue.
