### ISSUE TITLE
Themes guide

### ISSUE THREAD

**Issue by cNorspang** [NvChad/NvChad#478]
Could any guide be made/Where to find information on how to make a theme for NvChad?. I know that external themes will cause some issues with plugins, but i would like to make a Halloween theme, as October is coming up.  Maybe a bit of documentation on how to crate a theme for NvChad could be added?

**Comment by Theory-of-Everything** [comment]
There is a [Themes](https://github.com/NvChad/NvChad/wiki/Themes) article in the NvChad wiki.

**Comment by siduck76** [comment]
> There is a [Themes](https://github.com/NvChad/NvChad/wiki/Themes) article in the NvChad wiki.

That's outdated

**Comment by siduck76** [comment]
@cNorspang I'll make it after 3 days , don't mind the delay!

**Comment by G-Rowell** [comment]
Is there any reason why local themes don't work?

(as long as the properly follow the `NvChad/base16` structure & format?

**Comment by G-Rowell** [comment]
Oh wait, they for sure won't work currently, as themes have been moved to `NvChad/extensions` (which I like),

though we should add a `custom/themes` folder maybe?

**Comment by siduck76** [comment]
> Oh wait, they for sure won't work currently, as themes have been moved to `NvChad/extensions` (which I like),
> 
> though we should add a `custom/themes` folder maybe?

ye then we need to have two files in that folder then : 

highlights.lua and base16-colors.lua

**Comment by cNorspang** [comment]
> @cNorspang I'll make it after 3 days , don't mind the delay!

Not minding the delay at all, just happy that it might actually come. In the meantime, i can rice everything else, and actually develop the color theme it self

**Comment by siduck76** [comment]
@cNorspang https://nvchad.github.io/contribute#how-to-submit-themes
