### ISSUE TITLE
Clean install on M1: "Error during tarball extraction"

### ISSUE THREAD

**Issue by juanandresgs** [NvChad/NvChad#479]
**Describe the bug**

On clean install, opening nvim pops up an error-

> nvim-treesitter[lua]: Error during tarball extraction.
> tar: Error opening archive: Failed to open 'tree-sitter-lua.tar.gz'

**To Reproduce**
1. Install nvchad
2. Open nvim

**Expected behavior**
Functioning nvchad install, including tree-sitter.

**Screenshots**

<img width="568" alt="Screen Shot 2021-09-20 at 3 04 43 AM" src="https://user-images.githubusercontent.com/15952691/133967015-704b3968-2e93-4ab4-8a62-4f5efd3ae8e3.png">

**Desktop (please complete the following information):**
 - Operating System
 MacOS 11.6 on M1
 - Terminal
 iterm2
 - Version of Neovim
v0.6.0-dev+1741-g5fd21b8d3

**Additional context**

Just ran the same install on an intel Mac, same setup, same OS, and NvChad installed just fine. :|

**Comment by ashincoder** [comment]
better use the stable version of Neovim. https://github.com/neovim/neovim

**Comment by G-Rowell** [comment]
> 
> 
> better use the stable version of Neovim. https://github.com/neovim/neovim

@juanandresgs +1

NeoVim 0.5 is ideal

**Comment by juanandresgs** [comment]
Switched to stable, error persists.

> NVIM v0.5.0
> Build type: Release
> LuaJIT 2.1.0-beta3

**Comment by G-Rowell** [comment]
Can you check if you have tar installed,

`tar --version`

**Comment by ashincoder** [comment]
I do think this one is a problem. Never happened to me but. 
https://github.com/NvChad/NvChad/blob/main/lua/core/options.lua#L63

**Comment by juanandresgs** [comment]
Of course, tar is installed by default and has been tested separately.

@ashincoder tried removing the tar relevant lines but it made no difference. 
Any ideas?

**Comment by ashincoder** [comment]
@juanandresgs do a `:checkhealth treesitter`

**Comment by juanandresgs** [comment]
![Image 9-20-21 at 3 19 PM](https://user-images.githubusercontent.com/15952691/134061635-9bbddfb6-a074-4229-8af8-6d161e3438f2.jpg)
That's all I got

**Comment by samrath2007** [comment]
so what I did for my nvim on m1 install is this
```
brew install --HEAD luajit
brew install --HEAD neovim
```
You could try this I guess

**Comment by juanandresgs** [comment]
Ah! Tried reinstalling luajit and stumbled upon something, it seems luajit is not yet supported for M1 (there's talk of deprecating it). Think that might be it?

**Comment by samrath2007** [comment]
luajit supported on head is supported afaik

**Comment by G-Rowell** [comment]
Hmmmm, yeah could quite possible be due to the ARM architecture,
not too sure what we can do to help from our end?

Sorry, wish I could help solve it

**Comment by ashincoder** [comment]
Mm yeah. No use in creating issues like this in NvChad. These are neovim issues.

**Comment by siduck76** [comment]
> Mm yeah. No use in creating issues like this in NvChad. These are neovim issues. Soz

agreed!
