### ISSUE TITLE
Adding Telescope extension

### ISSUE THREAD

**Issue by mrassili** [NvChad/NvChad#480]
**Describe the bug**
I cannot add a Telescope extension

**Expected behavior**
Installing the extension and then adding it to `extensions` under `lua/plugins/configs/telescope.lua` doesn't work

**Desktop (please complete the following information):**
 - Operating System: OSX
 - Terminal iTerm2
 - Version of Neovim 0.5

How can I add Telescope extensions?

**Comment by siduck76** [comment]
which extension and how are you adding them?

**Comment by mrassili** [comment]
@siduck76 this is the extension; https://github.com/ThePrimeagen/git-worktree.nvim

I installed it by including it in `lua/plugins/init.lua` and also added it to the extensions list in `lua/plugins/configs/telescope.lua` but I can't find it when I open Telescope and look for `git worktree`

Maybe I am missing something?

**Comment by mrassili** [comment]
Here's what I did to make it work: https://www.reddit.com/r/neovim/comments/psh5d1/how_can_i_add_telescope_extensions_to_nvchad/hdqbkzk/?utm_source=reddit&utm_medium=web2x&context=3

you can close this.
