### ISSUE TITLE
Disabling Completions Breaks Config

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#482]
So I was trying to disable all of the cmp and snippet related plugins via adding disable flags, e.g. cmp, luasnip, and friendly-snippets, but disabling cmp results in an error from the other two, and disabling those breaks the entire config. Things like 'jk' stop working, and on entry to the editor I get a message saying "please check your config for correctness"

I want to disable them because as a programmer who uses primarily python, the performance speedup and responsiveness of coq-nvim is breathtaking by comparison. Unfortunately, they do not play nicely together for obvious reasons. 

I do think that as a general housekeeping thing outside of my use case, completions should be disable-able with the rest of the functional remaining intact.

**Comment by siduck76** [comment]
I'll soon add some options for disabling cmp and related plugins , let (#465) get merged first

**Comment by siduck76** [comment]
https://github.com/NvChad/NvChad/blob/main/lua/core/default_config.lua#L76

check our docs about explaining the whole config https://nvchad.github.io/#config
