### ISSUE TITLE
Add a variable in chadrc for a snippets directory 

### ISSUE THREAD

**Issue by macarthy** [NvChad/NvChad#483]
**Is your feature request related to a problem? Please describe.**

I would like to add a custom folder for my snippets

**Describe the solution you'd like**

I set a variable in chadrc and that folder is loaded 

**Describe alternatives you've considered**

I tried this but it didn't work 

require("luasnip/loaders/from_vscode").lazy_load({ paths = { "./config/nvim/snippets" } }) -- Load snippets from my-snippets folder

**Comment by siduck76** [comment]
soon! let #465 merge first

**Comment by siduck76** [comment]
#465 related!

**Comment by siduck76** [comment]
https://github.com/NvChad/NvChad/blob/main/lua/core/default_config.lua#L84

**Comment by siduck76** [comment]
https://nvchad.github.io/config
