### ISSUE TITLE
Allow plugin option to be passed from chadrc 

### ISSUE THREAD

**Issue by macarthy** [NvChad/NvChad#484]
**Is your feature request related to a problem? Please describe.**

In this case i Would like to set virtual text to false 

**Describe the solution you'd like**

if I could pass setting in chadrc that are merge with the default settings  that would stop them being overwritten 

**Describe alternatives you've considered**

I can edit the lsp config file directly but it gets overwritten on updates 

Alternatively I can fork the project, point the update url to my repo and apply a patch with the changes i want :-)

**Comment by mrassili** [comment]
Question to maintainers: regarding override of config when you update, what happens to added plugins if I decide to update? Do they get overridden?

**Comment by siduck76** [comment]
#465 related

**Comment by siduck76** [comment]
https://nvchad.github.io/config

**Comment by mrassili** [comment]
> https://nvchad.github.io/config

I didn't know this page existed, thanks!
