### ISSUE TITLE
nvchad theme picker errors out when trying to save new theme to chadrc.lua

### ISSUE THREAD

**Issue by hsheikhali1** [NvChad/NvChad#490]
**Describe the bug**
Theme change using telescope is trying to update my theme upon selecting a new one but the save functionality is looking for the old location of `chadrc.lua` rather than the new location.

**To Reproduce**
1. type `<leader>th`
2. Select a new theme
3. nvchad prompts user to update to selected theme
4. Error occurs: ENOENT: no such file or directory /.config/nvim/lua/chadrc.lua

**Expected behavior**
Theme picker should let user save/update their theme with the selected theme.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Operating System: Arch Linux (BSPWM)
 - Terminal: Alacritty/Kitty
 - Version of Neovim: 0.5.x

**Additional context**
The below link is where the bug is and it needs to be changed to:
```lua
local file = vim.fn.stdpath "config" .. "/lua/custom/" .. user_config .. ".lua"
```
https://github.com/NvChad/extensions/blob/a7b2b58dbdea8a1ddfbf0c4f2e07b52390c2cb0b/lua/nvchad/change_theme.lua#L12

**Comment by hsheikhali1** [comment]
This is a rather easy fix I think -- not sure if I am allow to just change it in the NvChad/extensions repo and create a PR

**Comment by siduck76** [comment]
I was working on the docs , forgot about this, thanks! 

https://github.com/NvChad/extensions/commit/62723ca317664dcba8872853df7b073859b33f7d , should be fixed I think.

**Comment by hsheikhali1** [comment]
Nice :) Glad we got that in there -- I tend to change my theme every minute while editing ahaha

**Comment by siduck76** [comment]
> Nice :) Glad we got that in there -- I tend to change my theme every minute while editing ahaha

btw could you do packersync and check if nvimtree is working?

**Comment by hsheikhali1** [comment]
Yup - let me do that rn

**Comment by hsheikhali1** [comment]
> > Nice :) Glad we got that in there -- I tend to change my theme every minute while editing ahaha
> 
> btw could you do packersync and check if nvimtree is working?

Yikes...
![image](https://user-images.githubusercontent.com/14851850/134777235-39b7ff57-c394-4ce1-8fde-ecbbf34cffd7.png)

**Comment by hsheikhali1** [comment]
Looks like packersync removed nvimtree from nvchad?

**Comment by siduck76** [comment]
> Looks like packersync removed nvimtree from nvchad?

yea very weird :/ . Idk why it should do that :c

**Comment by marvelman3284** [comment]
Getting the same issue, see #troubleshooting in the discord

**Comment by siduck76** [comment]
> Looks like packersync removed nvimtree from nvchad?

nvimtree config has been updated , can you check now if its working? btw updater is broken for a while so copy stuff manually for now

**Comment by hsheikhali1** [comment]
> > Looks like packersync removed nvimtree from nvchad?
> 
> nvimtree config has been updated , can you check now if its working? btw updater is broken for a while so copy stuff manually for now

Yeah looks like it's still broken via `packersync` but I will update it manually

**Comment by hsheikhali1** [comment]
Okay its working now 👍🏽
