### ISSUE TITLE
chadrc.lua missing

### ISSUE THREAD

**Issue by bashirsouid** [NvChad/NvChad#491]
**Describe the bug**
From the documentation it appears that there should be a file called `chardrc.lua` but appears missing from clone and Github search. Am I blind?

It affects update because on fresh clone if you do <Leader>uu it can't find `chardrc.lua` file.

**To Reproduce**
1. Fresh clone of repository
2. Attempt update with <Leader>uu
3. See error that chadrc.lua is not found.
4. Confirm in OS that indeed file is not present

**Expected behavior**
The `chadrc.lua` file is present.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Operating System: Ubuntu Linux 20.04
 - Terminal: Kitty
 - Version of Neovim: NVIM v0.6.0-dev

**Additional context**
- Also reproduces with the docker quickstart example from the readme file.

**Comment by siduck76** [comment]
updater is broken at the moment! Also you need to copy example_chadrc.lua to chadrc.lua in custom folder.

also check the new config! https://nvchad.github.io/config

**Comment by G-Rowell** [comment]
@bashirsouid 

We had a major custom overhaul #465,

copy the `custom/example_chadrc.lua` -> `custom/chadrc.lua`

Probably worth making a post about this, but I do not have the permission to change the projects README, pin an issue, or make a post in our Discord announcements.

---

This change was made to protect users configs moving forward, though I can understand the confusion.


G

**Comment by neel229** [comment]
Where do I find the discord channel link?

**Comment by siduck76** [comment]
> Where do I find the discord channel link?

On the readme discord badge

**Comment by bashirsouid** [comment]
Cool. Thanks. Just a suggestion: I think that best UX here is if you try to update and it's not present is to just ignore the absence and proceed to update because nothing inside it seems necessary for updates. Thanks!

**Comment by Thorhian** [comment]
I'm a newbie and just trying to check out NVChad. This threw me through a loop for a bit until I found this issue. Following the getting started guide yesterday resulted in a broken NVChad setup.

**Comment by G-Rowell** [comment]
@bashirsouid @Thorhian 

My apologies,

the docs have to always play catch-up to the code, because of how fast we've been moving recently 🤣 

Should be fixed with my note in the site when we merge it to main,
check it out here:

https://github.com/NvChad/nvchad.github.io/commit/24b8a96df557f07a304e03f35cd3ae287bd08cf2

Would love feedback if my wording is wrong!

Thanks again,
G

**Comment by bashirsouid** [comment]
Cool. I think that wording note is perfect :+1:

**Comment by G-Rowell** [comment]
Thanks both of you for pointing out the docs issue!

**Comment by mateusdeap** [comment]
So I have a `chadrc.lua` in my custom folder, but trying to update with `<leader> + uu` complains there is no `chadrc.lua` directly under the lua folder. What should I do?

**Comment by siduck76** [comment]
> So I have a `chadrc.lua` in my custom folder, but trying to update with `<leader> + uu` complains there is no `chadrc.lua` directly under the lua folder. What should I do?

add the chadrc , copy the example chadrc file

**Comment by DirtySoc** [comment]
Just setup NvChad for the first time, also ran into this issue.

**Comment by siduck** [comment]
> Just setup NvChad for the first time, also ran into this issue.

read this whole issue and you'll understand
