### ISSUE TITLE
best explanation to modify the configuration of a plugin

### ISSUE THREAD

**Issue by grimgort** [NvChad/NvChad#500]
Hello,

I'm trying to migrate to the new version of NVCHAD, but I find the documentation a bit complicated to modify the default configuration of a plugin. 

In particular, I'm trying to add cmp-path and cmp-calc for nvim_cmp as below. How should I modify the chadrc to include these changes?

Is it possible to disable nvchad default plugins?

   sources = {
      { name = "nvim_lsp" },
      { name = "path" },
      { name = "luasnip" },
      { name = "cmp_tabnine" },
      { name = "nvim_lua" },
      { name = "buffer" },
      { name = "calc" },
      { name = "emoji" },
      { name = "treesitter" },
      { name = "crates" },
   },

I also tried to add a server for lsp_config, but without success 👍 
![image](https://user-images.githubusercontent.com/44238325/134954074-70e7a8b9-9736-4bac-95a6-3478291040d1.png)

**Comment by siduck76** [comment]
if you're just gonna use clangd's default lspconfig then just add clangd word int the lspconfig's server table , in chadrc

**Comment by siduck76** [comment]
I suggest you to read the whole docs rather than cherry picking the thing you want :l

**Comment by siduck76** [comment]
anyways you can override the default config by : 

![image](https://user-images.githubusercontent.com/59060246/134954953-d53b698f-c4e8-43b9-bff3-90af835fd5df.png)

**Comment by grimgort** [comment]
Thanks for help, but nothing work. I have read all the documentation, but I don't understand. I am not familiar with LUA and I don't fully understand the chadrc function (override_req). 
I tried the following things: 
![image](https://user-images.githubusercontent.com/44238325/135047342-4b6e8abe-1b50-4501-bc66-47b2aa6ee196.png)

**Comment by siduck76** [comment]
> Thanks for help, but nothing work. I have read all the documentation, but I don't understand. I am not familiar with LUA and I don't fully understand the chadrc function (override_req).
> I tried the following things:
> ![image](https://user-images.githubusercontent.com/44238325/135047342-4b6e8abe-1b50-4501-bc66-47b2aa6ee196.png)

![image](https://user-images.githubusercontent.com/59060246/135055050-417689f6-0455-446f-8562-85dfd9fa3d79.png)

**Comment by siduck76** [comment]
I suggest you learning basic lua from our guides first then go to the config section

**Comment by siduck76** [comment]
https://nvchad.github.io/getting-started/post-install

**Comment by grimgort** [comment]
Ok sorry, i have understand..... we need to launch packerSync so that the modifications of the plugin configuration file are taken into account. This is logical because we load the file in Packer. But it may be worth to remind it in the documentation, because it is not obvious at first

**Comment by siduck76** [comment]
> Ok sorry, i have understand..... we need to launch packerSync so that the modifications of the plugin configuration file are taken into account. This is logical because we load the file in Packer. But it may be worth to remind it in the documentation, because it is not obvious at first

yeah agreed , sorry for not mentioning it!

**Comment by siduck76** [comment]
@grimgort https://nvchad.github.io/config#replace-default-config-of-a-plugin
