### ISSUE TITLE
Clean update while under heavy development

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#502]
Not really a feature request.

I have created an alias as nvchad is under heavy development and `Space u u` to update breaks once in a while.

`nvchad="rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim ; git clone https://github.com/NvChad/NvChad ~/.config/nvim ; ln -s ~/.config/chadrc.lua ~/.config/nvim/lua/custom/; nvim +'hi NormalFloat guibg=#1e222a' +PackerSync" `

This implies that the chadrc.lua is located in ~/.config/ and will therefore not be removed + later linked back into nvim/lua/custom/

**Comment by siduck76** [comment]
@se7en-x230 the updater is fixed now!
