### ISSUE TITLE
wal.vim integration

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#503]
It would be great if we could get `wal.vim` working with the themes!

repo: https://github.com/dylanaraps/wal.vim

**Comment by siduck76** [comment]
https://github.com/NvChad/NvChad/issues/397 :l

**Comment by siduck76** [comment]
I dont think this would be possible sorry! Nvchad themes are made after many trials and testing [check](https://nvchad.github.io/contribute#creating-the-theme-example) , if someone does a PR for this then i'll see what I can do.

**Comment by danjenson** [comment]
ok bummer, because my entire system theme uses pywal

**Comment by siduck76** [comment]
> ok bummer, because my entire system theme uses pywal

oh no pywal :despair:
