### ISSUE TITLE
Eager load plugins / load on custom keymappings 

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#504]
I have the following custom shortcuts in my `init.lua` file:

```lua
   map('n', '<C-f>', ':lua require("telescope.builtin").find_files({ search_dirs = { ".", "/data/repos" } }) <CR>')
   map('n', '<C-s>', ':lua require("telescope.builtin").live_grep({ search_dirs = { ".", "/data/repos" } }) <CR>')
```

However, since telescope is lazy-loaded, these always fail. Should I include telescope.vim in my init.lua again and specify keys that enable it? Is there a way to eager load this plugin? (Incidentally, it would also be nice to specify default search directories).

**Comment by G-Rowell** [comment]
Packer will load Telescope when that command is called,
so rather then using lua, try using a standard command.

eg;  `map('n', '<C-f>', ':Telescope find_files <CR>)`

**Comment by G-Rowell** [comment]
You can also provide options to the command using this above format too, checkout the Telescope docs

**Comment by siduck76** [comment]
> Packer will load Telescope when that command is called,
> so rather then using lua, try using a standard command.
> 
> eg; `map('n', '<C-f>', ':Telescope find_files <CR>)`

looks like he wants to find files in specific dirs

**Comment by G-Rowell** [comment]
That's plenty achievable with the `:Telescope` command, you can pass through any options that you can pass in lua

**Comment by danjenson** [comment]
Unfortunately, it doesn't seem to work..

```lua
   map('n', '<C-f>', ':Telescope find_files search_dirs=[".", "/data/repos"] <CR>')
   map('n', '<C-s>', ':Telescope live_grep search_dirs=[".", "/data/repos"] <CR>')
```

Same with {}. It only works in lua form for me

**Comment by G-Rowell** [comment]
I think your format is wrong, 

I have done this myself before.

You were pointed to the Telescope docs in the issue you created there: https://github.com/nvim-telescope/telescope.nvim/issues/1276#issuecomment-924631386

**Comment by G-Rowell** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L586-L620

**Comment by danjenson** [comment]
Yea and it doesn't actually seem to specify how to use an array, because that is a vimscript array. Not your problem though. Thanks
