### ISSUE TITLE
how should I setup lsp to overwrite the default config

### ISSUE THREAD

**Issue by tydra-wang** [NvChad/NvChad#508]
Problem is `plugins.options.lspconfig.servers` in chadrc can only setup lsp server with default config.

If I put my lspserver setup stuffs in custom dir like `custom/lspconfig.lua`:

1. how to use `local function on_attach` and `local capabilities` declared in builtin `lspconfig.lua` ?
2. need I put `require('custom.lspconfig')` in `custom/init.lua`?

**Comment by siduck76** [comment]
https://nvchad.github.io/config#how-to-setup-lsp-server

**Comment by siduck76** [comment]
Please read all of https://nvchad.github.io/config D:

**Comment by abalmos** [comment]
Shouldn't there be a hook to override a call to the LSP's `setup` function? The hook could pass the built in `on_attach` and `capabilities`? At the moment the only way I can figure out how to have a custom call to an LSP's `setup` (which I need for four LSPs) is to duplicate the `lspconfig.lua` within the custom folder. And, yes, I _have_ already read the docs and I don't see anything related to this. The only example starts `null-ls` without an `on_attach` or `capabilities`.

**Comment by siduck76** [comment]
> Shouldn't there be a hook to override a call to the LSP's `setup` function? The hook could pass the built in `on_attach` and `capabilities`? At the moment the only way I can figure out how to have a custom call to an LSP's `setup` (which I need for four LSPs) is to duplicate the `lspconfig.lua` within the custom folder. And, yes, I _have_ already read the docs and I don't see anything related to this. The only example starts `null-ls` without an `on_attach` or `capabilities`.

null-ls can be setup the same way https://nvchad.github.io/config#install-null-ls

**Comment by abalmos** [comment]
@siduck76 I don't think your understanding our question. What I wrote has nothing to do with `null-ls` other then to point out it is an insufficient example of an LSP because it (apparently?) does not need on_attach / capabilities.

We don't understand how to add an LSP that _needs_ on_attach and capabilities without just totally overriding the built-in LSP config or duplicating the functions.

**Comment by siduck76** [comment]
> @siduck76 I don't think your understanding our question. What I wrote has nothing to do with `null-ls` other then to point out it is an insufficient example of an LSP because it (apparently?) does not need on_attach / capabilities.
> 
> We don't understand how to add an LSP that _needs_ on_attach and capabilities without just totally overriding the built-in LSP config or duplicating the functions.

oh , for now just override the lspconfig , I'll see what I can do! Been having exams lately so the development might be slow. PR's are welcomed!

**Comment by abalmos** [comment]
Is the approach of offering an override function the expected way?

**Comment by siduck76** [comment]
> Is the approach of offering an override function the expected way?

yes but lspconfig is an exception , But yea separating lspservers in a different file and not re-defining functions etc sounds better in my opinion , I think i have done that before : 

so lspconfig might have a line similar to [this](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/lspconfig.lua#L73)

and the user's lspconfig could have thiis : https://paste.sh/JcRLbT4R#gJNe5C0GZ4vn2h-pjv38cakc (sumneko_lua's example here)

**Comment by siduck76** [comment]
@abalmos  done https://nvchad.github.io/config#setup-lsp-server

**Comment by abalmos** [comment]
@siduck76 Great! Looks good and I think that will fit perfect with `nvim-lsp-installer`'s `on_server_ready()` method!

**Comment by abalmos** [comment]
I'll play with it tomorrow and let you know. Thanks for the quick turnaround!

**Comment by siduck76** [comment]
> @siduck76 Great! Looks good and I think that will fit perfect with `nvim-lsp-installer`'s `on_server_ready()` method!

yes i have written a quick doc for it , nvim-lsp-installer worked ootb! 

https://nvchad.github.io/config#setup-lsp-installer

**Comment by abalmos** [comment]
@siduck76 I was playing with this today, I think we need to combine both to provide the proper nvchad defaults (for example `<leader>rn` does not work as is).

Something like
```lua
local M = {}

M.setup_lsp = function(attach, capabilities)
   local lsp_installer = require "nvim-lsp-installer"

   lsp_installer.on_server_ready(function(server)
      local opts = {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
         settings = {},
      }
     
      if server.name == "rust_analyzer" then
         opts.settings = {
            ["rust-analyzer"] = {
               experimental = {
                  procAttrMacros = true,
               },
            },
         }
      end

      server:setup(opts)
      vim.cmd [[ do User LspAttachBuffers ]]
   end)

return M
```
Can even further extends with something like this:

```lua
local M = {}

M.setup_lsp = function(attach, capabilities)
   local lsp_installer = require "nvim-lsp-installer"

   lsp_installer.on_server_ready(function(server)
      local opts = {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
         settings = {},
      }
     
      if server.name == "rust_analyzer" then
         opts.settings = {
            ["rust-analyzer"] = {
               experimental = {
                  procAttrMacros = true,
               },
            },
         }

         opts.on_attach = function(client, bufnr)
            local function buf_set_keymap(...)
               vim.api.nvim_buf_set_keymap(bufnr, ...)
            end
            
            -- Run nvchad's attach
            attach(client, bufnr)
   
            -- Use nvim-code-action-menu for code actions for rust
            buf_set_keymap(bufnr, "n", "<leader>ca", ":CodeActionMenu<CR>", { noremap = true, silent = true })
            buf_set_keymap(bufnr, "v", "<leader>ca", ":CodeActionMenu<CR>", { noremap = true, silent = true })
         end
      end

      server:setup(opts)
      vim.cmd [[ do User LspAttachBuffers ]]
   end)

return M
```

**Comment by siduck76** [comment]
@abalmos we do have proper nvchad defaults! as per lspconfig and lspinstall but yea I didnt think of other plugins related to codeActions etc , would be appreciatable if you made a PR for this :)

**Comment by siduck76** [comment]
add an example config for (lspisntaller + custom keymaps) as the code above , put it here : 

https://github.com/NvChad/nvchad.github.io/blob/src/docs/config.md?plain=1#L437

**Comment by abalmos** [comment]
> @abalmos we do have proper nvchad defaults! as per lspconfig and lspinstall but yea I didnt think of other plugins related to codeActions etc , would be appreciatable if you made a PR for this :)

Maybe I'm doing something wrong then. Without using the `setup_lsp` function to get to at the built in `on_attach` and `capabilities` method, how does nvim-lsp-installer managed LSPs ever get the mappings defined in them? When I use the method currently described in to docs (and your video above), none of the mappings exist.

**Comment by abalmos** [comment]
> add an example config for (lspisntaller + custom keymaps) as the code above , put it here :
> 
> https://github.com/NvChad/nvchad.github.io/blob/src/docs/config.md?plain=1#L437

I will make a PR, but if I don't get to it today I will have to do it next week. Out the door for vacation in just a few hours!

**Comment by siduck76** [comment]
> > add an example config for (lspisntaller + custom keymaps) as the code above , put it here :
> > https://github.com/NvChad/nvchad.github.io/blob/src/docs/config.md?plain=1#L437
> 
> I will make a PR, but if I don't get to it today I will have to do it next week. Out the door for vacation in just a few hours!

no worries! I'll do it myself and create an example config section for lspinstaller and use your config in it

**Comment by siduck76** [comment]
done https://nvchad.github.io/config#advanced-config
