### ISSUE TITLE
Config Not Loading

### ISSUE THREAD

**Issue by things-markj** [NvChad/NvChad#513]
**Describe the bug**
The config is not loading after a clean install using the steps specified in the document, tried it on nvim 0.5 / 0.5.1 / 0.6 multiple times deleting nvim folders in the cache, .config, and the .local/share. Doing PackerSync returns that its not an editor command. Also tried the dev branch and the main branch. Also tried installing the packer package from the aur. Tried also with cellular+vpn and wifi network to check if it is a network issue. The config just doesn't want to load.
**To Reproduce**
git clone https://github.com/NvChad/NvChad ~/.config/nvim
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync

**Expected behavior**
Load the nvchad config and update the packages

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - Operating System: ArchLinux
 - Terminal: Kitty
 - Version of Neovim: 0.5.0

**Additional context**
I have none.

**Comment by G-Rowell** [comment]
Huh, this seems pretty strange.

Can you run these commands please:
```
cd ~/.config/nvim
git rev-parse --short HEAD
git diff
```

And tell me the output?

---

Something worth noting, you are cloning using the HTTPS link. This shouldn't be causing this issue, but SSH is more ideal for GIT

**Comment by things-markj** [comment]
Hi @G-Rowell ,yeah the first command returns ```1c9b5b4``` while the second one opens an empty document.

**Comment by things-markj** [comment]
Found the issue for future reference, changing the location of .vimrc in the bash/zsh environment file, breaks neovim. Thanks for your time and sorry for not spotting the issue it earlier.

**Comment by G-Rowell** [comment]
Ahhh, sorry for not getting back quicker!
Glad you got it sorted!
