### ISSUE TITLE
<Leader>e do not invoke `NvimTreeFocus` when the file is .html, .js, .tsx ...eg

### ISSUE THREAD

**Issue by lchtao26** [NvChad/NvChad#515]
`<Leader>e` is mapping to `:NvimTreeFocus <CR>`

1. It doesn't work when the file is .html, .js, .tsx ...eg, (LSP related)
2. but work for .png, .jpg, .md file

my config file is the same with latest the branch in NvChad.

**Comment by lchtao26** [comment]
And it work when I remap to `<Leader>9`, or something different from `<Leader>e`.

**Comment by G-Rowell** [comment]
I think `<leader>e` is mapped to two things,
thanks for the issue, we're trying to fix a whole lot of bugs rn including this!

**Comment by siduck76** [comment]
should fix it https://github.com/NvChad/NvChad/pull/514/files
