### ISSUE TITLE
Wrong colorscheme in Alacritty

### ISSUE THREAD

**Issue by AlbertoTrigo** [NvChad/NvChad#516]
**Describe the bug**
When using dark colorschemes in alacritty, everythings looks fine. However when the colorscheme is changed into a light one, the text is displayed in ultra-bright colors and cannot be readable.

**To Reproduce**
1. Go to 'https://github.com/toggle-corp/alacritty-colorscheme/'
2. Apply "base16-gruvbox-light-soft.yml" colorscheme
3. Try editing a document

**Expected behavior**
The neovim colorscheme should look the same independent of the terminal colorscheme

**Screenshots**
https://imgur.com/a/7wOY421 Light theme/Black theme

**Desktop:**
 - Operating System : Arch Linux
 - Terminal : Alacritty (latest release)
 - Version of Neovim : 0.5.1

**Comment by G-Rowell** [comment]
@AlbertoTrigo 

Just to check, you are changing the colour scheme within NvChad when you change your terminal colour scheme?

**Comment by siduck76** [comment]
alacritty!!! :angry: :rage:

**Comment by G-Rowell** [comment]
Ahhh, I misread the issue a little.

I'm willing to bet that Alacritty handles colour schemes in a weird/special way compared to other terminal emulators.

Hmmmmm

**Comment by siduck76** [comment]
> Ahhh, I misread the issue a little.
> 
> I'm willing to bet that Alacritty handles colour schemes in a weird/special way compared to other terminal emulators.
> 
> Hmmmmm

nvchad doesnt depend on the terminal's colorscheme tho

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/135588184-70a08976-cebb-49d3-b26f-c31757156e8f.png)

My terminal colorscheme

**Comment by AlbertoTrigo** [comment]
> Just to check, you are changing the colour scheme within NvChad when you change your terminal colour scheme?

Changing the color scheme from within NvChad solves the problem for that current terminal session. However, when opening neovim again, it goes back to displaying random colors.

Which terminal emulator do you consider a better alternative?

**Comment by siduck76** [comment]
one-light 
![image](https://user-images.githubusercontent.com/59060246/135588244-cb6f00f6-2234-4f1b-a370-22670529000b.png)

**Comment by siduck76** [comment]
> > Just to check, you are changing the colour scheme within NvChad when you change your terminal colour scheme?
> 
> Changing the color scheme from within NvChad solves the problem for that current terminal session. However, when opening neovim again, it goes back to displaying random colors.
> 
> Which terminal emulator do you consider a better alternative?

all nvchad screenshots are taken on my system , i use st terminal 

https://github.com/siduck76/st

**Comment by G-Rowell** [comment]
Also, make sure you set your colour scheme inside of NvChad,

something like:
in `custom/chadrc.lua`

`M.ui.colorscheme = "one-light"`

**Comment by AlbertoTrigo** [comment]
> Also, make sure you set your colour scheme inside of NvChad,

Already done

`M.ui = {
  theme = "gruvbox"
}`

**Comment by G-Rowell** [comment]
Ahhh, so trying to understand the problem here....

The light-coloured themes don't look like SiDucks?

1. Do you have transparency turned on in NvChad?
2. Have you tried a different terminal emulator?
3. Have you tried a different allacrity colourscheme?

**Comment by AlbertoTrigo** [comment]
1. No
2. Yes, on other terminal emulators (ie: st) it works.
3. Yes, with other light colorschemes it didn't work either

**Comment by siduck76** [comment]
> 1. No
> 2. Yes, on other terminal emulators (ie: st) it works.
> 3. Yes, with other light colorschemes it didn't work either

so this isnt a nvchad issue anymore , more like alacritty's issue ._.

**Comment by AlbertoTrigo** [comment]
Alright, closing this issue then.

**Comment by G-Rowell** [comment]
So judging by your screenshots,

It seems that there is an issue either with Alacritty, or the colourscheme you are using doesn't handle trasnperency properly.

Would you try another colour scheme just in case?

Though unfortunately I'm willing to be it's an issue with some Alacritty magic.

**Comment by G-Rowell** [comment]
Sorry we can't be of more help Alberto

**Comment by siduck76** [comment]
@AlbertoTrigo  light theme works fine here buddy 
![image](https://user-images.githubusercontent.com/59060246/135592088-a3c0d69e-4268-4060-adde-8a010c682931.png)


dont mind the font , this is just default alacritty

**Comment by AlbertoTrigo** [comment]
> @AlbertoTrigo light theme works fine here buddy

Yeah, because your _alacritty_ colorscheme is dark. Give it a try with a light colorscheme in alacritty not _NvChad_.

**Comment by siduck76** [comment]
> > @AlbertoTrigo light theme works fine here buddy
> 
> Yeah, because your _alacritty_ colorscheme is dark. Give it a try with a light colorscheme in alacritty, not _NvChad_.

oh no :/ 

https://github.com/NvChad/NvChad/issues/516#issuecomment-932058308

**Comment by obtusedev** [comment]
> > > Just to check, you are changing the colour scheme within NvChad when you change your terminal colour scheme?
> > 
> > 
> > Changing the color scheme from within NvChad solves the problem for that current terminal session. However, when opening neovim again, it goes back to displaying random colors.
> > Which terminal emulator do you consider a better alternative?
> 
> all nvchad screenshots are taken on my system , i use st terminal
> 
> https://github.com/siduck76/st

What OS and theme are you using? The terminal themes in the screenshots are so awesome looking and I want to emulate it. Many thanks! :+1:

**Comment by siduck** [comment]
@istrigo sorry I thought that this was an alacritty issue before , its fixed by now! Ik this got fixed wayyyy too late, cuz someone made the same issue recently and then i found out the same issue with kitty hyper etc

https://github.com/NvChad/base46/commit/18668b59cbbd5be885201c9f8aa7336223d54f2e
