### ISSUE TITLE
Code actions dont work at all

### ISSUE THREAD

**Issue by siduck76** [NvChad/NvChad#517]
Steps to reproduce : 

- Write the following code  (setup clangd before)
```
int main (int argc, char *argv[])
{
  return 0 lerolero
}
```
- enter : lua vim.lsp.buf.code_actions()
- you will see no output :/ 

It works in a minimal config tho : https://paste.sh/yqht-uuo#ani1rLvGgWFO--QM6eipEwmY
![image](https://user-images.githubusercontent.com/59060246/135699035-8a560b53-7c16-4b9a-962c-fe20efc2932f.png)

**Comment by abalmos** [comment]
Related to https://github.com/williamboman/nvim-lsp-installer/issues/115?

On vacation at the moment, but as of yesterday afternoon code actions worked fine for me with both tsserver and rust_analyzer installed by nvim-lsp-installer

**Comment by siduck76** [comment]
> Related to [williamboman/nvim-lsp-installer#115](https://github.com/williamboman/nvim-lsp-installer/issues/115)?
> 
> On vacation at the moment, but as of yesterday afternoon code actions worked fine for me with both tsserver and rust_analyzer installed by nvim-lsp-installer

i dont think so , we dont have lspinstaller by default. The minimal config works and I faced this same issue in lunarvim too

**Comment by siduck76** [comment]
Found out the issue! null-ls was causing this , removing it fixed code_actions. Since null-ls isnt added by default on nvchad so I suppose this isnt a nvchad issue anymore , probably upstream.

**Comment by siduck76** [comment]
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/229
