### ISSUE TITLE
Error while trying to edit files in the core directory

### ISSUE THREAD

**Issue by Jasylum** [NvChad/NvChad#521]
I get this error while trying to edit the files in the core directory. This doesn't happen when editing any other files inside the ~/.config/nvim

```
Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:4: Error loading core

/home/user/.config/nvim/lua/core/init.lua:13: Error loading core.custom

./custom.lua:18: loop or previous error loading module 'custom'
```

System = Arch linux 
Terminal = st
Nvim version = 5.0

![1633166983](https://user-images.githubusercontent.com/52153618/135710879-5ebc359f-ce35-42c6-b922-b5c854b924f5.png)

**Comment by siduck76** [comment]
why are you editing the core files? you arent supposed to do that! it'll get overwritten while updating anyways . 

https://nvchad.github.io/config

**Comment by Jasylum** [comment]
But aren't the mappings and all edited in the mapping.lua file which is inside the core directory?

**Comment by siduck76** [comment]
> But aren't the mappings and all edited in the mapping.lua file which is inside the core directory?

no

**Comment by siduck76** [comment]
read the config docs! so many things have been changed :D

**Comment by Jasylum** [comment]
Oh sorry will check it out asap.
