### ISSUE TITLE
Overriding default mappings does not work

### ISSUE THREAD

**Issue by mrassili** [NvChad/NvChad#523]
**Describe the bug**
I try to override the default mapping
```
save_file = "<C-s>", -- save file using :w
```
using
```
M.mappings = {
   save_file = "<leader>w",
}
```
in `custom/chadrc.lua`
but the `<leader>w` still opens the terminal in new window, how can I remove a default mapping altogether ?

**To Reproduce**
☝🏻 

**Expected behavior**
The new mapping should override the default one

**Desktop (please complete the following information):**
 - Operating System: OSX Big Sur
 - Terminal: iTerm2
 - Version of Neovim: 0.5

**Additional context**
Maybe related to #506

**Comment by siduck76** [comment]
this happens probably cuz the opening term terminal is mapped to that, can you try other keys which arent used in default keybinds?

**Comment by mrassili** [comment]
> this happens probably cuz the opening term terminal is mapped to that, can you try other keys which arent used in default keybinds?

That's what I did, I just mapped terminal `new_window` to `<leader>xxxx` instead of `<leader>n` to *delete* the default mapping, there should be a better way I guess

**Comment by siduck** [comment]
> > this happens probably cuz the opening term terminal is mapped to that, can you try other keys which arent used in default keybinds?
> 
> That's what I did, I just mapped terminal `new_window` to `<leader>xxxx` instead of `<leader>n` to _delete_ the default mapping, there should be a better way I guess

hmm just use a  non default key :)

**Comment by siduck** [comment]
@mrassili 

 If you want to use a default mapping which is already mapped to something else then you need to change that too , in your case : 
 
 
![image](https://user-images.githubusercontent.com/59060246/142565538-b57ce30e-0fa0-4293-9da7-3fddca6b8811.png)
