### ISSUE TITLE
Add plugin mappings outside those defined in `core/mappings`

### ISSUE THREAD

**Issue by mrassili** [NvChad/NvChad#524]
**Describe the bug**
Hi,
I'd like to add some mappings related to Telescope, like `git_worktrees -> <leader>t` for example
I know I need to put it inside `M.mappings.plugins ` in `custom/chadrc.lua` but unless I have `git_worktrees` specified inside `M.telescope` in `core/mappings` I cannot map it
I'm wondering how can I extend those plugin specific maps by my own keywords if that makes sense

<img width="937" alt="Screen Shot 2021-10-03 at 1 34 41 AM" src="https://user-images.githubusercontent.com/25288435/135735433-c6b406e4-1ec4-4265-a7c3-528cae0f4330.png">

**Desktop (please complete the following information):**
 - Operating System: Big Sur
 - Terminal: iTerm2
 - Version of Neovim: 0.5

**Additional context**

**Comment by siduck76** [comment]
https://nvchad.github.io/config#add-new-mappings

**Comment by mrassili** [comment]
@siduck76 Yes that's what I did again 😁  but I was hoping to have all overrides centralized in one place (i.e. `M.mappings.plugins` in `custom/chadrc.lua`)

**Comment by Akianonymus** [comment]
You can just copy the M.mappings.plugins from default config to chadrc and replace with whatever you want. It will work.


Everything that is present in default_config.lua can be always overridden by the respective values present in chadrc.lua
