### ISSUE TITLE
Take the dashboard screen shot off the readme 

### ISSUE THREAD

**Issue by macarthy** [NvChad/NvChad#530]
**Describe the bug**
The first screenshot users see is the dashboard, and since its not enabled by default I think it should be removed, or at least moved  

**To Reproduce**
Look a the readme

**Comment by siduck76** [comment]
> **Describe the bug** The first screenshot users see is the dashboard, and since its not enabled by default I think it should be removed, or at least moved
> 
> **To Reproduce** Look a the readme

its still a default plugin in nvchad so i'll keep it.

**Comment by macarthy** [comment]
I was thinking about people like issue #525 who are expecting the dashboard on launch.
