### ISSUE TITLE
attempt to index global 'lspconfig' (a nil value)

### ISSUE THREAD

**Issue by mrassili** [NvChad/NvChad#531]
**Describe the bug**
I have this error `attempt to index global 'lspconfig' (a nil value)` when I open neovim
after adding these lines to my custom lsp config

_lua/custom/plugin_confs/lspconfig.lua_
```
  lspconfig.tsserver.setup {
     --- change that triggers the error ---
      on_attach = function(client)
        -- disable tsserver formatting
        client.resolved_capabilities.document_formatting = false

        -- define an alias
        vim.cmd("command -buffer Formatting lua vim.lsp.buf.formatting()")
        vim.cmd("command -buffer FormattingSync lua vim.lsp.buf.formatting_sync()")

        -- format on save
        vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
      end
   }
```

**Desktop (please complete the following information):**
 - Operating System: Big Sur
 - Terminal: iTerm2
 - Version of Neovim: 0.5

**Comment by siduck76** [comment]
is this needed to be put in the setup?

![image](https://user-images.githubusercontent.com/59060246/135759758-03765092-16bc-44d8-8a80-63af69218239.png)

**Comment by mrassili** [comment]
@siduck76 doesn't matter, the error is still there after I reopen neovim
something to do with `on_attach` if I add it it gives the error 🤷🏻‍♂️
