### ISSUE TITLE
nvim colors doesn't work fine while on tmux

### ISSUE THREAD

**Issue by benja-pieri** [NvChad/NvChad#534]
Hello, I'm using NvChad with tmux and see that the colors doesn't work fine on tmux, I'm sending two screenshots with the aquarium theme. one with tmux and other without tmux.

![notmux](https://user-images.githubusercontent.com/55410870/135921938-10a3f6b1-e023-4028-996f-f7ca0a3414f5.PNG)
![tmux](https://user-images.githubusercontent.com/55410870/135921963-8d7f2d33-def6-4f22-b298-fa951e3a4c28.PNG)

**Comment by Shyber05** [comment]
What was the solution here and what terminal was being used?

**Comment by siduck** [comment]
@Shyber05  you need to set something in your tmux conf, something like xterm256 colors, google it

https://www.reddit.com/r/neovim/comments/uanvdw/neovimtmux_color_problem/ 
https://stackoverflow.com/questions/60309665/neovim-colorscheme-does-not-look-right-when-using-nvim-inside-tmux

**Comment by bj-pieri** [comment]
Hello, it's been almost 3 years since that and I don't post the solution, I just add the following plugins:

**Comment by bj-pieri** [comment]
Hello, it's been almost 3 years since that and I don't post the solution, my bad... I just added the following plugins at my .tmux.conf:
set -g  default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
