### ISSUE TITLE
When opening a file from a terminal window, the undo list is not empty.

### ISSUE THREAD

**Issue by dizzib** [NvChad/NvChad#543]
**Describe the bug**
When opening a file (new or existing) from a terminal window, the undo list seems to contain an extra entry.

**To Reproduce**
1. Fire up the example docker container
2. leader w (open a new terminal window)
3. nvim ho (open a new empty file)
4. Press u to undo
5. Nvim now thinks the file has been modified, and the red close symbol has turned into a green dot.

**Expected behavior**
Nvim should treat the file as not modified and the red close cross should remain as is. Expected status bar to read “Already at oldest change“.

**Desktop (please complete the following information):**
 - Mac big sur 11.5.2
 - iterm2
 - Neovim v0.5.1

**Additional context**
This problem does not occur when opening a file from nvimtree. I suspect the problem is with one of the plugins but I am unable to track it down.

**Comment by peppapig450** [comment]
I think that the opening of a file with a name counts as a buffer write. I am on Mac Big Sur too and I tried doing it without giving the new file a name and it didn't happen. Could be wrong tho.

**Comment by dizzib** [comment]
Thanks. If I remove nvchad by deleting ~/.config/nvim this bug doesn’t happen and nvim 0.5.1 behaves as expected. :)

**Comment by siduck** [comment]
are you executing the nvim ho command in the terminal buffer ( which u opened at step 1 )?

**Comment by dizzib** [comment]
I execute step 3 “nvim ho” from within the terminal buffer/window opened in step 2.

**Comment by siduck** [comment]
> I execute step 3 “nvim ho” from within the terminal buffer/window opened in step 2.

hmm dont! dont run nvim within a nvim terminal buffer. the nested nvim will act weird. instead of that you couldve did Shift + t and then :w ho

**Comment by ev2** [comment]
> > I execute step 3 “nvim ho” from within the terminal buffer/window opened in step 2.
> 
> hmm dont! dont run nvim within a nvim terminal buffer. the nested nvim will act weird. instead of that you couldve did Shift + t and then :w ho

Hi,
   it happens also from a normal linux terminal.
To reproduce it:
   from a just installed and working NvChad config 
`➜ nvim .config/nvim/init.lua`
in cmd execute
```
:undolist
number changes  when               saved                                                                                                                                                        
     1       1  4 seconds ago                                                                                                                                                                   
Press ENTER or type command to continue
```
If I lanch nvim without args and inside open the file via
```
:edit  .config/nvim/init.lua
:undolist
Nothing to undo
```
This behaviour is not present in plain nvim.
Maybe is an autocmd changing the buffer? (which anyway does not change" It only presents a messy undolist)

Great job anyway!

**Comment by siduck** [comment]
@ev2 ive tried plain nvim and i still get this issue . Idk much about this but i dont think its really an issue. probably a feature. whenever you'll have a file on the buffer opened, it'll enable the undolist. :thinking:

**Comment by ev2** [comment]
It does not happen to me on plain nvim (0.6.0), tried just now after
```
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
```
I think it is bearable but worth to be invesigated a bit.
I will try to find it but my lua is still poor

**Comment by siduck** [comment]
> It does not happen to me on plain nvim (0.6.0), tried just now after
> 
> ```
> rm -rf ~/.config/nvim
> rm -rf ~/.local/share/nvim
> rm -rf ~/.cache/nvim
> ```
> 
> I think it is bearable but worth to be invesigated a bit. I will try to find it but my lua is still poor

ooh , nvchad supports 0.6 only
