### ISSUE TITLE
[BUG] changing theme with <leader>th couldn't save, also throws error

### ISSUE THREAD

**Issue by qvieth** [NvChad/NvChad#547]
changing theme with <leader>th couldn't save, also throws error

**Screenshots**
![image](https://user-images.githubusercontent.com/71810726/136747650-816782d5-d68d-4d18-a184-0b60a000cef9.png)

**Comment by siduck76** [comment]
add a chadrc.lua file first. 

Also new docs have been written so check this out https://nvchad.github.io/config

**Comment by qvieth** [comment]
That works! Thanks @siduck76
