### ISSUE TITLE
ColorScheme Isn't being set!

### ISSUE THREAD

**Issue by PhantomRex123** [NvChad/NvChad#549]
**Describe the bug**
After setting colorscheme from the keybinding **<leader> + th** changes aren't being set

**To Reproduce**
1. From docs run this command in the lua/custom folder
```
cp example_init.lua init.lua
cp example_chadrc.lua chadrc.lua
```
2. Open neovim <leader> + th
3. Set colorscheme
4. Exit and go into neovim again
5. Changes not being effected

**Expected behavior**
Colorscheme being changes to onenord/nord

**Desktop (please complete the following information):**
 - Arch linux 
 - Alacritty
 - NVIM v0.5.1

**Additional context**
Neovim installed via pacman.

**Comment by kugiyasan** [comment]
![image](https://user-images.githubusercontent.com/44143656/137012610-6dacf24e-ee87-4c77-9530-d7dd3525934c.png)
Immediately after setting a theme, you should get a prompt in the bottom of the screen, answer `y` to make your theme persistent.

**Comment by sudddddd** [comment]
@siduck this still does not solve the problem that <leader>+th not being able to save the colorscheme.

**Comment by peppapig450** [comment]
When was the last time you updated NvChad? It works for me on Ubuntu, Arch Linux, and MacOS

**Comment by sudddddd** [comment]
It is working normally after restarting my PC. Don't know what happened there.
