### ISSUE TITLE
Potentially new colour scheme

### ISSUE THREAD

**Issue by hsheikhali1** [NvChad/NvChad#554]
**Is your feature request related to a problem? Please describe.**
Just wanted to throw this here to add a potentially new colour scheme for nvchad.

**Describe the solution you'd like**
So here is the link to the colourscheme:
https://github.com/mrjones2014/lighthaus.nvim

**Describe alternatives you've considered**
Well other dark colour schemes 

**Additional context**
https://github.com/mrjones2014/lighthaus.nvim link to the colour

**Screenshot**
https://github.com/mrjones2014/lighthaus.nvim -> screenshots here

**Comment by hsheikhali1** [comment]
Hmm I might try converting it myself and see how it turns out. I'll try myself and create a PR

**Comment by siduck** [comment]
im gonna close this, if you still want to add this theme then make a PR on the our base16 repo
