### ISSUE TITLE
Separate autopairs from cmp

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#567]
Currently, disabling cmp also disables autopairs. I believe this is because enabling autopairs but not cmp causes an error due to the nature of autopair's config. While I understand cmp adds some functionality to autopairs, I think it would be best if there was a conditional in the autopairs config that checks cmp's status variable to dynamically use it.  You can force it to load cmp  in the config file for autopairs by putting in a packer load condition, so that the after=cmp statement does not interfere with them having separate status flags.

Here is an example of the loader statement I used to get rid of such a race condition for coq. 
require("packer").loader("coq_nvim coq.artifacts") --force load coq

Here, in autopairs config you would have something like the pcall check performed in many of the nvchad configs, followed by a loader statement like the one above if the pcall fails, all conditional upon the 'status' variable for cmp.

I would make the changes myself and then PR it, but my NvChad has some small edits even outside of custom I think, and even updating on my end is sometimes difficult with the merge conflicts, let alone trying to pull my insanity to master.

**Comment by siduck76** [comment]
> > @zbirenbaum I'll just add another option for autopairs in the plugin statuses but if the user disables cmp and wants to use autopairs then he must override the default config of autopairs. Is that ok for you?
> 
> Yeah that sounds great to me! I just offered the rest of the explanation in case you wanted to make sure that disabling cmp wouldn't break the defaults for autopairs. I would maybe put a comment in the readme or in the config files that disclaim disabling cmp will require providing your own config for autopairs so that people don't get confused and start posting issues about that lol.

agreed , I'll put a comment in the autopairs config itself ._.
