### ISSUE TITLE
Terminated by signal SIGILL (Illegal instruction) when i use LSP.

### ISSUE THREAD

**Issue by SlyBouhafs** [NvChad/NvChad#573]
It seems that every time the auto completion menu pops up, nvchad crashes. It also crashes when i run `:LspInfo`
This is the error: `terminated by signal SIGILL (Illegal instruction)`

**Desktop (please complete the following information):**
 - OSX 10.15.6
 - Kitty
 - 0.5.1

**Comment by siduck** [comment]
@SlyBouhafs does this still occur? you sure its not the issue with your system?

**Comment by SlyBouhafs** [comment]
@siduck The error still happens, i guess it has to do with my system, i actually just ignored it and started coding on the server, it works fine there.
Closing the issue as there's no way to know what's causing it, it happens with all vim flavored configs that rely on the new lsp.

**Comment by siduck** [comment]
> @siduck The error still happens, i guess it has to do with my system, i actually just ignored it and started coding on the server, it works fine there. Closing the issue as there's no way to know what's causing it, it happens with all vim flavored configs that rely on the new lsp.

are you able to  reproduce that error with a minimal config? if yes then make an upstream issue for this ( lspconfig repo)

**Comment by siduck** [comment]
@SlyBouhafs  https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua
