### ISSUE TITLE
nvim-autopairs stop working after toggle a terminal

### ISSUE THREAD

**Issue by SleepyCatOnTheBed** [NvChad/NvChad#574]
https://user-images.githubusercontent.com/71932200/138586202-c4ad6268-db95-4ade-8480-c8611aa41cba.mp4

I just reinstall nvchad yesterday and find that the autopairs doesn't work properly. This happens not only in JS but also in CPP.

**Comment by siduck** [comment]
@SleepyCatOnTheBed is this fixed now?

**Comment by SleepyCatOnTheBed** [comment]
I apologize for such a late reply. After update nvim-autopairs, the problem seem to be fixed. I will close the issue now
