### ISSUE TITLE
Unable to reopen hidden window terminal

### ISSUE THREAD

**Issue by MikaelElkiaer** [NvChad/NvChad#575]
**Describe the bug**
I am unable to reopen a window terminal once I have hid it, it simply disappears when selecting it.
It, however, works fine with split terminals.

**To Reproduce**
1. Open a new window terminal (default binding `<leader>w`)
2. Hide the terminal (default binding `JK`)
3. Bring up terminal finder (default binding `<leader>W`)
4. Choose the window terminal (hit `<cr>`)
5. See that nothing happens.
6. Open terminal finder again to see that it is gone from the list as well.

**Expected behavior**
Reopens and focuses the window terminal.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Arch (Manjaro i3)
 - Alacritty
 - v0.5.1

**Additional context**
I am using a very close to vanilla nvchad with not many extra plugins or config.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/142564198-77c1aac4-04e7-43e8-9240-c647378943e3.mp4

this works for me

**Comment by MikaelElkiaer** [comment]
Sorry for not following up on this. It also works for me now, after updating something.
