### ISSUE TITLE
nvim-autopairs-completion.cmp deprecated

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#578]
**Describe the bug**
[nvim-autopairs] function nvim-autopairs.completion.cmp setup is deprecated.

**To Reproduce**
1. Open Nvim
2. it shows up in the bottom bar(mind's blanking on what it is called).

**Expected behavior**
It not to show up

**Screenshots**
<img width="698" alt="Screen Shot 2021-10-30 at 3 11 24 AM" src="https://user-images.githubusercontent.com/55930078/139528881-6614e365-a2c3-43c1-8833-04411335939b.png">

**Desktop (please complete the following information):**
 - macOS Monterey
 - iterm2
 - 0.5.1

**Additional context**
happened before and after updating nvchad and doing packersync

**Comment by peppapig450** [comment]
The problem is here, https://github.com/windwp/nvim-autopairs/issues/171. I'd submit a PR but idk how Lua works that well and I dont want to mess anything up.

**Comment by siduck** [comment]
@peppapig450 in your autopairs config (check plugins/others.lua file)

```
   local present1, autopairs = pcall(require, "nvim-autopairs")
   local present2, cmp_autopairs = pcall(require, "nvim-autopairs.completion.cmp")

   if not (present1 or present2) then
      return
   end

   autopairs.setup()

   local cmp = require "cmp"
   cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())
   ```

**Comment by siduck** [comment]
lemme know if this fixes it , then i'll commit this change.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/commit/4b2bbe5d1c2d3587cd284703d2a61075990e8723

**Comment by siduck** [comment]
@peppapig450 lemme know if its fixed!

**Comment by peppapig450** [comment]
Yep it does.
