### ISSUE TITLE
Too stupid to set up lsp (Ive read through the docs, etc...)

### ISSUE THREAD

**Issue by azndd** [NvChad/NvChad#579]
**Describe the bug**
Even though ive copied example_chadrc.lua to lua/custom/chadrc.lua and put pyright into lspconfig, it doesnt seem to work.
I probably did a stupid mistake somewhere, but i just cant figure it out.

**To Reproduce**
^

**Expected behavior**
LSP should work.

**Desktop (please complete the following information):**
 - Operating System: Gentoo
 - Terminal: st
 - Version of Neovim: NVIM v0.5.0
                                   Build type: Release

The content of chadrc.lua is the following:
``
local M = {}
M.options, M.ui, M.mappings, M.plugins = {}, {}, {}, {}

M.plugins = {
   options = {
    lspconfig = {
      servers = {"pyright"},
    },
  },
}

return M
``

**Comment by peppapig450** [comment]
Okay so first off you're gonna wanna create a folder called plugins in the lua/custom directory. Create a file called lspconfig.lua in the /custom/plugins directory. You'll then want to change ur chadrc to, 
```lua
local M = {}
M.options, M.ui, M.mappings, M.plugins = {}, {}, {}, {}

M.plugins = {
   options = {
      lspconfig = {
         setup_lspconf = "custom.plugins.lspconfig",
      },
   },
   default_plugin_config_replace = {},
}
return M
```

Then you go into the lspconfig.lua file and enter this, 
```lua 
local M = {}

M.setup_lsp = function(attach, capabilities)
  local lspconfig = require "lspconfig"

  -- lspservers with default config
  local servers = { "pyright" }

  for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup {
      on_attach = attach,
      capabilities = capabilities,
      -- root_dir = vim.loop.cwd,
      flags = {
            debounce_text_changes = 150,
         },
    }
  end
end
return M
``` 

Now I am not a gentoo user, nor do I know much about it but you also have to make that pyright is on the path.

**Comment by azndd** [comment]
Thank you very much.
Maybe this could be added to the LSP server section, nothing stands there about having to create a folder plugins in custom and creating a file lspconfig.lua
The only thing that stands there is that one has to add
 lspconfig = {      servers = {"html","cssls"},   },
 to the chadrc's lspconfig section.
Now where i got these instructions "custom.plugins.lspconfig" makes total sense, but yeah.

**Comment by siduck** [comment]
> Thank you very much. Maybe this could be added to https://nvchad.netlify.app/getting-started/post-install#install-lsp-servers, nothing stands there about having to create a folder plugins in custom and creating a file lspconfig.lua The only thing that stands there is that one has to add lspconfig = { servers = {"html","cssls"}, }, to the chadrc's lspconfig section. Now where i got these instructions "custom.plugins.lspconfig" makes total sense, but yeah.

creating the plugins folder was just an example. If you didnt read the previous sections + dont know lua ( which was covered in setup section) then yea it'd be confusing for you.

**Comment by peppapig450** [comment]
The netlify one seems to be a bit behind the github.io version and if I am not mistaken google shows that first, so it is completely understandable

**Comment by siduck** [comment]
> The netlify website seems to be a lot behind the github.io version. And if I am not mistaken google shows that first, so it is completely understandable

oh thats dead lol , btw where did you see it? I thought I had updated the links in many places.

**Comment by siduck** [comment]
@azndd  https://nvchad.github.io/config/Lsp%20stuff

**Comment by peppapig450** [comment]
<img width="1392" alt="Screen Shot 2021-10-31 at 8 31 55 PM" src="https://user-images.githubusercontent.com/55930078/139618058-8f0c9a6d-971c-4009-9846-3c56191b02f2.png">
idk why google doesn't like GitHub.io

**Comment by sudddddd** [comment]
I have installed pyright using "williamboman/nvim-lsp-installer" and also added the two scripts as mentioned above. I then added "$HOME/.local/share/nvim/lsp_servers/python/node_modules/pyright to my path. But still I can't run the LSP, I am getting the following error- Unable to find executable. Please check your path and ensure the server is installed.

**Comment by peppapig450** [comment]
@sudddddd ill look into it when i get home from school can u send ur configuration for lsp-installer? and do echo $PATH

**Comment by siduck** [comment]
@sudddddd no need to put at path if you're using lspinstaller
