### ISSUE TITLE
New Onenord 

### ISSUE THREAD

**Issue by benjamin-shih** [NvChad/NvChad#580]
**Describe the solution you'd like**
Any chance we could get an integration of this onenord theme? [Onenord](http://neovimcraft.com/plugin/rmehri01/onenord.nvim/index.html)
Would like to try it out in NvChad

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/397#issuecomment-907183192 

Btw we already have a onenord theme , check it.
