### ISSUE TITLE
<leader>+th giving telescope error: attempt to get length of local 'message' (a nil value) after opening a file

### ISSUE THREAD

**Issue by sudddddd** [NvChad/NvChad#581]
**Describe the bug**
After opening a file in neovim and pressing <leader>+th to change the theme, I get the following error- 
```
Error executing vim.schedule lua callback: ...er/opt/telescope.nvim/lua/telescope/previewers/utils.lua:148: attempt to get length of local 'message' (a nil value)
Press ENTER or type command to continue
```

After pressing ENTER, the window that opens is not showing the preview of the file on the right part of the window.

**To Reproduce**
1. nvim <any_file>
2. <leader>+th

**Expected behavior**
Preview of the file should be shown on the window that opens up.

**Screenshots**
![image](https://user-images.githubusercontent.com/6321314/139570894-163782c8-3521-4966-a8ce-1b394c2c773e.png)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 21.04
 - Terminal: Terminator
 - Version of Neovim: NVIM v0.5.1

**Additional context**
This problem goes away if I press <leader>+th a second time after I quit from the first window. 
Also, after pressing <leader>+ff or <leader>+fw first after opening a file and then closing the popup window, I press <leader>+th, then the <leader>+th command works as expected.

**Comment by siduck** [comment]
@sudddddd yes this is a known issue https://github.com/NvChad/extensions/issues/3 , will take a while to look on it. probably @Akianonymus can help.

**Comment by sudddddd** [comment]
Okay, was not able to find it here, hence I asked.
