### ISSUE TITLE
Workspace statusline stuck on "empty title (0%)"

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#583]
This happens exclusively with CCLS and I have tried everything, including making a git repo, a .ccls, and messing with the ccls config, but I cannot figure out for my life why there's this stupid flashing indicator circle next to 'empty title (0%)' and I also can't seem to find the code which is creating the text despite searching for the keywords. Its obviously related to the 'loading workspace %' which appears on the statusline while the lsp is indexing, but ccls is _threaded_ and running on 24 of them by default, so its impossible it hasn't completed my test.c helloworld file. I even tried dropping the threads but to no avail. 

In my past experience ccls has been much better than clangd, especially for large projects. Pls help, if someone can point me in even vaguely the right direction I'll fix it myself and make a pr.

**Comment by peppapig450** [comment]
I think this is an upstream issue, so maybe make an issue request there.

**Comment by zbirenbaum** [comment]
> I think this is an upstream issue, so try opening an issue there.

I was afraid that was the case. I thought that NvChad implemented the workspace thing on the statusline, is it part of cmp or feline then?

**Comment by siduck** [comment]
> > I think this is an upstream issue, so try opening an issue there.
> 
> I was afraid that was the case. I thought that NvChad implemented the workspace thing on the statusline, is it part of cmp or feline then?

No it's a custom component in the feline config , check the statusline config. This is surely lsp related tho.

**Comment by zbirenbaum** [comment]
> > > I think this is an upstream issue, so try opening an issue there.
> 
> > 
> 
> > I was afraid that was the case. I thought that NvChad implemented the workspace thing on the statusline, is it part of cmp or feline then?
> 
> 
> 
> No it's a custom component in the feline config , check the statusline config. This is surely lsp related tho.

Thanks for the info. I'll make an issue post over there and just override feline to do a visual workaround in the meantime. Appreciate the help!

**Comment by siduck** [comment]
> > > > I think this is an upstream issue, so try opening an issue there.
> > 
> > 
> > > 
> > 
> > 
> > > I was afraid that was the case. I thought that NvChad implemented the workspace thing on the statusline, is it part of cmp or feline then?
> > 
> > 
> > No it's a custom component in the feline config , check the statusline config. This is surely lsp related tho.
> 
> Thanks for the info. I'll make an issue post over there and just override feline to do a visual workaround in the meantime. Appreciate the help!

noooo , not yet!

**Comment by siduck** [comment]
ok so this was the component 
```
function()
      local Lsp = vim.lsp.util.get_progress_messages()[1]
      if Lsp then
         local msg = Lsp.message or ""
         local percentage = Lsp.percentage or 0
         local title = Lsp.title or ""
         local spinners = {
            "",
            "",
            "",
         }

         local success_icon = {
            "",
            "",
            "",
         }

         local ms = vim.loop.hrtime() / 1000000
         local frame = math.floor(ms / 120) % #spinners

         if percentage >= 70 then
            return string.format(" %%<%s %s %s (%s%%%%) ", success_icon[frame + 1], title, msg, percentage)
         else
            return string.format(" %%<%s %s %s (%s%%%%) ", spinners[frame + 1], title, msg, percentage)
         end
      end
      return ""
   end,
   enabled = shortline or function(winid)
      return vim.api.nvim_win_get_width(winid) > 80
   end,
```
