### ISSUE TITLE
(Potential PR) Autopairs fix +  Hotswappable cmp and coq configurations

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#584]
So I go back and forth between cmp and coq, and in my sleep deprived annoyance at having to maintain separate configs for autopairs, lsp_setup files, and more, I wrote a bunch of code so that everything automatically swaps just by changing the status flags for only coq and cmp and running then running PackerSync. Honestly it is beautifully convenient and for anyone that occasionally works on large projects with slow LSPs (like pyright) it can really be helpful. It may take a bit but I could probably fairly easily generalize and move over the functionality from custom into the main repo and make a pr if there is any interest and the devs think it suits their mission. I wanted to ask before putting in the effort to move it out of custom and improve the code since it would take a bit.

I made sure that there's no performance hit (my startup time opening a file in a large project like init.lua is 073.250) and from a user perspective all it really does is add a flag in chadrc's plugin_status for coq.

As for Autopairs:
1. If cmp is disabled autopairs cannot load, defeating the purpose of having changed disable to its own flag
2. There's bug somewhere with overriding config for autopairs but idk exactly what it is. Currently I have commented out autopairs in the main init.lua, and have it setup in custom.lua instead. 'after' gets its value from a function call which returns "nvim_coq" or "nvim-cmp" depending on plugin_status so that there isn't a race condition for the cmp specific functionality.

use {
  "windwp/nvim-autopairs",
  disable = not status.autopairs,
  after = "nvim-cmp", --this is a problem
  config = override_req("nvim_autopairs", "(plugins.configs.others).autopairs()"),
}

The autopairs fix is pretty basic and if its decided that the stuff about coq shouldn't be implemented for some reason, setting after conditionally to bufenter or something in my function is pretty easy, though I would have to make a new file or put a conditional in the current config to support the cmp-less autopairs. Until I figure out why the override call is broken, I think its a pretty good solution and I'll probably end up making a pr for the autopairs fix sometime tomorrow regardless of the stuff above.

**Comment by siduck** [comment]
@zbirenbaum do you use cmp with Coq? You disable cmp right? If yes then ig we could do this in autopairs config : 

after = function ()
 cmp_status= check if compe is disabled via chadrc
If not then return 'nvim-cmp'
end

**Comment by siduck** [comment]
I'll make this change when I get back home. In college rn so don't mind the pseudo code lol

**Comment by siduck** [comment]
oh no 'after' expects a table and a function doesnt work in it. @zbirenbaum can you please try this ? This is just a wild guess lol 

```
      after = "nvim-cmp" or "coq",
```

**Comment by siduck** [comment]
nvm it doesnt work

**Comment by siduck** [comment]
added the change . Ig this is good to close now.

**Comment by zbirenbaum** [comment]
Here is the working switch from my config:
```

  use {
    "windwp/nvim-autopairs",
    after = aft,
    disable = not plugin_status.autopairs,
    config = function()
      require "custom.plugins.autopairs_selection"
    end,
  }
```
Where aft is:
```
local function afterchoice()
  if plugin_status.coq_nvim then
    return "coq_nvim"
  elseif plugin_status.cmp then
    return "nvim-cmp"
  end
end
local aft = afterchoice()
```



Where autopairs_selection is:
```
local plugin_status = require("core.utils").load_config().plugins.status
if plugin_status.coq then
  require "custom.plugins.coq_configs.autopairs_coq"
elseif plugin_status.cmp then
  require "custom.plugins.cmp_configs.autopairs_cmp"
end
```

**Comment by siduck** [comment]
I had given this a thought but this would mean it'll support coq additionally only. But adding an option in the chadrc would mean , it could be loaded after completion-nvim , coc.nvim , compe! Much functional ig

**Comment by zbirenbaum** [comment]
> I had given this a thought but this would mean it'll support coq additionally only. But adding an option in the chadrc would mean , it could be loaded after completion-nvim , coc.nvim , compe! Much functional ig

What if we added the override in the switch, by importing it similar to plugin_status, so that there's an elseif <user-defined plugin>?

**Comment by siduck** [comment]
I didnt quite understand that :smile: , but nvm it . The change has been does so it doesnt matter.

**Comment by siduck** [comment]
> > I had given this a thought but this would mean it'll support coq additionally only. But adding an option in the chadrc would mean , it could be loaded after completion-nvim , coc.nvim , compe! Much functional ig
> 
> What if we added the override in the switch, by importing it similar to plugin_status, so that there's an elseif ?
> 
> edit: I was thinking in reverse! I could just make the switch set the override lmao. Thanks, good change.
I didnt quite get that smile , but nvm it . The change has been does so it doesnt matter.
