### ISSUE TITLE
man page?

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#585]
**Is your feature request related to a problem?**
well not really but having the documentation open in a tab can get a little annoying

**Describe the solution you'd like**
Create a man page for nvchad so the documentation can be viewed easier

**Describe alternatives you've considered**
none

**Additional context**
maybe also implement a lua or python script to update the man page to keep it in sync with the website
(idk rlly know how man pages are made)

**Comment by siduck** [comment]
Ig this is related to https://github.com/NvChad/NvChad/issues/582 , so I'll close this.
