### ISSUE TITLE
How do hooks work?

### ISSUE THREAD

**Issue by danielyrovas** [NvChad/NvChad#586]
I've been reading the configuration for NvChad and I think I understand most of Lua but I'm unsure how the hooks function or what their purpose is.
   
Thanks for making such an awesome NeoVim configuration by the way, the code base seems quite modular and useable.

**Comment by zbirenbaum** [comment]
https://www.lua.org/pil/23.2.html

Hooks are fairly intuitive. They allow you to 'hook' into code running elsewhere during a specific event. To give an example in another language which is applicable, java has a JVM shutdown hook. It runs after normal code is all complete, right before the JVM completely exits. The real use case for this hook is cleanup during the normal exiting phase of the application (e.g. it wont run if you run kill -9 or shutdown your computer while the application is running, but will run if you call System.exit()).

The hooks in nvchad allow us to link the code in something like custom/init.lua to run at a specific point during the normal routine which is to run plugins/init.lua during packer's plugin installation phase.


The line in plugins/init.lua after all use statements:
```
...
   require("core.hooks").run("install_plugins", **use**)
end)

```
The hooked code in custom/init.lua
```
local hooks = require "core.hooks"
hooks.add("install_plugins", function(**use**)
  use {
...
  }
...
end)
```

The hooks.add() function in core/hooks.lua to add a hook to the list is triggered in custom/init.lua
```
M.add = function(name, fn)
   if not (has_value(allowed_hooks, name)) then
      error("Custom lua uses unallowed hook " .. name)
   end
   if hooks[name] == nil then
      hooks[name] = {}
   end
   table.insert(hooks[name], fn)
end
```
The hooks .run() function in core/hooks.lua called in plugins/init.lua to trigger the hooked code from custom/init.lua
```
M.run = function(name, args)
   if hooks[name] == nil then
      return
   end

   for _, hook in pairs(hooks[name]) do
      hook(args)
   end
end
```

I will note that NvChad makes use of a hook whitelist for reasons I am unaware of currently, so adding a custom hook outside of the ones in this table will fail unless you add it to the table, which will be overwritten or cause a merge conflict when you update:
```
local allowed_hooks = {
   "install_plugins",
   "setup_mappings",
   "ready",
}
```

**Comment by danielyrovas** [comment]
Thanks for the detailed response! I didn't realise they were something built into Lua.

**Comment by danielyrovas** [comment]
In the above case of the plugin hook, what is the difference between using the hook or simply 
```lua
pcall(require, 'custom.plugins')
```
at the end of the plugins.init.

**Comment by zbirenbaum** [comment]
> In the above case of the plugin hook, what is the difference between using the hook or simply
> 
> ```lua
> pcall(require, 'custom.plugins')
> ```
> 
> at the end of the plugins.init.

Notice that in the code within plugins/init.lua `use` is passed into the hook
```
   require("core.hooks").run("install_plugins", **use**)
```
Unlike:
```
pcall(require, 'custom.plugins')
```

By using the hook we are able to pass in context, allowing us to not have to call the packer initialization process as is done in plugins/init.lua with this code at the top:
```
local present, packer = pcall(require, "plugins.packerInit")

if not present then
   return false
end

local use = packer.use

```

**Comment by siduck** [comment]
I think this should look much cleaner now https://github.com/NvChad/NvChad/blob/dev/lua/core/hooks.lua

**Comment by fernandes** [comment]
hey @siduck 👋 

please, where is `ready` hook run? I could find `install_plugins` on `lua/plugins/init` and `setup_mappings` on `lua/core/mappings` but nothing about `ready`? or is it something I should call on custom? 🤔 

thank you

**Comment by siduck** [comment]
> hey @siduck 👋
> 
> please, where is `ready` hook run? I could find `install_plugins` on `lua/plugins/init` and `setup_mappings` on `lua/core/mappings` but nothing about `ready`? or is it something I should call on custom? 🤔
> 
> thank you

I had removed it , I cleaned the hooks logic few months ago!

**Comment by fernandes** [comment]
sweet! anything like `ready` hook? something to get run after everything else? thanks

**Comment by siduck** [comment]
> sweet! anything like `ready` hook? something to get run after everything else? thanks

no

**Comment by fernandes** [comment]
@AntonPieper is this what you are looking for https://nvchad.github.io/config/Custom%20config#add-plugins ?

**Comment by AntonPieper** [comment]
> @AntonPieper is this what you are looking for https://nvchad.github.io/config/Custom%20config#add-plugins ?

Thanks, that was what I was looking for👍
