### ISSUE TITLE
Dashboard plugin doesn't work

### ISSUE THREAD

**Issue by kamack38** [NvChad/NvChad#587]
**Describe the bug**
Even though I turned on dashboard plugin in `chadrc.lua` file, it still doesn't work. Also I turned on dashboard at vim enter, but it won't open and any keybindings of this plugin also don't work.

**To Reproduce**
```lua
M.plugins = {
   status {
      dashboard = true
   }
}
```
**Expected behavior**
Dashboard opens at neovim enter.

**Desktop (please complete the following information):**
 - Windows 10
 - Windows Terminal v1.12.2931.0
 - Neovim v0.5.1

**Comment by mister-coded** [comment]
Do `:PackerSync`

**Comment by kamack38** [comment]
```
Failed to update hrsh7th\nvim-cmp
```

**Comment by peppapig450** [comment]
When was the last time you updated nvchad? nvim-cmp had a breaking change that was patched recently

**Comment by kamack38** [comment]
I have the latest version
![obraz](https://user-images.githubusercontent.com/64226248/140186267-a205ce2a-3624-43b4-b5a7-611a9830cbba.png)

**Comment by kamack38** [comment]
After running health checks I get
```
- WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- ERROR: lua(highlights): Failed to load parser: uv_dlopen: C:\Users\kamac\AppData\Local\nvim-data\site\pack\packer\opt\nvim-treesitter\parser\lua.so nie jest prawid<b3>ow<b9> aplikacj<b9> systemu Win32.

  - ERROR: lua(locals): Failed to load parser: uv_dlopen: error: 193
  - ERROR: lua(folds): Failed to load parser: uv_dlopen: error: 193
  - ERROR: lua(indents): Failed to load parser: uv_dlopen: error: 193
  - ERROR: lua(injections): Failed to load parser: uv_dlopen: error: 193

**Comment by kamack38** [comment]
After running health checks I get
```
- WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- ERROR: lua(highlights): Failed to load parser: uv_dlopen: C:\Users\kamac\AppData\Local\nvim-data\site\pack\packer\opt\nvim-treesitter\parser\lua.so nie jest prawid<b3>ow<b9> aplikacj<b9> systemu Win32.

  - ERROR: lua(locals): Failed to load parser: uv_dlopen: error: 193
  - ERROR: lua(folds): Failed to load parser: uv_dlopen: error: 193
  - ERROR: lua(indents): Failed to load parser: uv_dlopen: error: 193
  - ERROR: lua(injections): Failed to load parser: uv_dlopen: error: 193

**Comment by peppapig450** [comment]
Ill try it on a windows 10 vm when I'm done with homework. I am on Windows 11 Insider dev build so idk if it will work the same

**Comment by peppapig450** [comment]
I think you forgot a comma actually this is what my chadrc looks like
```lua

local M = {}
M.options, M.ui, M.mappings, M.plugins = {}, {}, {}, {}

-- NOTE: To use this, make a copy with `cp example_chadrc.lua chadrc.lua`

--------------------------------------------------------------------

-- To use this file, copy the strucutre of `core/default_config.lua`,
-- examples of setting relative number & changing theme:

-- M.options = {
--    relativenumber = true,
-- }

 M.ui = {
   theme = "uwu"
 }

-- NvChad included plugin options & overrides

M.plugins = {
   options = {
      lspconfig = {
         setup_lspconf = "custom.plugins.lspconfig",
      },
   },
   status = {
      dashboard = true,
   },
   -- To change the Packer `config` of a plugin that comes with NvChad,
   -- add a table entry below matching the plugin github name
   --              '-' -> '_', remove any '.lua', '.nvim' extensions
   -- this string will be called in a `require`
   --              use "(custom.configs).my_func()" to call a function
   --              use "custom.blankline" to call a file
   default_plugin_config_replace = {},
 }
return M
```

**Comment by drull1000** [comment]
Thank you! My dashboard was not working either, but now it has been fixed. The problem was the comma.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/140235929-d9cb773f-8b37-4f02-9cf9-acbf02136c0f.mp4

**Comment by peppapig450** [comment]
How was the ascii art generated by the way? I was trying to change it the other day but it kept looking bad D:

**Comment by siduck** [comment]
> How was the ascii art generated by the way? I was trying to change it the other day but it kept looking bad D:

it depends on your terminal , if it supports boxdraw braillie then it'll make all the braillie chars ( dots ) look joined together , if you're on linux then you could use my st build . https://github.com/siduck76/st

**Comment by peppapig450** [comment]
Thanks!

**Comment by kamack38** [comment]
Actually, the config file was named `chardrc.lua` instead of `chadrc.lua` so I suppose this was the issue then, but adding commas also helped.

**Comment by archiif** [comment]
I'm also stuck with this issue, but the solutions above doesn't work. I know that nvim is detecting my `chadrc.lua` correctly because I can change my theme using it, but setting `M.plugins.status.dashboard` to `true` doesn't enable the dashboard even after `:PackerSync`.
Seeing @siduck's video, you can see a `Installed glepnir/dashboard-nvim` message after finishing the sync, which doesn't show up on my side.
What am I doing wrong here? Is there a change in the API since this issue?
This is my `chadrc.lua`:
```lua
-- Just an example, supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.ui = {
   theme = "gruvchad",
}

M.plugins = {
   status = {
      dashboard = true,
   },
}

return M
```

**Comment by archiif** [comment]
Ah, just found out that the plugin was replaced recently:
https://github.com/NvChad/NvChad/commit/ceaf02e0bffe291a1377da907a5f45c78e1593bd
Dashboard now works with `M.plugins.status.alpha` set to `true`

**Comment by axl72** [comment]
A copy chadrc.lua config file from here and I got this. 
![image](https://user-images.githubusercontent.com/76046080/188322444-6ff8e4c8-1d4f-4aad-b92f-050ef037781f.png)

But nvim dosnt show dashboard

**Comment by NielsKersic** [comment]
For anyone wanting to enable the dashboard, go to `lua/plugins/init.lua` and for goolord/alpha-nvim set `disable = false`.
```lua
["goolord/alpha-nvim"] = {
  after = "base46",
  disable = false,
  config = function()
    require "plugins.configs.alpha"
  end,
},
```

**Comment by siduck** [comment]
> For anyone wanting to enable the dashboard, go to `lua/plugins/init.lua` and for goolord/alpha-nvim set `disable = false`.
> 
> ```lua
> ["goolord/alpha-nvim"] = {
>   after = "base46",
>   disable = false,
>   config = function()
>     require "plugins.configs.alpha"
>   end,
> },
> ```

thats not the way, you have to do it in your custom config, just put this in your custom plugin list, reopen nvim and do packersync


```lua
["goolord/alpha-nvim"] = {
  disable = false,
},
```

**Comment by NielsKersic** [comment]
Whoops, I guess I got a little bit too excited about figuring out the wrong way myself. Thanks for the correction!

**Comment by Khasirah** [comment]
> simplescreenrecorder-2021-11-04_05.15.43.mp4

i'm stuck alpha doesn't show up
this is my tree folder and my chadrc

![image](https://user-images.githubusercontent.com/46507686/200705762-01f51cef-f768-4fe2-9fce-caa7814448dc.png)

i already did `:PackerSync`

**Comment by siduck** [comment]
please reopen neovim and do packersync @Khasirah

**Comment by Khasirah** [comment]
> please reopen neovim and do packersync @Khasirah

![image](https://user-images.githubusercontent.com/46507686/200726215-68eef528-28c6-4ab7-a077-0ae391f0f271.png)
 still get same error

**Comment by siduck** [comment]
> > please reopen neovim and do packersync @Khasirah
> 
> ![image](https://user-images.githubusercontent.com/46507686/200726215-68eef528-28c6-4ab7-a077-0ae391f0f271.png) still get same error

status, options? there are no such plugins, you have something seriously wrong in your config :/

**Comment by Khasirah** [comment]
:(

**Comment by siduck** [comment]
> :(

check our examples_config repo and use that as custom config, its a good starting point

**Comment by JDeepD** [comment]
Can confirm. This is the same issue with me. For some reason, all the options inside `M.plugins` are getting cloned.
For this config,
```
M.plugins = {
  status = {
    dashboard = true,
  }
}
```
Packer is trying to clone `https://github.com/status.git`
![image](https://user-images.githubusercontent.com/64089730/210231196-4aaced75-d49a-4651-a9ed-340240c978ef.png)

For @Khasirah , Packer is trying to clone `status` and `options` since he passed those in `M.plugins`

**Comment by siduck** [comment]
@JDeepD  the status option is the old syntax and was removed ages ago

**Comment by Vealcoo** [comment]
@siduck It still doesnt work for me :(
my neovim version is NVIM v0.8.2
and there is my setup

        ["goolord/alpha-nvim"] = {
          after = "base46",
          disable = false,
          config = function()
            require "plugins.configs.alpha"
          end,
        },

**Comment by siduck** [comment]
> @siduck It still doesnt work for me :( my neovim version is NVIM v0.8.2 and there is my setup
> 
> ```
>     ["goolord/alpha-nvim"] = {
>       after = "base46",
>       disable = false,
>       config = function()
>         require "plugins.configs.alpha"
>       end,
>     },
> ```

dont add the after and config lines, only the disable line is enough. reopen neovim and do packersync

**Comment by eyejayvee** [comment]
This worked for me:
``` lua
---@type ChadrcConfig
local M = {}

M.nvdash = {
        load_on_startup = true
}

return M
```

**Comment by SaiShubham624** [comment]
I was having the same problem when I noticed that in [nvconfig.lua](https://github.com/NvChad/ui/blob/v3.0/lua/nvconfig.lua), `nvdash` is not inside `ui` field, but outside of it. When I put this in my `chadrc.lua`, it worked!

```
---@type ChadrcConfig
local M = {}

M.base46 = {
  theme = "gruvbox",
}

M.nvdash = {
  load_on_startup = true,
}
return M
```
