### ISSUE TITLE
How to set default terminall shell?

### ISSUE THREAD

**Issue by kamack38** [NvChad/NvChad#588]
How can I set the default terminal shell?

**Comment by siduck** [comment]
how do you do it in normal vim?

**Comment by kamack38** [comment]
```
:set shell=shell.exe
```

**Comment by kamack38** [comment]
But I don't know how to add start parameters

**Comment by siduck** [comment]
> But I don't know how to add start parameters

did you read our docs? if yes then you should know basic lua and converting vimscript code to lua :/
