### ISSUE TITLE
Can't preview buffer or hidden terminal

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#590]
**Describe the bug**
leader + W and failed to preview hidden terminal.

**To Reproduce**
1.  leader + h (open terminal)
2.  j + k (normal mode)
3.  leader + x (hide terminal)
4.  leader + shift + w (view hidden terminal)
5.  failed to load.

**Desktop (please complete the following information):**
 - Windows 10 & Pop OS
 - Windows Terminal (WSL2) & Kitty
 - Neovim v0.6.0

**Others**
I believe this issue is similar/duplicate to https://github.com/NvChad/NvChad/issues/589#issue-1044911464 and https://github.com/NvChad/NvChad/issues/575#issue-1037716582

https://user-images.githubusercontent.com/73665622/140422547-cadd4365-cc55-4a6f-adb8-8898cb6c3d1f.mp4

**Comment by siduck** [comment]
@GreatestOfAllTimee do packersync again and lemme know if it's fixed.

**Comment by GreatestOfAllTimee** [comment]
No its not.

**Comment by GreatestOfAllTimee** [comment]
> 
> 
> @GreatestOfAllTimee do packersync again and it should be fixed.

Fixed!
