### ISSUE TITLE
This is not an issue i used nvchad for a long period of time and i liked it very much then wanted to build my own config 

### ISSUE THREAD

**Issue by imSafdarAwan** [NvChad/NvChad#591]
so i had to leave the nvchad but i liked the colorschems where could i find these color schemes color palletes by the way i wanted to copy some of your color schemes but could do that because can't figure out where did you put your config files for colors schemes

**Comment by imSafdarAwan** [comment]
i cant figure out where is the hl_themes are i thought it would be in the packer dir but couldn't find

**Comment by Pocco81** [comment]
All of the color palettes can be found [here](https://github.com/NvChad/nvim-base16.lua).

**Comment by imSafdarAwan** [comment]
> All of the color palettes can be found [here](https://github.com/NvChad/nvim-base16.lua).

thanks
