### ISSUE TITLE
tsserver not starting

### ISSUE THREAD

**Issue by Jasylum** [NvChad/NvChad#592]
So I installed tsserver through the lsp-installer for javascript, but it doesn't load. Do I need to manually set the configuration for tsserver to work correctly or am I doing something wrong?

https://user-images.githubusercontent.com/52153618/140502926-4e30049c-5e0f-4d62-8a25-615c0cc62ab1.mp4

**Comment by siduck** [comment]
make sure your root_dir matches well to the default ones. check lspconfig's tsserver section in config.md

**Comment by Jasylum** [comment]
So do I need to place the config in a separate file and then require that file?

**Comment by siduck** [comment]
> So do I need to place the config in a separate file and then require that file? and where do you place these files? EDIT: Got it

just to make sure! For example the rust lsp will not load without cargo.toml in the root dir ( i.e current dir ) , same with other languages probably.

**Comment by Jasylum** [comment]
One more thing. Do mappings for some lsp not work properly? I have a code action available but the default keybindings would not work for it. Similarly the bindings for renaming and more are also not working.

**Comment by siduck** [comment]
> One more thing. Do mappings for some lsp not work properly? I have a code action available but the default keybindings would not work for it. Similarly the bindings for renaming and more are also not working.

because you need to attach em. If you're using lspinstaller then this could be your lspconfig : 

```
local M = {}

M.setup_lsp = function(attach, capabilities)
   local lsp_installer = require "nvim-lsp-installer"

   lsp_installer.on_server_ready(function(server)
      local opts = {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
         settings = {},
      }

      server:setup(opts)
      vim.cmd [[ do User LspAttachBuffers ]]
   end)
end

return M
```

**Comment by siduck** [comment]
make sure you remove this config from here 
![image](https://user-images.githubusercontent.com/59060246/140535388-89931a28-8d0d-4a10-835c-844cab087f17.png)

and you should know how to override the default lspconfig with custom one.

**Comment by siduck** [comment]
If you're new to nvchad then I suggest reading this https://nvchad.github.io/config/Walkthrough

**Comment by Jasylum** [comment]
> make sure you remove this config from here ![image](https://user-images.githubusercontent.com/59060246/140535388-89931a28-8d0d-4a10-835c-844cab087f17.png)
> 
> and you should know how to override the default lspconfig with custom one.

I added this in the plugins/init.lua file so do I remove them and add them to the custom/init.lua file?

**Comment by siduck** [comment]
yes just remove the config section there and add the one i sent into your custom lspconfig.lua file . No you dont need to setup the config for every lsp!

**Comment by Jasylum** [comment]
But in the default config has been set for the rust_analyzer only right?

**Comment by siduck** [comment]
> But in the default config has been set for the rust_analyzer only right?

thats just an example!!! :angry:

**Comment by siduck** [comment]
you better check our docs soon and understand the whole config well rather than checking waifus :rocket: :smile:

**Comment by Jasylum** [comment]
No I mean do I change the rust_analyzer to for example clangd and so on?

**Comment by Jasylum** [comment]
> > But in the default config has been set for the rust_analyzer only right?
> 
> thats just an example!!! angry

I am really sorry for being such a noob

**Comment by siduck** [comment]
> No I mean do I change the rust_analyzer to for example clangd and so on?

yep

**Comment by siduck** [comment]
I'll mention the example statement in the docs to make it clear!

**Comment by Jasylum** [comment]
One last question. So can I add other keybindings from the plugins/configs/lspconfig.lua for renaming and stuff?

**Comment by siduck** [comment]
> One last question. So can I add other keybindings from the plugins/configs/lspconfig.lua for renaming and stuff?

you mean overriding the default lsp keybindings?

**Comment by Jasylum** [comment]
No I mean importing other keybindings

**Comment by siduck** [comment]
> No I mean importing other keybindings

like?

**Comment by siduck** [comment]
you can just do that in custom/init.lua or any file then source that file into init.lua

**Comment by Jasylum** [comment]
> > No I mean importing other keybindings
> 
> like?

`  buf_set_keymap("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>", opts)
   buf_set_keymap("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>", opts)
   buf_set_keymap("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>", opts)
   buf_set_keymap("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts)
   buf_set_keymap("n", "gk", "<cmd>lua vim.lsp.buf.signature_help()<CR>", opts)
   buf_set_keymap("n", "<space>wa", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", opts)
   buf_set_keymap("n", "<space>wr", "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", opts)
   buf_set_keymap("n", "<space>wl", "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", opts)
   buf_set_keymap("n", "<space>D", "<cmd>lua vim.lsp.buf.type_definition()<CR>", opts)
   buf_set_keymap("n", "<space>rn", "<cmd>lua vim.lsp.buf.rename()<CR>", opts)
`
These

**Comment by siduck** [comment]
> > > No I mean importing other keybindings
> > 
> > 
> > like?
> 
> ` buf_set_keymap("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>", opts) buf_set_keymap("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>", opts) buf_set_keymap("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>", opts) buf_set_keymap("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts) buf_set_keymap("n", "gk", "<cmd>lua vim.lsp.buf.signature_help()<CR>", opts) buf_set_keymap("n", "<space>wa", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", opts) buf_set_keymap("n", "<space>wr", "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", opts) buf_set_keymap("n", "<space>wl", "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", opts) buf_set_keymap("n", "<space>D", "<cmd>lua vim.lsp.buf.type_definition()<CR>", opts) buf_set_keymap("n", "<space>rn", "<cmd>lua vim.lsp.buf.rename()<CR>", opts)` These

bruh those are default keybinds. you dont need to import them.

**Comment by siduck** [comment]
maybe Im wrong but idk much with lspisntaller

**Comment by Jasylum** [comment]
Ok I will try to figure it out. Thank you for your help.
