### ISSUE TITLE
Make lsp mappings configurable in chadrc

### ISSUE THREAD

**Issue by DanielCardonaRojas** [NvChad/NvChad#593]
**Describe the solution you'd like**

It would be nice to configure the hardcoded mappings in confgs/lspconfig.lua and have these configured through some 
user defined section in chadrc.

Specifically, I would like to configure code_action,  goto_prev, goto_next, and formatting bindings but I can imagine other users wanting to configure other ones as well.

**Comment by siduck** [comment]
those mappings are a lot and we'd prefer to stay with the default behaviour but anyways you can just override the lspconfig. I guess it would be better write your preferred lsp mappings in a different file.

an example to override lspconfig : 

![image](https://user-images.githubusercontent.com/59060246/140536993-7eefc7bf-efac-438a-bebf-1eb9476a4bc7.png)

**Comment by DanielCardonaRojas** [comment]
How about making on attach function overridable?

**Comment by siduck** [comment]
> How about making on attach function overridable?

sounds good, Im busy a lil these days cuz of college and I barely get time for nvchad + programming :(( . PR's are welcomed
