### ISSUE TITLE
attempt to index 'autopairs' (a nil value)

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#595]
**Describe the bug**
E5108: Error executing lua ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:844: /User
s/nick/.config/nvim/lua/plugins/init.lua:208: attempt to index field 'autopairs' (a nil value)

**To Reproduce**
1. <leader+u+u> Update nvchad 
2. :PackerSync 
3. See error

**Expected behavior**
No errors!

**Screenshots**
<img width="792" alt="Screen Shot 2021-11-07 at 5 56 42 PM" src="https://user-images.githubusercontent.com/55930078/140672727-99ef271b-7a6b-457d-a547-d3ba1f9574a2.png">

**Desktop (please complete the following information):**
 - macOS Monterey
 - iterm2 
 -  0.5.1 
 
**Additional context**
This also happened on Ubuntu earlier when I updated and ran PackerSync. 
I am pretty sure this is caused by or related to #584

**Comment by siduck** [comment]
weird , this shouldnt be happening. Is packercompile working?

**Comment by peppapig450** [comment]
yeah it is

**Comment by peppapig450** [comment]
I think autopairs still works too, it is weird

**Comment by hunger** [comment]
This has been fixed for me for a while now.

**Comment by imadjamil** [comment]
I have an issue that may be related, when I try to start telescope (<leader+f+f>) the following error shows:
![image](https://user-images.githubusercontent.com/6026260/142413440-507db52c-267e-4b5a-97f9-7ba78b748acb.png)

**Comment by siduck** [comment]
> I have an issue that may be related, when I try to start telescope (<leader+f+f>) the following error shows: ![image](https://user-images.githubusercontent.com/6026260/142413440-507db52c-267e-4b5a-97f9-7ba78b748acb.png)

is your config up to date? also are you using nvim 0.5.1 ?

**Comment by imadjamil** [comment]
Yes my config is up to date as far as I know, is there something specific that I can check?
I am running a fork that includes all my custom settings:
https://github.com/imadjamil/NvChad.git

NVIM 0.6.0
![image](https://user-images.githubusercontent.com/6026260/142434319-854898ef-95a7-42e4-9a39-1efbefc94df2.png)

PS: The error message shows only the first time I use telescope after starting vim, no message is shown later.

Thanks

**Comment by siduck** [comment]
> @siduck
> 
> Yes my config is up to date as far as I know, is there something specific that I can check? I am running a fork that includes all my custom settings: https://github.com/imadjamil/NvChad.git
> 
> NVIM 0.6.0 ![image](https://user-images.githubusercontent.com/6026260/142434319-854898ef-95a7-42e4-9a39-1efbefc94df2.png)
> 
> PS: The error message shows only the first time I use telescope after starting vim, no message is shown later.
> 
> Thanks

could you check the issue with vanilla nvchad? like without any changes

**Comment by peppapig450** [comment]
Do autopairs still work?

**Comment by siduck** [comment]
> Do autopairs still work?

yes , Im not able to reproduce this issue.

**Comment by peppapig450** [comment]
It happened to me randomly, I haven't seen it since and even when it did happen I think auto pairs still worked fine.

**Comment by siduck** [comment]
> It happened to me randomly, I haven't seen it since and even when it did happen I think auto pairs still worked fine.

hmm so this doesnt happen now right?

**Comment by peppapig450** [comment]
No it happened once for me

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/142563903-145674b2-7d28-44e3-962e-4975f8cede3a.mp4

doesnt occur with me

**Comment by imadjamil** [comment]
@siduck It seems that PackerSync resolved my issue !

However, after this sync I got a problem with null-ls that is not able to load cppcheck for some reason ...
![image](https://user-images.githubusercontent.com/6026260/142596143-ce0bf82d-a833-4f28-ab77-e662d44d6cf4.png)
