### ISSUE TITLE
Basically unusable on URxvt

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#598]
**Describe the bug**
I can't type stuff properly on urxvt

**To Reproduce**
1. Use URxvt 
2. open neovim
3. type

**Expected behavior**
To be able to type

**Screenshots**

https://user-images.githubusercontent.com/55930078/141149316-21cc985d-d5dd-4838-8eb5-4896114bbf3e.mp4

**Desktop (please complete the following information):**
 - Arch Linux
 - URxvt
 - v0.6.0-dev+566-g4174244d8

**Comment by siduck** [comment]
doesnt occur with me . I tried vanilla rxvt

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/141150791-d39cf525-7c0c-4552-93ba-0e2235d94773.mp4

**Comment by peppapig450** [comment]
okay its probably my xresources then

**Comment by peppapig450** [comment]
This also happens too 
![image](https://user-images.githubusercontent.com/55930078/141154314-befd6f13-72f4-4d66-aae7-7b1f304d8bc5.png)

**Comment by peppapig450** [comment]
I am gonna assume this has something to do with the title or buffer name right?

**Comment by siduck** [comment]
> I am gonna assume this has something to do with the title or buffer name right?

whats the issue? I dont get it

**Comment by siduck** [comment]
Btw I would suggest using my st build

**Comment by peppapig450** [comment]
I am prolly gonna use st just wanted to try rxvt

**Comment by peppapig450** [comment]
The issue is that like whenever I type that text comes up and it likes blocks the typing idk its super weird

**Comment by siduck** [comment]
Can you try using nvim --clean? Lemme know if you can type

**Comment by peppapig450** [comment]
yeah

**Comment by peppapig450** [comment]
Another thing when I open it it seems like the whole thing is highlighted
but im using st now so It isn't that big of a deal
