### ISSUE TITLE
Alacritty padding breaks bottom bar, theme changer not working properly.

### ISSUE THREAD

**Issue by gpxorg** [NvChad/NvChad#599]
### FIRST BUG

**Describe the bug**
I have found two different issues with nvchad. Before anything, I must say that I've been using the older config for most of the time and it is until recently that I updated to the newer one which made things even more confusing and buggy. Issue N1 being the bottom bar(above the command line). Upon changing the padding of the terminal, the bottom bar was screwed up. Even after noticing this, I changed the padding of the terminal back to 0, but the issue remained. I changed the theme to a light one so you can see it clearly

**To Reproduce issue N1**
Steps to reproduce the behavior of first issue:
1. Use Alacritty and go in alacritty.yml
2. Set window padding to x = 25 and y = 25 each
3. Restart
4. Open neovim and check the bottom bar

**Expected behavior**
Wasn't expecting to get this look. It's weird.

**Screenshots**
[Bug 1](https://i.imgur.com/XaLnigC.png)

**Desktop (please complete the following information):**
 - os Arch Linux
 - term Alacritty 
 - nvim version 0.5.1

### SECOND BUG

**Describe the bug**
The second bug being the theme changer. Sure, I changed the theme for the issue above, but once I restart nvim, the theme switches back to the original one. Not only that, at first, when I tried changing the theme of the editor, I'd select the theme from the menu (space t + h), and type "y" to confirm my selection. I was greeted with an error and I couldn't use the editor from that point on unless I restarted it. After that. I tried doing the same thing but this time I pressed the ENTER key to confirm my selection. No error this time, but the theme wouldn't remain. It would revert back to the original one after restarting.

**To Reproduce issue N2**
Steps to reproduce the behavior of second issue:
1. Open theme changer (SPACE + t + h)
2. Select theme and confirm selection by typing "y" or pressing ENTER
3. Try to use the editor or restart to find that the theme has not changed

**Expected behavior**
Was expecting to change my theme without any issues. 

**Screenshots**
[Error by typing "y" to confirm selection](https://i.imgur.com/MkhjscO.png)
[Red mark showing that the search bar from the editor remains after selection, editor becomes unusable after typing "y"](https://i.imgur.com/osGHigz.png)
**Desktop (please complete the following information):**
 - os Arch Linux
 - term Alacritty 
 - nvim version 0.5.1

EXTRA QUESTION: How can I change theme colors like I used to? I couldn't find any relevant files. There used to be different files for each theme and for its colors.

**Comment by siduck** [comment]
use a proper nerd font in alacritty

**Comment by siduck** [comment]
read the docs to know well about nvchad config

**Comment by siduck** [comment]
https://nvchad.github.io/config/walkthrough#colors
