### ISSUE TITLE
Toggle Theme

### ISSUE THREAD

**Issue by m3hdi404** [NvChad/NvChad#600]
When i'm trying to change Nvchad theme by SPACE+t+h, i got this error message:
![image](https://user-images.githubusercontent.com/74054557/141465012-feb43ff5-3166-4a04-873c-ef3bc507e0c3.png)

I'm using nvim latest version by Fedora repository and i also tried to reinstall Nvchad and Nvim multipe times.

Is there any fix for this?

**Comment by siduck** [comment]
add chadrc file in custom dir ,  copy stuffs relevant from the example_chadrc file. Also please read the docs :/

**Comment by m3hdi404** [comment]
Thanks bro it fixed and sorry for not reading the docs :(

**Comment by siduck** [comment]
> Thanks bro it fixed and sorry for not reading the docs :(

no worries , check the config section order wise and it also links to a basic beginner friendly lua tutorial in (setup/learn lua section) . Take your time :)

**Comment by swaroop18122002** [comment]
Hi I got some similar kind of error 
can I get some help with it 
I've also copy pasted the two file `chadrc.lua` and `init.lua` 
But it's still showing me some error

This is the error message I am getting 
 
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/p
acker/opt/packer.nvim/lua/packer/load.lua:83: Vim(lua):E5108: Error executing lua ...im/site/pack/packer/start/extensions/lua/nvchad/init.lua:74: module 'nvchad.reload_con
fig' not foun

![Screenshot_20211115_141651](https://user-images.githubusercontent.com/72123851/141751587-223f231e-95ad-4f2c-93a3-8ba7b8e05a71.png)
![Screenshot_20211115_141754](https://user-images.githubusercontent.com/72123851/141751590-e08d62db-6bca-4c91-84eb-44b2f106a96c.png)
d:

**Comment by siduck** [comment]
@swaroop18122002 do packersync reopen

**Comment by swaroop18122002** [comment]
> @swaroop18122002 do packersync , reopen nvim

Thanks for your response it's working all fine now
I just read what this command does 
It loads `opt` plugin 
thanks again ✌🏻

**Comment by siduck** [comment]
> > @swaroop18122002 do packersync , reopen nvim
> 
> Thanks for your response it's working all fine now I just read what this command does It loads `opt` plugin thanks again ✌🏻

that plugin syncs all defined plugins i.e if they're not installed but defined in config , it installs them, updates them and then compiles the config at last.
