### ISSUE TITLE
Not an order from the editor. Telescope.

### ISSUE THREAD

**Issue by MMAGANADEBIA** [NvChad/NvChad#601]
**Describe the bug**
Today I did `<leader> + uu` and packer sync and get some problems.
When I try to use the Telescope plugin, nvim throw a error that says Telescope "marks",  "find_files", "oldfiles" (and other telescope functions) is not an order from the editor.

**To Reproduce**
1. Install or `<leader> + uu.`
2. PackerSync.
3. Use some telescope function.

**Screenshots**
Error (some words are in Spanish because it is my native language):
![telescope-bug](https://user-images.githubusercontent.com/42789411/141723127-116f02ba-b573-4a9f-b645-1381e1da5b78.png)

Block of code that contains the line of the error thrown (positioned on the marked line):
![image](https://user-images.githubusercontent.com/42789411/141723371-7e245580-2c1e-4de3-8c24-518eb1c19e37.png)

**Desktop (please complete the following information):**
 - Operating System: Parrot OS.
 - Terminal: Alacritty.
 - Version of Neovim: v0.5.0

**Additional context**
Before today, nvchad was working fine, until I update with `<leader> + uu` and do PackerSync, then telescope stop working throwing the error.
I tried reinstalling all, but the problem don't go.

**Comment by siduck** [comment]
can u try 0.5.1? ig that was mentioned in the docs

**Comment by MMAGANADEBIA** [comment]
Yes, it worked, thank you very much!
I did not think there could be a problem because moments before I had no problem, but maybe it was because I had a lot without updating, but it is good to know that it can actually cause problems.
