### ISSUE TITLE
Help testing the dev branch!

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#602]
Lots of cleaning has been done lately so I would want you to report errors if you face any , switch to the dev branch first.

Go to chadrc , add the branch url 

![image](https://user-images.githubusercontent.com/59060246/141828778-650796d1-8bae-43cb-bb15-547a9a034924.png)

ok now do packersync and then space uu 

Then remove these lines from chadrc 

![image](https://user-images.githubusercontent.com/59060246/141825416-7869fc59-900b-4f6e-b868-993b58adb23e.png)

reopen nvim

**Comment by peppapig450** [comment]
If you need me to help test anything else just @ me, I can do it if im not at school

**Comment by siduck** [comment]
cool! Nvm this issue, I'll test it myself on both of my machines and phone :sunglasses:

**Comment by abalmos** [comment]
For what it's worth, I tried dev and had issues. Didn't have time to debug so I just switched back. I have a hunch it was a poor merge job on some changes I made to lspconfig that moved to new files in `dev`

**Comment by siduck** [comment]
> For what it's worth, I tried dev and had issues. Didn't have time to debug so I just switched back. I have a hunch it was a poor merge job on some changes I made to lspconfig that moved to new files in `dev`

hmm you can see the commit history , lots of stuffs have been cleaned and made easier . I'll mention them in the docs once its stable.

**Comment by siduck** [comment]
Also I would suggest just having a custom dir rather than maintaing your own fork and merging / fixing merge conflicts which lead to potential errors.

**Comment by siduck** [comment]
my custom folder 

https://github.com/siduck/dotfiles/tree/master/nvim
