### ISSUE TITLE
Cursor bugging when using auto-completion.

### ISSUE THREAD

**Issue by dmaizel** [NvChad/NvChad#603]
Cursor bugging when using autocompletion. Also odd behavior of the tab key.

https://user-images.githubusercontent.com/12670492/142177868-0a0ef8f7-e9a6-4ebc-b15d-83e180d4ec9d.mp4

..

**Comment by siduck** [comment]
is that termux or alacritty?

**Comment by dmaizel** [comment]
> is that alacritty?

zsh

**Comment by siduck** [comment]
i mean which terminal is this

**Comment by dmaizel** [comment]
> i mean which terminal is this

The Z shell (Zsh)

**Comment by siduck** [comment]
isnt zsh a shell?

**Comment by dmaizel** [comment]
I'm using the default linux terminal (Gnome)

**Comment by siduck** [comment]
May I know how old is your config?

**Comment by siduck** [comment]
hmm so this issue occurs everytime you type?

**Comment by dmaizel** [comment]
Yep

**Comment by siduck** [comment]
which lsp is that? also does the same thing happen in other terminals?

you could try my st build https://github.com/siduck/st

**Comment by 21eleven** [comment]
I have this issue in alacritty and kitty. Happens often but not always on lines with lsp virtual text. Seen it happen with pyright and rust_analyzer.

**Comment by 21eleven** [comment]
I tried using https://github.com/siduck/st however when I run it I get
```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  917
  Current serial number in output stream:  954
```
I am using swaywm/wayland not a WM that uses X11.

**Comment by siduck** [comment]
> I tried using https://github.com/siduck/st however when I run it I get
> 
> ```
> X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
>   Major opcode of failed request:  139 (RENDER)
>   Minor opcode of failed request:  20 (RenderAddGlyphs)
>   Serial number of failed request:  917
>   Current serial number in output stream:  954
> ```
> 
> I am using swaywm/wayland not a WM that uses X11.

oh then it wont work , its for xorg only

**Comment by siduck** [comment]
for wayland I would suggest foot terminal

**Comment by abalmos** [comment]
I also have this problem with neovim `master` (which is probably about a month old now). There is an issue on neovim/neovim about it, but I couldn't turn it up with a quick search. I believe that a recent PR merge *may have* fixed the problem, but I have not found the time to test yet.

The bug is related to virtual text and adjusting the `spacing` option. 

I commented NvChad's defaults in `lua/plugins/configs/lspconfig.lua` like this:

```lua
local lsp_publish_diagnostics_options = overrides.get("publish_diagnostics", {
   virtual_text = {
      -- prefix = "",
      -- spacing = 0,
   },
   signs = true,
   underline = true,
   update_in_insert = false, -- update diagnostics insert mode
})
```

And have not seen the issue again (alacritty or not). I don't *think* you need to comment `prefix`, I just find the red box to be noisy.

**Comment by abalmos** [comment]
Can confirm that `master` (as of a few minutes ago) still exhibits this issue. `prefix` is fine, but supplying `spacing` is not.

**Comment by tydra-wang** [comment]
what's your neovim version?

**Comment by siduck** [comment]
@abalmos does this occur with 0.5.1?

**Comment by abalmos** [comment]
> what's your neovim version? make sure you are using neovim v0.5.1!

Not an option for me. NvChad works great on neovim `master`, sans this issue and some trivial renaming of `LspDiagnostics*` (which really only breaks diagnostic symbols)

> @abalmos does this occur with 0.5.1?

I'm not sure, I have not used the 0.5 line in a while; However, given it is not widely reported here, I assume it does not.

**Comment by siduck** [comment]
@dmaizel use 0.5.1 v

**Comment by omida86** [comment]
For me this happens when I use diagnostics with null-ls. It's a null-ls bug.

**Comment by siduck** [comment]
> For me this happens when I use diagnostics with null-ls. It's a null-ls bug.

does this occur after removing null-ls

**Comment by omida86** [comment]
> > For me this happens when I use diagnostics with null-ls. It's a null-ls bug.
> 
> does this occur after removing null-ls

No. Doesn't happen if I turn off diagnostics in null-ls either. Also it only happens when that line has an error. So if null-ls eslint detects an error on that line, every input gets messed up.

I just switched to the nvim lsp eslint and it solved my issues.

**Comment by siduck** [comment]
> > > For me this happens when I use diagnostics with null-ls. It's a null-ls bug.
> > 
> > 
> > does this occur after removing null-ls
> 
> No. Doesn't happen if I turn off diagnostics in null-ls either. Also it only happens when that line has an error. So if null-ls eslint detects an error on that line, every input gets messed up.
> 
> I just switched to the nvim lsp eslint and it solved my issues.

it would be great if you reported this error into null-ls repo!

**Comment by evikser** [comment]
> I also have this problem with neovim `master` (which is probably about a month old now). There is an issue on neovim/neovim about it, but I couldn't turn it up with a quick search. I believe that a recent PR merge _may have_ fixed the problem, but I have not found the time to test yet.
> 
> The bug is related to virtual text and adjusting the `spacing` option.
> 
> I commented NvChad's defaults in `lua/plugins/configs/lspconfig.lua` like this:
> 
> ```lua
> local lsp_publish_diagnostics_options = overrides.get("publish_diagnostics", {
>    virtual_text = {
>       -- prefix = "",
>       -- spacing = 0,
>    },
>    signs = true,
>    underline = true,
>    update_in_insert = false, -- update diagnostics insert mode
> })
> ```
> 
> And have not seen the issue again (alacritty or not). I don't _think_ you need to comment `prefix`, I just find the red box to be noisy.

Looks like this defaults located it `lua/plugins/configs/others.lua` at this moment

```lua
vim.diagnostic.config {
   virtual_text = {
      prefix = "",
      -- spacing = 0,
   },
   signs = true,
   underline = true,
   update_in_insert = false,
}
```

**Comment by omida86** [comment]
True, after removing spacing 0 null-ls eslint works for me too.

**Comment by siduck** [comment]
i have made this change globally, thx for reporting the fix guys :)
