### ISSUE TITLE
Add a new runtimepath entry in the custom folder

### ISSUE THREAD

**Issue by mtarld** [NvChad/NvChad#605]
Hi!
First of all, thank you very much for NvChad, I'm currently quitting Emacs (+evil mode) to switch to neovim and it saves me a lot of time :slightly_smiling_face: 

**Is your feature request related to a problem? Please describe.**
Actually, there is an issue in vim/neovim about auto-indentation for PHP files. And there is a workaround described [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/462#issuecomment-700278736).
The main idea is to create a `php.vim` that is loading after the PHP official indent plugin containing the following:
```vim
setlocal indentexpr =
setlocal autoindent
setlocal smartindent
setlocal shiftwidth=4
```
To make it work I had to put that file in `~/.config/nvim/after/indent/php.vim`.
And here is the issue. As that file is not in the `custom` folder, it'll be overridden as soon as will update NvChad.

**Describe the solution you'd like**
A solution could be to add a new runtime path in the custom folder so that it won't be overridden I guess. But maybe I'm missing an easier approach.

Thanks in advance!

**Comment by siduck** [comment]
hmm Idk how this works! Btw does putting that change in custom/init.lua not work?

**Comment by siduck** [comment]
@mtarld we dont have any after dir in our lua/ dir , so even if you add after dir it wont get affected. One thing we could do is gitignore lua/after dir.

**Comment by Akianonymus** [comment]
@mtarld To add a runtimepath, use below code:
```
vim.opt.rtp:append(vim.fn.stdpath "config" .. "/lua/custom/after")
```
You can add this in custom/init.lua

This will add `~/.config/nvim/lua/custom/after` to runtimepath, then add your php.vim to custom/after folder. Try and report.

**Comment by siduck** [comment]
since the solution above is provided , I'll be closing this. @mtarld if the issue still persists then feel free to reopen this

**Comment by mtarld** [comment]
Hi! Sorry for the late response (I've been quite overwhelmed these days).
That indeed worked like a charm, many thanks @Akianonymus and @siduck
