### ISSUE TITLE
Making Y behave like other capital letters

### ISSUE THREAD

**Issue by horta** [NvChad/NvChad#608]
I use the following mapping

```
-- Behave like other capitals
map("n", "Y", "yg$", opts)
```

to make `Y` yank from the cursor position to the end-of-line (not including newline character).

I took it from here: https://github.com/ThePrimeagen/.dotfiles/blob/874636dad3cbcad6ca96982047025181684993f2/nvim/.config/nvim/init.vim#L141

**Comment by siduck** [comment]
done!
