### ISSUE TITLE
Keep cursor centered when moving to 

### ISSUE THREAD

**Issue by horta** [NvChad/NvChad#609]
When you goto a definition, for example, sometimes the cursor is at the last line of the screen, which I find odd since I want that line to be highlighted. The following mappings

```
-- Keep it centered
map("n", "n", "nzzzv", opts)
map("n", "N", "Nzzzv", opts)
```

took from https://github.com/ThePrimeagen/.dotfiles/blob/874636dad3cbcad6ca96982047025181684993f2/nvim/.config/nvim/init.vim#L142

makes sure that the line is centered in the screen.

**Comment by siduck** [comment]
@horta could you show a demo (vid) of this?

**Comment by horta** [comment]
I wrote rubbish, sorry. Those remapping try to keep the cursor centred while we are doing next on the search.

I guess those mappings might be controversial for some people as well, so please close it if you wish.

**Comment by siduck** [comment]
> I wrote rubbish, sorry. Those remapping try to keep the cursor centred while we are doing next on the search.
> 
> I guess those mappings might be controversial for some people as well, so please close it if you wish.

hmm Ig so!  btw if you could show a recording of the behaviour then i'd consider checking about this

**Comment by siduck** [comment]
nvm it , anyways you can add the mappings yourself .

```
local hooks = require "core.hooks"

hooks.add("setup_mappings", function(map)
   map("n", "n", "nzzzv")
   map("n", "N", "Nzzzv")
end)

```

**Comment by horta** [comment]
https://user-images.githubusercontent.com/514522/143290158-351ba2f7-8beb-43cd-8a48-12759b64c35b.mov

**Comment by horta** [comment]
I'm in doubt now whether I prefer the centering way...

**Comment by horta** [comment]
Also, don't you find hard to know which word the cursor is currently on while searching? The above video shows that. Find quite hard...
