### ISSUE TITLE
add which-key.nvim (or any keybinding cheatsheet)

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [NvChad/NvChad#610]
**Is your feature request related to a problem? Please describe.**
There are many custom keybindings defined and used in NvChad, and often require sifting through documentation to figure out the keybinding for a specific task.

**Describe the solution you'd like**
Make use of plugins such as [which-key.nvim](https://github.com/folke/which-key.nvim) to aid in keybinding reference and provide descriptions of the keybindings, not just the command the keybinding will run.

**Describe alternatives you've considered**
Considered using the cheatsheet (\<leader\>dk).

**Screenshot**
Something like this, but with custom descriptions of each keybinding.
![image](https://user-images.githubusercontent.com/79387351/142862192-8885ce65-5362-4e89-beb3-faddf6b65567.png)

**Comment by siduck** [comment]
@max397574 is working on it.

**Comment by peppapig450** [comment]
https://github.com/NvChad/extensions/issues/5

**Comment by bdwiel** [comment]
I would also like to see which-key.nvim used. The cheatsheet requires first searching for the mapping and then closing the cheatsheet. Searching by mapping requires typing out something like "/leader>" plus some letters of the mapping. For example, searching for telescope mappings is "/leader>f" but in which-key it's just " f".

**Comment by siduck** [comment]
> I would also like to see which-key.nvim used. The cheatsheet requires first searching for the mapping and then closing the cheatsheet. Searching by mapping requires typing out something like "/leader>" plus some letters of the mapping. For example, searching for telescope mappings is "/leader>f" but in which-key it's just " f".

you can add whichkey yourself tho

**Comment by bdwiel** [comment]
> you can add whichkey yourself tho

Totally. It's just the descriptions are missing from whichkey then so all mappings have to be called again to include the descriptions.

**Comment by parker-upstart** [comment]
I bump this as well, could we get and update on the progress @max397574 @siduck ?

**Comment by max397574** [comment]
if you expect users to use that you should add descriptions to mappings @siduck

**Comment by parker-upstart** [comment]
Yea, the lack of descriptions makes `:Telescope kepmaps` fairly unusable.. unless of course I'm not using it to its fullest potential. I think end game I'll either have to manually create my own which key support, or I'll just wait until it's robust within NvChad itself.

**Comment by siduck** [comment]
btw you can still add whichkey yourself, however it would be still basic tho as you wouldnt be able to register the mappings

**Comment by parker-upstart** [comment]
Yeah, I've done that but it'd be nice to have a full description of everything built within whichkey. Is there any timeline for when the full implementation of whichkey within NvChad itself will be complete?

**Comment by parker-upstart** [comment]
Oh cool, thanks @siduck !

**Comment by AlexanderHOtt** [comment]
Any update on this? The telescope picker shows <anonymous> for a lot of the keybindings so built-in whichkey would be nice.

**Comment by siduck** [comment]
> Any update on this? The telescope picker shows for a lot of the keybindings so built-in whichkey would be nice.

@parker-upstart  @AlexanderHOtt its added check recent commit regarding breaking change

**Comment by siduck** [comment]
@g-e-o-m-e-t-r-i-c ik this might be tooo late lol
