### ISSUE TITLE
Missing symbol for Telescope plugin prefix

### ISSUE THREAD

**Issue by DrJackilD** [NvChad/NvChad#612]
**Describe the bug**
When I opening telescope pop-up (e.g. for buffer search), prefix are looks like a question mark symbol. From the screenshots of other users I realize, that magnifier glass should be there, but probably my font is nit supported this. Which font do I need to use to have this symbol?

**Screenshots**
![Screenshot 2021-11-26 at 11 58 27](https://user-images.githubusercontent.com/1544738/143563578-21d64be5-428a-485e-b16a-d7a4caaaf84f.png)

![Screenshot 2021-11-26 at 11 58 15](https://user-images.githubusercontent.com/1544738/143563601-d3afc99f-8c85-407a-8207-e7c73f2e623d.png)

**Desktop (please complete the following information):**
 - Mac OS 11.6
 - iTerm 2

Nvim info
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/config -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/src -I/usr/local/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck** [comment]
Any nerdfont will do  , I use jetbrainsmono nerd font.

**Comment by DrJackilD** [comment]
@siduck I've tried JetBrains Mono Nerd Font - no luck, still got the ? mark

**Comment by DrJackilD** [comment]
For more information - looks like VS Code show this symbol ok. Maybe iTerm2 bug?

### Symbol in the VS Code (with JetBrains Mono) 
![Screenshot 2021-11-27 at 01 15 55](https://user-images.githubusercontent.com/1544738/143660649-920b87e3-a219-4755-990c-74469dc7ac8a.png)

### Symbol in Nvim (with JetBrains Mono in terminal)
![Screenshot 2021-11-27 at 01 16 31](https://user-images.githubusercontent.com/1544738/143660676-ba80768b-a37d-4723-ab3f-8e3187eeb182.png)

**Comment by DrJackilD** [comment]
Yep, definitely iTerm2 problems, but I'm not sure what's exactly cause the troubles. Here is I open Nvim in VS Code internal terminal - symbol is rendered correctly.
![Screenshot 2021-11-27 at 01 22 30](https://user-images.githubusercontent.com/1544738/143660850-a41c5cee-c9ce-4906-af90-6a5092182ea5.png)

**Comment by siduck** [comment]
> Yep, definitely iTerm2 problems, but I'm not sure what's exactly cause the troubles. Here is I open Nvim in VS Code internal terminal - symbol is rendered correctly. ![Screenshot 2021-11-27 at 01 22 30](https://user-images.githubusercontent.com/1544738/143660850-a41c5cee-c9ce-4906-af90-6a5092182ea5.png)

try alacritty or kitty

**Comment by peppapig450** [comment]
it works on kitty

**Comment by DrJackilD** [comment]
Yep, works fine in `alacritty`. Thank you for your help guys!

**Comment by peppapig450** [comment]
I found a solution or a workaround technically you can change it from the font awesome glyph to this  (unicode point is f422) explanation why it doesnt work is here https://gitlab.com/gnachman/iterm2/-/issues/7570#note_147643096

**Comment by DrJackilD** [comment]
Great, thank you! @peppapig450 @siduck do you guys think it worth to change this symbol in the Nvchad itself, as a workaround, to make it work seamlessly on iTerm2?

**Comment by siduck** [comment]
#

> Great, thank you! @peppapig450 @siduck do you guys think it worth to change this symbol in the Nvchad itself, as a workaround, to make it work seamlessly on iTerm2?

For now you can just override the telescope config , I'll add a chadrc option for this later.

**Comment by ashtonfei** [comment]
I changed the icon with an alternative search icon, it works now.

https://www.nerdfonts.com/cheat-sheet
nf-oct-search

<img width="191" alt="image" src="https://user-images.githubusercontent.com/16481229/202910932-f1a7c195-05ea-49f5-97aa-5c2511436238.png">

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/16481229/202910806-a65404ed-dfd5-482c-9e13-899f1a7343e1.png">
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/16481229/202910980-e533a940-73d2-4076-a5ba-5384b152cb14.png">
