### ISSUE TITLE
lspconfig attemp to call field 'setup' (a nil value)

### ISSUE THREAD

**Issue by SleepyCatOnTheBed** [NvChad/NvChad#616]
I tried to update my plugins with Packer Update, and after that received this error. I have already reinstalled as usual, and Packer Sync, but still receive this. May I also ask for the cause of this issue ?

![image](https://user-images.githubusercontent.com/71932200/143677214-26c47275-d348-4419-a6d3-1102c11579de.png)

My system:
- Ubuntu 20.04
- NVIM 0.5.1

Thank you.

**Comment by siduck** [comment]
when was the last tiimme you updated nvchad?

**Comment by SleepyCatOnTheBed** [comment]
I don't think I have updated nvchad recently, I used the old config of the NvChad v1.0 since it was stable for me.

**Comment by siduck** [comment]
> I don't think I have updated nvchad recently, I used the old config of the NvChad v1.0 since it was stable for me.

oh rip , update to the master config!

**Comment by siduck** [comment]
many things have changed since then , check our docs

**Comment by SleepyCatOnTheBed** [comment]
Oh dear, a lot of things have been changed. I will close the issues now and check the docs. Thank you.
