### ISSUE TITLE
Include the `stabilize` plugin so current line placement doesn't jump around on quickfix/splits...

### ISSUE THREAD

**Issue by erwin** [NvChad/NvChad#617]
**Is your feature request related to a problem? Please describe.**
Using Neovim/Vim by default, when you do splits `:sp` or open the quickfix list `:cope`, the location of your current line in the window jumps around.

**Describe the solution you'd like**
The [stabilize.nvim plugin](https://github.com/luukvbaal/stabilize.nvim) prevents `:sp`, `:cope`, `:ccl` type operations from causing the window to jump around.

**Describe alternatives you've considered**
The default NvChad behavior works fine. I just think that in terms of making NeoVim more of a IDE experience, this default line jumpiness of Vim would be better replaced with `Stabilize` - see the animated GIF below...

Of course individual NvChad users can add this themselves, I just think this could be a generally useful add-on in the quest to make NvChad an ideal IDE. Whether it would be more bloat, only you can decide :-)

**Additional context**
If something like this can't be added, maybe a documentation section on "plugins that NvChad users might be interested in"?

**Screenshot** (Vim/Neovim's default "jumpiness" vs stabilize enabled)
![image](https://camo.githubusercontent.com/1f3e694e1dce2dcc48f679ad8675d8fa678e2db065e796268ed1a3de1b2f73f4/68747470733a2f2f692e696d6775722e636f6d2f547675347856522e676966)

**Comment by siduck** [comment]
Could you show the behaviour with/without this plugin?

**Comment by abalmos** [comment]
@siduck the gif is the with/without behavior.

I'm only commenting because I also enjoy and use this plugin.

**Comment by erwin** [comment]
The animated gif above does show the behavior with/without "stabilize", but it's very subtle.

These screenshots hopefully highlight the difference.
Let's stay we start by looking at `hooks.lua`.
![image](https://user-images.githubusercontent.com/11534217/143768764-87eba075-eb8a-4224-88db-b394c1f93896.png)

Now we run `lua vim.lsp.buf.references()` to see the references in the quickfix window.

By default, the window will now JUMP... 
1. The first line in the window is now `line 5`, 
2. Visual placement of `line 8` in the window has jumped several lines...
This is the default vim/neovim behavior.

![image](https://user-images.githubusercontent.com/11534217/143769244-14dbd864-3199-49af-9e50-4d5d6c56efca.png)

When using `:split` or any other widget that changes the window size, we get line movement that you wouldn't get on any other IDE. When we close the `quickfix` window with `:ccl` the window jumps again.

# With `stabilize` enabled, the window jumpiness is gone:

1. The first line is STILL `line 1`.
2. The placement of `line 8` relative to the total window size has not moved.

![image](https://user-images.githubusercontent.com/11534217/143769397-af11ff67-f20c-4432-b28e-875997925d92.png)

# Stabilize Enabled...  Beautiful... 🦚

![image](https://user-images.githubusercontent.com/11534217/143768784-10cc2414-0c75-4b5a-8894-0e191284a889.png)

**Comment by siduck** [comment]
> @siduck the gif is the with/without behavior.
> 
> I'm only commenting because I also enjoy and use this plugin.

oh lul sorry I forgot to check it.

**Comment by peppapig450** [comment]
we could add it here https://nvchad.github.io/Extras

**Comment by siduck** [comment]
> we could add it here https://nvchad.github.io/Extras

agreed!

**Comment by siduck** [comment]
> we could add it here https://nvchad.github.io/Extras

done https://nvchad.github.io/Extras#stabilizenvim
