### ISSUE TITLE
add an option to lazyload/not lazy load nvimtree

### ISSUE THREAD

**Issue by hunger** [NvChad/NvChad#621]
When I use an unconfigured nvim, then opening `nvim .` will great me with a view of the files in the current directory. This is not the case in NVchad.

I read up on `nvimtree`, the plugin you use to replace `netrw` with. From what I understand that should enable some file listing by default?

**To Reproduce**
1. Run `nvim .` from a terminal

**Expected behavior**
The directory contents is displayed either in the main buffer or at least the file tree opens.

Instead an empty window is opened.

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal: Kitty
 - Version of Neovim: 0.6, but was the same with 0.5

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/144255341-e691d091-8510-41bc-85a9-8dd5c1bfa8df.mp4

**Comment by siduck** [comment]
it should work.

**Comment by siduck** [comment]
@hunger we have lazyloaded nvimtree so it nvim . wont work by default like netrw stuff. I'll add an option to add this behaviour.

**Comment by hunger** [comment]
@siduck: I would love to have way less stuff lazy-loaded in my setup!

Yes, that is great idea, but I had e.g. Telescope having really strange behavior before when triggered before opening a file and nvim-cmp is a bitch to set up with extra extensions, too.

Maybe you could have a set of basic plugins load on startup by default? nvim-cmp, telescope and nvimtree sound like they will be active pretty much as soon as you do *anything* with NVChad.

**Comment by hunger** [comment]
I removed the `cmd` line from the nvimtree setup code. Now nvimtree is shown on `nvim .`, as expected. But non of the keyboard shortcuts work :-( I must be doing something wrong still.

**Comment by siduck** [comment]
> @siduck: I would love to have way less stuff lazy-loaded in my setup!
> 
> Yes, that is great idea, but I had e.g. Telescope having really strange behavior before when triggered before opening a file and nvim-cmp is a bitch to set up with extra extensions, too.
> 
> Maybe you could have a set of basic plugins load on startup by default? nvim-cmp, telescope and nvimtree sound like they will be active pretty much as soon as you do _anything_ with NVChad.
those are some big plugins! and previously lazy loaded , nvim cmp with its 5+ source plugins was kinda slow so I had to lazy load it. I'll probably add an option not to lazy load these.

**Comment by hunger** [comment]
I know. But I need those *anyway*, so I do pay the price of loading them. I can just postpone the inevitable for a bit ... and work around the breakage that causes.

**Comment by siduck** [comment]
> I know. But I need those _anyway_, so I do pay the price of loading them. I can just postpone the inevitable for a bit ... and work around the breakage that causes.

not lazyloading nvimtree does have some usecases but what about cmp?

**Comment by hunger** [comment]
I wanteds to set up extra cmp completions and found it hard to due due to lazy loading.

I did manage in the end by ordering the loading of modules in Packer, so that is not pressing for me:-)

IMHO most of the lazy loading is just cosmetics in NVchad: The plugins do not get loaded when vim starts, but when I open the first file -- which is about 95% of the time right after vim is up for me. And if I go for the 5% I notice subtle breakages like nvimtree not working even though it should. Or Telescope not supporting all the extension it does have available when doing `nvim file.txt`. So I am not a big fan of lazy loading:-)

**Comment by G-Rowell** [comment]
Would agree that we don't need to lazy load 100% of the plugins imo.

As several plugins are light as is, and there should be some consideration as to if a plugin needs to be lazy loaded.
Especially as we have had a good share of bugs/issues and workarounds due to excessive lazy loading

I think NvimTree is a good example of something that is fine to not lazy load.

@siduck What are your thoughts?
If you are strongly against this then I'll start working on a flag to enable / disable lazy loading.


But otherwise I can take a look at the core plugins to load normally (no lazy loading), and if it is appropriate AND doesn't not majorly impact startup time.

**Comment by siduck** [comment]
> I wanted to set up extra `cmp` completion plugins and found it hard to do due to lazy loading. BAsically the naive approach that is documented everywhere does not work. I did manage in the end by ordering the loading of modules in Packer after reading up on that plugin, so that is not pressing for me:-)
> 
> IMHO most of the lazy loading is just cosmetics in NVchad: The plugins do not get loaded when vim starts, but when I open the first file -- which is about 95% of the time right after nvim has fully come up for me (I most of the time do `nvim file.txt`).
> 
> In the remaining 5% (when I start `nvim` without giving a file) I notice subtle breakages like nvimtree not working even though it should. Or Telescope not supporting all the extension it does have available when doing `nvim file.txt`. So I am not a big fan of lazy loading:-)

cmp-path is the last cmp lazy loaded plugin , any other cmp plugin can be loaded after it 

![image](https://user-images.githubusercontent.com/59060246/144985888-8fecd755-3502-43a1-9498-7563c634e808.png)

also cmp loads on insertenter , so even if you open a file with nvim then cmp wont load until you're in the insert mode

**Comment by G-Rowell** [comment]
(though I agree that we need a strong focus on avoiding a sluggish setup)

thoughts?

**Comment by siduck** [comment]
> (though I agree that we need a strong focus on avoiding a sluggish setup)
> 
> thoughts?

there's no sluggish setup , it might be if the user's unaware of lazyloading. startuptime is important on low end machines , without lazy loading it'll be a lil slow. 
![image](https://user-images.githubusercontent.com/59060246/144986331-9eff7336-c6e7-4270-8360-929366883c32.png)


i'll add some docs regarding proper understanding of lazy loading etc.

**Comment by G-Rowell** [comment]
Hmmmm,

do agree with being considerate for people with lower end machines

Would guess that NvimTree would not have a huge impact?
And would solve this bug.


Though would expect a bigger plugin like cmp to of course impact a lot on startup

**Comment by siduck** [comment]
> Hmmmm,
> 
> do agree with being considerate for people with lower end machines
> 
> Would guess that NvimTree would not have a huge impact? And would solve this bug.
> 
> Though would expect a bigger plugin like cmp to of course impact a lot on startup

i will add a flag to enable/disable lazyloading for nvimtree.

**Comment by hunger** [comment]
If you enable all these heavy plugins, they will be loaded and they will take their startup time -- either when nvim starts or a later when the file is opened for the first time or some command is trigger. You will pay the price, you can just select whether you want to pay it directly on nvim start or at some later point in time.

I do notice a delay when opening the first file in NVChad... that is when I pay the price of the convenience of having all these plugins enabled. I personally find that more annoying than a slightly longer delay on start-up.

**Comment by siduck** [comment]
> If you enable all these heavy plugins, they will be loaded and they will take their startup time -- either when nvim starts or a later when the file is opened for the first time or some command is trigger. You will pay the price, you can just select whether you want to pay it directly on nvim start or at some later point in time.
> 
> I do notice a delay when opening the first file in NVChad... that is when I pay the price of the convenience of having all these plugins enabled. I personally find that more annoying than a slightly longer delay on start-up.

opening a file with lazyloaded plugins is still faster than not lazyloaded setup tho 

![image](https://user-images.githubusercontent.com/59060246/145048117-40e35506-caf8-4340-98de-83203d7bcd89.png)

**Comment by mark-ruddy** [comment]
I was having a slightly similar issue: When opening nvim(with NvChad) with nvim-tree set to open on startup, it was opening as an empty buffer in *non-git repos*, strangely enough. By setting "ignore_buffer_on_setup" to true in nvim-tree it opened correctly:

```
-- nvim-tree
require'nvim-tree'.setup {
  open_on_setup = true,
  open_on_setup_file = true,
  ignore_buffer_on_setup = true,
  actions = {
    open_file = {
      resize_window = true,
    },
  },
  view = {
    relativenumber = true,
  },
}
```

This may not fix this specific issue raised by @hunger but its fixed nvim-tree opening on startup for me. I didn't touch the lazy-loading configuration so I'm not sure if nvim-tree is lazy-loaded by default still in NvChad.

**Comment by siduck** [comment]
@hunger ik this is tooooooooooooooooooo late but ye:

```lua
local autocmd = vim.api.nvim_create_autocmd

autocmd("BufEnter", {
   callback = function()
      if vim.api.nvim_buf_get_option(0, "buftype") ~= "terminal" then
         vim.cmd "lcd %:p:h"
      end
   end,
})```
