### ISSUE TITLE
Comment Color should respect the Theme

### ISSUE THREAD

**Issue by typkrft** [NvChad/NvChad#624]
**Is your feature request related to a problem? Please describe.**
Comments are `grey_fg` in `/lua/colors/highlights.lua`, for dracula the correct color is `#6272a4`.  Not only is it true to the theme, but it's a huge improvement in readability in my opinion.

**Describe the solution you'd like**
In dracula `#6272a4` is listed as grey. This could be resolved in a number or ways, the easiest being change `grey_fg` to `grey` but I'm not sure the impact this would have on other themes. We could also add some logic that chooses the comment color based on the theme. I'm not sure if themes have particular maintainers or not.

**Describe alternatives you've considered**
NA

**Additional context**
NA

Current `grey_fg`
**Screenshot**
<img width="971" alt="Screen Shot 2021-12-06 at 1 35 28 AM" src="https://user-images.githubusercontent.com/12100960/144798971-27d5d1d2-b2ab-4fa0-9f6a-4301ddc0d2c8.png">

Theme Correct `grey`
<img width="971" alt="Screen Shot 2021-12-06 at 1 34 44 AM" src="https://user-images.githubusercontent.com/12100960/144798869-ac4f85fc-9797-44bd-9017-e749fa722b0f.png">

**Comment by siduck** [comment]
grey_fg doesnt look that darker here 

![image](https://user-images.githubusercontent.com/59060246/144801839-bc58a943-9f7d-4069-9b98-6c1b022d7522.png)

**Comment by siduck** [comment]
do packersync , i changed some colors 

c

**Comment by typkrft** [comment]
It does certainly look better, and is more readable so goal achieved in that regard. Though my think was just to use the color of theme's designated comments (`#6272A4`). https://spec.draculatheme.com/#sec-Standard 
Regardless thanks!

**Comment by siduck** [comment]
> It does certainly look better, and is more readable so goal achieved in that regard. Though my thinking was just to use the color of theme's designated comments (`#6272A4`). https://spec.draculatheme.com/#sec-Standard Regardless thanks!

the issue's that we cant follow a theme 100% since we have 49~ colors to define and no colorscheme comes with such large number of colors so I try to make the theme better than the original one :p
