### ISSUE TITLE
Consider switching from nvim_comment to comment.nvim?

### ISSUE THREAD

**Issue by erwin** [NvChad/NvChad#626]
**Is your feature request related to a problem? Please describe.**
comment.nvim highlights:

*   [Supports treesitter](https://github.com/numToStr/Comment.nvim#treesitter).
*   [Supports commentstring](https://github.com/numToStr/Comment.nvim#commentstring).
*   Prefers single-line/linewise comments
*   Supports line (`//`) and block (`/* */`) comments
*   Dot (`.`) repeat support for `gcc`, `gbc` and friends
*   Count support (`[count]gcc`)
*   Left-right (`gcw gc$`) and Up-Down (`gc2j` `gc4k`) motions
*   Use with text-objects (`gci{` `gbat`)
*   Supports pre and post hooks
*   Ignore certain lines, powered by Lua regex

See: https://github.com/numToStr/Comment.nvim 

**Describe the solution you'd like**
Consider switching the comment plugin to comment.nvim

**Describe alternatives you've considered**
Of course we can switch this manually in our configs. Just thought this version may be more generally useful. Super irritating to me that many of the vim comment plugins don't do block comments.

**Additional context**

**Screenshot**
https://user-images.githubusercontent.com/42532967/136532939-926a8350-84b7-4e78-b045-fe21b5947388.gif

**Video** with very strange intro...
https://www.youtube.com/watch?v=-InmtHhk2qM

**Comment by siduck** [comment]
does it need any extra plugin? Ive seen there's a separate treesitter commentstring plugin

**Comment by siduck** [comment]
i tried using it but confused about using it, it didnt work for me :/
