### ISSUE TITLE
Avoid duplicating buffer on leader + x

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#629]
https://user-images.githubusercontent.com/59060246/144987746-3fb90cdd-8dc0-4810-9b27-d730411a68d2.mp4

- use :bdelete for deleting the buffer.
or
- leader +x should hide normal buffers and terminal buffers 
- Ctrl q should delete the buffer completely via :bdelete

**Comment by G-Rowell** [comment]
So the idea of the buffer close utility is to keep the window layout when ideal,

though agree that this is an edge case and will fix this

**Comment by siduck** [comment]
> So the idea of the buffer close utility is to keep the window layout when ideal,
> 
> though agree that this is an edge case and will fix this

alright then

**Comment by siduck** [comment]
@G-Rowell nvm :(

**Comment by siduck** [comment]
@zbirenbaum can you check on this when free? we dont need to keep the layout while closing the buffer so just remove the un-needed code in the close_buffer function in the utils.lua

**Comment by zbirenbaum** [comment]
I'm not even sure what the command is supposed to do. That utils code is an absolute mess. Whatever the goal is I need clearly stated. Closing a window is easy, but I have no idea what this function is supposed to do.

**Comment by siduck** [comment]
> I'm not even sure what the command is supposed to do. That utils code is an absolute mess. Whatever the goal is I need clearly stated. Closing a window is easy, but I have no idea what this function is supposed to do. @siduck

The function closes non terminal buffers (kills them ig) and if there's a terminal buffer then it just hides it. But it has extra code for maintaining the layout while closing the buffer and we dont need that! @G-Rowell knows it better

**Comment by zbirenbaum** [comment]
@siduck theres a ton of code related to figuring out which buffer to display instead. I think this should just go tbh. If not even you have any clue what it's doing/supposed to be doing then that's quite literally 114 lines of (extremely dated judging by the hacks used instead of functions now in the api) code bloating up utils that should just be gone.

Use a plugin for it, or have me write a saner version in a week or two when I have time with clear goals, but I personally vote this needs to be gone immediately.

**Comment by siduck** [comment]
@zbirenbaum its not neeeded, Ig only this part is relevant 
![image](https://user-images.githubusercontent.com/59060246/165030521-ab61aeed-1f4d-4232-82d5-9659d2d03d0c.png)
( it needs debloating too)

**Comment by zbirenbaum** [comment]
@siduck Do you just want it to delete a buffer and then close the window when a user calls it?

**Comment by siduck** [comment]
> @siduck Do you just want it to delete a buffer and then close the window when a user calls it?

idk about it xd, just delete the buffer / window , whenever if I have a file or :help any buffer ( non terminal ) opened then it should run :bd

**Comment by siduck** [comment]
Only this part's left, i have finished re-implementing the custom config. Need to update the docs or move to another static site generator :thinking:

**Comment by zbirenbaum** [comment]
wait what do you mean re-implemented custom. If it is staying then shouldn't it be left as is?

**Comment by siduck** [comment]
> wait what do you mean re-implemented custom. If it is staying then shouldn't it be left as is?

the custom config stuff is cleaner than before now, easier as well :imp:

**Comment by zbirenbaum** [comment]
Ok, just gimme a chance to look over it before you merge it pls

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/165031424-2048ec39-5120-4d66-971a-70e44f4e384e.png)

Look, majority of the users there dont want custom config at all and only half of em want the custom config. But 90% of the comments are in favor of the custom config so I gave it a thought that the old config was a lil complex in look unless we look at the docs so many didnt favor the custom config,  So I simplified the config

**Comment by zbirenbaum** [comment]
As was pointed out by many people though, git issue polls have insane selection bias. That's almost certainly not representative of our users as a whole.

**Comment by siduck** [comment]
> As was pointed out by many people though, git issue polls have insane selection bias. That's almost certainly not representative of our users as a whole.

yep, i was able to vote to both the reactions :laughing:
