### ISSUE TITLE
custom theme dir

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#631]
It would be great if we added a custom theme dir path as an option in the chadrc 

something like this : 

![image](https://user-images.githubusercontent.com/59060246/139169176-bf818399-cdab-4798-9805-a271ceda18b6.png)

And the custom folder must have the user's theme folders , which must have 2 folders : 

hl_themes 
themes 

![image](https://user-images.githubusercontent.com/59060246/139169109-3db3554b-9319-49c4-8590-b6d3e64ddf99.png)

- changes must be done in the telescope theme switcher

**Comment by siduck** [comment]
Ive noticed this a lot that I have to intervene and edit themes personally when theme PR's come which makes me think that y'all wouldnt be able to make perfect themes for nvchad! so I dont think this 'custom' local theme feature would be of any use. just send new theme requests , I will make them when free.

**Comment by tahsin-npx** [comment]
Is it possible to use .vim theme files with Nvchad? :/

**Comment by siduck** [comment]
> Is it possible to use .vim theme files with Nvchad? :/

ofc, just source it. 

```
vim.cmd " ~/.config/nvim/lua/custom/siduck.vim"
```

**Comment by tuberry** [comment]
It seems that there only are two ways to use and modify private imperfect themes:
 1) submit the theme to the repository and wait for review,
 2) `so` the theme in the `custom` folder and undo all the redundant parts of the default theme.

IMHO, they aren't that "customizable".

**Comment by siduck** [comment]
1

> It seems that there only are two ways to use and modify private imperfect themes:
> 
> 1. submit the theme to the repository and wait for review,
> 2. `so` the theme in the `custom` folder and undo all the redundant parts of the default theme.
> 
> IMHO, they aren't that "customizable".

1 option is only viable

**Comment by tuberry** [comment]
> 1 option is only viable

They look more like multiple color schemes within the same [theme](https://github.com/NvChad/nvim-base16.lua/blob/master/lua/base16.lua) rather than multiple themes. I would prefer a custom theme rather than customizing a theme.

**Comment by siduck** [comment]
> > 1 option is only viable
> 
> They look more like multiple color schemes within the same [theme](https://github.com/NvChad/nvim-base16.lua/blob/master/lua/base16.lua) rather than multiple themes. I would prefer a custom theme rather than customizing a theme.

wym same theme?

**Comment by tuberry** [comment]
Why not let users set any theme in a more convenient way? i.e.
```diff
diff --git a/lua/colors/init.lua b/lua/colors/init.lua
index 8927251..0390770 100644
--- a/lua/colors/init.lua
+++ b/lua/colors/init.lua
@@ -2,33 +2,42 @@ local M = {}
 
 -- if theme given, load given theme if given, otherwise nvchad_theme
 M.init = function(theme)
-   if not theme then
-      theme = require("core.utils").load_config().ui.theme
-   end
-
-   -- set the global theme, used at various places like theme switcher, highlights
-   vim.g.nvchad_theme = theme
-
-   local present, base16 = pcall(require, "base16")
-
-   if present then
-      -- first load the base16 theme
-      base16(base16.themes(theme), true)
-
+  if not theme then
+    theme = require("core.utils").load_config().ui.theme
+  end
+
+  -- set the global theme, used at various places like theme switcher, highlights
+  vim.g.nvchad_theme = theme
+
+  local present, base16 = pcall(require, "base16")
+  if present then
+    -- first load the base16 theme
+    local ok, array = pcall(base16.themes, theme)
+    if ok then
+      base16(array, true)
       -- unload to force reload
       package.loaded["colors.highlights" or false] = nil
       -- then load the highlights
       require "colors.highlights"
-   end
+    else
+      pcall(vim.cmd, "colo " .. theme)
+    end
+  else
+    pcall(vim.cmd, "colo " .. theme)
+  end
 end
 
 -- returns a table of colors for given or current theme
 M.get = function(theme)
-   if not theme then
+  local colors = require("core.utils").load_config().ui.colors
+  if #colors ~= 0 then
+    return require(colors)
+  else
+    if not theme then
       theme = vim.g.nvchad_theme
-   end
-
-   return require("hl_themes." .. theme)
+    end
+    return require("hl_themes." .. theme)
+  end
 end
 
 return M
diff --git a/lua/core/default_config.lua b/lua/core/default_config.lua
index eb17228..9676a48 100644
--- a/lua/core/default_config.lua
+++ b/lua/core/default_config.lua
@@ -46,6 +46,7 @@ M.options = {
 
 M.ui = {
    hl_override = "", -- path of your file that contains highlights
+   colors = "", -- path of your file that contains colors
    italic_comments = false,
    theme = "onedark", -- default theme

```

**Comment by siduck** [comment]
@tuberry i cant work on nvchad most of the time due to college/exams , if you want this feature then add it as a PR.
