### ISSUE TITLE
random telescope error while theme switching

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#632]
This happens only once and for the first time ( leader th) : 

![image](https://user-images.githubusercontent.com/59060246/135701449-e26b6bc6-0ac9-4c67-897c-54db195265f9.png)

**Comment by Akianonymus** [comment]
How to reproduce this ?

**Comment by siduck** [comment]
> How to reproduce this ?

- open a file with nvim i.e nvim filename and then do leader th

https://user-images.githubusercontent.com/59060246/145685935-0a9e054e-b431-44e7-8cb8-1c0821127bb6.mp4
