### ISSUE TITLE
Breaking change! 

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#634]
remove this line from your chadrc
 
 ```
 M.options, M.ui, M.mappings, M.plugins = {}, {}, {}, {}
```

**Comment by siduck** [comment]
Also some of you might be asking where's the custom dir , dont worry its just not created by default. you need to create it in the lua folder like before.

**Comment by asher-gh** [comment]
custom options not being applied after removing the line

**Comment by siduck** [comment]
> custom options not being applied after removing the line

did you update nvchad and did packersync? do you use 0.6?

**Comment by asher-gh** [comment]
Yes. The issue seemed to be with `M.mappings` I had in `chardrc.lua`. After removing that, its working as expected. However, I'm still trying to figure out why the `space + /` comment mapping is not working

**Comment by siduck** [comment]
> Yes. The issue seemed to be with `M.mappings` I had in `chardrc.lua`. After removing that, its working as expected. However, I'm still trying to figure out why the `space + /` comment mapping is not working

its fixed. latest commit of comment.nvim had some breaking changes so i updated the mappings config
