### ISSUE TITLE
Please name the themes in the README.

### ISSUE THREAD

**Issue by qazip** [NvChad/NvChad#635]
You have several screenshots in the README showcasing NvChad's themes. Could you please name them? I'd be interested in using these themes in my own config but I can't find any reference to them. I am referring to these 2 specifically:

https://user-images.githubusercontent.com/59060246/130129880-59ab1ad5-9aa6-4f50-9ddd-d8dde0c16257.png

and

https://user-images.githubusercontent.com/59060246/130129897-a68b1585-f42d-4325-8482-102dd2fe1e9e.png

or are they your own themes? If so, do you have a repo for them?

**Comment by siduck** [comment]
onedark and gruvchad

**Comment by siduck** [comment]
https://github.com/NvChad/nvim-base16.lua

**Comment by bryant-the-coder** [comment]
How can i get gruvchad in a regular nvim setup?? FYI I am not using NvChad.
My repo: https://github.com/bryant-the-coder/NvHack

**Comment by bryant-the-coder** [comment]
Or other theme??? Cause it will be great to use it :))
