### ISSUE TITLE
Where does chardrc.lua live?

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#636]
More a question.
Where does the custom settings from chardrc.lua go now?
It used to go to nvim/lua/custom/ but that folder does not exist anymore on a new clone

**Comment by siduck** [comment]
> More a question. Where does the custom settings from chardrc.lua go now? It used to go to nvim/lua/custom/ but that folder does not exist anymore on a new clone

its in the same folder

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config

**Comment by se7en-x230** [comment]
Before it was created on new clone. 
I added now `mkdir -p ~/.config/nvim/lua/custom/`
to my alias and now it works again

`nvchad="rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim ; git clone https://github.com/NvChad/NvChad ~/.config/nvim ;  mkdir -p ~/.config/nvim/lua/custom/ ; ln -s ~/.config/chadrc.lua ~/.config/nvim/lua/custom/; nvim +'hi NormalFloat guibg=#1e222a' +PackerSync" \
`

**Comment by siduck** [comment]
> Before it was created on new clone. I added now `mkdir -p ~/.config/nvim/lua/custom/` to my alias and now it works again
> 
> `nvchad="rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim ; git clone https://github.com/NvChad/NvChad ~/.config/nvim ; mkdir -p ~/.config/nvim/lua/custom/ ; ln -s ~/.config/chadrc.lua ~/.config/nvim/lua/custom/; nvim +'hi NormalFloat guibg=#1e222a' +PackerSync" \ `

you dont need to do this! just super uu :D

**Comment by se7en-x230** [comment]
I have sometimes trouble with leader uu. Getting multiple errors upon restart. 
Does not happen often but if I just use the alias to pull the newest version and link my custom back.

**Comment by siduck** [comment]
> I have sometimes trouble with leader uu. Getting multiple errors upon restart. Does not happen often but if I just use the alias to pull the newest version and link my custom back.

whenever you get such errors  ,just do packersync
