### ISSUE TITLE
Can't install local plugin

### ISSUE THREAD

**Issue by ayocloud** [NvChad/NvChad#637]
**Describe the bug**
I tried to add a local vim-script plugin but failed

**To Reproduce**

1. add config in `custom/init.lua`

```
hooks.add("install_plugins", function(use)
   use {
      "~/.gtags/gtags.vim"
   }
end)
```
2. exit nvim
3. open nvim and exec `:PackerInstall`

**Screenshots**
```
Failed to install /root/.gtags/gtags.vim 
Errors:
  Cloning into '/root/.local/share/nvim/site/pack/packer/start/gtags.vim'... 
  remote: Not Found 
  fatal: repository 'https://github.com//root/.gtags/gtags.vim.git/' not found
```

**Desktop (please complete the following information):**
 - Fedora
 - Alacritty
 - NVIM v0.5.1

**Comment by siduck** [comment]
does it work if u do it in plugins/init.lua

**Comment by ayocloud** [comment]
> does it work if u do it in plugins/init.lua

no, that doesn't work

config
```
return packer.startup(function()
    local plugin_settings = require("core.utils").load_config().plugins
    local override_req = require("core.utils").override_req

    -- ...
    use {
        "~/.gtags/gtags.vim"
    }
    -- ...

    -- load user defined plugins
    require("core.hooks").run("install_plugins", use)
end)
```

**Comment by siduck** [comment]
> > does it work if u do it in plugins/init.lua
> 
> no, that doesn't work
> 
> config
> 
> ```
> return packer.startup(function()
>     local plugin_settings = require("core.utils").load_config().plugins
>     local override_req = require("core.utils").override_req
> 
>     -- ...
>     use {
>         "~/.gtags/gtags.vim"
>     }
>     -- ...
> 
>     -- load user defined plugins
>     require("core.hooks").run("install_plugins", use)
> end)
> ```

then the issue is with your plugin probably!

**Comment by siduck** [comment]
try 
```
use "~/.gtags/"
```

**Comment by ayocloud** [comment]
> try
> 
> ```
> use "~/.gtags/"
> ```

exec `:PackerInstall` and no error reported
but plugin doesn't work

i try to put it in vim's autoload folder and it doesn't work too

i think there may be a problem with my plugin

thanks

**Comment by siduck** [comment]
> > try
> > ```
> > use "~/.gtags/"
> > ```
> 
> exec `:PackerInstall` and no error reported but plugin doesn't work
> 
> i try to put it in vim's autoload folder and it doesn't work too
> 
> i think there may be a problem with this plugin
> 
> thanks

no need to install it , try 

```
vim.cmd('~/.gtags/gtags.vim') 
```

**Comment by ayocloud** [comment]
@siduck
I know why it doesn't work.
The local plugin directory structure should look like this
```
.
└── gtags/
    └── plugin/
        └── gtags.vim
```
and then add 
```
use "~/gtags"
```
in `custom/init.lua`


I think there is something wrong with my original method

**Comment by siduck** [comment]
@ayocloud show your init.lua

**Comment by ayocloud** [comment]
@siduck 
```
hooks.add("setup_mappings", function(map)
   map("n", "<leader>cc", ":Telescope <CR>", opt)
   map("n", "<leader>q", ":q <CR>", opt)
end)


hooks.add("install_plugins", function(use)
  use "~/gtags"
end)
```
and the `~/gtags`  folder should look like 
```
root
└── gtags/
    └── plugin/
        └── gtags.vim
```

**Comment by siduck** [comment]
> @siduck
> 
> ```
> hooks.add("setup_mappings", function(map)
>    map("n", "<leader>cc", ":Telescope <CR>", opt)
>    map("n", "<leader>q", ":q <CR>", opt)
> end)
> 
> 
> hooks.add("install_plugins", function(use)
>   use "~/gtags"
> end)
> ```
> 
> and the `~/gtags` folder should look like
> 
> ```
> root
> └── gtags/
>     └── plugin/
>         └── gtags.vim
> ```

oh idk then! cant you just source gtags.vim?

**Comment by ayocloud** [comment]
@siduck 
it works too
😶
