### ISSUE TITLE
Telescope transparency colors highlights

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#638]
**Describe the bug**
When transparent set to "true"

**To Reproduce**
1. Telescope find file `<leader>ff` _or_ any related to telescope UI

**Desktop (please complete the following information):**
 - Windows 10 & Pop OS
 - Windows Terminal (WSL2 Ubuntu 20.04) & Kitty
 - NVIM v0.6.0 Release

https://user-images.githubusercontent.com/73665622/145260174-801b1148-7303-4224-ac05-6e69bed13b24.mp4

**Comment by siduck** [comment]
fixed

**Comment by peppapig450** [comment]
this isnt really related but are you using exa?

**Comment by GreatestOfAllTimee** [comment]
> this isnt really related but are you using exa?

What exa means ?

**Comment by peppapig450** [comment]
are you using exa for ls it looks like you are
https://github.com/ogham/exa

**Comment by GreatestOfAllTimee** [comment]
> are you using exa for ls it looks like you are https://github.com/ogham/exa

I see, nahh, I use lsd it more faster
https://github.com/Peltoche/lsd

**Comment by peppapig450** [comment]
ooh thanks ill try that out
