### ISSUE TITLE
Error in in the Wiki....

### ISSUE THREAD

**Issue by CaninoDev** [NvChad/NvChad#641]
**Describe the bug**
The shortcuts have been mislabeled in [Navigation In Insert Mode](https://nvchad.github.io/config/Default%20mappings#navigation-in-insert-mode) section of the wiki. Currently, `ctrl - k` documented to be bound to the `next line` behavior. It is in fact, bound to the `prev line` behavior. `ctrl-j` is similarly in error (it should be documented as bound to the `next line` behavior instead of `prev line`.)

**Screenshots**
![2021-12-09_14-02](https://user-images.githubusercontent.com/16412897/145459268-273f327d-3bce-4259-894d-fd252ad792f1.png)

**Comment by siduck** [comment]
thanks for reporting this! https://github.com/NvChad/nvchad.github.io/commit/c685d71b149e5cc67af2fd99b22456c93f841d75
