### ISSUE TITLE
Failed to install packer packages

### ISSUE THREAD

**Issue by abdullah-saal** [NvChad/NvChad#642]
**Describe the bug**
I tried installing it on my laptop and it worked with neovim installed from apt, but now I want to use it on ssh server, so I used appimage. and got the following errors, might be a trivial issue, but I am new to this.

**Screenshots**
![Screenshot from 2021-12-10 02-07-00](https://user-images.githubusercontent.com/82318860/145483607-c03ab34b-931b-4dee-8d02-11d1837b5fca.png)

**Comment by siduck** [comment]
is this 0.6v?

**Comment by abdullah-saal** [comment]
It is `NVIM v0.7.0-dev+697-g6063e07a0`
I tried `NVIM v0.6.0` but got the same errors

**Comment by siduck** [comment]
I doubt if the old version of Ubuntu is causing this , can you try the newest version?

**Comment by abdullah-saal** [comment]
Can't change it, unfortunately.

**Comment by peppapig450** [comment]
My guess would be that a C library that neovim/lua's c api depends on is too old because of the Ubuntu version

**Comment by peppapig450** [comment]
So I installed ubuntu 16.04 lts on an VM and tried to build from source and I had to install cmake from a ppa to get it to build otherwise it failed. This might have something to do with it?

**Comment by peppapig450** [comment]
I can confirm the issue is almost 99% because of the ancient git version 
https://github.com/wbthomason/packer.nvim/issues/82
https://github.com/wbthomason/packer.nvim/issues/95

**Comment by peppapig450** [comment]
I installed a newer git version following this https://unix.stackexchange.com/questions/33617/how-can-i-update-to-a-newer-version-of-git-using-apt-get and it works :) 
![image](https://user-images.githubusercontent.com/55930078/147157212-b166e4c3-11d5-40e2-a9d5-112131d7c19a.png)

**Comment by siduck** [comment]
so this is most probably the system's issue! update it :v
