### ISSUE TITLE
nvim-comment plugin default bindings do not work

### ISSUE THREAD

**Issue by Ryunaq** [NvChad/NvChad#643]
**Describe the bug**
[nvim-comment](https://github.com/terrortylor/nvim-comment) plugin default bindings do not work. E.g.  `gcc` does nothing.
Interestingly, if first I do `leader /` (the default binding), and then I do `gcc`, it works as intended. I don't know much about nvim/lua but I'm guessing the lazy loading of the plugin is causing it (?).

**To Reproduce**
Clean install of nvchad on neovim.

**Expected behavior**
`gcc` and the other related commands (`gcl`, etc) comment the lines.

**Desktop (please complete the following information):**
 - WSL2 (Manjaro) on Windows 10.
 - Windows Terminal
 - NVIM v0.7.0-dev+704-gac2d140a3

**Additional context**
As I said, not sure what's causing this but as suggested [here](https://github.com/NvChad/NvChad/issues/626) maybe changing to Comment.nvim would help? Idk really.

Btw great work! Thanks for it.

**Comment by siduck** [comment]
maybe cuz nvim-comment is lazy loaded? remove its lazy loading and see

**Comment by Ryunaq** [comment]
I didn't know how to disable the lazy loading so I just disabled the plugin and added my own config for Comment.nvim haha. Well this solves the problem for me so I'll close the issue. Thanks!

**Comment by siduck** [comment]
> I didn't know how to disable the lazy loading so I just disabled the plugin and added my own config for Comment.nvim haha. Well this solves the problem for me so I'll close the issue. Thanks!

check our docs!

**Comment by Akianonymus** [comment]
@Ryunaq Comment.nvim has been merged in the repo and this issue should also be fixed.

https://github.com/NvChad/NvChad/commit/d2db2cc1cd4cdb8197ceffbfb84c3fdfb704d5d0

**Comment by danielcherubini** [comment]
I've just started to have this issue.. i don't know what caused it, it happened after i did a recent update for nvchad

**Comment by siduck** [comment]
> I've just started to have this issue.. i don't know what caused it, it happened after i did a recent update for nvchad

make sure you use 0.6.1

**Comment by danielcherubini** [comment]
It is, here's everyhing

```NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"```
  
and all my dots for nvchad
https://gitlab.com/danielcherubini/dotfiles/-/tree/master/nvchad

**Comment by siduck** [comment]
> It is, here's some more details
> 
> ```
> NVIM v0.6.1
> Build type: Release
> LuaJIT 2.0.5
> Compiled by builduser
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> ```
> 
> and all my dots for nvchad https://gitlab.com/danielcherubini/dotfiles/-/tree/master/nvchad

does it work with default nvchad

**Comment by danielcherubini** [comment]
Nope, here's what i've tried

1. Revert back to default nvchad
2. delete `.local/share/nvim`
3. delete `.cache/nvim`
4. delete `.config/nvim` and 'reinstall' nvchad 

none of those worked.

when i check `:PackerStatus` i can see `Comment.nvim` isn't loaded, nor is `nvim-tree` (but im guessing that doesnt load till i open the tree.

Assuming that `Comment.nvim` is loaded the same way, that it's lazy loaded till you use the `leader /` keybind, that would make sense to why it suddenly loads.

Could the `gcc` bind not be loading `Comment.nvim` ?

**Comment by siduck** [comment]
> Nope, here's what i've tried
> 
> 1. Revert back to default nvchad
> 2. delete `.local/share/nvim`
> 3. delete `.cache/nvim`
> 4. delete `.config/nvim` and 'reinstall' nvchad
> 
> none of those worked.
> 
> when i check `:PackerStatus` i can see `Comment.nvim` isn't loaded, nor is `nvim-tree` (but im guessing that doesnt load till i open the tree.
> 
> Assuming that `Comment.nvim` is loaded the same way, that it's lazy loaded till you use the `leader /` keybind, that would make sense to why it suddenly loads.
> 
> Could the `gcc` bind not be loading `Comment.nvim` ?

comment nvim is lazy loaded so its not loaded by default ,it loads on module 'Comment' . 

try checking its lua api, might help 

https://github.com/numToStr/Comment.nvim/blob/master/doc/API.md#%EF%B8%8F-usage
