### ISSUE TITLE
Session save keeps NvimTree as an empty buffer

### ISSUE THREAD

**Issue by Ryunaq** [NvChad/NvChad#646]
**Describe the bug**
Session saving provided by the Dashboard plugin in NvChad save the file explorer vim-tree like an empty file.

**To Reproduce**
1. Have the vim-tree file explorer open and save the session.
2. Close nvim
3. Reopen nvim and load the session. The vim-tree will appear like an empty file
![image](https://user-images.githubusercontent.com/17756312/145688273-4a5799ba-daee-4377-bcfe-b42625ab26a0.png)

**Expected behavior**
Either not save the vim-tree explorer as an empty file, or reopen nvim-tree correctly.

**Desktop (please complete the following information):**
 - WSL2 Manjaro in Windows10
 - Windows Terminal
 - NVIM v0.7.0-dev+704-gac2d140a3

**Additional context**
I guess this is rather a problem from the Dashboard plugin, but I think it'd be better to cover this case in NvChad, since the solution will probably be somewhat hacky.

**Comment by G-Rowell** [comment]
@Ryunaq 

Hmmmm,
looks like we don't have our session tool in the default config anymore?
See our default plugin list: https://github.com/NvChad/NvChad/blob/main/lua/plugins/init.lua

What are your thoughts?

Though we seem to still have some code regarding the session plugin in NvChad


Galen

**Comment by Ryunaq** [comment]
@G-Rowell 

By default the dashboard plugin is turned off, but I turned it on and as far as I can see I think the code should be working, no idea why it doesn't.

**Comment by G-Rowell** [comment]
@Ryunaq 

NeoVim does have in-built sessions,
though the code for saving sessions in NvChad references a plugin that we don't use anymore.

**Comment by siduck** [comment]
> @Ryunaq
> 
> NeoVim does have in-built sessions, though the code for saving sessions in NvChad references a plugin that we don't use anymore.

Yes dashboard isn't used by default so it's mappings are disabled too

**Comment by Ryunaq** [comment]
@siduck yeah, the problem appears when the plugin and the mappings are enabled. I guess this is a question of whether disabled-by-default plugins are supported to work with the tree or not.

**Comment by siduck** [comment]
> @siduck yeah, the problem appears when the plugin and the mappings are enabled. I guess this is a question of whether disabled-by-default plugins are supported to work with the tree or not.

I doubt if dashboard.nvim's implementation of saving session isnt faulty, can you try this https://github.com/folke/persistence.nvim
sorry for late reply :(

**Comment by siduck** [comment]
@Ryunaq remove lazy loading for nvim-tree first ( go to plugin options , nvimtree lazy_true option in default_config.lua) and make that change into chadrc.

use this plugin for session management, better than dashbaord.nvim imo

```
 
   use {
      "rmagatti/auto-session",
      cmd = { "SaveSession", "RestoreSession" },
      config = function()
         require("auto-session").setup {
            log_level = "info",
            auto_session_enable_last_session = false,
            auto_session_root_dir = "~/test/", -- change this!
            auto_session_enabled = false,
            auto_save_enabled = false,
            auto_restore_enabled = false,
            auto_session_suppress_dirs = nil,
            pre_save_cmds = { "tabdo NvimTreeClose" },
            post_restore_cmds = { "tabdo NvimTreeRefresh" },
         }
      end,
   }
   ```
