### ISSUE TITLE
lspconfig binding not working

### ISSUE THREAD

**Issue by Ryunaq** [NvChad/NvChad#647]
**Describe the bug**
The lspconfig bindings as declared [here](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/lspconfig.lua) do not work as intended. It seems they are not being recognized? I'm doing `:map` and none of these seem to be getting mapped into neovim. Manually executing the commands works fine, i.e. `lua vim.lsp.buf.hover()<CR>` works as intended, but `K` does not.

**To Reproduce**
1. Clean install of NvChad.
2. Set up custom lspconfigs as declared [here](https://nvchad.github.io/config/Lsp%20stuff)
3. Try to run a command, like `K`

**Expected behavior**
The keybinding should execute the command.

**Desktop (please complete the following information):**
- WSL2 Manjaro in Windows10
- Windows Terminal
- NVIM v0.7.0-dev+704-gac2d140a3

**Additional context**
Since my custom lsp servers are working correctly, the [lspconfig.lua](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/lspconfig.lua) must be recognizing well my custom config. There may be a problem with the `on_attatch` function then (?). I'm new and not fully understanding how this works.

**Comment by GreatestOfAllTimee** [comment]
I thinks, `lsp.hover` base on language server you installed. Here are the example on my LSP config file. `shift+k` will bring to man page. Im not quite sure why man page, but its seems like a good idea.

https://user-images.githubusercontent.com/73665622/145713809-6c9f60cb-1313-4d21-8b78-c26e4b6a8ea2.mp4

**Comment by GreatestOfAllTimee** [comment]
OR try remap at lua/custom/init.lua. Its also happen to me at `lua vim.lsp.buf.formatting()`.

**Comment by Ryunaq** [comment]
> I thinks, `lsp.hover` base on language server you installed. Here are the example on my LSP config file. `shift+k` will bring to man page. Im not quite sure why man page, but its seems like a good idea.
> 
>  LSP_HOVER.mp4

Yeah, `K` is sending me to the man page too, I haven't figured out why haha.

**Comment by siduck** [comment]
sorry for late response and btw K works for me!

https://user-images.githubusercontent.com/59060246/147379850-a287009e-1585-4ca5-9960-865351657fd8.mp4

**Comment by Akianonymus** [comment]
K works fine here, along with other lsp bindings.

**Comment by Ryunaq** [comment]
Hmm are you guys using a clean config? `K` did not work for me, nor for GreatestOfAllTimee.

**Comment by siduck** [comment]
> Hmm are you guys using a clean config? `K` did not work for me, nor for GreatestOfAllTimee.

no i have a custom config too! my custom dir https://github.com/siduck/dotfiles/tree/master/nvim

**Comment by GreatestOfAllTimee** [comment]
I think it's fixed on [#31e551a](https://github.com/NvChad/NvChad/commit/31e551af3072df8e3d0f8c65d98adb3d32b0b0fb) and [#3a96695](https://github.com/NvChad/NvChad/commit/3a966955d4d71b8661b35588c8b12288e6d3c6f3) , however `<Shift> + k` only work when [LSP](https://github.com/neovim/nvim-lspconfig) Language server already configured.

**Comment by Ryunaq** [comment]
Indeed it is, thanks!
