### ISSUE TITLE
Is there a way to disable the default keymappings?

### ISSUE THREAD

**Issue by SCJangra** [NvChad/NvChad#648]
I am having a really hard time getting used to the default keymappings (I think LunarVim have better keymappings). It would be wonderful if there was a way to disable all default mappings, so that i can configure my own mappings using which-key.

**Comment by siduck** [comment]
you're coming from lunarvim so probably yes you its keymappings might be more favorable to you. you can just override the default mappings.

**Comment by siduck** [comment]
and check em here if they're applied 

![image](https://user-images.githubusercontent.com/59060246/145701891-ce68fb51-3766-4fb7-8222-3204fb782196.png)

**Comment by SCJangra** [comment]
> you're coming from lunarvim

No i don't  come from LunarVim. I manage my own config. I did not mention that, because I would obviously prefer the keymappings I setup myself over others.

> you can just override the default mappings

Yes, I could for example, override keymappings in `M.mappings` in `custom/chadrc.lua`, but i am using which-key and
![image](https://user-images.githubusercontent.com/40860699/145703455-61881c04-c051-45eb-bc8e-444c64b346c1.png)
this does not look pretty. There are a lot of `+prefix` and they are not useful.

I could directly set my keymappings using which-key, but then the default keymappings are still there. And now we have multiple keymaps that do the same thing. And it also make the which-key window look very cluttered.

That's why I am currently having to do both. First override the default keymappings in `M.mappings` and then set those same mappings using which-key in `setup_mappings` hook.

And besides all that, there are some mappings I would rather not have at all. For example if I am using which-key, then the mapping for cheatsheet is no longer useful. There are a few other mappings that i would probably never use, so it makes no sens to have them in the first place (they also take extra space in which-key window). But currently there is no way to delete them.

**Comment by dinhmai74** [comment]
@SCJangra Do you find the solution to remove all default mappings ? I'm facing same issue.

**Comment by SCJangra** [comment]
@dinhmai74 No, currently NvChad does not provide a way to remove default mappings.
But if NvChad is your daily driver and you don't mind losing a very small part of its functionality, then there is something you can do about it.

Go to `lua/core/utils.lua` file, there you will find a function named `map`.
Comment everything inside this function (don't comment the function itself, just its contents). Something like this
```
M.map = function(mode, keys, command, opt)
--    local options = { noremap = true, silent = true }
--    ...
--    map_wrapper(mode, keys, command, options)
end
```

This function seems to be used to set default mappings. And you will have to do this every time you update NvChad

But now you won't be able to use the map function passed to the `setup_mappings` hook.
```
hooks.add("setup_mappings", function(map)
                                      ^----- This is the same map function, and it doesn't do anything anymore.
end)
```
