### ISSUE TITLE
Digraphs

### ISSUE THREAD

**Issue by fullstopslash** [NvChad/NvChad#649]
The current insert mode mapping of <C-k> clashes with the default mapping for inserting digraphs.  If you're not familiar with those, they're these really handy shortcuts for inserting Unicode characters.   For example allowing one to do ``` <C-k> ,.``` to insert an ellipsis, among _many_ other things.  If it's to remain the default I feel it should at least be mentioned in the documentation 👍

**Comment by G-Rowell** [comment]
While I never need insert unicode characters and the like,
I do agree that at the very least we should have a note of this.

Maybe we could have a page on our website like:

---

#NvChad quirks

###mappings

- conflict of the NeoVim digraph mapping, such as `<C - k> , .` with an insert mode mapping

---

Thoughts?

**Comment by siduck** [comment]
https://github.com/NvChad/nvchad.github.io/commit/122aaa6f22db1b526928e9bb0707a287a0a6d5ed
