### ISSUE TITLE
chadrc.lua missing during installation

### ISSUE THREAD

**Issue by zakrywilson** [NvChad/NvChad#652]
**Describe the bug**
I was doing a fresh installation, following the instructions here: https://nvchad.github.io/getting-started/setup

The documentation has "Install" and "Update" under the "Setup" section. I figured I probably needed to update after I installed, so I tried running the updater `<leader>uu` and got the following error:

```
E5108: Error executing lua ...im/site/pack/packer/start/extensions/lua/nvchad/init.lua:31: ENOENT: no such file or directory: /usr/local/redacted/.config/nvim/lua/custom/chadrc.lua
stack traceback:
        [C]: in function 'assert'
        ...im/site/pack/packer/start/extensions/lua/nvchad/init.lua:31: in function 'file'
        ...ack/packer/start/extensions/lua/nvchad/update_nvchad.lua:36: in function 'update_nvchad'
        [string ":lua"]:1: in main chunk
```

I had to do some Googling to find #491 that resulted in [this](https://github.com/NvChad/nvchad.github.io/commit/24b8a96df557f07a304e03f35cd3ae287bd08cf2) fix to the documentation. But that fix for the "Post-install" page (the second page), not the "Setup" page, which is the first page users may run into this issue.

**To Reproduce**
I think repro is probably obvious – same as #491. If you have any questions on how to repro this or any other questions, please let me know.

**Expected behavior**
Either one of the two:
1. Those custom files are not required by the system in order to update (maybe show a warning).
2. The [Setup](https://nvchad.github.io/getting-started/setup) page has a note about this, so first-time users don't run into this issue. It's not obvious that those custom files are created by users, and it's not obvious that I should go to the [next page](https://nvchad.github.io/getting-started/post-install) in order to find the solution to the problem I encountered on the first.

Thanks!

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config

Check the lua/examples dir
