### ISSUE TITLE
About Lsp Install

### ISSUE THREAD

**Issue by Eolien55** [NvChad/NvChad#654]
**Is your feature request related to a problem? Please describe.**
Not really. I recall you removing LspInstall, for compatibility with Windows.

**Describe the solution you'd like**
Well, there is https://github.com/williamboman/nvim-lsp-installer, that seems to be support Windows, unlike the other lsp installer that you previously used. Furthermore, kabouzeid from https://github.com/kabouzeid/nvim-lspinstall have deprecated his own Lsp installer, and recommends the use of williamboman's tool.

**Describe alternatives you've considered**
You can also just don't re-add Lsp installer tools.

**Additional context**
Maybe not important but I've opened this issue : https://github.com/NvChad/NvChad/issues/458.

**Screenshot**
None required

**Comment by siduck** [comment]
https://nvchad.github.io/config/Lsp%20stuff#lsp-installer

**Comment by Eolien55** [comment]
oooooh, sorry
