### ISSUE TITLE
map a key to load  custom init files

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#657]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

**Describe the solution you'd like**
map a key to load  custom init files

**Describe alternatives you've considered**
 
**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
you can already create your own mappings . I dont see any reason for this to be added by default!

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#add-new-mappings
