### ISSUE TITLE
Comment mapping not working 

### ISSUE THREAD

**Issue by asher-gh** [NvChad/NvChad#658]
**Describe the bug**
After updating, comment mapping is not working. However `gcc` comments out 

**Expected behavior**
Using `<space> + / `should comment out

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/74317567/146367899-86200883-99a7-4e18-97ea-5fd1f054350c.png">

**Desktop **
 - MacOS 12.1
 - iTerm 3.4.14
 - neovim 0.6

**Comment by siduck** [comment]
> **Describe the bug** A clear and concise description of what the bug is. After updating, comment mapping is not working. However `gcc` comments out
> 
> **Expected behavior** Using `<space> + / `should comment out
> 
> **Screenshots** <img alt="image" width="1440" src="https://user-images.githubusercontent.com/74317567/146367899-86200883-99a7-4e18-97ea-5fd1f054350c.png">
> 
> **Desktop **
> 
> * MacOS 12.1
> * iTerm 3.4.14
> * neovim 0.6

did you do packersync and leader uu?

**Comment by asher-gh** [comment]
Yes. It seemed to work before

**Comment by siduck** [comment]
comment.nvim had a breaking change in its latest commit so fixed it.
