### ISSUE TITLE
Cant update Nvchad/extensions

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#660]
**Describe the bug**
Nvchad/extensions update fails on PackerSync

**To Reproduce**
1. run :PackerSync
2. see error

**Expected behavior**
It to update cleanly

**Screenshots**
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/55930078/146451599-f057833a-7d73-4f38-b452-31056cc86207.png">

**Desktop (please complete the following information):**
 - Operating System: MacOS Monterey
 - Terminal: Kitty & iterm2
 - Version of Neovim: 0.6.0

**Additional context**
I think I changed the file terms.lua to fix a problem before but I don't remember. I tried manually `find ~/.config/nvim -type f -name 'terms.lua'` and nothing came up. manually running git reset --hard HEAD didnt work either

**Comment by siduck** [comment]
this is very weird :/

**Comment by siduck** [comment]
delete your .local/share/nvim and see

**Comment by peppapig450** [comment]
That worked. Thank you!
