### ISSUE TITLE
Unable to use space as mapping prefix

### ISSUE THREAD

**Issue by kasfil** [NvChad/NvChad#661]
**Describe the bug**
I was remapped my mapleader key to `,` then i'm trying to use `space` as some keymap prefix with this
![image](https://user-images.githubusercontent.com/46927505/146627117-b525c59a-9aa0-4594-a346-4f7b075462e0.png)
unfortunately this mapping won't work

**To Reproduce**
1. try remap leader key to `,`
2. setup new mapping with `space` prefix

**Expected behavior**
mapping should work

**Desktop (please complete the following information):**
 - Operating System: Arch
 - Terminal: Kitty
 - Version of Neovim: v0.6.0 release build

**Comment by siduck** [comment]
no need to remap leader for this! <space>o will still work , tested it rn

**Comment by kasfil** [comment]
if i still use `,` as my leader and `space` for some mapping prefix, will it work?

i mean, when i remap my leader to `,`
then i have `<leader>ff` to spawn telescope file finder, this should be `,ff`
then setup new mapping with `<space>o`

then my `<space>o` mapping key is not working

**Comment by siduck** [comment]
" , " doesnt work for me at all

**Comment by G-Rowell** [comment]
@kasfil 

As a hacky test,
setting line 16 in `lua/core/default_config.lua` -> M.options ..... to `mapleader = ","`
does work to change the leader key.

(though this is best done in the custom section, but this was to test that this works.)

----

then as my second hacky test, adding this line in the "required_mappings()" scope did work,
`map("n", "<space>o", ':echo "mapping works!" <CR>')`
(around line 82 of `lua/core/default_config.lua`)

----

So it seems that this should all work,
though these two changes should be made within your custom folder!

Would you try again and let me know if you're still stuck?

Galen

**Comment by kasfil** [comment]
@G-Rowell 

Thanks for your suggestion,
i tried your first suggestion, and it works
but since it will be revert back for each NvChad update, i will use other mapping key.

thanks for all suggestion, i will close the issue

**Comment by G-Rowell** [comment]
Well, you should be able to do this without it reverting!!

Checkout the 'custom' folder we use: https://nvchad.github.io/config/Custom%20config
