### ISSUE TITLE
Error when trying to use update mechanism built-in 

### ISSUE THREAD

**Issue by meaz** [NvChad/NvChad#663]
According to [https://nvchad.github.io/getting-started/setup](https://nvchad.github.io/getting-started/setup) `<leader> + uu` should allow to update. However, when I do so, I get this:
```
E5108: Error executing lua ...im/site/pack/packer/start/extensions/lua/nvchad/init.lua:31: ENOENT: no such file or directory: /home/name/.config/nvim/lua/custom/chadrc.lua
stack traceback:
        [C]: in function 'assert'
        ...im/site/pack/packer/start/extensions/lua/nvchad/init.lua:31: in function 'file'
        ...ack/packer/start/extensions/lua/nvchad/update_nvchad.lua:36: in function 'update_nvchad'
        [string ":lua"]:1: in main chunk
```

Indeed, I don't have a `custom/chadrc.lua`...

I have tried with a clean / new version of NvChad.

**Comment by siduck** [comment]
you need to have a chadrc file! copy it from examples dir

**Comment by Akianonymus** [comment]
Actually this is a valid issue, it shouldn't show an error whether custom folder is there or not.

**Comment by GreatestOfAllTimee** [comment]
Is from [Nvchad/Extension](https://github.com/NvChad/extensions/blob/51e37338ed91d2325352a146c10e16bb7d70f172/lua/nvchad/update_nvchad.lua#L36)

**Comment by meaz** [comment]
So updating with `<leader> + uu` doesn't work without a `custom/chadrc.lua` ?

**Comment by siduck** [comment]
> So updating with `<leader> + uu` doesn't work without a `custom/chadrc.lua` ?

yes , i'll look about it this weekend

**Comment by Akianonymus** [comment]
This should be fixed now.
