### ISSUE TITLE
It always remind to press enter

### ISSUE THREAD

**Issue by loenvom** [NvChad/NvChad#664]
When Open nvim, I get this :

Feline: error while processing component number 10 on section 1 of type 'active'
: ...r/neovim/0.6.0/share/nvim/runtime/lua/vim/diagnostic.lua:83: Invalid severi
ty: Information

![image](https://user-images.githubusercontent.com/59039948/147069697-c5dfb63d-9aaf-4057-a8de-6c182b797cb1.png)

**Comment by loenvom** [comment]
When I press enter, It still exist.

**Comment by dedani** [comment]
same.

**Comment by G-Rowell** [comment]
I've been trying to debug this myself,
It's probably an issue upstream with Feline.

Will keep you all updated, have a temp-fix in the meantime

**Comment by G-Rowell** [comment]
@dedani @loenvom 

Steps to hot-fix:

1. `vim --noplugin ~/.config/nvim/lua/plugins/init.lua`
2. add `commit = "4ef5e1516395eea731275e0f58b6bfba5c6ac9c1",` after line 39
3. close vim
4. open vim with `vim --noplugin`
5. run `:PackerSync`
6. quit and open vim normally

this will fix whatever breaking change Feline made for the meantime, it will have to be removed at some point

**Comment by dedani** [comment]
Thanks, will apply it! I did remove the whole feline-packer entry before, but your fix is better.

**Comment by G-Rowell** [comment]
https://github.com/feline-nvim/feline.nvim/commit/6be9ca2d26b704d4df91a3199cd0c2ab870ac9d8

This is the breaking commit,
it's labelled as such, so reading into it

**Comment by loenvom** [comment]
yep, I fix it just by use specific version 0.3.3 of feline

**Comment by boppyt** [comment]
This was fixed in #666.

**Comment by G-Rowell** [comment]
@boppyt 

Thank you very much Boppy!!

**Comment by boppyt** [comment]
> @boppyt 
> 
> Thank you very much Boppy!!

No probs, happy to help!
