### ISSUE TITLE
Suggestion about Feline

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#667]
**Describe the bug**
Feline gives errors and makes it unable for me to type anything

**To Reproduce**
1. :PackerSync
2. open nvim
3. See Error

**Expected behavior**
nvim to open without errors 

**Screenshots**
<img width="1440" alt="Screen Shot 2021-12-22 at 3 21 03 PM" src="https://user-images.githubusercontent.com/55930078/147165914-834e2826-de13-45d9-b031-077220b585c0.png">

**Desktop (please complete the following information):**
 - macOs Monterey
 - Kitty
 - 0.6.0

**Additional context**
Is it possible to use something instead of feline? I feel like I have to spend hours figuring out feline bugs and breaking changes every week, and it is kind of annoying when I am trying to work on coding something.

**Comment by peppapig450** [comment]
Okay I just saw the other issues for this but I'll leave this here because I suggested something too

**Comment by boppyt** [comment]
Fixed in #666.

Hmm, feline worked fine for me.

**Comment by peppapig450** [comment]
On macOs everytime I do :PackerSync (like once or twice a week) I get errors with feline. And it is extremely frustrating

**Comment by siduck** [comment]
@peppapig450 we might switch over to https://github.com/NTBBloodbath/galaxyline.nvim then!

**Comment by boppyt** [comment]
weren't we using galaxyline before?

**Comment by siduck** [comment]
> weren't we using galaxyline before?

Hmm we were but since glephnir was offline for many months so galayxline repo became dead , so we switched to feline and for lazy loading stuff too.

**Comment by boppyt** [comment]
I see, I do personally prefer feline over the galaxyline though.
But if it constantly causes problems on darwin platform guess we have to change.
I'm kind of curious what kind of problems those users are getting.

**Comment by siduck** [comment]
> I see, I do personally prefer feline over the galaxyline though. But if it constantly causes problems on darwin platform guess we have to change. I'm kind of curious what kind of problems those users are getting.

Same

**Comment by siduck** [comment]
@peppapig450 list out your issues , I will fix em

**Comment by peppapig450** [comment]
I'll start making a list when I get them 👍

**Comment by barungh** [comment]
I am getting the same issue on my Arch Linux machine, any quick fix ? 👀

**Comment by peppapig450** [comment]
Updating NvChad than packersyncing again fixed it for me

**Comment by boppyt** [comment]
Not sure if we should close this, p sure he was talking about the original feline problem, not the feline problems on darwin.

**Comment by siduck** [comment]
> Not sure if we should close this, p sure he was talking about the original feline problem, not the feline problems on darwin.

I will open this when he faces the issue again.

**Comment by barungh** [comment]
Didn't find any option to update Nvchad when I was stuck on the issue,
so , reinstalled Nvchad, updated all plugins, 
and it fixed the issue of course
👍🏻

**Comment by siduck** [comment]
> Didn't find any option to update Nvchad when I was stuck on the issue, so , reinstalled Nvchad, updated all plugins, and it fixed the issue of course 👍🏻

Leader uu
