### ISSUE TITLE
can someone help me ?

### ISSUE THREAD

**Issue by sukai-cheng** [NvChad/NvChad#669]
![image](https://user-images.githubusercontent.com/35868545/147242414-0f778454-e441-4263-8ea1-18b91cf2c89c.png)

**Comment by boppyt** [comment]
What commit of nvchad and feline are you using?

**Comment by siduck** [comment]
I hope youre using 0.6v of nvim and your nvchad is uptodate! + did you run packersync ?

**Comment by boppyt** [comment]
Yep, I believe this shouldn't happen with latest feline.nvim.

**Comment by sukai-cheng** [comment]
I have up-to-date
![image](https://user-images.githubusercontent.com/35868545/147264463-03d3a45a-2655-48ab-a64f-94dcfe31d2a2.png)

**Comment by siduck** [comment]
> I have up-to-date ![image](https://user-images.githubusercontent.com/35868545/147264463-03d3a45a-2655-48ab-a64f-94dcfe31d2a2.png)

did you update nvchad? space uu

**Comment by bryant-the-coder** [comment]
How can i use gruvchad or any other theme from NvChad to ny config without using NvChad?

**Comment by siduck** [comment]
> How can i use gruvchad or any other theme from NvChad to ny config without using NvChad?

hmm you cant ._.

**Comment by bryant-the-coder** [comment]
Why:)

**Comment by siduck** [comment]
> Why? It would be great to have it :))

you can thereotically but you'll have to copy nvchad highlights too , since those themes just contain colors and do nothing. you need to figure it out yourself.

**Comment by bryant-the-coder** [comment]
:( can help :))))

**Comment by bryant-the-coder** [comment]
Pretty please :p cause i still dont know how to create a theme... I got ideas in mind but... Dont know how to create a theme 😭😭😭. I dont know how to use colorbuddy... I cant follow people theme... So please help.. Beg ya

**Comment by siduck** [comment]
> Pretty please :p cause i still dont know how to create a theme... I got ideas in mind but... Dont know how to create a theme sobsobsob. I dont know how to use colorbuddy... I cant follow people theme... So please help.. Beg ya

i wish i could! but honestly nvchad themes wont work well out of nvchad!! may i know the reason of yours for not using nvchad?

**Comment by bryant-the-coder** [comment]
Hmm first kinda conplicated. Second, i lovr building things on my own and planning to make one as successful as NvChad. That is my milestone

**Comment by siduck** [comment]
> Hmm first kinda conplicated. Second, i lovr building things on my own and planning to make one as successful as NvChad. That is my milestone. I never hate NvChad.

did you read our docs?

**Comment by bryant-the-coder** [comment]
Yes... But still complicated for a 14 year old

**Comment by siduck** [comment]
> Yes... But still complicated for a 14 year old

join our discord server ( check readme discord badge ) , let me know what you dont understand and I will surely help

**Comment by bryant-the-coder** [comment]
I cant join... Lemme snapshot

**Comment by bryant-the-coder** [comment]
![Screenshot_20211225_122702_com.discord.jpg](https://user-images.githubusercontent.com/92417638/147377380-16d39111-3934-468c-87c9-9aa4f814e8d0.jpg)

**Comment by boppyt** [comment]
Wait, is NvChad's nvim-base16 fork only work on nvchad?

**Comment by boppyt** [comment]
> ![Screenshot_20211225_122702_com.discord.jpg](https://user-images.githubusercontent.com/92417638/147377380-16d39111-3934-468c-87c9-9aa4f814e8d0.jpg)

- before I assist you with this, seems like it's off topic.
- you need to get a OS role in #rules to see those channels.

**Comment by siduck** [comment]
@sukai-cheng make sure you're using neovim 0.6v , do leader uu , then do :Packersync,  if you get errors that don't let you run packer commands then do : nvim --noplugin , and run the packer command.
