### ISSUE TITLE
vim.diagnostic is a nil value

### ISSUE THREAD

**Issue by SamuelMosesA** [NvChad/NvChad#671]
**Describe the bug**
Feline.nvim and nvim-lspconfig don't run because vim.diagnostic is a nil value

**To Reproduce**
- Use NVIM v0.5.1
- Run the installer script on the install page

**Expected behavior**
Nvim should start without any errors and the bottom bar should appear

**Screenshots**
![nvChad error](https://user-images.githubusercontent.com/56961772/147246995-cd58a80d-4ece-43f0-96bf-39223f6fcf36.png)

**Desktop (please complete the following information):**
 - Operating System: Pop OS 21.10
 - Terminal: Alacritty
 - Version of Neovim:  v0.5.1

**Additional context**
---

**Comment by boppyt** [comment]
Oops, sorry for the trouble, @SamuelMosesA !
I'll fix the feline part and take a look at the lspconfig.

**Comment by siduck** [comment]
can you use v0.6 ?

**Comment by ghifarit53** [comment]
AFAIK `vim.diagnostic` just becomes available in version >= `0.6`. Either you should upgrade to `0.6` or nvChad should add some version checking in the configuration to support backward compatibilities

**Comment by boppyt** [comment]
feline still has backward compatibility with 0.5, It's on me since I forgot to check for 0.6+

**Comment by boppyt** [comment]
Actually, I think we should just raise the minimum version to 0.6 since lspconfig doesn't support 0.5 anymore @siduck

**Comment by boppyt** [comment]
#672
