### ISSUE TITLE
add chocolate theme

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#675]
https://gitlab.com/snakedye/chocolate

**Comment by rfc2119** [comment]
Side question: Is there any plan to add a light theme with yellow/green-ish background like  [solarized light](https://ethanschoonover.com/solarized/) ?

**Comment by siduck** [comment]
> Side question: Is there any plan to add a light theme with yellow/green-ish background like [solarized light](https://ethanschoonover.com/solarized/) ?

no but PRS are welcomed

**Comment by bryant-the-coder** [comment]
it's like gruvchad+gruvbox having a baby :)

**Comment by bryant-the-coder** [comment]
@siduck i think i can do it. What is the dateline?

**Comment by siduck** [comment]
anytime

**Comment by bryant-the-coder** [comment]
ok. what's da rules to follow? will i be a chadtributor 😂😂😂

**Comment by siduck** [comment]
> ok. what's da rules to follow? will i be a chadtributor joyjoyjoy

https://nvchad.github.io/contribute#how-to-submit-themes

**Comment by bryant-the-coder** [comment]
@siduck this theme is too hard :P gotta wait for a official theme to be release

**Comment by bryant-the-coder** [comment]
XD. sorry tho

**Comment by siduck** [comment]
I give up on this :cry: 
https://discord.com/channels/869557815780470834/869557816430563370/957291910710562867

**Comment by bryant-the-coder** [comment]
why u give up? i thought u wanted to do it for a long time?

**Comment by siduck** [comment]
> why u give up? i thought u wanted to do it for a long time?

if i cant replicate it 100% same to the original one then there's no use

**Comment by sudo-ghost** [comment]
offtopic but has anyone found chocolate for alacritty? ive never seen this theme before nvchad

**Comment by siduck** [comment]
@sudo-ghost no, but it shouldnt be hard to make :)
