### ISSUE TITLE
nvim changes my terminal cursor

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#677]
**Describe the bug**
My cursor is a bar before I use neovim, but afterwards it is changed to a box.

**To Reproduce**
1.  open nvim
2. exit nvim `:q`
3. cursor is changed

**Expected behavior**
Cursor to stay the same 

**Screenshots**
https://user-images.githubusercontent.com/55930078/147373100-cd983398-96d0-4b17-9489-eb96dde7ee4e.mp4

**Desktop (please complete the following information):**
 - Operating System: Windows 11 - sshed into Arch Linux (happens on MacOS and Ubuntu too)
 - Terminal: Happens on every terminal I've tested except kitty
 - Version of Neovim: 0.6.0

**Additional context**
I know this isn't really an NvChad problem, but I searched the internet for about 45 minutes trying to find a fix and I couldn't find one in Lua. I also don't know which config file I would edit for this in NvChad.

**Comment by GreatestOfAllTimee** [comment]
https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes

**Comment by GreatestOfAllTimee** [comment]
Lua is optional, you can create a .vim script and source it.

**Comment by peppapig450** [comment]
where would i put something like this in the configuration. 
https://github.com/PrashanthaTP/dotfiles/commit/b283ad761e6ba2ccd8cf31bcd0e2196d12403b2a

**Comment by GreatestOfAllTimee** [comment]
Source vim script inside your [custom config](https://nvchad.github.io/config/Custom%20config) , e.g: `vim.cmd("source ~/.config/nvim/lua/custom/plugins/cursor.vim")` (_base on where your config file at_).

**NOTE :** Windows Terminal have some limitation about configuration your terminal display, even you running Ubuntu.

Or maybe this may help you: [restore cursor (#4867)](https://github.com/neovim/neovim/issues/4867#issuecomment-279901877) , take note, this only have been test on _Macos and Linux_.

**Comment by peppapig450** [comment]
I wrote a powershell script to change it but I cannot get it to work with the autocmd

https://user-images.githubusercontent.com/55930078/147374412-1393a68e-b610-4b09-8f14-aca3edbb1c14.mp4

**Comment by peppapig450** [comment]
Okay it turns out I was way overcomplicating this and I just had to change the guicursor on VimLeave. Thank you very much for dealing with my stupidity. But on the brightside, I guessed I learned some PowerShell.

**Comment by peppapig450** [comment]
Which custom config file would the autocmds go in? I have a feeling it's init.lua, but it might not even matter.

**Comment by siduck** [comment]
> Which custom config file would the autocmds go in? I have a feeling it's init.lua, but it might not even matter.

any, if you want to organize your custom dir then you could add autocmds in a different file and load that file in init.lua 

https://github.com/siduck/dotfiles/tree/master/nvim

**Comment by siduck** [comment]
@peppapig450 join our discord!

**Comment by peppapig450** [comment]
okay

**Comment by peppapig450** [comment]
It turns out that `echo -n -e '\e[0 q'` works in windows terminal too 🤦

**Comment by GreatestOfAllTimee** [comment]
> @peppapig450 join our discord!

Hey Chad, I think you need to bring HTML highlight back in NvChad/nvim-base16 [#4eb83f0](https://github.com/NvChad/nvim-base16.lua/commit/4eb83f08152ad54d766fea697f2bf3c544440c13#diff-00b6e8fce46043d3aeb9be44f6b034f734bca28de26cc71b9e0f6e39d4f78e46L178) because of tree-sitter highlight issue [#1788](https://github.com/nvim-treesitter/nvim-treesitter/issues/1788#issue-988278548) and [#2151](https://github.com/nvim-treesitter/nvim-treesitter/issues/2151#issue-1085577797) on HTML & Svelte files. Whats your suggestion ?

**Comment by siduck** [comment]
> > @peppapig450 join our discord!
> 
> Hey Chad, I think you need to bring HTML highlight back in NvChad/nvim-base16 [#4eb83f0](https://github.com/NvChad/nvim-base16.lua/commit/4eb83f08152ad54d766fea697f2bf3c544440c13#diff-00b6e8fce46043d3aeb9be44f6b034f734bca28de26cc71b9e0f6e39d4f78e46L178) because of tree-sitter highlight issue [#1788](https://github.com/nvim-treesitter/nvim-treesitter/issues/1788#issue-988278548) and [#2151](https://github.com/nvim-treesitter/nvim-treesitter/issues/2151#issue-1085577797) on HTML & Svelte files. Whats your suggestion ?

i added the html hightlight back locally but i still face the same issue!

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/147434574-59196447-7ad6-4996-9c9e-6be1d141487b.mp4

**Comment by GreatestOfAllTimee** [comment]
> i added the html hightlight back locally but i still face the same issue!

Treesitter highlight need to be disable `:TSDisable highlight` or 
```lua
ts_config.setup {
   ensure_installed = {
      "lua",
      "vim",
   },

   highlight = {
      enable = true,
      disable = { "html", "svelte" }, -- disable HTML & Svelte highlight
  },
}
```

**Comment by siduck** [comment]
> > i added the html hightlight back locally but i still face the same issue!
> 
> Treesitter highlight need to be disable `:TSDisable highlight` or
> 
> ```lua
> -- lua/plugins/configs/treesitter.lua
> 
> ts_config.setup {
>    ensure_installed = {
>       "lua",
>       "vim",
>    },
> 
>    highlight = {
>       enable = true,
>       disable = { "html", "svelte" }, -- disable HTML & Svelte highlight
>   },
> }
> ```

oh then the user can add this setting himself , also adding highlights for html wouldnt be hard too 

https://nvchad.github.io/config/Custom%20config#override-default-highlights

**Comment by GreatestOfAllTimee** [comment]
> oh then the user can add this setting himself , also adding highlights for html wouldnt be hard too
> 
> https://nvchad.github.io/config/Custom%20config#override-default-highlights

Sure this settings is optional. Btw how to import base colors ? **Example:** htmltag using _base05_ and etc ... so if I set htmltag with red and after that I change my current theme, the htmltag still become red. What I expect is htmltag colors supposed to follow the current themes.

**Comment by siduck** [comment]
> > oh then the user can add this setting himself , also adding highlights for html wouldnt be hard too
> > https://nvchad.github.io/config/Custom%20config#override-default-highlights
> 
> Sure this settings is optional. Btw how to import base colors ? **Example:** htmltag using _base05_ and etc ... so if I set htmltag with red and after that I change my current theme, the htmltag still become red. What I expect is htmltag colors supposed to follow the current themes.

hmm thats  not possible at the moment , for now you can just manually copy hex colors of those base colors

**Comment by GreatestOfAllTimee** [comment]
No worries! I just overide html highlight in [base16.lua](https://github.com/NvChad/nvim-base16.lua/blob/master/lua/base16.lua) , but it a bit annoying because `Packersync` will fail to get the current update for nvim-base16 (_if nvim-base16 has a update_). So I need to git clone manually. Overall it fine! ❤

**Comment by peppapig450** [comment]
I finally solved my problem to revert it to what it was exactly before. I gave up trying to figure out autocmd and used what I knew best, shell scripting. So I wrote this bash function and added it to my bashrc 
```shell 
nvim ()
{
    file="$1";
    command nvim "$file" && echo -ne '\e[0 q'
}
```
and now when i close nvim my cursor is changed back 😄
