### ISSUE TITLE
user config support (or make it easy to update config without breaking anything)

### ISSUE THREAD

**Issue by ceylog** [NvChad/NvChad#68]
Thank you for your work, I like it very well. Can you provide support for custom configuration options? When I update, my custom configuration will be overwritten.

**Comment by ashincoder** [comment]
what do you mean by custom configuration options.

**Comment by isquack** [comment]
Whaddaya mean.
There is more than a dozen config files for customizing it and it's well organized.
You should probably edit those files rather than creating your own.
You have the option to source your config files if you created separate ones.

**Comment by ashincoder** [comment]
Ok will work on that.

**Comment by siduck76** [comment]
@ceylog Im still learning neovim and lua so it'll take some time , For now just check every commit I make. adding changes manually wouldnt be that hard.

**Comment by ashincoder** [comment]
That is what I was trying to say.

**Comment by ceylog** [comment]
> @ceylog Im still learning neovim and lua so it'll take some time , For now just check every commit I make. adding changes manually wouldnt be that hard.

Great.😄

**Comment by Vanderscycle** [comment]
I do understand @ceylog issue, I am running an older version of the repo that I modified to my liking. I noticed that packer transforms all .lua files into a folder/lua.lua which makes the usage of rsync impossible. 

A potential solution, although not pretty, is separating all .lua files in the folder/lua.lua as it was a few months ago.

Of note, when I am creating a pr I fork the most up-to-date state of hte repo.

**Comment by Pocco81** [comment]
I'd suggest having a centralized config file with a global var to take vals from, like so:

**nvchad_globals.lua**

```lua
local globs = {}


globs.indentation = 4
globs.statusline = "galaxyline"
globs.wrap_lines = false
globs.treesitter.ensure_installed = "all"
-- and the rest....

return globs
```

and then call them where and when needed:

**some_config_file.lua**

```lua
if (require("path.to.nvchad_globals")["statusline"] == "galaxyline") then
    require("galaxyline")
else
    print("NVChad: Unsupported statusline. Sorry...")
end
```


Furthermore, @ceylog , I personally don't think it's the best idea to have nvchad as your config and then pulling from the repo to "update it". For example: if in nvchad @siduck76 decides to set the indentation to 4 but you have it set to 2 in your local config then there will be a conflict. This is not a program but an awesome config, which means that the settings are relative to the users' needs.

A "workflow" that makes more sense is to fork the repo and set this repo as an "upstream" while you modify the config in your fork's main branch (or any other) and then when ground-breaking changes are done here (e.g. adding support for an LSP) you could fetch from upstream into a local branch and then cherry-pick what you need.

But again, that's my opinion...

**Comment by ashincoder** [comment]
@Pocco81 that is a really great idea to make a branch and all. but I ain't the owner man.

**Comment by ashincoder** [comment]
@Pocco81 if you would like to add that checkout my fork [here](https://github.com/ashincoder/NvChad). And maybe create a Pull Request ;)

**Comment by siduck76** [comment]
> I'd suggest having a centralized config file with a global var to take vals from, like so:
> 
> **nvchad_globals.lua**
> 
> ```lua
> local globs = {}
> 
> 
> globs.indentation = 4
> globs.statusline = "galaxyline"
> globs.wrap_lines = false
> globs.treesitter.ensure_installed = "all"
> -- and the rest....
> 
> return globs
> ```
> 
> and then call them where and when needed:
> 
> **some_config_file.lua**
> 
> ```lua
> if (require("path.to.nvchad_globals")["statusline"] == "galaxyline") then
>     require("galaxyline")
> else
>     print("NVChad: Unsupported statusline. Sorry...")
> end
> ```
> 
> Furthermore, @ceylog , I personally don't think it's the best idea to have nvchad as your config and then pulling from the repo to "update it". For example: if in nvchad @siduck76 decides to set the indentation to 4 but you have it set to 2 in your local config then there will be a conflict. This is not a program but an awesome config, which means that the settings are relative to the users' needs.
> 
> A "workflow" that makes more sense is to fork the repo and set this repo as an "upstream" while you modify the config in your fork's main branch (or any other) and then when ground-breaking changes are done here (e.g. adding support for an LSP) you could fetch from upstream into a local branch and then cherry-pick what you need.
> 
> But again, that's my opinion...

this might make the config more complex and bloated , for now I think updating NvChad via commits would be right until it gets stable.

**Comment by ashincoder** [comment]
Is this still an issue as @siduck76 made his statement

**Comment by siduck76** [comment]
@ashincoder yes , I'll think about this till next month. I'll see what I can do something while still letting NvChad bloat free and suckless.

**Comment by JavaCafe01** [comment]
or we can go all out like spacevim :laughing:

**Comment by ashincoder** [comment]
@ceylog I have made global config support in [StarVim](https://github.com/ashincoder/StarVim
)

**Comment by ashincoder** [comment]
@Pocco81 is this what you meant here [StarVim](https://github.com/ashincoder/StarVim)

**Comment by ashincoder** [comment]
Why isn't anyone replying to this issue. @siduck76 you can check [StarVim](https://github.com/ashincoder/StarVim) here and see what I have implemented to setup a global config

**Comment by siduck76** [comment]
> Why isn't anyone replying to this issue. @siduck76 you can check [StarVim](https://github.com/ashincoder/StarVim) here and see what I have implemented to setup a global config

Cuz this thing feels complex :c

**Comment by siduck76** [comment]
idk if adding it will make the config bloated xd

**Comment by ashincoder** [comment]
What do you mean? By bloated

**Comment by ashincoder** [comment]
What do you mean by bloated 🤔

**Comment by ashincoder** [comment]
bloated means overfill and extended.

**Comment by siduck76** [comment]
i saw starvim's config.lua , it looked too long so got scared

**Comment by ashincoder** [comment]
Long does'nt mean scary does it. You just have read through all the things then you will understand. StarVim should get a star :smile:

**Comment by siduck76** [comment]
> Long does'nt mean scary does it. You just have read through all the things then you will understand. StarVim should get a star

if you showed an easy way for global config then I'd consider having it! config looks much cleaner without it tho ngl

**Comment by ashincoder** [comment]
I don't think there is a easy way. You have to describe every option to global so that the user can change according to his taste.

**Comment by siduck76** [comment]
> I don't think there is a easy way. You have to describe every option to global so that the user can change according to his taste.

what files are related to config.lua? 

I think adding these 60~ lines could be nice , the rest lang stuff isnt needed

https://github.com/ashincoder/StarVim/blob/dev/lua/config.lua#L60

**Comment by ashincoder** [comment]
They are for changing the formatter. I will remove the linter cause they don't do anythin as I have tested

**Comment by siduck76** [comment]
> They are for changing the formatter. I will remove the linter cause they don't do anythin as I have tested

ohh so the global config is only config.lua? i thought we need to define more stuff in other files

**Comment by ashincoder** [comment]
For the user config sv-config.lua file is there

**Comment by Pocco81** [comment]
[I have achieved this in my personal config](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev-mnc/.config/nvim/lua/nvd_settings.lua). It's still a work in progress because yesterday I switched to NvChad for convenience, so not everything is within that file, yet...

**Comment by Vanderscycle** [comment]
> [I have achieved this in my personal config](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev-mnc/.config/nvim/lua/nvd_settings.lua). It's still a work in progress because yesterday I switched to NvChad for convenience, so not everything is within that file, yet...

Ohhh, That's a good idea

**Comment by siduck76** [comment]
> [I have achieved this in my personal config](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev-mnc/.config/nvim/lua/nvd_settings.lua). It's still a work in progress because yesterday I switched to NvChad for convenience, so not everything is within that file, yet...

dang thats a lot :l

**Comment by Pocco81** [comment]
I mean, you don't need to have all of that. I personally like to have my stuff centralized, but if you wanted to you could just have a centralized config for autocommands, highlights, mappings and abbreviations, which are things most users would like to configure themselves. In [here](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/tree/dev-mnc/.config/nvim/lua/nvdope/runlevel) and [here](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/tree/dev-mnc/.config/nvim/lua/nvdope/utils) you'll find the modules that do that in my config.

**Comment by Pocco81** [comment]
> dang thats a lot :l

It's the same as what you'd normally have in nvchad, but in just one place, for convenience :]

**Comment by siduck76** [comment]
centralizing highlights would be a huge pain , it already has such stuff in highlights.lua .

**Comment by Akianonymus** [comment]
@siduck76 Theming in general is a pain in nvchad, first all it should be imported as a colorscheme that neovim recognises.

**Comment by godspeed-x** [comment]
I also agree there should be a separate file for user configs. It makes easier to update NvChad for those who fork it. If changes are made to the other config files there are conflicts during updates. It's not that manually updating from the commits is a lot of work but I guess it would just be more convenient to have something like that.

**Comment by godspeed-x** [comment]
I also agree there should be a separate file for user configs. It makes easier to update NvChad for those who fork it. If changes are made to the other config files there are conflicts during updates. It's not that manually updating from the commits is a lot of work but I guess it would just be more convenient to have something like that.

**Comment by siduck76** [comment]
> @siduck76 Theming in general is a pain in nvchad, first all it should be imported as a colorscheme that neovim recognises.

I have thought about it but won't implement it , also nvchad already has 4 chad themes. Tools a lot of time to make em . Since their original themes don't look that good I had to change many colors for syntax highlighting and  26~ colors for rest of the highlights. If I added the highlight stuff in theme base16 theme plugin itself then it gets hard for the user to write his own highlights so better add the user highlights and those user highlights shall get commented in the theme plugin like vertsplit highlight etc so stuff won't highlight twice.

**Comment by Akianonymus** [comment]
> > @siduck76 Theming in general is a pain in nvchad, first all it should be imported as a colorscheme that neovim recognises.
> 
> I have thought about it but won't implement it , also nvchad already has 4 chad themes. Tools a lot of time to make em . Since their original themes don't look that good I had to change many colors for syntax highlighting and 26~ colors for rest of the highlights. If I added the highlight stuff in theme base16 theme plugin itself then it gets hard for the user to write his own highlights so better add the user highlights and those user highlights shall get commented in the theme plugin like vertsplit highlight etc so stuff won't highlight twice.

I don't understand, how are these reasons relavant to making a colorscheme recognised by nvim ? 🤔

**Comment by siduck76** [comment]
Doesn't nvim recognize base16 plugin?

**Comment by Akianonymus** [comment]
> Doesn't nvim recognize base16 plugin?
 
Try `:Telescope colorscheme`

That's what i was talking about

**Comment by siduck76** [comment]
> > Doesn't nvim recognize base16 plugin?
> 
> Try `:Telescope colorscheme`
> 
> That's what i was talking about

Ohh that stuff , why not make our own theme switcher with telescope?

**Comment by Akianonymus** [comment]
> > > Doesn't nvim recognize base16 plugin?
> > 
> > 
> > Try `:Telescope colorscheme`
> > That's what i was talking about
> 
> Ohh that stuff , why not make the theme switcher with telescope? Like letting it execute certain stuffs for changing nvchad bsse16 and nvchad global theme

Ohh, you mean a custom implementation which will show just our themes

**Comment by ashincoder** [comment]
Will that be that easy. You may have to write a function to implement it

**Comment by siduck76** [comment]
> Will that be that easy. You may have to write a function to implement it

PR's are welcome :D

**Comment by siduck76** [comment]
Im noob with telescope so it'd be hard for me at the moment xd

**Comment by siduck76** [comment]
also the telescope window should have all 4 nvchad themes 

 selecting a theme and pressing enter on it should execute : 
 
- change vim.g.nvchad_theme first 
- require the highlights.lua file

**Comment by Akianonymus** [comment]
> also the telescope window should have all 4 nvchad themes
> 
> selecting a theme and pressing enter on it should execute :
> 
> * change vim.g.nvchad_theme first
> * require the highlights.lua file

requiring the highlights won't be enough, you have to reload bufferline and statusline before too

**Comment by siduck76** [comment]
> > also the telescope window should have all 4 nvchad themes
> > selecting a theme and pressing enter on it should execute :
> > 
> > * change vim.g.nvchad_theme first
> > * require the highlights.lua file
> 
> requiring the highlights won't be enough, you have to reload bufferline and statusline before too

oh shit yes and even webdevicons too

**Comment by Akianonymus** [comment]
> > > also the telescope window should have all 4 nvchad themes
> > > selecting a theme and pressing enter on it should execute :
> > > 
> > > * change vim.g.nvchad_theme first
> > > * require the highlights.lua file
> > 
> > 
> > requiring the highlights won't be enough, you have to reload bufferline and statusline before too
> 
> oh shit yes and even webdevicons too

or source $MYVIMRC

probably will work

**Comment by G-Rowell** [comment]
I mean, 
a fair few neovim & plugin settings can be overwritten by a user config file?

Eg:
Normal NvChad setup & config structure
THE LAST thing that is done is source custom.lua   (`require custom.setup()`) 
custom.lua is an NvChad provided file in which config is overridden to the users preferred

**Comment by G-Rowell** [comment]
I don't know if this approach is perfect, but it could well work,
as it keeps all the NvChad settings,

and the user only has in their config file their preferences (only have to include specific settings they want to change?)

**Comment by G-Rowell** [comment]
Very easy to implement:
make `custom.lua`, give it the boilerplate lua format & some comments,
add `custom.lua` to `.gitignore`,
add the call to `custom.lua - config()` in `init.lua`
commit.


Means that this `custom.lua` stays in the repo, but the gitignore means it's touched by git when contributors work on pull requests? (so keeps users in NvChad, while keeping their own configs)

**Comment by G-Rowell** [comment]
Implemented a working prototype:

https://github.com/siduck76/NvChad/pull/168

**Comment by siduck76** [comment]
@G-Rowell thanks for your work! I'll think about adding global option after 1.0v release so keep it on hold for a while :v

**Comment by Akianonymus** [comment]
Commenting here too for reference

How about adding a custom.sample.lua to repo, not custom.lua

But, we will originally use custom.lua only. A check will be added if custom.lua is present for error handling

custom.sample.lua will contain all the configuration which are change able without breaking with core nvchad setup.

By all configuration, i mean vim options( enable dashboard or not ), mappings, etc

The sample custom config will contain the values which are set in nvchad by default.

So, even if user renames custom.sample.lua to custom.lua, should get default configs and then they can start messing with it .

**Comment by siduck76** [comment]
> Commenting here too for reference ( sample comment in pr 168 )
> 
> How about adding a custom.sample.lua to repo, not custom.lua
> 
> But, we will originally use custom.lua only. A check will be added if custom.lua is present for error handling
> 
> custom.sample.lua will contain all the configuration which are change able without breaking with core nvchad setup.
> 
> By all configuration, i mean vim options( enable dashboard or not ), mappings, etc
> 
> The sample custom config will contain the values which are set in nvchad by default.
> 
> So, even if user renames custom.sample.lua to custom.lua, should get default configs and then they can start messing with it .

sounds cool! NvChad will be kinda initially complete after 1.0v so we'll add the custom.lua after it!

**Comment by G-Rowell** [comment]
Could also have a branch to test this functionality, 
so that it can plug right into 1.0v?

It could be a way to ease some load off of @siduck76, have two people be responsible for the branch/custom config,
then before merge to main have siduck check off?

Dunno, either way I'm chill

**Comment by siduck76** [comment]
> Could also have a branch to test this functionality,
> so that it can plug right into 1.0v?
> 
> It could be a way to ease some load off of @siduck76, have two people be responsible for the branch/custom config,
> then before merge to main have siduck check off?
> 
> Dunno, either way I'm chill

yeah sounds good! Im going to release 1.0v at this month's ending so gotta wait!  you can create a theme switcher in the meantime , next month I'll add a a different branch for the global config stuff :)

**Comment by ashincoder** [comment]
So who are you going to assign that branch to

**Comment by ashincoder** [comment]
Next month :0 ! I mean @G-Rowell idea was goood :)

**Comment by G-Rowell** [comment]
> Next month :0 ! I mean @G-Rowell idea was goood :)

Freaking zoomers with no patience :stuck_out_tongue_closed_eyes:

**Comment by siduck76** [comment]
> Next month :0 ! I mean @G-Rowell idea was goood :)

yeah I have college these days so such huge changes like global config would need some tinkering! so next month lul .

**Comment by siduck76** [comment]
> So who are you going to assign that branch to

Didnt think about assigning for now , anyone can add PR for global config in that different branch

**Comment by siduck76** [comment]
@Akianonymus join the gitter master!

**Comment by Akianonymus** [comment]
> @Akianonymus join the gitter community master!

Ooh, we have gitter community, will join

( just saw in readme )

**Comment by JustSage** [comment]
There's an issue with vim.g.theme being recognized in icons.lua ...
It works in highlights.lua , but returns nil in icons.lua .. a very odd behavior :/

**Comment by Pocco81** [comment]
So I've achieved full config capacity from one single file ~~and also better modularization (structured like one unix systems boot), better lsp conf, better utils, etc... but that is not relevant to this issue~~ [in my fork](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/tree/dev-mnc/.config/nvim). Take a look: 

https://user-images.githubusercontent.com/58336662/126726127-8740ed7a-c112-4930-a82a-65393df73574.mp4

**Comment by siduck76** [comment]
I think we can soon implement this after 1.0v or before 1.0 itself xD.

but one thing Im sure , I wont add theme color tables in the global config at all!

**Comment by siduck76** [comment]
also stuffs like this wont be added :

![image](https://user-images.githubusercontent.com/59060246/126726638-4775d9b3-e917-456c-a8fb-49e618f548ef.png)


since they're not present in nvchad's config itself xD. would be nice not to add each and every nvim's default options

**Comment by Pocco81** [comment]
As I said, this is my personal config so that's why I have so many settings and stuff (which if I'm not wrong they are not the defaults).

Also, there are some things like, for instance, autocommands that depend on plugins that *should* not be in the main config file but in the plugins' conf (for obvious reasons)

With that said, I'd be more than happy to help in the development of this feature :)

**Comment by siduck76** [comment]
> As I said, this is my personal config so that's why I have so many settings and stuff (which (if I'm not wrong) are not the defaults).
> 
> Also, there are some things like, for instance, autocommands that depend on plugins that _should_ not be in the main config file but in the plugins' conf (for obvious reasons)
> 
> With that said, I'd be more than happy to help in the development of this feature :)

yeah cool :)

**Comment by siduck76** [comment]
I never wanted to have a global config.lua for nvchad , thought it added unneeded complexity and bloat but seeing your config gives me some hope :D

**Comment by siduck76** [comment]
@ceylog https://github.com/siduck76/NvChad/commit/0efa21c9c987c10ef9ccb572ab268d85d308060b

**Comment by ashincoder** [comment]
@siduck76 do u think on adding orgmode.nvim

**Comment by siduck76** [comment]
> @siduck76 do u think on adding orgmode.nvim

yes in 2.0v

**Comment by ashincoder** [comment]
ok

**Comment by Anonysus69** [comment]
Shouldn't this be closed.user config is implemented and we can update.pocco is working on something to update.but we can do updates now using git pull and nvim +Packersync

**Comment by siduck76** [comment]
> Shouldn't this be closed.user config is implemented and we can update.pocco is working on something to update.but we can do updates now using git pull and nvim +Packersync

yes I'll close this when the update command is added to new docs ( site ) , Aki is working on a updater.lua so gotta wait

**Comment by siduck76** [comment]
https://nvchad.netlify.app/docs/getting%20started/setup/#update
