### ISSUE TITLE
Icons do not appear 

### ISSUE THREAD

**Issue by jegasape** [NvChad/NvChad#680]
**Describe the bug**
After the container is created and all the dependencies installed, the icons do not appear in the editor

**To Reproduce**

>   docker run -w /root -it --rm alpine:edge sh -uelic '
>     apk add git nodejs neovim ripgrep alpine-sdk --update
>     git clone https://github.com/NvChad/NvChad ~/.config/nvim
>     nvim -c "autocmd User PackerComplete quitall" -c "PackerSync"
>     nvim'
> 

**Expected behavior**
It is expected that after the configurations have been installed, all the elements should appear.

**Screenshots**

![issue](https://user-images.githubusercontent.com/44595343/147398560-1f541c0c-9082-4a6c-a3c1-76b6cc504f72.png)

**Desktop (please complete the following information):**
 - Operating System
![2](https://user-images.githubusercontent.com/44595343/147398437-ac78b341-0f94-4afd-bfdf-10cc50738f60.png)

 - Terminal 
  **/bin/sh**
 
 - Version of Neovim
 ![Screenshot from 2021-12-25 23-53-41](https://user-images.githubusercontent.com/44595343/147398451-ad2faa4c-51b6-4455-85bb-71e76adda4cc.png)

**Additional context**
N/A.

**Comment by bryant-the-coder** [comment]
at the moment i think nvimtree is buggy so it is not related to NvChad. The contributors are finding a way to solve this problem at the moment. I am not the contributor but a guy who joins the discord group :))

**Comment by siduck** [comment]
Use a nerd font in your terminal , this is your terminal's issue

**Comment by hawkinchina** [comment]
in nvchad tabline and status line, the icons are not displaying properly,  but the nvim tree  is ok.

**Comment by siduck** [comment]
> in nvchad tabline and status line, the icons are not displaying properly, but the nvim tree is ok.

enable it in terminal

**Comment by hawkinchina** [comment]
I run the neovim  in the docker (alpine linux), so i do not use any terminal emulator, just setting in the init.lua:  vim.opt.guifont="Hack Nerd Font:h12" .    it donot like iterm2 in the macos,  changing iterm2 ->preferences -->profiles -->text -> font:  JetBrainsMonos Nerd Font.  
1), I test the nvChad.Ui tabline: just like modules.lua (lines 97-99):
`local new_tabtn = btn(" 󰐕 ", "TabNewBtn", "NewTab")
local small_btn = btn(" 󰅁 ", "TabTitle", "ToggleTabs")
local closeAllBufs = btn(" 󰅖 ", "CloseAllBufsBtn", "CloseAllBufs")
`
these icons cannot display.  but I can change these to the icons  i can see in the alpine linux. but it bored me so much.

**Comment by hawkinchina** [comment]
or. NvChad can export all these icons so that i can change it in the init.lua.

**Comment by siduck** [comment]
> vim.opt.guifont="Hack Nerd Font:h12"

please try with another terminal like ghostty etc. i have seen many issues with iterm2
