### ISSUE TITLE
Telescope find_files should ignore files in .gitignore by default

### ISSUE THREAD

**Issue by RKBethke** [NvChad/NvChad#682]
**Is your feature request related to a problem? Please describe.**
When searching for files with Telescope `find_files` (`<space>ff`), all files within the current directory are returned- including those described in the .gitignore file.  For repositories that create a large number of build files, searches take a large amount of time and return useless files. 

**Describe the solution you'd like**
Removing the `no_ignore=true` flag from the Telescope find_files command results in the expected behavior.  This can be added to the `find_hiddenfiles` command for a single exhaustive search option. 

**Describe alternatives you've considered**
If the current behavior is deemed correct, this could be exposed as an option to the user.

**Comment by siduck** [comment]
i had added no_ignore=true since the custom folder is gitignored and it wasnt shown in the telescope :/

**Comment by peppapig450** [comment]
I think this shouldn't be an option by default because often times I still work on files that are .gitignored and it helps being able to open them using telescope.

**Comment by RKBethke** [comment]
> I think this shouldn't be an option by default because often times I still work on files that are .gitignored and it helps being able to open them using telescope.

With the linked PR one could still use `find_hiddenfiles` to search for those .gitignored files

**Comment by divan** [comment]
I've reinstalled NvChad from scratch last week and use default configuration.

While working on custom/ configs I often want to use Telescope live grep or find files feature, but custom/ is gitignored and doesn't appear in search. I understand that somehow I can include gitignored files into search, but I don't want to enable this for all repos. 

Is is possible to enable only for NvChad config directory? Or maybe there is another solution to this?
