### ISSUE TITLE
Why dashboard wont open firstly? 

### ISSUE THREAD

**Issue by Ruixi-rebirth** [NvChad/NvChad#685]
![image](https://user-images.githubusercontent.com/75824585/147534298-5b58369c-9149-451b-863c-62e58b1e8e30.png)

**Comment by siduck** [comment]
Enable it in chadrc

**Comment by siduck** [comment]
![Uploading Screenshot_20211228-122350_DuckDuckGo.jpg…]()

**Comment by Ruixi-rebirth** [comment]
ok,thank you!
