### ISSUE TITLE
unmap key bindings

### ISSUE THREAD

**Issue by yonchicy** [NvChad/NvChad#690]
I want to unmap \<c-a\>. I read the docs but didn't the ways doing this.

**Comment by siduck** [comment]
> I want to unmap <c-a>. I read the docs but didn't the ways doing this.


to unmap that key , should see where its used . check default_config and make its change in chadrc

![image](https://user-images.githubusercontent.com/59060246/147682966-807701cb-0aab-43b7-b324-e10adbbfe6f9.png)
