### ISSUE TITLE
Why doesn't it take up the entire terminal

### ISSUE THREAD

**Issue by Ruixi-rebirth** [NvChad/NvChad#692]
My terminal is alacritty
There will be gaps on the right and below
![image](https://user-images.githubusercontent.com/75824585/147723056-3f705081-1fe9-4a08-bf1d-045eb4c87944.png)

**Comment by siduck** [comment]
St terminal?

**Comment by Ruixi-rebirth** [comment]
Alacritty

**Comment by siduck** [comment]
Does this happen with default nvim?

**Comment by Ruixi-rebirth** [comment]
The default neovim does not have such a situation

**Comment by Ruixi-rebirth** [comment]
![image](https://user-images.githubusercontent.com/75824585/147723765-c91ec07c-b76b-4553-8944-ba2dc1b0c062.png)
The above is the default

**Comment by GreatestOfAllTimee** [comment]
> ![image](https://user-images.githubusercontent.com/75824585/147723765-c91ec07c-b76b-4553-8944-ba2dc1b0c062.png)

Default nvim, you set background to transparent and nvim will follow your terminal colors. Try to enable transparency on  nvchad and see what happen.

**Comment by GreatestOfAllTimee** [comment]
For the right gap, setting your padding right on alacritty config file.

**Comment by Ruixi-rebirth** [comment]
![image](https://user-images.githubusercontent.com/75824585/147724195-c5dab10f-d6fa-4fba-9019-2086688610af.png)
I use picom to make the terminal transparent, it looks like this when I close it

**Comment by GreatestOfAllTimee** [comment]
> ![image](https://user-images.githubusercontent.com/75824585/147724195-c5dab10f-d6fa-4fba-9019-2086688610af.png) I use picom to make the terminal transparent, it looks like this when I close it

Can you see the difference ? Default Nvim had a same gap on the right and bottom. Terminal emulators draw their characters in a grid. The dimensions of each cell, and thus of the grid itself, are determined by your font. If those dimensions don't match those of your window then you will get gaps around the useful area.

So to solve this issue you may need to setting your padding right and bottom side on the Alacritty config file.

**Comment by GreatestOfAllTimee** [comment]
OR try to change your font style or font size and what happen. If you found a better solution it would be great to share here 😃

**Comment by Ruixi-rebirth** [comment]
The font I used is fire code. When I change it to another font, the gap on the right is gone, but there will still be a gap at the bottom. So it’s the font of my terminal, so which font is more suitable? Can you recommend it?

**Comment by GreatestOfAllTimee** [comment]
You need to find out. I have the same problem to, so I setting on the terminal config file.

**Comment by Ruixi-rebirth** [comment]
ok, thank you

**Comment by siduck** [comment]
> The font I used is fira code. When I change it to another font, the gap on the right is gone, but there will still be a gap at the bottom. So it’s the font of my terminal, so which font is more suitable? Can you recommend it?

Font in nvchad screenshots is jetbrainsmono nerd font , use that.
