### ISSUE TITLE
LSP key binding is not working

### ISSUE THREAD

**Issue by tanshunyuan** [NvChad/NvChad#693]
For some reason, my lsp config key binding does not work. I had to manually input most of the keybinding into `custom/init.lua`. I have included the following in my `.chadrc` and still lsp binding does not load.

```
M.plugins = {
   status = {
      dashboard = true,
   },
   lspconfig = {
      servers = { "html", "cssls" },
   },
   options = {
      nvimtree = {
         ui = {
            side = "right",
         },
      },
      lspconfig = {
         setup_lspconf = "custom.plugins.lsp.lspconfig",
      },
   },
}
```
Here's a [link](https://github.com/tanshunyuan/dotfiles/blob/even-unstable/config/nvim/lua/custom/chadrc.lua) to my nvim dot file

**Comment by siduck** [comment]
Lspconfig table no longer has the servers table , update your nvchad config and check the lsp stuff section in our docs.

**Comment by tanshunyuan** [comment]
nvim version: `NVIM v0.6.0`

I removed the table config from `custom/chadrc.lua` and followed the steps from [here](https://nvchad.github.io/config/Lsp%20stuff) but it still does not work. Am I doing something wrong here?

Here is my file structure under the custom folder
![image](https://user-images.githubusercontent.com/29978940/147748713-b6da93a4-01b2-4c57-ac9f-ead2a96a97c0.png)

Using [which-key](https://github.com/folke/which-key.nvim#:~:text=%F0%9F%92%A5%20Which%20Key-,WhichKey%20is%20a%20lua%20plugin%20for%20Neovim%200.5%20that%20displays,and%20vim%2Dwhich%2Dkey.) I still can't see lsp keybindings, for example formatting is `<leader>fm` and it is not showing up
![image](https://user-images.githubusercontent.com/29978940/147749367-51768465-6b3f-4aa5-b18b-dcdade56850c.png)

Here are the file contents
`custom/init.lua`
```lua
local hooks = require "core.hooks"

hooks.add("setup_mappings", function(map)
   map("n", "<leader>qq", ":q <CR>")
   map("n", "<leader>qQ", ":qa <CR>")
   map("n", "<C-S>", ":wa <CR>")
   map("n", "<C-\\>", ":vs <CR>")
end)

hooks.add("install_plugins", function(use)
   use {
      "mattn/emmet-vim",
      config = function()
         require("custom.plugins.emmet").config()
      end,
   }
   use {
      "williamboman/nvim-lsp-installer",
      config = function()
         require("custom.plugins.lsp.lsp-installer").setup_lsp()
      end,
   }
   use {
      "jose-elias-alvarez/null-ls.nvim",
      after = "nvim-lspconfig",
      config = function()
         require("custom.plugins.lsp.null-ls").setup()
      end,
   }
   use {
      "folke/which-key.nvim",
      config = function()
         require("which-key").setup()
      end,
   }
end)
```
`custom/chadrc.lua`
```lua
local M = {}
M.ui = {
   theme = "onedark",
}

M.plugins = {
   status = {
      dashboard = true,
   },
   options = {
      nvimtree = {
         ui = {
            side = "right",
         },
      },
      lspconfig = {
         setup_lspconf = "custom.plugins.lsp.lspconfig",
      },
   },
}

return M
```

`custom/plugins/lsp/lspconfig.lua`
```lua
local M = {}

M.setup_lsp = function(attach, capabilities)
   local lspconfig = require "lspconfig"
   local servers = { "html", "cssls", "pyright" }

   for _, lsp in ipairs(servers) do
      lspconfig[lsp].setup {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
      }
   end

   lspconfig.tsserver.setup {
      on_attach = function(client, bufnr)
         client.resolved_capabilities.document_formatting = false
         vim.api.nvim_buf_set_keymap(bufnr, "n", "<space>fm", "<cmd>lua vim.lsp.buf.formatting()<CR>", {})
      end,
   }
end

return M
```

`custom/plugins/lsp/lsp-installer.lua`
```lua
local M = {}

M.setup_lsp = function(attach, capabilities)
   local lsp_installer = require "nvim-lsp-installer"

   lsp_installer.on_server_ready(function(server)
      local opts = {
         on_attach = attach,
         capabilities = capabilities,
         flags = {
            debounce_text_changes = 150,
         },
         settings = {},
      }

      if server.name == "sumneko_lua" then
         local sumneko_opts = require "custom.plugins.lsp.settings.sumneko_lua"
         opts = vim.tbl_deep_extend("force", sumneko_opts, opts)
      end

      server:setup(opts)
      vim.cmd [[ do User LspAttachBuffers ]]
   end)
end

return M
```

**Comment by prurph** [comment]
The docs are kind of confusing.

What's happening now is you're calling `setup_lua` from your `lspconfig.lua` but note that does nothing with `nvim-lsp-installer`, only with `lspconfig`. Here's a super basic example:

```lua
-- init.lua
customPlugins.add(function(use)
   -- get rid of the config setting here (NvChad will handle this)
   use "williamboman/nvim-lsp-installer"
end)


-- chadrc.lua (no changes from what you have now)
local M = {}
M.ui = {
   theme = "onedark",
}

M.plugins = {
   options = {
      lspconfig = {
         setup_lspconf = "custom.plugins.lsp.lspconfig",
      },
   },
}

return M

-- custom/plugins/lsp/lspconfig.lua
local M = {}

M.setup_lsp = function(attach, capabilities)
    require("nvim-lsp-installer").on_server_ready(function(server)
    local opts = {
      on_attach = attach,
      capabilities = capabilities
    }
    server:setup(opts)
  end)
end

return M
```

In this scenario get rid of your custom `lsp-installer.lua`; it's not doing anything.

**Comment by siduck** [comment]
@Akianonymus if the user has come across the lsp docs then he mustve read how to install plugins etc stuff so no need to use the customPlugins function and the docs have been updated regarding lspinstaller

https://nvchad.github.io/config/Lsp%20stuff#basic-config

**Comment by prurph** [comment]
Yeah, OP is mixing up both the basic lspconfig setup and the nvim-lsp-installer setup.

**Comment by tanshunyuan** [comment]
Thanks a lot @prurph for the explanation, I'll try to fix it and update back on this in about a week or two!
