### ISSUE TITLE
NvChad always override `whichwrap` in `init.lua`

### ISSUE THREAD

**Issue by yifeikong** [NvChad/NvChad#694]
**Describe the bug**
NvChad has this settings: `opt.whichwrap:append "<>[]hl"` in `lua/core/options.lua`. I want to reset this setting to the default value, so I added `vim.opt.whichwrap = 'b,s'` in my `lua/custom/init.lua`, but it does not work. It seems that `init.lua` is run before the `options.lua` kicks in.

Then I try to override this in `chadrc.lua`, but It also does not work.

**Expected behavior**
I can override the default settings.

**Desktop (please complete the following information):**
 - macOS
 - Iterm2 + tux
 - vim 0.6.0

**Comment by yifeikong** [comment]
> How did you override it in chadrc?

Actually, I didn't, because I could not figure out where to add it.

**Comment by siduck** [comment]
@yifeikong can you load custom's init.lua at the last?

move the first 2 lines at the last 

![image](https://user-images.githubusercontent.com/59060246/148420143-b5a02b12-14d1-4a1d-9432-d576f990dbe4.png)


lemme know if this works

**Comment by yifeikong** [comment]
@siduck it works as expected. Thanks.

**Comment by siduck** [comment]
> @siduck it works as expected. Thanks.

just confirming! so loading custom/init.lua at the last ( in main init.lua ) fixes your issue right? if yes then i will make this change on the repo

**Comment by yifeikong** [comment]
> > @siduck it works as expected. Thanks.
> 
> just confirming! so loading custom/init.lua at the last ( in main init.lua ) fixes your issue right? if yes then i will make this change on the repo

Yes.
