### ISSUE TITLE
Modifying the default keyboard mapping does not take effect

### ISSUE THREAD

**Issue by Ruixi-rebirth** [NvChad/NvChad#695]
![image](https://user-images.githubusercontent.com/75824585/147810249-10b59dad-18c8-4a5d-a63b-e24c498f1b46.png)

**Comment by siduck** [comment]
Just won't work , I think it's use by skme default mapping or such, try <C-t>t

**Comment by Ruixi-rebirth** [comment]
![image](https://user-images.githubusercontent.com/75824585/147813859-9b867d6b-99ae-47ac-bfee-b639f3e14df9.png)
After I tried to modify the default keyboard mapping like this, when I PackerSync, the above situation will appear

**Comment by Ruixi-rebirth** [comment]
I reconfigured from scratch, and I found that once I modified the default keyboard mapping in chadrc. The configuration in this file is invalid, and the default will be restored. Isn't it possible to overwrite the keyboard mapping in default_config like I did?
![image](https://user-images.githubusercontent.com/75824585/147816949-89d37748-2822-414d-bf74-87d0b7e93488.png)

**Comment by siduck** [comment]
C-y worked for me , doesnt work for you?

**Comment by Ruixi-rebirth** [comment]
Ok, it worked, thank you
