### ISSUE TITLE
nvim-treesitter[vim]: Error during compilation

### ISSUE THREAD

**Issue by marbinuwusito** [NvChad/NvChad#697]
Can't install Tree Sitter

**To Reproduce**
1. Fresh instalation on windows platform

**Expected behavior**
install correctly tree sitter

**Screenshots**

Error:
![image](https://user-images.githubusercontent.com/72583007/147861312-59644b35-3dce-418d-a28e-ed1b68f28f15.png)

:checkhealt nvim_treesitter
![image](https://user-images.githubusercontent.com/72583007/147861334-850f8175-fb17-4984-a576-243fcd423f3a.png)

neovim version

![image](https://user-images.githubusercontent.com/72583007/147861342-1708770b-f9c1-4ca9-8997-b34972915fdd.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Windows Terminal

**Comment by peppapig450** [comment]
Maybe something to do with this?
https://stackoverflow.com/a/56801275/17520245

**Comment by GreatestOfAllTimee** [comment]
I think this issue is from Tree-Sitter itself. See [#2135](https://github.com/nvim-treesitter/nvim-treesitter/issues/2135#issue-1083857653)

**Comment by peppapig450** [comment]
this too 
https://github.com/nvim-treesitter/nvim-treesitter/issues/2152

**Comment by siduck** [comment]
not a nvchad issue!
