### ISSUE TITLE
words im typing arent showing up right

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#698]
**Describe the bug**
Im trying to type basename and very weird things are happening 

**To Reproduce**
1. enter insert mode
2. try to type
3. strange things happen

**Expected behavior**
To be able to type basename 

**Screenshots**

https://user-images.githubusercontent.com/55930078/147866290-9feed1a7-1aac-4ecc-b873-b554e4d4cb17.mov

**Desktop (please complete the following information):**
 - macOS
 - kitty
 - 0.6.1
 
**Additional context**
My guess would be that this is related to the lsp maybe?

**Comment by siduck** [comment]
can you try 0.6?

**Comment by peppapig450** [comment]
lemme try to build from source

**Comment by peppapig450** [comment]
I'm very confused now because it isnt happening at all 😐

**Comment by peppapig450** [comment]
I think it was null-ls

**Comment by peppapig450** [comment]
Well it works now so i'll close this ig

**Comment by siduck** [comment]
> I think it was null-ls

i doubt! probably 0.6.1

**Comment by peppapig450** [comment]
0.6.1 was working fine until i re-enabled null-ls earlier

**Comment by siduck** [comment]
> 0.6.1 was working fine until i re-enabled null-ls earlier

does this issue happen with 0.6?

**Comment by tanshunyuan** [comment]
So is the issue `null-ls`? Because I am facing the same issue too or maybe it's the terminal itself 🤷🏽

**Comment by siduck** [comment]
> So is the issue `null-ls`? Because I am facing the same issue too or maybe it's the terminal itself 🤷🏽

does this happen with 0.6?

**Comment by tanshunyuan** [comment]
Yes it does happen with nvim 0.6

**Comment by siduck** [comment]
> Yes it does happen with nvim 0.6

weird , im not able to reproduce this error!

**Comment by peppapig450** [comment]
yeah this is null-ls, and it only happens in .sh files so its shellcheck 
```lua
  -- Shell
  b.formatting.shfmt,
  b.diagnostics.shellcheck.with { diagnostics_format = "#{m} [#{c}]" },
```
