### ISSUE TITLE
Default LSP key mappings don't work

### ISSUE THREAD

**Issue by bradleyburgess** [NvChad/NvChad#701]
I did a fresh install of NvChad, and love everything about it... except that the default key mappings for the LSP actions don't work.

I copied the `lspconfig` bindings to my `custom/init.lua` and replaced every `<cmd>lua ...` with `:lua ...`, and it seems to work now.

**Comment by siduck** [comment]
> I did a fresh install of NvChad, and love everything about it... except that the default key mappings for the LSP actions don't work.
> 
> I copied the `lspconfig` bindings to my `custom/init.lua` and replaced every `<cmd>lua ...` with `:lua ...`, and it seems to work now.

do you use lsp installer?

**Comment by siduck** [comment]
also you need a custom lspconfig file i think , check my nvchad custom folder 

https://github.com/siduck/dotfiles/tree/master/nvchad/custom
