### ISSUE TITLE
External Syntax Check?

### ISSUE THREAD

**Issue by erwin** [NvChad/NvChad#704]
# **Is your feature request related to a problem? Please describe.**

The biggest downside I've noticed with the neovim Lua based config system generally and using NvChad in particular is the fragility of the config file.

Since NvChad really just encourages the user to put config changes in `lua/custom` perhaps only those files need to be scanned...

Would just be very helpful when there's a parsing error to some information about what has gone wrong rather than just having nvim start behaving strangely...

# **Describe the solution you'd like**

Ideally I would like an external script or even a command line switch akin to `apachectl -S` that would check the syntax of the included config files, especially the ones under `lua/custom` and give a Line Number if a syntax error was found, and report an `OK` if no syntax errors were found.

Even more ideally, it would run fast and be connected by default to saving the init.lua similar to the way `visudo` doesn't let you save errors in the sudoers file syntax.

* Even if this process ran very slowly, it would still be so helpful to me.

* Maybe something along these lines already exists and I've just missed it somehow.

* Maybe this is a neovim issue rather than an NvChad issue.

I think Lua based config is a genius move... I just wish we had some good error messages, especially for `./lua/custom/init.lua`

**Comment by peppapig450** [comment]
Maybe you could use this as a standalone binary? https://github.com/sumneko/lua-language-server

**Comment by peppapig450** [comment]
I think this might also be because lua is dynamically typed.

**Comment by Akianonymus** [comment]
@erwin 
> # **Is your feature request related to a problem? Please describe.**
> The biggest downside I've noticed with the neovim Lua based config system generally and using NvChad in particular is the fragility of the config file.
> 
> Since NvChad really just encourages the user to put config changes in `lua/custom` perhaps only those files need to be scanned...
> 
> Would just be very helpful when there's a parsing error to some information about what has gone wrong rather than just having nvim start behaving strangely...
> 
Where are you not getting the messages ? point out some

> I think Lua based config is a genius move... I just wish we had some good error messages, especially for `./lua/custom/init.lua`
Currently it doesn't crash the whole config if malformed custom/init.lua, but doesn't show error. Will fix that.

**Comment by Akianonymus** [comment]
Also, i get your whole idea, the best way to check a lua file syntax is by using the `luac` program.

```shell
luac -p init.lua
```
If it succeeds, then it's fine, otherwise not.

**Comment by siduck** [comment]
> Maybe you could use this as a standalone binary? https://github.com/sumneko/lua-language-server

@erwin to get precise error or  luac as aki mentioned
