### ISSUE TITLE
add night-owl theme

### ISSUE THREAD

**Issue by brianmoran** [NvChad/NvChad#705]
Examples:

https://github.com/bluz71/vim-nightfly-guicolors
or
https://github.com/Julpikar/night-owl.nvim

**Comment by free-150** [comment]
add 𝐄𝐝𝐠𝐞 theme
https://github.com/sainnhe/edge
![image](https://user-images.githubusercontent.com/92285544/149152751-8dda3939-6831-4639-b807-093d374fe073.png)

**Comment by siduck** [comment]
onelight is enough
