### ISSUE TITLE
Catppuccin theme for NvChad

### ISSUE THREAD

**Issue by AlphaTechnolog** [NvChad/NvChad#706]
**Is your feature request related to a problem? Please describe.**
I really love NvChad, but I love too the [catppuccin](https://github.com/catppuccin/catppuccin) theme

**Describe the solution you'd like**
Create a theme for NvChad and call it `catppuccin` in the NvChad theme selector

**Describe alternatives you've considered**
I am using the onedark theme with NvChad, because `catppuccin` doesn't exists in NvChad, and I cannot install it

**Additional context**
In days back I found this [repository](https://github.com/catppuccin/catppuccin) that shows a color palette for a theme called catppuccin and then I go to this [repository](https://github.com/catppuccin/catppuccin) that is the integration of the catppuccin palette for neovim, it's writted in lua, I really want to have it disponible for NvChad

**Screenshot**
I have my own neovim config, where I include it theme, a screenshot of it is this:
![catppuccin](https://user-images.githubusercontent.com/54639968/148140344-202b8fd7-6713-48ed-a46d-9d68f79c5d6a.png)

**Comment by peppapig450** [comment]
freebsd 👀

**Comment by siduck** [comment]
i dont think you followed our theme contributing guide :(

**Comment by siduck** [comment]
https://nvchad.github.io/contribute#how-to-submit-themes

**Comment by AlphaTechnolog** [comment]
> i dont think you followed our theme contributing guide :(

I don't create the catppuccin theme for NvChad, I am requesting and suggesting an idea of a new theme for NvChad

**Comment by AlphaTechnolog** [comment]
I love catppuccin theme, but I not know how to port it to NvChad...

**Comment by siduck** [comment]
> > i dont think you followed our theme contributing guide :(
> 
> I don't create the catppuccin theme for NvChad, I am suggesting an idea of a new theme for NvChad

oh my bad, i just woke up and checked this, thought it was the base16 repo! sorry i will make this theme myself in this month :D

**Comment by AlphaTechnolog** [comment]
xd, Thank you so much @siduck, I really love catppuccin and NvChad, it's a great combination

**Comment by siduck** [comment]
added it yesterday! 

https://i.redd.it/t1pvmqlq3oc81.png

**Comment by AlphaTechnolog** [comment]
I love It!! Thank you so much @siduck

**Comment by AlphaTechnolog** [comment]
Really cool setup!

**Comment by slashtechno** [comment]
Is it possible to select a specific Catppuccin flavor?  
From the [catppuccin/nvim](https://github.com/catppuccin/nvim) [README](https://github.com/catppuccin/nvim#usage):   
> ```vim
> colorscheme catppuccin " catppuccin-latte, catppuccin-frappe, catppuccin-macchiato, catppuccin-mocha
> ```  
> ```lua
> vim.cmd.colorscheme "catppuccin"
> ```

However, I'm unsure how to accomplish this in NvChad as it seems `:colorscheme` is separate from the NvChad theme picker (`<leader> + t + h`)

**Comment by siduck** [comment]
@slashtechno no, and no catpuccin variants will be added. our catpuccin is way different than the original one too. I can add thousands of other themes but not catpuccin, i refuse to elaborate

**Comment by slashtechno** [comment]
> @slashtechno no, and no catpuccin variants will be added. our catpuccin is way different than the original one too. I can add thousands of other themes but not catpuccin, i refuse to elaborate

Can I use Neovim's `colorscheme` system or do I have to use Base46?

**Comment by siduck** [comment]
@slashtechno in nvchad you cant use other themes, so only base46

**Comment by mainrs** [comment]
> @slashtechno no, and no catpuccin variants will be added. our catpuccin is way different than the original one too. I can add thousands of other themes but not catpuccin, i refuse to elaborate

Could you please explain what is so different and why porting is so hard? I tried enabling the `latte` flavour but the nvim-tree for example is not styled as well as the status bar. They are kept in the dark theme variant.

**Comment by mainrs** [comment]
> @mainrs catpuccin porting is not hard, infact its easy for me. I can add thousands of themes, but I will not port catpuccuin themes no matter what. I refuse to elaborate.

Ahhh, I understand you. I misunderstood you before, sorry! I found how themes work and how to make a custom one on the webpage! 

Thank you for the hard work on nvchad!
