### ISSUE TITLE
Lsp rename doesn't work.

### ISSUE THREAD

**Issue by NeoDrags** [NvChad/NvChad#707]
According to the documentation and the plugin mappings it states that for lsp rename it says leader + rn as in the picture below, but it is not working as intended.
![image](https://user-images.githubusercontent.com/60562379/148153601-e842afd9-7317-465d-b92d-927c0235c8fb.png)
****

**Comment by siduck** [comment]
Is your nvchad config up to date?  And which nvim version

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/148240700-66478ef7-0e4b-46e2-a6bb-6bb11fd03b32.mp4

works here :/

**Comment by thiago-buarqque** [comment]
@siduck I liked the UI in the video. How can I setup something similar? Not talking about the nvchad UI though, but the one you clicked to record and all of that
