### ISSUE TITLE
`ready`hook does not seem to be called anymore

### ISSUE THREAD

**Issue by hunger** [NvChad/NvChad#708]
**Describe the bug**
I have some code wired up to the "ready" hook. The hook is accepted, but the code does not seem to be run ever.

**To Reproduce**
Add this code to your `custom/init.lua` file:

```lua
local hooks = require "core.hooks"

hooks.add("ready", function()
    vim.wo.colorcolumn = '10,20,30,40,50,60,70,80,90,100'
end)
```

Start nvim and open a file. No color columns in sight:-/

**Expected behavior**

Way too many color columns

**Desktop (please complete the following information):**
 - Linux
 - Kitty 0.24.0
 - neovim 0.6.1

**Comment by siduck** [comment]
The way you're using ready hook isn't really correct,  please read our docs. You don't even need to use that hook :/

**Comment by hunger** [comment]
That is just an example:-)

I started using that hook to actually bind together a whole bunch of plugins. I kind of used this hook as a "all plugins loaded" hook. That was easier than configuring packer correctly.

**Comment by siduck** [comment]
> That is just an example:-)
> 
> I started using that hook to actually bind together a whole bunch of plugins. I kind of used this hook as a "all plugins loaded" hook. That was easier than configuring packer correctly.

I dont get you, the install_plugins hooks is needed for packer stuff

https://github.com/siduck/dotfiles/blob/master/nvchad/custom/plugins/init.lua

**Comment by hunger** [comment]
I do install plugins in the install_plugins hook. I just added some code to actually make a bunch of plugins work together in the ready hook. That was easier to do than figuring out how to make Packer run the same code at the right time. I have fixed most of that in the meantime, but I still had a few commands in the ready hook.

I did define `local hooks = require "core.hooks"` somewhere before `hooks.add(...)`, I will update my original message to include that. The hook was run a couple of weeks ago and stopped in the meantime.

Why did you say I do not need that hook? Is there a more convenient way to run some of my code after NVChad is done?

**Comment by siduck** [comment]
> I do install plugins in the install_plugins hook. I just added some code to actually make a bunch of plugins work together in the ready hook. That was easier to do than figuring out how to make Packer run the same code at the right time. I have fixed most of that in the meantime, but I still had a few commands in the ready hook.
> 
> I did define `local hooks = require "core.hooks"` somewhere before `hooks.add(...)`, I will update my original message to include that. The hook was run a couple of weeks ago and stopped in the meantime.
> 
> Why did you say I do not need that hook? Is there a more convenient way to run some of my code after NVChad is done?

that hook was removed few months ago so i dont think it will work! also put your stuff at the last line in custom/init.lua

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/694#issuecomment-1006746815

**Comment by hunger** [comment]
Oh, the hook is gone? You might want to remove this line then: https://github.com/NvChad/NvChad/blob/16d035c031c5c4420925551cfa67bb4f39fe1947/lua/core/hooks.lua#L6

OK, closing the ticket then.

And sorry for taking so much of your time!

**Comment by siduck** [comment]
> Oh, the hook is gone? You might want to remove this line then:
> 
> https://github.com/NvChad/NvChad/blob/16d035c031c5c4420925551cfa67bb4f39fe1947/lua/core/hooks.lua#L6
> 
> OK, closing the ticket then.
> 
> And sorry for taking so much of your time!

oh yea sorry for that! btw check the issue link i sent. if that works then you can load stuff after everything loads
