### ISSUE TITLE
Unable to to select anything with telescope

### ISSUE THREAD

**Issue by typkrft** [NvChad/NvChad#711]
**Describe the bug**
On a fresh install, with no custom lua I am unable to open any telescope finder and select a file. 

**To Reproduce**
1. Open nvim
2. `space ff`
3. type in search
4. use arrow keys to select match

**Expected behavior**
This was working in the past. 

**Screenshots**
![ezgif-2-f17a5dc190](https://user-images.githubusercontent.com/12100960/148321874-304e463a-761d-4e2d-a96d-f1e9af78f804.gif) 

**Desktop (please complete the following information):**
 - Operating System: macOS 12.1 (21C52)
 - Terminal: Kitty 0.24.0
 - Version of Neovim NVIM v0.6.1 Build type: Release

** Additional Context
Doesn't appear to be a highlighting error or anything regarding theming. If I hit return it will always select the first match.

Edit:
Looks like a breaking change in telescope, though I'm not exactly sure what to fix. Pinning an older, not specific, commit (99aa102b384305311308ff573b6790fa53366e10) resolves this. 

Edit: Looks like the latest commit f285599440fcdbf97a7f44d120d403c80316f576 broke it for me.

**Comment by vic-gfuentes** [comment]
Facing the same issue here

**Comment by Littlesharkcug** [comment]
I am also facing the same issue

**Comment by siduck** [comment]
seems like the latest commits from telescope has messed up with it. I cant find it out either

**Comment by siduck** [comment]
it'll get fixed soon 

https://github.com/nvim-telescope/telescope.nvim/pull/1660/files
