### ISSUE TITLE
Change word problem while typing

### ISSUE THREAD

**Issue by angkosal** [NvChad/NvChad#712]
**Describe the bug**
When I press `cw` change word and type some words

**Screenshots**

On `cw` typing
![image](https://user-images.githubusercontent.com/15922367/148325345-38c708ab-cd55-4459-b6a7-f748ad13cf87.png)

After escape
![image](https://user-images.githubusercontent.com/15922367/148325453-15f84884-d24f-449b-82c7-314e438eabaf.png)

**Desktop:**
 - Operating System (Windows 11 pro)
 - Terminal (Windows Terminal for wsl)
 - Version of Neovim (NVIM v0.6.0)

**Comment by GreatestOfAllTimee** [comment]
I'm not quite understand what are the issue is. Pls describe with a more details.

**Comment by omida86** [comment]
Are you using eslint with null-ls?

**Comment by GreatestOfAllTimee** [comment]
Im using null-ls without eslint. It would be great if you provide a short video or gif.

**Comment by angkosal** [comment]
@GreatestOfAllTimee  Here the video, Sir.
When we typing that problem occur, but after I hit escape it will become correctly. 
https://user-images.githubusercontent.com/15922367/148376115-58d61a69-f16d-4403-b983-980667dd4163.mp4

**Comment by angkosal** [comment]
@omida86  yes, I am

**Comment by omida86** [comment]
@angkosal that's a bug with null-ls with diagnostics with eslint. Replace it with Nvim LSP eslint. See: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint

**Comment by GreatestOfAllTimee** [comment]
This is a duplicate #603 and I believe this issue also happen on [Pyright](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#pyright) and [Rust_analyzer](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rust_analyzer).

**Comment by abalmos** [comment]
I believe this is a neovim issue. It can easily be worked around for now: https://github.com/NvChad/NvChad/issues/603#issuecomment-974751993

**Comment by siduck** [comment]
> I believe this is a neovim issue. It can easily be worked around for now: [#603 (comment)](https://github.com/NvChad/NvChad/issues/603#issuecomment-974751993)

does this happen with nvim-lsp's eslint config ( try without null-ls )

**Comment by angkosal** [comment]
@omida86 @GreatestOfAllTimee Thanks you for help.
