### ISSUE TITLE
the `setup_mappings`  not working at the lastest version

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#713]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
@tomasky use the map function 
![image](https://user-images.githubusercontent.com/59060246/148547135-6a890a4a-a113-400c-a767-c97627df709e.png)

i will remove the setup_mapping hooks soon
