### ISSUE TITLE
BREAKING CHANGE

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#714]
remove your hooks stuff (rename it) i have removed the hooks stuff since it was complex and most of it wasnt used fully. 

install plugins by 
```
local customPlugins = require "core.customPlugins"

customPlugins.add(function(use)
   use {
       "folke/which-key.nvim"
    }
 end)
```

mappings : 

```
local map = require("core.utils").map

map("n", "<leader>cc", ":Telescope <CR>")
 ```

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/blob/main/examples/init.lua

**Comment by hunger** [comment]
Congratulations: My setup runs even better than before;-)

**Comment by siduck** [comment]
@hunger offtopic! are you the founder of the Qt project or such? o_o

**Comment by hunger** [comment]
@siduck: offtopic! I did work on Qt (or more specific: Qt Creator) for a while -- long after it was founded though.

**Comment by MikaelElkiaer** [comment]
Would it be possible to keep a single pinned issue for breaking changes so that it can be watched?

**Comment by siduck** [comment]
> Would it be possible to keep a single pinned issue for breaking changes so that it can be watched?

done!

**Comment by MikaelElkiaer** [comment]
> > Would it be possible to keep a single pinned issue for breaking changes so that it can be watched?
> 
> done!

Very nice, thanks.

**Comment by siduck** [comment]
BREAKING CHANGE : After updating nvchad config, you wont see your statusline 

fix =  :PackerSync

**Comment by marvelman3284** [comment]
> BREAKING CHANGE : After updating nvchad config, you wont see your statusline
> 
> fix = :PackerSync

I cannot do :PackerSync

**Comment by siduck** [comment]
> > BREAKING CHANGE : After updating nvchad config, you wont see your statusline
> > fix = :PackerSync
> 
> I cannot do :PackerSync

when was the last time you updated whole nvchad :l

**Comment by marvelman3284** [comment]
> > > BREAKING CHANGE : After updating nvchad config, you wont see your statusline
> > > fix = :PackerSync
> > 
> > 
> > I cannot do :PackerSync
> 
> when was the last time you updated whole nvchad :l

a few min ago

**Comment by marvelman3284** [comment]
```E5108: Error executing lua ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:844: /home/marvel/.config/nvi
m/lua/core/customPlugins.lua:11: attempt to call local 'hook' (a string value)
stack traceback:
        [C]: in function 'error'
        ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:844: in function <...are/nvim/site/pack/packer/o
pt/packer.nvim/lua/packer.lua:811>
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk```
getting this error

**Comment by siduck** [comment]
i hope youre using 0.6.1v of nvim

**Comment by marvelman3284** [comment]
> i hope youre using 0.6.1v of nvim
```
nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
```

**Comment by siduck** [comment]
> remove your hooks stuff (rename it) since i have removed the hooks [4e54ee0](https://github.com/NvChad/NvChad/commit/4e54ee0081babd3138180bb61ea093fcac03fd46)
> 
> install plugins by
> 
> ```
> local customPlugins = require "core.customPlugins"
> 
> customPlugins.add(function(use)
>    use {
>        "folke/which-key.nvim"
>     }
>  end)
> ```
> 
> mappings :
> 
> ```
> local map = require("core.utils").map
> 
> map("n", "<leader>cc", ":Telescope <CR>")
> ```
> 
> DONT BE CONFUSED GUYS! you just need to replace some words i.e hooks related

seems like you didnt make this change :/

**Comment by marvelman3284** [comment]
> > remove your hooks stuff (rename it) since i have removed the hooks [4e54ee0](https://github.com/NvChad/NvChad/commit/4e54ee0081babd3138180bb61ea093fcac03fd46)
> > install plugins by
> > ```
> > local customPlugins = require "core.customPlugins"
> > 
> > customPlugins.add(function(use)
> >    use {
> >        "folke/which-key.nvim"
> >     }
> >  end)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mappings :
> > ```
> > local map = require("core.utils").map
> > 
> > map("n", "<leader>cc", ":Telescope <CR>")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > DONT BE CONFUSED GUYS! you just need to replace some words i.e hooks related
> 
> seems like you didnt make this change :/

I did :|
 
![image](https://user-images.githubusercontent.com/58921302/150660778-302f140e-b7c4-400a-b8ad-f3d83fd67140.png)
here is my custom/init.lua

**Comment by marvelman3284** [comment]
packer gives the same error as before

**Comment by siduck** [comment]
idk then!

**Comment by siduck** [comment]
anyways due to a recent forced commit, updating nvchad might not work (leader uu) so re-clone the repo and move your custom folder into it. do :PackerSync

**Comment by peppapig450** [comment]
:|
I dont have my old config so idk what to do now

**Comment by siduck** [comment]
> :| I dont have my old config so idk what to do now

why :l  . couldnt u back it up on git or locally. maybe just edit my custom conf 

https://github.com/siduck/dotfiles/tree/master/nvchad/custom

**Comment by MikaelElkiaer** [comment]
Hmm, someone ought to do a writeup on best practices on forking, making custom changes, and keeping the forked repo up-to-date. :)

**Comment by G-Rowell** [comment]
Hey @MikaelElkiaer 

I wrote this a long time ago, it is a little hidden though.

https://nvchad.github.io/contribute


Does this cover what you were thinking of?

**Comment by MikaelElkiaer** [comment]
> Hey @MikaelElkiaer
> 
> I wrote this a long time ago, it is a little hidden though.
> 
> https://nvchad.github.io/contribute
> 
> Does this cover what you were thinking of?

Yeah, that's pretty good. Good pro tips on rebase and stylua.

**Comment by G-Rowell** [comment]
Thank you!
Always appreciate feedback

We'll have to look into placing a web link in our README (or something else to help make that page more known)!

**Comment by siduck** [comment]
dashboard -> alpha-nvim migration 

https://github.com/NvChad/NvChad/issues/816

**Comment by peppapig450** [comment]
this changed your config over 😄

```shell
sed -i 's/dashboard/alpha/' ~/.config/nvim/lua/custom/chadrc.lua
```
