### ISSUE TITLE
How to change the default configuration in lua/plugins/packerInit.lua

### ISSUE THREAD

**Issue by Near2U0** [NvChad/NvChad#715]
I want to change the "default_url_format" in lua/plugins/packerInit.lua. How can I implement it in my own charc.lua or init.lua?

**Comment by Near2U0** [comment]
Some basic Git commands are:
```
packer.init {
    git = {
          default_url_format = 'https://hub.fastgit.org/%s',
   },
}
```

**Comment by siduck** [comment]
@Near2U0  https://github.com/NvChad/NvChad/blob/main/lua/core/default_config.lua#L76

**Comment by siduck** [comment]
> Help, same help.
just override packer.nvim's config, please read the docs regarding how to override plugin configs in nvchad
