### ISSUE TITLE
[bug] custom snippets are not displayed

### ISSUE THREAD

**Issue by nank1ro** [NvChad/NvChad#719]
**Describe the bug**
My custom snippets are not displayed.
I've followed the `friendly-snippets` structure with:
- my_snippets
    - snippets
      - flutter.json
    - package.json

Then I open a `.dart` file, and the snippets are never presented when typing in _INSERT_ mode.

Part of my `chadrc.lua` that is inside the __custom__ folder:
```lua
M.plugins = {
  ...
  options = {
    luasnip = {
       snippet_path = {
         "~/.config/nvim/lua/custom/my_snippets/"
       },
    },
  }
```

The `package.json` follows the style required:
```json
{
  "name": "snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": "dart",
        "path": "./snippets/flutter.json"
      },
    ]
  }
}
```

Part of the `flutter.json`:
```json
{
    "Stateless Widget": {
        "prefix": "stw",
        "body": [
            "class ${1:name} extends StatelessWidget {",
            "  const ${1:name}({Key? key}) : super(key: key);\n",
            "  @override",
            "  Widget build(BuildContext context) {",
            "    return Container();",
            "  }",
            "}"
        ],
        "description": "Create a Stateless widget"
    }
}
```

**Expected behavior**
To see the `dart` snippets when typing `st..`, etc.

**Desktop (please complete the following information):**
 - Operating System: MacOS Monterey 12.1
 - Terminal: iTerm 2
 - Version of Neovim: 0.6.1

**Comment by nank1ro** [comment]
For now inside the `plugins/configs/others.lua` I've added this line:
```lua
require("luasnip").filetype_extend("dart", {"flutter"})
```
After these lines of code:
```lua
require("luasnip/loaders/from_vscode").load { paths = chadrc_config.plugins.options.luasnip.snippet_path }
require("luasnip/loaders/from_vscode").load()
```

And I can finally see the `flutter` snippets from `friendly-snippets`
But the issue still happens, because my custom snippets are not loaded.

I don't know if this is an issue related with NvChad or LuaSnip

**Comment by siduck** [comment]
i dont wrok with snippets so im not sure if i can help with this , is the path of your snippets correct? did you do packer compile

**Comment by nank1ro** [comment]
Yes I run PackerCompile, the snippets path is correct, I've tried 10 times but nothing 😞

**Comment by siduck** [comment]
what happens when you just have 

```
require("luasnip/loaders/from_vscode").load { paths = chadrc_config.plugins.options.luasnip.snippet_path }
```

**Comment by nank1ro** [comment]
@siduck I've tried but still nothing

**Comment by siduck** [comment]
what happens when you load it after default snippets 
require("luasnip/loaders/from_vscode").load()
require("luasnip/loaders/from_vscode").load { paths = chadrc_config.plugins.options.luasnip.snippet_path }

**Comment by nank1ro** [comment]
The snippets from ` friendly-snippets` works, the custom one no.

**Comment by siduck** [comment]
@nank1ro  you can now change the default packer definition of a plugin https://nvchad.github.io/config/Custom%20config#remove--redefine-plugins so no need of the snippet path variable, Maybe thats bugged. if this works then i will remove that Or the issue might be with your snippets.

**Comment by nank1ro** [comment]
Sorry @siduck I didn't understand what to do.
I assure you that the snippets are correct because I use them on VSCode and the json format is valid, tested on https://jsonlint.com/

**Comment by siduck** [comment]
> Sorry @siduck I didn't understand what to do. I assure you that the snippets are correct because I use them on VSCode and the json format is valid, tested on https://jsonlint.com/

add luasnip's name in that remove table . 

and then install luasnip ( define it in your custom dir ) . add its config ( dont use our snippets variable)

**Comment by danjenson** [comment]
I'm also interested in this -- so luasnips' snippet-path does nothing in the chadrc now?

**Comment by siduck** [comment]
> > Sorry @siduck I didn't understand what to do. I assure you that the snippets are correct because I use them on VSCode and the json format is valid, tested on https://jsonlint.com/
> 
> add luasnip's name in that remove table .
> 
> and then install luasnip ( define it in your custom dir ) . add its config ( dont use our snippets variable) and then do :PackerSync

try this @danjenson

**Comment by nank1ro** [comment]
Hi,

finally I was able to make it working.
I don't know how, but today after updating NvChad and using again the `options.luasnip.snippet_path` successfully my custom snippets appeared correctly.
You can close the issue if you want, thanks a lot for your time and your help

**Comment by bidhan690** [comment]
> Hi,
> 
> finally I was able to make it working.
> I don't know how, but today after updating NvChad and using again the `options.luasnip.snippet_path` my custom snippets appeared correctly.
> You can close the issue if you want, thanks a lot for your time and your help 

Hey can you share config files?

**Comment by siduck** [comment]
> > Hi,
> > finally I was able to make it working.
> > I don't know how, but today after updating NvChad and using again the `options.luasnip.snippet_path` my custom snippets appeared correctly.
> > You can close the issue if you want, thanks a lot for your time and your help
> 
> Hey can you share config files?

check the snippets * doc in nvchad.com
