### ISSUE TITLE
Integration NvChad `updates` with new Packer Snapshot feature

### ISSUE THREAD

**Issue by erwin** [NvChad/NvChad#721]
**Is your feature request related to a problem? Please describe.**
Packer has a `snapshot` feature that will be dropping soon...
See: 

https://github.com/wbthomason/packer.nvim/pull/370/commits

**Describe the solution you'd like**
I think it would be a good idea to wrap all `nvchad update` calls with `packer snapshots` so that people can easily roll back if there's ever a conflict.

**Describe alternatives you've considered**
Of course fine to leave as is. Just a nice way to make `NvChad` more stable for users.

Closely related, I think users would also benefit from some a `rolling` and a `release` build... Basically rolling is always the newest version of everything, and `release` points to specific versions of each package. For example see:

https://www.lunarvim.org/01-installing.html#prerequisites

> #### Stable
>
> No alarm or surprise:
>
```
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
```

> #### Rolling
>
> All the new features with all the new bugs:
>
```
LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
```

Might also be good to explicitly set NvChad's `neovim` version number compatibility. For example, `release` might always work on NeoVim stable, and `rolling` might be a neovim nightly release, where we periodically update the exact release tag to say newer than X... 

Or does everyone running nightly actually run a script somewhere to pull a new release every single night?

**Comment by siduck** [comment]
nvchad users are supposed to use the master branch i.e which means they're using the rolling release version. The releases are just meant to track the progress etc. Also most of the errors related to breaking of config only occur when the plugins used in nvchad have some syntax related changes which break their configs. so its not really nvchad breaking the config! but plugins most of the time!

**Comment by peppapig450** [comment]
lunarvim's install.sh script is a mess jeez

**Comment by erwin** [comment]
> so its not really nvchad breaking the config! but plugins most of the time!

Isn't NvChad a custom config that collects many plugins?
So doesn't it make sense to extend control over those plugins so they behave as reliably as possible?

**Comment by siduck** [comment]
> > so its not really nvchad breaking the config! but plugins most of the time!
> 
> Isn't NvChad a custom config that collects many plugins? So doesn't it make sense to extend control over those plugins so they behave as reliably as possible?

we cant, it depends on the plugin. If it has any breaking change and the user does PackerSync then his nvchad gets broken

**Comment by peppapig450** [comment]
What if we detect breaking changes and warn the user before they packer sync until it can be resolved?

**Comment by peppapig450** [comment]
We could also use a ci pipeline to detect if any errors occur to let us know

**Comment by siduck** [comment]
yes this can be done but idk how CI works!

**Comment by erwin** [comment]
I was just hoping that NvChad Update could be wrapped in a PackerSnapshot, so that if anything does go wrong, it's easy to revert.

I could see a NvSync that's a wrapper around PackerSync that also calls PackerSnapshot first could also be pretty useful.

**Comment by siduck** [comment]
im not sure how the packersnapshot works, so for example I do PackerSync today ( no errors ) and after a month I do PackerSync and then some plugin config breaks like feline.nvim so I can revert to that month old snapshot?

**Comment by erwin** [comment]
> some plugin config breaks like feline.nvim so I can revert to that month old snapshot

Yes, as long as you did a PackerSnapshot before the next PackerSync

See the PR where the feature is in progress and ready to be merged:

https://github.com/wbthomason/packer.nvim/pull/370


### Make snapshot

To make a snapshot you just have to run

```
:PackerSnapshot <snapshot name>
```

### Restore snapshot

To rollback to a snapshot you have two ways:

Add `config.snapshot = 'some snapshot'`. You can specify either the snapshot name which will be fetched inside `config.snapshot_path` (the default snapshot directory which is `~/.cache/nvim/packer` but you can change it) or an absolute path.
    So, if I want to restore a snapshot named foo I would have something like this:

```
packer.startup( {function() use 'tjdevries/colorbuddy.vim' end, config = { snapshot='foo' })
```

In this way, every time you boot up NeoVim it will always load that snapshot.

    You can also run `:PackerRollback` which updates your installed plugins' commit to the snapshot you specified. After that you just need to run `:PackerUpdate` and it will revert back

#### Delete snapshot

Just run `PackerDelete <snapshot name>` , you can either provide only the snapshot name or an absolute path.

### Misc:

I've also added a `packer.snapshot_complete()` so that `PackerRollback` and `PackerDelete` can prompt which snapshots are available.
    
The snapshot format is a Lua table serialized using `vim.inspect` 

`packer.rollback` hard resets the git repo of the given plugin

**Comment by siduck** [comment]
so this will snapshot the whole nvim config too right?

**Comment by erwin** [comment]
> this will snapshot the whole nvim config too right

Unfortunately it doesn't snapshot the whole config... 

In think since Packer is ultimately just a package manager they wanted to limit the scope of it

**Comment by siduck** [comment]
user might face this issue that using master config + old snapshot can cause break things!

**Comment by erwin** [comment]
Could cause conflict... But don't we only try to roll back when things are no longer working? I think it does make sense to package up the config with the rollback though as you pointed out.

Anyway, it's new... I think it will take some experimentation to figure out if there's a way to make good use of it in NvChad... Just wanted to bring it to your attention.

**Comment by siduck** [comment]
> I'm sure your right. Without also backing up the config it could cause conflict...
> 
> Might be worth a shot though as we only try to roll back when things are no longer working? I think it does make sense to package up the config with the rollback though as you pointed out.
> 
> Anyway, it's new... I think it will take some experimentation to figure out if there's a way to make good use of it in NvChad... Just wanted to bring it to your attention.

maybe we can try this: 

local snapshotDate; 

when user creates a snapshot then assign snapshotDate.

- Then do this, revert to nvchad (github commit) which is closer or equal to the snapshotDate , btw this will require some scripting, @peppapig450 is good with scripting so he might help with this. 

Sooo at the end  ,


```
:PackerSnapshot <snapshot name> | run that script
```

**Comment by peppapig450** [comment]
ill work on it when i finish homework 👍

**Comment by peppapig450** [comment]
Is there info on how the date will be formatted?

**Comment by peppapig450** [comment]
![image](https://user-images.githubusercontent.com/55930078/148872877-df94059f-94bf-4bb1-8d8c-58c0f8ac3e93.png)
@siduck  @erwin first attempt very rough prototype

**Comment by peppapig450** [comment]
could we preview the commits and dates with telescope?

**Comment by siduck** [comment]
> could we preview the commits and dates with telescope?

i think so

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/150617594-ed546637-c7c6-43ff-b39f-c1521b2d6a65.png)

idk about date tho

**Comment by siduck** [comment]
thats leader cm

**Comment by peppapig450** [comment]
hmm i got it to find the closest commit using an awk script but it only works on gnu awk (i think, i know for sure bsd awk doesnt work) im working on righting one that works for both

**Comment by siduck** [comment]
> hmm i got it to find the closest commit using an awk script but it only works on gnu awk (i think, i know for sure bsd awk doesnt work) im working on righting one that works for both

does windows use gnu awk too?

**Comment by peppapig450** [comment]
git bash uses gnu awk idk if cygwin does i dont have it installed

**Comment by peppapig450** [comment]
im guessing it doesnt by default based on this https://www.gnu.org/software/gawk/manual/html_node/Cygwin.html

**Comment by peppapig450** [comment]
just an update - this pr seems to be almost ready to be merged to main

**Comment by siduck** [comment]
:0

**Comment by peppapig450** [comment]
```shell 
#!/bin/bash
set -Eeuo pipefail

declare snapshotDate commit

snapshotDate="$(awk -F= '/packersnapshot/ {print $2}' test.file | tr -d '-')"

commit=$(git log --format='%H %ci' --date=format:'%Y-%m-%d %H:%M:%S' | tr -d '-' | /usr/bi
n/awk -v c=2 -v t="$snapshotDate" 'NR==1{d=$c-t;d=d<0?-d:d;v=$c;next}{m=$c-t;m=m<0?-m:m}m<
d{d=m;v=$c}END{print v}')

echo "$commit"
``` 
current script i have rn

**Comment by peppapig450** [comment]
This feature was merged

**Comment by peppapig450** [comment]
```shell 
#!/bin/sh
set -eu

snapshotDate=$(awk -F'=' '/packersnapshot/ {print $2}' test.file | tr -d '-')

commit=$(git log --format='%H %ci' --date=format:'%Y-%m-%d %H:%M:%S' | tr -d '-' | \
  awk -v c=2 -v t="$snapshotDate" 'NR==1{d=$c-t;d=d<0?-d:d;v=$c;next} \
  {m=$c-t;m=m<0?-m:m} \
    m<d{d=m;v=$c}END{print v}'
)

commit=$(git log --format='%H %ci' --date=format:'%Y-%m-%d %H:%M:%S' | tr -d '-' | awk -v t="$commit" '$2 == t {print $1}')
echo "$commit"
```

**Comment by siduck** [comment]
btw i dont see any packersnapshot option 
![image](https://user-images.githubusercontent.com/59060246/159144924-2e84c82b-d9dd-4780-9012-1a1490225aa4.png)

**Comment by peppapig450** [comment]
> btw i dont see any packersnapshot option ![image](https://user-images.githubusercontent.com/59060246/159144924-2e84c82b-d9dd-4780-9012-1a1490225aa4.png)
> 
> how do we use it?

no idea

**Comment by siduck** [comment]
hmm got it
![image](https://user-images.githubusercontent.com/59060246/165183342-831a66a9-bdce-419f-bbc0-2b27d70ff990.png)

we added some commands here but missed snapshot command

**Comment by peppapig450** [comment]
I've finished finals so I can work on this again but I don't know how to do the lua bit but if you need anything done with the shell script let me know. 👍

**Comment by siduck** [comment]
> I've finished finals so I can work on this again but I don't know how to do the lua bit but if you need anything done with the shell script let me know. +1

have you tried this snapshot feature yourself?

**Comment by peppapig450** [comment]
I have no idea how it works so no. I haven't really done anything with neovim in the last 3 weeks

**Comment by bryant-the-coder** [comment]
PackerSnapShot basically saves the current file (i think that is what they call it). When there is a breaking change and the config somehow broke. Run `PackerSnapShotRollback <name when you save your snapshot>`

**Comment by siduck** [comment]
does it work for u

**Comment by bryant-the-coder** [comment]
Yes. :))

**Comment by siduck** [comment]
I tried adding the snapshot and snapshot path variable in the packer init config, it just gives me some errors :/

**Comment by peppapig450** [comment]
I'll try it when I finish homework tonight

**Comment by bryant-the-coder** [comment]
> I tried adding the snapshot and snapshot path variable in the packer init config, it just gives me some errors :/

why are u changing the path var?

**Comment by siduck** [comment]
> > I tried adding the snapshot and snapshot path variable in the packer init config, it just gives me some errors :/
> 
> why are u changing the path var?

i didnt, i kept it default as shown in packer readme and yet i get some errors bruh

**Comment by siduck** [comment]
@zbirenbaum  we need to add user_commands for PackerSnapshot, PackerSnapshotRollback and PackerSnapshotDelete

I tried doing it but not sure how to make the function accept args 

![image](https://user-images.githubusercontent.com/59060246/166114775-dc97e7ee-a8f7-41ec-bb15-395a1034540e.png)

check https://github.com/wbthomason/packer.nvim/blob/4dedd3b08f8c6e3f84afbce0c23b66320cd2a8f2/lua/packer.lua#L137
