### ISSUE TITLE
hide buffers and view them with telescope

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#728]
Leader + x hides terminal buffer, the same way we could hide normal ( file ) buffers since bufferline gets very cluttered with toooo many files ( aka buffers ) opened so it would be nice to hide the file buffers instead.

- leader + x ( by default this hides term buffers but now hide file buffers too)
- leader + shift + b  will show telescope picker with only hidden file buffers

**Comment by Akianonymus** [comment]
> Leader + x hides terminal buffer, the same way we could hide normal ( file ) buffers since bufferline gets very cluttered with toooo many files ( aka buffers ) opened so it would be nice to hide the file buffers instead.
> 
> * leader + x ( by default this hides term buffers but now hide file buffers too)
> * leader + shift + b  will show telescope picker with only hidden file buffers

What's wrong with the current behaviour ? leader+x closes the buffer and obviously gets removed from bufferline.

**Comment by siduck** [comment]
> > Leader + x hides terminal buffer, the same way we could hide normal ( file ) buffers since bufferline gets very cluttered with toooo many files ( aka buffers ) opened so it would be nice to hide the file buffers instead.
> > 
> > * leader + x ( by default this hides term buffers but now hide file buffers too)
> > * leader + shift + b  will show telescope picker with only hidden file buffers
> 
> What's wrong with the current behaviour ? leader+x closes the buffer and obviously gets removed from bufferline.

Im aware but it would be nice to hide non terminal buffers too

**Comment by siduck** [comment]
I somemtimes work with 10+ files together so having them opened clutters the bufferline

**Comment by zbirenbaum** [comment]
> I somemtimes work with 10+ files together so having them opened clutters the bufferline , it would be good to hide them. Ik i can just open them with nvimtree but i cant keep remembering which files i had been working on xd

This is the big reason why some people (including me) like vimtabs are very against things like bufferline. Try out `:tabe`, it may help you out a lot.

Sometimes plugin feature creep obscures the original ways of doing things and ends up making them harder.
