### ISSUE TITLE
About lsp-installer

### ISSUE THREAD

**Issue by Ruixi-rebirth** [NvChad/NvChad#729]
![image](https://user-images.githubusercontent.com/75824585/149603212-706a38fd-e662-43e7-8080-ed70326ca5a0.png)
![image](https://user-images.githubusercontent.com/75824585/149603279-2dc280a1-5b01-4102-9858-8ff681c74b8f.png)

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/149603798-c8a9edd3-351d-4766-af6a-1c789ddd13b3.mp4

**Comment by siduck** [comment]
works fine for me :/

**Comment by siduck** [comment]
your root dir doesnt match , it must at least have .git or package.json for tsserver to start

**Comment by Ruixi-rebirth** [comment]
It works fine for me too, thank you!

**Comment by Ruixi-rebirth** [comment]
> your root dir doesnt match , it must at least have .git or package.json for tsserver to start

I would like to know why do this? Is there any relevant documentation?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/149606592-7daa6304-6354-4345-878d-75f78a678656.png)
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver
