### ISSUE TITLE
module in packer's plugin

### ISSUE THREAD

**Issue by oliverdding** [NvChad/NvChad#730]
**Describe the bug**

After adding custom plugin(e.g. simrat39/rust-tools.nvim) that relays on core plugins(e.g. nvim-lspconfig), module not found exception was given.

![startup error](https://user-images.githubusercontent.com/43624923/149612851-99107b74-9cef-4577-8391-0991b5fc5473.png)

Seems like the packer can't recognize real module behind the plugin name? When I added module to the nvim-lspconfig, everything work great:

![module added](https://user-images.githubusercontent.com/43624923/149613108-96a88e8a-c742-40f8-86a4-d50afe09b9f1.png)

**To Reproduce**

Plugins list

```lua
    -- dap
    use {
        "mfussenegger/nvim-dap",
        module = "dap",
        opt = true,
        config = function() require "custom.plugins.dap" end,
        setup = function()
            require("core.utils").packer_lazy_load "nvim-dap"
        end,
    }

    use {
        "rcarriga/nvim-dap-ui",
        module = "dapui",
        opt = true,
        after = "nvim-dap",
        config = function() require("dapui").setup() end,
        setup = function()
            require("core.utils").packer_lazy_load "nvim-dap-ui"
        end,
    }

    use {
        "theHamsta/nvim-dap-virtual-text",
        opt = true,
        after = "nvim-dap",
        config = function() require("nvim-dap-virtual-text").setup() end,
        setup = function()
            require("core.utils").packer_lazy_load "nvim-dap-virtual-text"
        end,
    }

    -- rust
    use {
        "simrat39/rust-tools.nvim",
        module = "rust-tools",
        opt = true,
        after = "nvim-lspconfig",
        config = function() require "custom.plugins.rust" end,
        setup = function()
            require("core.utils").packer_lazy_load "rust-tools.nvim"
        end,
    }
```

**Desktop (please complete the following information):**
 - Arch Linux x86_64(Kernel 5.16.0-zen1-1-zen)
 - Alacritty
 - NVIM v0.6.1 (LuaJIT 2.0.5)

**Additional context**

By the way, the lazy load ability seems not play it's role. Every time neovim starts, all the dap related plugins are loaded:

![lazy load](https://user-images.githubusercontent.com/43624923/149612985-4bc340bc-6d76-4764-8315-8d8df6b6b3eb.png)

**Comment by Akianonymus** [comment]
@oliverdding Do not use this `require("core.utils").packer_lazy_load "rust-tools.nvim"` in normal configs, you don't need it.

I will add the lspconfig changes to plugins/init.lua

**Comment by Akianonymus** [comment]
Update: Added in this pr

https://github.com/NvChad/NvChad/pull/737
