### ISSUE TITLE
Italics Support

### ISSUE THREAD

**Issue by danielcherubini** [NvChad/NvChad#732]
So I've noticed that with the themes, you have stripped the italics out, So function names and other things don't have italic support.

take Dracula for instance, yours is called chadracula, and it's just basically the dracula colors, but not the italics.

Here's an example with the official dracula theme

![image](https://user-images.githubusercontent.com/399473/149826461-c16aab2d-9691-426b-afb8-b99dd23a5fa3.png)

And yours

![image](https://user-images.githubusercontent.com/399473/149826519-6f35de0d-48bc-4252-982f-e3ba0a387969.png)

See the difference? It's not just dracula, it's really all of them.

So either you could add more options for italics, so function names, variables, models, etc,etc ... or you could just use the official themes.

**Comment by siduck** [comment]
there is a reason we dont use official themes https://github.com/NvChad/NvChad/issues/397

**Comment by siduck** [comment]
you can add italics support yourself 

![image](https://user-images.githubusercontent.com/59060246/149852082-279e8a8a-e1e0-4b94-90a5-afeb519cd1b3.png)

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-default-highlights

**Comment by siduck** [comment]
my custom highlights file 
![image](https://user-images.githubusercontent.com/59060246/149852134-a536fc13-35a7-41d0-b538-05cc28ae2b20.png)

**Comment by danielcherubini** [comment]
Huge thanks!

https://gitlab.com/danielcherubini/dotfiles/-/blob/master/nvchad/highlights.lua

**Comment by dinhmai74** [comment]
hi @danielcherubini, can you share how to do it. I'm new here and cannot find the way to do it

**Comment by blackode** [comment]
Is there a language specific highlights?
I mean I would like to make function names as italic in Elixiir. 
The following is my override in **highlights.lua**
```
M.override = {
  AlphaHeader = { fg = "blue" },
  CursorLine = {
    bg = "black2",
  },
  Comment = {
    italic = true,
  },
  Statement = {
    italic = true,
  },
  Define = { italic = true },
  eliixirString = { italic = true },
  Include = { italic = true },
  TSVariable = { italic = true },
  Variable = { italic = true },
  -- Type = { italic = true },
  Function = { italic = true },
  Keyword = { italic = true },
  TSKeyword = { italic = true },
  TSMethod = { italic = true },
  TSDefine = { italic = true },
  SpecialComment = { italic = true },
}
`

**Comment by tom-w00d** [comment]
SpecialComment does not work with doc comment in Rust, Comment does so I am sure the hl_override and the config is correct, just SpecialComment seems not to work for some reason I can’t figure out.

Any help?

**Comment by siduck** [comment]
> Is there a language specific highlights? I mean I would like to make function names as italic in Elixiir. The following is my override in **highlights.lua**
> 
> ```
> M.override = {
>   AlphaHeader = { fg = "blue" },
>   CursorLine = {
>     bg = "black2",
>   },
>   Comment = {
>     italic = true,
>   },
>   Statement = {
>     italic = true,
>   },
>   Define = { italic = true },
>   eliixirString = { italic = true },
>   Include = { italic = true },
>   TSVariable = { italic = true },
>   Variable = { italic = true },
>   -- Type = { italic = true },
>   Function = { italic = true },
>   Keyword = { italic = true },
>   TSKeyword = { italic = true },
>   TSMethod = { italic = true },
>   TSDefine = { italic = true },
>   SpecialComment = { italic = true },
> }
> `
> ```

that would be tricky to implement, so just use an autocmd or check the filetype dir
