### ISSUE TITLE
parity with `nvim --clean <dir>`

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#733]
**Describe the bug**
opening nvim with a directory, i.e. `nvim .` opens a file named `.`. If you open nvim-tree from here and select a file, it closes the buffer.

**To Reproduce**
1. `nvim .`
2. open nvim-tree
3. select file from tree
4. ????
4. watch it exit vim immediately

**Expected behavior**
Opens file selected using nvim-tree. It would also be nice to open nvim-tree from the start, rather than a buffer named '.'

**Desktop (please complete the following information):**
 - Void Linux 5.15.14_1
 - Alacritty
 - NVIM v0.6.1

Please let me know if this isn't the proper place for this bug. I am posting here merely because I feel `NvChad` strives to give reasonable defaults to the plugins it provides, and this is certainly unexpected behavior.

**Comment by ericwq** [comment]
Repeat the above steps. The selected file is opened.  Try to use `Ctr-n` to toggle `nvim-tree` instead of '.'

**Comment by danjenson** [comment]
I'm not sure I follow, if you run `nvim .` it opens the current working directory, then you open `nvim-tree` with `ctrl+n`, select a file, press enter, and bam it exits nvim. Furthermore, if you open a directory, here just '.' (cwd) for simplicity, it should open nvim-tree automatically, the same way regular nvim will open the file explorer, rather than naming a file '.'

**Comment by peppapig450** [comment]
u could add this to ~/.bashrc
```shell
alias 'nvim .'='nvim +NvimTreeToggle'
```

**Comment by ericwq** [comment]
are u sure the problem is related with NvChad? what if u run nvim-tree.lua in standalone environment?

**Comment by danjenson** [comment]
what about `nvim <any dir>`? '.' was just used as a simple example demonstrating the unexpected behavior. And as I mentioned in my original comment:

Please let me know if this isn't the proper place for this bug. I am posting here merely because I feel NvChad strives to give reasonable defaults to the plugins it provides, and this is certainly unexpected behavior.

**Comment by siduck** [comment]
did you un-lazy load nvimtree ?

**Comment by danjenson** [comment]
No, how would I do that for this plugin, since it's configured by NvChad?

**Comment by siduck** [comment]
> No, how would I do that for this plugin, since it's configured by NvChad?

there's a chadrc option for it, refer default_config.lua plugins->options->nvimtree-> lazy load var

![image](https://user-images.githubusercontent.com/59060246/151725618-2fb81552-11d4-40fb-889d-4f83ef23ba9b.png)

make it false then do PackerCompile

**Comment by peppapig450** [comment]
> what about `nvim <any dir>`? '.' was just used as a simple example demonstrating the unexpected behavior. And as I mentioned in my original comment:
> 
> Please let me know if this isn't the proper place for this bug. I am posting here merely because I feel NvChad strives to give reasonable defaults to the plugins it provides, and this is certainly unexpected behavior.

I think you could do this in a bash function

**Comment by siduck** [comment]
> `nvim --clean .`

this is more of a nvimtree issue rather than nvchad issue ;(

**Comment by siduck** [comment]
wait lemme see

**Comment by peppapig450** [comment]
https://user-images.githubusercontent.com/55930078/151734532-22c6124b-e32a-498d-9777-d94cc5ef96f9.mp4

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/151734477-5ff97950-5422-48b5-a778-d50e822dd787.mp4

Solution : 


 - open_on_setup = false, (in nvimtree default table)
 - remove lazy loading
 - :PackerCompile

**Comment by siduck** [comment]
since you dont wanna copy whole nvimtree table to just make that simple change so do it via chadrc itself

example : 

```
M.plugins = {

   options = {
      nvimtree = {
         lazy_load = false,
      },
   },

   default_plugin_config_replace = {
      nvim_tree = {
         open_on_setup = true,
      },
   },
}
```

**Comment by siduck** [comment]
documented here https://nvchad.github.io/config/Custom%20config#override-default-config-of-a-plugin

**Comment by RenanZX** [comment]
> documented here https://nvchad.github.io/config/Custom%20config#override-default-config-of-a-plugin

Page not found

> since you dont wanna copy whole nvimtree table to just make that simple change so do it via chadrc itself
> 
> example :
> 
>``` 
> M.plugins = {
> 
>    options = {
>       nvimtree = {
>          lazy_load = false,
>       },
>    },
> 
>    default_plugin_config_replace = {
>       nvim_tree = {
>          open_on_setup = true,
>       },
>    },
> }

It doesn't works

> i think this does what you want? should work on any posix shell
> ```
> #!/usr/bin/env bash
> 
> nvim() {
>   test="$1"
> # if arg is a directory open with nvimtree
>   if [ -d "$test" ]; then
>     command nvim +NvimTreeToggle "$test"
> # if arg is a file open without nvimtree
>   elif [ -f "$test" ]; then
>     command nvim "$test"
>   else
> # if there is no argument or argument is either just run nvim
>     command nvim
>   fi
> # Note: command is used to run nvim because otherwise the function being named nvim causes problems
> }

It doesn't works too, i guess the command ```+NvimTreeToggle``` is deprecated, because it opens in the same folder that i'm located, even typing ```nvim +NvimTreeToggle "folder_location"``` in bash, i need to activate something to make it works?

**Comment by siduck** [comment]
+NvimTreeToggle isnt depreceated . please just run `nvim +NvimTreeToggle` and check

```bash
nv() {
  [ -n "$1" ] && [ -d "$1" ] && cd "$1" && shift
  nvim +NvimTreeToggle "$@"
}
```

**Comment by RenanZX** [comment]
> +NvimTreeToggle isnt depreceated . please just run nvim +NvimTreeToggle and check
>```
> nv() {
>  [ -n "$1" ] && [ -d "$1" ] && cd "$1" && shift
>  nvim +NvimTreeToggle "$@"
>}

Thank you, it works.
