### ISSUE TITLE
Return to last edited file then back from explore

### ISSUE THREAD

**Issue by i3Cheese** [NvChad/NvChad#734]
More formally I want to space + e in explorer get me back to last edited file.

Sometimes I just like to spin around windows when thinking and find it annoying when I cannot get back with the same keybind.
Also it may be useful then you just want to check a project file tree.

**Comment by siduck** [comment]
this might be more of a nvimtree feature which is out of the scope of nvchad's future features. Maybe you can try 

https://github.com/rmagatti/auto-session
