### ISSUE TITLE
Bad indentation with `.vue` and `.php` files

### ISSUE THREAD

**Issue by AlphaTechnolog** [NvChad/NvChad#736]
I have a problem with NvChad working, when I open a `.vue` file and create some method or a lifecycle method like `create` or `mounted` in the `<script>` tag, the indent is not working great:

https://user-images.githubusercontent.com/54639968/150588147-5377f9df-493b-4949-8bb4-e75afb603917.mp4

> Using the default configuration only with the catppuccin theme

I try removing the treesitter parser for vue, I have been noticed it may causes problems with indentation in some languages and some cases, like in php or in react jsx (in some cases, not in all), but it's not working...

**Comment by AlphaTechnolog** [comment]
I updated NvChad now (using leader+uu), and then getting the same problem but a bit different in `.php` files:


https://user-images.githubusercontent.com/54639968/150589715-0ff8df0b-a075-47cf-9260-4d1407bdc307.mp4

> I tried putting `set autoindent` into config, but it doesn't work

Putting `vim.cmd [[ set autoindent ]] ` and `vim.opt.autoindent = true` into `custom/init.lua` file in NvChad config

**Comment by siduck** [comment]
there's an option for enabling indent in treesitter config ,try that

**Comment by AlphaTechnolog** [comment]
> there's an option for enabling indent in treesitter config ,try that

where I enable it?

**Comment by AlphaTechnolog** [comment]
I try with my custom nvim with this config:

```
local M = {}
local present, config = pcall(require, 'nvim-treesitter.configs')
if not present then
  return { setup = function () end }
end

M.setup = function ()
  config.setup {
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = true
    }
  }
end

return M
```

**Comment by AlphaTechnolog** [comment]
I try with my custom config of neovim with this config:

```lua
local M = {}
local present, config = pcall(require, 'nvim-treesitter.configs')
if not present then
  return { setup = function () end }
end

M.setup = function ()
  config.setup {
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = true
    }
  }
end

return M
```

And it works correctly

But in NvChad:

```lua
local present, ts_config = pcall(require, "nvim-treesitter.configs")

if not present then
   return
end

ts_config.setup {
   ensure_installed = {
      "lua",
      "vim",
   },
   highlight = {
      enable = true,
      -- use_languagetree = true,
      additional_vim_regex_highlighting = true
   },
}
```

It doesn't work, I uncomment use_languagetree to match my custom config, and it config works correctly with php, but with `.vue` file I get the same problem

**Comment by siduck** [comment]
does your config workwith vue php files

**Comment by AlphaTechnolog** [comment]
yeah, it works correctly:

https://user-images.githubusercontent.com/54639968/150641368-a8992043-9c76-4acf-810a-2634b6fd7bb8.mp4

> Sorry for the video quality

**Comment by AlphaTechnolog** [comment]
I tried disabling vue treesitter parser in NvChad but it doesn't work too
> I think it's not a problem related with treesitter

My custom NvChad config is:

- lua/custom/init.lua
```lua
-- This is an example init file , its supposed to be placed in /lua/custom/

-- This is where your custom modules and plugins go.
-- Please check NvChad docs if you're totally new to nvchad + dont know lua!!

-- MAPPINGS
local map = require('core.utils').map

local keys = { 'jk', 'kj', 'jj', 'kk' }

for _, key in ipairs(keys) do
  map('i', key, '<esc>')
end

vim.cmd [[
 augroup RestoreCursorShapeOnExit
   autocmd!
   autocmd VimLeave * set guicursor=a:hor20
   autocmd InsertEnter * set guicursor=a:hor20
   autocmd InsertLeave * set guicursor=a:block
   autocmd VimEnter * set guicursor=a:block
 augroup END
]]

map('n', '<esc>', ':noh<cr>')

-- NOTE: the 4th argument in the map function can be a table i.e options but its most likely un-needed so dont worry about it

-- NOTE: we heavily suggest using Packer's lazy loading (with the 'event','cmd' fields)
-- see: https://github.com/wbthomason/packer.nvim
-- https://nvchad.github.io/config/walkthrough
```

- lua/custom/chadrc.lua
```lua
-- This is an example chadrc file , its supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.ui = {
   hl_override = "", -- path of your file that contains highlights
   italic_comments = false,
   theme = "catppuccin", -- default theme

   -- Change terminal bg to nvim theme's bg color so it'll match well
   -- For Ex : if you have onedark set in nvchad, set onedark's bg color on your terminal
   transparency = false, 
}

M.plugins = {
   -- enable/disable plugins (false for disable)
   status = {
      blankline = true, -- indentline stuff
      bufferline = true, -- manage and preview opened buffers
      colorizer = true, -- color RGB, HEX, CSS, NAME color codes
      comment = true, -- easily (un)comment code, language aware
      dashboard = true,
      better_escape = true, -- map to <ESC> with no lag
      feline = true, -- statusline
      gitsigns = true,
      lspsignature = true, -- lsp enhancements
      vim_matchup = true, -- improved matchit
      cmp = true,
      nvimtree = true,
      autopairs = true,
   },
   options = {
      packer = {
         init_file = "plugins.packerInit",
      },
      autopairs = { loadAfter = "nvim-cmp" },
      cmp = {
         lazy_load = true,
      },
      lspconfig = {
         setup_lspconf = "custom.plugins.lspconfig", -- path of file containing setups of different lsps
      },
      nvimtree = {
         enable_git = 0,
         -- packerCompile required after changing lazy_load
         lazy_load = true,

         ui = {
            allow_resize = true,
            side = "left",
            width = 25,
            hide_root_folder = true,
         },
      },
      luasnip = {
         snippet_path = {},
      },
      statusline = {
         -- hide, show on specific filetypes
         hidden = {
            "help",
            "dashboard",
            "NvimTree",
            "terminal",
         },
         shown = {},

         -- truncate statusline on small screens
         shortline = true,
         style = "default", -- default, round , slant , block , arrow
      },
      esc_insertmode_timeout = 300,
   },
   default_plugin_config_replace = {},
}

return M
```

**Comment by AlphaTechnolog** [comment]
I use vls for vue files and intelephense for php files
> Its are the language servers

**Comment by siduck** [comment]
@AlphaTechnolog I will check this later btw dont copy whole chadrc! add the table which is only needed . look at mine https://github.com/siduck/dotfiles/blob/master/nvchad/custom/chadrc.lua

**Comment by AlphaTechnolog** [comment]
> @AlphaTechnolog I will check this later btw dont copy whole chadrc! add the table which is only needed . look at mine https://github.com/siduck/dotfiles/blob/master/nvchad/custom/chadrc.lua

Ok, I try with your chadrc, and getting the same issue with `.vue` files, `php` files are correctly working at adding `additional_vim_regex_highlight` to treesitter config in my case!

**Comment by siduck** [comment]
> > @AlphaTechnolog I will check this later btw dont copy whole chadrc! add the table which is only needed . look at mine https://github.com/siduck/dotfiles/blob/master/nvchad/custom/chadrc.lua
> 
> Ok, I try with your chadrc, and getting the same issue with `.vue` files, `php` files are correctly working at adding `additional_vim_regex_highlight` to treesitter config in my case!
oh so adding additional_vim_regex_highlight works?

**Comment by siduck** [comment]
also i meant to keep your chadrc short ,avoid having unused tables

**Comment by AlphaTechnolog** [comment]
> > > @AlphaTechnolog I will check this later btw dont copy whole chadrc! add the table which is only needed . look at mine https://github.com/siduck/dotfiles/blob/master/nvchad/custom/chadrc.lua
> > 
> > 
> > Ok, I try with your chadrc, and getting the same issue with `.vue` files, `php` files are correctly working at adding `additional_vim_regex_highlight` to treesitter config in my case!
> 
> oh so adding additional_vim_regex_highlight works?

Only for `.php` files, the problem persist for `.vue` files

**Comment by AlphaTechnolog** [comment]
> also i meant to keep your chadrc short ,avoid having unused tables

Thank you, I will update it!

**Comment by AlphaTechnolog** [comment]
My new chadrc: (thank you, I don't know NvChad works correctly if I skip some tables values)

```lua
local M = {}

M.ui = {
  hl_override = "", -- path of your file that contains highlights
  italic_comments = true,
  theme = "onedark-deep", -- default theme

  -- Change terminal bg to nvim theme's bg color so it'll match well
  -- For Ex : if you have onedark set in nvchad, set onedark's bg color on your terminal
  transparency = false, 
}

M.plugins = {
  status = {
    blankline = false,
    dashboard = true,
    colorizer = true,
  },
}

return M
```

**Comment by siduck** [comment]
does your custom config have anything particular that does the indent thing?

**Comment by AlphaTechnolog** [comment]
> does your custom config have anything particular that does the indent thing?
No

But searching in the NvChad source code, in the file `lua/core/default_config.lua` are enabled by default, it causes problems with `.vue` files, In my nvchadrc config I put this:

```lua
M.options = {
  smartindent = false,
}
```

And it solves the problem for `.vue` files, for fix the `.php` files add `additional_regex_highlight` to treesitter config

**Comment by AlphaTechnolog** [comment]
Basically it's the difference from my custom neovim config. My custom neovim config have:

```lua
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
```

And NvChad has anything like this:

```lua
vim.opt.tabstop = options.tabstop
vim.opt.shiftwidth = options.shiftwidth
vim.opt.tabstop = options.tabstop -- where are true by defaultvim.opt.smartindent = options.smartindent -- where 
```

**Comment by siduck** [comment]
> Basically it's the difference from my custom neovim config. My custom neovim config have:
> 
> ```lua
> vim.opt.tabstop = 2
> vim.opt.shiftwidth = 2
> vim.opt.expandtab = true
> ```
> 
> And NvChad has anything like this:
> 
> ```lua
> vim.opt.tabstop = options.tabstop
> vim.opt.shiftwidth = options.shiftwidth
> vim.opt.tabstop = options.tabstop -- where are true by default
> vim.opt.smartindent = options.smartindent -- where are true by default
> ```

ours is the same too except tabstop is 8

**Comment by AlphaTechnolog** [comment]
> > Basically it's the difference from my custom neovim config. My custom neovim config have:
> > ```lua
> > vim.opt.tabstop = 2
> > vim.opt.shiftwidth = 2
> > vim.opt.expandtab = true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And NvChad has anything like this:
> > ```lua
> > vim.opt.tabstop = options.tabstop
> > vim.opt.shiftwidth = options.shiftwidth
> > vim.opt.tabstop = options.tabstop -- where are true by default
> > vim.opt.smartindent = options.smartindent -- where are true by default
> > ```
> 
> ours is the same too except tabstop is 8

Yeah, but nvchad default config has smartindent in true and it causes problems on files .vue and .php in some cases

**Comment by siduck** [comment]
you can disable smartindent from your chadrc tho!

**Comment by AlphaTechnolog** [comment]
yeah, I do it! and it works! Thank you for NvChad!
