### ISSUE TITLE
tree sitter errors when opening a file

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#742]
**Describe the bug**
Whenever you open  a file tree sitter throws a ton of errors

**To Reproduce**
1. open nvim
2. select a file with telescope (or open it directly)
3. Tree sitter throws errors

**Expected behavior**
Tree sitter to not throw errors

**Screenshots**
<img width="1440" alt="Screen Shot 2022-01-22 at 2 54 50 PM" src="https://user-images.githubusercontent.com/55930078/150658139-9add9fe9-6a19-404d-b10a-03cc3412c633.png">

**Desktop (please complete the following information):**
- MacOS monterey
 - Kitty
 - v0.6.1

**Additional context**
This started happening either yesterday or the day before 
This also might be an upstream error

**Comment by GreatestOfAllTimee** [comment]
This seems like not an error from Nvchad. Do you already run `:TSUpdate` ?

**Comment by peppapig450** [comment]
that fixed it 
I didnt even know that was a command 🤦 thanks
