### ISSUE TITLE
[Suggestion]: Add vim-polyglot plugin

### ISSUE THREAD

**Issue by hunger** [NvChad/NvChad#744]
**Is your feature request related to a problem? Please describe.**

I open files that vim does not support rather regularly.

**Describe the solution you'd like**

[vim-polyglot](https://github.com/sheerun/vim-polyglot) adds a lot of filetype definitions in addition to what vim supports out of the box.

The web page claims polyglot adds about 10ms to vim startup -- much less than all the different language plugins this curated lists consist of would take when installed individually. I do find this very acceptable -- considering the configuration pain this has saved me already.

**Describe alternatives you've considered**

Installing plugins manually whenever I run into something that is not supported... which is a pain and slows me down whenever I open a filetype not yet covered.

I am looking through the plugins I load on top of what NVchad provides and found this to be the one that is probably generally applicable -- and that could help people getting started into the vim world. But then I am new to vim, maybe I am missing something.

**Comment by Sparkenstein** [comment]
TBH sounds something that you can easily have as a custom plugin in `chadrc.lua` instead a default plugin in nvchad. have you tried [custom config](https://nvchad.github.io/config/Custom%20config)

**Comment by GreatestOfAllTimee** [comment]
Nvchad come with [`nvim-treesitter/nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter), nvim-treesitter not just for syntax highlight it has many more features. Not gonna lie, some of [vim-polyglot](https://github.com/sheerun/vim-polyglot) syntax highlight are much better. I believe you're not read [Nvchad documention](https://nvchad.github.io).

Also see [`nvim-treesitter/nvim-treesitter#supported-languages`](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages).

**Comment by siduck** [comment]
you can add it yourself.I have used vim-polygot before and treesitter highlights syntax better

**Comment by hunger** [comment]
I do use it myself, I just think it would be valuable to have generally.

The highlighting is not the interesting part: polyglot handles a lot of setup for indention, compiler command and a lot more of the bits and pieces that make vim powerful.

I guess it all comes down to what NvChad is: For me it is a convenient base to get the basics set up and polyglot is definitely something that I consider very baseline.

**Comment by Freyskeyd** [comment]
I find myself struggling using treesitter with elixir files.
It seems very slow (like 1 sec loading on small files0
