### ISSUE TITLE
Question: how to disable nvchad while using vscode-neovim extension

### ISSUE THREAD

**Issue by SalttySugar** [NvChad/NvChad#747]
Hello everyone!

I struggle to disable nvchad completely while i am using vscode-neovim binding.

I want to provide an individual configuration file to the vscode-neovim extension, however even when running a clean configuration like this:

 `nvim -u $config` 

I'm having problems as it runs the packer_compiled.lua file in the background and this leads to errors like:

` Error detected while processing VimEnter Autocommands for "*"`

**Comment by siduck** [comment]
you may add a PR for the runtime https://github.com/NvChad/NvChad/issues/699 . Idk how that works so cant help

**Comment by caeu** [comment]
Not sure if I got the question right. I also use both neovim and vscode-neovim. I set different empty init.nvim file for vscode-neovim. This can be done from the setting of vscode.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/57561032/153071191-468d53be-d1d3-4908-a515-5e7b816463dc.png">

**Comment by zbirenbaum** [comment]
> Not sure if I got the question right. I also use both neovim and vscode-neovim. I set different empty init.nvim file for vscode-neovim. This can be done from the setting of vscode.
> 
> <img alt="image" width="751" src="https://user-images.githubusercontent.com/57561032/153071191-468d53be-d1d3-4908-a515-5e7b816463dc.png">

**Comment by siduck** [comment]
we do not support vscode stuffs! with nvchad on vscode you're on your own! @SalttySugar

**Comment by WernerWessely** [comment]
For anyone looking into this and @SalttySugar, you might find this helpful: https://www.reddit.com/r/neovim/comments/zptwc8/good_way_to_switch_between_configurations_while/?utm_source=share&utm_medium=web2x&context=3
