### ISSUE TITLE
BREAKING CHANGE! removed some plugins

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#748]
https://github.com/NvChad/NvChad/commit/4511b84d6c902aa818d7dc49c6b7b6c0dfb60004#commitcomment-64461265
 
 To install and setup lsp stuff, check https://nvchad.github.io/config/Lsp%20stuff
 To install autocompletion stuff ,check https://nvchad.github.io/config/Autocompletion
 
 you just need to copy paste configs from the docs.

**Comment by hunger** [comment]
So I have to manage all the completion and LSP plugins on my own going forward?

**Comment by siduck** [comment]
yes

**Comment by siduck** [comment]
we just had lspconfig and signature by default. never planned to add any extra lsp plugins tho . So all you have to do is read our docs and copy paste those configs

**Comment by tomasky** [comment]
Why not create a new branch containing these plugins?

**Comment by siduck** [comment]
> Why not create a new branch containing these plugins?

that'll keep confusion, all you need to do is just copy paste these once. we had plenty of issues regarding these plugins in the past so removed them finally. Even tho you can just refer the our docs for their lazy loaded configs

**Comment by hunger** [comment]
Sure, no problem, I updated to the latest and greatest with adjusted docs.

What does Nvchad want to provide? I can actually no longer find that information on the web site/README anymore, but I was under the impression that this was about a fast IDE-like experience.
Where is the IDE-like now that LSP/completion was removed?

Basically I am confused as to what this project is about now.

**Comment by siduck** [comment]
> Sure, no problem, I updated to the latest and greatest with adjusted docs.
> 
> What does Nvchad want to provide? I can actually no longer find that information on the web site/README anymore, but I was under the impression that this was about a fast IDE-like experience. Where is the IDE-like now that LSP/completion was removed?
> 
> Basically I am confused as to what this project is about now.

I never wanted to remove those plugins but there were users who wanted to use them non-lazy loaded which caused issues with some plugins  for them and breaking cmp completely, read the commit thread above. Also for the ide part, thats just mentioned in our about section of the repo .

"An attempt to make neovim cli as functional as an IDE while being very beautiful, blazing fast"

So you must be aware that nvchad doesnt provide IDE like features by default, its just a means to create your own custom config (and use core plugins for lsp,completion mentioned in the docs) which provides an ide like experience. We never claimed to provide an IDE like stuff, its just an 'attempt'. NvChad's supposed to be used as a base config on top of which the user adds his own config. This isnt like other frameworks. NvChad might be for those wanting to make their neovim look beautiful and load fast ( lazy loaded ). I will soon add a 'why' section in the readme explaining various stuffs.

**Comment by hunger** [comment]
It is of course your project, you can do whatever makes sense to you. Don't let me stop you, I really appreciate the work you have put in and have enjoyed using NVchad!

> So you must be aware that nvchad doesnt provide IDE like features by default

It used to provide a pretty solid base so far IMHO with LSP, treesitter, completion and search for various things being taken care of out of the box.

> NvChad's supposed to be used as a base config on top of which the user adds his own config.

... which has always worked great for me:-) It still does, with all the LSP/completion stuff moved out. This change does slightly nudge me into the direction of forking the code and moving over to a more static configuration more tailored to myself than I did that before when I was benefiting more from the defaults you provided.

Hmm, thinking about that: Nvchad is now closer to its true aim at making me better with nvim stuff:-)

Anyway: Thank you for all the effort you did and for providing a solid base for me to build on!

**Comment by siduck** [comment]
@hunger too bad that I had taken the decision of removing those plugins too fast without giving it any thought! After some tinkering i think its easy to fix #740 while still lazy loading cmp o_O

**Comment by siduck** [comment]
fixed it, but updating nvchad might not work ( leader uu) so re-clone the repo and move your custom folder into it. do :PackerSync

**Comment by hunger** [comment]
Nice!

Would you consider integration of cmp with lsp? You would need to let nvim-cmp update the capabilities using this line:

```
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)
```

after the capabilities are set up and before passing off to the custom user code.

That enables help to pop up when selecting things to complete.

**Comment by siduck** [comment]
@hunger we'll just use lspconfig's capabilities by default since using cmp's capabilities would mean removing lazy loading for it, but you can add it in your lspconfig 

![image](https://user-images.githubusercontent.com/59060246/151278744-fd811d74-9a5e-482f-805a-be05ed7dbdf6.png)
