### ISSUE TITLE
[ISSUE] I can't open some files (ex: userChrome.css)

### ISSUE THREAD

**Issue by linuxmobile** [NvChad/NvChad#753]
I've got some erros trying to open some files. Here you can found an example. I decided to get log with `nvim -V 1 userChrome.css`

I've got everything updated and installed ( `uu` to update nvchad nvim. And `packer sync | packer update`.)

![image](https://user-images.githubusercontent.com/10554636/150990473-77270aa5-97b1-49ac-bd40-87056a22fd10.png)

**Comment by ericwq** [comment]
for NvChad, `packer.nvim` should be installed in ***opt*** directory instead of ***start*** directory.
see [here](https://github.com/NvChad/NvChad/blob/main/lua/plugins/packerInit.lua#L6)

**Comment by linuxmobile** [comment]
> for NvChad, `packer.nvim` should be installed in _**opt**_ directory instead of _**start**_ directory. see [here](https://github.com/NvChad/NvChad/blob/main/lua/plugins/packerInit.lua#L6)

It's looks fine... 

![image](https://user-images.githubusercontent.com/10554636/151032224-1bf6c23c-3339-43f7-b489-28dd40e76e3e.png)

**Comment by siduck** [comment]
share that usercrome.css here

**Comment by linuxmobile** [comment]
> share that usercrome.css here

https://github.com/linuxmobile/dwm-dots/blob/main/.mozilla/firefox/userChrome.css

**Comment by siduck** [comment]
works here :l
