### ISSUE TITLE
Describe how to add an ftplugin

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#755]
I would like to add a file type plugin like [this](https://github.com/lervag/dotvim/blob/d4b3effb5f26c7559ee90305f86759e80b3826bb/personal/ftplugin/markdown.vim). The docs don't seem to clarify if this is possible and if so, how.

**Describe the solution you'd like**
Update docs to add this.

**Describe alternatives you've considered**
Rewriting ftplugin in python.

**Comment by siduck** [comment]
you can either convert that whole file into lua or just source it 

vim.cmd "source ~/.config/nvim/yourfile.vim"

**Comment by siduck** [comment]
there's a treesitter for markdown tho
