### ISSUE TITLE
Mention ripgrep as a pre-requisite

### ISSUE THREAD

**Issue by sfc-gh-mkeller** [NvChad/NvChad#756]
**Is your feature request related to a problem? Please describe.**
When I installed NvChad the [pre-requisite docs](https://nvchad.github.io/getting-started/setup#pre-requisites) never say to install ripgrep for the live grep to work.

**Describe the solution you'd like**
Have `ripgrep` mentioned as a pre-requisite and have https://github.com/BurntSushi/ripgrep#installation linked.

**Comment by peppapig450** [comment]
When was this removed? I could've sworn it was mentioned in there

**Comment by siduck** [comment]
oh oops! i thought ripgrep was required only for telescope media, my bad i removed it before. Its re-added now!
