### ISSUE TITLE
plugin config replace in chadrc.lua not work

### ISSUE THREAD

**Issue by oliverdding** [NvChad/NvChad#757]
## description
Below is my `chadrc.lua`:

```lua
local M = {}

M.plugins = {
    default_plugin_config_replace = {
        nvim_tree = {
            view = {side = 'right', auto_resize = true},
            trash = {cmd = "rmtrash", require_confirm = true}
        }
    }
}

return M
```

and I add a `vim.inspect` on the configuration object passed to `nvimtree.setup():

![image](https://user-images.githubusercontent.com/43624923/151116876-b19c23cf-cee6-4d84-9741-953c26d94b09.png)

After starting the nvim, and pressing `<leader>e` to start nvim-tree, nvim printed the `default` object as below:

```
{
  auto_close = false,
  disable_netrw = true,
  filters = {
    dotfiles = false
  },
  git = {
    enable = false,
    ignore = false
  },
  hijack_cursor = true,
  hijack_netrw = true,
  ignore_ft_on_setup = { "dashboard" },
  open_on_tab = false,
  update_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = false
  },
  view = {
    allow_resize = true,
    hide_root_folder = true,
    side = "left",
    width = 25
  }
}
```

## Environment
 - macOS 12.1 21C52 x86_64
 - iTerm2
 - NVIM v0.6.0

**Comment by oliverdding** [comment]
I found that NVIM v0.6.1 worked as expected... So I'm closing this issue...

**Comment by mgray88** [comment]
Can we reopen this? Same environment (except I have v0.6.1 already), same steps, yet I have the same issue

**Comment by oliverdding** [comment]
@mgray88 You'd better take a look at [this](https://github.com/NvChad/NvChad/issues/769), introducing a breaking changes on configuring user's plugin. And it works as expected on my environment.

**Comment by mgray88** [comment]
Hmm. Having just installed NvChad, and followed the docs pretty precisely, I'm not seeing where I went wrong. Everything else in this config works:
```
M.plugins = {
    status = {
        colorizer = true,
    },
    options = {
        statusline = {
            style = "arrow",
        },
    },
    default_plugin_config_replace = {
        nvimtree = {
            lazy_load = true,
            view = {
                hide_root_folder = false,
            },
        },
    },
    install = userPlugins,
}
```

<img width="752" alt="Screen Shot 2022-02-20 at 08 35 02" src="https://user-images.githubusercontent.com/411747/154845237-474ea164-fff1-4f14-bc06-42d33467227a.png">

**Comment by siduck** [comment]
its nvim_tree

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/154847119-1749b905-7fe0-4d5c-9159-8a6d958783a6.png)
nvimtree's packer definition. the first arg is used for plugin replace

**Comment by mgray88** [comment]
🤦 
Many thanks. I was looking at the `plugins.options` section

**Comment by neevek** [comment]
I have the same problem, though I alreay have `0.6.1` and I have updated to the latest NvChad.

I was trying to enlarge the nvim-tree's width, but `default_plugin_config_replace` seems not working. With the following configuration, I can confirm the `options` section and `install` both work.

```lua
-- custom/chadrc.lua
M.plugins = {
  options = {
    statusline = {
      style = "arrow",
    },
  },

  default_plugin_config_replace = {
    nvim_tree = {
      view = {
        width = 35,
      },
    },
  },

  install = userPlugins,
}
```

**Comment by siduck** [comment]
do packersync, works fine here

**Comment by neevek** [comment]
> do packersync, works fine here

Yes it works. Thnaks.

**Comment by siduck** [comment]
> > do packersync, works fine here
> 
> Yes it works. Thnaks.

cool! feel free to ask more help :)

**Comment by siduck** [comment]
> > do packersync, works fine here
> 
> Yes it works. Thnaks.

cool! feel free to ask more help :)

**Comment by neevek** [comment]
Hi, @siduck , I think I run into another problem related to this one.

I have the following configuration to enable `bufferline`'s `diagnostics_indicator`, but it does't work. If I put this configuration directly in `plugins/configs/bufferline.lua`'s `default.options` section, it works as expected.
I did run `PackerSync` and restarted `nvim` without effect.

```lua
M.plugins = {
    bufferline = {
      diagnostics = "nvim_lsp",
      diagnostics_indicator = function(count, level, diagnostics_dict, context)
        local icon = level:match("error") and "" or ""
        return " " .. icon .. count
      end,
    },
  },
```

**Comment by siduck** [comment]
@neevek 

```
   bufferline = {
         options = {
            diagnostics = "nvim_lsp",
            diagnostics_indicator = function(count, level, diagnostics_dict, context)
               local icon = level:match "error" and "" or ""
               return " " .. icon .. count
            end,
         },
      },
      ```
      
      do packercompile

**Comment by neevek** [comment]
> @neevek do packercompile
> 
> ```
>    bufferline = {
>          options = {
>             diagnostics = "nvim_lsp",
>             diagnostics_indicator = function(count, level, diagnostics_dict, context)
>                local icon = level:match "error" and "" or ""
>                return " " .. icon .. count
>             end,
>          },
>       },
>       
> ```

Thank you, this works.
Could you please elaborate on those minor differences of configurations, so I can fix it myself in the future:

1. What's the difference of putting plugin configurations in `M.plugins.options` and in `M.plugins.default_plugin_config_replace`?
2. When using `default_plugin_config_replace`, why some plugins need to put configurations in the `options` table (like `bufferline`), some others don't (like `nvim_tree`)? I tried reading the code, but still didn't figure it out.

**Comment by siduck** [comment]
@neevek u need to use the options table for bufferline cuz it has an options table in its default table where as most plugins like nvimtree just have a default table 

![image](https://user-images.githubusercontent.com/59060246/158042528-f234f112-b9aa-40d0-9909-2e61ab021b39.png)

plugins.default_plugin_config_replace  stuff just merges your table into the default table of that plugin

**Comment by siduck** [comment]
and the M.plugins.options just have settings for some plugins only (not all!) . Basically nvchad takes the tables from chadrc and then overrides the default table ( default_config.lua ) so 

- default_config.lua ( default nvchad settings in the form of tables )
- chadrc.lua ( user settings in the form of tables , basically can also be a copy of default_config.lua but only selected parts like if i just want to change theme then im gonna use M.ui, no  need to add whole default_config's table! )

**Comment by neevek** [comment]
> and the M.plugins.options just have settings for some plugins only (not all!) . Basically nvchad takes the tables from chadrc and then overrides the default table ( default_config.lua ) so
> 
> * default_config.lua ( default nvchad settings in the form of tables )
> * chadrc.lua ( user settings in the form of tables , basically can also be a copy of default_config.lua but only selected parts like if i just want to change theme then im gonna use M.ui, no  need to add whole default_config's table! )

This makes a lot of sense, thank you for the hardwork, this is a great project.
