### ISSUE TITLE
[confused] should I manage lsp and completion stuff in my own init.lua file?

### ISSUE THREAD

**Issue by oliverdding** [NvChad/NvChad#758]
## Question

As the issue describes, user should manage their lsp and completion stuff on their own, but I found that everything are still there:

![image](https://user-images.githubusercontent.com/43624923/151285619-8f6c06f6-1c18-4b40-bc23-3647471da425.png)

So should I disable all related stuff in chadrc.lua and provide my own configuration in init.lua?

Will the lsp and completion stuff remove some time later?

(BTW, gitter chat seems down now...

**Comment by siduck** [comment]
sorry for the confusion! do  https://github.com/NvChad/NvChad/issues/748#issuecomment-1022313066

**Comment by siduck** [comment]
we no longer use gitter, try https://discord.com/invite/gADmkJb9Fb

**Comment by oliverdding** [comment]
> 

It seems that I cannot accept the invatition.
