### ISSUE TITLE
statusline display error

### ISSUE THREAD

**Issue by ttw1018** [NvChad/NvChad#759]
This is something wrong with the display of status line. I've tried several nerd font,  the problem is still.
I'am using iTerm2 with Code New Roman Nerd Font.

![problems](https://user-images.githubusercontent.com/48583236/151561069-e40b8ab3-a7a1-480d-b74e-f0a3bb29458d.png)

**Comment by peppapig450** [comment]
I had lots of problems with iterm2 so I switched to kitty

**Comment by siduck** [comment]
@ttw1018 terminal issue most likely, try kitty/ alacritty or wezterm

**Comment by SakeyJakey** [comment]
Did you change your terminal font to the nerd font or just install it?

**Comment by ttw1018** [comment]
Recommend to switch to alacritty, it displays well  in alacritty.
