### ISSUE TITLE
Dashboard plugin missing

### ISSUE THREAD

**Issue by ankitpal1029** [NvChad/NvChad#760]
i didn't get the dashboard screen even if my screen is empty
it doesn't appear in my list of plugins either
![image](https://user-images.githubusercontent.com/49815751/151630497-b7325290-6d58-42d0-875e-dba03dd5e5e7.png)

if i try installing it i get this error message
![image](https://user-images.githubusercontent.com/49815751/151630621-71cd7b91-c51f-4735-9a5d-6f555f934ac4.png)
can someone help me out in this regard?

**Comment by siduck** [comment]
its disabled my default. so enable it in the status table of plugins table in chadrc.
