### ISSUE TITLE
NvChadUpdate delete modifications to files tracked by Git

### ISSUE THREAD

**Issue by rfc2119** [NvChad/NvChad#762]
**Describe the bug**
`NvChadUpdate` command deletes local modifications to files tracked in Git (even those under _lua/custom_) even if you answered "N" to the warning

**To Reproduce**
1. cd ~/.config/nvim
2. echo "-- test" >> init.lua
3. nvim -c "NvUpdateChad"
4. Answer with "N" and exit

**Expected behavior**
Edited file should contain my modification, even if it's a core repository file tracked in Git. In my case, I was on a branch off main that tracked my _custom_ folder and I lost all my modifications in _lua/custom/init.lua_

**Desktop**
 - OS: Ubuntu 20.04.1
 - Terminal: Deepin Terminal
 - Version of Neovim: 0.6.0

**Comment by Akianonymus** [comment]
Probably some edgecase i missed, will look into it.
