### ISSUE TITLE
Error when using telescope Live Grep

### ISSUE THREAD

**Issue by MarcoVitangeli** [NvChad/NvChad#763]
Hi! I have the problem that when opening a "home level" file or directory, the live grep telescope freezes and I have to quit terminal.

1. Go to  ~
2. open terminal and do 'nvim some_file'
3. open telescope live_grep
4. search for something

It should be looking for the string but instead it freezes

Desktop :
 - Ubuntu 20.04
 - gnome-terminal
 - Neovim 0.6.1

NOTE: this does not happen with big directories that are below home, I opened my work folders with multiple files and nothing happened

**Comment by siduck** [comment]
because home dir is very huge so it freezes. Not a nvchad issue! if you want to live grep then try snap

**Comment by peppapig450** [comment]
this is probably a ripgrep issue. I don't think it should freeze.
Then again it is Ubuntu with Gnome so is probably Gnome's fault somehow
