### ISSUE TITLE
Tab behaves weird with luasnip 

### ISSUE THREAD

**Issue by socialsmoker223** [NvChad/NvChad#764]
**Describe the bug**
Cannot use tab ans s-tab to jump between the snippet sections

**To Reproduce**
1. insert a snippet with multi-stops
2. press tab to trigger the jump action

**Expected behavior**
tab and s-tab is used to jump forward and backward in a snippet e.g. $1 to $2 and finally to $0

**Screenshots**
![tab](https://user-images.githubusercontent.com/64748277/151670668-32c688d5-1aa3-485c-b0be-153c9b3851ab.gif)
pressing tab should be jumping to title, other settings, and under /maketitle

**Desktop (please complete the following information):**
 - Operating System: Arch
 - Terminal: st
 - Version of Neovim: v0.6.1

**Additional context**

**Comment by siduck** [comment]
did you update rn?

**Comment by socialsmoker223** [comment]
> did you update rn?
yes

**Comment by siduck** [comment]
Im unable to see the cursor due to screenkey

**Comment by gitaarik** [comment]
I'm trying the latest version now, and it doesn't seem to be working for me. Are you supposed to be able to jump to the next parameter of a function with `<Tab>` when you see the snippet popup? I just get a tab indentation in my code.

![Peek 2023-12-09 19-33](https://github.com/NvChad/NvChad/assets/2470302/9a33ab62-8e7d-46da-abed-e85a31ae4b76)

**Comment by siduck** [comment]
tab just cycles through next item in completion, totally unrelated to function parameters @gitaarik

**Comment by gitaarik** [comment]
oh, aha, sorry ;), and thanks!

**Comment by siduck** [comment]
> oh, aha, sorry ;), and thanks!

https://www.reddit.com/r/neovim/comments/13ol3vb/manipulating_and_moving_between_function/
