### ISSUE TITLE
Override Entire Packer Use Table

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#765]
So I think that if nothing else, the whole LSP issue from a bit ago went to show that there is always going to be some niche case in which a user wants to override multiple settings like load order (after, wants, etc) or something else. For instance, I often use forks of plugins that are in the NvChad init.lua for unmerged PRs to test out features or implement my own. 

Also, since I recently did a massive overhaul and reorganization of my LSP and completion setup which improved performance and functionality so much I'll likely PR it soon, which made changes to load order, the use for this type of thing has become pretty apparent to me, as I have to use an edited version of NvChad's init.lua I maintain on my own.

I spent some time thinking about it and came up with a solution that I currently have working but wanted to hear your thoughts regarding this idea @siduck @Akianonymus  before I put too much work into cleaning up parts of the code base it renders unnecessary and organizing.

**Comment by siduck** [comment]
@zbirenbaum yes I was thinking about this too, we can simply use a table instead of function in packer's startup 

see https://github.com/lewis6991/dotfiles/blob/master/config/nvim/lua/lewis6991/plugins.lua#L359 (init is a table in this line)

**Comment by zbirenbaum** [comment]
> @zbirenbaum yes I was thinking about this too, we can simply use a table instead of a function in packer's startup 
> 
> 
> 
> see https://github.com/lewis6991/dotfiles/blob/master/config/nvim/lua/lewis6991/plugins.lua#L359 (init is a table in this line)

Lol that's exactly what I did. I'll go ahead and finish it up today and submit a PR!

**Comment by siduck** [comment]
> > @zbirenbaum yes I was thinking about this too, we can simply use a table instead of a function in packer's startup
> > see https://github.com/lewis6991/dotfiles/blob/master/config/nvim/lua/lewis6991/plugins.lua#L359 (init is a table in this line)
> 
> Lol that's exactly what I did. I'll go ahead and finish it up today and submit a PR!

I guess you need to change stuff for customPlugins too, since user's defined plugins are gonna be in a table too so we need to remove hooks stuff too!

**Comment by zbirenbaum** [comment]
> I guess you need to change stuff for customPlugins too, since user's defined plugins are gonna be in a table too so we need to remove hooks stuff too!

yeah that's what I meant by cleaning up parts of the code base, shouldn't be too hard though.

**Comment by zbirenbaum** [comment]
> I guess you need to change stuff for customPlugins too, since user's defined plugins are gonna be in a table too so we need to remove hooks stuff too!

I'm on the last couple small edits before I submit but I wanted to check in on this. Right now the user still adds plugins from init.lua, but overrides or removes from chadrc. 

Do we want to change that so custom.init.lua is just a table which gets merged in to the main one? I know that's what you implied before but that's a pretty big breaking change and wanted to make sure. It may confuse users which are coming to NvChad as well since it would be very contrary to the normal method of adding plugins.

**Comment by siduck** [comment]
@zbirenbaum  
![image](https://user-images.githubusercontent.com/59060246/164955381-77f7032c-43ac-4dbd-b750-5b1af37868e8.png)

i was thinking about adding this syntax for defining plugins, but it doesnt work for me. How did you make it work?

**Comment by zbirenbaum** [comment]
> @zbirenbaum
> 
> ```
>    ["andymass/vim-matchup"] = {
>       opt = true,
>       setup = function()
>          require("core.utils").packer_lazy_load "vim-matchup"
>       end,
>    },
> ```
> 
> i was thinking about adding this syntax for defining plugins, but it doesnt work for me. How did you make it work before?

It’s always worked, I still have it in my custom config. The whole table just needs to be the same format whichever it is.

**Comment by zbirenbaum** [comment]
@siduck if you want to change it to that let me handle it, because there are places elsewhere in utils it will let me simplify.

**Comment by siduck** [comment]
> @siduck if you want to change it to that let me handle it, because there are places elsewhere in utils it will let me simplify.

yea show the utils part!

**Comment by siduck** [comment]
@zbirenbaum why doesnt this work :/

```local plugin_settings = require("core.utils").load_config().plugins
local present, packer = pcall(require, plugin_settings.options.packer.init_file)

if not present then
   return false
end

local plugins = {
   ["nvim-lua/plenary.nvim"] = {},
   ["lewis6991/impatient.nvim"] = {},
   ["nathom/filetype.nvim"] = {},

   ["wbthomason/packer.nvim"] = {
      event = "VimEnter",
   },

   ["NvChad/extensions"] = {
      config = function()
         vim.schedule_wrap(require("nvchad.terminal").init())
      end,
   },

   ["NvChad/nvim-base16.lua"] = {
      after = "packer.nvim",
      config = function()
         require("colors").init()
      end,
   },

   ["kyazdani42/nvim-web-devicons"] = {
      after = "nvim-base16.lua",
      config = function()
         require "plugins.configs.icons"
      end,
   },

   ["feline-nvim/feline.nvim"] = {
      after = "nvim-web-devicons",
      config = function()
         require "plugins.configs.statusline"
      end,
   },

   ["akinsho/bufferline.nvim"] = {
      after = "nvim-web-devicons",

      setup = function()
         require("core.mappings").bufferline()
      end,

      config = function()
         require "plugins.configs.bufferline"
      end,
   },

   ["lukas-reineke/indent-blankline.nvim"] = {
      event = "BufRead",
      config = function()
         require("plugins.configs.others").blankline()
      end,
   },

   ["NvChad/nvim-colorizer.lua"] = {
      event = "BufRead",
      config = function()
         require("plugins.configs.others").colorizer()
      end,
   },

   ["nvim-treesitter/nvim-treesitter"] = {
      event = { "BufRead", "BufNewFile" },
      run = ":TSUpdate",
      config = function()
         require "plugins.configs.treesitter"
      end,
   },

   -- git stuff
   ["lewis6991/gitsigns.nvim"] = {
      opt = true,
      config = function()
         require("plugins.configs.others").gitsigns()
      end,
      setup = function()
         require("core.utils").packer_lazy_load "gitsigns.nvim"
      end,
   },

   -- lsp stuff

   ["neovim/nvim-lspconfig"] = {
      module = "lspconfig",
      opt = true,
      setup = function()
         require("core.utils").packer_lazy_load "nvim-lspconfig"
         -- reload the current file so lsp actually starts for it
         vim.defer_fn(function()
            vim.cmd 'if &ft == "packer" | echo "" | else | silent! e %'
         end, 0)
      end,
      config = function()
         require "plugins.configs.lspconfig"
      end,
   },

   ["ray-x/lsp_signature.nvim"] = {
      after = "nvim-lspconfig",
      config = function()
         require("plugins.configs.others").signature()
      end,
   },

   ["andymass/vim-matchup"] = {
      opt = true,
      setup = function()
         require("core.utils").packer_lazy_load "vim-matchup"
      end,
   },

   ["max397574/better-escape.nvim"] = {
      event = "InsertCharPre",
      config = function()
         require("plugins.configs.others").better_escape()
      end,
   },

   -- load luasnips + cmp related in insert mode only

   ["rafamadriz/friendly-snippets"] = {
      module = "cmp_nvim_lsp",
      event = "InsertEnter",
   },

   ["hrsh7th/nvim-cmp"] = {
      after = "friendly-snippets",
      config = function()
         require "plugins.configs.cmp"
      end,
   },

   ["L3MON4D3/LuaSnip"] = {
      wants = "friendly-snippets",
      after = "nvim-cmp",
      config = function()
         require("plugins.configs.others").luasnip()
      end,
   },

   ["saadparwaiz1/cmp_luasnip"] = {
      after = "LuaSnip",
   },

   ["hrsh7th/cmp-nvim-lua"] = {
      after = "cmp_luasnip",
   },

   ["hrsh7th/cmp-nvim-lsp"] = {
      after = "cmp-nvim-lua",
   },

   ["hrsh7th/cmp-buffer"] = {
      after = "cmp-nvim-lsp",
   },

   ["hrsh7th/cmp-path"] = {
      after = "cmp-buffer",
   },

   -- misc plugins
   ["windwp/nvim-autopairs"] = {
      after = plugin_settings.options.autopairs.loadAfter,
      config = function()
         require("plugins.configs.others").autopairs()
      end,
   },

   ["goolord/alpha-nvim"] = {
      disable = true,
      config = function()
         require "plugins.configs.alpha"
      end,
   },

   ["numToStr/Comment.nvim"] = {
      module = "Comment",
      keys = { "gcc" },

      setup = function()
         require("core.mappings").comment()
      end,

      config = function()
         require("plugins.configs.others").comment()
      end,
   },

   -- file managing , picker etc
   ["kyazdani42/nvim-tree.lua"] = {
      after = "nvim-web-devicons",
      cmd = { "NvimTreeToggle", "NvimTreeFocus" },

      setup = function()
         require("core.mappings").nvimtree()
      end,

      config = function()
         require "plugins.configs.nvimtree"
      end,
   },

   ["nvim-telescope/telescope.nvim"] = {
      module = "telescope",
      cmd = "Telescope",

      setup = function()
         require("core.mappings").telescope()
      end,

      config = function()
         require "plugins.configs.telescope"
      end,
   },
}

-- For now, testing the default config only

local testt = {}

-- Example :
--[[

 ["goolord/alpha-nvim"] = {
      disable = true,
      config = function()
         require "plugins.configs.alpha"
      end,
   },

   will get converted to =>
  
   {
     "goolord/alpha-nvim",
      disable = true,
      config = function()
         require "plugins.configs.alpha"
      end,
   },

   and then pushed to testt table
--]]

for key, _ in pairs(plugins) do
   plugins[key][1] = key
   testt[#testt + 1] = plugins[key]
end

return packer.startup(function(use)
   for _, v in pairs(testt) do
      use(v)
   end
end)
```

**Comment by siduck** [comment]
I dont see any error but I dont see any plugins EITHER!

![image](https://user-images.githubusercontent.com/59060246/164959767-1c3b216e-a235-42ce-9e38-5d611455a71d.png)

even tho packerstatus seems to be simple 

![image](https://user-images.githubusercontent.com/59060246/164959815-f2b8d8ea-0d84-46e0-84df-034e383fb702.png)

**Comment by zbirenbaum** [comment]
@siduck you need both the first line and the one in the brackets to be the plugin name, you can't just put it in the brackets and take it out of the actual table. Having the key be the same as the first value of the table just makes some plugin management stuff easier. See here

https://github.com/zbirenbaum/NvCustom/plugins_table.lua

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/164959873-0e1ca695-7acc-45cb-a87a-c2453fc0fc84.png)

OOPS!

**Comment by siduck** [comment]
Oh ik about this 
![image](https://user-images.githubusercontent.com/59060246/164959886-f6613584-6381-49b4-b5fc-728d3d218329.png)

The syntax would look crowded imo so I didnt wanted it

**Comment by zbirenbaum** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/164959873-0e1ca695-7acc-45cb-a87a-c2453fc0fc84.png)
> 
> 
> 
> OOPS!

Yeah i fixed it. Just go to plugins_table in the repo I edited to

**Comment by zbirenbaum** [comment]
> Oh ik about this 
> 
> ![image](https://user-images.githubusercontent.com/59060246/164959886-f6613584-6381-49b4-b5fc-728d3d218329.png)
> 
> 
> 
> The syntax would look crowded imo so I didnt wanted it

If you use folds it's actually less crowded because all that will show is the plugin name when the table is folded.

**Comment by zbirenbaum** [comment]
I will say the way you had it just now does look better though, so maybe I'll PR packer to support it.

**Comment by siduck** [comment]
> I dont see any error but I dont see any plugins EITHER!
> 
> ![image](https://user-images.githubusercontent.com/59060246/164959767-1c3b216e-a235-42ce-9e38-5d611455a71d.png)
> 
> even tho packerstatus seems to be simple
> 
> ![image](https://user-images.githubusercontent.com/59060246/164959815-f2b8d8ea-0d84-46e0-84df-034e383fb702.png)

Nvm i fixed this @zbirenbaum and default plugin table works but I have issue when merging the user table 

![image](https://user-images.githubusercontent.com/59060246/164960088-400be806-f6ce-433d-b6ef-aa3c8df44df5.png)

![image](https://user-images.githubusercontent.com/59060246/164960107-8c158ed6-7777-4204-b852-7e69926e1e66.png)

**Comment by siduck** [comment]
Even tho the user plugins table isnt a nil value 
![Uploading image.png…]()

**Comment by zbirenbaum** [comment]
@siduck you can't just set the first table value to key, it will overwrite it, and you also can't use table.insert because you will have to shift the entire table up an index to do so and that is ungodly inefficient. 

This would probably have to be upstreamed in packer to be done efficiently. Right now you are overwriting part of your config. I can take a look at this tomorrow but please don't push any changes related to this, as I have the plugin merge set up very carefully.

**Comment by siduck** [comment]
@zbirenbaum the first table value gets set to the string and not the key :l , I tested this.

**Comment by zbirenbaum** [comment]
> @zbirenbaum the first table value gets set to the string and not the key :l , I tested this.

The key is a string.

**Comment by siduck** [comment]
yes so the code still does work 

```lua

 ["goolord/alpha-nvim"] = {
      disable = true,
   },

   will get converted to =>
  
   {
     "goolord/alpha-nvim",
      disable = true,
   },
   ```

**Comment by zbirenbaum** [comment]
> yes so the code still does work 
> 
> 
> 
> ```lua
> 
> 
> 
>  ["goolord/alpha-nvim"] = {
> 
>       disable = true,
> 
>    },
> 
> 
> 
>    will get converted to and pushed into another table =>
> 
>   
> 
>    {
> 
>      "goolord/alpha-nvim",
> 
>       disable = true,
> 
>    },
> 
>    ```

No. It will be 

["goolord/alpha-nvim"] = {
   disable = true,
},

To 

["goolord/alpha-nvim"] = {
   "goolord/alpha-nvim",
},

**Comment by zbirenbaum** [comment]
And as I said, while you could use table.insert to avoid that, you would be slowing it down tremendously. By a factor of up to 5x or more.

**Comment by siduck** [comment]
im just doing this locally lul

**Comment by zbirenbaum** [comment]
I suppose a slightly better way would be to save the current 1st value in a temp var and then just add it to the end since packer doesn't care about order other than the plugin being the first value, but you would still be performing double the current operations.

**Comment by siduck** [comment]
> > yes so the code still does work
> > ```lua
> >  ["goolord/alpha-nvim"] = {
> > 
> >       disable = true,
> > 
> >    },
> > 
> > 
> > 
> >    will get converted to and pushed into another table =>
> > 
> >   
> > 
> >    {
> > 
> >      "goolord/alpha-nvim",
> > 
> >       disable = true,
> > 
> >    },
> > ```
> 
> No. It will be
> 
> ["goolord/alpha-nvim"] = { disable = true, },
> 
> To
> 
> ["goolord/alpha-nvim"] = { "goolord/alpha-nvim", },

![image](https://user-images.githubusercontent.com/59060246/164960774-6685b149-8dfe-425d-bf0a-f6b6a5384e3e.png)

**Comment by zbirenbaum** [comment]
Can you try printing the resulting table with vim.inspect

**Comment by zbirenbaum** [comment]
Oh I see, since all the other parts of the config have keys it works. Yeah that's fine then until user config has things in a different format and then you have to convert.

**Comment by siduck** [comment]
> Oh I see, since all the other parts of the config have keys it works. Yeah that's fine then until user config has things in a different format and then you have to convert.

yea that works, the issue is with merging the user table with default plugin table. 

For example 

![image](https://user-images.githubusercontent.com/59060246/164960936-9dec2a81-f6b9-4247-926b-b539f0764840.png)


:((

**Comment by zbirenbaum** [comment]
> > Oh I see, since all the other parts of the config have keys it works. Yeah that's fine then until user config has things in a different format and then you have to convert.
> 
> 
> 
> yea that works, the issue is with merging the user table with default plugin table. 
> 
> 
> 
> For example ( d.lua is loaded in init.lua )
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/59060246/164960936-9dec2a81-f6b9-4247-926b-b539f0764840.png)
> 
> 
> 
> 
> 
> :((

I can write something to make it work tomorrow. It's 3am here so I can't help with this any more for the moment.

**Comment by siduck** [comment]
oh oops, you should be sleeping at the moment. /ban @zbirenbaum  :laughing:

**Comment by siduck** [comment]
nvm Im dumb, I was using vim.tbl.deep_extend but its vim.tbl_deep_extend :stuck_out_tongue_closed_eyes:
