### ISSUE TITLE
[HELP] How do I add `colorcolumn`?

### ISSUE THREAD

**Issue by asher-gh** [NvChad/NvChad#766]
I have used the `M.options` for setting other options but `colorcolumn` is not working for me.

**Comment by siduck** [comment]
you can only override default options from M.options. so basically do vim.o.colorcolumn =stuff in your custom/init.lua or anywhere in custom dir. Read our docs to understand our config well

**Comment by vitosans** [comment]
I know this is closed, but this does not seem to work for me: 

pwd (.config/nvim/lua/custom)

file init.lua

vim.opt.colorcolumn = "80"
vim.o.colorcolumn = "80"
vim.cmd([[ set colorcolumn=80 ]])

:set colorcolumn=
