### ISSUE TITLE
BREAKING CHANGE WITH INSTALLING PLUGINS

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#769]
I had cleaned packer config  https://github.com/NvChad/NvChad/commit/64c32d2e5e958c70154a4ecd17a771123d0a5662

https://nvchad.github.io/config/Custom%20config#add-plugins

**Comment by ElSamhaa** [comment]
@siduck My overrides doesn't work anymore? Here is the corresponding change.
![image](https://user-images.githubusercontent.com/34912861/151695824-9f65ae9e-d081-4bbc-8094-d6353ac2a5d9.png)

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/151697@ElSamhaa -9c43ee53-67ef-483c-a3b5-1a43997fcd75.mp4

@ElSamhaa works fine here. did you do leader uu + packersync?

**Comment by ElSamhaa** [comment]
@siduck yes I've done a `PackerSync`. The issue is with the `ui.hl_overrides` which seems to be deprioritized -- or not loaded -- after the latest changes.

No changes were made to that file, only changes to `custom/init.lua` and `custom/chadrc.lua` corresponding to your latest commit.

**Comment by ElSamhaa** [comment]
@siduck Resolved now :+1: .

The mistake was in the `M.plugins.install = require "custom.plugins"` -> `M.plugins.install = require "custom"`.
As `init.lua` is under `custom` not `custom/plugins`. I think an update to the docs/guide is required?

**Comment by siduck** [comment]
> @siduck Resolved now +1 .
> 
> The mistake was in the `M.plugins.install = require "custom.plugins"` --> `M.plugins.install = require "custom"`. As `init.lua` is under `custom` not `custom/plugins`. I think an update to the docs/guide is required?

https://nvchad.github.io/config/Custom%20config#add-plugins

**Comment by hunger** [comment]
@siduck: The switch was straight forward for me, following the docs linked here. Everything works as before. 👍🏼

**Comment by ElSamhaa** [comment]
@hunger The docs has an explicit mention of `custom/init.lua` and an implicit mention of `custom/plugins/init.lua`. This might be a source of confusion for neovim-rookies like me.

**Comment by hunger** [comment]
@ElSamhaa: What I did is this:
 1. copy my `lua/custom/init.lua` to `lua/custom/plugins.lua`
 2. edit `lua/custom/init.lua` to remove all the plugin stuff
 3. edit `lua/custom/plgins.lua` according to the docs: Basically remove everything but the plugins, put those in a table and strip out the `use`.
 4. Add the two lines from the docs to `lua/custom/chadrc` so that my plugins will get loaded.

**Comment by siduck** [comment]
> @hunger The docs has an explicit mention of `custom/init.lua` and an implicit mention of `custom/plugins/init.lua`. This might be a source of confusion for neovim-rookies like me.

custom/plugins/init.lua is just an example. you can use any file in custom dir and use its path
