### ISSUE TITLE
Request for notice when making breaking changes

### ISSUE THREAD

**Issue by MarkusSagen** [NvChad/NvChad#770]
Want to start of by saying that I love the NvChad project.
What I think could be improved and cause fewer issues down the line is more clear communication when it comes to breaking changes or migration guides. For instance, the latest change seem to move package installations to `chadrc.lua` instead of `init.lua`. This can easy fix by the user, but I think that you shouldn't have to look into each pull request to know before-hand if fetching a new update will break your existing NvChad configs. 

Suggestions:
- When fetching new releases (`<leader>uu`) provide info on what breaking changes will occur before fetching
- Have a place to inform on new releases (discussion page, issue new releases, or even on the README landing page)

**Comment by siduck** [comment]
I'll keep this in mind next time! @MarkusSagen . Thanks for your input!

**Comment by MarkusSagen** [comment]
Oh, sorry! Didn't see that there was a closed issue for this already!
