### ISSUE TITLE
Autowrite on focus lost

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [NvChad/NvChad#773]
How can I add this? It would be nice to have as a default. Either that or autowrite on exiting insert mode.
```
augroup configgroup
    autocmd!
    " save all files on focus lost, ignoring warnings about untitled buffers
    autocmd FocusLost * silent! wa
augroup END
```

I think it would be:
```
vim.api.nvim_command([[
augroup configgroup
   autocmd!
   " save all files on focus lost, ignoring warnings about untitled buffers
   autocmd FocusLost * silent! wa
augroup END 
]])
```

**Comment by mikededo** [comment]
Check the [`autocmds`](https://nvchad.github.io/config/Custom%20config#autocmds) documentation. May be what you are looking for.

**Comment by siduck** [comment]
@HarleyQuinn-Z6 yes the later (lua code) or you can store the autocmds into a file i.e chad.vim  and source that file in your custom/init.lua like : 

vim.cmd "source path to chad.vim"

**Comment by HarleyQuinn-Z6** [comment]
Thanks, you should clarify that in the docs.
```
Autocmds#

    Well, for example you just create a new file called autochad_cmds.lua in the custom folder and require it in the init.lua file of the custom folder! BOOOM!!
```
