### ISSUE TITLE
Custom plugin 

### ISSUE THREAD

**Issue by mikededo** [NvChad/NvChad#774]
**Describe the bug**

It does not properly sync if there's only one plugin in the table assigned to the custom props `install` value.

**To Reproduce**

1. Reproduce the installation as explained in the documentation.
2. Copy the `/examples` folder in the `/lua/custom` folder, as explained in the documentation.
3. Modify the `/lua/custom/plugins.lua` file that has been copied from `/examples` as follows
```lua
-- Keep one of the two plugins
return {
  { "elkowar/yuck.vim", ft = "yuck", disable = 1 }
  -- { "ellisonleao/glow.nvim", cmd = "Glow" },
}
```
4. Open `nvim` and run `PackerSync`

**Expected behavior**

It should only install one plugin, the first one, yet it throws the error exposed above. I am no expert with lua and I have not been able to find why could the error be thrown. Is it due to how the prop `install` is parsed? Or it is because of something about `lua` that I am not aware? 😓 

**Screenshots**

No screenshot, but the error recieved is:

```shell
Error detected while processing command line:
E5100: Cannot convert given lua table: table should either have a sequence of positive integer keys or contain only string keys
E5108: Error executing lua error converting argument 1
stack traceback:
        [C]: in function 'expand'
        ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:182: in function 'manage'
        ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:171: in function 'manage'
        ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:320: in function 'manage_all_plugins'
        ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:530: in function 'sync'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Desktop (please complete the following information):**
 - Operating System: Manjaro
 - Terminal: Kitty
 - Version of Neovim: v0.6.1

**Additional context**

No.

**Comment by Akianonymus** [comment]
Try removing the disable flag

**Comment by mikededo** [comment]
It happens with any plugin that is there, as long as there is only one plugin.

**Comment by Akianonymus** [comment]
Will be fixed after the pr is merged..

https://github.com/NvChad/NvChad/pull/776
