### ISSUE TITLE
Deletion is slow

### ISSUE THREAD

**Issue by hunger** [NvChad/NvChad#788]
**Describe the bug**

When I want to delete several characters or lines in a file using `<del>`, `<bs>` or `<d>`, then I have to hit the key repeatedly. Key repeat is disabled.

This is not the case when I disable NvChad.

**To Reproduce**
1. Install standard NVChad from master, do not apply any customization.
2. Load a file
3. Hold down the `d` key in normal mode. Same is true for holding down the <bs>/<del> keys in insert mode.

**Expected behavior**

Holding down the `d` key will in time delete all lines in the file.

**Actual behavior**

One line is deleted, nothing happens afterwards.

**Desktop (please complete the following information):**
 - Linux
 - Kitty
 - Neovim 0.6.1

**Additional context**

The behavior persists when I start `neovim --noplugin`.

The expected behavior can be observed when I start neovim without loading NVchad.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/152088428-3a4a59b6-088b-4d40-99ae-456ceb078afe.mp4

I see no difference

**Comment by hunger** [comment]
I poked at the problem a bit: The problem vanishes as soon as I change the "clipboard" option to "".

I am on a wayland-only system, maybe the wayland copy/paste tools are too slow or something? I guess I'll have to make do with * and + buffers:-/

Thanks for testing!

I'll close this again: This is a problem with upstream neovim, not with NVchad. Sorry for sending you onto this wild goose chase!

**Comment by hunger** [comment]
I use `wl-paste` and `wl-copy` AFAICT.

But I run neovim inside a container, interacting with the compositor run on the bare metal. Maybe that is what causes the delay, so idea.

**Comment by siduck** [comment]
> I use `wl-paste` and `wl-copy` AFAICT.
> 
> But I run neovim inside a container, interacting with the compositor run on the bare metal. Maybe that is what causes the delay, so idea.

why container :/
