### ISSUE TITLE
[ISSUE] in case Shada file doesn't exist

### ISSUE THREAD

**Issue by ericwq** [NvChad/NvChad#793]
**Describe the bug**
for a fresh installation, such as :
```sh
docker run -w /root -it --rm alpine:edge sh -uelic '
    apk add git nodejs neovim ripgrep alpine-sdk --update
    git clone https://github.com/NvChad/NvChad ~/.config/nvim
    nvim -c "autocmd User PackerComplete quitall" -c "PackerSync"
    nvim'
```
nvim reports:
```txt
Error executing vim.schedule lua callback: /root/.config/nvim/lua/core/options.lua:80: Vim(rshada):E886: System error while opening ShaD
a file /root/.local/share/nvim/shada/main.shada for reading: no such file or directory
stack traceback:
        [C]: in function 'cmd'
        /root/.config/nvim/lua/core/options.lua:80: in function </root/.config/nvim/lua/core/options.lua:78>
```
**To Reproduce**
1. run the above docker command.

**Expected behavior**
no error reports, even for the first time nvim starts.

**Desktop (please complete the following information):**
 - Operating System: Mac OS Monterey, Docker desktop 4.4.2, 5.10.76-linuxkit
 - Terminal: Alacritty
 - Version of Neovim: 0.6.1

**Additional context**
I use the following commands as a work-around.
```dotfile
RUN nvim --headless -u NONE -c 'echo "init shadafile"' -c qall
RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

**Comment by siduck** [comment]
Ive not tried docker but I dont get this issue on my system tho

**Comment by siduck** [comment]
tested it rn and its stuck here 
![image](https://user-images.githubusercontent.com/59060246/152645208-e362418d-0d11-4bc8-9d21-2c2b9e33d38e.png)

**Comment by siduck** [comment]
```zsh
  docker run -w /root -it --rm alpine:edge sh -uelic '
    apk add git neovim ripgrep alpine-sdk --update
    git clone https://github.com/NvChad/NvChad ~/.config/nvim
    nvim --headless -u NONE -c 'echo "init shadafile"' -c qall
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
    nvim '

```

**Comment by siduck** [comment]
can you send a pr for this? https://github.com/NvChad/NvChad#try-nvchad-in-a-docker-container

**Comment by Akianonymus** [comment]
or just change `rsh` to `silent! rsh` in options.lua
