### ISSUE TITLE
NvChad update fails [Windows]

### ISSUE THREAD

**Issue by DirtySoc** [NvChad/NvChad#795]
**Describe the bug**
When trying to update NvChad with the built in update script, it fails on Windows.

**To Reproduce**
1. Open nvim
2. Run :NvChadUpdate or `<leader>-uu`

**Expected behavior**
NvChad updates successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/33207400/152275791-cb3551c2-0cb0-4ced-828c-784d1e0d6084.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Windows Terminal (PowerShell Core 7.1.5)
 - NeoVim 0.6.1

**Additional context**
N/A

**Comment by siduck** [comment]
well your .gir directory is removed so how will it update? backup your custom dir and re-clone the repo. move custom dir and packersync

**Comment by DirtySoc** [comment]
> well your .gir directory is removed so how will it update? backup your custom dir and re-clone the repo. move custom dir and packersync

I installed following the NvChad user install directions provided and don't regularly develop on vim extensions. I'm not sure what this means. Is the full neovim git repo supposed to be in this folder?

**Comment by siduck** [comment]
> > well your .gir directory is removed so how will it update? backup your custom dir and re-clone the repo. move custom dir and packersync
> 
> I installed following the NvChad user install directions provided and don't regularly develop on vim/neovim extensions. I'm not sure what this means. Is the full neovim git repo supposed to be in ~/AppData/Local/nvim on Windows?

im not sure how windows works so cant really help. Maybe @barungh can

**Comment by barungh** [comment]
![image](https://user-images.githubusercontent.com/12285528/152364045-5e82ba7c-7bc5-4558-9a44-b8e4cc9ad637.png)

Documentation clearly says that , it does `git reset --hard` 

so definitely, if you want Nvchad's update mechanism, then you nee to copy complete repository in `~/AppData/Local/nvim` 

I suggest if you want `<leader> + uu`  functionality, then you first move to `~/AppDatal/Local/`

*git clone* there 
and rename the folder to *nvim* 🤷🏻

**Comment by siduck** [comment]
@DirtySoc 
![image](https://user-images.githubusercontent.com/59060246/152366656-d1cf1a19-01a2-4605-abe4-b08624f08ebb.png)

**Comment by xarthurx** [comment]
> @DirtySoc ![image](https://user-images.githubusercontent.com/59060246/152366656-d1cf1a19-01a2-4605-abe4-b08624f08ebb.png)

I encounter exactly the same issue.
I think here the doc should say rename `NvChad` to `nvim`, instead of copying the `init.lua` and `lua` folder. 
If following the doc, no git info will be kept.

**Comment by siduck** [comment]
good point, i'll change it
