### ISSUE TITLE
impatient.nvim does not load custom config in consistant way

### ISSUE THREAD

**Issue by br1anchen** [NvChad/NvChad#798]
**Describe the bug**
By enabling `lewis6991/impatient.nvim`, I got inconsistent custom configuration loading result. 

**To Reproduce**
I tested with below use cases:
1. Enables `lewis6991/impatient.nvim` with rebased `Nvchad` changes with my local custom configuration:
    - custom plugin is still kept by `packer`
    - custom configuration for individual plugins does not apply
 2. Hard reset my local branch with `Nvchad` upstream `main` branch, without any local custom configuration:
    - run `:PackerSync`, all custom plugins removed (expected)
    -  Add new `custom` folder with previous custom configuration
    -  run `:PackerSync` again
    -  No custom plugins and configuration loaded (tested by `print` in `lua` module)
    - ref repo: https://github.com/br1anchen/NvChad/tree/brian/tmp-migrate
 3. Removing `impatient.nvim` related logic, re-apply local custom configuration
    - custom plugins are installed
    - custom configurations are applied

**Expected behavior**
Custom plugins should be installed and custom configuration should be applied with `impatient.nvim` enabled.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: macOs, arch linux
 - Terminal: Alacritty
 - Version of Neovim: NVIM v0.7.0-dev+907-g96aa7dd09

**Additional context**
This might be upstream issue with `lewis6991/impatient.nvim`, but it makes local changes within `lua` module very unstable.

**Comment by siduck** [comment]
impatient does work here, what doesnt actually work for u? custom plugins configs not setting up?

**Comment by villavicencio** [comment]
@br1anchen I noticed the same thing. After checking out the README for `lewis6991/impatient.nvim` I noted that it stores it's cache in `$XDG_CACHE_HOME/nvim/luacache`. Blowing that away and running PackerSync again fixed the problem for me.

**Comment by br1anchen** [comment]
Thanks @villavicencio , I think you can also use `:LuaCacheClear` to clear the cache and re-run `:PackerSync` after restart `neovim`.

**Comment by villavicencio** [comment]
Awesome, thanks for the tip, good for future reference and glad it worked!
