### ISSUE TITLE
Auto-Complete not working at NVIM 0.7.0

### ISSUE THREAD

**Issue by igorcguedes** [NvChad/NvChad#799]
Auto-Complete isnt working at NVIM 0.7.0

![image](https://user-images.githubusercontent.com/48987652/152468588-8b20151c-4b85-40b3-a490-8c363efd72f5.png)

Running into Gentoo, Kitty, nvim 0.7

**Comment by siduck** [comment]
nvchad supports 0.6.1 , also enable snippets in your chadrc and do packersync
