### ISSUE TITLE
Comment.nvim is never loaded

### ISSUE THREAD

**Issue by hunger** [NvChad/NvChad#801]
**Describe the bug**

The `Comment.nvim` plugin is never marked as loaded in `PackerStatus`. Not after startup, not after loading a file, not even after doing `<leader>/`.

Consequently none of the plugins functions actually work.

Once I run `:lua require('Comment').setup()` the I can start to toggle lines with `gcc`

**To Reproduce**

Start nvim, do `:PackerStatus`. Try doing `gcc` to toggle a line comment.

**Expected behavior**

I can use e.g. `gcc` to toggle comment lines.

**Comment by siduck** [comment]
comment.nvim loads on <leader>/ i.e it loads on that setup function

**Comment by siduck** [comment]
btw whats the difference between gcc and leader /

**Comment by siduck** [comment]
comment.nvim is lazy loaded at leader / so the gcc works after it.

**Comment by siduck** [comment]
do packercompile

**Comment by hunger** [comment]
`gcc`is just an example, the plugin defines several key bindings after all.

I just added `require('Comment').setup()` into my `lua/custom/init.lua` now. The plugin is not loaded after that is done (according to `PackerStatus`), but all the necessary bits and pieces are in place anyway and `gcc`and `<leader>/` both work as expected.

**Comment by siduck** [comment]
> `gcc`is just an example, the plugin defines several key bindings after all.
> 
> I just added `require('Comment').setup()` into my `lua/custom/init.lua` now. The plugin is not loaded after that is done (according to `PackerStatus`), but all the necessary bits and pieces are in place anyway and `gcc`and `<leader>/` both work as expected.

your pfp indeed looks scary :fearful: XD. Anyways if you totally want to change plugin's packer definition then check https://nvchad.github.io/config/Custom%20config#remove--redefine-plugins

**Comment by hunger** [comment]
After updating NVChad my require-workaround no longer works:-/

Check https://github.com/numToStr/Comment.nvim : This plugin defines a whole set of mappings! You made one of them work and left the rest broken. That is not much of a fix:-)

FWIW: AstroVim loads Comment.nvim on BufRead event (https://github.com/kabinspace/AstroVim/blob/0fdf5b48ebfa2008cf60697db6cc3f2032b8b136/lua/core/plugins.lua#L296). I am pretty sure that works better, but also loads this plugin earlier than strictly necessary.

**Comment by siduck** [comment]
> After updating NVChad my require-workaround no longer works:-/
> 
> Check https://github.com/numToStr/Comment.nvim : This plugin defines a whole set of mappings! You made one of them work and left the rest broken. That is not much of a fix:-)
> 
> FWIW: AstroVim loads Comment.nvim on BufRead event (https://github.com/kabinspace/AstroVim/blob/0fdf5b48ebfa2008cf60697db6cc3f2032b8b136/lua/core/plugins.lua#L296). I am pretty sure that works better, but also loads this plugin earlier than strictly necessary.

mappings like? also nvchad had breaking changes last week. Make sure you follow up with the pinned issues

**Comment by hunger** [comment]
They are all listed in the README of the plugin, shown at the link I gave above 

Yes, I m up to date with the breaking changes.

**Comment by siduck** [comment]
> They are all listed in the README of the plugin, shown at the link I gave above
> 
> Yes, I m up to date with the breaking changes.

you can just redefine comment.nvim then

**Comment by siduck** [comment]
only these? 
![image](https://user-images.githubusercontent.com/59060246/152800392-c84c3aef-39f1-4efb-ac3d-d830b07137ab.png)
`

**Comment by hunger** [comment]
Those are the defaults I think. I am new to the plugin and do not really use it yet. But I was following some guide that was `gcc`and such all over:-)

I just overrode the Comment.nvim plugin locally now to load on BufRead and that works nicely for me. Not sure that is something for NVchad though, as you really like the lazy loading!

**Comment by siduck** [comment]
> Those are the defaults I think. I am new to the plugin and do not really use it yet. But I was following some guide that was `gcc`and such all over:-)
> 
> I just overrode the Comment.nvim plugin locally now to load on BufRead and that works nicely for me. Not sure that is something for NVchad though, as you really like the lazy loading!

U can just use leader / . I only use that command for commenting stuff

**Comment by hunger** [comment]
Why? That plugin does much more than that: Why have it when you can not make full use of it?

This issue is closed, and I am not contesting that: I do have my work-around and am a happy camper again.
