### ISSUE TITLE
there is something wrong in VIMR

### ISSUE THREAD

**Issue by ttw1018** [NvChad/NvChad#802]
While using in VIMR, there is something wrong.
![image](https://user-images.githubusercontent.com/48583236/152667137-ecef5e88-8d94-4bea-854c-9ee555fd2832.png)

**Comment by boppyt** [comment]
What version of neovim & NvChad are you running?

+ #671

**Comment by ttw1018** [comment]
> What version of neovim & NvChad are you running?
> 
> * [vim.diagnostic is a nil value #671](https://github.com/NvChad/NvChad/issues/671)

V0.6.0 NEOVIM and the latest NVCHAD

**Comment by boppyt** [comment]
Is it 0.6.0-dev?

We officially support 0.6.1+ (stable)

**Comment by ttw1018** [comment]
Problem has been solved with using the latest VIMR.
Thanks for helping.
