### ISSUE TITLE
"custom.plugins" doesn't seem to source everything?

### ISSUE THREAD

**Issue by danjenson** [NvChad/NvChad#803]
After several breaking changes, my luasnips don't work again, I've converted it to what I think is the new format
inside `lua/custom/plugins/init.lua`
```
return {
....
	{
		"L3MON4D3/LuaSnip",
		wants = "friendly-snippets",
		after = "nvim-cmp",
		config = function()
			local luasnip = require("luasnip")
			luasnip.config.set_config({
				history = true,
				updateevents = "TextChanged,TextChangedI",
			})
			require("luasnip.loaders.from_vscode").lazy_load({ paths = { "~/.config/snippets" } })
		end,
	},
```
But my custom plugins never get loaded now. Is the logic still the same for how these are loaded?

**Comment by siduck** [comment]
thats a default plugin so you need to first remove it . 

check https://nvchad.github.io/config/Custom%20config#remove--redefine-plugins

**Comment by danjenson** [comment]
wait so I have to remove it to configure it? Is there anyway just to configure the default?

**Comment by danjenson** [comment]
Also, can you define where defaults are listed, etc? Last week I feel like I copied a bunch of configs into my custom one because all of luasnips , cmp-nvim-* etc were removed. Are they back now? Also it seems that any packer package that is in the /start directory it wants to remove now?

**Comment by siduck** [comment]
> Also, can you define where defaults are listed, etc? Last week I feel like I copied a bunch of configs into my custom one because all of luasnips , cmp-nvim-* etc were removed. Are they back now? Also it seems that any packer package that is in the /start directory it wants to remove now?

yes they are back now

**Comment by siduck** [comment]
> wait so I have to remove it to configure it? Is there anyway just to configure the default? Is there no way to just add a line to load my custom snippets at the end or elsewhere in the config?

https://github.com/NvChad/NvChad/blob/main/lua/core/default_config.lua#L92

**Comment by danjenson** [comment]
Ok, but to be clear, there is now way to add a custom luasnips directory other than removing the default plugin and adding the same plugin with the line appended for custom snippets?

**Comment by siduck** [comment]
> Ok, but to be clear, there is now way to add a custom luasnips directory other than removing the default plugin and adding the same plugin with the line appended for custom snippets?

ye u can just add the path to your snippets file
