### ISSUE TITLE
Preview hidden terminal -- <leader>+W

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/NvChad#804]
**Describe the bug**

**To Reproduce**
1. `<leader>w`: Spawn new terminal buffer.
2. `JK`: Leave terminal and hide.
3. `<leader>-S-w`: Show hidden terminal buffers.
4. Message popup (still can preview hidden terminal after this message).

**Expected behavior**
No message will popup if hidden terminal exist.

### **Screenshots/Videos**
![Animation](https://user-images.githubusercontent.com/73665622/152696513-248a0957-3873-441b-942d-976a9aa2a769.gif)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Terminal Wezterm
 - NVIM v0.6.1 Release

**Additional context**
This issue is coming from https://github.com/NvChad/extensions/commit/4ce2eb9eddc749c0ece22829d56673b97015cc4a#

**Comment by Akianonymus** [comment]
Update and check again, should be fixed.

**Comment by GreatestOfAllTimee** [comment]
fixed!
