### ISSUE TITLE
`mksession` command arent working very welll

### ISSUE THREAD

**Issue by kevinmarquesp** [NvChad/NvChad#806]
**Describe the bug**
I want to save my sessions manually, but it doesnt work... :T

**To Reproduce**
1. Just open some files
2. And make some tabs, fold some lines, split some windows
3. Use `mksession! ~/some_where` to save everything
4. When you run `nvim -S ~/some_where` you just open all the buffers, with out any split, tab or row folds...

**Desktop (please complete the following information):**
 - Operating System: Arch BTW
 - Terminal: xfce4-terminal
 - Version of Neovim: v0.6.1

**Additional context**
I like to make in that way because I use both vim and neovim, with sessions script I can acsess any of my sections with both vim and neovim... Sory for my english, and thank you for reading <3

**Comment by siduck** [comment]
can u show how this works without nvchad

**Comment by kevinmarquesp** [comment]
And it is how NvChad works with sessions....

https://user-images.githubusercontent.com/71402116/152830214-b8d5c7e5-ee22-4aca-aa18-ec0bdcb7d7d0.mp4

**Comment by kevinmarquesp** [comment]
Btw, thats my script...

```bash
#!/usr/bin/env bash

vim_dir=~/.dotfiles/vim_secs
cd $vim_dir

# Style config of FZF
sec_file=$(
    fzf \
        --border sharp \
        --margin 15% \
        --padding 10% \
        --info inline \
        --prompt 'SEARCH: ' \
        --pointer '**' \
        --ansi \
        --color 'bg+:-1,pointer:green,fg+:green,hl:yellow,border:gray'
)

# Open section if $sec_file is not null
if [[ $sec_file ]]; then
    if [ $1 == "-v" ] || [ $1 == "--vim" ]; then
        vim -S $sec_file
    else
        nvim -S $sec_file
    fi
fi
```

**Comment by peppapig450** [comment]
```shell
#!/usr/bin/env bash

vim_dir=~/.dotfiles/vim_secs
cd $vim_dir

# Style config of FZF
sec_file=$(
    fzf \
        --border sharp \
        --margin 15% \
        --padding 10% \
        --info inline \
        --prompt 'SEARCH: ' \
        --pointer '**' \
        --ansi \
        --color 'bg+:-1,pointer:green,fg+:green,hl:yellow,border:gray'
)

# Open section if $sec_file is not null
if [[  -n $sec_file ]]; then
    if [[ $1 = -v || $1 = --vim ]]; then
        vim -S "$sec_file"
    else
        nvim -S "$sec_file"
    fi
fi
```

**Comment by peppapig450** [comment]
use this instead if. [[ $sec_name ]] doesn't do anything -n tests if the variable contains a value

**Comment by peppapig450** [comment]
also I'd think you would be better of using exit codes here

**Comment by bryant-the-coder** [comment]
> Here how it works with my custom config
> 
> https://user-images.githubusercontent.com/71402116/152826807-2cc0b4ff-d3b3-4f96-8a11-5ee023f8d802.mp4
> 
> But I really want to use NvChad :|

how do you change the cursor color on each line

**Comment by siduck** [comment]
@bryant-the-coder add bg color to cursorline highlight
