### ISSUE TITLE
Error running config for LuaSnip: from_vscode.lua:72: '=' expected near 'continue'

### ISSUE THREAD

**Issue by drscream** [NvChad/NvChad#808]
**Describe the bug**
I tried to use `NvChad` with my Neovim installation on MacOS but by pressing `i` I receive the following error message:

```
packer.nvim: 
Error running config for LuaSnip:
...acker/start/impatient.nvim/lua/impatient/profile.lua:148: 
...acker/start/impatient.nvim/lua/impatient/profile.lua:190: 
...e/pack/packer/start/impatient.nvim/lua/impatient.lua:137: 
...re/nvim/site/pack/packer/opt/LuaSnip/lua/luasnip/loaders/from_vscode.lua:72: '=' expected near 'continue'
```

This message only appears on the first start. After continue editing the file the error isn't shown anymore.

**To Reproduce**
1. Follow the regular NvChad installation instructions
2. Start `nvim` in iTerm2
3. Press `i` for insert mode

**Expected behavior**
No error should be shown

**Screenshots**
<img width="930" alt="Screenshot 2022-02-08 at 06 43 40" src="https://user-images.githubusercontent.com/315645/152925740-414e6483-5c03-45d2-834d-43c482fa727b.png">

**Desktop:**
 - Operating System: MacOS 12.1
 - Terminal: iTerm2
 - Version of Neovim: v0.6.1 (Features: +acl +iconv +tui)
 
**Additional context**
I compiled Neovim myself via pkgsrc including all dependencies (lua 5.1, etc.). So if you think it's related so an missing configuration option I'm sorry for creating the bug report.

**Comment by siduck** [comment]
do :LuaCacheClear and then packersync

**Comment by drscream** [comment]
Thanks a lot! Additional to that I sichtet from Lua to LuaJIT.

**Comment by siduck** [comment]
> Thanks a lot! Additional to that I sichtet from Lua to LuaJIT.

how do i switch to luajit? and why use it btw? is it fast

**Comment by drscream** [comment]
I could not say if it's really faster or not, but I used a Neovim version with LuaJIT in the past.

As I compile Neovim via pkgsrc, I mostly did some modifications of the pkgsrc Makefile:

```diff
diff --git a/neovim/Makefile b/neovim/Makefile
index 746a61eb66..04a9d43d4a 100644
--- a/neovim/Makefile
+++ b/neovim/Makefile
@@ -49,12 +49,13 @@ post-extract:
 .endif
 .include "../../devel/msgpack/buildlink3.mk"
 .include "../../lang/LuaJIT2/platform.mk"
-.if !empty(PLATFORM_SUPPORTS_LUAJIT:M[Yy][Ee][Ss])
-.include "../../lang/LuaJIT2/buildlink3.mk"
-.else
-.include "../../lang/lua51/buildlink3.mk"
-CMAKE_ARGS+=		-DPREFER_LUA=ON
-.endif
+.include "../../wip/LuaJIT21/buildlink3.mk"
+#.if !empty(PLATFORM_SUPPORTS_LUAJIT:M[Yy][Ee][Ss])
+#.include "../../lang/LuaJIT2/buildlink3.mk"
+#.else
+#.include "../../lang/lua51/buildlink3.mk"
+#CMAKE_ARGS+=		-DPREFER_LUA=ON
+#.endif
 .include "../../lang/lua/application.mk"
 .include "../../wip/lua-luv/buildlink3.mk"
 .include "../../sysutils/desktop-file-utils/desktopdb.mk"
```

But I assume this will not help you so much. If you compile Neovim by your own it might automatically detect the Lua or LuaJIT version installed.
