### ISSUE TITLE
[IDEA] Consider to use ImageGoNord as Wallpaper utility converter

### ISSUE THREAD

**Issue by TheJoin95** [NvChad/NvChad#809]
**Is your feature request related to a problem? Please describe.**
Many times I can't find a wallpaper with same palette of my terminal and other apps, even when I download other dotenv or theme I still can't find a good image for my desktop

**Describe the solution you'd like**
Using [ImageGoNord](github.com/schrodinger-Hat/ImageGoNord) anyone can convert any kind of wallpaper into their fav color palettes

**Describe alternatives you've considered**
An alternative is to create a variant using photoshop or gimp or any kind of image processing software

**Additional context**
I'm one of the developer behind ImageGoNord and since last year we were giving the opportunity to anyone to convert any image into their own or popular palettes from [ImageGoNord Website](ign.schrodinger-hat.it/) or [SubReddit](https://www.reddit.com/r/ImageGoNord/)

**Screenshot**
![immagine](https://user-images.githubusercontent.com/6616203/153227362-54912b67-2936-435e-aa7c-0a918b058505.png)

**Comment by siduck** [comment]
i have tried it and not all converted images look good. Also our colorschemes are tested a lot while creating so we gotta have perfect ones! So cant have imagegonord ;((
