### ISSUE TITLE
[Bug] Nvim-tree closes when opening it

### ISSUE THREAD

**Issue by Johnsiras** [NvChad/NvChad#812]
**OS**
Windows 10 Pro, 19044

**Neovim version**
0.6.1

**Nvim-tree version**
master

**Terminal**
wezterm

**Describe the bug**
- When opening the explorer, it closes the explorer and creating a new file if you're on the dashboard (dashboard.nvim)
![wezterm-gui_5hai1PS0nb](https://user-images.githubusercontent.com/78542955/153352835-25bff701-f76c-4518-b0a5-6820b3adec3d.gif)
- Opening the explorer with the file opened, it closes instead of opening it
![wezterm-gui_qUOcPP4N5d](https://user-images.githubusercontent.com/78542955/153354785-bf46fa7a-7492-4a15-aac4-b98380903692.gif)

**To Reproduce**
Open the explorer with `:NvimTreeOpen` or with the mapping: `<C-n>`

**Expected Behavior**
Show the file structure

**Comment by Johnsiras** [comment]
(sorry for bad english not too good at it)

**Comment by qn91** [comment]
I saw it's related with this [issue](https://github.com/kyazdani42/nvim-tree.lua/issues/951#issuecomment-1034096655) in nvim-tree.lua

**Comment by siduck** [comment]
it should be fixed now, I think
