### ISSUE TITLE
[Question] Custom folder chardrc is ignored.

### ISSUE THREAD

**Issue by ViiEx** [NvChad/NvChad#813]
# Chardrc.lua is being igored.

## Description.
I installed NvChad a week ago and im trying to create my custom config to include my personal staff as the wiki suggest by creating a `custom` folder inside `lua` dir. Tho after going through all the wiki about the configuration and run `:PackerSync`, packer does't look like it installs the added plugins in `custom/plugins/init.lua` Tho I check the `nvim/init.lua` file and I know for a fact that it is loading the `custom/init.lua` file. I'm sure that it is a problem on my side cause I'm new to lua. Do I have to include `chadrc.lua` in my `custom/init.lua` somehow?

## Files in my configs

```lua
-- nvim/lua/custom/plugins/init.lua
return {
   { "elkowar/yuck.vim", ft = "yuck" },
   { "ellisonleao/glow.nvim", cmd = "Glow" },
   { "williamboman/nvim-lsp-installer" },
   {
     "jose-elias-alvarez/null-ls.nvim",
      after = "nvim-lspconfig",
      config = function()
        require("custom.plugins.configs.null-ls").setup()
      end,
    },
    {
      "karb94/neoscroll.nvim",
      opt = true,
      config = function()
        require("neoscroll").setup()
      end,

      -- lazy loading
      setup = function()
        require("core.utils").packer_lazy_load "neoscroll.nvim",
      end,
    },
    {
      "Pocco81/AutoSave.nvim",
      config = function()
        require("custom.plugins.configs.autosave").setup()
      end,
    },
    { "nathom/filetype.nvim" },
    {
      "nvim-telescope/telescope-media-files.nvim",
      after = "telescope.nvim",
      config = function()
        require("custom.plugins.configs.telescope-media").setup()
        require("telescope").load_extension "media_files"
      end,
    },
}
```

```lua
-- nvim/lua/custom/chadrc.lua
local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.ui = {
   theme = "onedark",
}

-- Install plugins
local userPlugins = require "custom.plugins" -- path to table
local pluginsConfig = require "custom.plugins.configs" -- Import the custom config file

M.plugins = {
   install = userPlugins,
   options = {
     lspconfig = {
       setup_lspconf = "custom.plugins.configs.lspconfig",
     },
   },
}

local map = require("core.utils").map
-- Whire maps here.

-- NOTE: we heavily suggest using Packer's lazy loading (with the 'event','cmd' fields)
-- see: https://github.com/wbthomason/packer.nvim
-- https://nvchad.github.io/config/walkthrough

return M
```

```lua
-- nvim/lua/custom/init.lua

vim.g.did_load_filetypes = 1

-- MAPPINGS
local map = require("core.utils").map

map("n", "<leader>cc", ":Telescope <CR>")
map("n", "<leader>q", ":q <CR>")
map("n", "<leader>fp", ":Telescope project<CR>")

```

## Tree view
```bash
.
├── examples
│  ├── chadrc.lua
│  ├── init.lua
│  └── plugins.lua
├── init.lua
├── LICENSE
├── lua
│  ├── colors
│  │  ├── highlights.lua
│  │  └── init.lua
│  ├── core
│  │  ├── autocmds.lua
│  │  ├── default_config.lua
│  │  ├── mappings.lua
│  │  ├── options.lua
│  │  └── utils.lua
│  ├── custom
│  │  ├── chadrc.lua
│  │  ├── init.lua
│  │  └── plugins
│  │     ├── configs
│  │     │  ├── autosave.lua
│  │     │  ├── init.lua
│  │     │  ├── lspconfig.lua
│  │     │  ├── null-ls.lua
│  │     │  └── telescope-media.lua
│  │     └── init.lua
│  └── plugins
│     ├── configs
│     │  ├── bufferline.lua
│     │  ├── cmp.lua
│     │  ├── dashboard.lua
│     │  ├── icons.lua
│     │  ├── lspconfig.lua
│     │  ├── lspkind_icons.lua
│     │  ├── nvimtree.lua
│     │  ├── others.lua
│     │  ├── statusline.lua
│     │  ├── telescope.lua
│     │  └── treesitter.lua
│     ├── init.lua
│     └── packerInit.lua
└── plugin
   └── packer_compiled.lua
```

## **Desktop (please complete the following information):**
 - Operating System: Arch Linux
 - Terminal: Alacritty with fish shell
 - Version of Neovim: v0.6.1

**Comment by limeless** [comment]
this problem is happening on my Arch Linux too,

but on Windows Neovim can properly load `chadrc.lua` inside custom directory.

**Comment by siduck** [comment]
custom dir is gitignored but certainly  not ignored by packer!

**Comment by siduck** [comment]
works fine here https://vimeo.com/676115036

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/153525106-698c6bc6-49f3-4bc4-a0b5-fd7d059adc44.mp4

works fine here

**Comment by limeless** [comment]
I've notice on Windows `<space> th` value will save into `custom\chadrc.lua`,
but on Linux it won't apply selected value to `M.ui = { theme = "<colorscheme>", }`.

is it maybe permission problem? what permission should apply to `custom/` folders?

**Comment by siduck** [comment]
You don't need to add any permission, just make sure that chadrc is present and u have custom dir in lua dir

**Comment by siduck** [comment]
@limeless do u get any errors? Also make sure that u have no custom dir in your home folder

**Comment by ViiEx** [comment]
I tried to delete nvim folder from `~/.config` , `~/.local/share` and `~/.cache` to reinstall it cause after I saw you I thought that my work but it still just downloaded the 32 plugins and the chadrc got ignored.

**Comment by siduck** [comment]
> I tried to delete nvim folder from `~/.config` , `~/.local/share` and `~/.cache` to reinstall it cause after I saw you I thought that my work but it still just downloaded the 32 plugins and the chadrc got ignored.

very weird, can u show me a video of this? also after fresh clone u gotta copy your custom dir in .config/nvim/lua

**Comment by ViiEx** [comment]
of course, I will upload one in couple hours since I'm not on my machine now. On another note tho I did tried my config on an Ubuntu machine and everything was perfect. I cloned my own config straight from my fork to try replicate the exact same steps I did on my Arch. I got an error cause I had some extra `,` in a line but after I fixed that everything compiled perfectly.

**Comment by limeless** [comment]
@siduck Thanks for your time and advise, I wipe all my nvim config like you did in the video, now NvChad will read `chadrc.lua`

**Comment by ViiEx** [comment]
Found the solution. After I've done again a clean istall with the fixed config files lua was able to compile and installed everything properly. Thank you a lot for your time.
