### ISSUE TITLE
New theme doesn't persists - Can't set to catppuccin even with setup on chadrc.lua

### ISSUE THREAD

**Issue by fematarazzo** [NvChad/NvChad#815]
I used <leader> + T + H to select my prefered theme.
Set to "catppuccin"
It prompts: _Set catppuccin as default theme ? [y/N]_
I write y
It doesn't prompts me anything else, but sets to the captpuccin theme.

If I close and reopen neovim, it sets back to the default theme that comes installed.
In my .config/nvim/lua/custom/chadrc.lua file I even have catppuccin set as default, but it doesn't work:

```
local M = {}

local plugin_conf = require "custom.plugins.configs"
local userPlugins = require "custom.plugins"

M.plugins = {
   status = {
      colorizer = true,
      snippets = true,
   },

   options = {
      lspconfig = {
         setup_lspconf = "custom.plugins.lspconfig",
      },
   },

   default_plugin_config_replace = {
      nvim_treesitter = plugin_conf.treesitter,
      nvim_tree = plugin_conf.nvimtree,
   },

   install = userPlugins,
}

M.ui = {
   theme = "catppuccin",
}

return M
```

This happens with any theme I set

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/153689473-a12c2af1-1532-4644-8f68-2f3238553562.mp4

**Comment by fematarazzo** [comment]
Makes sense, but I've even copied your setup and with yout custom plugins folder, so it should work, right?
Btw, how to you create a new folder directly on nvimtree and copied to the clipboard? I always try copying it with +*y but doesn't work.

![Captura de tela de 2022-02-13 18-54-49](https://user-images.githubusercontent.com/64224424/153776861-add8c75c-46b4-436e-848c-a483e6825b62.png)

**Comment by siduck** [comment]
i usually do

**Comment by G-Rowell** [comment]
Can confirm that I can replicate this bug.

Part of the debug message below, looking into this rn


> ```
> 
> M.plugins = {
>    status = {
>       colorizer = true,
>       snippets = true,
>    },
> 
>    options = {
>       lspconfig = {
>          setup_lspconf = "custom.plugins.lspconfig",
>       },
>    },
> 
>    default_plugin_config_replace = {
>       nvim_treesitter = plugin_conf.treesitter,
>       nvim_tree = plugin_conf.nvimtree,
>    },
> 
>    install = userPlugins,
> }
> 
> M.ui = {
>    theme = "catppuccin",
> }
> 
> return M
> ```
> 
> 
> This happens with any theme I set

**Comment by G-Rowell** [comment]
It seems this file: https://github.com/NvChad/extensions/blob/main/lua/nvchad/change_theme.lua

fails in several cases:

- when the theme line in commented out in `chadrc.lua`
- when the theme line is not present in `chadrc.lua`
- when `chadrc.lua` doesn't exist


it's likely possible to solve this, but this functionality may not be worth the effort?

---

the exact problem is with the logic of `change_theme.lua`, lines: 14 & 18-22

**Comment by siduck** [comment]
> It seems this file: https://github.com/NvChad/extensions/blob/main/lua/nvchad/change_theme.lua
> 
> fails in several cases:
> 
> * when the theme line in commented out in `chadrc.lua`
> * when the theme line is not present in `chadrc.lua`
> * when `chadrc.lua` doesn't exist
> 
> it's likely possible to solve this, but this functionality may not be worth the effort? (given we want users to modify NvChad anyway?)
> 
> @siduck what are your thoughts?
> 
> the exact problem is with the logic of `change_theme.lua`, lines: 14 & 18-22

if this file doesnt exist or is messed up then that will mess up whole chadrc. 

local userPlugins = require "custom.plugins"

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/154832001-c4fa615f-5c4d-4313-ac10-3873b8a6c451.mp4

**Comment by G-Rowell** [comment]
@siduck 

Yeap!

Try remove the line in your `chadrc.lua` that sets the theme, then try.
It won't work but will throw no error.

Then try to `mv chadrc.lua chadrc.lua.BAK`,
It won't work and will throw an error.

Thoughts?
See: https://github.com/NvChad/NvChad/issues/815#issuecomment-1046173549
