### ISSUE TITLE
Replace dashboard-nvim with alpha-nvim

### ISSUE THREAD

**Issue by itsmeboy0** [NvChad/NvChad#816]
https://github.com/goolord/alpha-nvim

**Comment by siduck** [comment]
Im inclined towards adding this more https://github.com/startup-nvim/startup.nvim

**Comment by siduck** [comment]
> Looks better eyes (any benchmarks on that plugin?)

it takes no time! just need someone to pr it xD

**Comment by peppapig450** [comment]
startup-nvim's config file is larger than dashboard-nvim which equals bloat.

**Comment by itsmeboy0** [comment]
`dashboard-nvim` is unmaintained which is why I am eager to replace it. If you don't like `startup.nvim` consider using `alpha-nvim`.

**Comment by peppapig450** [comment]
alpha-nvim is faster and it looks more like dashboard-nvim so it maintains the same kind of look and feel while not adding any performance drawbacks

**Comment by siduck** [comment]
> alpha-nvim is faster and it looks more like dashboard-nvim so it maintains the same kind of look and feel while not adding any performance drawbacks So I think we should use this over startup.nvim

did u do any benchmark?

**Comment by peppapig450** [comment]
My lua skills aren't good enough to do the config :l

**Comment by peppapig450** [comment]
https://github.com/goolord/alpha-nvim he says its the fastest according to his benchmarks 🤷‍♂️

**Comment by siduck** [comment]
> https://github.com/goolord/alpha-nvim he says its the fastest according to his benchmarks man_shrugging

yea i tried it. its the fastest

**Comment by MikaelElkiaer** [comment]
@siduck Shouldn't this have been mentioned in #714 ?

**Comment by siduck** [comment]
> @siduck Shouldn't this have been mentioned in #714 ?

oh my bad, I didnt consider this as breaking change as most users just use the default dashboard config. lemme add it real quick

**Comment by peppapig450** [comment]
you can change it easily if you run
```shell
sed -i 's/dashboard/alpha/' ~/.config/nvim/lua/custom/chadrc.lua
```

**Comment by itsmeboy0** [comment]
> you can change it easily if you run
> 
> ```shell
> sed -i 's/dashboard/alpha/' ~/.config/nvim/lua/custom/chadrc.lua
> ```

Except when you have a dashboard-specific config.
