### ISSUE TITLE
Overwrite cmp mapping

### ISSUE THREAD

**Issue by drscream** [NvChad/NvChad#822]
**Describe the bug**

Based on the documentation I tried to overwrite the mapping of the plugin `cmp` to remove the `<CR>` mapping. For that reason I added the following lines to `chadrc.lua`:

```lua
local M = {}

M.plugins = {
  install = userPlugins,
  default_plugin_config_replace = {
    cmp = {
      mapping = {
        ["<CR>"] = {},
      }
    }
  }
}

return M
```

**To Reproduce**
1. Create `~/.config/nvim/lua/custom/chadrc.lua` with the above content
2. Try to auto-complete something from an existing code / file
3. Press enter
4. Code is completed instead of `<CR>` (newline)

**Expected behavior**
Allow to overwrite the mapping of `cmp` plugin.

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Terminal: iTerm2
 - Version of Neovim: v0.6.1

**Comment by whkelvin** [comment]
try setting ["<CR>"] = nil

**Comment by drscream** [comment]
Sadly that doesn't change anything. I assume that the `mapping` could not be overwritten in the above way.

**Comment by whkelvin** [comment]
You can also try changing cmp to nvim_cmp as suggested in the [doc](https://nvchad.github.io/config/Custom%20config)

``` lua
M.plugins = {
   default_plugin_config_replace = {
      bufferline = "custom.bufferline",
   },
}

-- NOTE: The 'bufferline' variable there is taken from the first argument here
--  config = override_req("bufferline", "plugins.configs.bufferline", "setup")
-- you will find that in the packer's bufferline use function
-- make sure you do :PackerCompile or :PackerSync after this since the packer_compiled.lua present needs to update
``` 

in `plugins/init.lua`
```lua
   {
      "hrsh7th/nvim-cmp",
      disable = not plugin_settings.status.cmp,
      after = "friendly-snippets",
      config = override_req("nvim_cmp", "plugins.configs.cmp", "setup"),
   },
```

**Comment by drscream** [comment]
I also tried the following which doesn't work:

```lua
--- chadrc.lua

local pluginConfs = require "custom.plugins.configs"

M.plugins = {
  default_plugin_config_replace = {
    nvim_cmp = pluginConfs.cmp,
  }
}
```

```lua
--- plugins/configs.lua

local M = {}

M.cmp = {
  mapping = {
    ["<CR>"] = nil
  }
}

return M
```

**Comment by whkelvin** [comment]
I just got mine to work, what I did was creating a `custom/plugin_config/cmp.lua` file and copy the content over from `plugins/configs/cmp.lua` and made changes to the mapping.

Finally, I put this in `custom/chadrc.lua` . Turns out cmp works and nvim_cmp doesn't.
```lua
  default_plugin_config_replace = {
    nvim_tree = pluginConfig.nvimtree, -- paritial override
    cmp = "custom.plugin_config.cmp", 
  },
```

**Comment by whkelvin** [comment]
sorry for the late reply, updated to the most recent version and can confirm nvim_cmp works now.
