### ISSUE TITLE
Infinite loop caused by requiring plugin table

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#824]
While trying to debug what on earth was going on with my config for #823, I realized trying to load chadrc from my custom/plugins_table file to get the plugin_status variable causes an infinite loop, since chadrc requires plugins_table for setting the install variable. I fixed it by making plugins.status a separate file required by both of them rather than requiring each other, but this may be something that should be disclaimed in the docs.

Also, since the user plugin table can be a pretty large file, requiring it every time the config is loaded is quite inefficient. I was thinking it maybe better to make plugins.install a string, and just require it once inside utils or init.lua (which would also fix the above issue), but it would be a breaking change...

**Comment by zbirenbaum** [comment]
> everything's fine here :l

Make a plugin file and put ‘require(“core.utils”).load_config().plugins.status’, (or whatever it is, I’m on mobile) add a plugin, and watch it mess up on packer sync…

**Comment by siduck** [comment]
adding a plugin works for me, btw we already defined the plugin status for default plugins. Why would you want to define it for custom plugins?

**Comment by zbirenbaum** [comment]
> adding a plugin works for me, btw we already defined the plugin status for default plugins. Why would you want to define it for custom plugins?

I have a complex setup. For instance, if I have cmp enabled, I know coq needs to be disabled, etc. My custom plugins are enabled and disabled frequently so having a unified table is helpful.

Also, for people like me with a 200 line plugin table, requiring it every time the config is loaded cannot be efficient... I just PR'd an opt in fix that doesn't break anything.
