### ISSUE TITLE
Show pulled commits when updating NvChad

### ISSUE THREAD

**Issue by sitiom** [NvChad/NvChad#825]
**Is your feature request related to a problem? Please describe.**
Much like with packer:
![image](https://user-images.githubusercontent.com/56180050/154012720-d13ae2bd-f9ca-455b-a09e-7157e7dc6f42.png)

**Comment by siduck** [comment]
@Akianonymus

**Comment by G-Rowell** [comment]
I am getting an error:

```
Error: NvChad Update failed.
```

when I try to update,
does anyone else get this?


This error comes from this line in our extensions repo: https://github.com/NvChad/extensions/blob/main/lua/nvchad/update_nvchad.lua#L81

**Comment by siduck** [comment]
> I am getting an error:
> 
> ```
> Error: NvChad Update failed.
> ```
> 
> when I try to update, does anyone else get this?
> 
> This error comes from this line in our extensions repo: https://github.com/NvChad/extensions/blob/main/lua/nvchad/update_nvchad.lua#L81

a lot has changed recently. you need to check the pinned issues.

**Comment by G-Rowell** [comment]
Will do, mine is an updated branch that is the same as `NvChad/NvChad:main`, but still could be related to a breaking change, will look around!

Congrats on the changes!!!! :grin:

**Comment by siduck** [comment]
@sitiom done

**Comment by sitiom** [comment]
Great! What does it look like?

**Comment by siduck** [comment]
> Great! What does it look like?

update your nvchad and see yourself!

**Comment by sitiom** [comment]
I just updated a few minutes ago so I didn't see. I'll just wait for a new commit

**Comment by siduck** [comment]
> I just updated a few minutes ago so I didn't see. I'll just wait for a new commit

![image](https://user-images.githubusercontent.com/59060246/166142154-55032030-0ae9-42b4-adce-75fbd0983f47.png)
