### ISSUE TITLE
Dashboard is using Telescope and vim-clap at the same time.

### ISSUE THREAD

**Issue by limeless** [NvChad/NvChad#826]
**Describe the bug**
When at Dashboard, using key binding of `<leader>bm` instead to open Telescope's mark function,
it's trying to launch `:Clap marks`, but when navigate cursor on `Bookmarks` and hit enter, it shows telescope's mark window.

If you run command `DashboardJumpMarks` like it defined in `core/mappings.lua` it will trying to use `vim-clap` too.

**To Reproduce**
1. Enable dashboard from `custom\chadrc.lua`
2. re-launch neovim and `:PackerSync`
3. re-launch neovim again and use shortcut `<leader> b m` as it show on Bookmarks SPC b m, there will be an error message complaining about :Clap command is not found.
4. navigate to Bookmarks option and hit enter.

**Expected behavior**
it should be using Telescope for both method to call the function.

**Screenshots**
### Use Shortcuts
![Using Shortcuts](https://user-images.githubusercontent.com/1501022/153985282-98b11f28-6992-4068-bcc5-ac4c61d670a6.png)
### Navigate to option and hit Enter
![Navigate to option and Enter](https://user-images.githubusercontent.com/1501022/153985328-85e72e8b-2240-498d-97d7-3b5022688ba5.png)

**Desktop (please complete the following information):**
 - Win 10
 - Neovide / Alacritty
 - NVIM v0.6.0

**Comment by siduck** [comment]
sorry for late reply! i moved to alpha-nvim so this should be solved now
