### ISSUE TITLE
`table index is nil` when doing `PackerSync`

### ISSUE THREAD

**Issue by sitiom** [NvChad/NvChad#829]
**Describe the bug**
I get the error `E5108: Error executing lua C:\Users\rycae\AppData\Local\nvim/lua/core/utils.lua:308: table index is nil` when doing PackerSync.

This bug was introduced in https://github.com/NvChad/NvChad/pull/818. For now, I will be reverting to the last working commit (https://github.com/NvChad/NvChad/commit/a21e884983ef6d99ef6fb3d3ce714953c43332a1).

**To Reproduce**
1. Do `:PackerSync`

**Expected behavior**
My config should work fine as before.

**Screenshots**
[![asciicast](https://asciinema.org/a/ZCNaQS8YUSQWuUGrjeD6J0Pjq.svg)](https://asciinema.org/a/ZCNaQS8YUSQWuUGrjeD6J0Pjq)

**Desktop (please complete the following information):**
 - Windows 11
 - Windows Terminal
 - Neovim v0.6.1

**Additional context**
This is not a Windows-specific error.

**Comment by siduck** [comment]
it works fine here

https://user-images.githubusercontent.com/59060246/154801843-22f4bff2-0aa3-4e13-a158-d8ce9ab41564.mp4

looks like some windows/packer issue :l

**Comment by sitiom** [comment]
It is not a windows issue because it also happens to me on Linux. It might not be also a packer issue because I am on https://github.com/NvChad/NvChad/commit/a21e884983ef6d99ef6fb3d3ce714953c43332a1 and the latest packer commit is working fine.

**Comment by siduck** [comment]
> It is not a windows issue because it also happens to me on Linux. It might not be also a packer issue because I am on [a21e884](https://github.com/NvChad/NvChad/commit/a21e884983ef6d99ef6fb3d3ce714953c43332a1) and the latest packer commit is working fine.

can you update to the latest commit?

**Comment by sitiom** [comment]
This bug happens on the latest commit of nvchad.

**Comment by sitiom** [comment]
Additional context: it works fine with an empty user plugins table (`return { }`). As soon as I add one, the bug starts to appear.

**Comment by siduck** [comment]
> This bug happens on the latest commit of nvchad. The regression started at #818.

@zbirenbaum

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/154811373-ac969c65-5f6f-48ee-9f69-24616d1aedcb.mp4

works fine here :/

**Comment by zbirenbaum** [comment]
#818 actually fixed this issue on my end. Are you requiring the plugins.status variable from the plugin table file?

**Comment by sitiom** [comment]
> #818 actually fixed this issue on my end. Are you requiring the plugins.status variable from the plugin table file?

([`init.lua`](https://github.com/sitiom/dotfiles/blob/main/chezmoi/.chezmoitemplates/nvim/plugins/init.lua)) No.

**Comment by siduck** [comment]
> > #818 actually fixed this issue on my end. Are you requiring the plugins.status variable from the plugin table file?
> 
> ([`init.lua`](https://github.com/sitiom/dotfiles/blob/main/chezmoi/.chezmoitemplates/nvim/plugins/init.lua)) No.

   "jeffkreeftmeijer/vim-numbertoggle",
 isnt a table . can you wrap single lined plugin definitions into a table too? and do packersync

**Comment by sitiom** [comment]
> can you wrap single lined plugin definitions into a table too? and do packersync

Same thing.

**Comment by zbirenbaum** [comment]
return {
   {"jeffkreeftmeijer/vim-numbertoggle"},
   {
      "karb94/neoscroll.nvim",
      opt = true,
      config = function()
         require"neoscroll".setup()
      end,
      setup = function()
         require"core.utils".packer_lazy_load "neoscroll.nvim"
      end,
   },
   {"tpope/vim-sleuth"},
   {
      'kevinhwang91/nvim-hlslens',
      config = function()
         require"custom.plugins.configs.nvim-hlslens".setup()
      end
   },
   {
      "folke/todo-comments.nvim",
      requires = "nvim-lua/plenary.nvim",
      config = function()
         require"todo-comments".setup()
      end
   },
   {"tpope/vim-repeat"},
   {
      "ur4ltz/surround.nvim",
      config = function()
         require"surround".setup{ mappings_style = "surround" }
      end
   },
   {"tpope/vim-unimpaired"},
   {
      "winston0410/range-highlight.nvim",
      requires = 'winston0410/cmd-parser.nvim',
      config = function()
         require'range-highlight'.setup{}
      end
   },
   {"yamatsum/nvim-cursorline"},
   {
      "lambdalisue/suda.vim",
      config = function()
         vim.g.suda_smart_edit = 1
      end
   },
   {
      "petertriho/nvim-scrollbar",
      after = 'nvim-hlslens',
      config = function()
         require"scrollbar".setup()
         require"scrollbar.handlers.search".setup()
      end
   },
   {
      "JoosepAlviste/nvim-ts-context-commentstring",
      after = "nvim-treesitter",
      config = function()
         require'nvim-treesitter.configs'.setup {
            context_commentstring = {
               enable = true,
               enable_autocmd = false,
            }
         }
      end
   },
   {"VebbNix/lf-vim"},
   {"gpanders/editorconfig.nvim"},
   {
      "andweeb/presence.nvim",
      config = function()
         require"presence":setup { main_image = "file" }
      end,
   },
   { "raghur/vim-ghost", run = ":GhostInstall" },
   {
      "luukvbaal/stabilize.nvim",
      config = function() require"stabilize".setup() end
   },
   {"williamboman/nvim-lsp-installer"},
   {
      "j-hui/fidget.nvim",
      config = function()
         require"fidget".setup {
            window = {
               blend = 0,
            }
         }
      end,
   },
   {
      "gelfand/copilot.vim",
      config = function()
         -- Copilot assume mapped
         vim.g.copilot_assume_mapped = true
         vim.g.copilot_no_tab_map = true
      end,
   },
   {
      "jose-elias-alvarez/null-ls.nvim",
      requires = "nvim-lua/plenary.nvim",
      after = "nvim-lspconfig",
      config = function()
         require"custom.plugins.configs.null-ls".setup()
      end
   },
   {"hrsh7th/cmp-copilot"},
   {
      "p00f/nvim-ts-rainbow",
      after = "nvim-treesitter"
   },
   {
      "jvgrootveld/telescope-zoxide",
      after = "telescope.nvim",
      requires = "nvim-lua/popup.nvim",
      config =function ()
         require"telescope".load_extension("zoxide")
      end
   },
   {"alker0/chezmoi.vim"}
}

**Comment by sitiom** [comment]
Thanks, it works (as a workaround for now).

> Or just ask users to only include tables and not strings?

I'd prefer keeping the strings to be in par with the behavior of packer.

**Comment by siduck** [comment]
> Thanks, it works (as a workaround for now).
> 
> > Or just ask users to only include tables and not strings?
> 
> I'd prefer keeping the strings to be in par with the behavior of packer (less confusion from users).

its not a workaround. you are supposed to wrap every plugin definition in a table.

**Comment by zbirenbaum** [comment]
> Thanks, it works (as a workaround for now).
> 
> > Or just ask users to only include tables and not strings?
> 
> I'd prefer keeping the strings to be in par with the behavior of packer (less confusion from users).

I think I have a working fix. I'll PR it and link it in a moment. Could you clone the branch I submit and confirm it works on your end as well.

> > Thanks, it works (as a workaround for now).
> > > Or just ask users to only include tables and not strings?
> > 
> > 
> > I'd prefer keeping the strings to be in par with the behavior of packer (less confusion from users).
> 
> its not a workaround. you are supposed to wrap every plugin definition in a table.

I have a fix which allows for strings as well. Do you want me to PR it or nah? He is right that packer allows strings, but tbh I'm a bit partial to enforcing making them tables for clarity's sake.

**Comment by sitiom** [comment]
If you're going to enforce putting it in tables, clarify it in the docs.

**Comment by zbirenbaum** [comment]
> If you're going to enforce putting it in tables, clarify it in the docs.

I agree with this.

**Comment by siduck** [comment]
> If you're going to enforce putting it in tables, clarify it in the docs.



> If you're going to enforce putting it in tables, clarify it in the docs.

done
