### ISSUE TITLE
Is there a command / shortcut to reload config changes?

### ISSUE THREAD

**Issue by xarthurx** [NvChad/NvChad#830]
**Is your feature request related to a problem? Please describe.**
Not sure if there's already a function.
But I check the `default_config` but cannot find anything related.

In general, I'd like to update any UI / config change without closing and restarting `neovim`.
I  can do this with `:source $MYVIMRC<CR>` with my previous `init.vim`, not sure how to do it with the  `lua` mechanism.

**Describe the solution you'd like**
With one command / shortcut, I can reload my config.

**Comment by siduck** [comment]
you may check nvim-reload plugin
