### ISSUE TITLE
]Can't Scroll And Select LSPConfig Suggestions

### ISSUE THREAD

**Issue by The-0Day** [NvChad/NvChad#831]
**Describe the bug**
I Can't Scroll On LSPConfig Suggestions And Select Them.

**To Reproduce**
1. Open Terminal
2. Then Just Open A File, For Example `nvim lol.c`
3. Type `#inc` 
4. It shows you some Suggestions, You Can't Select Them, Looks Like The Array Keys Not Working!

**Expected behavior**
Well, It's So Clear, We Need To Select On Suggestions, But We Can't Scroll On Them!

**Screenshots**
![2022-02-19_04-27](https://user-images.githubusercontent.com/76570757/154801400-5bfdb515-81de-4687-9ccc-82134c438233.png)

**Desktop (please complete the following information):**
 - OS: `Linux arch 5.16.9-arch1-1`
 - Terminal: `St Terminal`
 - Version of Neovim:   ```NVIM v0.6.1
                                        Build type: Release
                                         LuaJIT 2.1.0-beta3
                                         Compiled by builduser
                                      ```




**Additional context**
My Custom `chadrc.lua` (`$HOME/$USER/.config/nvim/lua/custom/chadrc.lua`) URL At: https://termbin.com/6kel
My Custom `init.lua` (`$HOME/$USER/.config/nvim/lua/custom/init.lua`) URL At: https://termbin.com/zp97
My LSPCofig `lspconfig.lua` (`/home/zeroday/.config/nvim/lua/custom/plugins/lspconfig.lua`) URL At: https://termbin.com/ltpq

**Comment by siduck** [comment]
u need to scroll with either TAB or SHIFT TAB 

CTRL N or CTRL P

**Comment by The-0Day** [comment]
Not Working Too, Any Way To Using Array Keys?

**Comment by siduck** [comment]
> Not Working Too, Any Way To Using Arrow Keys?

they work? your keyboard might be the issue. It works for me even with the arrow keys

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/154801906-e0aa2cfa-cfcb-48e9-b206-724e1a98d036.mp4

**Comment by The-0Day** [comment]
> > Not Working Too, Any Way To Using Arrow Keys?
> 
> they work? your keyboard might be the issue. It works for me even with the arrow keys






> > Not Working Too, Any Way To Using Arrow Keys?
> 
> they work? your keyboard might be the issue. It works for me even with the arrow keys

I Test It With Two Keyboards, I Have A Laptop, Not Working On My Internal And External Keyboard.
I Don't Think So My Keyboard Has The Issue, The Arrow Keys Works On Other Apps!

**Comment by The-0Day** [comment]
> simplescreenrecorder-2022-02-19_18.32.04.mp4

Weird!

**Comment by The-0Day** [comment]
Lol, `CTRL P` & `CTRL N` Works Now, But The Arrow Keys Not Working Yet!

**Comment by The-0Day** [comment]
Anyway, The Problem Fixed.
Thanks!
