### ISSUE TITLE
Add nvim-ts-rainbow as a plugin

### ISSUE THREAD

**Issue by jayp0521** [NvChad/NvChad#832]
**Is your feature request related to a problem? Please describe.**
Currently, trying to visually find matching braces, tags, etc. is difficult. It involves `%` to find the matching one or visually scanning. Adding different colors to would like make it easier.

**Describe the solution you'd like**
Adding `nvim-ts-rainbow` as a treesitter plugin. I willing to create a PR for this change if the feature is accepted.

Config would be similar to: https://github.com/jayp0521/dotfiles/commit/8adeb798e578a58ce4e75ed28aef59a3381be469#diff-9e5de8d25e6ac81e55b7fb2216a203d7abecd8f68b9faa6533ee9637a65917cbR18

**Describe alternatives you've considered**
No

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
you can add this for yourself

**Comment by boppyt** [comment]
https://nvchad.github.io/config/Custom%20config#add-plugins
