### ISSUE TITLE
unable to use tab completions

### ISSUE THREAD

**Issue by Felix-Kyun** [NvChad/NvChad#836]
**Describe the bug**
whenever i use tab to select a completion it adds a tab rather than cycling through the completions list.

**To Reproduce**
1. open any file
2. start typing 
3. use tab to select a suggestion

**Expected behavior**
it should normally cycle through the completions 

**Screenshots**

https://user-images.githubusercontent.com/99094581/154857302-267051d5-9f1f-4cba-9c8b-5e73ec3f9323.mp4

**Desktop (please complete the following information):**
 - ubuntu 20.04
 - gnome terminal
 - was using 0.7 but the same happens in 0.6

**Comment by AnInternetTroll** [comment]
I just had this issue and `:PackerSync` fixed it. Can you try that?

**Comment by Felix-Kyun** [comment]
> I just had this issue and `:PackerSync` fixed it. Can you try that?

i tried it but didn't work

**Comment by Felix-Kyun** [comment]
I'm having this issue just on my pc as it work completely fine on my termux installation.

**Comment by peppapig450** [comment]
I have this issue sometimes on my mac and pc, other times it works completely fine

**Comment by danjenson** [comment]
Not working for me either. Freshly updated all packer packages and NvChad. Snippets, completions, can't use tab or enter to complete.

**Comment by siduck** [comment]
> Not working for me either. Freshly updated all packer packages and NvChad. Snippets, completions, can't use tab or enter to complete. The list populates, but I can't tab through them or press enter to accept the default (first) one. I suspect it is related to this: [a21e884](https://github.com/NvChad/NvChad/commit/a21e884983ef6d99ef6fb3d3ce714953c43332a1) I've found that they do actually load...after an indeterminate period of time. The list populates immediately, but it can't be used until some plugin is loaded.

yea that commit caused it. But tab doesnt work only for the first time 

open a file 
type something and the completion shows up ( tab doesnt work now)
go back to normal mode (jk)
type something again and the tab completion works now

**Comment by danjenson** [comment]
yea...that's...annoying and unclear

**Comment by siduck** [comment]
> yea...are there plans to fix that? I think it makes sense to eager load snippets/completions, especially since many of them create template files, functions, etc. It definitely feels like it's "broken" unless you know this combo.

yes i'll see about this

**Comment by victorpsantos** [comment]
I had the same issue, but for me, just making "nvim-cmp" not wait for "friendly-snippets" solved it.
![NvChad_Issues_836](https://user-images.githubusercontent.com/46680292/155281721-64a09544-f189-445b-962a-dff2586c3759.png)

**Comment by Johnsiras** [comment]
Same issue here

**Comment by victorpsantos** [comment]
So instead of making nvim-cmp not wait for friendly-snippets, just change the friendly-snippets event type from "InsertCharPre" to "InsertEnter". I think this is better.

![NvChad_Issue_836](https://user-images.githubusercontent.com/46680292/155658489-04b60c44-ad12-42f0-973e-4acf3aece8f0.png)

**Comment by siduck** [comment]
> So instead of making nvim-cmp not wait for friendly-snippets, just change the friendly-snippets event type from "InsertCharPre" to "InsertEnter". I think this is better.
> 
> ![NvChad_Issue_836](https://user-images.githubusercontent.com/46680292/155658489-04b60c44-ad12-42f0-973e-4acf3aece8f0.png)

Yes that will work, but it will add a delay in telescope prompt for the first time ._.

**Comment by ghost** [comment]
I'm still facing this issue

**Comment by siduck** [comment]
> I'm still facing this issue

make a video, i hope u didnt disable  cmp

**Comment by ghost** [comment]
Tab completion didn't work because of `vim.opt.paste = true` too!
