### ISSUE TITLE
Indentblankline activated When opening the Alpha

### ISSUE THREAD

**Issue by hawk90** [NvChad/NvChad#840]
**Describe the bug**
Indentblankline activated When opening the Alpha

**To Reproduce**

edit 
custom/chadrc.lua  

~~~
M.plugins = {
 status = {
  alpha = true,
 },
}
~~~  

and :PackerSync

**Expected behavior**
No activated Indentblankline

**Screenshots**
![image](https://user-images.githubusercontent.com/6481112/155679590-837f9572-01df-4ec6-b508-3ebf9b648cf5.png)

**Desktop (please complete the following information):**
 - Operating System: ubuntu18.04
 - Terminal: Wez's Terminal Emulator
 - Version of Neovim: 0.7.0-dev

**Additional context**

**Comment by boppyt** [comment]
I was unable to reproduce this in latest `master`.
![image](https://user-images.githubusercontent.com/71049646/155681960-8a24bbc4-88df-4075-993d-ef32e582c023.png)

Tested with your minimal config, commit `* 0cf5d77 - (vor 2 Tagen) (HEAD -> main, origin/main, origin/HEAD)`

**Comment by hawk90** [comment]
I tested in
~~~
commit 0cf5d77f72593593c6190373520d7826051b1a72 (HEAD, origin/main, origin/HEAD, main)
~~~
still have a problem.

**Comment by boppyt** [comment]
I've tested it in wezterm, foot, alacritty, kitty with/without tmux, and still cannot reproduce this problem.

Just in case, have you tried reinstalling nvchad?

```
-- Just an example, supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.ui = {
   theme = "gruvchad",
}

M.plugins = {
 status = {
  alpha = true,
 },
}

return M
```

**Comment by siduck** [comment]
unable to produce at all 
![image](https://user-images.githubusercontent.com/59060246/155698433-a1610d15-94de-4ac1-8c4a-6289a2038365.png)


Please do packersync

**Comment by hawk90** [comment]
I just reinstalled it. and reconfig.

the problem doesn't happend! thx!
