### ISSUE TITLE
Possible to not lazy load `Packer`?

### ISSUE THREAD

**Issue by xarthurx** [NvChad/NvChad#841]
**Is your feature request related to a problem? Please describe.**
I'm trying to use `vimtex`'s inverse search and call it from `cmd`.
This requires the use of `Packer` when `nvim` is not started:

```cmd /c start /min nvim --headless -c "PackerLoad vimtex"```

To achieve this, I need to disable this line:
https://github.com/NvChad/NvChad/blob/0cf5d77f72593593c6190373520d7826051b1a72/lua/plugins/init.lua#L18

Is it possible to do so in custom config?

(I don't want th change it every time I update `NvChad`)

**Comment by boppyt** [comment]
@siduck I think we should consider getting rid of this, and If I remember correctly you have said that it's basically useless.

And In the meantime, I believe this would work as a workaround for now:
```lua
M.plugins = {
  default_plugin_remove = {
    "wbthomason/packer.nvim",
  },

  install = {
    { "wbthomason/packer.nvim" },
  },
}
```

**Comment by siduck** [comment]
> @siduck I think we should consider getting rid of this, and If I remember correctly you have said that it's basically useless.
> 
> And In the meantime, I believe this would work as a workaround for now:
> 
> ```lua
> M.plugins = {
>   default_plugin_remove = {
>     "wbthomason/packer.nvim",
>   },
> 
>   install = {
>     { "wbthomason/packer.nvim" },
>   },
> }
> ```
> 
> This one should reside in your custom `chadrc`, thus not affected by NvChad upgrade.
yea i wasnt aware of how its lazy loaded but its not useless, i checked the mappings file and got to know that packer gets lazy loaded whenever packer commands are loaded. The work around is fine! :laughing:
