### ISSUE TITLE
How to remove a rule of nvim-autopairs

### ISSUE THREAD

**Issue by C1oud555** [NvChad/NvChad#846]
I want to remove the rule of "`" of nvim-autopairs. I don't find the default config of it in default init.lua . So I decide to add this

require('nvim-autopairs').remove_rule('`')

in custom/init.lua.
But after that, when I start nvim, it will report this:

error loading custom/init.lua

...te/pack/packer/opt/nvim-autopairs/lua/nvim-autopairs.lua:86: attempt to index field 'config' (a nil val
ue)

If this is a wrong approach to custom auto-pairs rules, please tell me the right way.

Macos, nvim 0.6.1, Alacritty

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/155937511-3f84f29f-7186-4f72-9c40-7832228162ae.png)
https://nvchad.github.io/config/Custom%20config#replace-default-config-of-a-plugin

**Comment by C1oud555** [comment]
@siduck Thanks for your solution. But after look through nvim-autopairs doc. I think it's rule can only be modified by Plugin Integration. No api to change that by replace config.

**Comment by zbirenbaum** [comment]
> @siduck Thanks for your solution. But after look through nvim-autopairs doc. I think it's rule can only be modified by Plugin Integration. No api to change that by replace config.

What do you mean by this exactly? Everything NvChad does with autopairs can be overriden, including totally removing autopairs from the NvChad plugin table and adding it to your own, so I am a bit confused.

**Comment by C1oud555** [comment]
I solved this by remove this plug from default and reinstall & reconfigure again😂
https://nvchad.github.io/config/Custom%20config#remove--redefine-plugins

**Comment by bryant-the-coder** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/155937511-3f84f29f-7186-4f72-9c40-7832228162ae.png)
> https://nvchad.github.io/config/Custom%20config#replace-default-config-of-a-plugin

colorscheme?

**Comment by C1oud555** [comment]
By default, nvim-autopairs will auto pair `, so when I press ` , it becomes ``.
 I want to delete the this ` rule, so when I press `, it won't auto pair another ` for me. 
But I can't simply put "require('nvim-autopairs').remove_rule('`')" in custom/init.lua, it reports error.

**Comment by 4ry1337** [comment]
how can I remove autopairs entirely?

**Comment by siduck** [comment]
@4ry1337 enabled=false
