### ISSUE TITLE
Remove nvim-tree plugin, cheatsheet still shows nvim-tree prompt

### ISSUE THREAD

**Issue by Near2U0** [NvChad/NvChad#849]
**Is your feature request related to a problem? Please describe.**
Remove nvim-tree plugin, cheatsheet still shows nvim-tree prompt

**Describe the solution you'd like**
Remove nvim-tree plugin, cheatsheet does not show nvim-tree prompt

**Additional context**

![image](https://user-images.githubusercontent.com/46817847/156119350-ee3fa764-6603-401e-b4a0-a69b112aba44.png)

![image](https://user-images.githubusercontent.com/46817847/156119430-890e42fc-194c-4c7e-be90-2ff199a1f842.png)

I also found that the line "relative_line_number_toggle" is too long and crowded with "leader+rn", I don't know if it has something to do with my display resolution
![image](https://user-images.githubusercontent.com/46817847/156119588-9f7e7a74-7677-4809-9cf0-b45ce239c2e4.png)

**Comment by siduck** [comment]
the cheatsheet isnt dynamic. It just shows the default keybinds. However we may add whichkey support in the near future
