### ISSUE TITLE
nvim-tree g:nvim_tree_window_picker_exclude not working

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#850]
**Describe the bug**
nvim-tree g:nvim_tree_window_picker_exclude not working
　
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
wym not working? where did you add it? how did you define it?

**Comment by tomasky** [comment]
nvim-tree remove the global config `g:nvim_tree_window_picker_exclude`,  
It should be configured like this  :
```lua
setup{
actions = {
      open_file = {
         window_picker = { exclude = {
            buftype = { "terminal", "help" },
         } },
      },
   },
}
```

**Comment by siduck** [comment]
i meant where did you add this config?

**Comment by tomasky** [comment]
in `custom/nvimtree.lua` file
```lua
default_plugin_config_replace = {
      nvim_tree = "custom.nvimtree",
   },
```

**Comment by tomasky** [comment]
Thanks , my own nvimtree configuration works fine
