### ISSUE TITLE
Start edit where left the file last time not working anymore?

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#854]
I had 
`vim.cmd([[au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif]])
` 
in my /lua/custom/chadrc.lua since month but for whatever reason lately it stoped working.
The file gets loaded as I can see when changing the theme but this line gets ignored?

**Comment by bryant-the-coder** [comment]
```lua
 
 ​--​ Restore cursor last position upon reopening the file 
 ​cmd​(​[[ 
 ​  augroup last_cursor_position 
 ​    autocmd! 
 ​    autocmd BufReadPost * 
 ​      \ if line("'\"") > 1 && line("'\"") <= line("$") && &ft !~# 'commit' | execute "normal! g`\"zvzz" | endif 
 ​  augroup END 
 ​]]​)
```

**Comment by bryant-the-coder** [comment]
use this. this worked for me

**Comment by se7en-x230** [comment]
thanks but also does not work for me ....

**Comment by bryant-the-coder** [comment]
u nid to hv vim.cmd. not only cmd

**Comment by boppyt** [comment]
`custom/init.lua`?

AFAIK chadrc is only used for pulling the user's config table.

**Comment by se7en-x230** [comment]
Something changed. My original setup in /lua/custom/ worked and now it gets ignored no matter what I do

**Comment by siduck** [comment]
> Something changed. My original setup in /lua/custom/ worked and now it gets ignored no matter what I do

very weird

**Comment by rrpolanco** [comment]
This doesn't seem to be working for me neither. I have 
```lua
vim.cmd([[ autocmd BufReadPost * if @% !~# '\.git[\/\\]COMMIT_EDITMSG$' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif ]])
```

in my lua/custom/autocmds.lua and is sourced from my custom/init.lua but it's not taking effect.

**Comment by siduck** [comment]
Im not sure whats causing this, can you remove plugin one by one and test it?

**Comment by rrpolanco** [comment]
> This doesn't seem to be working for me neither. I have
> 
> ```lua
> vim.cmd([[ autocmd BufReadPost * if @% !~# '\.git[\/\\]COMMIT_EDITMSG$' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif ]])
> ```
> 
> in my lua/custom/autocmds.lua and is sourced from my custom/init.lua but it's not taking effect.

Purging my compiled packer plugins (`rm -r ~/.config/nvim/plugin`) and running `PackerSync` made this work for me again.

**Comment by gamesky** [comment]
> > This doesn't seem to be working for me neither. I have
> > ```lua
> > vim.cmd([[ autocmd BufReadPost * if @% !~# '\.git[\/\\]COMMIT_EDITMSG$' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif ]])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in my lua/custom/autocmds.lua and is sourced from my custom/init.lua but it's not taking effect.
> 
> Purging my compiled packer plugins (`rm -r ~/.config/nvim/plugin`) and running `PackerSync` made this work for me again.

the latest neovim and nvchad , it still doesn't work

**Comment by gamesky** [comment]
The `.local/share/nvim/shada/main.shada` file not updated after editing some file when upgrade nvchad to latest

**Comment by gamesky** [comment]
Why remove the shadafile path config ? 

```lua
vim.schedule(function()
   vim.opt.shadafile = "NONE"
   vim.cmd [[ silent! rsh ]]
end)
```

**Comment by siduck** [comment]
you can override it, check how to change default options in our docs

**Comment by siduck** [comment]
@gamesky does that work on windows?

**Comment by siduck** [comment]
ig no cuz of the path!

**Comment by siduck** [comment]
well they can write the vim.schedule function in options.user function itself then! https://nvchad.github.io/config/Custom%20config#change-default-options
