### ISSUE TITLE
Use a base16 builder template to generate all the color schemes?

### ISSUE THREAD

**Issue by freddiehaddad** [NvChad/NvChad#856]
There are a limited number of base16 color schemes shipping with NvChad and I'm wondering if we can improve this.  Are there any potential issues with using a template to generate all the color schemes that are part of the base16 library?  This is the practice used within the repo as can be seen in the scheme repository section on the main github page.

The base16 color schemes:  https://github.com/chriskempson/base16

If all the existing color schemes follow the same pattern, then we should be able to create a yaml template and inject all the color schemes into the repository using a base16 builder (i.e. https://github.com/InspectorMustache/base16-builder-python)?

https://github.com/chriskempson/base16#scheme-repositories

I am happy to work on this and submit a PR if there's consensus that this will work.  Maybe even a few tips educating me on the organization and inner workings of the theming system in NvChad could be helpful.

**Comment by siduck** [comment]
generating colorschemes the automated way isnt a good idea imo. Before pushing the colorschemes, it kinda takes a while to test them and keep changing the colors until it gets perfect. So basically nvchad colorschemes are gonna be alive until I am
