### ISSUE TITLE
help!!! I set nvim-tree's option in custom/chadrc.lua, bud it doesn't work

### ISSUE THREAD

**Issue by U-DI-Page** [NvChad/NvChad#858]
here is my chadrc
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/14305674/156607266-64369018-92d3-4952-984b-73dd29062e14.png">

**Comment by U-DI-Page** [comment]
I reInstall nvChad and run :PackerSync after config the chadrc.lua, It works, I don't know why

**Comment by siduck** [comment]
> I reInstall nvChad and run :PackerSync after config the chadrc.lua, It works, I don't know why

good, i suggest you updating nvchad and nvim plugins daily
