### ISSUE TITLE
NvChad logo

### ISSUE THREAD

**Issue by siduck76** [NvChad/NvChad#86]
Submit your logos for NvChad  if you can make one ( It must be beautiful and clean)

- Can be a non text logo
- The text logo can be short and creative , something like this (neovim treesitter)

![image](https://user-images.githubusercontent.com/59060246/122562400-a8102400-d060-11eb-9f2f-c72033b78f3f.png)

**Comment by Mangeshrex** [comment]
@siduck76 I have made a simple logo and I have to edit even more in this [NvChad.png ](https://drive.google.com/file/d/1WpubBOmaV24JANYrUXBQ_JWatnsVS4-C/view?usp=drivesdk)

**Comment by siduck76** [comment]
> @siduck76 I have made a simple logo and I have to edit even more in this [NvChad.png ](https://drive.google.com/file/d/1WpubBOmaV24JANYrUXBQ_JWatnsVS4-C/view?usp=drivesdk)

![image](https://user-images.githubusercontent.com/59060246/122559057-72693c00-d05c-11eb-8eeb-a8df2139d2ea.png)

show it as an image here

**Comment by Mangeshrex** [comment]
Ahh shit ![20210618_171023_0000.png](https://user-images.githubusercontent.com/82205152/122559198-a80e2500-d05c-11eb-9353-51f5cfabe9d0.png) I sent that cu it wasn't accepting images

**Comment by siduck76** [comment]
It'd be nice if we had a non text logo -.-

**Comment by Mangeshrex** [comment]
Lmao then how do you want your logo to be? You should atleast tell what things would you like to include in it and some info about it

**Comment by siduck76** [comment]
you dont have to add period after the text logo tho , also you can make NV look like N .

**Comment by ashincoder** [comment]
join the NV to make it look like one letter. There should be chad to make it look better.

**Comment by Mangeshrex** [comment]
>  you dont have to add period after the text logo tho , also you can make NV look like N . Use sexy colors

How about if I use your xresources xD

**Comment by Vanderscycle** [comment]
""""
⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠛⠛⠋⠉⠈⠉⠉⠉⠉⠛⠻⢿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⡿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⢿⣿⣿⣿⣿ ⣿⣿⣿⣿⡏⣀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿ ⣿⣿⣿⢏⣴⣿⣷⠀⠀⠀⠀⠀⢾⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿ ⣿⣿⣟⣾⣿⡟⠁⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣷⢢⠀⠀⠀⠀⠀⠀⠀⢸⣿ ⣿⣿⣿⣿⣟⠀⡴⠄⠀⠀⠀⠀⠀⠀⠙⠻⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⣿ ⣿⣿⣿⠟⠻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠶⢴⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⣿ ⣿⣁⡀⠀⠀⢰⢠⣦⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⣿⣿⣿⣿⡄⠀⣴⣶⣿⡄⣿ ⣿⡋⠀⠀⠀⠎⢸⣿⡆⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⠗⢘⣿⣟⠛⠿⣼ ⣿⣿⠋⢀⡌⢰⣿⡿⢿⡀⠀⠀⠀⠀⠀⠙⠿⣿⣿⣿⣿⣿⡇⠀⢸⣿⣿⣧⢀⣼ ⣿⣿⣷⢻⠄⠘⠛⠋⠛⠃⠀⠀⠀⠀⠀⢿⣧⠈⠉⠙⠛⠋⠀⠀⠀⣿⣿⣿⣿⣿ ⣿⣿⣧⠀⠈⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠟⠀⠀⠀⠀⢀⢃⠀⠀⢸⣿⣿⣿⣿ ⣿⣿⡿⠀⠴⢗⣠⣤⣴⡶⠶⠖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡸⠀⣿⣿⣿⣿ ⣿⣿⣿⡀⢠⣾⣿⠏⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠉⠀⣿⣿⣿⣿ ⣿⣿⣿⣧⠈⢹⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿ ⣿⣿⣿⣿⡄⠈⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣦⣄⣀⣀⣀⣀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠙⣿⣿⡟⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠁⠀⠀⠹⣿⠃⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⢐⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⠿⠛⠉⠉⠁⠀⢻⣿⡇⠀⠀⠀⠀⠀⠀⢀⠈⣿⣿⡿⠉⠛⠛⠛⠉⠉ ⣿⡿⠋⠁⠀⠀⢀⣀⣠⡴⣸⣿⣇⡄⠀⠀⠀⠀⢀⡿⠄⠙⠛⠀⣀⣠⣤⣤⠄⠀
""""

**Comment by siduck76** [comment]
that doesnt view on dashbaord!

**Comment by siduck76** [comment]
> > you dont have to add period after the text logo tho , also you can make NV look like N . Use sexy colors
> 
> How about if I use your xresources xD

yes sure

**Comment by Vanderscycle** [comment]
> that doesnt display on dashbaord!
fixed it 
![chadTest](https://user-images.githubusercontent.com/52706578/122590724-cfda9a00-d016-11eb-9646-9b60276c078a.png)

**Comment by Mangeshrex** [comment]
Looks cool

**Comment by Mangeshrex** [comment]
Ahh looks very cool xD

**Comment by Mangeshrex** [comment]
> that doesnt display on dashbaord!

From where did you get that hydra ASCII? Are some more alternatives for that?

**Comment by Vanderscycle** [comment]
@Mangeshrex 
on the [Dashboard](https://github.com/glepnir/dashboard-nvim/wiki/Ascii-Header-Text) repo

**Comment by Mangeshrex** [comment]
Ok

**Comment by Vanderscycle** [comment]
also this is a pretty good tool https://505e06b2.github.io/Image-to-Braille/

**Comment by siduck76** [comment]
for now I want a logo something like [this](https://github.com/michaelb/sniprun)  has

**Comment by gishmel** [comment]
Wonder if something like this text is what you'd be looking for? My wife put it together and we weren't sure what symbol you'd want next to it similar to SnipRun but if you like the text happy to further develop it. Thanks for the awesome repo love the configurations set up in it. ![image](https://user-images.githubusercontent.com/2837051/126025038-3f61ae54-4f02-4e2b-9e0b-ba5e8b918c91.jpeg)

**Comment by siduck76** [comment]
@gishmel thanks for making it! I want a logo without a text tho , also no extra "v" letter . I wanted something styled similar to sniprun's , treesitter-nvim's logo , only N letter should be used

**Comment by se7en-x230** [comment]
![image](https://user-images.githubusercontent.com/69777713/126640594-e2f59881-5ae2-48b4-a35d-1aa14629dbcd.png)

...

**Comment by se7en-x230** [comment]
![image](https://user-images.githubusercontent.com/69777713/126641170-6c596b37-454d-432f-936b-25a771f8a3d8.png)

**Comment by siduck76** [comment]
Want something unique , creative and beautiful :D

**Comment by se7en-x230** [comment]
Summarize:
The logo should a short "N" letter without additional text, which is unique, creative, beautiful in sexy colors...

**Comment by siduck76** [comment]
> Summarize:
> The logo should a short "N" letter without additional text, which is unique, creative, beautiful in sexy colors...

yes , sounds dumb maybe but thats what it should be imo xD. Maybe someday I'll learn gimp/figma and make it , might take years too :/

**Comment by DJuan33** [comment]
What about this?

![image](https://user-images.githubusercontent.com/45220181/126820931-d5f8afb5-2002-4827-bad8-fffe48342c9d.png)

**Comment by siduck76** [comment]
> What about this?
> 
> ![image](https://user-images.githubusercontent.com/45220181/126820931-d5f8afb5-2002-4827-bad8-fffe48342c9d.png)

ouch! so far best logo submitted here! I'll think about it , also can you make it look like the chad's hiding behind the "N" letter?

**Comment by DJuan33** [comment]
> > What about this?
> > ![image](https://user-images.githubusercontent.com/45220181/126820931-d5f8afb5-2002-4827-bad8-fffe48342c9d.png)
> 
> ouch! so far best logo submitted here! I'll think about it , also can you make it look like the chad's hiding behind the "N" letter?

I'll try it after my lunch UwU

**Comment by DJuan33** [comment]
@siduck76 

I'm not sure about colors but what do you think?

![image](https://user-images.githubusercontent.com/45220181/126825222-770700be-53f0-4b84-9d81-826415696da6.png)

**Comment by siduck76** [comment]
> @siduck76
> 
> I'm not sure about colors but what do you think?
> 
> ![image](https://user-images.githubusercontent.com/45220181/126825222-770700be-53f0-4b84-9d81-826415696da6.png)

Lel 

> @siduck76
> 
> I'm not sure about colors but what do you think?
> 
> ![image](https://user-images.githubusercontent.com/45220181/126825222-770700be-53f0-4b84-9d81-826415696da6.png)

Lel , the logo should have N letter only!

**Comment by DJuan33** [comment]
> > @siduck76
> > I'm not sure about colors but what do you think?
> > ![image](https://user-images.githubusercontent.com/45220181/126825222-770700be-53f0-4b84-9d81-826415696da6.png)
> 
> Lel
> 
> > @siduck76
> > I'm not sure about colors but what do you think?
> > ![image](https://user-images.githubusercontent.com/45220181/126825222-770700be-53f0-4b84-9d81-826415696da6.png)
> 
> Lel , the logo should have N letter only!

Fine!

I did a SVG if you need it.

![image](https://user-images.githubusercontent.com/45220181/126825573-f2b48cca-e155-4fcd-850e-8d024cc6f994.png)

**Comment by siduck76** [comment]
> > > @siduck76
> > > I'm not sure about colors but what do you think?
> > > ![image](https://user-images.githubusercontent.com/45220181/126825222-770700be-53f0-4b84-9d81-826415696da6.png)
> > 
> > Lel
> > 
> > > @siduck76
> > > I'm not sure about colors but what do you think?
> > > ![image](https://user-images.githubusercontent.com/45220181/126825222-770700be-53f0-4b84-9d81-826415696da6.png)
> > 
> > Lel , the logo should have N letter only!
> 
> Fine!
> 
> I did a SVG if you need it.
> 
> ![image](https://user-images.githubusercontent.com/45220181/126825573-f2b48cca-e155-4fcd-850e-8d024cc6f994.png)
> 

Looks cool so far , I will consider using this if we don't get another logo better than this , in 2 months ;(

**Comment by siduck76** [comment]
https://github.com/vhyrro/neorg 's logo looks very nice and its just one letter! need something like this

**Comment by se7en-x230** [comment]
![image](https://user-images.githubusercontent.com/69777713/126885902-89b6258a-bd40-475d-9d8d-b1cbfbcb78b8.png)

**Comment by siduck76** [comment]
Also we shouldn't use neovim logo's gradient color , they don't look good imo! Use the colors from nvchad colorschemes.

**Comment by se7en-x230** [comment]
What are the nvchad colors?

**Comment by siduck76** [comment]
> What are the nvchad colors?

the ones from lua/themes.lua folder

**Comment by gaetgu** [comment]
@siduck76 Here is a flat icon I made. 
![NVChad logo](https://user-images.githubusercontent.com/47652746/127556421-d67c9d8d-d30d-44c5-aa0e-547bb0b6d5a6.png)

**Comment by siduck76** [comment]
> @siduck76 Here is a flat icon I made.
> ![NVChad logo](https://user-images.githubusercontent.com/47652746/127556421-d67c9d8d-d30d-44c5-aa0e-547bb0b6d5a6.png)

oo looks nice so far , I'll put this if we dont get any logo by next month.

**Comment by se7en-x230** [comment]
![image](https://user-images.githubusercontent.com/69777713/127610112-e8fa0f15-bdd2-44e8-a048-dad36531722a.png)

**Comment by siduck76** [comment]
No offense but this looks bad lul

**Comment by Iorvethe** [comment]
## The logo

![mock](https://user-images.githubusercontent.com/58810330/128641269-11afb22e-be0e-4f3a-9ca4-edeaa0d3bd34.png)

## The rationale behind

I tried to do something similar to Neovim's logo, having it as a starting point and reference. As you can see, Neovim's is an **N** containing a **V**, the green part. We can think of it as a continuation of Vim, an upgrade of it. That's what I tried to express.

I tried to show that NvChad is an amelioration of Neovim. As such, I followed the design style of the original logo which looks to me like a folded paper ribbon. You can notice that it now has two more folds forming a **C** next to the **N**.

As for the color palette, One Dark being the default theme, I figured I should use its colors. Also, they're pretty nice to look at!

I hope you like it, and don't hesitate to tell me if you want something from it to be changed, be it colors, shape or whatever. I'd be glad to help!

**Comment by siduck76** [comment]
@Iorvethe could you use similar colors?

https://cdn.dribbble.com/users/393931/screenshots/6138086/zawadi_02-04-04_4x.png

**Comment by siduck76** [comment]
Guys ik this is too early! But if by any chance someone could improve this or make a better logo before 19th then it will be very nice , gotta add the logo on the website ( gonna start  working with it soon )

**Comment by G-Rowell** [comment]
> ## The logo

@Iorvethe 

You that's pretty awesome! 
Very cool :smile:

**Comment by Iorvethe** [comment]
> > ## The logo
> 
> @Iorvethe
> 
> You that's pretty awesome!
> Very cool smile

Thank you very much! ^^

**Comment by siduck76** [comment]
also @lorvethe , could you make a logo with transparent bg too?

**Comment by Iorvethe** [comment]
There you go, the same but with the colors from the link above.

## With light and dark background

![mock_v2](https://user-images.githubusercontent.com/58810330/129737411-def216cc-126c-4410-a6cc-324e15a6568a.png)

## With transparent background

![transp_back](https://user-images.githubusercontent.com/58810330/129740641-d3369cc0-19d6-4e2c-a4c5-eb5629da6d62.png)

**Comment by siduck76** [comment]
Awesome! this looks very nice .

**Comment by Iorvethe** [comment]
Do you want it in the SVG file format?

**Comment by siduck76** [comment]
> Do you want it in the SVG file format?

ofc :)

**Comment by Iorvethe** [comment]
Any idea how I can send it to you? Apparently Github doesn't support this format...

Via e-mail or maybe through an MR?

**Comment by siduck76** [comment]
> Any idea how I can send it to you? Apparently Github doesn't support this format...
> 
> Via e-mail or maybe through an MR?

join our discord server https://discord.gg/sDKUMn3q
