### ISSUE TITLE
I can't enable cursor line

### ISSUE THREAD

**Issue by ahhshm** [NvChad/NvChad#863]
I added this to `custom/init.lua` to enable the cursor line but it didn't work:
```lua
vim.opt.cursorline = true
```
Then I noticed that the cursor line is enabled by default but for some reason, you cleared the `CursorLine` highlight in `colors/highlight.lua` so it doesn't show up.

```lua
-- Disable cursor line
cmd "hi clear CursorLine"
```

**Comment by zahimeen** [comment]
Yeah, this kinda bugged me too but I just went around it and highlighted it myself. I do recommend creating a pull request or something to fix this. No clue why the development team decided to disable it.

**Comment by siduck** [comment]
> Yeah, this kinda bugged me too but I just went around it and highlighted it myself. I do recommend creating a pull request or something to fix this. No clue why the development team decided to disable it.
> 
> For reference, I used the following lines of code in the `init.lua` file in the custom config directory:
> 
> ```lua
> vim.cmd [[
> 
>    augroup ilikecursorline
>       autocmd VimEnter * :highlight CursorLine guibg=#282a2e
>    augroup END
> 
> ]]
> ```

no need for that, check https://github.com/NvChad/NvChad/pull/865#issuecomment-1060086826

**Comment by txchen** [comment]
@siduck what's the correct way to enable cursorline now? I still need to use @zahimeen 's solution to make it work.

**Comment by siduck** [comment]
@txchen 

![image](https://user-images.githubusercontent.com/59060246/170875680-e2abdd81-2521-450b-9a91-71ef1713ae52.png)


you just need to override its hl group. Check our docs to learn about it :)

**Comment by Shahabaz-Bagwan** [comment]
overriding the HL group in "custom/highlights.lua" is not working the solution provided by @zahimeen is working as expected. 
![image](https://github.com/NvChad/NvChad/assets/4272320/222a65bb-8c30-4551-9e68-33b2d4575e87)

**Comment by siduck** [comment]
> overriding the HL group in "custom/highlights.lua" is not working the solution provided by @zahimeen is working as expected. ![image](https://user-images.githubusercontent.com/4272320/240880729-222a65bb-8c30-4551-9e68-33b2d4575e87.png)

weird, works fine here

![image](https://github.com/NvChad/NvChad/assets/59060246/21fc97da-964d-4b3b-a165-844fbbe11d8a)

**Comment by Shahabaz-Bagwan** [comment]
![image](https://github.com/NvChad/NvChad/assets/4272320/9d924206-f863-4872-81d2-4dc9fc4ee757)

no luck.

EDIT: I tried in docker with clean install it is working. I guess it is something to do with may changes.

**Comment by siduck** [comment]
> ![image](https://user-images.githubusercontent.com/4272320/240946955-9d924206-f863-4872-81d2-4dc9fc4ee757.png)
> 
> no luck.
> 
> EDIT: I tried in docker with clean install it is working. I guess it is something to do with may changes.

make sure you dont have broken stuff in  your config, try our example_config repo

**Comment by jeffvandyke** [comment]
I was very annoyed that NvChad seemed to be allowing a cursor column, but cleared the cursor line highlighting group. The solution I had to ultimately go with after lacking an easy way to set the cursor line to match cursor column was to use a highlight link autocommand in lua in my `custom/init.lua` file:
```
-- Undoes NvChad's effect of clearing CursorLine
vim.api.nvim_create_autocmd({ "VimEnter" }, {
  pattern = { "*" },
  command = "highlight link CursorLine CursorColumn",
})
```

**Comment by siduck** [comment]
@jeffvandyke thats bad, all you have to do is add CursorLine & CursorColumn in hl_override

**Comment by jeffvandyke** [comment]
What do I set them to so that they follow whatever theme I happen to pick for the day? I can't use hardcoded hex colors since I want it to change per theme, and it's not obvious which "theme" color is used for CursorColumn. The best solution for me would be to have NvChad avoid clearing CursorLine and behave normally (stick to the defaults) as much as possible so I don't have to look into things like this.

**Comment by Shahabaz-Bagwan** [comment]
> What do I set them to so that they follow whatever theme I happen to pick for the day? I can't use hardcoded hex colors since I want it to change per theme, and it's not obvious which "theme" color is used for CursorColumn. The best solution for me would be to have NvChad avoid clearing CursorLine and behave normally (stick to the defaults) as much as possible so I don't have to look into things like this.

https://github.com/Shahabaz-Bagwan/nvChadCustom/blob/2027437a9cd5f78d255b4218296b33de79399838/highlights.lua

try this. I had the same issue but as @siduck mentioned overriding in the highlights.lua file solve the issue.

**Comment by jeffvandyke** [comment]
Like I said, I can't use hard-coded hex colors. If I do, then if I change my theme to a different one (especially a light one), the colors are different between the column and line.
<img width="398" alt="image" src="https://github.com/NvChad/NvChad/assets/6729124/7c42cd36-f171-42e2-8a0a-05f5e755075c">

**Comment by jeffvandyke** [comment]
I also added a note on a related closed PR - https://github.com/NvChad/NvChad/pull/865#issuecomment-1785811684 - If some people don't like the CursorLine appearance, then the correct solution is: _turn off the `'cursorline'` option_ - that's the entire point of that option: to show or hide this line, and needing to do such convoluted workarounds to undo the clearing of this highlight group so that it behaves normally again for the people that find it useful is time wasting and unintuitive.

**Comment by Shahabaz-Bagwan** [comment]
> @txchen 
> 
> ![image](https://user-images.githubusercontent.com/59060246/170875680-e2abdd81-2521-450b-9a91-71ef1713ae52.png)
> 
> 
> you just need to override its hl group. Check our docs to learn about it :)

@jeffvandyke have you tried using the name from the theme instead of hardcoded value?

Edit:

You can find all the themes and their respective colors here
https://github.com/NvChad/base46/tree/v2.0/lua%2Fbase46%2Fthemes

**Comment by Shahabaz-Bagwan** [comment]
> What do I set them to so that they follow whatever theme I happen to pick for the day? I can't use hardcoded hex colors since I want it to change per theme, and it's not obvious which "theme" color is used for CursorColumn. The best solution for me would be to have NvChad avoid clearing CursorLine and behave normally (stick to the defaults) as much as possible so I don't have to look into things like this.

The reason behind clearing the highlights group is to show the highlighted line number which is only possible when Cursorline is set.

https://stackoverflow.com/questions/8247243/highlighting-the-current-line-number-in-vim

**Comment by jeffvandyke** [comment]
Thanks, the `one_bg*` family of background colors might make sense if I needed to manually set highlighting for `CursorLine`.

To your second point, however, what about option `set cursorlineopt=number`? The default for this option is `number,line`, but setting to "number", according to docs has this effect: "Highlight the line number of the cursor with CursorLineNr |hl-CursorLineNr|." This seems like a much better way to highlight your number without hacking highlighting rules, and allow for user's configs to easily override this back to the default if they find it useful.

Edit: just confirmed that setting this option to number works, even without the CursorLine highlight cleared. I'd highly recommend setting this opt instead of clearing the highlight group.

**Comment by asmathfire** [comment]
Someone help me because I am from windows. I Have the same issue and I don't know how to doo this for a clean Nvchad install and I do not know anything abt neovim configurations and writing them. @siduck your link in #865 is not working anymore. Please help

**Comment by siduck** [comment]
vim.o.culopt = "both"

**Comment by asmathfire** [comment]
@siduck  Thank you. If you can please integrate neotree-nvim instead of nvim-tree because it is better at handling larger files with larger directories present inside them. It also SIGNIFICANTLY reduces input lag when done so. Thank you very much.

**Comment by siduck** [comment]
@AshwinWhjr1  just disable nvimtree and setup neotree

**Comment by asmathfire** [comment]
@siduck I know it is like a recommendation. It is a recommendation for NvChad. 
Thank You.

**Comment by siduck** [comment]
@AshwinWhjr1 I appreciate it but now replacing anything such as a plugin will make a huge breaking change which I cant do. Years ago, NvChad was known for its breaking changes but since last  2 years Ive been trying my best to  keep it stable
