### ISSUE TITLE
Buffers closing when switching to another buffer

### ISSUE THREAD

**Issue by Johnsiras** [NvChad/NvChad#867]
**Describe the bug**
Buffers are closing when trying to switch on another buffer

**To Reproduce**
1. Open a new tab (or open a terminal with `CTRL + w`)
2. Switch to a buffer using `S-tab` or `tab`

**Expected behavior**
Switch to buffers without any issues

**Screenshots**

https://user-images.githubusercontent.com/78542955/157175226-5cb5f141-d003-4622-86e6-b6df9b5ad915.mp4

**Desktop (please complete the following information):**
 - Windows, 19.0
 - Wezterm
 - Nvim 16.1

**Comment by Johnsiras** [comment]
Isn't this some plugin problem?

**Comment by siduck** [comment]
@Johnsiras sorry for the late response! this is a plugin feature ( bufferline ) and not a bug
