### ISSUE TITLE
Chadrc is not read for plugin status and plugin remove

### ISSUE THREAD

**Issue by gshakir** [NvChad/NvChad#868]
My chadrc

M.plugins = {

  status = {
    alpha = true,
  },

  options = {
    lspconfig = {
      setup_lspconf = "custom.plugins.lspconfig",
    },
  },

   default_plugin_remove = {
     "akinsho/bufferline.nvim",
   },

  install = userPlugins,
}

The status and default_plugin_remove doesn't work. It works if I make the change in the default_config.lua

**Comment by gshakir** [comment]
Debugged to find 'pcall' for chard fails. I am on Mac.

+   --local chadrcExists, change = pcall(require, "custom.chadrc")
+   local change = require "custom.chadrc"

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/157593991-ffc3da8b-dab1-4983-b276-347e22264357.mp4

works here :/

**Comment by gshakir** [comment]
Thank you. So I traced it down to syntax issues in chadrc.lua and other custom files. I believe this is the source of lot of issues that magically get resolved. What is the best way to check health and syntax of custom lua files? We should add that in the https://nvchad.github.io/config/Custom%20config page.

**Comment by siduck** [comment]
> Thank you. So I traced it down to syntax issues in chadrc.lua and other custom files. I believe this is the source of lot of issues that magically get resolved. What is the best way to check health and syntax of custom lua files? We should add that in the https://nvchad.github.io/config/Custom%20config page.

idk, maybe check codeactions or just write good code xD
