### ISSUE TITLE
Pressing tab pastes a recursive thing?

### ISSUE THREAD

**Issue by Johnsiras** [NvChad/NvChad#872]
**Describe the bug**
When pressing tab on insert mode, it pastes a cmp.u.k.recursive thing

**To Reproduce**
1. Go to insert mode
2. Press tab

**Expected behavior**
Add a space (normal tab)

**Screenshots**
![wezterm-gui_1jJVsJYrkU](https://user-images.githubusercontent.com/78542955/158298304-56a5f15e-0f24-4128-86ae-90e06b6b2807.gif)

**Desktop (please complete the following information):**
 - Windows 10
 -  Wezterm
 - 16.1

**Comment by siduck** [comment]
can u try alacritty

**Comment by Johnsiras** [comment]
it's the same

**Comment by siduck** [comment]
when was the last time you updated nvchad and did packersync?

**Comment by Johnsiras** [comment]
i mean two days

**Comment by Johnsiras** [comment]
is it an issue with cmp, or the config?

**Comment by Johnsiras** [comment]
this must be a config problem, my friend says that cmp is working fine for him.

**Comment by siduck** [comment]
can you remove your custom dir and do a packersync and check again?

**Comment by Johnsiras** [comment]
ok!

**Comment by Johnsiras** [comment]
It is my custom config, i don't even know which one does affect cmp 🤔

**Comment by Johnsiras** [comment]
OH! it's copilot.vim issue! i mean config mistake, i disabled the tab map so it's doing that! Thank you for your help btw!

Im gonna close this now
