### ISSUE TITLE
Unable to set base16 theme using nvim-base16

### ISSUE THREAD

**Issue by garrettmaring** [NvChad/NvChad#875]
Nvchad installs the nvim-base16 be default 👍  I have a simple base16 theme that I'd like to set as my NvChad theme.

Reading the [nvim-bas16](https://github.com/RRethy/nvim-base16) I tried the following but don't see my changes persisting.

What is the correct way to set a base16 theme?

```lua
M.plugins = {
   default_plugin_config_replace = {
     nvim_base16 = {
       config = function() {
         local colorscheme = require('nvim-base16')

         colorscheme.setup({
           base00 = '#21201e', base01 = '#292929', base02 = '#383838', base03 = '#585858',
           base04 = '#b6b8b8', base05 = '#d6d8d8', base06 = '#e6e8e8', base07 = '#fbffff',
           base08 = '#bc404e', base09 = '#dc965f', base0A = '#fadc68', base0B = '#96be0e',
           base0C = '#46bdb4', base0D = '#389ED5', base0E = '#b295f0', base0F = '#a16946',
         })
       }
     }
   },
}
```

**Comment by siduck** [comment]
our base16 plugin is different from that! We'll add support for adding local themes soon

**Comment by siduck** [comment]
https://nvchad.github.io/contribute#how-to-submit-themes
