### ISSUE TITLE
An error occurred while installing the built-in plugin. The built-in plugin cannot be updated

### ISSUE THREAD

**Issue by pjhui-go** [NvChad/NvChad#876]
**Describe the bug**
When executing the following command：
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync

There is an error when install github plugin:

![1](https://user-images.githubusercontent.com/55966040/158503414-41bd20ad-bf13-452a-b064-a73c2437e3b1.png)
![2](https://user-images.githubusercontent.com/55966040/158503443-470cb94d-28c1-4117-a634-9f97f9e56285.png)

thanks

**Comment by siduck** [comment]
weird, is your internet very slow

**Comment by pjhui-go** [comment]
Network speed is not slow, independent installation of plug-ins can be installed soon

**Comment by siduck** [comment]
im unable to produce this :l

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/159144277-ee127fbd-a798-4554-adc6-40d48bb5dbec.mp4

works fine here
