### ISSUE TITLE
Being able to define a map command to be used by a plugin

### ISSUE THREAD

**Issue by maxyz** [NvChad/NvChad#878]
Currently we have a way to redefine some of the keybindings used, but to redefine the command they call we'll have to redefine the plugins setup.

For example, let's say I want to call `NvimTreeFindFile` with `<leader>e` instead of `NvimTreeFocus`.

Following the documentation we might assume that a simple:
```lua
map("n", "<leader>e", "<cmd>NvimTreeFindFile<CR>")
```

in the custom/init.lua would be enough, but it doesn't work, as the nvim-tree setup is called afterwards.

So we need to disable the mapping from the plugin, using custom/chadrc.lua:
```lua
M.mappings = {
  plugins = {
    nvimtree = {
      focus = "",
    },
  },
}
```

In order to replace the command that is being used in the nvim-tree setup.

**Describe the solution you'd like**
I would like have a user hook in the default plugins so we can execute things after the plugins.

That would be something like:
```lua
M.plugins = {
  default = {
    nvim_tree = {
      on_setup = function()
        map("n", "<leader>e", "<cmd>NvimTreeFindFile<CR>")
      end,
    },
  },
}
```

**Comment by siduck** [comment]
:rocket:
