### ISSUE TITLE
nvim-tree no_focus not effective

### ISSUE THREAD

**Issue by zaixi** [NvChad/NvChad#880]
**Describe the bug**
nvim-tree no_focus not effective

**To Reproduce**
1. NvimTreeToggle
2. NvimTreeToggle
3. NvimTreeFindFileToggle
4. The cursor jumps to the nvim-tree window

**Expected behavior**
After opening nvim-tree, the cursor is still in its original position

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System：Ubuntu18.04
 - Terminal: gnome-terminal
 - Version of Neovim:0.6.1

**Additional context**

**Comment by boppyt** [comment]
How are you setting the `no_focus` option?

AFAIK it's only available in lua toggle function.

**Comment by zaixi** [comment]
> 你是如何设置`no_focus`选项的？
> 
> AFAIK 它仅在 lua 切换功能中可用。

**Comment by zaixi** [comment]
> How are you setting the `no_focus` option?
> 
> AFAIK it's only available in lua toggle function.

Nvimtreefindfiletoggle command with no_focus  parameter

**Comment by siduck** [comment]
> > How are you setting the `no_focus` option?
> > AFAIK it's only available in lua toggle function.
> 
> Nvimtreefindfiletoggle command with no_focus parameter

share that command

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/166101928-0cc633ff-2cb9-4e9e-9a08-d839c10a384d.png)

gives this error 
![image](https://user-images.githubusercontent.com/59060246/166101937-12a09415-45f6-403b-ab6f-03810abf016b.png)


![image](https://user-images.githubusercontent.com/59060246/166101948-ac2b0599-5072-441f-a4cb-e1387fbcd3b1.png)

gives this errro 
![image](https://user-images.githubusercontent.com/59060246/166101952-e82b948b-30bc-44a8-a560-e77706941231.png)

**Comment by siduck** [comment]
Ok found the fix, that error pops up cuz nvimtree module isnt loaded and we lazy loaded nvimtree so the module will only load when nvimtree or nvimtreefocus commands are run ( these are loaded by mappings )

So this issue will get fixed if u open nvimtree once after entering neovim or just disable lazy loading in nvimtree by 

```lua

local M = {}

M.plugins = {
   user = {
      ["kyazdani42/nvim-tree.lua"] = {
         cmd = false,
      },
   },
}

return M
```

check our docs! a lot has changed regarding the syntax of custom config.
