### ISSUE TITLE
Please stop telling me to check my config for correctness

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [NvChad/NvChad#881]
This message is really annoying. It appears every time I open neovim and it's not telling me anything useful like the line in which there is an error. So please just make it stop.

**Comment by Johnsiras** [comment]
and i think this is not about nvchad issue, this is nvim issue it must be your config problem.

**Comment by boppyt** [comment]
This is coming from packer, when it failed to load the packer_compiled file.

Normally this shouldn't happen, you probably do have an error somewhere.

**Comment by siduck** [comment]
your config issue!!
