### ISSUE TITLE
Statusline overlaying artifact drawn

### ISSUE THREAD

**Issue by DreamingRaven** [NvChad/NvChad#882]
**Describe the bug**
Firstly thank you for NvChad it is amazing!

<del>After updating / merging NvChad to version in master branch (and dealt with the breaking changes) I get an overlaying block of text that hides what I am currently typing/ impeding writing. </del> Nothing to do with NvChad update seems to be a change in some dependency used by NvChad in the last 3 weeks since the last container was built.
I think an image (in the screenshots section) of the previous version ( <del>commit: 9d013a35</del>, top image) vs the new version (<del>commit: 4ad0bf1</del>,
bottom image) helps illustrate this strange overlaying artifact.

<del>This could be due to dockerisation but this worked without issue from a previous commit, which leads me to believe it was a recent change. I also completely deleted my own custom configuration (mostly copied from siducks example configs in staging) but the issue persists even without them completely.</del>

**To Reproduce**
Steps to reproduce the _faulty_ behavior:

(This works with and without my customisations which are mostly siducks in this version)
1. sudo docker run -it registry.gitlab.com/deepcypher/dockeride:bork-statusline
2. insert mode
3. start typing
4. notice what looks like a copy of the statusline has appeared on top of what you are writing.

Steps to reproduce the _working_ behavior from 3 week old container:

1. sudo docker run -it registry.gitlab.com/deepcypher/dockeride:master
2. insert mode
3. start typing
4. nothing happens, you type as normal

The specific dockerfile can be seen: https://gitlab.com/deepcypher/dockeride/-/blob/master/Dockerfile
which is unchanged apart from adding autopep8 and pynvim to the container:
```
diff --git a/Dockerfile b/Dockerfile
index 47d4c94..443e922 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -23,6 +23,8 @@ RUN apk add --repository "https://dl-cdn.alpinelinux.org/alpine/edge/testing" \
     python3 \
     py3-pip \
     py3-language-server \
+    py3-autopep8 \
+    py3-pynvim \
     nodejs \
     npm && \
     npm install -g dockerfile-language-server-nodejs
```

**Expected behavior**
The expected behavior can be seen in the first image where the artifact is not present as it was in a previous version.

**Screenshots**

![larized](https://user-images.githubusercontent.com/10534713/158836890-0a6889f7-0095-4a07-8475-47c091ffd366.png)

**Desktop (please complete the following information):**
 - Operating System: Archlinux (Docker container OS: Alpine:edge)
 - Terminal (rxvt-unicode fish piped into container bash)
 - Version of Neovim (v0.6.1)

**Additional context**
This is part of a dockerised NvChad project ( https://gitlab.com/deepcypher/dockeride )
The full command to run it with buffer sharing (in X11):
```
xhost local:root && sudo docker run -e DISPLAY --volume /tmp/.X11-unix:/tmp/.X11-unix --volume /home/archer/git/dockeride:/playground -it registry.gitlab.com/deepcypher/dockeride:master
```
replace /home/archer/git/dockeride with whatever dir you want to mount inside the container for editing

Edit: Updated likely dependency change cause

**Comment by DreamingRaven** [comment]
Tested using the docker container in readme seems to work without the artifact. Hmm maybe it is a problem with the docker build itself in comparison to the one in the readme. This would suggest it is a dependency or some change in my dockerfile not present when simply running the alpine container with bare minimal additions:
![runline](https://user-images.githubusercontent.com/10534713/158976223-0d166cec-3540-44d9-b426-338c550d9199.png)

**Comment by siduck** [comment]
:thin

**Comment by DreamingRaven** [comment]
Yeaaaahh... I know. A bit of a difficult issue to pin down.
I figured you might have some idea of the cause, or possibly seen something similar. I will deep dive the issue when I can, strip everything out of the container and work my way up until I find what is causing the problem, since at-least the readme container works.

The Jackie Chan "what" meme comes to mind. That's how im imagining that emoji IRL.

**Comment by siduck** [comment]
hmm if the readme container works then this might be issue with you container! Idk much about docker, I tested your container and works fine too 

![image](https://user-images.githubusercontent.com/59060246/159143927-b9ea9e24-94cd-47a9-b5c2-9eaafee6c728.png)

**Comment by DreamingRaven** [comment]
Yeah its an odd one, thanks for giving it a read and a look through the container. I appreciate it!

For the sake of completeness before I close this github-issue I have tracked down the problem to the installation of python3 inside the container and some of the like packages (not sure if one specific package of the set is causing the issue yet until further testing).

simply changing:
```
# language dependencies, and language servers for things like CoC
RUN apk add --repository "https://dl-cdn.alpinelinux.org/alpine/edge/testing" \
    go \
    gopls \
    rust \
    cargo \
    python3 \
    py3-pip \
    py3-language-server \
    nodejs \
    npm && \
    npm install -g dockerfile-language-server-nodejs

# symlink python to python3 since it is not done by default
RUN ln -s /usr/bin/python3 /usr/bin/python
```
to this:
```
# language dependencies, and language servers for things like CoC
RUN apk add --repository "https://dl-cdn.alpinelinux.org/alpine/edge/testing" \
    go \
    gopls \
    rust \
    cargo \
    npm && \
    npm install -g dockerfile-language-server-nodejs
    # python3 \
    # py3-pip \
    # py3-language-server \
    # py3-autopep8 \
    # py3-pynvim \

# # symlink python to python3 since it is not done by default
# RUN ln -s /usr/bin/python3 /usr/bin/python

```
fixes the container. Clearly something must have changed with regards to python and nvim or atleast the alpine package of python.

A strange problem but hey atleast it works again. Although I will need to re-add python at some point since it is supposed to be a containerised IDE for multiple langs.

The following now works as expected on both the master and staging branches:
```
sudo docker run -it registry.gitlab.com/deepcypher/dockeride:master
sudo docker run -it registry.gitlab.com/deepcypher/dockeride:staging
```
Cheers

**Comment by siduck** [comment]
> I think I'm experiencing the same bug on openSUSE Tumbleweed since this week, no container used.
> 
> Freshly opened nvim, just typing `test` shows the following:
> 
> ![image](https://user-images.githubusercontent.com/8134686/159478830-14c1429f-5715-4641-b750-796a4c7b2a4b.png)
> 
> after going out of input mode and adding a new line the artifact disappears but will reappear when writing a new word starting with the letter `t`, typing something like `blahblah` appears to not trigger it then.

which nvim version?

**Comment by mohms** [comment]
NVIM v0.6.1

Just tried it on my laptop running fedora and it doesn't happen there. Same nvim version, same config, nvchad up to date and frehly run :PackerSync on both machines

**Comment by DreamingRaven** [comment]
Yes this does look identical to the problem I have with python in my docker containers :/
I will re-open this issue since it appears not to be isolated to my own work.
The only difference being I could type literally anything and the problem would manifest rather than the letter t.

**Comment by DreamingRaven** [comment]
Ok so for the purposes of finding a fix to this now that it is not just myself, I have created a purposefully broken branch with the minimal changes needed to break  the statusline and cause this behavior. The only things that are different to a working version is simply installing python3. However being that the last update to python was more than 3 weeks ago, this means the problem is not actually python3 but something interacting with python3 when it becomes available, and that other thing is what updated in the last 3 weeks that breaks the statusline.
![py3](https://user-images.githubusercontent.com/10534713/159488879-7e2282ca-33ff-49a2-a3e9-f9fffa69e4d3.png)

borked version available here:
https://gitlab.com/deepcypher/dockeride/-/tree/bork-statusline 

Once the container is done building it should be available at: registry.gitlab.com/deepcypher/dockeride:bork-statusline
That way at-least it can be inspected by anyone with docker installed who might have some input.

You can either build the container locally or pull from the above registry (assuming user is not in the docker group):
```
sudo docker pull registry.gitlab.com/deepcypher/dockeride:bork-statusline && sudo docker run -it registry.gitlab.com/deepcypher/dockeride:bork-statusline
```
This way atleast we can all be on the same page since we all can reproduce exactly what is breaking.

**Comment by mohms** [comment]
> The only difference being I could type literally anything and the problem would manifest rather than the letter t.

Just tried again, my first impression was that it is only triggered upon typing the first letter of the word in the first line again (first line was `test` so I thought the t is what triggers it), but it also happens with any other input. After Line 1 it doesn't always happen at the first character/word though.

**Comment by siduck** [comment]
does using any other terminal fix this issue? try my st build 

https://github.com/siduck/st

**Comment by DreamingRaven** [comment]
After the first line it triggers whenever an autocompletion comes up. So if get past the first line where it always happens. I can type a word like `acute` then if I type the letter `a` on the next line triggering an autocompletion for the word `acute` brings this overlayed statusline issue every time.

**Comment by DreamingRaven** [comment]
> does using any other terminal fix this issue? try my st build
> 
> https://github.com/siduck/st

I will try that, will add some lines to the container, so might take a tad.

**Comment by DreamingRaven** [comment]
> Quick test with some terminal emulators. Kitty and Alacritty seem to work normally, no artifacts show up.
> 
> Where it happens: gnome-terminal, tilix

I dont seem to get the same results as you, but again I am working from a container, and the raw specifics of how the terminal interacts with shells and processes inside containers might just be muddying the waters. But so far none of the combinations solve the issue. + if it was a terminal issue it would in theorey always appear rather than only when the python3 package is present.

**Comment by mohms** [comment]
I just tried the container. Running my OS installed nvim in kitty does not trigger the bug, but it shows up when I run your container in the same kitty terminal

**Comment by DreamingRaven** [comment]
> I just tried the container. Running my OS installed nvim in kitty does not trigger the bug, but it shows up when I run your container in the same kitty terminal

Hmm. I think I may need to do some reading about how the background of Docker and the users terminal are interacting, but this maybe gives credence to the theory that it is unrelated to the term-emulator being used. 
But it still doesnt make sense why it would only be present when python3 is present :/ Not sure what to look into next. I might try looking through any issues in the felyn repo related to python.

**Comment by DreamingRaven** [comment]
btw @siduck is there any way to disable all the completion plugins at once? I tried:
``` 
m.plugins = {
  status = {
    cmp = false,
  },
}
```
since it appears all cmp related plugins have  a line with `disable = not plugin_settings.status.cmp` but this just fails with `All parsers are up-to-date![packer.nvim] [ERROR 14:36:41] a...596: attempt to index a nil value`

The reason I ask is since it seems to happen on autocompletion I thought I might try without the autocompletion plugins to see what happens if it can give any more clues.

**Comment by siduck** [comment]
> btw @siduck is there any way to disable all the completion plugins at once? I tried:
> 
> ```
> m.plugins = {
>   status = {
>     cmp = false,
>   },
> }
> ```
> 
> since it appears all cmp related plugins have a line with `disable = not plugin_settings.status.cmp` but this just fails with `All parsers are up-to-date![packer.nvim] [ERROR 14:36:41] a...596: attempt to index a nil value`
> 
> The reason I ask is since it seems to happen on autocompletion I thought I might try without the autocompletion plugins to see what happens if it can give any more clues.

do packersync after that

**Comment by siduck** [comment]
> Quick test with some terminal emulators. Kitty and Alacritty seem to work normally, no artifacts show up.
> 
> Where it happens: gnome-terminal, tilix

So i doubt if its a nvchad issue o_o

**Comment by siduck** [comment]
show your custom dir

**Comment by mohms** [comment]
removed my custom dir and ran `:PackerSync`, still happens in the vte terminals.

> So i doubt if its a nvchad issue o_o

I guess you're right, it's especially weird since it doesn't happen on my fedora machine with the same terminals. Another difference I noticed is this `[No Name] - NVIM`
![image](https://user-images.githubusercontent.com/8134686/159892466-9963a3f7-a703-4c80-8b5e-3df619fa8991.png)

It is not present in the bug-free terminals.

**Comment by siduck** [comment]
> removed my custom dir and ran `:PackerSync`, still happens in the vte terminals.
> 
> > So i doubt if its a nvchad issue o_o
> 
> I guess you're right, it's especially weird since it doesn't happen on my fedora machine with the same terminals. Another difference I noticed is this `[No Name] - NVIM` ![image](https://user-images.githubusercontent.com/8134686/159892466-9963a3f7-a703-4c80-8b5e-3df619fa8991.png)
> 
> It is not present in the bug-free terminals.

very weird

**Comment by DreamingRaven** [comment]
I see that too, although not sure what the significance would be.
![work-vs-bork](https://user-images.githubusercontent.com/10534713/159893341-e9df67e8-6c31-44c0-9e8e-1e6c408d1ba4.png)

**Comment by siduck** [comment]
> I see that too, although not sure what the significance would be. ![work-vs-bork](https://user-images.githubusercontent.com/10534713/159893341-e9df67e8-6c31-44c0-9e8e-1e6c408d1ba4.png)

whats the terminal on the right? does this happen with lunarvim?

**Comment by DreamingRaven** [comment]
> whats the terminal on the right? does this happen with lunarvim?

Both are the same except the left hand docker image does not have python installed, and the one on the right has python3 installed. As far as I am aware there is no lunarvim package (in either), unless it is installed by default by NVChad which it doesnt look like it is. I can try it with lunarvim if that is what you meant. (adding package now to test)

**Comment by DreamingRaven** [comment]
O_O
![wtf](https://user-images.githubusercontent.com/10534713/159896844-5a2a7f93-1e70-43f5-be99-6291ee8a764c.png)
OOOOk so this is definateley beyond NVChad!

**Comment by DreamingRaven** [comment]
Is it something the two share? Because this doesnt happen in base nvim.

**Comment by siduck** [comment]
> Is it something the two share? Because this doesnt happen in base nvim.

try it with astrovim

**Comment by DreamingRaven** [comment]
## Astrovim
![astrovim](https://user-images.githubusercontent.com/10534713/159902811-b7a9330b-c7f9-44ba-b29e-4a8b3f39e4b8.png)
there was a small problem with autopairs initially with astrovim, but it appears to be working fine. No issues in the otherwise broken container. And no [No Name] in the statusline.

## Spacevim
![spacevim](https://user-images.githubusercontent.com/10534713/159903372-25762a7e-f054-43d6-94af-25908c167952.png)
Spacevim doesnt like when it loses focus, and while you cant see it here because when it loses focus it covers up the [No Name] in the statusline.

**Comment by DreamingRaven** [comment]
So so far it seems AstroVim is the only one that functions properly as all the others have the [No Name] in place of the specific git branch, or completely cover the text in some auto completion manner.

**Comment by siduck** [comment]
> So so far it seems AstroVim is the only one that functions properly as all the others have the [No Name] in place of the specific git branch, or completely cover the text in some auto completion manner.

hmm does this occur if you remove lazy loading from cmp?

**Comment by DreamingRaven** [comment]
Sure I can try it, but i'm not entirely sure how I can go about it if i'm honest with you. Is there an easy way I can do it to test it?

**Comment by siduck** [comment]
> Sure I can try it, but i'm not entirely sure how I can go about it if i'm honest with you. Is there an easy way I can do it to test it?

just remove the insertenter here  and packercompile

![image](https://user-images.githubusercontent.com/59060246/160305081-aa07110f-06cf-457c-9102-99ea775bea1d.png)

**Comment by DreamingRaven** [comment]
left is with without event = "InsertEnter", right is with "InsertEnter". The dockerfile is rebuilt from scratch so it shouldn't be necessary to packercompile in my case I believe.
![behaviour](https://user-images.githubusercontent.com/10534713/160375031-97ec88ba-f330-4973-b344-3512d31817df.png)
On an empty file they look about the same, and the problem still presists.
![behaviour](https://user-images.githubusercontent.com/10534713/160375399-6bab0046-813c-4929-b8c8-c3b35bec9941.png)
However trying to edit an actual lua file (in this case init.lua of nvchad) the commented out version (left) does not overlay inline compared to the previously enabled event version (right)! There still appears to be an overlaying in the status-line however. But it looks promising. I also tried it with some samples of python:
![behaviour](https://user-images.githubusercontent.com/10534713/160376456-b6003bfe-3517-4a19-8fa6-3c5e717ac247.png)
The difference is quite stark! It is a nightmare to edit the file on the right. But the version with your suggested changes on the left is working completely normally asside from some ignorable overlaying in the statusline!

**Comment by DreamingRaven** [comment]
This works so well I would almost say this is a non problem now. However that still raises the question of why does it cause this overlaying when the completion is loaded?

**Comment by siduck** [comment]
ive never faced this issue, boohoo for python!! did you try other languages?

**Comment by DreamingRaven** [comment]
Yeah so far I have tried python, go, and lua for this issue. It doesnt appear to matter they all work fine. Its only when python3 is installed in the system that this issue manifests itself which is bizzare. Anyway I think this is fine for now. I will override the default config for the completion package so I can atleast have python installed for linting, debugging, and general dev of python files etc. I will close this issue for now as a solution to the original problem of overlaying the line being written has been found now atleast!
