### ISSUE TITLE
export plugins/configs/*lua of default

### ISSUE THREAD

**Issue by zaixi** [NvChad/NvChad#883]
**Is your feature request related to a problem? Please describe.**
I only want to change the default settings of some plugin. For example, statusline.lua of current_line

**Describe the solution you'd like**
The built-in configured default can be accessed externally. For example, statusline.lua  local default modify M.default

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-default-config-of-a-plugin
