### ISSUE TITLE
Strange behavior under unix screen

### ISSUE THREAD

**Issue by JSilva6** [NvChad/NvChad#884]
If opening nvhcad theme under a `screen` session in the terminal, all the colors get wildly strange. Already tried all sorts of `.screenrc` configs.

**To Reproduce**
1. Simply start `screen` on your terminal and try to open an nvim instance with nvchad configured

**Expected behavior**
No greenie color/no underline under everything

**Screenshots**
Example:
![image](https://user-images.githubusercontent.com/43544777/159038257-914eb39f-e221-423d-b6c3-8800db6e2634.png)
![image](https://user-images.githubusercontent.com/43544777/159038725-d033c127-959d-4b85-839d-54d64e0bc00a.png)
![image](https://user-images.githubusercontent.com/43544777/159038327-e37e4887-9095-40df-8b2d-ec780a0cac85.png)

Just to compare, this is what I used to see when on vim (no lua, no nvchad)
![image](https://user-images.githubusercontent.com/43544777/159038466-48e5c66f-ab9f-4b8c-ba54-fc806d4bfe8e.png)
![image](https://user-images.githubusercontent.com/43544777/159038498-101cea18-f6ec-4d1c-aabc-2acdb61c979e.png)

**Desktop (please complete the following information):**
 - MacOs 11.6.4
 - iTerm2
 - nvim 0.6.1 Release

**Comment by JSilva6** [comment]
Just to make it clear, it runs normally outside the screen container.

**Comment by siduck** [comment]
ive tried it and i get weird colors too. I think screen doesnt support guicolors (used by nvchad)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/159143581-001a0e59-068a-4dd2-8348-002d4010323a.png)
lunarvim

**Comment by siduck** [comment]
astrovim 
![image](https://user-images.githubusercontent.com/59060246/159143615-60947d20-ce32-4639-81cf-ab8b7c5451e9.png)

**Comment by siduck** [comment]
spacevim (left = normal, right = screen)

![image](https://user-images.githubusercontent.com/59060246/159143713-c360bb33-85d1-4803-b905-543afae62849.png)

**Comment by siduck** [comment]
logo-ls ( colored ls icons ) and fzf ( normal on the left, screen on the right)

![image](https://user-images.githubusercontent.com/59060246/159143736-ccfa2e5e-3d99-4fbe-b0e2-f99a1effb9d7.png)

**Comment by siduck** [comment]
so ig this is a screen issue afterall
