### ISSUE TITLE
error when setting up LSP server with LSP-installer

### ISSUE THREAD

**Issue by garrettmaring** [NvChad/NvChad#887]
I've encountered an error when following the [LSP setup instructions](https://nvchad.github.io/config/Lsp%20stuff#lsp-installer).

Since nvim-lspinstall seems deprecated I added [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) to my custom plugins.

My chadrc calls the custom plugins config for lsp per the documentations structure but after running :PackerSync I receive the following error.

```
packer.nvim: Error running config for nvim-lspconfig: [string "require('plugins.configs.lspconfig')"]:1: loop or previous error loading module 'plugins.configs.lspconfig'
```

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/159143088-2041d02a-2879-4421-b642-9bbc4b4fce87.mp4

you'll get that error only on the first packersync

**Comment by rakanzaidm** [comment]
if that error persists, remove nvim-data folder and do a reinstall of packer, i got the same error over and over even after the first packersync, but a reinstall everything is fixed, at least that's what worked for me
