### ISSUE TITLE
dashboard wont load with simple enable from chadrc after the override-able commit

### ISSUE THREAD

**Issue by rakanzaidm** [NvChad/NvChad#888]
**Describe the bug**
the alpha dashboard wont show up after that commit. i only use simple chadrc to enable it. maybe i'm just a dummy and now there's an extra step i have to do to enable this after this commit. but as someone who doesn't know anything about programming figuring it out without instruction is kind of hard, i would expect that enabling it would result in the dashboard enabled. also switching back to the old alpha.lua config works fine

**To Reproduce**
1. install the latest nvchad
2. made a custom/chadrc.lua in lua folder
3. enable alpha from it

**Expected behavior**

**Screenshots**
[imagine a good ol classic "no name" screen as if the dashboard hasn't been enabled]

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Terminal: Windows Terminal
 - Version of Neovim: Latest Stable Build, 0.6.1

**Additional context**
again maybe i just need to add some stuff to enable it after the override commit and im just a dummy please let me know if i did the setup wrong. but yeah switching the alpha.lua to before the commit fixed the issue, so is there anything i have to add from now on to use the dashboard now? also everything else works perfectly fine,  for example enabling colorizer from the chadrc works fine

**Comment by boppyt** [comment]
I was able to reproduce this issue, will propose a PR.

**Comment by rakanzaidm** [comment]
oh my god what an actual chad this is blazingly fast

**Comment by rakanzaidm** [comment]
wait am i just stoopid or is it still doesn't work for anybody else?

**Comment by boppyt** [comment]
Are you sure that you pulled the latest commit then ran PackerSync?

**Comment by rakanzaidm** [comment]
ah oops i think i just failed to update, unable to access github error i'll figure this connection thing later HAHA, but yupppp copy and pasting the code and PackerSync solved the issue!! thank you

**Comment by boppyt** [comment]
No probs, have a nice day!

**Comment by Johnsiras** [comment]
Sorry about the commit! Just wanna fix it tho, but no time for it but really sorry!
