### ISSUE TITLE
can't seem to get custom config for indent-blankline to work

### ISSUE THREAD

**Issue by rakanzaidm** [NvChad/NvChad#891]
**Describe the bug**
i tried configuring indent blankline plugin with a custom config but i can't get it to work. changing it in the others.lua manually succeed, but it's gonna get reset on update. on the other hand i also managed to use a custom config for nvimtree, and thought that it might just me being silly, i checked over and over again and i think i did it correctly(?). i tried using a config file, and tried changing the config directly in the chadrc.lua, doesn't work with indent blankline, but works with nvimtree, am i using the wrong override thingy for the plugin?

**To Reproduce**
1.  setup chadrc.lua and on the default_plugin_config_replace thingy, add indent_blankline (which i believe is the name for the override thing? like the nvim_tree)
2. and make your custom config there, or use a config folder instead
3. i tried setting up show_first_indent_level = true

**Expected behavior**
the first indent level should be lined

**Screenshots**
![image](https://user-images.githubusercontent.com/101485444/159247496-d7822b5d-110d-4bcd-98e4-b0c88c4bb2e1.png)

**Desktop (please complete the following information):**
 - Operating System Windows 11
 - Terminal Windows Terminal
 - Version of Neovim 0.6.1 latest stable release

**Additional context**
changing the config directly on lua/plugins/configs/others works, but with user config it doesn't, honestly i could just be misunderstanding things and indent_blankline isn't even the correct name, but it's the first one on the override thing on init.lua so i'm assuming it's the correct one, i'm really sorry if this is just me being silly...

**Comment by Johnsiras** [comment]
yes it is, "indent_blankline" is correct. I think it works for me

**Comment by Johnsiras** [comment]
is this are you saying?

**Comment by siduck** [comment]
did u do packercompile

**Comment by rakanzaidm** [comment]
o god im so dumb HAFSDHFASHDHHAHA yeaaa it works after packercompile!!! i thought packersync was all i needed to do because it works with nvim_tree and changing blankline directly from the others.lua... thank you for your help!!
![image](https://user-images.githubusercontent.com/101485444/159369700-a4d335fc-c5ba-4d86-b768-22885ec353ad.png)
