### ISSUE TITLE
i want use oneDarkPro

### ISSUE THREAD

**Issue by zlongCoding** [NvChad/NvChad#895]
**I want to set the theme of Nvim to oneDarkPro, what should I do? Can you give me an idea**

1. 
![github1](https://user-images.githubusercontent.com/20821148/159472321-c87bd542-9a73-40fc-bdfe-8f9ef626f8cf.jpg)

2. 
<img width="903" alt="image" src="https://user-images.githubusercontent.com/20821148/159472633-bf4bcb79-24c4-461c-abb0-8d986fc4e4b5.png">

> The first image is nvim's oneDark theme color，The second image is from oneDarkPro in vscode

Since I am used to using oneDarkPro, how should I set it up

**Comment by siduck** [comment]
make a theme for it and PR

https://nvchad.github.io/contribute#how-to-submit-themes

whats the difference between onedark and onedark pro?

**Comment by siduck** [comment]
the default theme in nvchad is onedark and ig onedark is called as onedark pro in vscode ._.

**Comment by zlongCoding** [comment]
Ok, I'll look into it

**Comment by siduck** [comment]
yes onedark = onedark Pro so we already have that theme
