### ISSUE TITLE
how use `Alt` or `Option` key of mappings

### ISSUE THREAD

**Issue by nshusr** [NvChad/NvChad#897]
my config resize window not work, Terminal is iTerm2
``` lua
-- window
map("n", "<a-k>", ":res +1 <CR>")
map("n", "<A-j>", ":res -1 <CR>")
map("n", "<A-h>", ":vertical resize-1 <CR>")
map("n", "<A-l>", ":vertical resize+1 <CR>")
```

**Comment by boppyt** [comment]
`A-` should work just fine.

Have you tried running the command on its own?

**Comment by nshusr** [comment]
treid ok command, bind mapping not work, 
I found that `A-` was not used in nvchad's built-in binding shortcuts.

**Comment by boppyt** [comment]
`M-` is what `A-` gets converted into, if I recall correctly.

have you tried checking that there isn't any conflict between keymaps? (`:nmap`)

**Comment by nshusr** [comment]
ohhhhhh  😄 

![image](https://user-images.githubusercontent.com/45023042/159646447-f005255c-c590-4a33-a0f1-4eca056d4ad2.png)

No other keys conflict with it

But it still doesn't work properly, and there is no response after pressing the key.

**Comment by siduck** [comment]
res +1 / -1 in command mode itself didnt work for me

**Comment by nshusr** [comment]
I running :res +1 video
<video src="https://user-images.githubusercontent.com/45023042/159657377-362d2184-1263-4c35-9d4d-431a859605d1.mov">

**Comment by boppyt** [comment]
does `:nnoremap <A-k> :res +1<cr>` work?

**Comment by nshusr** [comment]
not work 😩 

> does `:nnoremap <A-k> :res +1<cr>` work?

**Comment by boppyt** [comment]
Seems to work perfectly fine here.

**Comment by nshusr** [comment]
> Seems to work perfectly fine here.

Your terminal app is Iterm2 or other

**Comment by boppyt** [comment]
Not iTerm2, though I believe it shouldn't really matter.

does it work on `nvim --clean`?

**Comment by nshusr** [comment]
no work on `nvim --clean`

> Not iTerm2, though I believe it shouldn't really matter. does it work on `nvim --clean`?
> […](#)
> On 22/03/23 02:59AM, Rea wrote: > Seems to work perfectly fine here. Your terminal app is Iterm2 or other -- Reply to this email directly or view it on GitHub: [#897 (comment)](https://github.com/NvChad/NvChad/issues/897#issuecomment-1076173408) You are receiving this because you commented. Message ID: ***@***.***>

**Comment by siduck** [comment]
@nshusr A key didnt work for me but this works 

```
map("n", "<leader>j", ":res -3<CR>")
map("n", "<leader>k", ":res +3<CR>")

map("n", "<leader>h", ":vertical resize-3<CR>")
map("n", "<leader>l", ":vertical resize+3<CR>")
```

**Comment by boppyt** [comment]
Sounds like a local problem to me. Does it work on terms other than
iterm2?
supplying --clean should give you the near-plain neovim environment,
where this *should* work just fine.

**Comment by nshusr** [comment]
> @nshusr A key didnt work for me but this works
> 
> ```
> map("n", "<leader>j", ":res -3<CR>")
> map("n", "<leader>k", ":res +3<CR>")
> 
> map("n", "<leader>h", ":vertical resize-3<CR>")
> map("n", "<leader>l", ":vertical resize+3<CR>")
> ```
This is also an additional option, but am I the only one who can't use the `A` key?

@boppyt Both Terminal.app and iTerm2 do not work when the mapping I set uses the A key

`Nvim --clean` tested the Alt key is also invalid

**Comment by siduck** [comment]
I cant use A either

**Comment by siduck** [comment]
maybe cuz A is already mapped, i think its used for entering insertmode

**Comment by boppyt** [comment]
On second thought, it may be because Option isn't really Alt.
I recall that there should be some option to send the Meta(alt) on
option keypress in iTerm2, can you check it out?

**Comment by Johnsiras** [comment]
`A` works fine for me, maybe it's just a terminal meta kbd?

**Comment by nshusr** [comment]
default Option + `a-z` input symbol 

my last config use `A-Arrow`
``` lua
-- window
map("n", "<A-Up>", ":res +1 <CR>")
map("n", "<A-Down>", ":res -1 <CR>")
map("n", "<A-Left>", ":vertical resize-1 <CR>")
map("n", "<A-Right>", ":vertical resize+1 <CR>")
```

In addition, this seems to be a solution, but I haven't tested it yet and it doesn't seem to be recommended.

https://stackoverflow.com/questions/7501092/can-i-map-alt-key-in-vim

**Comment by nshusr** [comment]
Ohhhhh

iTerm2 config set disable Option Input Symbol to solve this problem.
![image](https://user-images.githubusercontent.com/45023042/160590018-eb43d30e-888e-4550-bbdd-72d2113dd2f3.png)
