### ISSUE TITLE
can't configure Shatur/neovim-session-manager plugin

### ISSUE THREAD

**Issue by rakanzaidm** [NvChad/NvChad#900]
**Describe the bug**
as someone who doesn't understand basically any programming, this might just me messing up so might not be a bug at all. after some success installing some plugins via the plugin file specified in chadrc following the guides, i tried to install this plugin called neovim session manager, if it's just a plain install, there is no problem at all, but when i try to configure the setup from that file, my chadrc become irrelevant and not being read by nvim, as if i have nothing on there, so i think it's probably messing up the format and make the chadrc fail to combine with the nvchad defaults and such? i tried installing and configuring telescope extensions plugins and no problem, and again plain installations seem to work just fine. and more importantly, i just tried to follow the plugin page and nvchad documentation, and this could totally be just me not knowing how to install plugins correctly, and if that's the case could someone tell me the right way to set this up :')

**To Reproduce**
1. on the plugin file specified in your chadrc, install neovim-session-manager
2. configure autoload_mode to disabled by requiring its setup (with config = function() too?), what i did is there on the screenshot

**Expected behavior**
neovim session manager installed and working properly, without autoloading the last saved session on startup

**Screenshots**
![image](https://user-images.githubusercontent.com/101485444/159842760-17cf3d27-f58b-4d2e-a882-6492bb4b4ce4.png)

**Desktop (please complete the following information):**
 - Operating System Windows 11
 - Terminal Windows Terminal
 - Version of Neovim 0.6.1 latest stable release

**Additional context**
oh and i also did packersync and packercompile properly this time HAHA, but when i try to do packersync after this setup, it just asked me to uninstall all my custom plugins, including alpha and colorizer that i enabled in chadrc, so yeah as if my chadrc is not even there. thank you so much in advance and sorry for all the issue report...

oh also here's the plugin: https://github.com/Shatur/neovim-session-manager

**Comment by siduck** [comment]
show me your whole custom dir

**Comment by rakanzaidm** [comment]
here it is https://github.com/rakanzaidm/custom

(i also commented the neovim session manager so i can still use neovim for now, it's in custom/plugins/plug)

**Comment by rakanzaidm** [comment]
so uhhh.... yeah it was my fault after cleaning my custom file and setting it up properly again it just works... thank you and sorry for the inconvenience...
