### ISSUE TITLE
clang-format is not triggered anymore

### ISSUE THREAD

**Issue by chebro** [NvChad/NvChad#902]
**steps to reproduce**

1. create a new cpp file with some boilerplate code.
2. run `:lua vim.lsp.buf.formatting()`

**expected behavior**
formatting should work as expected, but nothing happens.

**desktop**
 - os: archlinux
 - term: kitty
 - nvim: v0.6.1

**additional context**
from a discussion in the discord support channel it looks like the bug was introduced in this commit https://github.com/NvChad/NvChad/commit/ef6ecab861cee3e5ec25d32b328d6ef654860384

**Comment by siduck** [comment]
add clang_format in your null ls config, its a builtin formatter in it

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/159930030-a142391a-d1d3-43ab-b6e6-f2e71e063897.png)

**Comment by siduck** [comment]
or 
 ```
    lspconfig.clangd.setup {
      on_attach = function(client, _)
         client.resolved_capabilities.document_formatting = false
         client.resolved_capabilities.document_range_formatting = false
                  vim.api.nvim_buf_set_keymap(bufnr, "n", "<space>fm", "<cmd>lua vim.lsp.buf.formatting()<CR>", {})

      end,
   }
   ```

**Comment by rtunazzz** [comment]
> add clang_format in your null ls config, its a builtin formatter in it

Hey there, appreciate you looking into this for us! :goat:

I'm currently having the same exact issue with `gopls` in golang files. I'm assuming the solution for golang would be to install [golangci_lint](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#golangci_lint) and use that instead?

Is there any way to use the native, `gopls` formatter? I tried using the snippet you shared in your [most recent comment](https://github.com/NvChad/NvChad/issues/902#issuecomment-1077648274) but that did not work for me.
```lua
   lspconfig.gopls.setup {
     on_attach = function(client, _)
        client.resolved_capabilities.document_formatting = false
        client.resolved_capabilities.document_range_formatting = false
     end,
  }
```

The only way I got it working was essentially reverting the [original commit (`ef6ecab`)](https://github.com/NvChad/NvChad/commit/ef6ecab861cee3e5ec25d32b328d6ef654860384) which broke the formatting for me but for obvious reasons that solution isn't ideal.

Thanks!

**Comment by siduck** [comment]
@rtunazzz my bad! it set it as true not false (the client.resolved.... stuff)

**Comment by rtunazzz** [comment]
> @rtunazzz my bad! set it as true not false (the client.resolved.... stuff)

Setting it to `true` still did not fix the issue for me but I think that was just because you forgot to call the `attach` func. I added it and it worked! Here's the updated snippet that worked for me (for anyone that may stumble across this issue in the future)
```lua
   lspconfig.gopls.setup {
     on_attach = function(client, _)
        attach(client)

        client.resolved_capabilities.document_formatting = true
        client.resolved_capabilities.document_range_formatting = true
     end,
   }
```
