### ISSUE TITLE
Telescope stops working after first use in each session

### ISSUE THREAD

**Issue by guillegalor** [NvChad/NvChad#903]
**Describe the bug:**
I have just started to use NvChad. In every nvim session, the first execution of `:Telescope <whatever>` works perfectly. but after that execution, no matter if I cancelled it or actually select a file, :Telescope stops being a command of the editor, rising this error message if I try to use it. 
```
E492: Not an editor command: Telescope
```

In this moment, nvim also doesn't autocomplete if I type :Teles and hit tab unlike usual. 

**Things I have tried:**
* Deleting the whole .config/nvim folder and installing NvChad as indicated again.
* Deleting the folder where packer stores Telescope plugin, `.local/share/nvim/site/pack/packer/opt/telescope.nvim`, and reinstalling the pluging with Packer. 
* :PackerSync and PackerStatus show no error message, it seems everything is ok, both while working and after executing Telescope one time and stops working.

I tried to replicate this on the docker image, but it works fine there.

**Configuration:**
    I have only a few mappings in `.config/nvim/lua/custom/init.lua` and a few things in `.config/nvim/lua/custom/chadrc.lua`, but the error persist after a clean install with nothing on this folder

**Desktop :**

    Operating System: Ubuntu 20.04.4 LTS
    Terminal: Kitty.
    Version of Neovim: tried v0.6.1and v0.7
    
Since I haven't been able to replicate this in the docker image, I think I'm asking for some guideness to identificate the problem and what could be causing it.

Thank you so much in advance, feel free to ask for any kind of information about my configuration if I missed something.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/159952107-6f7ff924-c68c-4cd4-87ce-8c558162b06d.mp4

works fine here

**Comment by Johnsiras** [comment]
Btw telescope stops working on :PackerCompile too!

**Comment by guillegalor** [comment]
I found the problem, there was incompatibilities with my previous configuration of neovim.

Since I was using Paq, all the plugins installed in .local/share/nvim/site/pack/paq/ were still present there, which was causing the bug.

Thank you very much anyway.
