### ISSUE TITLE
How do I fix the sidebar width

### ISSUE THREAD

**Issue by zlongCoding** [NvChad/NvChad#904]
each time I switch to the panel, this will cause the nvImTree span to change. Is there any way I can fix the width

this is a GIF generated by my editor
![1](https://user-images.githubusercontent.com/20821148/160076802-bb6e7618-b0e6-4d19-a51e-3cfdf0c6578e.gif)

**Comment by siduck** [comment]
is this nvim 0.7

**Comment by zlongCoding** [comment]
> is this nvim 0.7

yes ， my nvim version is 
> NVIM v0.7.0-dev+1274-gc1b98cfa5

**Comment by siduck** [comment]
> > is this nvim 0.7
> 
> yes ， my nvim version is
> 
> > NVIM v0.7.0-dev+1274-gc1b98cfa5

oh use 0.6.1 only

**Comment by zlongCoding** [comment]
> > > is this nvim 0.7
> > 
> > 
> > yes ， my nvim version is
> > > NVIM v0.7.0-dev+1274-gc1b98cfa5
> 
> oh use 0.6.1 only

ok,  thanks
