### ISSUE TITLE
"New File" button in alpha dashboard

### ISSUE THREAD

**Issue by neevek** [NvChad/NvChad#912]
**Is your feature request related to a problem? Please describe.**

Not a problem, just a feature enabling users to easily start editing a new file from dashboard.

**Describe the solution you'd like**

Add a "New File" button in the dashboard, and an `e` shortcut to start editing a new file.
Also there's another issue that may be related to this one, when toggling on `nvim-tree` and open a new file from `nvim-tree` while the dashboard is visible, dashboard is not closed, but I think it should be closed in those cases.

**Comment by siduck** [comment]
thats the default behaviour, dashboard is a buffer too i think so nvimtree treats it like that.

**Comment by siduck** [comment]
you can override the default config of dashboard and add your new file button
