### ISSUE TITLE
nvim-cmp suggests buffer related words after typing just 1 letter

### ISSUE THREAD

**Issue by primeapple** [NvChad/NvChad#913]
**Describe the bug**
When in insert mode in a buffer, after typing a single letter `nvim-cmp` already shows suggestions.
It ignores custom config.

**To Reproduce**
1. Open a file with nvim, for example the `init.lua` at the root of this project
2. In a new line, type a single letter, for example `p`
3. `nvim-cmp` already shows suggestions (for me it is `p~` [snippet, which is fine], `pcall`, `plugin`, `present`, ... [which are all from the buffer])

**Expected behavior**
I would like to enable buffer autocompletion just after typing 5 letters. The default is 3 (see https://github.com/hrsh7th/cmp-buffer#keyword_length-type-number).
However I can't do this, even after overwriting the cmp config.

**Screenshots**

**Desktop (please complete the following information):**
- Macos
- Kitty
- nvim 0.61

**Additional context**
The relevant `chadrc.lua`:
```lua
local cmpConfig = require("custom.plugins.cmp")
M.plugins = {
    default_plugin_config_replace = {
        nvim_cmp = cmpConfig,
    }
}
```

`lua/custom/plugins/cmp.lua`:
```lua
return {
   sources = {
      { name = "nvim_lsp" },
      { name = "luasnip" },
      {
          name = "buffer",
          option = {
              keyword_length = 5
          }
      },
      { name = "nvim_lua" },
      { name = "path" },
   },
}
```

**Comment by siduck** [comment]
did u do packercompile

**Comment by primeapple** [comment]
Yes, did it. Also as I mentioned the default value by `nvim-buffer` is `3` so it shouldn't show anything for less letters by default.

**Comment by hrsh7th** [comment]
@primeapple Sorry. It seems to be my design mistake.

The `cmp-buffer`'s keyword-length option is to be used to gather words from buffer. To not be used to `completion trigger`.

You should specify the following (it's nvim-cmp's core setting)


_correct_
```
cmp.setup {
  sources = {
    { name = 'buffer', keyword_length = 5 }
  }
}
```

_wrong_
```
cmp.setup {
  sources = {
    { name = 'buffer', option = { keyword_length = 5 } }
  }
```
}

**Comment by primeapple** [comment]
@hrsh7th , wow this solves the issue! Thank you so much!
Maybe it would be good to add this information to the readme as well :)
