### ISSUE TITLE
Option to enable netrw

### ISSUE THREAD

**Issue by codeasashu** [NvChad/NvChad#914]
**Is your feature request related to a problem? Please describe.**
Yes. I am using [vim-fugitive](https://github.com/tpope/vim-fugitive) and I need to have `netrw` enabled in order to use `:GBrowse` command. I am unable to do so as `:netrw` is disabled by default in this setup 

**Describe the solution you'd like**
I would like to override `disabled_built_ins` from `custom/`. I am unable to understand how can I do so using `M.`

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Screenshot**
Maybe a screenshot of the feature

**Comment by beune** [comment]
Related: #919

**Comment by codeasashu** [comment]
@siduck Can you please also add into documentation how to do so? I am still unclear about implementing this

**Comment by codeasashu** [comment]
@siduck No worries, I've now this in my chadrc.lua and its working perfectly.

```lua
local M = {}
M.plugins = {
  builtins = {
      "2html_plugin",
      "getscript",
      "getscriptPlugin",
      "gzip",
      "logipat",
      -- "netrw",
      "netrwPlugin",
      "netrwSettings",
      "netrwFileHandlers",
      "matchit",
      "tar",
      "tarPlugin",
      "rrhelper",
      "spellfile_plugin",
      "vimball",
      "vimballPlugin",
      "zip",
      "zipPlugin",
   }
}

return M
```

Thank you for amazing work 👍

**Comment by stephancb** [comment]
The solution does not work anymore with the latest Nvchad 2.5.

**Comment by siduck** [comment]
> The solution does not work anymore with the latest Nvchad 2.5.

for v2.5 you have direct access to lazy config, just uncomment netrw stuff in it?
