### ISSUE TITLE
nvchad incompatible with laststatus=3

### ISSUE THREAD

**Issue by jsholmes** [NvChad/NvChad#916]
require("core.utils").hide_statusline() sets it back to 2, so global statusline doesn't work

**Comment by bryant-the-coder** [comment]
globalstatusline is for nightly not stable version

**Comment by siduck** [comment]
yes wait until 0.7 gets stable then i'll add this myself.We currently support only 0.6.1

**Comment by bryant-the-coder** [comment]
@siduck we should have a 0.7 branch :P

**Comment by siduck** [comment]
not yet @bryant-the-coder

**Comment by bryant-the-coder** [comment]
y?

**Comment by siduck** [comment]
> y?

Let 0.7.1 get stable first I.e it's the stable release isn't released yet
