### ISSUE TITLE
Theme request: Papercolor or Gruvbox light

### ISSUE THREAD

**Issue by martisj** [NvChad/NvChad#918]
**Is your feature request related to a problem? Please describe.**
Would love a light theme like PaperColor or Gruvbox light. It's easier to work in sunny conditions with a light theme.

**Describe the solution you'd like**
https://github.com/NLKNguyen/papercolor-theme

**Describe alternatives you've considered**
I tried to use the themes as external themes but I don't think all the plugins are supported by these themes? 🤷‍♂️

**Comment by siduck** [comment]
@martisj theme requests will go in the base16 repo
