### ISSUE TITLE
Why does NvChad disable zip support? 

### ISSUE THREAD

**Issue by beune** [NvChad/NvChad#919]
I want to view zip files in neovim. However, NvChad disables this support in `lua/core/options.lua`, around line 71. How do you re-enable zip support?

**Comment by siduck** [comment]
cuz no one uses it, you can enable it via chadrc now

**Comment by beune** [comment]
> cuz no one uses it, you can enable it via chadrc now

How does one do this?

**Comment by siduck** [comment]
> > cuz no one uses it, you can enable it via chadrc now
> 
> How does one do this?

check the commit ._.

**Comment by EricDuminil** [comment]
For reference, the disabled plugins are now in `lua/plugins/configs/lazy_nvim.lua`

**Comment by EricDuminil** [comment]
Sorry, I don't understand how I could enable tarPlugin or gzip plugins again, since I often have to see the content of tar.gz files.

Should I somehow override `M.lazy_nvim.performance.rtp.disabled_plugins`? If so, I couldn't find any place to do so in custom/ folder.

Or should I simply enable the plugins manually? If so, I don't know how either.


Thanks for the excellent work!

**Comment by siduck** [comment]
> Sorry, I don't understand how I could enable tarPlugin or gzip plugins again, since I often have to see the content of tar.gz files.
> 
> Should I somehow override `M.lazy_nvim.performance.rtp.disabled_plugins`? If so, I couldn't find any place to do so in custom/ folder.
> 
> Or should I simply enable the plugins manually? If so, I don't know how either.
> 
> Thanks for the excellent work!

@EricDuminil please check core/default_config... the lazy_nvim field expects a table same as the default lazy config we have

**Comment by EricDuminil** [comment]
Got it, thanks!

For reference, I added this block to `nvim/lua/custom/chadrc.lua`:

```
M.lazy_nvim = {
  performance = {
    rtp = {
      -- Comment plugins that you want to leave enabled:
      disabled_plugins = {
        "2html_plugin",
        "tohtml",
        "getscript",
        "getscriptPlugin",
        -- "gzip",
        "logipat",
        "netrw",
        "netrwPlugin",
        "netrwSettings",
        "netrwFileHandlers",
        "matchit",
        -- "tar",
        -- "tarPlugin",
        "rrhelper",
        "spellfile_plugin",
        "vimball",
        "vimballPlugin",
        -- "zip",
        -- "zipPlugin",
        "tutor",
        "rplugin",
        "syntax",
        "synmenu",
        "optwin",
        "compiler",
        "bugreport",
        "ftplugin",
        "editorconfig",
      }
    }
  }
}
```
It disables most plugins, but leaves gzip/tar/zip enabled.
