### ISSUE TITLE
Unable to override any plugin configurations using chadrc

### ISSUE THREAD

**Issue by evprkr** [NvChad/NvChad#923]
EDIT: I'm realizing now that I can't override ANY plugins. I have been trying to override some settings in bufferline (seen in my chadrc linked below) and those are not working either. What is going on?

I'm trying to configure nvim_cmp so when I press enter, it will only insert a snippet that I have EXPLICITLY highlighted, rather than the default behavior to just insert whatever the first result is without asking. I realized after updating that changing the config in `/plugins/configs/cmp.lua` gets overwritten.

Here is my [custom/init.lua](https://gist.github.com/evprkr/030528c3a983f57625eceff0a74e246f) and my [custom/chadrc.lua](https://gist.github.com/evprkr/eaff10f91d8199b04cdcbd883c3fe48b)

I followed the instructions on the wiki to override the setting that's in the setup for nvim_cmp, specifically the mapping for `<CR>`, which I found on the github page for that plugin. I tried naming this table `nvim_cmp` and just `cmp` and neither worked. I also tried overriding the entire config using the instructions on the wiki, and that didn't work either.

My example of how this setting affects me:
If I go into a new file, enter insert mode, type `# main.py` and press `enter`, it inserts a whole bunch of crap about "property", all I want is a line break.

**Comment by evprkr** [comment]
Something about this whole 'custom' config system is super broken, I can't even disable a plugin using the exact method on the wiki on a fresh install of NvChad, so I'm nuking this and doing a custom setup. Sorry, I tried. It's been two days and I can't get this to work.

**Comment by siduck** [comment]
did you do packercompile?

**Comment by siduck** [comment]
Let me show you how to disable a plugin :angry:

**Comment by evprkr** [comment]
Yes, I did run PackerCompile, and PackerSync. Nothing seems to work.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/161299233-e6b4fe29-9b29-4460-80ee-e9f73906f0e6.mp4 

demo to disable blankline

**Comment by siduck** [comment]
just make sure that you write correct variable name and make sure your chadrc isnt broken

**Comment by evprkr** [comment]
> simplescreenrecorder-2022-04-01_21.23.01.mp4 
> demo to disable blankline

This is *not at all* what it says to do on the wiki, that needs to be updated asap. Here is the example from the wiki: 

```
M.plugins = {
   default_plugin_remove = {
       "akinsho/bufferline.nvim",
       "norcalli/nvim-colorizer.lua",
       "neovim/nvim-lspconfig",
   },
}
```

Which does not work. I assume this is also why my configs for bufferline aren't working, because the example on the wiki is wrong and it should be done a different way. Please consider updating the wiki so new users like me don't spend two days screwing around with this only to find out the documentation was never accurate.

**Comment by siduck** [comment]
There's a difference between disabling and removing a plugin. the default_plugin_remove removes the plugin's table inside the whole plugin list table + removes plugin locally . Disabling a plugin i.e with the status table just removes plugin locally

**Comment by evprkr** [comment]
Disabling should be added to the wiki then, I think. Either way, removing it should have worked still, but it didn't for some reason.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/161304759-fb84d373-89f2-4918-ad56-139947b15010.mp4

removing plugin works here

**Comment by siduck** [comment]
the examples in wiki isnt wrong at all :/

**Comment by siduck** [comment]
overriding bufferline

https://user-images.githubusercontent.com/59060246/161305172-c25ef872-3cd2-4668-8865-23f3c0e47f0a.mp4

**Comment by evprkr** [comment]
Closing this as I've moved on to using stock Neovim with plugins installed and configured manually, so as to have a better understanding for what is actually going on.

**Comment by siduck** [comment]
if this file doesnt exist https://gist.github.com/evprkr/eaff10f91d8199b04cdcbd883c3fe48b#file-chadrc-lua-L2 , none of your chadrc changes might not work
