### ISSUE TITLE
If i open nvim-tree ,then `space+v` ,will open two new  windows

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#924]
**Describe the bug**
If i open nvim-tree ,then `space+v` ,will open two new  windows

**To Reproduce**
1. nvim some.lua
2. ctrl+n
3. edit some.lua
4. `space+v`

**Expected behavior**
should open only one new  window

**Screenshots**

**Desktop (please complete the following information):**
 -  ubuntu
 - Terminal
 - nvim-0.7

**Additional context**

**Comment by siduck** [comment]
yea agreed i get this issue too 
![image](https://user-images.githubusercontent.com/59060246/161196994-06472653-3c56-4f1c-8c84-0d5d59cdc6d3.png)

but this has been there before the new implementation of the terminal toggling

**Comment by siduck** [comment]
it should be fixed
