### ISSUE TITLE
Issues with new implementation of terminal toggling 

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#925]
@zbirenbaum 

## 1 

- Terminals opened on right/bottom i.e like split windows are listed in the bufferline 

![image](https://user-images.githubusercontent.com/59060246/161195687-c0036815-1187-4e0f-a747-eb49aadb74c2.png)

Old behaviour : they werent listed in the bufferline , nobufflisted stuff

**Comment by zbirenbaum** [comment]
> @zbirenbaum 
> 
> 
> 
> 1. terminals opened on right/bottom i.e like split windows are listed in the bufferline 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/59060246/161195687-c0036815-1187-4e0f-a747-eb49aadb74c2.png)
> 
> 
> 
> Old behaviour : they werent listed in the bufferline , nobufflisted stuff 

Ahh I think that's related to my fix for the telescope thing, didn't notice cuz I don't use buffer line. I'll take a look at it, thanks for letting me know.

**Comment by siduck** [comment]
# 2

We can no longer spawn multiple terminals :c  

## Steps to reproduce 

- Press leader+v 2 times
- Old behaviour would spawn 2 vertical terminals but now it just minimizes the terminal buffer i.e pressing leader +v again will not show the terminal buffer but it will show it in the bufferline 

https://user-images.githubusercontent.com/59060246/161196111-39216c60-31d3-436e-9e9d-d6fd656647f8.mp4

Expected behaviour : leader + v / x should spawn multiple terminals rather than toggling

@zbirenbaum

**Comment by siduck** [comment]
# 3 

Horizontal terminal eats up the area of nvimtree too, this shouldnt be happening 

![image](https://user-images.githubusercontent.com/59060246/161196523-baeb00e4-30ed-4743-b85e-f06bb9a73cb8.png)

**Comment by zbirenbaum** [comment]
> # 2
> 
> 
> 
> We can no longer spawn multiple terminals :c  
> 
> 
> 
> ## Steps to reproduce 
> 
> 
> 
> - Press leader+v 2 times
> 
> - Old behaviour would spawn 2 vertical terminals but now it just minimizes the terminal buffer i.e pressing leader +v again will not show the terminal buffer but it will show it in the bufferline 
> 
> 
> 
> https://user-images.githubusercontent.com/59060246/161196111-39216c60-31d3-436e-9e9d-d6fd656647f8.mp4
> 
> 
> 
> Expected behaviour : leader + v / x should spawn multiple terminals rather than toggling
> 
> 
> 
> @zbirenbaum 
> 
> 
> 
> 

How do you propose we show the terminal after it is hidden? That was the whole point of this feature, to not have to manually select it. 

If you want a second horizontal term do ctrl-w h and :Term

**Comment by siduck** [comment]
> > # 2
> > We can no longer spawn multiple terminals :c
> > ## Steps to reproduce
> > 
> > * Press leader+v 2 times
> > * Old behaviour would spawn 2 vertical terminals but now it just minimizes the terminal buffer i.e pressing leader +v again will not show the terminal buffer but it will show it in the bufferline
> > 
> > 
> >   
> >     
> >     
> > 
> >     simplescreenrecorder-2022-04-01_10.06.52.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > Expected behaviour : leader + v / x should spawn multiple terminals rather than toggling
> > @zbirenbaum
> 
> How do you propose we show the terminal after it is hidden? That was the whole point of this feature, to not have to manually select it.
> 
> If you want a second horizontal term do ctrl-w h and :Term

I didnt that the old feature of spawning multiple terminals would be the cost for this

**Comment by siduck** [comment]
ctrl w s works, what about vertical ones?

**Comment by zbirenbaum** [comment]
>  ctrl w s works, what about vertical ones?

Ctrl w v

**Comment by zbirenbaum** [comment]
> > > ctrl w s works, what about vertical ones?
> 
> > 
> 
> > Ctrl w v. Since that's really uncommon behavior I think having the user do ctrl w s/v and :Term is reasonable, as toggling on and off is way more common.
> 
> > 
> 
> > Any other way would need different hotkeys for showing and hiding, which would just pollute the mappings and render the plugin nearly pointless. If you really want it, I can implement it for you to use, but I have to insist that I think it's best the current behavior stays as the default.
> 
> 
> 
> current behaviour is fine and will be the default one, btw how do i map Ctrl w s :term? :thinking: 

Are you on nightly or .6

**Comment by siduck** [comment]
> > > > ctrl w s works, what about vertical ones?
> > 
> > 
> > > 
> > 
> > 
> > > Ctrl w v. Since that's really uncommon behavior I think having the user do ctrl w s/v and :Term is reasonable, as toggling on and off is way more common.
> > 
> > 
> > > 
> > 
> > 
> > > Any other way would need different hotkeys for showing and hiding, which would just pollute the mappings and render the plugin nearly pointless. If you really want it, I can implement it for you to use, but I have to insist that I think it's best the current behavior stays as the default.
> > 
> > 
> > current behaviour is fine and will be the default one, btw how do i map Ctrl w s :term? thinking
> 
> Are you on nightly or .6

.6 , 

      map("n", "<leader>H", " what to add here <CR>")

**Comment by zbirenbaum** [comment]
This works for me:
```
vim.api.nvim_set_keymap("n", "<leader>h", "<CMD>:split<CR><CMD>:term<CR><CMD>:startinsert<CR>", {noremap = true, silent = true})
```
, so in .6 you would just put 
```"<CMD>:split<CR><CMD>:term<CR><CMD>:startinsert<CR>"``` at the location you indicated.

If you don't want to go into insert mode when the terminal opens, just take out the start insert part. If you want to be able to open another term from inside the term, set the same mapping for "t" instead of "n"

You will need to override the terminal hotkey from mappings, which didn't happen properly from chadrc until I put it inside this:

```
vim.api.nvim_create_autocmd({"VimEnter"}, {
   callback = function ()
      require "custom.utils.hot_reload"
      require "custom.utils.mappings".navigation()
      vim.api.nvim_set_keymap("n", "<leader>h", "<CMD>:split<CR><CMD>:term<CR><CMD>:startinsert<CR>", {noremap = true, silent = true})
      vim.api.nvim_set_keymap("n", "<leader>h", "<CMD>:split<CR><CMD>:term<CR><CMD>:startinsert<CR>", {noremap = true, silent = true})
   end,
   once = true,
})
```
But nvim_create_autocmd is a .7 feature. Make sure you set it somewhere loaded late into the loading process and it'll be fine.

**Comment by siduck** [comment]
@zbirenbaum 
![image](https://user-images.githubusercontent.com/59060246/161200075-af87722c-f457-4cc7-9cd6-49ef8d7c6728.png)

what about the vertical one?

**Comment by Johnsiras** [comment]
> # 2
> We can no longer spawn multiple terminals :c
> 
> ## Steps to reproduce
> * Press leader+v 2 times
> * Old behaviour would spawn 2 vertical terminals but now it just minimizes the terminal buffer i.e pressing leader +v again will not show the terminal buffer but it will show it in the bufferline
> 
>  simplescreenrecorder-2022-04-01_10.06.52.mp4 
> Expected behaviour : leader + v / x should spawn multiple terminals rather than toggling
> 
> @zbirenbaum

My problem is i can't spawn a terminal now doing `<leader> w/<leader> v/<leader> h` doesn't do anything instead it uses the default `w` mapping

![image](https://user-images.githubusercontent.com/102006493/161200473-eb533193-2738-4d87-9ef8-15c5a0445c0f.png)

**Comment by siduck** [comment]
@JoakoV3 packersync!!!!!!!!!!!

**Comment by Johnsiras** [comment]
> @JoakoV3 leader uu and packersync!!!!!!!!!!!

Works now still, `<leader> w` doesn't work. Is it mapping problem?

**Comment by siduck** [comment]
wym doesnt work, show the error

**Comment by Johnsiras** [comment]
> wym doesnt work, show the error

There's no error instead it doesn't open a new terminal buffer
![wezterm-gui_jJAniEfBDw](https://user-images.githubusercontent.com/102006493/161201517-be0fd95e-bc0a-445f-aa2c-85d4aa628138.gif)

**Comment by siduck** [comment]
ohh that, i misread. I'll add the mapping for this now

**Comment by siduck** [comment]
@zbirenbaum is it possible to add a toggleable floating terminal  ?
```
      map("n", "<leader>ft", ":execute 'PackerStatus' | term <CR>")

```

![image](https://user-images.githubusercontent.com/59060246/161201778-aa47a265-d0b2-42db-9ca3-889080a18e0b.png)


idk how to close this tho

**Comment by zbirenbaum** [comment]
> @zbirenbaum is it possible to add a toggleable floating terminal ?
> 
> ```
>       map("n", "<leader>ft", ":execute 'PackerStatus' | term <CR>")
> ```
> 
> ![image](https://user-images.githubusercontent.com/59060246/161201778-aa47a265-d0b2-42db-9ca3-889080a18e0b.png)
> 
> idk how to close this tho

Yeah its definitely possible. 

So, the current list of changes is:
1. Do not list terms in the bufferline
2. Do not overlap nvimtree with horizontal term
3. Make hide and new callable outside of the terminal plugin
4. Add floating terminals

I am extremely busy at the moment with school work, but I think I can do 1 and 2 in the next day or two.

I have some ideas on a good way of doing 3 using some stuff I learned about recently, but it may require a lot of refactoring, although I think the end result will be more extensible. 

4 could probably be done fairly simply, but I'd rather wait until after the changes of 3 so that it doesn't just add more code for me to refactor.

**Comment by siduck** [comment]
no rush, take your own time

**Comment by zbirenbaum** [comment]
@siduck 1 & 2 have been addressed NvChad/extensions#11 #927

**Comment by siduck** [comment]
> @siduck 1 & 2 have been addressed [NvChad/extensions#11](https://github.com/NvChad/extensions/pull/11) #927
> 
> I know I _could_ technically merge this in myself now but I'd prefer for someone else to test it on .6 first. Sorry about making extra work for you laughing

works good!

**Comment by siduck** [comment]
### 4

Unable to unhide terminal buffers that were opened with leader + H or leader + V ( old implementation mappings) 

![image](https://user-images.githubusercontent.com/59060246/161376339-eac09b73-8824-4e1e-a7b7-6783a5de7a2b.png)

**Comment by zbirenbaum** [comment]
> ### 4
> 
> 
> 
> Unable to unhide terminal buffers that were opened with leader + H or leader + V ( old implementation mappings) 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/59060246/161376339-eac09b73-8824-4e1e-a7b7-6783a5de7a2b.png)
> 
> 

Hmm are you talking about terminals opened with the ctrl w s :term mapping?

**Comment by siduck** [comment]
> > ### 4
> > Unable to unhide terminal buffers that were opened with leader + H or leader + V ( old implementation mappings)
> > ![image](https://user-images.githubusercontent.com/59060246/161376339-eac09b73-8824-4e1e-a7b7-6783a5de7a2b.png)
> 
> Hmm are you talking about terminals opened with the ctrl w s :term mapping?

yes ig https://github.com/NvChad/NvChad/blob/main/lua/core/mappings.lua#L120

**Comment by bryant-the-coder** [comment]
how are you going to make the terminal being hidden from bufferline and make it float?

**Comment by zbirenbaum** [comment]
> > > ### 4
> 
> > > Unable to unhide terminal buffers that were opened with leader + H or leader + V ( old implementation mappings)
> 
> > > ![image](https://user-images.githubusercontent.com/59060246/161376339-eac09b73-8824-4e1e-a7b7-6783a5de7a2b.png)
> 
> > 
> 
> > Hmm are you talking about terminals opened with the ctrl w s :term mapping?
> 
> 
> 
> yes ig https://github.com/NvChad/NvChad/blob/main/lua/core/mappings.lua#L120

You can try binding leader h to the plugins "new" function. I may need to add another table and checks for showing and hiding to work with multiple terminals in the same direction though.

If you don't open a terminal though the plugin it can't track it.

**Comment by zbirenbaum** [comment]
> how are you going to make the terminal being hidden from bufferline and make it float?

Floats are done the same way as I currently create the terminals except with a call to nvim_open_win instead of splitting and using the new window. All you have to do is set the window's buffer to be the terminal you create.

I already fixed the terminals being listed in buffer line for the normal split ones. Since listing is controlled by buffers, and not windows, opening it in a float shouldn't affect bufferline.

**Comment by bryant-the-coder** [comment]
Can you send the commit where you did it?

**Comment by zbirenbaum** [comment]
> Can you send the commit where you did it? 

https://github.com/NvChad/extensions/commit/aca0859598b1107a206bf3bc9111d461c006ac84

**Comment by bryant-the-coder** [comment]
interesting. i am trying to make my terminal float like how nvchad does. cant find a way to do it.

**Comment by zbirenbaum** [comment]
> interesting. i am trying to make my terminal float like how nvchad does. cant find a way to do it. 

What do you mean? I haven't implemented floating terminals yet

**Comment by bryant-the-coder** [comment]
Yes i know that. I still need to ask permission to use that code :P

**Comment by zbirenbaum** [comment]
> Yes i know that. I still need to ask permission to use that code :P 

Lmao it's open source. Unless you are making money off of it, copy and paste whatever you want, no permission needed.

**Comment by bryant-the-coder** [comment]
yay

**Comment by bryant-the-coder** [comment]
@zbirenbaum can explain what is does the function in the extension repo do?

**Comment by bryant-the-coder** [comment]
> # 3
> 
> Horizontal terminal eats up the area of nvimtree too, this shouldnt be happening
> 
> ![image](https://user-images.githubusercontent.com/59060246/161196566-e134b7d4-7b76-47b4-a5d7-d4b2135cfa4c.png)

you are trying to mimic vscode settings? we should have a toggle on and off in nvchad like how vscode does hehe

**Comment by siduck** [comment]
> Yes i know that. I still need to ask permission to use that code :P

credit nvchad tho

**Comment by siduck** [comment]
> @siduck floats have been pushed. Default hotkey is alt-i. Was going to do leader-f, but that caused a big delay since f is used for searching for char. Alt-i is the default for most terminal plugins like toggleterm so it fit.

wow it works well!

![image](https://user-images.githubusercontent.com/59060246/162579802-be91a759-d00c-4de9-a508-7f841d24895c.png)
