### ISSUE TITLE
nvchad does not display typed greek letters 

### ISSUE THREAD

**Issue by frostedpenguin** [NvChad/NvChad#929]
**Describe the bug**
nvchad displays greek letters just fine but when I go ahead and type them i get gibberish like this 

`φÎ±φÎ´Î±Î´φσÎ`

Now that does not happen in command mode and it does not happen when I run nvim without config.

Also check health does not show any errors.

**To Reproduce**
type greek letters in insert mode

**Expected behavior**
be able to accurately display greek characters when I am typing.

**Desktop (please complete the following information):**
 - OS : Arch linux 5.16.14
 - terminal : kitty
 - Version of Neovim : 0.6.1

**Comment by siduck** [comment]
does it display without nvchad?

**Comment by frostedpenguin** [comment]
@siduck yes I can write greek in both neovim and vim and in general on my pc. The issue arrises only when I type greek on nvchad in insert mode

**Comment by siduck** [comment]
can you show a screenshot of what it looks in vanilla neovim and nvchad?

**Comment by frostedpenguin** [comment]
@siduck 
![20220403_181646](https://user-images.githubusercontent.com/54059975/161434909-2433b94b-8101-4eee-b0c6-cb069b54f8cc.png)
![20220403_181602](https://user-images.githubusercontent.com/54059975/161434913-a05fe1ec-25d4-44ad-93b4-9cf49b030458.png)

**Comment by siduck** [comment]
how does it look in vanilla neovim? @frostedpenguin

**Comment by frostedpenguin** [comment]
@siduck 
![20220403_182452](https://user-images.githubusercontent.com/54059975/161435219-5a876755-4caf-45b3-88a3-4c7cbe8efa16.png)

**Comment by siduck** [comment]
hmmm very weird! can you try it in lunarvim ?

**Comment by frostedpenguin** [comment]
@siduck 
lunarnvim seems to be working fine too..
![20220404_103751](https://user-images.githubusercontent.com/54059975/161496489-9dbfadde-280c-46d8-b54b-75ce0b8962e4.png)

I dont know whats up but it definitely has to do something with a dependency..  It was working till some days back I then opened nvchad and it just did not work  in both on my computers .. which both use arch

**Comment by frostedpenguin** [comment]
So I did some investigation on the issue and it seems the the problem is caused from the bellow mappings
` 
map("i","ξκ", "<esc>")
map("i","κξ", "<esc>")
`
I had those mapping a while back and everything was working fine ..
I run neovim with the mappings only as config and the problem still persisted, so it really is not a problem with Nvchad but with the newer version neovim.. 
So I am closing this issue here !
