### ISSUE TITLE
^M symbol on null-ls format

### ISSUE THREAD

**Issue by Johnsiras** [NvChad/NvChad#930]
**Describe the bug**
- After formatting you will see a ^M symbol (maybe it depends on each indent)
- Removing the symbols, errors are showing up
- This happens on (wezterm, alacritty, windows terminal)

**To Reproduce**
1. Format the code with `<leader> + fm`
2. Try to remove the ^M symbols on your code

**Expected behavior**
Format the code without errors and weird symbols

**Screenshots**
![WindowsTerminal_QyP4ABwtby](https://user-images.githubusercontent.com/102006493/161496636-0a98bf42-42e6-44d6-adda-ddc27dc461a4.png)
![WindowsTerminal_l9W2GsNbnC](https://user-images.githubusercontent.com/102006493/161496750-b44eae38-8366-4b5d-971e-60199972bf5c.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Windows Terminal
 - 16.1

**Comment by bryant-the-coder** [comment]
OK. I want you to do this ok? Use nightly. They fixed it in nightly

**Comment by Johnsiras** [comment]
> OK. I want you to do this ok? Use nightly. They fixed it in nightly

It worked! Thanks :)

**Comment by bryant-the-coder** [comment]
no prob buddy
