### ISSUE TITLE
Overriding default settings of default plugins via `chadrc`

### ISSUE THREAD

**Issue by besnija** [NvChad/NvChad#939]
**Describe the bug**
It was already repoted with iTerm2 on issues here: https://github.com/NvChad/NvChad/issues/471

**To Reproduce**

1.Clean Install
2.Open neovim
3.Open Telescope
4.See the faulty icon

**Expected behavior**
I am supposed to see the missing magnifying glass icon but sadly I don't so I decided to override it with a different one.
The one that is properly displayed is `f422`, while `f002` isn't. (source: https://www.nerdfonts.com/cheat-sheet, search for "search"). With the `~/.config/nvim/lua/custom/chadrc.lua` config I am supposed to see it overridden, but it isn't.
I've carefully tried to be precise and exact by following an example for `bufferline` noted in videos here https://github.com/NvChad/NvChad/issues/923

Done `PackerCompile`, `PackerSync` and restarted iTerm2 before every `:wq`

**Screenshots**
![Screen Shot 2022-04-09 at 19 58 27](https://user-images.githubusercontent.com/53597440/162586075-5de4d324-ba4d-4299-971c-561f13e40325.png)

**Desktop (please complete the following information):**
 - MacOS Monterey
 - iTerm2
 - Version of Neovim

```
nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

I have tried both of the options by placing the change directly in `chadrc` and by separating it into a file and calling it file.

_**Can't see the icon in here because of markup but there is a magnifying glass there most definitely!**_

---

```
local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.plugins = {
   default_plugin_config_replace = {
     telescope = {
        defaults = {
          prompt_prefix = "   ",
        },
      },
   },
}

return M
```

---

`configs.lua`

```
local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:
local pluginConfs = require "custom.plugins.configs"

M.nvimtelescope = {
        defaults = {
            prompt_prefix = "   ",
        },
}

return M
```
Respective `chadrc` with this method.

```
local M = {}

local pluginConfs = require "custom.plugins.configs"

M.plugins = {
   default_plugin_config_replace = {
      telescope = pluginConfs.nvimtelescope,
   },
}

return M
```

---

**Additional context**

When I place the same change in `~/.config/nvim/lua/plugins/configs/telescope.lua` the change is reciprocated. I'd really need assistance as to where I am making this mistake, as neovim looks flawless and this is the only bug I see and it is annoying 😅 .

Thank you in advance!
Lazar

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/162603329-17c057a9-6ef6-4490-978e-6e39f9d8e7df.mp4

your code snippet works here

**Comment by besnija** [comment]
You are correct it does work, and I found the problem. It was because initially, I was adding a `,` after the closing `}` for `default_plugin_config_replace`. That made it so the `theme` part was invalidated and the file was corrupt.
Then I tried to remove that `theme` snippet all together which also made the file corrupt.
Now after a nights sleep I added it back in without the trailing `,`, and everything works now!

To be more graphic.

```
...
 default_plugin_config_replace = {
     telescope = {
        defaults = {
          prompt_prefix = " Ôê¢  ",
        },
      },
   },
},     <------ this guy was the problem

M.ui = {
   theme = "classic-dark",
}
...
```

Thank you for your work, keep going strong and please don't remove the **custom** part 😭

**Comment by zbirenbaum** [comment]
Since this looks like its been solved I'm gonna go ahead and close it. Please remember to close your post if you have found a solution to your problem! If the solution wasn't provided on the post, feel free to include it in closing notes so that others with the same issue can find how you fixed it.
