### ISSUE TITLE
pls help, it's really cost me a lot of time

### ISSUE THREAD

**Issue by sukai-cheng** [NvChad/NvChad#945]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/35868545/162625484-72861081-6601-4e21-a4d6-2b361ce7a48d.png">

**Comment by sukai-cheng** [comment]
I don't know why  it still fail to download

**Comment by siduck** [comment]
your internet is probably the issue :l

**Comment by zbirenbaum** [comment]
There is no chance this is a NvChad issue, and there was never any reply regarding if internet was the issue, so I am going to close it. Feel free to @ me or reply to this post if the issue has persisted and I will provide some other potential solutions in the case that you have a proxy set up or something.

**Comment by siduck** [comment]
> There is no chance this is a NvChad issue, and there was never any reply regarding if internet was the issue, so I am going to close it. Feel free to @ me or reply to this post if the issue has persisted and I will provide some other potential solutions in the case that you have a proxy set up or something.

 sometimes the internet gets slow and if its slower than what packer requires then plugins wont clone/update and maybe when the internet was good he posted the issue @sukai-cheng is it resolved now?

**Comment by sukai-cheng** [comment]
nope , it's still a problem

**Comment by O1024** [comment]
![image](https://github.com/NvChad/NvChad/assets/132685272/a36a171b-ee94-46f3-b463-47b4f67c89db)
@sukai-cheng set lazy.vim git url format
