### ISSUE TITLE
I can not edit remote files using nvchad

### ISSUE THREAD

**Issue by alohl669** [NvChad/NvChad#947]
**Describe the bug**
With a clean neovim installation, I can edit remote ssh files like using vim traditional method ```nvim scp://user@myserver//home/user/file``` but I can not after nvChad installation, it just open a white/clear page

**To Reproduce**
1. try using neovim without NvChad
2. try using neovim with NvChad

**Expected behavior**
NeoVim open my remote files.

**Screenshots**
Try with vim
https://i.imgur.com/BhHBM51.png
https://i.imgur.com/zSebCNL.png

Try wit clean neovim
https://i.imgur.com/WxY87R2.png
https://i.imgur.com/8juhVky.png

Installing nvchad and try with neovim again
https://i.imgur.com/mrN1DHB.png
https://i.imgur.com/LrIjegT.png
https://i.imgur.com/oxzReNZ.png
https://i.imgur.com/rcS51ne.png

**Desktop (please complete the following information):**
 - Operating System:
  - Client Ubuntu 20.04
  - server debian 11
 - Terminal: terminator with HackNerdFotns
  - https://i.imgur.com/xPzDWro.png
 - Version of Neovim: 0.6.1
  - https://i.imgur.com/ZAAAz3p.png

**Comment by primeapple** [comment]
So this is  because we are disabling the netrw plugin that is needed to edit files via scp. You can enable netrw, but maybe someone has an idea to get it working without?

**Comment by alohl669** [comment]
> So this is because we are disabling the netrw plugin that is needed to edit files via scp. You can enable netrw, but maybe someone has an idea to get it working without?
> 
> Try it out, add the following to your `chadrc.lua`
> 
> ```lua
> M.plugins = {
>    builtins = {
>       "2html_plugin",
>       "getscript",
>       "getscriptPlugin",
>       "gzip",
>       "logipat",
>       "matchit",
>       "tar",
>       "tarPlugin",
>       "rrhelper",
>       "spellfile_plugin",
>       "vimball",
>       "vimballPlugin",
>       "zip",
>       "zipPlugin",
>    }
> }
> ```
> 
> and restart Neovim (maybe also run `:PackerCompile` again.)
> 
> This should enable "netrw", "netrwPlugin", "netrwSettings", "netrwFileHandlers".

I added your lines into ```~/.config/nvim/examples/chadrc.lua``` because is the only file with this name. It doesn't work, even using ```:PackerCompile```, restar shell session, etc.

>but maybe someone has an idea to get it working without?  

Sure, I can use a sshfs mount point. But these methods require installing dependencies on any host node, remembering to mount and unmount these filesystems in each case, etc. Is not a solution, just a risky alternative for a team. Losing an original nvim function is not an upgrade, is a compatibility bug.

**Comment by alohl669** [comment]
Ok, folowing your mention about disabling netrw, eventually I enable it using the follow commands

```
sed -i "s/disable_netrw = true,/disable_netrw = false,/g" .config/nvim/lua/plugins/configs/nvimtree.lua
sed -i 's/"netrw/--\"netrw/g' .config/nvim/lua/core/default_config.lua
```
I don't know why you disable this feature, maybe causes any incompatibility?

**Comment by siduck** [comment]
we use nvimtree mainly so we dont require netrw, and disabling it saves some startuptime

**Comment by alohl669** [comment]
> we use nvimtree mainly so we dont require netrw, and disabling it saves some startuptime

So enable netrw is totally secure, right?

**Comment by siduck** [comment]
> > we use nvimtree mainly so we dont require netrw, and disabling it saves some startuptime
> 
> So enable netrw is totally secure, right?

yep

**Comment by primeapple** [comment]
> I added your lines into `~/.config/nvim/examples/chadrc.lua` because is the only file with this name. It doesn't work, even using `:PackerCompile`, restar shell session, etc.

Please read the documentation: https://nvchad.github.io/config/Custom%20config
The `chadrc.lua` file is used to overwrite the custom configuration. Currently you are changing code that can be updatet with each commit, which WILL cause merge conflicts, that you have to manually resolve.

**Comment by alohl669** [comment]
> > I added your lines into `~/.config/nvim/examples/chadrc.lua` because is the only file with this name. It doesn't work, even using `:PackerCompile`, restar shell session, etc.
> 
> Please read the documentation: https://nvchad.github.io/config/Custom%20config The `chadrc.lua` file is used to overwrite the custom configuration. Currently you are changing code that can be updatet with each commit, which WILL cause merge conflicts, that you have to manually resolve.

Alright, works perfect, and it is not necessary to apply `:PackerCompile`

**Comment by siduck** [comment]
@lijunzh thats because it was moved into options file, u just need to override default options now. check the docs

**Comment by siduck** [comment]
> Thanks for the quick response. This issue is pretty new, so I thought the API has not changed since then.
> 
> By the way,
> 
> > ```lua
> > vim.g["loaded_" .. plugin] = 1
> > ```
> 
> I thought this line will disable the plugin. Do I misunderstand here?

oh yes that was a typo, 0 is correct

**Comment by lijunzh** [comment]
I tried setting those to `0` but it does not work (I still cannot vim scp://). But when I comment out those four line in the `core/options.lua`, it works. I am wondering what is the difference here. 

When commenting out, `let loaded_netrw` return `E121: Undefined variable: g:loaded_netrw`. But when setting them to zero, `let loaded_netrw` returns `g:loaded_netrw   #0`. I don't know if those matter.

**Comment by siduck** [comment]
thats weird, make an issue for this @lijunzh

**Comment by lijunzh** [comment]
@siduck Thanks, I will create an issue now.
