### ISSUE TITLE
custom plugins config file do not load 

### ISSUE THREAD

**Issue by ch4m1gn0n** [NvChad/NvChad#948]
**Describe the bug**
custom plugins config file do not load

**To Reproduce**
1. i try to change which-key config use packer
2. but doesn't work 
3. then i add some nonsense characters in the config file
4. there is still no error. Does this mean it doesn't load the file?

**Expected behavior**
 load the config.

**Screenshots**
![2022-04-11-23:50:41-screenshot](https://user-images.githubusercontent.com/51645204/162780657-08d95b8a-92ab-4cbd-b315-d4de5d556893.png)

**Desktop (please complete the following information):**
 - Operating System: EndeavourOS
 - Terminal: alacritty
 - Version of Neovim: NVIM v0.6.1

**Additional context**

**Comment by siduck** [comment]
did u do packersync?

**Comment by nishan-singh** [comment]
Hi Siduck,

i am new to neovim. I have the same problem. What do you mean by packersync?
It might be a really dumb question, but i didn't get what it means to do packersync.

**Comment by siduck** [comment]
@nishan-singh forget about it, we use lazy.nvim as package manager so is lazy sync command, do read all of nvchad.com 

and in order, also lazy.nvim docs
