### ISSUE TITLE
packer.nvim: Error running config for nvim-treesitter: ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:104: Vim:No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.

### ISSUE THREAD

**Issue by spoilyzer** [NvChad/NvChad#952]
I have that error when I want to use nvim. Any suggestions?

**Comment by bryant-the-coder** [comment]
Install one of this compiler. I expect your on windows. Install gcc, clang is enough

**Comment by spoilyzer** [comment]
I just did it and it's working. Thank you so much for helping me!
