### ISSUE TITLE
Open Directory with Nvim-tree

### ISSUE THREAD

**Issue by primeapple** [NvChad/NvChad#953]
**Describe the bug**
When opening a directory with neovim like `nvim .` we would like to immediately open Nvim-Tree.
This is different from https://github.com/NvChad/NvChad/issues/316 , so I'm opening a new issue

It would be awesome if we can do this via a setting?

**To Reproduce**
1. `nvim .`
2. Empty buffer

**Expected behavior**
Nvim-tree on fullsize is opened

**Additional context**
- We have to somehow not lazy load nvim-tree when opening a directory
- We should be setting `open_on_setup = true` in the `setup` section of nvim-tree

**Comment by primeapple** [comment]
I figured it out by disabling lazy loading for `nvim-tree` as well as setting `open_on_setup = true`. However couldn't this be solved by a nice autocommand, since we are using the mighty packer anyway?

See also: https://github.com/wbthomason/packer.nvim/discussions/877

**Comment by siduck** [comment]
sorry for late reply 

```lua
vim.cmd [[ autocmd BufEnter * if &buftype != "terminal" | lcd %:p:h | endif ]]

```

**Comment by primeapple** [comment]
This is not what I want. This changes the directory to the current path, right? However what I want is to only load `nvim-tree` if we are opening a directory. So this autocmd has to go somewhere in the `cmd` section of the packer `use` section of `nvim-tree`.

**Comment by siduck** [comment]
oh for that you gotta unlazyload nvimtree I think

**Comment by mark-ruddy** [comment]
@primeapple This may not fix it for you but I had a similar problem and fixed it by setting `ignore_buffer_on_setup` to true in nvim-tree

See code at: https://github.com/NvChad/NvChad/issues/621#issuecomment-1123259453
