### ISSUE TITLE
Nix flake integration

### ISSUE THREAD

**Issue by sioodmy** [NvChad/NvChad#956]
Integrating nix flake into NvChad would make it easier for user to install it

**Comment by siduck** [comment]
Idk anything about nix at all so cant help ._.

**Comment by mobsenpai** [comment]
@siduck nixos is getting more popular. Please take a look at this. No pressure tho, just a request.

**Comment by siduck** [comment]
@redyf

**Comment by redyf** [comment]
> @redyf

I'll look into it and try to make a flake.

**Comment by redyf** [comment]
I did some progress but then got stuck, the flake's working but it's not sourcing the plugins directory in lua/plugins. Currently only core is working properly, I'm afraid I'll have to focus on other stuff related to uni and then **maybe** come back to it. Feel free to make a PR if you would like to contribute: https://github.com/redyf/nix-flake-nvchad

**Comment by nonetrix** [comment]
There is a nvchad nixpkgs package but not sure how to use it correctly, can't get it to work. Just installing it as a vim plugin does nothing. I just want something that works with home manager and still let's me add extra config options

**Comment by siduck** [comment]
@nonetrix nvchad 2.5 is just like any other neovim config, think how you would store your own config to nix -_-

**Comment by nonetrix** [comment]
There is no need to be a complete ass about it either, I want to do it in a way that isn't a complete mess and so far I haven't be able to. I have only been able to get this
![image](https://github.com/NvChad/NvChad/assets/45698918/a534ae04-715e-4603-8da7-06696b11e61f)

**Comment by nonetrix** [comment]
I used your advice and it didn't work -_-
![image](https://github.com/NvChad/NvChad/assets/45698918/6a61d79b-1f84-4fd0-9cf8-99b54e494e8a)
![image](https://github.com/NvChad/NvChad/assets/45698918/d6b146f9-40c9-441d-ab19-d284393c2fed)

**Comment by siduck** [comment]
@redyf  :cry:

**Comment by nonetrix** [comment]
Flake works at least, kindaish but it's also breaking in different ways for me. Likely also out of date, since a lot of things have been changed might require redoing some things to be in line with the new config, I will be honest and say I am too dumb to do anything in that direction though
![image](https://github.com/NvChad/NvChad/assets/45698918/8ae972e8-5671-46ad-bc80-8d895b386c52)

**Comment by siduck** [comment]
@redyf just clone the starter repo and see

**Comment by redyf** [comment]
I'll see what I can do, the flake structure will probably need an update considering the new nvchad v2.5 branch 🤔

**Comment by MOIS3Y** [comment]
Hi guys!

I was able to successfully create `flake.nix` for `NvChad 2.5` it contains a package, an overlay and a home manager module.

[nvchad4nix](https://github.com/MOIS3Y/nvchad4nix)

I don't know how useful this is for the NvChad community, but I think it might be useful for Nix users :)

The main advantage is the ability to bring NvChad into your configuration and manage it declaratively
There are several nuances, I described them in README.md
The main drawback is that NvChad v2.5 saves and overwrites some files during execution.
This is a problem for Nix.
I had to do some tricks to get around this limitation.

- NvChad runs through its `nvchad` executable, as if it were a wrapper for nvim.
Under the hood it's just `nvim -u ~/.config/init.lua` but in this case it will have access to all the listed dependencies and there is no need to additionally install packages globally.
- In the home manager module or in the package override, depending on what you like best, you can specify the necessary dependencies (LSP treesitterb etc) and the path to your own configuration.

In general, I added it to my configuration and am using it as intended for now.
I could use some feedback :)

<details>
  <summary>Screenshots</summary>
  <img src="https://github.com/NvChad/NvChad/assets/48302224/a8475aed-e86d-41f3-8385-349623c1ea97">
  <img src="https://github.com/NvChad/NvChad/assets/48302224/0d552bfe-aae7-4b81-8c57-18bd1a07495c">
  <img src="https://github.com/NvChad/NvChad/assets/48302224/59d20dd9-af9f-4ca5-9f38-ae268d119c61">
</details>

It is also possible to run nvchad without installing it locally
!!! Run if you do not have your own configuration!!!

```console
nix run github:MOIS3Y/nvchad4nix/v2.5#nvchad
```

@redyf I could use some advice. Maybe something doesn't look right? Any ideas on how to improve?
The big problem I had was with `flake.nix` I couldn't use flake-utils they lose the HM module
I had to write my own slightly ugly functions.

**Comment by redyf** [comment]
> Hi guys!
> 
> I was able to successfully create `flake.nix` for `NvChad 2.5` it contains a package, an overlay and a home manager module.
> 
> [nvchad4nix](https://github.com/MOIS3Y/nvchad4nix)
> 
> I don't know how useful this is for the NvChad community, but I think it might be useful for Nix users :)
> 
> The main advantage is the ability to bring NvChad into your configuration and manage it declaratively There are several nuances, I described them in README.md The main drawback is that NvChad v2.5 saves and overwrites some files during execution. This is a problem for Nix. I had to do some tricks to get around this limitation.
> 
>     * NvChad runs through its `nvchad` executable, as if it were a wrapper for nvim.
>       Under the hood it's just `nvim -u ~/.config/init.lua` but in this case it will have access to all the listed dependencies and there is no need to additionally install packages globally.
> 
>     * In the home manager module or in the package override, depending on what you like best, you can specify the necessary dependencies (LSP treesitterb etc) and the path to your own configuration.
> 
> 
> In general, I added it to my configuration and am using it as intended for now. I could use some feedback :)
> Screenshots
> 
> It is also possible to run nvchad without installing it locally !!! Run if you do not have your own configuration!!!
> 
> ```
> nix run github:MOIS3Y/nvchad4nix/v2.5#nvchad
> ```
> 
> @redyf I could use some advice. Maybe something doesn't look right? Any ideas on how to improve? The big problem I had was with `flake.nix` I couldn't use flake-utils they lose the HM module I had to write my own slightly ugly functions.

Hi MOIS3Y, you did an AMAZING work! I just tried your solution and it worked flawlessly. Give this man an award @siduck :1st_place_medal:

**Comment by siduck** [comment]
I dont understand any of this nix stuff but @MOIS3Y 's effort will be showed on the install page 

the 5th btn there would be nix, what do u think?

![image](https://github.com/NvChad/NvChad/assets/59060246/9250132e-d53d-4236-990e-25831ade5a66)

**Comment by nonetrix** [comment]
If they feel like maintaining it maybe should be added to Nvchad organization

**Comment by redyf** [comment]
> I dont understand any of this nix stuff but @MOIS3Y 's effort will be showed on the install page 
> 
> the 5th btn there would be nix, what do u think?
> 
> ![image](https://github.com/NvChad/NvChad/assets/59060246/9250132e-d53d-4236-990e-25831ade5a66)
> 

That would be great imo 🙌

**Comment by MOIS3Y** [comment]
@siduck of course you can add this as another installation option)

```console
nix run github:MOIS3Y/nvchad4nix/v2.5#nvchad
```
It will work for everyone without exception who has nix with enable [flake feature](https://nixos.wiki/wiki/Flakes) installed on their system.
The only thing is if the user already has neovim configured, as I said earlier, his current files from `~/.config/nvim` will be moved to the backup folder nearby.

If the use case for NvChad with Nix is ​​in demand by the community, you can add a repository to the organization, I'm all for it) Maybe someone will have an idea on how to improve it.
The Nix staff I wrote is fairly simple and easy to maintain, unless version 2.5 changes dramatically in the future.

The only thing I don’t like is the fact that one way or another we need to copy the configuration from `/nix/store` to `~/.config/nvim`
If only NvChad could run the startup configuration from any directory (currently it's only `~/.config/nvim`) and didn't write anything to its files, but wrote overlays and created a .lock file somewhere in` ~/.cache/nvchad ~/.cache/ nvim `
This would solve all the shortcomings. User configuration based on `starter` would simply be simlinked to ~/.config/nvim
-- --
Oh yeah, I completely forgot to mention somewhere, MesonInstall will not work, this is a fundamental limitation of Nix.
In fact, it is not needed by those who use nix; all dependencies (node, git, treesitter, LSPservers e.t.c) are added as `extraPackages`

**Comment by siduck** [comment]
@MOIS3Y  ~/.config/nvim isnt needed, if you know the neovim's nvimappname feature you can use that

**Comment by MOIS3Y** [comment]
@siduck  I meant this:

<details>
  <summary>Screenshots</summary>
  <img src="https://github.com/NvChad/NvChad/assets/48302224/83ec03f8-9419-41bc-8db0-9d89e9fa508d">
  <img src="https://github.com/NvChad/NvChad/assets/48302224/508419a3-db72-47c9-9996-e4730abb894d">
  <img src="https://github.com/NvChad/NvChad/assets/48302224/e84a8c59-c449-415d-9fe5-7e951cfb21fa">
</details>

- In the first case there will be an error
- In the second case everything is fine

To be honest, I don’t understand why the import doesn’t work in this place, the lua traceback is very poor

-- --
The standard behavior of home-manager is when it simply creates a symbolic link `/nix/store/longhash-nvchad2.5/*` `~/.config/nvim/*` to where we need it
If we do this, then during initialization there will be the same error, since the files are actually located in store

If you are wondering why the launch occurs not through `nvim` as standard, but through the `nvchad` wrapper:
everything is simple here in fact, it is somewhat similar to flatpak, nix does not follow FHS in the usual sense, it puts absolutely all packages in `/nix/store`. In our case neovim treesitter git lua-language-server etc
We can’t reach them, but nvchad can, when building nix, it will wrap it and point it to all the listed dependencies in `extraPackages`

Like this
```sh
#! /nix/store/306znyj77fv49kwnkpxmb0j2znqpa8bj-bash-5.2p26/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/m9nqvj3xqqrzanpg9g2awkh8rc987qq6-neovim-0.10.0/bin'':'/':'}
PATH='/nix/store/m9nqvj3xqqrzanpg9g2awkh8rc987qq6-neovim-0.10.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/swdgw9aj85l2d983s4b1vziwb2i1p7xi-tree-sitter-0.22.5/bin'':'/':'}
PATH='/nix/store/swdgw9aj85l2d983s4b1vziwb2i1p7xi-tree-sitter-0.22.5/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/cn26v027m7mwl785f03wlvraqrm7dilw-ripgrep-14.1.0/bin'':'/':'}
PATH='/nix/store/cn26v027m7mwl785f03wlvraqrm7dilw-ripgrep-14.1.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
# ... etc
exec -a "$0" "/nix/store/d8wk4hiqm84iiz8fi5jqxy39xdsi6idq-nvchad-2.5/bin/.nvchad-wrapped"  "$@"
```
What benefits does this provide?
You can have several different versions of the same package, and you can roll back from a bad update.
You can configure the system once and replicate it to all your hosts.

I could wrap nvim  like this, but then it wouldn't install from [nixpkgs cache](https://cache.nixos.org/)
Building nvim would come from the source code locally, which is stupid)

**Comment by siduck** [comment]
ah i dont understand much of this nix stuff :nerd_face: , just let me know when its ready enough to be put on NvChad org!

**Comment by redyf** [comment]
> @siduck of course you can add this as another installation option)
> 
> ```
> nix run github:MOIS3Y/nvchad4nix/v2.5#nvchad
> ```
> 
> It will work for everyone without exception who has nix with enable [flake feature](https://nixos.wiki/wiki/Flakes) installed on their system. The only thing is if the user already has neovim configured, as I said earlier, his current files from `~/.config/nvim` will be moved to the backup folder nearby.
> 
> If the use case for NvChad with Nix is ​​in demand by the community, you can add a repository to the organization, I'm all for it) Maybe someone will have an idea on how to improve it. The Nix staff I wrote is fairly simple and easy to maintain, unless version 2.5 changes dramatically in the future.
> 
> The only thing I don’t like is the fact that one way or another we need to copy the configuration from `/nix/store` to `~/.config/nvim` If only NvChad could run the startup configuration from any directory (currently it's only `~/.config/nvim`) and didn't write anything to its files, but wrote overlays and created a .lock file somewhere in`~/.cache/nvchad ~/.cache/ nvim` This would solve all the shortcomings. User configuration based on `starter` would simply be simlinked to ~/.config/nvim
> 
> Oh yeah, I completely forgot to mention somewhere, MesonInstall will not work, this is a fundamental limitation of Nix. In fact, it is not needed by those who use nix; all dependencies (node, git, treesitter, LSPservers e.t.c) are added as `extraPackages`

you can make Mason.nvim work on nixos by adding .local/bin to PATH:
```nix
  # Add support for .local/bin
  home.sessionPath = [
    "$HOME/.local/bin"
  ];
```
or by doing it in your shell config file (.zshrc, .bashrc, etc) manually :
```shell
export PATH=$PATH:~/.local/bin/
```

**Comment by siduck** [comment]
@MOIS3Y  I can create a repo where you can do these nix changes i.e convert the starter repo for nix, is your repo ready :thinking:

**Comment by sioodmy** [comment]
Wow, that's impressive. Good job, @MOIS3Y.

**Comment by MOIS3Y** [comment]
@siduck yes, you can add.
I checked the work on four of my devices, everything is fine.
I haven't tested @redyf 's Meson option, it looks like it will work (doesn't meson put packages in /usr/local?). This could be added as a separate option in the future. Or I can add it now and test it

> i.e convert the starter repo for nix

Probably for users who do not use Nix, the files associated with it will be confusing.
On the other hand, it may look more holistic, now I just fetch starter, and Nix pulls this repository as src

**Comment by redyf** [comment]
@MOIS3Y Mason uses .local/share/nvim/mason/ for storing binaries, packages, registries, etc. At least on NixOS

**Comment by siduck** [comment]
@MOIS3Y  https://github.com/NvChad/nix, send a PR

**Comment by MOIS3Y** [comment]
@siduck I sent a PR

----

Guys, I got an idea, as you remember, if we use nvchad4nix, we need to exec it as `nvchd`.
We cannot just exec  nvim because if we have just neovim installed on our system, it will not find the extraPackages that we passed to the programs.nvchad.extraPackages option.

So there are two options to solve the problem:
- I can write in README.md that if you want to use the usual nvim, just pass to the standard module:
```nix
# HM standart module:
 programs.neovim = {
   enable = true;
   extraPackages = config.programs.nvchad.extraPackages;
 };
```
This way neovim will see all the dependencies that we passed to nvchad

- I can modify the `programs.nvchad.neovim` option (now it accepts the package if the user uses some custom neovim then nvchad will use it)
```nix
programs.nvchad.neovim = {
  enable = true;
  package = pkgs.neovim;  # or whatever the user wants
};
```
In the second option, the module under the hood (not explicitly) will simply do what I suggested in the first option, only I will add `lib.mkForce` there in case the option value is already set somewhere in the configuration.

I'm not sure which is better, probably the first option gives the user more control. On the other hand, the second option will do everything itself out of the box.

@redyf @sioodmy  what do you think?

**Comment by redyf** [comment]
> @siduck I sent a PR
> 
> Guys, I got an idea, as you remember, if we use nvchad4nix, we need to exec it as `nvchd`. We cannot just exec nvim because if we have just neovim installed on our system, it will not find the extraPackages that we passed to the programs.nvchad.extraPackages option.
> 
> So there are two options to solve the problem:
> 
>     * I can write in README.md that if you want to use the usual nvim, just pass to the standard module:
> 
> 
> ```nix
> # HM standart module:
>  programs.neovim = {
>    enable = true;
>    extraPackages = config.programs.nvchad.extraPackages;
>  };
> ```
> 
> This way neovim will see all the dependencies that we passed to nvchad
> 
>     * I can modify the `programs.nvchad.neovim` option (now it accepts the package if the user uses some custom neovim then nvchad will use it)
> 
> 
> ```nix
> programs.nvchad.neovim = {
>   enable = true;
>   package = pkgs.neovim;  # or whatever the user wants
> };
> ```
> 
> In the second option, the module under the hood (not explicitly) will simply do what I suggested in the first option, only I will add `lib.mkForce` there in case the option value is already set somewhere in the configuration.
> 
> I'm not sure which is better, probably the first option gives the user more control. On the other hand, the second option will do everything itself out of the box.
> 
> @redyf @sioodmy what do you think?

Amazing work! Personally I believe the first option is better :+1:

**Comment by MOIS3Y** [comment]
Guys my comment
```nix
# HM standart module:
 programs.neovim = {
   enable = true;
   extraPackages = config.programs.nvchad.extraPackages;
 };
```
unfortunately it won’t work, the standard module doesn’t collect dependencies the way I do it, unfortunately it doesn’t find lua and python dependencies accurately. If you look at the source code, there is additional processing `finalPackage`
I should have checked this first

For now, the workaround is still an alias, but there are some other ideas on how to automate this.
I will discuss the module in [NvChad/nix](https://github.com/NvChad/nix) so as not to lose information.
