### ISSUE TITLE
How to make default plugin stick to a specific version?

### ISSUE THREAD

**Issue by neevek** [NvChad/NvChad#957]
After updating, the prompt says `numToStr/Comment.nvim` has a breaking change commit, and it indeed fails to work after that. Now I want to make this plugin stick to previous commit, how to do that?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/163716210-3ad1b37f-b242-4302-8a2a-d3135ce3e36b.png)

**Comment by neevek** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/163716210-3ad1b37f-b242-4302-8a2a-d3135ce3e36b.png)

I know this setting, I just don't know how to set this for default plugins of NvChad.

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#remove--redefine-plugins

then you can define this plugin in chadrc too

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/163921801-b3fb235e-4fd0-410a-904b-f6ab333bcae5.mp4

Comment.nvim works in 0.7 so this isnt a nvchad issue
