### ISSUE TITLE
Error while creating lua chunk / Not a publisher's command: PackerSync

### ISSUE THREAD

**Issue by uSebazz** [NvChad/NvChad#958]
I have this bug when installing nvChad, I did everything in the guide, I installed packer to be able to do packerSync and it doesn't work either, the truth is I don't know what's wrong, it only works plug
![image](https://user-images.githubusercontent.com/90474850/163836409-48651a5b-37f0-412f-852f-eff52b6858bd.png)

**Comment by siduck** [comment]
i hope you are using neovim 0.6.1

**Comment by uSebazz** [comment]
> i hope you are using neovim 0.6.1

Hmm, let me see

**Comment by uSebazz** [comment]
> i hope you are using neovim 0.6.1

![image](https://user-images.githubusercontent.com/90474850/163843681-50d7e7c0-456a-4c48-86b9-78b22d04b229.png)
No

**Comment by uSebazz** [comment]
anyone can help me?

**Comment by siduck** [comment]
use 0.6.1 and see if there's any error. 0.7 is not supported at the moment.

**Comment by uSebazz** [comment]
> use 0.6.1 and see if there's any error. 0.7 is not supported at the moment.

I changed to version 0.6.1 and nothing changed, I still get the same error and the packer does not work, no idea what the error is.

**Comment by siduck** [comment]
are u using vanilla nvchad

**Comment by uSebazz** [comment]
> are u using vanilla nvchad
> 

I managed to get it to work, but on another OS, thanks for the help <3
