### ISSUE TITLE
Alignment issue for statusline style - slant

### ISSUE THREAD

**Issue by dnjmn** [NvChad/NvChad#959]
**Describe the bug**
status line alignment issue for style - slant in right hand side

**To Reproduce**
1. Go to chadrc in custom dir
2. set M.plugins.options.statusline.style = slant
3. reload / or re enter vim
4. there will be an alignment issue rignt hand side.

not sure weather it should look like this or not... (not in my opinion)
<img width="540" alt="Screenshot 2022-04-19 at 8 37 04 AM" src="https://user-images.githubusercontent.com/49618740/163912766-dad8b65d-bf28-4418-babf-e2a8a2b383d0.png">

**Desktop (please complete the following information):**
 - MacOS 12.3.1
 - Alacritty
 - 0.7

**Comment by siduck** [comment]
did you set a nerd font?

**Comment by dnjmn** [comment]
yes... i am using `family: JetBrainsMono Nerd Font Mono`

**Comment by siduck** [comment]
did u try  JetBrainsMono Nerd Font only?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/163919852-6686120b-9489-4b1d-b713-f1312aa4f68b.png)
works fine with st , idk about other terminnals :(

**Comment by dnjmn** [comment]
> did u try JetBrainsMono Nerd Font only?

yes i tried... and it is working. But will it not work for mono fonts? and is this a terminal issue?

**Comment by siduck** [comment]
> > did u try JetBrainsMono Nerd Font only?
> 
> yes i tried... and it is working. But will it not work for mono fonts? and is this a terminal issue?

yes looks like a terminal issue. btw why mono fonts? they do more bad then good imo
