### ISSUE TITLE
leader key invalid

### ISSUE THREAD

**Issue by onefishum** [NvChad/NvChad#960]
**Describe the bug**
Under Ubuntu 64 20.04.4 LTS, the leader key cannot be used. Set vim g. Mapleader = '' is also not possible

**Desktop (please complete the following information):**
 - Operating System
Ubuntu64 20.04.4 LTS 
 - Terminal
gnmoe terminal 3.36.2
 - Version of Neovim
Noevim v0.6.1

**Comment by siduck** [comment]
space is the leader key

**Comment by siduck** [comment]
oh , idk how to help with this

**Comment by onefishum** [comment]
vim.g.mapleader = " "

function map(mode, shortcut, command)
	vim.api.nvim_set_keymap(mode, shortcut, command,{ noremap =true, silent =true})
end

map("n", "<leader>q", ":q <CR>")

Under neovim, it can be written like this, nvchad can't.

**Comment by siduck** [comment]
you can write it in custom/init.lua file

**Comment by siduck** [comment]
You seem new to nvchad so I suggest reading through the docs https://nvchad.github.io/config/walkthrough

**Comment by criticic** [comment]
i was facing a similar problem, turns out i was not doing it fast enough.

do the keypresses individually, and try to do it in less than a second

**Comment by siduck** [comment]
> i was facing a similar problem, turns out i was not doing it fast enough.
> 
> do the keypresses individually, and try to do it in less than a second

yes

**Comment by onefishum** [comment]
> **Describe the bug** Under Ubuntu 64 20.04.4 LTS, the leader key cannot be used. Set vim g. Mapleader = '' is also not possible
> 
> **Desktop (please complete the following information):**
> 
> * Operating System
>   Ubuntu64 20.04.4 LTS
> * Terminal
>   gnmoe terminal 3.36.2
> * Version of Neovim
>   Noevim v0.6.1

**Comment by javaddev** [comment]
> space is the leader key

Ah, thanks, I thought it was backslash :)
