### ISSUE TITLE
Optional <Tab> mapping for cmp

### ISSUE THREAD

**Issue by lijunzh** [NvChad/NvChad#961]
Is it possible to make the following code block optional?

https://github.com/NvChad/NvChad/blob/1c8a677024179b966ba2ab420e6edbe8dfda146b/lua/plugins/configs/cmp.lua#L40-L57

The usage case is to make `cmp` and `Copilot` coexists. You can achieve this by using the `custom` directory with the following code 

```
local cmp = require("cmp")

M.cmp = {
	mapping = {
		["<C-p>"] = cmp.mapping.select_prev_item(),
		["<C-n>"] = cmp.mapping.select_next_item(),
		["<C-e>"] = cmp.mapping.close(),
		["<CR>"] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Replace,
			select = true,
		}),
		["<Tab>"] = cmp.config.disable,
		["<S-Tab>"] = cmp.config.disable,
	},
}
```

However, it will require `cmp` pre-installed. For the first time setup, you will have to comment out these line of code since `require("cmp")` will fail. If we can make the above code in `NvChad` optional, we don't need to manually disable it in the customized plugin config and thus no need to `require("cmp")`.

**Comment by siduck** [comment]
@lijunzh very sorry for late reply, v2.0 might be a big release and new easy + clean custom config implementation, it'll take a while tho! but for now you override cmp

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-default-config-of-a-plugin

**Comment by lijunzh** [comment]
@siduck No worries. I saw you were business with #922
I will wait till your v2.0 is stable and look back at the config again. I have a working version for now.

**Comment by siduck** [comment]
@lijunzh check the pinned issue

**Comment by siduck** [comment]
as per new syntax

![image](https://user-images.githubusercontent.com/59060246/165589850-2fc035dd-00f2-4246-8e67-6522f070cc9a.png)

**Comment by lijunzh** [comment]
@siduck Thank you very much for letting me know.
