### ISSUE TITLE
Telescope error, not an editor command

### ISSUE THREAD

**Issue by pathakraul** [NvChad/NvChad#964]
Ubuntu 22.04
NVIM v0.6.1

I did the PackerSync and started getting this error
```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim:E492: Not an editor command: Telescope find_files                          
Please check your config for correctness                                                                                                                                 
Press ENTER or type command to continue
```

No Telescope command working, Telescope itself not working

```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim:E492: Not an editor command: Telescope                                     
Please check your config for correctness                                                                                                                                 
Press ENTER or type command to continue
```

I dont know if this is Telescope plugin issue or its integration with nvchad

I also installed the nvchad from scratch but same issue

**Comment by siduck** [comment]
very weird :l

**Comment by ilyazub** [comment]
Same here. I've installed NvChad from scratch for the first time and received this error.

```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim:E492: Not an editor command: Telescope find_files                                                                    
Please check your config for correctness
```

Looks similar to https://github.com/NvChad/NvChad/issues/198.

**Comment by Pasqat** [comment]
Kind of similar error for me too. I tried to do a fresh install of Nvchad main and customless repo but nothing worked, I to don't know if it is an issue with Telescope.
Tomorrow I will try to copy/paste the error I get

**Comment by pathakraul** [comment]
I dont see this issue once i upgraded the neovim to 7.0.

I will let others also to confirm this before closing this issue

**Comment by juniorupf** [comment]
Same problem here in neovim v0.6 it desapeared when I updated to neovim v0.7.
