### ISSUE TITLE
nvim-tree separator

### ISSUE THREAD

**Issue by PoSayDone** [NvChad/NvChad#969]
I've got a separator between nvim-tree and main window, but there are no separator on screenshots. How to disable it?

**Screenshots**
![image](https://user-images.githubusercontent.com/29358657/164989624-9c3a659c-da96-4c9e-9c50-bf7c203c62e0.png)

**Comment by siduck** [comment]
[not a              ](https://github.com/kyazdani42/nvim-tree.lua/issues/1142)

**Comment by PoSayDone** [comment]
> [kyazdani42/nvim-tree.lua#1142](https://github.com/kyazdani42/nvim-tree.lua/issues/1142)

okay, I've tried to roll back on nvim 0.6.1, but when I try `hi NvimTreeVertSplit guifg=none guibg=none ctermfg=none ctermbg=none`, it's still have a color

**Comment by siduck** [comment]
it wont work like that, use our current config with 0.6. It should work

**Comment by PoSayDone** [comment]
> it wont work like that, use our current config with 0.6. It should work

Thanks!

**Comment by siduck** [comment]
as this isnt a nvchad issue, im closing this. (neovim v0.7 issue)

**Comment by siduck** [comment]
@PoSayDone 
https://github.com/kyazdani42/nvim-tree.lua/pull/1219

do packersync and update nvchad leader uu
