### ISSUE TITLE
I cannot get a dashboard

### ISSUE THREAD

**Issue by Samisafool** [NvChad/NvChad#973]
**Describe the bug**
I cannot get a dashboard, every time I try it does nothing

**To Reproduce**
My chadrc

```lua

local M = {}

M.plugins = {
  status = {
    dashboard = true,
    alpha = true,
  }
}

return M
```

**Expected behavior**
I would get a dash

**Screenshots**
![image](https://user-images.githubusercontent.com/59611020/165471552-423537be-83fc-4c9b-b581-2fc457b3bd59.png)

**Desktop (please complete the following information):**
 - Operating System Arch Linux
 - Terminal Konsole
 - Version of Neovim v0.7.0

**Additional context**
I am new to neovim so apologies if I get it wrong

**Comment by siduck** [comment]
u dont need dashboard = true, its just alpha =true

**Comment by Samisafool** [comment]
I tried that already, nothing again. Do I need to press a certain button to get it?

**Comment by siduck** [comment]
no

**Comment by Samisafool** [comment]
Hmm interesting, I just cloned the repo to .config/nvim and added that rc.

(btw other configs in the rc work fine)

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/165473602-9eddad01-6961-46bd-a254-c69320ac2a88.mp4

**Comment by Samisafool** [comment]
Oh!

I don't think it's written that you have to PackerSync after enabling, maybe I missed it somewhere?

Also how do you get that file tree?

**Comment by siduck** [comment]
oh another guy asked the same issue in our discord server and he already did packersync, so i thought that was you here ._.

**Comment by gamesky** [comment]
alpha plugin not active:

```lua

["goolord/alpha-nvim"] = {
  disable = true,
}

```

**Comment by siduck** [comment]
> alpha plugin not active:
> 
> ```lua
> ["goolord/alpha-nvim"] = {
>   disable = true,
> }
> ```

Do it disable false, the new syntax for custom config got pushed recently

**Comment by gamesky** [comment]
so if i want to active alpha plugin, must be:
```lua
-- custom/plugins.lua
["goolord/alpha-nvim"] = {
  disable = false,
}
```

**Comment by siduck** [comment]
yep, cuz by default we have disable = true, and this packer option uninstalls the plugin 

so by default its 

["goolord/alpha-nvim"] = {
  disable = false,
  config = stuff
}

and when you do 

["goolord/alpha-nvim"] = {
  disable = false,
}

your table overrides the default one!

**Comment by alannungaray** [comment]
Hi there I just google it my problem and this answer comes a little bit old by the breaking changes so I'll put the next link to solve it 
https://nvchad.github.io/config/Custom%20config#enable-dashboard
