### ISSUE TITLE
nvterm spawned terminals dont hide

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#977]

**Comment by zbirenbaum** [comment]
What do you mean they don't hide? Toggling hides them.

**Comment by siduck** [comment]
toggling does but those spawned by leader + v / h. Try it yourself 


leader + v 
leader + x 

now press
leader + W

it'll show no terminal buffers open

**Comment by zbirenbaum** [comment]
The issue wasn't that they weren't being hidden. The issue is that the telescope extension relies on a ton of information not set by default for terminals. I changed it to use nvterm, since it was currently using nvchad specific info anyways, and now its better.

**Comment by zbirenbaum** [comment]
> > The issue wasn't that they weren't being hidden. The issue is that the telescope extension relies on a ton of information not set by default for terminals. I changed it to use nvterm, since it was currently using nvchad specific info anyways, and now its better.
> 
> ![image](https://user-images.githubusercontent.com/59060246/166079220-baf12d98-083c-4407-91f3-e9f33b7169c8.png)
> 
> Ig we need some functionality to hide terminal buffer in close_buffer function thinking

You haven't synced.

**Comment by siduck** [comment]
i did!

**Comment by zbirenbaum** [comment]
What did you do to cause that

**Comment by siduck** [comment]
> toggling does but those spawned by leader + v / h. Try it yourself
> 
> leader + v leader + x
> 
> now press leader + W
> 
> it'll show no terminal buffers open

.

**Comment by zbirenbaum** [comment]
Thats exactly what I did to check it works before pushing.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/166079404-2f398db4-4ce3-4843-bd8a-cbd94cc1159b.mp4

**Comment by zbirenbaum** [comment]
Have you pulled down my changes in NvChad

**Comment by siduck** [comment]
yes I did

**Comment by siduck** [comment]
is your nvchd uptodate tho?

**Comment by zbirenbaum** [comment]
Sorry I forgot to push the changes in utils

**Comment by siduck** [comment]
btw you need to format before you push!

**Comment by pwnwriter** [comment]
@siduck @zbirenbaum I'm having the same issue in my setup, It opens the buffer of terminal but doesn't hide.

like we do in scratchpad xD

**Comment by siduck** [comment]
@pwnwriter make a video of the issue
