### ISSUE TITLE
hide / restore file buffers

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#979]
- Ctrl + q  to close all types of buffers
- leader + x to hide terminal & file buffers
- leader + W to pick terminal buffers ( done already )
- leader + B to pick file buffers

**Comment by gamesky** [comment]
If i open nvim-tree ,and open two file buffers , then `leader+x`  ,the command not working

**Comment by siduck** [comment]
open a new issue for this @gamesky

**Comment by zbirenbaum** [comment]
@siduck btw disable is not the same as remove...  I really wish you had kept the remove section in chadrc.

**Comment by zbirenbaum** [comment]
Instead of fixing this i'm now having to port my config

**Comment by zbirenbaum** [comment]
And now it no longer accepts existing keys... @siduck this is a sizable regression.

**Comment by zbirenbaum** [comment]
@gamesky @siduck fixed. Don't open a issue.

**Comment by gamesky** [comment]
My nvim-tree is on the right, and the close command is not working very well. I have update nvchad and packersync

**Comment by zbirenbaum** [comment]
> My nvim-tree is on the right, and the close command is not working very well. I have update nvchad and packersync

What do you mean by "very well"

I set the mapping to also close buffers of type "nofile" which nvimtree is, and it worked fine for me.

**Comment by gamesky** [comment]
If i open nvim-tree(right side) ,and open two file buffers , then leader+x in a file buffer window , the focus will be on the tree window

**Comment by zbirenbaum** [comment]
> If i open nvim-tree(right side) ,and open two file buffers , then leader+x in a file buffer window , the focus will be on the tree window

That is expected behavior on Neovim's part. If you want it to do otherwise please open a feature request describing the behavior you want and I'll consider implementing it when I have time.

**Comment by siduck** [comment]
> @siduck btw disable is not the same as remove... I really wish you had kept the remove section in chadrc.

hmm didnt know but it uninstalls the plugin locally and doesnt run its config so thats all matters ig

**Comment by gamesky** [comment]
maybe 
```lua
:bd! | :bnext
```

**Comment by zbirenbaum** [comment]
> > @siduck btw disable is not the same as remove... I really wish you had kept the remove section in chadrc.
> 
> hmm didnt know but it uninstalls the plugin locally and doesnt run its config so thats all matters ig

This is false. Lets suppose I don't want any of the defaults to interfere with my config. If I do remove, my config is the only thing read. If I do disable, my config doesn't work. My old implementation of merging plugins was carefully designed for this reason.

**Comment by siduck** [comment]
wym doesnt work? can you give any example so i could test :thinking:

**Comment by siduck** [comment]
if the plugin appears in both the users and the defaults then both merge

**Comment by zbirenbaum** [comment]
> if the plugin appears in both the users and the defaults then both merge

This is the problem. Everything from the defaults to be ignored. You shouldn't have to explicitly override every key to have your own config for a plugin.

**Comment by zbirenbaum** [comment]
Also, the user has to add pointless lines to their plugin config with disable just to get rid of default plugins, which is counter intuitive.

**Comment by zbirenbaum** [comment]
@siduck for example:
If the user wants to load a plugin on a keystroke, but the defaults have the plugin load via an event like "bufenter" the final config passed to packer will have both, which will cause the plugin to load on BufEnter since it occurs first (I believe. Even if this is false the issue remains)

**Comment by siduck** [comment]
> > if the plugin appears in both the users and the defaults then both merge
> 
> This is the problem. Everything from the defaults should be ignored. You shouldn't have to explicitly override every key to have your own config for a plugin.

no, everything from default shouldnt be ignored, if the user wants to change one option from the default plugin options like cmd = {} , events etc then he can just  use 
```lua
["a/b"] = {
    cmd = stuff
}
````

there are like barely 4-6 lines in a plugin definition, let em do some work!

**Comment by zbirenbaum** [comment]
> > > if the plugin appears in both the users and the defaults then both merge
> > 
> > 
> > This is the problem. Everything from the defaults should be ignored. You shouldn't have to explicitly override every key to have your own config for a plugin.
> 
> no, everything from default shouldnt be ignored, if the user wants to change one option from the default plugin options like cmd = {} , events etc then he can just use
> 
> ```lua
> ["a/b"] = {
>     cmd = stuff
> }
> ```
> 
> there are like barely 4-6 lines in a plugin definition, let em do some work!

When you have hundreds of plugins, it adds up.

**Comment by siduck** [comment]
ive barely seen anyone redefining plugins tho, most just override the default table.

**Comment by zbirenbaum** [comment]
> ive barely seen anyone redefining plugins tho, most just override the default table.

Dude its three lines of code, and one additional table entry in chadrc. I'll add it the second you give the ok.

**Comment by siduck** [comment]
> > ive barely seen anyone redefining plugins tho, most just override the default table.
> 
> Dude its three lines of code, and one additional table entry in chadrc. I'll add it the second you give the ok.

cut the talk, show me the code :rocket:

**Comment by siduck** [comment]
also it'd be easy to redefine 90% of the plugins as we dont have events for all the plugins and it'd just be easy to change the events to bufwinenter/bufread to fix the issue in user table

**Comment by zbirenbaum** [comment]
@siduck I just realized, if user defined plugins aren't defaulted to, what is the point of the override table in M.plugins

I just pushed a solution to "removals" branch

**Comment by zbirenbaum** [comment]
Buffer showing is a builtin function of telescope. That's its primary purpose. A link to the source for the builtin for it is in our telescope terminal showing extension. This should be closed.
