### ISSUE TITLE
Major issues with new plugin merging methods

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/NvChad#982]
Table deep extend doesn't remove keys that don't exist in the merging table. The previous implementation was that if the plugin config existed in the user's table, their config would be used exclusively. This was much better.

Also disable != remove, the lack of remove feature is also a serious regression.

For reference, my startup time is now **_50% worse_** after the update and porting my config. Somehow even wiping the core config's init.lua doesn't fix it completely, though it helps. I don't know what to do about this.

@siduck

**Comment by siduck** [comment]
![2022-04-28-145054_1920x1080_scrot](https://user-images.githubusercontent.com/59060246/165721328-d8ca0a2e-f930-42a2-abea-baca29afcc38.png)

tested on live void linux iso 

new custom = 20 ms 
old custom = 18 ms 

probably cuz i didnt lazyload nvterm

**Comment by siduck** [comment]
can you give an example of the keys dont exist in merging table?

**Comment by siduck** [comment]
```lua 
 [ "abc/xyz"] = {
    cmd = "bruh"
 }
 
 merging table (wrong way)
 
  [ "abc/xyz"] = { }
 
 
 do this instead 
 
  [ "abc/xyz"] = {
    cmd = false
 }
 
 ```

**Comment by zbirenbaum** [comment]
I lazy load nvterm and colorizer, so that's not it. I also made sure nvterm is absurdly lightweight so pretty much nothing other than a keymap definition is done at startup.

**Comment by siduck** [comment]
hmm, but i didnt find any difference in the startuptime from previous / new custom implementation

**Comment by siduck** [comment]
anyways the remove feature was added before so i'll close this
