### ISSUE TITLE
Let users know when *BREAKING CHANGES* occur before running :NvChadUpdate

### ISSUE THREAD

**Issue by LeonHeidelbach** [NvChad/NvChad#984]
When running :NvChadUpdate as of now users are not notified about breaking changes that might completely brick their setup when pulling changes from main. Since most people actually use their editor to fix their config when those changes occur, it would be nice to be able to abort the update process and to prepare for a manual maintenance run rather than having to go back and manually resetting to a working commit.

This script I wrote nicely packaged into NvChad could be a solution to also specifically list all breaking commits. You can then decide on a syntax on how to mark those commits using a list of keywords:
```bash
#!/bin/sh

KEYWORDS=("BREAKING" "MAJOR")
REMOTE_HEAD=$(git ls-remote --heads origin main | cut -f1)
CURRENT_HEAD=$(git rev-parse HEAD)

# Create grep pattern
GREP=$(printf "%s|" "${KEYWORDS[@]}")
GREP=${GREP::-1}

# Fetch new commits silently
git fetch --quiet

# Filter all commits that are newer than the current HEAD by the given keywords
BREAKING_COMMITS=$(git log --oneline --no-merges --decorate --color --date=short \
    --pretty='format:%ad: %C(green)%h%C(reset) %C(red)%s%C(reset)'               \
    $CURRENT_HEAD..$REMOTE_HEAD | grep -iE "$GREP")

# Check if breaking changes occured
if [ -z "$BREAKING_COMMITS" ]; then
    # Print message and continue with update
    echo -e "\e[32mNo breaking changes\e[0m"
    # Continue with update procedure
else
    # Print warning message and list all commits that contain breaking changes
    # that are newer than the currently checked out commit.
    echo -e "\e[31mThe following breaking changes occured:\e[0m\n"
    echo "$BREAKING_COMMITS" | sed 's/^/    /'

    # Ask for confirmation to continue with update procedure.
    echo -e "\n\e[31mAre you sure you want to continue?\e[0m"
    read -p "[y/N] " -n 1 -r

    # Continue depending on user input
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo -e "\n\n\e[32mContinuing with update...\e[0m"
        # Continue with update procedure
    else
        echo -e "\n\n\e[31mAborting update!\e[0m"
        # Abort update procedure
        exit 1
    fi
fi
```

**Comment by LeonHeidelbach** [comment]
Since there has not been any feedback from the maintainers regarding this issue, I have simply implemented this feature myself and created a [PR](https://github.com/NvChad/extensions/pull/13). I have also included a check that will not fetch on every `:NvChadUpdate` but rather compare the remote HEAD with the currently checked out HEAD and only fetch changes if the HEADs differ. This will make checking for updates quicker. The prompt will look like this:

![NvChadUpdate_Breaking_Change_Check](https://user-images.githubusercontent.com/55194243/166058629-743e9fdb-8e29-4246-a00d-f08be00d8d06.png)

**Comment by siduck** [comment]
@Akianonymus  add this up

**Comment by Akianonymus** [comment]
Why not merge if it works ? I am very busy these days, no time to review.

**Comment by FelixKratz** [comment]
I believe using packers snapshot feature could also aid some of the pain wirh breaking changes from that side: https://github.com/wbthomason/packer.nvim/pull/370. Implementing this with the new breaking changes monitor it could be possible to freeze the last known working version and always revert to that version if something has bricked.

**Comment by siduck** [comment]
@FelixKratz already on v2.0 feature list! I'll implement it after may 2

**Comment by itsmeboy0** [comment]
> Currently commits that contain the following keywords in their message will be marked as "potentially breaking":
> 
> * break
> * fix
> * bug
> * merge
> * squash

If that's the case, it would be better if this project were to strictly follow the [Conventional Commit](http://conventionalcommits.org/) guidelines for every commit.
![image](https://user-images.githubusercontent.com/75471378/166132919-ca7db70d-cae5-4317-bc1e-72495b6bb171.png)

**Comment by siduck** [comment]
@FelixKratz snapshot feature was already added yesterday, check recent commits

**Comment by LeonHeidelbach** [comment]
> > Currently commits that contain the following keywords in their message will be marked as "potentially breaking":
> 
> > 
> 
> > * break
> 
> > * fix
> 
> > * bug
> 
> > * merge
> 
> > * squash
> 
> 
> 
> If that's the case, it would be better if this project were to strictly follow the [Conventional Commit](http://conventionalcommits.org/) guidelines for every commit. The rules make more sense there and there is existing tooling to help enforce this such as [commitlint](https://github.com/conventional-changelog/commitlint).
> 
> ![image](https://user-images.githubusercontent.com/75471378/166132919-ca7db70d-cae5-4317-bc1e-72495b6bb171.png)
> 
> 

@itsmeboy0 as agreed upon with @siduck I have changed the keywords to mark commits as "breaking" only if they match the regular expression `/breaking.*change/gi`. Alongside with some other changes as detailed in this pending [PR](https://github.com/NvChad/extensions/pull/15). He mentioned that he will be using those keywords if any breaking changes occur in the future. You will as of the aforementioned PR also be able to see a list of all commits before being prompted to update even if no breaking changes were found. I found that I like to see what happened in the repo before pulling the changes. "New commits" and "breaking changes" (if any were found) are found are now two separate sections.

**Comment by FelixKratz** [comment]
> @FelixKratz snapshot feature was already added yesterday, check recent commits

Thanks! You are doing very nice work here
