### ISSUE TITLE
Nvim switching to nvimtree after closing a buffer when nvimtree's opened

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#989]
https://github.com/NvChad/NvChad/issues/976#issuecomment-1112916636
 
new close_buffer behaviour 

![new](https://user-images.githubusercontent.com/202344/165894624-48dc4aaf-593c-4930-85eb-119f08967ce8.gif)

old

![old](https://user-images.githubusercontent.com/202344/165894645-95f9a92f-16dc-4c24-a6f7-62bb39736845.gif)

**Comment by kmiasko** [comment]
@siduck It's working properly. Thank you!
