### ISSUE TITLE
Override or unmap default plugin mapping

### ISSUE THREAD

**Issue by jtuz** [NvChad/NvChad#994]
**Is your feature request related to a problem? Please describe.**
According to [NvChad documentation](https://nvchad.github.io/config/Custom%20config) the way to change plugin mappings is performing the following instructions:

for instead for this default plugin mapping:
`map("n", "<leader>th", "<cmd> :Telescope themes <CR>")`
```lua
-- lua/custom/chadrc.lua
M.plugins = {
  user = {
     ["nvim-telescope/telescope.nvim"] = {
      setup = function()
         -- load default mappings first
         require("core.mappings").telescope()

         -- then load your mappings
         local map = require("core.utils").map
         map("n", "<leader>ts", "<cmd> :Telescope themes <CR>")
      end,
     }
  }
}
```
but this tweak only provide an option without overriding the default mapping, so then this may cause conflicts with other custom mappings.
Ways to reproduce this issue:
Change default plugin mapping for any other, then run `:Telescope keymaps`,  taking the example above, in the filter field type `themes` now there are two available options.

**Describe the solution you'd like**
Override or unmap the default plugin mapping

**Comment by jtuz** [comment]
![Screen Shot 2022-04-29 at 17 59 26](https://user-images.githubusercontent.com/1232719/166078789-0c958a3c-be92-4e3b-ae70-84488179441a.png)
![Screen Shot 2022-04-29 at 17 59 01](https://user-images.githubusercontent.com/1232719/166078793-21cfa7f8-9653-428e-a9a0-742fa0969585.png)

**Comment by siduck** [comment]
```lua
         map("n", "<leader>th", "<cmd> :Telescope  <CR>") -- example
```
