### ISSUE TITLE
Status line is no longer customizable

### ISSUE THREAD

**Issue by jtuz** [NvChad/NvChad#995]
**Describe the bug**
Status line is no longer customizable due the last breaking changes set as default the [only available option:](https://github.com/NvChad/NvChad/blob/83fe03455e4bab192f1b522101c52a8e5d4a6027/lua/plugins/configs/statusline.lua#L52) 

**To Reproduce**
1. Edit `lua/core/default_config.lua` or `lua/custom/chadrc.lua`
2. set this options: 
```lua
M.plugins = {
   override = {},
   remove = {},

   options = {
      packer = {
         init_file = "plugins.packerInit",
      },
      lspconfig = {
         -- setup_lspconf = "", -- path of lspconfig file
         setup_lspconf = "custom.plugins.lspconfig",
      },
      statusline = {
         style = "block", -- this should set statusline to block option
      },
   },

   -- add, modify, remove plugins
   user = {},
}

```
**Expected behavior**
Change statusline style

**Desktop (please complete the following information):**
 - Manjaro
 - Kitty
 - Version of Neovim: 0.7.0

**Additional context**
Also this is happening for other option like `lspconfig`

**Comment by siduck** [comment]
yes its not by chadrc, only thing you can do is change the separators. Or you have to change the whole config

**Comment by siduck** [comment]
oh wait i misread!
