### ISSUE TITLE
reduce startuptime

### ISSUE THREAD

**Issue by siduck** [NvChad/NvChad#996]
lazyloaded nvim-base16 after packer and its almost 2x faster now
 
 
![image](https://user-images.githubusercontent.com/59060246/166078095-e98e6be1-8448-4112-bcf8-635f609022dd.png)

 
 But it makes the highlights load a lil slow, would be cool too find a workaround!

https://user-images.githubusercontent.com/59060246/166077925-42c3d9a2-5cce-4984-bb61-5e3099b74427.mp4

**Comment by zbirenbaum** [comment]
How are you lazy loading

**Comment by bryant-the-coder** [comment]
I am also wondering. Maybe he is using BufWinEnter?

**Comment by siduck** [comment]
> How are you lazy loading

see those lil nvim windows

**Comment by zbirenbaum** [comment]
> > How are you lazy loading
> 
> see those lil nvim windows

They are identical.

**Comment by zbirenbaum** [comment]
Ok even now though, I can't reproduce these results. I'm also confused af as to how your startup time is 20ms as vanilla nvchad on my very very fast desktop running arch is closer to 35.

**Comment by siduck** [comment]
what are your specs? @zbirenbaum . Also that startuptime was with my custom config added . My custom config speed's the same as vanilla nvchad. i lazy load a lot!

**Comment by zbirenbaum** [comment]
> what are your specs? @zbirenbaum . Also that startuptime was with my custom config added . My custom config speed's the same as vanilla nvchad. i lazy load a lot!

My my desktop is r9 3900x 2080ti 64gb 3200mhz ram. Rn install on normal ssd but I have an nvme it used to be on and even then not much faster. 

I also lazy load everything so idk what it could be

**Comment by siduck** [comment]
wow thats a lot!

my system's a bit old and 8gb ram+ hdd
![image](https://user-images.githubusercontent.com/59060246/166090378-60b12041-8c28-4eff-8fa6-ec2a6fb8d5be.png)

**Comment by zbirenbaum** [comment]
> wow thats a lot!
> 
> 
> 
> my system's a bit old and 8gb ram+ hdd
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/59060246/166090639-e50a8458-2241-445a-a493-65e38a33d944.png)
> 
> 
> 
> 

Your laptop is actually newer than mine though 😂

**Comment by siduck** [comment]
I suppose the startuptime is fine for now, so lemme close this.
