### ISSUE TITLE
Autocommand in `custom/init.lua` to enable `syntax` not working

### ISSUE THREAD

**Issue by asher-gh** [NvChad/NvChad#999]
This used to work in previous config
```lua
vim.cmd("au FileType latex,markdown setlocal  syntax=markdown spell spelllang=en_gb")
```
But doesn't after the new config structure. 

`:verbose set syntax?` gives
```
  syntax=
        Last set from Lua
```

**Comment by siduck** [comment]
I dont think it has nothing to do with the custom config implementation, as the custom/init.lua was left untouched

**Comment by siduck** [comment]
maybe it doesnt work cuz of v0.7?

**Comment by siduck** [comment]
there's latex , markdown treesitter parsers too

**Comment by asher-gh** [comment]
I've them installed it's because with `spell`, it shows spell corrections in code blocks. setting `syntax=markdown` resolves that issue.

**without syntax**
<img width="939" alt="Screenshot 2022-04-30 at 15 30 51" src="https://user-images.githubusercontent.com/74317567/166109757-2ab2fc0d-6f6c-4e3e-9390-89fb85b5a3bd.png">

**with syntax**
<img width="945" alt="image" src="https://user-images.githubusercontent.com/74317567/166109789-1c065059-a56f-40ca-99c3-a8cbc9ea84fb.png">

**Comment by asher-gh** [comment]
also
